### ISSUE TITLE
Enable client modding by default and the menu should have to tab to enable/disable installed clientmods

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#10038]
## Problem
CSM loading on servers is disabled by default. This creates extreme headaches for game modes which use client mods. 

Also the configuration file is extremely over complicated for the normal player since a user usually wants to load all client mods installed regardless. Also, this configuration file is also extremely useless for that reason. So it should not even be part of the engine in the first place.

## Solutions

1.) Create a client mods tab which a user can easily push a button to enable a grayed out list of client mods currently installed in the client mods folder. Flipping this button could also toggle the setting "enable_client_modding" so the average user can easily have a gui visual to set these settings.

2.) Allow all client mods to load regardless and let the server tell the client if the mods can load since that's how it works regardless.

## Alternatives

Send client mods to the client from the server and load automatically.

## Additional context

A week of pulling my hair out.

**Comment by rubenwardy** [comment]
Clientside modding is still experimental and unsupported, which is why it's not exposed to users and is disabled by default

**Comment by paramat** [comment]
Is the request of this issue referring to the 'enable_client_modding' clientside setting or the 'load client mods' 'csm restriction' sent from a multiplayer server? Or both?

> CSM loading on servers is disabled by default. This creates extreme headaches for game modes which use client mods.

CSM has no meaning for multiplayer servers or distributed games yet because Server-Sent CSM (SSCSM) (which is the actual intended primary purpose of CSM) has not been implemented yet.
> Alternatives
Send client mods to the client from the server and load automatically.

It was intended from the beginning that this will happen, and this might progress soon, sfan5 has mentioned they might work on it.

Client-provided CSM was done first as a development step only (and unfortunately then became usable in MT, we made a big mistake), then work on completing SSCSM stopped and has had very little progress for 3 years.

The 'csm restrictions' sent from a multiplayer server disables client mod loading by default, this is absolutely essential due to the harm to a server client-provided CSMs can cause due to cheating. There was a big controversy 3 years ago with lots of very unhappy server owners. So the default of the 'load client mods' 'csm restriction' cannot be changed.

Once SSCSM is implemented, the clientside 'enable_client_modding' setting must disable CSM by default because the client must always opt-in to CSMs sent from a server, for security reasons.

So we cannot enable CSM by default in either way.
However, your request for a CSM tab is possible.

**Comment by jastevenson303** [comment]
Paramat you make it sound like a person who is able to launch and maintain a server is unable to disable CSM.

Consequentially, one who is not so inclined, is now forced to figure out how to enable CSM, which takes a lot of digging and work to achieve.  Games like Crafter are suffering because of your limited and negative views of CSM, in my honest opinion.

**Comment by paramat** [comment]
> you make it sound like a person who is able to launch and maintain a server is unable to disable CSM.

Nothing i wrote implies that, i know that server owners restrict CSM and mentioned that above.
> one who is not so inclined, is now forced to figure out how to enable CSM, which takes a lot of digging and work to achieve.

It is a little messy i agree, but for good reason, as i explained above.
> Games like Crafter are suffering because of your limited and negative views of CSM

I do not oppose oilboi's wish to make CSM easier to manage, nothing i wrote states or impies that, see the last line of my previous comment.
In the PR, which i do not oppose, it is the other core devs who are asking for the tab to be less prominent, not me.
I do not have sole control of CSM development as you imply, on my own i am powerless. CSM is the way it is due to consensual action by multiple core devs and for good reasons.

You make a very poor attempt at trying to blame this on me alone, which shows your already obvious obsessive and irrational grudge.
But, thanks for making an actual argument this time.

**Comment by jastevenson303** [comment]
Wow you edited that four times?!
