### ISSUE TITLE
Implementing shadows and light culling in the existing lightmap compilator

### ISSUE THREAD

**Issue by MirceaKitsune** [minetest/minetest#10067]
I had an idea I wanted to bring up. I may even attempt implementing it myself if I can, but would first like confirmation from the developers that it's considered an acceptable approach so I don't work for nothing.

So... lights and shadows. Proper lighting is a feature that's been long desired by many players. RealBadAngel and I looked into implementing dynamic shadowing years ago, with the intent of adding support for realtime OpenGL light sources. This is of course an extremely difficult task and will probably never be done for the Minetest engine.

Then it suddenly occurred to me that to implement satisfactory shadows, realtime lights may not be needed at all: The existing lighting system could be able to do something that looks almost as good! The code responsible for updating and baking the vertex colors might require just one simple check to compile correct shadowing.

Today I better noticed that when you place a torch, there's currently no code to detect light intersections in any form. The torch will illuminate everything within its radius: This means that if you place it on the back of a wall, it lightens the other side of that wall too and shines right through it. For some reason I never fully realized this, and it was the "wait a minute" moment that got me to ponder my solution. There's already a calculation for Ambient Occlusion and I'm thinking of doing something similar to get shadows.

![Screenshot_20200619_213035](https://user-images.githubusercontent.com/825418/85170696-7199a080-b276-11ea-82bb-b22ef03644c2.png)

I pondered whether each time the light level gets calculated for a source at every vertex, a ray can be traced from that vertex to the origin of the emitter node. For sunlight it should be traced toward the direction of the sun... as that might be harder the initial implementation could just trace it upward by default. If a solid node is in the way and there isn't a clear path between the torch and the lit point, the influence of this torch is ignored at that vertice. Or to simulate some bounce lighting, it could just be drastically reduced instead of completely ignored (eg: light * 0.9).

Needless to say I'd only implement this as a setting, and it would be up to the team whether to default it or leave it off as to not change existing behavior... no functionality would be modified irreversibly or broken. Only worry that comes to mind is performance; In a cave with countless lava nodes for example, each vertex will have to trace a ray toward every lava node within its radius... could this be too costly perhaps? None the less I think this can look very pretty if done right.

I'm eager to hear your thoughts and if such an algorithm would be accepted for the lighting system. If yes, pointers to where in the code I should look for this would be appreciated, I forgot the exact location of the light baking functions involved. Also is there a builtin method to trace a ray between two points and check if they hit a non-transparent surface... perhaps read that surface's transparency value to decide how much to dim the light by?

**Comment by TheTermos** [comment]
> The torch will illuminate everything within its radius: This means that if you place it on the back of a wall, it lightens the other side of that wall too and shines right through it.

Actually, it goes around, not through, build a wall wide n tall enough and you'll see.

This lighting system is actually pretty clever, you might think of it as extremely low resolution raytracing capable of generating shadows etc. - it's just sometimes difficult to notice because of  short lighting range and limited number of light levels.
I believe there are still unexplored possibilities within it, and I'd rather see it being expanded upon.

**Comment by MirceaKitsune** [comment]
@TheTermos Good to know all that, thanks for the info! Perhaps it might only use some tweaks and playing with, though it still sounds like what I particularly had in mind isn't possible yet.

What I'm thinking of is sharper shadows: If one corner of a node's surface isn't within direct reach of the light source but another is, you could have part of the face at 0.8 lighting intensity with another part at 0.2. Having strongly different mixtures between opposite vertices would allow for smooth but definitive (straight or diagonal) shadows to be cast.

Say you have a torch on the side of a 1 x 1 node pillar; It would be neat if when you look at the floor, you see the clear diagonal lines extending toward the back of the pillar where the light doesn't reach, with the area behind it being much darker in general. Or during sunrise / sunset, getting a lower light level on nodes hidden behind the sun by a wall (based on sun direction). This feels doable without radical changes to the lighting system though it may still require some work.

**Comment by MirceaKitsune** [comment]
So I dug a bit deeper into this: Using the minetest.conf setting `ambient_occlusion_gamma = 0.5` I can better see what the existing ambient occlusion system does. It seems to do about HALF of what I was thinking: Per-vertice directional shadowing exists to some extent, but it only goes one node deep... a node won't continue casting a shadow alongside a length of wall, nor does face direction appear to be properly accounted for. Another big issue as far as realism goes is that walls behind the node the torch is on are as bright as those in front of it.

![Screenshot_20200620_014009](https://user-images.githubusercontent.com/825418/85184689-65730a80-b299-11ea-9e63-1a3952f2988e.png)

I wonder if messing with the AO alone could achieve the results I want, though I don't wish to break it. What I'm thinking of might be a different check of its own however. In any case the change seems to go in src/client/mapblock_mesh.cpp line 190: `getSmoothLightCombined`

**Comment by TheTermos** [comment]
> What I'm thinking of is sharper shadows: If one corner of a node's surface isn't within direct reach of the light source but another is, you could have part of the face at 0.8 lighting intensity with another part at 0.2.

This is basicly what's happening already in smooth lighting mode, adjacent vertices share same color, but different corners of the same node can be colored differently, and that is a part of the problem.

Imagine a node is between two other nodes that are lit with the same value, the node in the middle must be lit just the same as the other two because it shares all vertices with them.
That's why in smooth mode single nodes cast no shadow, shadow of a 2x2 platform's  is faint and diamond shaped and back of a 1 node pillar looks like it's lit.

And that's why I never use smooth lighting mode, it's bland, boring and does nothing for me.
Try turning it off, and even if you end up not liking it, you might want to play for a while with non smooth lighting and gamma turned down to get a feel how light propagation works.

**Comment by MirceaKitsune** [comment]
Flat lighting shows the system a bit better yes. Though it too doesn't feel like it culls properly and adjusts face brightness the right way, and it's even more fake in appearance.

I took another screenshot from a more complex environment to better show what I'm looking at: A torch placed on a wall is illuminating the ground on the hill above it just as much as the blocks in front, when normally that area should be shadowed and only receiving a fraction of bounce lighting. It makes the light looks fake and lacking in detail, that's what I'm hoping to find a solution to.

![Screenshot_20200620_020848](https://user-images.githubusercontent.com/825418/85203154-639a5d00-b314-11ea-9d47-5481a8d34493.png)

**Comment by TheTermos** [comment]
> A torch placed on a wall is illuminating the ground on the hill above it just as much as the blocks in front

Actually not just as much, the ground above is darker, but too little to notice. Set gamma to 0.5 or lower and you'll see. The default light curve is wrong imo.

You probably want to look at light propagation algorithm first, it governs how node light affects neighbor nodes and works the same regardless of vertex light mode. I'm sure it can be improved.

**Comment by MirceaKitsune** [comment]
That seems to be correct: I get much more realistic results with `display_gamma = 0.5`

![Screenshot_20200621_002726](https://user-images.githubusercontent.com/825418/85211914-6027c580-b356-11ea-8072-78bbb6b644f3.png)

I'd be tempted to suggest defaulting it to that, but this also makes caves lit by torches slightly darker overall. It does seem like at least the light curve could use some tweaking.

**Comment by paramat** [comment]
> I pondered whether each time the light level gets calculated for a source at every vertex, a ray can be traced from that vertex to the origin of the emitter node.

> Only worry that comes to mind is performance; In a cave with countless lava nodes for example, each vertex will have to trace a ray toward every lava node within its radius... could this be too costly perhaps?

Yes, performance would be a huge problem due to multiple light sources. I might be wrong but i suspect it would be completely impractical to do a line of sight calculation from every node to an unlimited number of light sources within 16 nodes.
When RBA and hmmmm were discussing hardware lighting, they were only considering doing that for a very limited number of light sources, possibly only sun and moon only.

> I'd be tempted to suggest defaulting it to that, but this also makes caves lit by torches slightly darker overall. It does seem like at least the light curve could use some tweaking.

Certainly we cannot make MT significantly darker by altering display_gamma or the light curve. It is inherently difficult to get a good light spread in MT due to the mapblock size limitation, so everything is carefully tuned to maximise brightness and light spread. This is why the light curve is the way it is, it used to have a faster light falloff around a light source, but the result was MT was much darker than currently.

Besides, messing with display_gamma or the light curve is a completely wrong way to try to acheive what you want, as they have nothing to do with creating shadows or culling light.

Altered display_gamma , or an altered light curve, makes nodes darker at a particular distance from a light source, but is not what you want because nodes with a line of sight to a light source are darkened by the same degree as nodes that do not have a line of sight to a light source, as you can see on the screenshot in the previous post.

Shadows and light culling should be done properly with code written for the purpose.

**Comment by hecktest** [comment]
The current flood filling behavior isn't incorrect, it's an approximation of radiosity. Light will bounce around, and on average, it'll flood spaces with a gradual falloff.
This approach is sometimes used to simulate global illumination even in the "big" engines, and it certainly doesn't look bad.

If shadows are added in some way (for instance by remembering direction and using it somehow when spreading), indirect lighting will need some sort of boost to maintain a similar scene brightness. Even then, it might just end up looking inferior.

Making it a client setting would make it even harder to maintain a consistent art direction, just like tonemapping and smooth lighting already do. Excessive options are usually a sign of indecisiveness on the developer's part.

**Comment by MirceaKitsune** [comment]
@hecktest Yeah, looking better at the system it seems to be more correct than I thought at first glance. The light spreading system I mean; At first I pondered changing how it works to simulate shadowing, but I think what I want is to separately implement shadows on top of it as an independent thing.

Obviously this issue and approach refers to using vertex colors for the job. Unless it were possible to generate a shadow-mapping projection texture (without using actual light sources), which would be preferred and more correct but opening other cans of worms. A shader might just be the way in the end, but this is getting beyond my knowledge.

**Comment by hecktest** [comment]
Shadow mapping isn't really that great, there are issues with it such as aliasing, shadow acne, or the artifacts introduced by workarounds to those. Artistically it doesn't fit any of the games being made with this engine, it's too fuzzy of an effect for something this crisp; sharp stencil-like shadows are what I'd rather have, or something that's per-node. Shadow mapping everything in the engine globally would be too opinionated of a change, and again, letting the client decide is always a problem because you don't know which case to prepare your art for.

One way I could see this working without breaking much is by separating direct and indirect light into their own buffers. Use a directional ray-march for direct light (A lookup table of forking paths can be precomputed for the biggest possible sphere), then flood indirect from that using the current manhattan flood fill. This would of course require twice as much data as the current 8 bit light.
With some tuning, it could actually work well for the general case. It would also allow for a tiny bit of overbright/HDR information, useful for post-processing shaders when those are finally implemented.

**Comment by MirceaKitsune** [comment]
@hecktest Fair point. My original idea was to cast a ray from each vertice to the light source(s) illuminating it, and if a solid is detected in the way darken that vertex by a given amount to only let some bounce lighting through (eg: light *= 0.25).

Main problem with this, aside from potential performance issues, is the light spreading algorithm doesn't appear to keep track of the original light source: It spreads from position to position and only accounts for direct neighbors. So this would probably have to be done as a separate test, by detecting all torches within 16 nodes of the vertice and casting a ray to each one to see if it hits a solid, darkening based on how many obstructions are detected out of the total lights. In an area with a lot of lit nodes, such as a lava cave, this could be rather slow depending on how expensive ray-tracing is.

**Comment by hecktest** [comment]
All scenes would become darker overall if you did that.
I'm afraid we'll just have to live without shadows until someone comes up with a completely new light propagation mechanism. Something that can occlude, but still doesn't require processing the same node more than once.

**Comment by Moth-Tolias** [comment]
off topic, but @MirceaKitsune what texture set is that? it's really pretty.

**Comment by MirceaKitsune** [comment]
@Moth-Tolias It's from the Mineclone game.

**Comment by numberZero** [comment]
> detecting all torches within 16 nodes of the vertice and casting a ray to each one

That will be rather expensive (unacceptably expensive for the server which needs to calculate lighting too, for mob spawning for example) and still, the shadow edge will be axis aligned as there are no intermediate vertices on the node face (it's a bit more complicated actually as a quad consists of 2 triangles but more or less arbitrary directions aren't possible anyway).

**Comment by paramat** [comment]
The suggested idea is not possible, so closing to not stress the core devs with issue count, but everyone is welcome to continue discussion here.
