### ISSUE TITLE
Don't remove breath

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10098]
OK, this is a weird issue, because it suggests to *not* do something.

I suggest to NOT remove breath, but to keep it. At least for now.

Why this issue? Because @rubenwardy has been continously pushing hard against breath, and wants to remove it.

@rubenwardy wants to remove breath from the engine and replace it with … something (probably Lua). Rubenwardy did not go into specifics yet.

Arguments about why breath should be removed (and their rebuttal):

* Lua implementation has not more lag
    * Wrong, because the code that detects whether you are inside a liquid is client-side. How can that be done in Lua without adding overhead?
* It's possible to do in Lua, so we don't need engine breath
    * We have a lot of features that could be theoretically be cloned in Lua, but it's not always a good idea to do so, especially if client knowledge is required *fast*. This kind of discussion often only revolves around that something can be done *in theory* in Lua, but that's rarely what this is truly about. What is important is not if something is doable in Lua, but if something is *practical to do* in Lua. That point is often ignored. And I think at this stage it is absolutely NOT practical to remove breath
* Engine breath is too gameplay-specific and forces a specific type of breath mechanic.
    * It should be explained which other breath mechanics would be thinkable. I can't think of that many breath gameplay mechanics, to be honest
    * The main limitation of current engine breath is the time interval at which you lose or gain breath, but this is definitely not something that can't be solved with engine
    * Even with this limitation, engine breath is perfectly functional, it is not proken, it has worked perfectly across many games and mods. It's just that you think it's lacking in features
* Lua breath gives more flexibility
    * Yes. This is absolutely true
    * But I argue that this flexibility is mostly an illusion for breath. There aren't really many sensible ways to do breath, because it always boils down to the same rules: Reduce breath when you're drowning, add breath when not
    * The hardcoded breath interval could be overcome by extending engine breath
    * Yes, Lua will be more flexible, but I cannot think of enough alternative implementations that warrant such flexibility (and by extension, a major refactor)
    * To be more convincing, you should present in detail examples for alternative breath gameplay rules that you want to enable. The more alternatives you present, and the more they deviate from the “default breath rule”, the better.
    * I also want to note the push to remove engine breath came exclusively from core devs, NOT modders
    
If you still want to remove breath, I strongly urge you to consider this:

1) Definitely do NOT just rip out breath from the engine and then walk away. That would be like saying to modders: “Lol, breath is gone now, most of your games and mods are broken now, figure out yourselves how to fix it. :P”. This would be terrible. In other words: Modder opinions should be considered because this is a major change

2) Do NOT remove breath as long no PROVEN alternative exists. It is not enough if there is an alternative only in theory. If you push for Lua-only, you have to provide evidence that a Lua-only implementation is a viable and PROVEN replacement for engine breath exists. A viable Lua replacement must:

* Have the same features as engine breath
* Have not significantly worse lag than engine breath (this should be measured)

This is because for such a major change, you definitely want to get it right, and not end up with a worse result

3) Removing breath is highly disruptive. A TON of games and mods depend on it. It can't be removed before 6.0.0. Rubenwardy agrees. But even then you will have massive breakage across basically all games, and it will be a lot of work to repair the damage. Because of this, a lot of thought should be put into backwards-compability or API-compability. I can't stress enough that removing breath without consideration for backwards-compability will absolutely break havoc in Minetest, so it will be extremely important. Remember that no matter how “easy” you will make it for games to fix themselves, some game authors might have been long gone when 6.0.0 drops, so some games will not “make it”.

4) Consider a generous deprecation period instead aggressively removing it after 1 release

----

Possible alternatives to remove breath:

* Keep engine breath, but make it more configurable, by adding features:
    * Custom interval at which breath increases/decreases (currently, intervals are hardcoded)
    * Other things? (I don't have other ideas)
* Mixed engine and Lua implementation
    * Let the engine figure out the “hard” / low-level stuff, like detecting whether the player is “with the head” inside a node, and then expose this info to Lua somehow
    * Let Lua do the high-level stuff, especially the gameplay rules
    * ↑ That way, we can avoid the extra lag that a pure Lua-only implementation would have
    * Keep `set_breath` and `get_breath` to keep disruption low, but maybe allow Lua to interpret the *meaning* of the breath value on its own
    * I see no need to make `set_breath` and `get_breath` overridable or to force Lua to add its custom field. The advantage of `set_breath` nd `get_breath` is standardization. I would hate to see 1000 incompatible names for breath
    * Optionally fall back to default breath behavior to avoid breaking games
    
    
----

Since this is a “negative” issue (it's about NOT adding something), I suggest to close this issue when the discussion is over and a decision was made.

**Comment by rubenwardy** [comment]
> Wrong, because the code that detects whether you are inside a liquid is client-side. How can that be done in Lua without adding overhead?

Wrong, **the code for breath is entirely server-side**. There is no breath code on the client. If it cannot be done efficiently in Lua, then we should give up on Lua completely. Note that breath checking also only happens every 0.5-1 second!

> but it's not always a good idea to do so, especially if client knowledge is required fast.

Doesn't need to be fast. It is already done on the server, so Lua won't make it any slower to the client.

> replace it with … something (probably Lua). Rubenwardy did not go into specifics yet.
> --
> What is important is not if something is doable in Lua, but if something is practical to do in Lua. That point is often ignored. And I think at this stage it is absolutely NOT practical to remove breath

200 lines of Lua: https://github.com/oilboi/Crafter/blob/master/mods/drowning/init.lua?rgh-link-
date=2020-06-24T07%3A49%3A31Z

**Comment by Wuzzy2** [comment]
Oops, so I must have jumped to conclusions too quickly by skimming over the code … So efficiency as counter-argument flies right out of the window. What about the rest?

---

But has this code been audited and tested for speed? What is needed is an officially-approved drop-in replacement for engine breath. One that is as close to current engine-breath as possible in order to keep disruption at an absolute minimum. I'd also prefer if this is released as a standalone mod that is made specifically for the purpose of demonstrating an alternative, not as part of a game that might change at any time without warning.

**Comment by sfan5** [comment]
Since backwards compatibility for breath needs to be preserved anyway I don't see a pressing need to remove it entirely and/or move it from C++ to Lua.

**Comment by hecktest** [comment]
What business does the engine have deciding where my character's head actually is? Depending on the animation, the head's position might be off by as much as 2 nodes. Even the engine's idea of "swimming" is questionable at best, you are swimming even if only your feet are touching water. You too can be like Jesus, halle-bloody-lujah.
Why shouldn't the engine also force everyone to use a hunger system as well? It's "inefficient" to do it in lua, after all. Let's make it a 0-20 scale, updated at a hardcoded interval and according to hardcoded conditions (Make some _groups_ for it! Everybody loves _groups_), with a built in hud bar for it, so that the engine has one more missing texture to complain about. But hey, we can now predict it client side 100ms ahead of the server, who still has the final word on whether we live or die. _Yay._

I've seen people do crazy things like set breath to 9999999 each frame just to make sure this doesn't ever interfere with their system. (Not the best way to handle it.) This is a huge problem with hardcoded systems; even if you kill them to replace with yours, you're never 100% sure whether some part of it doesn't remain active to come back and haunt you when you least expect it. And it's still always ticking and eating CPU cycles at best.

In fact, even _health_, dying and respawns are questionable, and I do not use those. (They're in fact buggy. Zombie clients still happen.)
What I do is, I intercept all the relevant callbacks and tell the engine "no, do not apply damage". This still eats a nontrivial amount of CPU. For good measure, everything is flagged as immortal as well. Stdout still tells me that a player with 20 hp has "punched" some entity with 10 hp, even though that is absolutely not what happened in the game. Pressing F5 and pointing at something still tells me that I'm looking at a GenericCAO with a certain amount of hitpoints belonging to certain "groups". (What does the client need this for? And hey, that means we're wasting bandwidth on it.)
Engine documentation is littered with concepts of "crafting", "eating", "armor", "punching", "tool", "digging" (by scraping a node for some time, decided by an arcane hardcoded formula, until it pops off), "groups" (which sometimes handle things that should be flags, and that's the only reason to pay attention to them). All these things that I'll never use, yet I have to read about them in order to at least effectively contain them. And you always have to waste precious head-space on this stuff whenever coding anything that could potentially touch those systems, including when you're fixing the engine itself. All of this to provide functionality that is so trivial that it could be the subject of a tutorial. _Wow, thanks a lot, engine._

**Comment by runsy** [comment]
No remove already features, please...

**Comment by hecktest** [comment]
Not remove, but move. This is just a minetest_game feature that hasn't been moved where it belongs yet.

**Comment by Wuzzy2** [comment]
> What I do is, I intercept all the relevant callbacks and tell the engine "no, do not apply damage".

Just force-set `enable_damage` to `false` with `minetest.settings:set_bool`. Damage (and breath) will be off. For entities, add the `immortal` group. That's it. That's all you need to do. No crazy solution like intercepting callbacks is needed. The health is still internally there, but it can be safely ignored.

You have not really a clue what you're talking about, and you don't understand the Lua API well. Like your rage about groups is completely unwarranted. Your feature killing spree will literally break nearly every mod and game in existence, so I kindly ask you to STFU. :-) Minetest is **NOT** an universal game engine. It's made for a specific type of game, so it's only logical to find a lot of specific features in it. That having said, some of the features are indeed having a lot of awfully hardcoded stuff in it and there have been pushes for more generalization. But even that is not an excuse to just blindly destroy features without further thought. Thing is, too much stuff depends on said features now …

**Comment by hecktest** [comment]
_An open source voxel game engine. Play one of our many games, mod a game to your liking, make your own game*, or play on a multiplayer server._ 

_*as long as it's minetest_game_


There are more and more people starting subgames from scratch these days. If you're not one of them, I think you're the one who needs to _shut the heck up_.


_Ah, no wait, you're not supposed to do that! H-haha, you see, when we said we wanted someone to come along and do something new and better designed, we uh, actually wanted someone to come and make us a better Free Minecraft :) haha, sorry! ;)_

**Comment by tenplus1** [comment]
I vote for improving the breath/drowning system by adding the following:

- add head level position so that player models can be any size and configuration (defaults to current)
- add breath stats like lung capacity, rate of air loss/increase, damage caused
- add the ability to disable breath entirely for external lua alternative if wanted

**Comment by hecktest** [comment]
Well, letting the game implement it covers all of that. Adding it into the engine is the opposite of what's needed. There are too many APIs for overly specific things already, and you will never be able to cover everyone's needs with a "fixed function" approach to game design, that's just a dead end.
A game-agnostic mod can emulate the current system without issues.

**Comment by TheTermos** [comment]
Yup, Minetest is being advertised as an engine, so it's only fair to do one of the following:
- stop doing that and find a better category that this thing fits in
- take a knife to it and start cutting out the crap trying to actually make it an engine

**Comment by Zughy** [comment]
> Minetest is NOT an universal game engine. It's made for a specific type of game, so it's only logical to find a lot of specific features in it.

Voxel art is not a type, voxel art is a technique, thus it has no limitation on the genre. If you don't agree, it's like saying that pixel art = Game Boy-like (or RPG Maker-like) video games. And you can see how stupid that is. Just to name one, Tamagotchi is pixel art. I can do an FPS, a platform, a tower defense, a puzzle game, literally anything. Right now Minetest heavily depends on Minecraft mechanics, as it actually started as a Minecraft/Infinitest FOSS clone. But if core devs decided to move it to an engine, that means things like breath, crafting inventory, even the inventory itself, are not needed anymore. I'm wtih hecktest on this one

> _An open source voxel game engine. Play one of our many games, mod a game to your liking, make your own game*, or play on a multiplayer server._
> 
> _*as long as it's minetest_game_
> 
> There are more and more people starting subgames from scratch these days. If you're not one of them, I think you're the one who needs to _shut the heck up_.
> 
> _Ah, no wait, you're not supposed to do that! H-haha, you see, when we said we wanted someone to come along and do something new and better designed, we uh, actually wanted someone to come and make us a better Free Minecraft :) haha, sorry! ;)_

This, but framed

**Comment by paramat** [comment]
I quite like the idea of moving breath and health to games, if that is practical, it may not be.

But anyway, despite what the first post claims, rubenwardy has no plans to move breath soon, and might never do so, so this issue is premature and invalid. Perhaps discuss in the forum.
