### ISSUE TITLE
Minetest crafting inventory shouldn't be shipped by default

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#10115]
Splitting #9791 (which is about the inventory in general)

## Problem
The craft inventory is very specific to Minecraft-like games, but not needed in the vast majority of genres (FPS, plaftorms, moba etc)

## Solutions

As Minetest is heading towards being an engine, it shouldn't have any crafting table by default. It should be up to modders whether implement it or not

## Additional Context
This would also mean having less things to focus on and closing several issues at once:
#10114
#9456
#9250
#8548
#8241
#7429
#7300
#5745
#5374
#5323
#4901
#4382
#1250
#1079

**Comment by SmallJoker** [comment]
I don't see the point of removing crafting from the engine. If you don't need it, set the `"crafting"` list to size 0. No matter how many issues you link here - the same (if not more) would persist in a Lua re-implementation.
Also good luck optimizing that Lua code. C++ does it very efficiently (hash tables) and it should be kept that way. Just for the sake of being "Minecraft-like" isn't a valid argument. Minetest can and is Minecraft-like and that's probably what the majority of players wants.
:-1: This is not worth it.

**Comment by Zughy** [comment]
I see your point, and as there are two thumbs up by two other core devs, I'll close the issue myself in a few days. I just want to correct one thing, in case someone wants to debate:

> Minetest can and is Minecraft-like and that's probably what the majority of players wants

But yet people don't like to have it called a Minecraft clone: isn't it a bit hypocrite? Also I don't agree: people only know this aspect because it's the one shipped by default since years, yet servers like rubenwardy's CTF or mine (mini-games) don't need a lot of survival mechanics (mine doesn't need any, for instance) and people do like them.  
  
It's like saying people play Minecraft because of its (vanilla or not) survival. The most famous servers are mini-games servers (one became a company, Hypixel, and it then was bought by Riot Games), then there are survival and RPGs. Also there are people loving technical mods, so the public is pretty heterogeneous. Of course till the coming of Hunger Games servers Minecraft were all vanilla/creative and slight variations of the genre, but that doesn't mean people *preferred* it. They simply didn't have a choice. As Taleb would say, the absence of proof is not a proof itself

**Comment by Moth-Tolias** [comment]
frankly, i find the minecraft crafting paradigm to be incredibly clunky; it's impossible for new players who don't already know the convention to understand what to do, remembering the exact shapes is a hassle, and even when you do know how to use it, it's slow - you have to find each item in your inventory and manually place them in the grid. minetest has simply copied this element of minecraft over without thinking about whether it was actually _worth_ copying.

mojang had to introduce the crafting guide [for those who are unfamiliar with modern minecraft, essentially a big list of all the possible outputs that fills in the grid automatically when you click an entry] to make it at all usable. at that point you might as well just get rid of the grid entirely, since all it's doing anymore is taking up ui space.

i agree with @Zughy. if minetest really is not minecraft, as some folks around here love to say, then we don't have to fall for the same design flaws that minecraft does.

**Comment by paramat** [comment]
> The craft inventory is very specific to Minecraft-like games, but not needed in the vast majority of genres

But it is used in the majority of Minetest games =)
> As Minetest is heading towards being an engine

It is not a completely neutral game engine, and eventually being one is not intended, even if it may be becoming a little more neutral and flexible. It will probably always be orientated towards 'Minecraftlike' cubic voxel games.

So it seems best to me to keep the C++ crafting code. As long as a modder can disable engine crafting there is not much reason to remove it, it works well and does not require much maintenance, most issues are requests for new features.
:-1:

MT is 'Minecraftlike' but is not a 'Minecraft clone', those 2 are different.
'Minecraftlike' does not mean 'specific Minecraft gameplay' or MTG, it means something like 'large cubic voxel world, flat planet surface mapgens, humanoid player, digging, carrying and placing cubes, crafting cubes into other items'.

**Comment by Zughy** [comment]
It makes sense to me, closing the issue then
