### ISSUE TITLE
Minetest gui doesnt work when built from source in Mac os x

### ISSUE THREAD

**Issue by elan69** [minetest/minetest#10130]
Minetest gui doesnt work when built from source in Mac os x high sierra
the mouse glitches into the middle and the only way to stop is to restart
but the minetest app installed from brew is fine

**Comment by elan69** [comment]
i forgot to mention that this is still a issue in release minetest 5.2.0 and the latest one

**Comment by SmallJoker** [comment]
> but the minetest app installed from brew is fine

Could you please write down a list of your test results like so? (example)

:ballot_box_with_check: 5.2.0 (stable) installed using brew
:negative_squared_cross_mark: 5.3.0-dev (built today) from source using `git clone` & `make`

What's the Irrlicht version of each binary?
What happens when you change the DPI?
What does pressing `ESC` (pause menu) or `I` (inventory) do?

**Comment by elan69** [comment]
installing the brew version and opening .app works 

When running the build from 5.2.0 which is built from source causes this issue

I have Irrlicht version 1.8.4

Pressing I or Esc doesn't work and the cursor keeps getting teleported into the middle of the screen
