### ISSUE TITLE
Press aux button to move fast while flying (configuration)

### ISSUE THREAD

**Issue by BruceMustache** [minetest/minetest#10148]
## Problem

Doesn't need to press aux button down to run while flying
ie: Run with aux is more fast 
Ex. Sometimes is confusing to run, don't run while flying while when in the ground you can rapidly press aux button down to run

## Solutions

Run with aux while flying 

## Alternatives

Add configuration option for this and also put it in change keys configuration as check box

**Comment by paramat** [comment]
The description is a little confusing.
By 'run' i assume you mean 'fast move', MT does not have 'run'.
'Run' implies being on the ground, so it is a little confusing to use that word =)

Do you mean that if the player has the fast move priv, and enables flying, they should have to press 'aux' to fly fast?
If so, there is already a setting to choose either behaviour:
```
#    If disabled, "aux" key is used to fly fast if both fly and fast mode are
#    enabled.
always_fly_fast (Always fly and fast) bool true
```
I think the default is correct and should not be changed, because most users need to automatically move fast when flying.

**Comment by BruceMustache** [comment]
Thanks
