### ISSUE TITLE
Formspec: Font styles don't work for table and textlist

### ISSUE THREAD

**Issue by Thomas--S** [minetest/minetest#10194]
##### Minetest version

```
Minetest 5.4.0-dev-82731d0d3
```

##### Summary
`font` styles have no effect for tables and textlists although it is described in `lua_api.txt`:
https://github.com/minetest/minetest/blob/4b4513a67d9fc426d0f33798d0810a3a0594baaf/doc/lua_api.txt#L2772-L2774

##### Steps to reproduce

Use the following formspec code:
```
size[5,5]
style_type[table,label;font=mono]
label[0,0;It works for labels]
table[0,1;4,4;t;But not for tables;1]
```

**Comment by v-rob** [comment]
Ooops.  I'm surprised I didn't catch that.  No, #9763 didn't add font support for them although it was intended earlier, and I suppose I forgot to remove that from `lua_api.txt`.

Well, the two ways to proceed are to remove that text, or actually implement it :-)  I think I'll try the latter since most terminal mods use textlists, so monospace makes a lot of sense there.
