### ISSUE TITLE
User custom formspec themes

### ISSUE THREAD

**Issue by Pevernow** [minetest/minetest#10192]
## Problem

Some users don't like the theme of the formspec now.

They would like to change their theme.
## Solutions

Can users customize their UI style?

I think users can use a configuration to modify their UI styles(For example, change the main menu 's style).

**Comment by Andrey2470T** [comment]
There is already the formspec styling support that was embedded still in 5.1.0, see here: https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2666

**Comment by wzy2006** [comment]
Yes.They can change in the lua code.

But users can not change the default style in the "Setting" page.

**Comment by rubenwardy** [comment]
They will need to install a mod to do this. I've  not seen any retheming mods yet, possibly because we don't have full theming support

**Comment by v-rob** [comment]
I think the authority of styling formspecs should be given to the game, not as a setting since setting a global theme would affect every game, messing up the specific asthetic of the game.  As for the main menu, there is #8758 and #9802 which are more specific to that problem.  As for MTG, that would deserve its own issue in MTG's repository.

**Comment by hecktest** [comment]
What @v-rob said, also...
_Don't texture packs already allow this?_

**Comment by SmallJoker** [comment]
Yet we could introduce a setting that sets the default value of the formspec prepend. This allows styling the main menu (hopefully) and also games that do not define any prepend (likely none).

**Comment by Zughy** [comment]
Adding "Possible close" considering SmallJoker, v-rob and hecktest comment

**Comment by SmallJoker** [comment]
This issue was closed for being a duplicate of #10435. Whereas it is possible to theme the main menu and game, there is currently no global, customizable formspec prepend. See my suggestion https://github.com/luanti-org/luanti/issues/10192#issuecomment-663959506 above.

Now that #16015 is merged, I do clearly see the need for such feature, thus insisting on opening it.
