### ISSUE TITLE
Organize mods using groups

### ISSUE THREAD

**Issue by BruceMustache** [minetest/minetest#10195]
## Problem

Many games and people organize they mods using modpacks the problem is you can't put a modpack inside of other modpack. So then games move all mods of the modpack to the upper level one. The problem is this makes that modpack desorganized and difficult to update

## Solutions

I suggest to add modgroups to add a mod group you just create a file modgroup.conf and they support a modpacks inside of it.

## Alternatives

With modgroups implemented would be possible to have some default modgroups in your mods folder to organize mods by catergories automatically and mods can also set its category in mod.conf. Groups like mapgen, decoration, mobs, technology in which mods like mesecons, digilines, digtron would be on technology; homedecor, xdecor, bakedclay, moreblocks in decoration; nssm, creatures, mobs_monster in mobs and so on

**Comment by rubenwardy** [comment]
The better solution is to allow nesting modpacks. Minetest does support nested mod packs in the backend, it's just the GUI that doesn't. So you can have nested modpacks in games

**Comment by BruceMustache** [comment]
Ok. And the part of organizing mods by categories?

**Comment by paramat** [comment]
It seems wrong to have modpacks inside modpacks, because a modpack is a collection of mods, it should not contain modpacks, all mods contained are part of the one modpack.
But nested folders within a modpack seems ok.

I cannot see justification for mod groups, :-1: for that. If nested folders are allowed then which one is 'mapgen' will already be obvious from what mods are contained.
Having groups also means needing to continually rethink and update the categorisation of mods and add new categories.
Modgroups seems overkill and an unnecessary complexity. Simply organising by dividing into folders is good enough.

**Comment by rubenwardy** [comment]
> It seems wrong to have modpacks inside modpacks, because a modpack is a collection of mods, it should not contain modpacks, all mods contained are part of the one modpack.
But nested folders within a modpack seems ok.

I disagree with this, it's very useful for organisation. I use it considerably in games, especially

**Comment by BruceMustache** [comment]
Another way to organize mods is putting tags in they and after that interface can filter them
