### ISSUE TITLE
Add handling for when attached object receives a set_pos call

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10224]
## Context

If you are an object, and you are attached to another object, and the code says that you should be moved via `set_pos`, then nothing happens. This is by design, to avoid unpredictable behavior.

However, it's still an annoying restriction, because it makes certain things impossible. For example, players cannot teleport while on a boat.

## Suggestion

To the object definition of the *parent* (e.g. boat), add a field `attached_set_pos_behavior`. It accepts strings and `nil`. This field tells the *child* object (e.g. player on boat) what to do when it has received a `set_pos` call.

Possible values are:

* `"stay"` or `nil`: Do nothing. This is the current behavior. This is the default.
* `"move_both"`: Child is moved to the position specified by `set_pos`, also brings its parent with them. The offset between child and parent is not changed.
* `"detach"`: First the child gets detached (`set_detach()`) from parent, then the child moves to the pos specified by `set_pos`

### Exmple for `"move_both"`

You are on position (0,10,0), you're a player (=child object) and are attached to a boat (=parent object). The boat has `attached_set_pos_behavior="move_both"`.

You're offset with (0,2,0) from your boat. Or in other words, the boat is offset (0,-2,0) from you. In absolute numbers, your boat is at (0,8,0).

You receive a `set_pos({x=100,y=100,z=100})`. This means, you teleport to (100,100,100). You bring your boat with you. Your boat is still offset (0,-2,0) from you, which means in absolute numbers the boat is now at (100,98,100).

Internally, I believe, this could be solved by applying the `set_pos` to the parent instead of the child, except that the target pos is first subtracting the parent-child offset. That way, the child automatically moves with the parent since it is still attached.

### Example for `"detach"`

You are on position (0,100,0), you're a player and are attached to a boat. The boat has `attached_set_pos_behavior="detach"`. You receive a `set_pos({x=100,y=100,z=100})`. This means, you first detach, then you teleport to (100,100,100). The boat stays where it is.

## Credits

Idea from @FeXoR-o-Illuria.

https://github.com/minetest/minetest_game/issues/2722#issuecomment-662652789

**Comment by hecktest** [comment]
This is potentially confusing with regards to how every other engine handles this. You'd expect that a position setter would set the local or world position of an object, _without dragging the parent along_.

If you want to teleport a player with a boat, shouldn't you just teleport the boat?
If you want to detach, can't you just detach? Why do you need a position setter doing this?
What if the boat has two seats? What happens to the other guy riding it?

This is bad engine design.

**Comment by Wuzzy2** [comment]
> If you want to teleport a player with a boat, shouldn't you just teleport the boat?

Of course this is possible, but not good enough. With this, you can only make it work for specific object, but it's not really a generic solution.

As soon you want to have generic handling of teleportation that works with all objects, this breaks down. Teleportation code often doesn't know or care about the objects it teleports. Also, the problem is that the child might or might not be attached when you do a `set_pos`.

> If you want to detach, can't you just detach? Why do you need a position setter doing this?

To avoid boilerplate code.

Again, this requires the child to know that it's attached. To safely teleport, you'd have to check for if you are attached before *every* `set_pos`. For every. Single. Object. Since every object *could* be attached. This is impractical, and it's always a gamble if you do a naked `set_pos`.

> What if the boat has two seats? What happens to the other guy riding it?

* `"stay"`: Nothing
* `"move_moth"` The other guy moves along with the parent, as if the parent was teleported normally. Teleporting a child really just means the teleportation command propagates to the parent
* `"detach"`: Nothing

> Make the param "world" or "local"

What does this mean? Which param?

**Comment by hecktest** [comment]
And that's exactly the responsibility of a `teleport` function, not a `set_pos` function. Resist the temptation to sneak more game code into the engine, that way lies madness. You can't and shouldn't expect a function to handle every possible case by itself. That leads to very baroque code which eventually grows into an unmanageable mess.

What you probably want is a library that wraps all this and gives you more meaningful functions like `teleport`, and you might as well write one yourself, or make it a minetest_game feature request. Writing your own helper functions is a better habit than trying to squeeze them into upstream code.

By param I mean, instead of the stay/detach/move enum, make it a local/world enum. In the first case, set_pos would set the local position (called "attachment offset" in our special snowflake minetest terms), and in the latter case, it would set the apparent world position (by multiplying by world-to-local and still setting the local). That way the ambiguity is resolved and it works like every other engine out there, no surprises.

I could tolerate a position parameter to set_detach instead, to ward off packet order gremlins, but if the network protocol is any good, it's probably unnecessary too.

**Comment by Wuzzy2** [comment]
But the problem is that `set_pos` might sometimes fail. So we have madness either way. Either we force most mods to add annoying boilerplate code every time they add `set_pos` (like we do now), or we add the madness into upstream. Note that my proposal is optional. Objects still stay by default. But OK, I guess my suggestion wasn't ideal.

Why an external library? Attachment stuff is 100% engine stuff, it is not game-specific at all. Attachments can be used for all sorts of things. Adding it to MTG only is very limited, also, we should really start to ignore MTG.

It's not a good idea to force each modder to figure out the attachment weirdness every single time again. The fact that `set_pos` might fail is a problem that pretty much all games will have, and not just MTG. You're trying to overgeneralize.
Maybe instead of modifying `set_pos` a new special function could be added for this that is like `set_pos` but also handles attachments. Or a 2nd parameter to `set_pos`, like you suggest, so old code is always compatible either way.

> By param I mean, instead of the stay/detach/move enum, make it a local/world enum. In the first case, set_pos would set the local position (called "attachment offset" in our special snowflake minetest terms), and in the latter case, it would set the apparent world position (by multiplying by world-to-local and still setting the local). That way the ambiguity is resolved and it works like every other engine out there, no surprises.

I don't see the point of the first case. We already have a function for that.

I hope we can at least agree that the documentation on `set_pos` is incomplete. It does currently not admit that `set_pos` will fail when the object is attached.

**Comment by Wuzzy2** [comment]
Also, `set_pos` should probably return `false` when the function has failed.

**Comment by hecktest** [comment]
Yes, currently it fails silently without it being documented. This is a bug.
It should be handled by changing the local or the reconstructed world position. Not by breaking transform chains, or by moving parents (????), that is plain mad. The only reason it makes sense to you is because you're thinking in minetest_game terms only, where object hierarchies don't get deeper than two levels and the most complex thing that happens is using a teleporter while sitting on a boat. (and this is probably the case that you want it to magically handle)

This "solution" will be a nuisance as soon as something like voxel entities becomes a thing, or if someone just makes multi seat vehicles. It would actually become a source of bugs in moddable games, because now, on top of everything else, you have to think about whether another mod has decided to use the "detach" or "move parent" modes for set_pos (because it's sooo "convenient"), which will lead to paranoid checks whether something has been detached or yanked to some invalid position, followed by crude, inaccurate attempts to repair the game state if it did happen. Madness, madness, madness. This is not how coding is supposed to look like.

Just seeing those options mentioned in documentation would make me think that someone's been smoking crack when implementing this, and I'd be pretty worried about what other horrors lurk in the API.

_A position setter is not a teleport, it's a position setter. The engine doesn't need to provide a one size fits all teleport function, and can't, because everyone will have different requirements for that._
For instance, moving the parent is a specific requirement that _you_ want, in which case you should write yourself a teleport function and make it do that. It's not boilerplate, because it's not identical across implementations.

the only problem is that set_pos fails on non-root objects, so just make it set the local or world position, that's all. (if this is done, a similar parameter should exist for get_pos)

**Comment by hecktest** [comment]
Let me mention this too; if it can be helped, there shouldn't be several ways to do one thing in an API, especially if there are subtle differences between them. This is a common theme in baroque abominations like C++, and other horrible technologies designed by commitee.

**Comment by Wuzzy2** [comment]
Alright, I am convinced now that extending `set_pos` with such added functionality is a bad idea. But the underlying problem still remains. So what other ways to solve it are there? Note the underlying problem I am trying to address is __NOT__ game-specific. As soon a game wants to deal with objects, attachments and `set_pos`, then this problem occurs. Therefore, I'm all for a generic solution.

Please write a proposal. I mean, a *real* proposal with actual API calls etc.

**Comment by HybridDog** [comment]
Maybe we could add a method to ObjectRef which is called when set_pos, set_velocity, or something similar is called on an attached child. By default this method does nothing (current Minetest behaviour), but it is possible to explicitly define this method in the entity definition.
For example, the method could be defined in the boat entity definition. When set_pos is called on a boat's child, which is a player,
the method would receive the information that set_pos(pos) has been applied on its child and the code in the method (which can be arbitrary) can then teleport the boat (and automatically all its attachments) to position pos. The modder implements this method, so it can handle complex situations such as having multiple children attached to one boat while set_pos is called on one of the children. If the boat itself is also attached to a parent and set_pos is called on the boat, the method of the boat's parent is executed. 
The method could not only be called when a position, velocity or acceleration of the child should change but also when the child is removed (the remove method). With this it is possible to e.g. make a boat drive back home when the player leaves the game.

**Comment by Wuzzy2** [comment]
I close this issue as my main design proposal is actually garbage. Yeah, I accept now that making `set_pos` extra complex wasn't my brightest of ideas ... And I have understood it wasn't carefully thought-through, especially the argument with multiple layers of attachments was convicing.

I have posted a new, simplified issue here: #11292
