### ISSUE TITLE
Discord Presence

### ISSUE THREAD

**Issue by AlanReviews** [minetest/minetest#10278]
Have a Discord presence for Minetest.

**Comment by NathanSalapat** [comment]
There is an unofficial Minetest discord here; https://discord.gg/mqEVpyf

**Comment by paramat** [comment]
Are you requesting an official Discord presence?

**Comment by rubenwardy** [comment]
Discord rich presence is when minetest tells discord that a player is playing Minetest, along with information like server, position, whatever

**Comment by paramat** [comment]
Ah ok, if this request is for 'Discord rich presence' then that has already been requested, discussed and rejected (oddly, i cannot find the issue for it yet).

**Comment by HybridDog** [comment]
Can this be implemented with Client Side Modding?

**Comment by benrob0329** [comment]
Potentially, but most servers have _all_ CSMs disabled, rendering such a thing useless most of the time.

**Comment by hecktest** [comment]
Workaround:
Open your window and shout at the top of your lungs about what you're currently doing to people who don't care one lick about it. Net effect should be about the same.
If you're worried that your favorite corporate scum won't make as much money that way, you can always just wire them a few dollars directly.

**Comment by LoneWolfHT** [comment]
> Open your window and shout at the top of your lungs about what you're currently doing to people who don't care one lick about it. 

That'd be pretty hard (The 'people that don't care a lick' part) because there are pretty much always people in or around my house that would immediately ask to join me :P Discord rich presence isn't intrusive either, and it doesn't show up to anyone without Discord.

BTW: Your post appears to be blindly hateful and unhelpful. If that wasn't your intention and what you gave was a genuine suggestion you might want to read up on how Discord works and rewrite your post with that new knowledge in mind

**Comment by orbea** [comment]
> Your post appears to be blindly hateful and unhelpful. 

What do you expect when discord is proprietary malware? Are we supposed to ignore that fact just to be "nice"?

**Comment by LoneWolfHT** [comment]
> What do you expect when discord is proprietary malware? Are we supposed to ignore that fact just to be "nice"?

That's a question Hitler was faced with on the topic of the Jews. He chose to act 'aggressively' on his belief.
That's a drastic comparison you can ignore if you want but until I see people saying Discord is malware like they are with TikTok (https://www.distractify.com/p/reverse-engineered-tiktok, etc) the answer to "whether or not Discord is malware" I label as a personal opinion, which isn't necessarily right/wrong, and just what Hitler had.

To reply without the drastic comparison: Yes, you should be nice or at least formal with people who you don't agree with, if they're doing nothing to provoke anything hostile.
I think I can speak for most/all of the Discord users here when I say that provoking hostility or being hostile isn't anywhere near the intent here.

**Comment by LoneWolfHT** [comment]
To get back ontopic:
Maintaining a fork that adds rich presence might work. If you provided compiled versions it wouldn't be too hard for users to switch to it if they wanted rich presence.
Might tackle this myself eventually. My plate is stacked to the sun atm though

**Comment by orbea** [comment]
@LoneWolfHT Your analogy is absurd and doesn't make much sense.

That said you should read this, discord being malicious software is not an opinion, but a reality. And yes, there are many social media platforms with similar problems unfortunately.

https://sneak.berlin/20200220/discord-is-not-an-acceptable-choice-for-free-software-projects/

**Comment by mnh48** [comment]
*ah sh\*t, here we go again*

Discord is actually kinda balance between "the larger mass" like TikTok or Facebook and "the smaller niche" like IRC

Maybe it's not good for open source philosophy but it's good enough for engaging with end users without going all the way to the even worse platform like Facebook.

If people want, people can even bridge Discord chat with IRC, many of them did that for development of their software, chatting with end user on Discord remotely from IRC while avoiding use of Discord itself at the same time.

**Comment by hecktest** [comment]
I propose that we instead integrate Bonzi Buddy into Minetest. All those users couldn't possibly be wrong.

![Bonzi_Buddy](https://user-images.githubusercontent.com/42101236/90688691-192f5100-e26f-11ea-8191-4f4e196b2235.png)

**Comment by LoneWolfHT** [comment]
> @LoneWolfHT Your analogy is absurd and doesn't make much sense.

As I said (I guess I may have put it mildly):
> That's a drastic comparison you can ignore if you want

I direct you to my reply without the drastic comparison, which I hope is less absurd/drastic
#

> That said you should read this, discord being malicious software is not an opinion, but a reality. And yes, there are many social media platforms with similar problems unfortunately.
> https://sneak.berlin/20200220/discord-is-not-an-acceptable-choice-for-free-software-projects/

I agree with quite a few of the points in there, but I disagree with a few too, and still don't see Discord's malicious intent. Just what looks like some bad decisions and unfortunate necessities created by human greed.
I use Discord mainly for gaming related things, and to be on the safe side I only give them info I'm comfortable with giving.
I've never been required to give my phone number and don't remember ever being asked to. Although a few rare servers require 2FA with Discord. I'm not in those servers.

This is probably annoying all the people subscribed by email so I take my leave from this discussion with the request I made earlier that we be nice or at least formal with the Discord users here.
If you can't do that then you should just hate me completely and smash that block button after giving me a (dis)like on all the platforms we share an account on :P

Good luck with your Bonzi Buddy integration hecktest. Never heard of it before but I'll trust those users of yours because who wouldn't

**Comment by orbea** [comment]
> and still don't see Discord's malicious intent.

The intent is not relevant, only the result. The result is clear that discord's users are part of a massive data collection campaign where the data is used at the whim of people who may not have their user's best interests at heart with no oversight or recourse. Whether discord's staff are simply misguided or actively malicious doesn't matter at this point.

>  I made earlier that we be nice or at least formal with the Discord users here.

Maybe this was not clear, but I personally do not have anything against discord users, only against discord itself which abuses its users. I think its sad that people have been conditioned to accept and ignore such abuses in the pursuit of convenience and not being excluded from various social circles. I also do not think its fair to expect people to beat around the bush when pointing out that discord the program and the social media platform are entirely unacceptable for free software projects.

**Comment by LoneWolfHT** [comment]
It seems I misunderstood your reply here https://github.com/minetest/minetest/issues/10278#issuecomment-676558292
That clears a lot up. I've edited my OP to be a little clearer too https://github.com/minetest/minetest/issues/10278#issuecomment-676554609
