### ISSUE TITLE
set_bone_position() causes bone to adopt rotation and position from parent bone.

### ISSUE THREAD

**Issue by ElCeejo** [minetest/minetest#10301]
This bug(?) occurred on Minetest 5.3.0 for me but it affects any client that has the set_bone_position() function

I'm fairly sure this isn't intentional and that's why I'm reporting it as a bug. I don't think anything more than the title is needed to describe this issue. Basically, when you use set_bone_position() on any bone, it will set the rotation of the bone to the rotation and position of whatever bone it is parented to. If it isn't parented to a bone the position is set to the center of the model.

I'm sure anyone who this matters to can figure out how to reproduce it. I'm too lazy to do it myself.

**Comment by hecktest** [comment]
![cool guy](https://user-images.githubusercontent.com/42101236/90760268-e83c3400-e2e1-11ea-9856-90efe17afdd7.gif)
Not a bug, set_bone_position sets the bone's transform in the parent's local space.
As far as I know, the only thing that has changed about it is that it now correctly follows animation, instead of being relative to the rest pose.

Allow me to explain:
![bonechain](https://user-images.githubusercontent.com/42101236/90759460-bd9dab80-e2e0-11ea-9da8-f498cec1911d.png)
Scene formats like .b3d and .x do not usually store bones, they store a chain of transform matrices, or "empties" if you will.
Those do not come with endpoint information, they have to position themselves using just a single matrix.
Therefore, a bone will typically be moved along its parent's major axis (which one it is depends on many things), then rotated to point towards where the next bone should be. This is the bone's local rest pose.

In order to position the bone in the orientation you want, you also have to apply the transformation it originally had in the rest pose. This could be added as a mode so that you don't have to open up a file and figure out what the rest pose was yourself.

**Documentation needed:**
Document the default behavior for set_bone_position.

**Feature request:**
Support other coordinate spaces for set_bone_position. Add a string parameter to specify one of the following:
- "parent": which is the current behavior and should be default
- "local": relative to the bone's rest pose
- "pose": relative to the bone's animated pose
- "object": relative to the entity's root
- "world": absolute world space

**Comment by ElCeejo** [comment]
Makes sense, I'll close this and make a feature request later.
