### ISSUE TITLE
Slow loading times

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10316]
## Problem

I am the host of a laggy server with a lot of textures.
If i want to switch accounts, I need to download images every time.
This is wasting my time!

## Solutions

Media cache can slove this problem.
1. first, client request a media list and media's hash
2. Second, client request medias that have change, Or request all media if no cache.

**Comment by MoNTE48** [comment]
This is how it works right now. All media are cached

**Comment by Emojigit** [comment]
but i still need to wait for a long time!

**Comment by rubenwardy** [comment]
What OS do you use? I suppose this is an XY issue - and your real request is to improve loading times

**Comment by sorcerykid** [comment]
I have to wonder whether this issue is actually network related. I'm running Minetest under Windows 10, and I've noticed my client hangs during media loading even when revisiting a server which has not restarted in several days, so the textures, sounds, models, etc. should all be unchanged.

Could it be that there is some bottleneck in reading the local cache folder on certain platforms, particularly if there are tens of thousands of files? Or is it possible that Minetest is attempting to re-download some media, regardless of the cache state? Has the caching mechanism been stress-tested under all different platforms?

**Comment by HybridDog** [comment]
I assume that currently when Minetest loads a list of textures, it alternates between loading a file (from disk) and processing it (e.g. apply texture modifiers, send to GPU memory, etc.). I don't know if it is better to load all files at once and then process them or to intertwine the loading and processing.
With flags in [`open`](https://man7.org/linux/man-pages/man2/open.2.html), and [`posix_fadvise`](https://man7.org/linux/man-pages/man2/posix_fadvise.2.html) it is possible to give hints to the Operating System for the file reading. For example, it can be specified that the file content is likely accessed in sequential order. I think these functions require a POSIX conform Operating System.

**Comment by Emojigit** [comment]
OS and version detals:
Server: Ubuntu 20.04 LTS with minetest 5.3.0-ppa0~ubuntu20.04.1
Client: Windows 10 with Minetest 5.3.0 pre-build version

**Comment by Wuzzy2** [comment]
As the (current) main developer of MineClone 2, I have a game with lots of data (esp. music files) and it takes a long time to load. I also noticed the loading time is always roughly the same, i.e. if I leave back to main menu and start MineClone 2 immediately again, the loading time is not cut down.
