### ISSUE TITLE
Split 'Name/Password' text field title for clarity. Darken text field background colours

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#10362]
![Screenshot from 2020-09-02 18-38-36](https://user-images.githubusercontent.com/3686677/92029137-02075d80-ed5d-11ea-8275-ef9d3b8552ce.png)

Although i have always assumed, correctly, that this means name in top field, password in bottom field, i have always thought this sloppy design and slightly open to misinterpretation. It could be interpreted as name and password in the top field separated by a slash. The greyed-out password field adds to the possible confusion, the greying-out has always slightly suggested to me: 'do not enter text here'.
1 or 2 of the background colours of the text fields are too bright, making readability bad with white text.

Proposal:
* Create some space: Move checkboxes upwards, move 'Server Port' field downwards level with 'Host Game'.
* Title 'Name' and 'Password' fields separately.
* Alter text field background colours to all be mid-grey, for better readability with white text (the screenshot is out of date, the main menu tabs are now mid-grey, so the background colour of the 'Name' text field is now inconsistent).

I can do a PR if this has some core dev support.

**Comment by v-rob** [comment]
I support making pwdfields having the same color as everything else.  I don't know why they look different in the first place, but it's worth noting that all fields have that color when freetype is disabled (that is, when you disable it in the advanced settings, the search field immediately changes color).

As for darkening the colors to match tabs, it sounds like it might look pretty good, although I can't say for certain until I see it.  It's definitely worth noting that the text cursor on Windows is impossible to see when hovering over pwdfields because they share the same gray color.
