### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by SoniEx2** [minetest/minetest#10386]
## Problem

A clear and concise description of what the problem is.
ie: Why is this needed?
Ex. I'm always frustrated when [...]

The community tends to be a bit on the ableist side, among other issues.

## Solutions

It would be helpful to have a code of conduct. We recommend something along the lines of [FreeBSD's old code of conduct](http://web.archive.org/web/20200530031745/https://www.freebsd.org/internal/code-of-conduct.html) because it's technically welcoming of porn mods.

## Alternatives

Other code of conducts are also an option, but a lot of them are corporate-oriented, TERF-backed, SWERF-backed, etc.

## Additional context

We still remember the "drooling morons" incident and we're not gonna let it go until you do something to address it and make sure things like it don't happen in the future.

**Comment by rubenwardy** [comment]
I'm in favour of adopting some kind of code of conduct, but I think it's best to keep it brief rather than explicit - there's less to argue about

**Comment by SoniEx2** [comment]
we think it should be enumerative because it's more effective and easier to understand that way. remember that the CoC applies to everyone, including moderators, and this is especially useful for holding them accountable.

the best tutorials lead by example. so do enumerative CoCs.

**Comment by appgurueu** [comment]
> The community tends to be a bit on the ableist side [...]

Any evidence for this claim?

I think the forum rules are sufficient.

**Comment by BluebirdGreycoat** [comment]
What is the "drooling morons" incident?

More to the point, why would a CoC that supposedly discouraged someone from calling someone a DM*, yet was welcoming of porn mods, be even slightly desirable? These priorities are exactly inverted from what they should be. Someone calling someone a DM online doesn't even get an eye-roll from me. Porn, on the other hand, is legally actionable and does far more damage.

From FreeBSD's old CoC:

```
All those given recognition as members of the Project in whatever form are seen as ambassadors of the Project.
```

This language is a poison pill and should never have been adopted, anywhere. It's a slick way to force people to adhere to corporate and/or group policy, even in their private lives, *even in areas that have nothing to do with their public contribution*.

The rest of that document contains similar traps. It's worded in order to elicit maximum agreement from folks who don't take the time to consider the consequences.

*Drooling Moron

**Comment by rubenwardy** [comment]
Porn mods are not allowed on the forums, GitHub (GH's terms and conditions), or ContentDB.

I much prefer the [Debian Code of Conduct](https://www.debian.org/code_of_conduct)

> What is the "drooling morons" incident?

http://irc.minetest.net/minetest/2019-02-06#i_5491083

**Comment by SoniEx2** [comment]
> More to the point, why would a CoC that supposedly discouraged someone from calling someone a DM*, yet was welcoming of porn mods, be even slightly desirable? These priorities are exactly inverted from what they should be. Someone calling someone a DM online doesn't even get an eye-roll from me. Porn, on the other hand, is legally actionable and does far more damage.

one is ableism, the other is not. one is harmful but often considered by public society as fine, the other is fine (as far as a category. specific porns may not be fine due to racism/ableism/etc but again see previous point.) but often considered by public society as bad.

> This language is a poison pill and should never have been adopted, anywhere. It's a slick way to force people to adhere to corporate and/or group policy, even in their private lives, even in areas that have nothing to do with their public contribution.
>
> The rest of that document contains similar traps. It's worded in order to elicit maximum agreement from folks who don't take the time to consider the consequences.

it's basically saying "if you're racist on twitter you get the boot" and that's a good thing tbh.

**Comment by SoniEx2** [comment]
> Porn mods are already not allowed on the forums, GitHub (GH's terms and conditions), or ContentDB, and they cannot be allowed as they will compromise hosting.

uh clearly you need a new hosting provider. and move away from github.

**Comment by rubenwardy** [comment]
Or we could just continue to keep porn out of a game, especially one that has a younger audience

**Comment by SoniEx2** [comment]
or you could just make an adult section for the game.

**Comment by SoniEx2** [comment]
look, this thing doesn't force you to make an adult section or accept adult content on non-adult sections. it only *allows* you to create such an adult section, and still doesn't allow adult content on non-adult sections.

the main benefit over, say, debian's CoC, is that it doesn't straight-up ban adult sections. it also doesn't let you be racist on twitter while participating on the project.

**Comment by BluebirdGreycoat** [comment]
I read the IRC discussion. Honestly, my first impression, going through it, was that "Soni" was either a troll, or had decided for some particular reason to go trolling that day.

Then I came to this:

```
20:24 	sfan5 	from the point where SoniEX joined a few days ago I was wondering why people were feeding the troll
```

Which pretty much confirmed that I wasn't the only one thinking that.

```
20:22 	Soni 	really, you've just proven yourself to be ableist, classist, and elitist, and you can't read
```

(Quoted reply was to @VanessaE). Me: That is not the case.

```
it's basically saying "if you're racist on twitter you get the boot" and that's a good thing tbh.
```

No. This utterly ignores the fact that 1) People change over time, and 2) Twitter (and everyone else) keep content *for years*. Do you really want some racist thing you said 10 years ago coming back to bite you because someone decided to go revenge-digging? Congrats. You just lost your job.

Or maybe you used to be friends with someone who later turned out to have ideas not welcomed by the wider society. Congrats. You just lost all your new friends, too (because someone went revenge-digging).

These are the real-world consequences. Only one side benefits: professional accusers.

This is not good.

**Comment by SoniEx2** [comment]
> No. This utterly ignores the fact that 1) People change over time, and 2) Twitter (and everyone else) keep content for years. Do you really want some racist thing you said 10 years ago coming back to bite you because someone decided to go revenge-digging? Congrats. You just lost your job.
>
> Or maybe you used to be friends with someone who later turned out to have ideas not welcomed by the wider society. Congrats. You just lost all your new friends, too (because someone went revenge-digging).
>
> These are the real-world consequences. Only one side benefits: professional accusers.
>
> This is not good.

Yeah no those ppl are abusers. They aren't allowed by the CoC either.

Here's the thing, if your moderators don't understand that ppl change, that's on *you*. If your idea of using a CoC like this is to punish everyone, that's on *you*. Transformative justice and restorative justice tell another story. That's what you should follow when using a CoC like this.

**Comment by appgurueu** [comment]
Honestly this issue is just wasting much needed resources.

We have never allowed any disrespectful PRs to the game or the engine (if there have ever been such) and will continue doing so. Accordingly, both game and engine are not concerned, so I don't see the point in this discussion. There's nothing to fix regarding the game and engine.

I say this issue should be a "possible close", as it concerns neither game nor engine.

**Comment by SoniEx2** [comment]
It concerns the IRC, the forums, the github, and the website.

**Comment by appgurueu** [comment]
1. Chat in the IRC
2. Make a forum post and report posts
3. Already handled by GitHub, report comments
4. The website is not offending anyone

I see no reasoning for this issue.

**Comment by rubenwardy** [comment]
There have been incidents in the past where a code of conduct would have been useful

**Comment by benrob0329** [comment]
SoniEx2, I know that you _really_ want some of that Nodecore Porn but you're gonna have to wait for another platform because nobody sane is gonna have that anywhere near a kids game. I don't care how many -isms or -ists you thow out, just because you don't have a problem with it doesn't mean the rest of us have to pander to you.

I am not against a CoC, but if Minetest adopts one it needs to be somewhat specific as to where it applies, as well as what kinds of recent behavior outside of that could still get you kicked off the team. The biggest potential problem I see is the big blurry line between condeming bigotry and overstepping because someone disagrees with a specific political movement, but that should probably go without saying. Unfortunately this will have to get political at some point as its defining behavioral principles around arbitrary moral constructs, but if we keep it to mostly the "problematic" behaviors we might be able to avoid most of it.

**Comment by rubenwardy** [comment]
I think that any "ambassador of the project" stuff should only apply to those officially involved, and not be in a code of conduct. If a core developer or moderator starts spewing white supremacist stuff on the Internet, then that is problematic both in terms of their neutrality and damage of reputation to us. Racism/white supremacy would, of course, be disallowed in the code of conduct itself

**Comment by BluebirdGreycoat** [comment]
```
It concerns the IRC, the forums, the github, and the website.
```
It concerns nothing. This is straight-up trolling.

```
We recommend something along the lines of FreeBSD's old code of conduct because it's technically welcoming of porn mods.
```
```
specific porns may not be fine due to racism/ableism/etc
```
```
uh clearly you need a new hosting provider. and move away from github. also freenode allows porn, so.
```
```
or you could just make an adult section for the game
```

Your motivation is obviously because you want porn mods. But apparently you don't like when someone uses the term "drooling idiot" to refer to a mindset that is anti-learning. You don't like it to the point that you want to propose a document that will force people to treat you delicately, while allowing you to ... push porn into Minetest.

```
Yeah no those ppl are abusers. They aren't allowed by the CoC either.
```

The CoC (as linked) says absolutely nothing about limitations on professional accusers. You are wrong.

```
Here's the thing, if your moderators don't understand that ppl change, that's on you.
```

What moderators may or may not understand is not the issue. The issue is that a CoC with this sort of poison-pill language provides a path--a highway, in fact--for any agitator outside the group to come in and use said document to professionally accuse anyone they have a personal disagreement with. Tip: *everyone* has said something wrong in their past. A CoC with such language is nothing less than very dangerous.

```
If your idea of using a CoC like this is to punish everyone, that's on you.
```

No, it is not. *You* are more likely than anyone else, right now, to want to use a CoC this way. You basically admitted it in your opening post.

```
Transformative justice and restorative justice tell another story.
```

^^^ An example of language that literally means the exact opposite of what the individual definitions of the worlds themselves mean. This is not the language of justice. This is the language of revolution.

**Comment by benrob0329** [comment]
I just skimmed the Debian CoC, and it seems to avoid a lot of the pitfalls that can come from CoCs by being mostly based in common-sense descriptions (ie "Be Respectful" as a general rule). I very much support using something along those lines because of this, and also becauae its a very well rounded CoC in terms of general behavior (Debian strikes again with its oddly sane leadership).

**Comment by SoniEx2** [comment]
"your motivation is because you want porn mods" but also "your motivation is because you want to get someone banned". which one is it gonna be?

the problem is most ppl who do wrong don't try to learn from it. case in point y'all are still insisting on stuff that happened years ago.

btw wtf is up with "[the idea that ppl should be able to code is] a mindset that is anti-learning". that's like saying learning ASL is anti-learning and you should force deaf kids to learn spoken english. :roll_eyes:

**Comment by BluebirdGreycoat** [comment]
```
Racism/white supremacy would, of course, be disallowed in the code of conduct itself
```

Unfortunately even those words are now highly politicized. In the US, at least, one *entire political platform* considers its opponents to be "the party of racists". Said party, in return, is slowly coming to consider the term to be nothing more than emotional blackmail.

Today, racism and white supremacy is wrong. Tomorrow, disagreeing with your political leaders will be wrong. This is all very unfortunate, but that's how history goes.

Let's keep it all very far away from here.

**Comment by SoniEx2** [comment]
your ableist arguments are comparable to ableist arguments that have existed for hundreds/thousands of years. they're not new, they're just in a new context. this is the problem that this whole issue is about. it's been years, you still haven't changed, and you still don't want to change. :/

**Comment by rubenwardy** [comment]
> Unfortunately even those words are now highly politicized. In the US, at least, one entire political platform considers its opponents to be "the party of racists". Said party, in return, is slowly coming to consider the term to be nothing more than emotional blackmail.
>
> Today, racism and white supremacy is wrong. Tomorrow, disagreeing with your political leaders will be wrong. This is all very unfortunate, but that's how history goes.
>
> Let's keep it all very far away from here.

Sounds like slippery slope fallacy. I very much disagree with that, remember that us moderators are human and have the capability to ensure the rules are applied fairly. The moderation team has a mixture of people with left, right, and center views.

**Comment by BluebirdGreycoat** [comment]
```
"your motivation is because you want porn mods" but also "your motivation is because you want to get someone banned". which one is it gonna be?
```

Both (and I am very tempted to drop a DM in here). They're not mutually exclusive.

```
the problem is most ppl who do wrong don't try to learn from it. case in point y'all are still insisting on stuff that happened years ago.
```

That's because people being fired from their jobs due to ancient history is a very real and very dangerous phenomenon. Plot twist: you can even get fired for saying something that society once considered *right*, that then became *wrong* because powerful forces made it so. And being fired is just the worst case. There's also blacklisting and shunning, etc. etc. etc.

```
btw wtf is up with "[the idea that ppl should be able to code is] a mindset that is anti-learning". that's like saying learning ASL is anti-learning and you should force deaf kids to learn spoken english.
```

You're trolling. Try to understand what the other person was saying in that IRC discussion.

**Comment by BluebirdGreycoat** [comment]
@rubenwardy I'm not sure why or what you disagree with; it's a matter of real-history as well as ancient history, and can be seen happening in a lot of places (specific subjects differ, of course, I am most familiar with the US). I was speaking about a large-scale issue, the moderation team of an individual formum is of course its own thing.

**Comment by appgurueu** [comment]
Glad this has been closed.
