### ISSUE TITLE
Add minetest.settings to CSM API

### ISSUE THREAD

**Issue by anon55555** [minetest/minetest#10382]
The code is already written as part of https://github.com/EliasFleckenstein03/dragonfireclient. This would allow changing client settings without restarting the game using a CSM.

**Comment by paramat** [comment]
This might be good to have eventually, but i think new CSM features should be frozen until SSCSM is somewhat complete, because:

* Time and effort spent on new CSM features is better spent implementing SSCSM which will guarantee the future of CSM.
* Client-Provided CSM (CPCSM) was never planned or intended, and is not officially supported, it was only ever a brief stepping stone towards SSCSM, and it was a mistake to make it a stepping stone. We did not need CPCSM before SSCSM, and CPCSM should have been disabled until we had SSCSM.
How CSM was initially developed was the biggest mistake MT ever made, bigger than sneak =D
* SSCSM should have been completed before CPCSM was made complex. Increasing the complexity of CSM first might make SSCSM more difficult to implement. Unfortunately what is happening is CSM is being made more complex during our impatient wait for SSCSM.
* The future of SSCSM is uncertain, it might never happen.
* If SSCSM does not happen all CSM might be removed, celeron55 considers having CPCSM without SSCSM unacceptable (i do too).

Unfortunately with how things happened, we let users have something they should never have had, so now of course it is difficult to tell users 'you should not have more of this', or 'it might be removed'.
I can understand users using and liking CSM, but keep in mind it is unstable, in development and not officially supported, so it could be removed and we have the right to do that. I want to make that clear to make sure users know they do not have the right to make a huge fuss if we ever remove CSM. You use it at your own risk and have to be prepared for it to disappear.

Because of the above, i am :-1: for this feature request until SSCSM is near completion.

**Comment by anon55555** [comment]
This doesn't add much complexity, it's literally 4 lines of code:
https://github.com/EliasFleckenstein03/dragonfireclient/blob/af085acbd32707576ff9e67c3b267ad6cf267288/src/script/scripting_client.cpp#L39
https://github.com/EliasFleckenstein03/dragonfireclient/blob/af085acbd32707576ff9e67c3b267ad6cf267288/src/script/scripting_client.cpp#L80
https://github.com/EliasFleckenstein03/dragonfireclient/blob/af085acbd32707576ff9e67c3b267ad6cf267288/src/script/lua_api/l_util.cpp#L515-L516

**Comment by jamesalexanderstevenson** [comment]
Looks good to me
