### ISSUE TITLE
Don't save mapblock if they are not modifled

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10396]
## Problem

If some player explores a lot if map blocks but without build at that block, the server will have a lot of useless and large map block files.

## Solutions

If the server just stores modified map blocks, then the map file can be smaller.

Also, mark those map blocks to explore, if mods want to get explore map blocks, the response will also include the explore but not stored map blocks.

**Comment by anon55555** [comment]
Some parts of terrain generation aren't deterministic in some games, e.g. dungeons, desert temples and clay in MineClone 2.

**Comment by anon55555** [comment]
So if you saw a structure and closed the game, then reopened it, it wouldn't be there any more.

**Comment by sorcerykid** [comment]
I seem to recall another discussion about limiting storage of newly generated mapblocks depending on the player privileges.

Anyway, I worked around this issue on the JT2 server by storing the checksums of all newly generated mapblocks. Then each month I run a command-line script that compares those stored checksums with the current map database. Any mapblocks that are still unchanged from their original state after four weeks are flagged for automatic deletion. 

Here's the checksum function I use in conjunction with the minetest.register_on_generated() callback:

```
local function get_checksum_of_area( map_data, area, min_pos, max_pos )
        -- variation of Fletcher-16 checksum algorithm
        local a = 0
        local b = 0

        for i in area:iterp( min_pos, max_pos ) do
                a = ( a + map_data[ i ] ) % 65536
                b = ( a + b ) % 65536
        end

        return a * 65536 + b    -- put first sum into upper 16 bits and second sum into lower 16 bits
end
```

**Comment by SmallJoker** [comment]
I'd like to highlight this 6 year old comment:

> Map format has no support to know if the node was created by mapgen or by user, so, i think it is very dangereous to be used...
> [...]

https://forum.minetest.net/viewtopic.php?p=163154&sid=ea2fac67111dd1ac15f65a7e605957b2#p163154

**Comment by paramat** [comment]
This is a complex feature that has been discussed a lot already, i suspect this is a duplicate but cannot find an issue yet.

**Comment by paramat** [comment]
More points:

* If unaltered mapblocks are not saved to the map database, this will require the server to repeatedly and frequently re-generate areas of a world. Mapgen is very intensive, so this would add a large load to a server, which is a big problem. Relative to this, a smaller map database size is an insignificant benefit that does not remotely compensate.

* Actually, very few areas of world will be 'unaltered', even if players do not alter them, because after mapgen game ABMs usually run, continuously altering an area, water flows into caves on lakebeds, lava flows through caves underground, mobs spawn and move around etc.
So the map database size reduction would not be as large as you might initially suspect (not that reducing map database size is a significant issue anyway).

So although this feature could be implemented, it would be insane to do so, adding a large load to servers, plus a lot of time and effort, complexity, problems, bugs.
This should be closed as being impractical.

**Comment by sorcerykid** [comment]
Thanks for the reminder about water flows and lava flows. That is a good point. I just updated my checksum function to skip all content IDs that map to "default:lava_source", "default:water_source", etc. That should help to more accurately detect unaltered mapblocks.

I'm also not concerned about ABMs, because subterranean areas comprise the vast majority of generated mapblocks on a survival server. And, at least in my experience, ABMs that set nodes usually only operate at the surface level.

**Comment by paramat** [comment]
Some more points:

Mods and games often have Lua code that runs on mapgen, this is often quite intensive and therefore causes disruptive server Lua lag. The repeated regeneration of areas will increase server Lua lag.

Mapgen is actually non-deterministic in (at least) 2 ways:
1. Because mapgen extends 16 nodes into neighbour mapchunks, the result of mapgen depends on the generation state of neighbour mapchunks, which will be different each time an area is regenerated.
2. Using multiple emerge threads makes it non-deterministic.

Non-determistic mapgen can be different each time an area is regenerated, which would be unacceptable.

So this seems to be 'can't add', as well as being impractical. So closing.
