### ISSUE TITLE
get_player_velocity() inconsistently returns non-null vector for static player

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10543]
##### Summary

`player:get_player_velocity()` returns non-null vector even if the player is not moving at all and touching ground (negative Y-component), see [this video](https://youtu.be/AGh4-vq5_Xc) - other times, it returns a constant null vector.

##### Steps to reproduce

```lua
minetest.register_globalstep(function()
    for _, player in pairs(minetest.get_connected_players()) do
        minetest.chat_send_all(minetest.pos_to_string(player:get_player_velocity()))
    end
end)
```

**Comment by SmallJoker** [comment]
This works as expected. Gravity is applied to the player at all times, resulting in minimal up/down movement until it collides with the ground and is set back to the surface.

**Comment by appgurueu** [comment]
@SmallJoker no - it inconsistently returns a non-null vector, see the video

**Comment by SmallJoker** [comment]
Then it's either floating point imprecision or right at the moment when the player collides but prior applying new acceleration -> velocity `(0,0,0)`.

**Comment by nerzhul** [comment]
is this not normal with gravity to have a little y down speed ?

**Comment by appgurueu** [comment]
> floating point imprecision

No, `-0.1` is not float imprecision

> right at the moment when the player collides but prior applying new acceleration -> velocity `(0,0,0)`

This is how it should be. The client step code first handles acceleration, then movement (and collision), and *then* it sends the player pos & velocity.

**Comment by paramat** [comment]
A small downward velocity might be expected, but -0.1 n/s does seem a little high.
I will reopen for more consideration, but am not suggesting there is a bug here.

**Comment by pyrollo** [comment]
Not tested from Lua but adding traces on many variable, including player vertical speed, I got many values around -0.5 despite player being on the ground.

**Comment by paramat** [comment]
See https://github.com/minetest/minetest/pull/10546#issuecomment-716036331 onwards for more discussion.

**Comment by appgurueu** [comment]
> See [#10546 (comment)](https://github.com/minetest/minetest/pull/10546#issuecomment-716036331) onwards for more discussion.
> 
> I am very concerned about how the 2 closed PRs were making changes to collision and movement code, because the risk is very high, while the actual issue is very minor and probably 'mostly harmless'.
> It might be fine to do nothing, any changes need long and careful consideration.

For my use case, it is not fine. I implement HUD indicators depending on player velocity. Those are now bouncing around despite the player standing still.

**Comment by pyrollo** [comment]
(Discussion continued from closed #10546 but concerns this issue)

@TheTermos said:
> That's the opposite of what I said.
> Was any of that unclear?

Sorry, I read to fast and to eager to solve issue :( :/

There is still a problem with truncation. If the player is close enough to the ground, vertical speed is kept but no move applied.
 
Adding following trace ([collision.cpp:474](https://github.com/minetest/minetest/blob/master/src/collision.cpp#L474) in `collisionMoveSimple`):
```
			CollisionAxis collided = axisAlignedCollision(box_info.box,
					movingbox, *speed_f, &dtime_tmp, (boxindex == 4) );

if (boxindex == 4) 
	printf("Box 4 collided=%d, dtime_tmp=%f, nearest_dtime=%f, top=%f, bottom=%f, speedY=%f\n",
		collided, dtime_tmp, nearest_dtime, box_info.box.MaxEdge.Y, movingbox.MinEdge.Y, speed_f->Y);

			if (collided == -1 || dtime_tmp >= nearest_dtime)
				continue;
```
When I enter the game and jump, I get:
(1)
```
Box 4 collided=1, dtime_tmp=0.005086, nearest_dtime=0.010000, top=65.000000, bottom=65.009979, speedY=-1.962000
Box 4 collided=-1, dtime_tmp=0.004914, nearest_dtime=0.004914, top=65.000000, bottom=65.009979, speedY=0.000000
```
(2)
```
Box 4 collided=-1, dtime_tmp=0.016954, nearest_dtime=0.003000, top=65.000000, bottom=65.009979, speedY=-0.588600
```

(1) seems ok, first loop detects the collision and sets speed to 0. But player bottom stays at 65.009979 instead of 65.0
(2) no collision occurs because dtime is too short, so speed is not set to 0. If player were at 65.0, collision would be detected and speed set to 0.

**Comment by TheTermos** [comment]
That's a weird spot to put a trace, you're not getting any relevant info there, just some passing temporary values and no results.

> But player bottom stays at 65.009979 instead of 65.0

These are floating point calculations, we're getting these errors no matter what.

If you want to get to the bottom of this, maybe find out where `get_player_velocity()` gets the data and work backwards from there.

**Comment by appgurueu** [comment]
> If you want to get to the bottom of this, maybe find out where `get_player_velocity()` gets the data and work backwards from there.

It gets them from `setPlayerPos`

**Comment by TheTermos** [comment]
I couldn't reproduce this effect with entities, so this seems to be player specific.

Both entities and players use the same collision code, so please, don't try to break collision unless there's a clear indication something's wrong with it.

**Comment by pyrollo** [comment]
> Both entities and players use the same collision code, so please, don't try to break collision unless there's a clear indication something's wrong with it.

I'm trying to understand. Obviously something is wrong, minor but wrong. Player on the ground should be ... on the ground, and with no speed.

The cause is very likely to be these floating point "errors" and the fact that collision system finds no collision in this gap but no move is done. I could place traces at a higher level that shows that.

I don't know the solution, probably in the move part.

**Comment by TheTermos** [comment]
In that trace speedY seems to be what comes in affected by acceleration, and in that particular spot it's perfectly fine for speed to be nonzero even when player stands still.

This effect is theoretically possible when dtime is less than 0.0001 (assuming acceleration is around 10) which occurs naturally at about 10 000 frames per second, so I'd say it's impossible enough and that's why entities are not affected.

Player is different though, the bad starts about here: [clientenvironment.cpp:192](https://github.com/minetest/minetest/blob/master/src/client/clientenvironment.cpp#L192)
What it does is chop up dtime into pieces of 0.01. The problem is with the last piece which can be very small, actually there's a comment which shows the author was aware of precision problems involved.

Still the probablility that leftover dtime is less than .0001 is around 1%, but the problem occurs around 50% of the time so something doesn't add up, or my calculations are off.

Anyway that loop looks weird and somehow eludes attention so it could probably use some review.
Instead of chopping off pieces of set duration it could just divide dtime into the smallest possible number of equal parts less than that duration.
Also it looks to me like acceleration is actually applied twice, not sure though, just eyeballing it.

**Comment by appgurueu** [comment]
> In that trace speedY seems to be what comes in affected by acceleration, and in that particular spot it's perfectly fine for speed to be nonzero even when player stands still.
> 
> This effect is theoretically possible when dtime is less than 0.0001 (assuming acceleration is around 10) which occurs naturally at about 10 000 frames per second, so I'd say it's impossible enough and that's why entities are not affected.
> 
> Player is different though, the bad starts about here: [clientenvironment.cpp:192](https://github.com/minetest/minetest/blob/master/src/client/clientenvironment.cpp#L192)
> What it does is chop up dtime into pieces of 0.01. The problem is with the last piece which can be very small, actually there's a comment which shows the author was aware of precision problems involved.
> 
> Still the probablility that leftover dtime is less than .0001 is around 1%, but the problem occurs around 50% of the time so something doesn't add up, or my calculations are off.
> 
> Anyway that loop looks weird and somehow eludes attention so it could probably use some review.
> Instead of chopping off pieces of set duration it could just divide dtime into the smallest possible number of equal parts less than that duration.
> Also it looks to me like acceleration is actually applied twice, not sure though, just eyeballing it.



> In that trace speedY seems to be what comes in affected by acceleration, and in that particular spot it's perfectly fine for speed to be nonzero even when player stands still.
> 
> This effect is theoretically possible when dtime is less than 0.0001 (assuming acceleration is around 10) which occurs naturally at about 10 000 frames per second, so I'd say it's impossible enough and that's why entities are not affected.
> 
> Player is different though, the bad starts about here: [clientenvironment.cpp:192](https://github.com/minetest/minetest/blob/master/src/client/clientenvironment.cpp#L192)
> What it does is chop up dtime into pieces of 0.01. The problem is with the last piece which can be very small, actually there's a comment which shows the author was aware of precision problems involved.
> 
> Still the probablility that leftover dtime is less than .0001 is around 1%, but the problem occurs around 50% of the time so something doesn't add up, or my calculations are off.
> 
> Anyway that loop looks weird and somehow eludes attention so it could probably use some review.
> Instead of chopping off pieces of set duration it could just divide dtime into the smallest possible number of equal parts less than that duration.
> Also it looks to me like acceleration is actually applied twice, not sure though, just eyeballing it.

**Comment by appgurueu** [comment]
misclick
