### ISSUE TITLE
Android: Buttons icons/GUI too small

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10554]
##### Minetest version
5.3.0 (android)

##### OS / Hardware
Operating system: android 6.0.2

##### Summary
Buttons are too small
![Screenshot_20201025-203107.png](https://user-images.githubusercontent.com/55009343/97107187-2d754b80-1701-11eb-9ce9-084669cff7c5.png)![Screenshot_20201025-202929.png](https://user-images.githubusercontent.com/55009343/97107211-4f6ece00-1701-11eb-855c-580d90575caa.png)
##### Steps to reproduce
Run a android client

**Comment by Andrey2470T** [comment]
I think the problem is that your screen size is just enough small. My phone`s one is ~ 6 inches and to me it is not hard to tap on.

**Comment by Emojigit** [comment]
> I think the problem is that your screen size is just enough small. My phone`s one is ~ 6 inches and to me it is not hard to tap on.

Then I think the main menu shout change its size when the screen is too large/small

**Comment by Andrey2470T** [comment]
>Then I think the main menu shoud change its size when the screen is too large/small
>
I think the main menu looks like already large on the limit on Android version. It is just an unavoidable problem.

**Comment by paramat** [comment]
I assume this issue is about buttons too small for the text, not too small for fingers?
If so, this happens on desktop too if you reduce game window size small enough, so is not really an Android problem. A workaround is to reduce font size.
I am fairly sure the 'text too big for buttons' problem is discussed in another issue, this is probably a duplicate.

**Comment by MoNTE48** [comment]
This has nothing to do with font size and can be fixed very easily.
This is an Android problem because we have a very small _touchscreen_ with a very high resolution (and high by Desktop standards) ppi.

**Comment by srifqi** [comment]
If this issue is in-game ContentDB-spesific, is it still a problem in 5.7.0 version?

<details>
<summary>1600×900 screen (240 DPI)</summary>

![In-game ContentDB on Minetest Android 1600x900](https://github.com/minetest/minetest/assets/4017302/a2eff168-a687-47fb-b885-67163b23f3f4)
</details>

<details>
<summary>1920×1080 screen (240 DPI)</summary>

![In-game ContentDB on Minetest Android 1920x1080](https://github.com/minetest/minetest/assets/4017302/1637a17a-1f9f-4fec-8b27-19b4d1238878)
</details>

<details>
<summary>2560×1440 screen (320 DPI)</summary>

![In-game ContentDB on Minetest Android 2560x1440](https://github.com/minetest/minetest/assets/4017302/3e3f0a62-7afb-4bdc-850e-15273cf3dd57)
</details>

(Tested on BlueStacks)
