### ISSUE TITLE
Adjustable Day/Night Ratio

### ISSUE THREAD

**Issue by Miner48er** [minetest/minetest#1063]
add conf option to allow longer/shorter day or night ratio

**Comment by paramat** [comment]
Should be left closed. What PilzAdam said. Also, this should be discouraged because cosmologically it would mean the Minetest world changes it's rate of spin twice per day.

**Comment by mwrsa** [comment]
Sorry, but this is nonsense. Where do you live, do you all have equally long days and nights?
Simply use a different approach to solve this without changing the speed: There must be a definition in the game at what points dusk or dawn set in. Make that configurable - done. Also this is basic functionality that should not need any mod to work. Other stuff with much less importance (meaning less fundamental) makes it into the game, while this is rejected?

**Comment by nanepiwo** [comment]
I agree that the sunrise/sunset times should be configurable, and then a mod can easily be made to create more-realistic, changing sunrise/sunset times if they desire.

**Comment by mwrsa** [comment]
It could be defined in night_length in the usual decimals. E.g. 800 would mean 8 hrs. full darkness, with dusk ending at 2000 and dawn setting in at 0400. Just my idea of the matter.

**Comment by numberZero** [comment]
Remember that visible sun speed (caused by Earth spin) is constant (15° per hour) and equal to visible moon (and stars) speed. So if you don’t want it to look weird, you have to change the sun trajectory to more realistic too, so that these speeds remain equal.

**Comment by Ferk** [comment]
In real life Moon and Sun have different trajectories and speeds across the sky (some days may even have the moon show up in the sky during daylight and hide in the horizon at night), and the angle of the axis in which the earth rotates makes the daytime different than the nighttime depending on the position across the year and how close to the poles you are.

Not saying that Minetest should replicate this. But certainly it's perfectly natural and not weird. The opposite might be more true.

**Comment by mwrsa** [comment]
So seasons and stuff like that are not even worth discussing? Well ok. Just wipe it off like that. Duh. I rest my case.
Still pledging for a reopen.

**Comment by paramat** [comment]
Worth discussing yes, also see #1997
Time speed should remain constant, because you wouldn't want the sky to rotate faster during the day.

As far as i can visualise it, a cube will always have equal night and day lengths whatever the orientation of its axis to the sun, even though the sun can appear lower in the sky. The unequal day and night seems to come from Earth being a sphere.
Essentially, unequal day and night, and therefore probably also seasons, don't make sense for the MT cubic cosmology
> Simply use a different approach to solve this without changing the speed: There must be a definition in the game at what points dusk or dawn set in. Make that configurable - done

That wouldn't work if time speed is unaltered because sun and moon need to be on the horizon at those times, so they would then need to shift their positions (relative to skybox and stars) twice a day.
> Also this is basic functionality

Not remotely basic, for a cube planet with no axial tilt this behaviour is (literally) alien.
> So if you don’t want it to look weird, you have to change the sun trajectory

It seems that still won't work as i may have realised above.

If MT was a spherical planet with axis tilt this feature would make sense, and be possible. But since it isn't there's no point is trying to reproduce it, you're lookng for a different and more realistic game.
Best this is hacked using a mod and time speed, in fact that's the only way to do it.

**Comment by numberZero** [comment]
@paramat MT world is only 60 km in each direction, far too little for a planet.

> the MT cubic cosmology

WTF? Sorry, but don’t forget MT is a game engine, not a game.
