### ISSUE TITLE
Retrieve DPI from get_player_information

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#10632]
Problem: font size appears to be much bigger on Windows than on Linux with the same settings. This is problematic when a fixed font size is set on some strings using `style*[]`, it may look good for Linux users but not on Windows or vice versa.

Solution: get the OS info from `get_player_information`

@v-rob @sfan5

**Comment by sfan5** [comment]
What you're seeing is not about Windows, it's DPI scaling.

It'd make sense to expose screen resolution and/or DPI to get_player_information.
Or better yet, maybe some combination (window size adjusted by DPI?) so modders don't have too many variables they need to work with.

**Comment by v-rob** [comment]
This is why absolutely sized fonts aren't recommended.  I should have put that somewhere in `lua_api.txt`.  If the problem can be solved with relatively sized fonts, I would say do that.  However, I think I heard that there was a problem with DPI scaling or it being fixed to an arbitrary number on Windows or something, although I can't verify that for certain.

Exposing window size to the server in any way isn't a good idea because the window size can change at any time so it could get invalidated or change without the server knowing.  DPI isn't likely to change, so that might be OK.

**Comment by sfan5** [comment]
> However, I think I heard that there was a problem with DPI scaling or it being fixed to an arbitrary number on Windows or something

Not anymore, I fixed that in #9586.

**Comment by kilbith** [comment]
> This is why absolutely sized fonts aren't recommended. [...] If the problem can be solved with relatively sized fonts, I would say do that.

I mentionned above: _with the same settings_ on both Linux or Windows. There's no Windows-specific default font size anymore. Absolute or relative sizes do not fix the issue.

**Comment by kilbith** [comment]
For the posterity:

- https://stackoverflow.com/a/2621524
- https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getdpiformonitor?redirectedfrom=MSDN

**Comment by sfan5** [comment]
DPI scaling is implemented for both X11 and Windows and for me it behaves identically on the same hardware. If the font sizes don't match, either your configuration is different or there is another bug.

**Comment by hecktest** [comment]
Is the DPI setting in .conf still supposed to work? It doesn't for me any more, it's stuck at 96 no matter what the value is. Maybe that's the actual problem.

As for the original request, sniffing the OS and window size is kinda creepy. I don't like when browsers do it, a block game should probably not be doing it either. This info is worthless anyway because it can be spoofed.

**Comment by hecktest** [comment]
Alright, I just tested, and on Win 7 the game just inherits the system DPI without using the .conf setting at all.

**Comment by sfan5** [comment]
> Is the DPI setting in .conf still supposed to work? It doesn't for me any more, it's stuck at 96 no matter what the value is. 

It's only read as fallback, this is suboptimal I know.

**Comment by kilbith** [comment]
> This is why absolutely sized fonts aren't recommended.

This is the same problem with relatively sized fonts: the same font size looks different over different OSes. Moreover, `font_size=+<number>/-<number>` is based off the default **user-set** font size, not the compile-time one.

Accessing the DPI setting from `get_player_information` is _still_ essential to make perfectly scaled GUIs on all setups.

**Comment by v-rob** [comment]
> This is why absolutely sized fonts aren't recommended.

The reason I said this is not to say that it fixes this specific problem, but because it accommodates the user.  Some people don't have very good eyesight and need larger fonts, or they just prefer a smaller or larger font.  By forcing a font size in a GUI, that GUI automatically doesn't accommodate those people.

In addition, even the DPI won't solve the problem.  People can set their own font, like a Minecraft-esque pixelly font or a more cursive-like font, use the monospace font, or have a language that requires the fallback font.  I've seen all of these myself.  A GUI that works with one font won't work with the others.  The fact is that it's never possible to make an absolutely-sized GUI like formspecs work with everyone's font.  This is why I say that relative fonts are best.  If you need big text, do `*2`.  If you need small text, use `*0.75`.  The user's font size will determine the rest.

However, this doesn't mean I'm automatically against exposing DPI information.  It sounds like it could be a good idea, especially for the HUD.  On the other hand, exposing the OS doesn't sound like a good idea and isn't the real root cause of the problem here.

**Comment by kilbith** [comment]
> People can set their own font

Then it should be also possible to know the font size in pixels. Freetype provides it: https://www.freetype.org/freetype2/docs/tutorial/step2.html

**Comment by kilbith** [comment]
Also it's better to increase `gui_scaling` than `font_size` if you have poor eyesight. That way, fonts are still consistent with the rest of the GUI.

**Comment by v-rob** [comment]
> Also it's better to increase `gui_scaling` than `font_size` if you have poor eyesight. That way, fonts are still consistent with the rest of the GUI.

Quite true, although `gui_scaling` has its own problems like making the form bigger than the screen.  However, there's still the problem of choosing other fonts than the default.

> Then it should be also possible to know the font size in pixels.

The difficulty is that a font size in `get_player_information` will only apply to one font, and not a font with a different `font_size`.  Also troublesome is the fact that formspecs are in coordinates, not pixels, and the coordinate is variable size depending on the overall size of the formspec.  I'm still trying to figure out potential ways to do this for the formspec replacement as well without SSCSM, but there might not be a good way.

I'm afraid there really doesn't seem to be a good way to have GUIs work absolutely perfectly on all platforms without proper layouting and/or SSCSM, although DPI and screen size could perhaps alleviate some of the problems.

**Comment by ExeVirus** [comment]
So what's left to get this into a merge-able state?

**Comment by erlehmann** [comment]
> Problem: font size appears to be much bigger on Windows than on Linux with the same settings. This is problematic when a fixed font size is set on some strings using style*[], it may look good for Linux users but not on Windows or vice versa.
> 
> Solution: get the OS info from get_player_information

I believe such a facility can and will be abused in a similar way that user agent strings are.
