### ISSUE TITLE
readFlagString uses str[0] which is undefined behavior when the string is empty

### ISSUE THREAD

**Issue by xyzz** [minetest/minetest#1064]
https://github.com/minetest/minetest/blob/a58b47d0f6f9b0838a16d8316b2b33c832820d80/src/util/string.cpp#L113

It's also not clear to me whether the C++ standard guarantees memory layout this code depends on.

**Comment by kwolekr** [comment]
Going through old issues and saw this.
Technically this isn't UB unless the CRT does dumb things.  See 21.4.5, titled "basic_string element access":

```
const_reference operator[](size_type pos) const;
reference       operator[](size_type pos);
    Requires: pos <= size().
    Returns: *(begin() + pos) if pos < size().  Otherwise, returns a reference to an
    object of type charT with value charT(), where **modifying** the object leads to
    undefined behavior.
```

`&str[0]` does get passed along to strtok_r, which requires a mutable `char *`: however, since char() == '\0', and '\0' cannot be used as a token in strtok, this usage of &str[0] would be safe unless the CRT attempts to write outside of the string, in which case it would be undefined behavior anyway.
