### ISSUE TITLE
ObjectRef:set_pos allows to teleport out of map bounds

### ISSUE THREAD

**Issue by randomMesh** [minetest/minetest#10673]
##### Minetest version
Minetest 5.4.0-dev-f1d72d212 (Linux)

##### Summary
The /teleport chat command checks if one wants to teleport out of the map and prevents this.
However, the `ObjectRef:set_pos` lua command does not and it's possible for mods to teleport the player out of the world, rendering them unable to move.

![screenshot_20201127_221807](https://user-images.githubusercontent.com/32773707/100485056-fd093e80-30fe-11eb-9908-dc356868abd6.png)

##### Steps to reproduce

```lua
minetest.register_on_joinplayer(function(player)
	minetest.after(3, function()
		player:set_pos({ x = 30930, y = 90, z = 30930 })
	end)
end)
```

I suggest to clamp the coordinates in `ObjectRef:set_pos` to the world boundaries.

**Comment by NathanSalapat** [comment]
I don't think this is a bug. A modder should never try to teleport a player out of the world. If some mod does this it's the mods fault, not the engine.

**Comment by randomMesh** [comment]
You're right, this is not a bug in the engine but i think it should nevertheless check for invalid coordinates when using its API.
Maybe call it a "must-have-feature".

**Comment by LoneWolfHT** [comment]
Could make it drop a warning at the least

**Comment by hecktest** [comment]
Any check for this will be more expensive than the setter itself. How about you just do the check yourself if you really need to? It's not "must have" at all.

**Comment by SmallJoker** [comment]
"map bounds" are defined by:

 * `MAX_MAP_GENERATION_LIMIT`: approximate limit of `s32`
 * setting `chunksize`: limitation caused by the outermost mapgen chunk
 * setting `mapgen_limit`: custom map generation limit

These are all very vague, especially the third which is a soft limit. i.e. if there's map data outside that range, it'll sill be loaded and may be modified. It only affects the map generator.
Whereas such a check might be helpful for modders, it would require to check these three points above and load the containing mapblock to see whether it's possible to move the player there. For the same reason as https://github.com/minetest/minetest/issues/10673#issuecomment-735250429 I'd prefer to have this solved in Lua rather than C++. Doing it correctly is far too complex for a setter function.

**Comment by randomMesh** [comment]
> Doing it correctly is far too complex for a setter function.
I see. What about a helper function in the lua API then?
Something like `minetest.isPosValid()` which can be called by mods? This would simplify checking the coordinates for sanity a lot.

**Comment by paramat** [comment]
I agree with NathanSalapat and SmallJoker, and SmallJoker is correct.

It is the modder's resonsibility to be careful where they move an object. It is entirely wrong to unnecessarily limit an API in this way. APIs are not player-facing.
All co-ordinates out to S16 min/max (roughly +-32768) are always valid.
'Map bounds' is hard to define, moving objects outside this may be desired and should be possible in an API.
'mapgen_limit' can be, and is, varied for worlds. This means functioning world can exist outside of 'mapgen_limit'. This makes it difficult to define or check what is 'out of bounds'.

Perhaps the correct check for a helper function would be if the destination is "ignore" nodes or not. However, what qualifies as an acceptable destination probably depends on the modder's intentions, and such a check is easily coded in a mod anyway.
How do we decide what is an acceptable destination? It depends on the modder's intentions.
So i think any one helper function is not of much use for most uses and is probably not worth doing.

**Comment by randomMesh** [comment]
Ok guys, thank you for your feedback. I'll make a mod which does the sanity check then.
Closing this now.
