### ISSUE TITLE
DISCUSS: should get_look_dir() take in account camera offset?

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#10725]
So, the other day I tried for the first time `set_eye_offset()` and I was super happy because I ended up with this
![imagen](https://user-images.githubusercontent.com/63455151/102494754-71d3f680-4075-11eb-8147-37ae3838a174.png)

As you can see, the crosshair correctly reveals collisions:
![imagen](https://user-images.githubusercontent.com/63455151/102495164-0f2f2a80-4076-11eb-894e-e6217f9c23a8.png)

But raycasts called from the player's very eyes such as
```
local pos = player:get_pos()
local pos_head = {x = pos.x, y = pos.y+1.475, z = pos.z}
local dir = player:get_look_dir()
local p1 = vector.add(head_pos, vector.multiply(dir, 0))
local p2 = vector.add(head_pos, vector.multiply(dir, 50))

local ray = minetest.raycast(p1, p2, true, false)
```
don't go towards the chrosshair. Instead, they follow the "standard" line of sight of the player, like if there were no offset (the small pink dots are particles generated by the raycast)
![imagen](https://user-images.githubusercontent.com/63455151/102495846-eeb3a000-4076-11eb-8e79-dc2b011e19b9.png)

I didn't label it as "feature request" because this is more about an inconsistency: items range acts following the crosshair but players' look direction doesn't. What to do?

EDIT: I only tested it in 5.3

**Comment by SmallJoker** [comment]
I believe what you need is `get_camera_pos` rather than `get_pos`.

**Comment by Zughy** [comment]
It's more than that. If I shoot, I expect the bullets to start from the player and not from the centre of the camera (when it has an offset). To do that, if I had a `get_camera_pos()` AND a `get_camera_dir()` (as the character is a bit tilted), I should cast a ray straight from the camera position and then detect the first collision it encounters - AKA where the crosshair is pointing. Then, in order to draw the particles, I should have a particle trail starting from the player's head, going towards the crosshair (so where the camera raycast landed).

Also, let's take the last screen: if my item had a `range = 100`, I'd been able to select the guy because it considers where the crosshair is. On the contrary, with a raycast it doesn't, because it's perpendicular according to the player position

**Comment by rubenwardy** [comment]
It sounds like the problem you raise is that `get_look_dir()` returns the look direction of the camera and not the player. This is correct, get_look_dir is documented as:

> * `get_look_dir()`: get camera direction as a unit vector

The direction from the player to the crosshair is something different and requires a raycast from the camera - due to parallax

**Comment by paramat** [comment]
I think 'no'.
Rubenwardy makes some correct points. There are misunderstandings here.

`get_look_dir()` is documented as camera direction, and it is also player model head direction, because both point in the same direction. Whatever camera offset you use, the direction returned by the API is correct for both.
So the API behaves correctly and does not need not be changed. And there is no inconsistency.

Direction from player model eyes to current selection is something completely different and is a different direction to look direction of camera and player model. If you want an API to return that it has to be a new API.
In the absence of this new API, any problems you experience (such as those described) due to using camera offset should be dealt with in mod code.

Your suggestion would actually make `get_look_dir()` behave incorrectly.
When you use a camera offset, the player model no longer looks in the direction of the selection, while the camera does, this is clear in your 2nd screenshot. But the existing API should continue to return the correct look direction for camera and player model.

Perhaps you could change the issue title to request a new API instead?

Note: The crosshair is not a point in space, it marks a ray from the camera. The current selection is a point in space and is where that ray crosses a selectable node or object.

> It sounds like the problem you raise is that get_look_dir() returns the look direction of the camera and not the player.

Both directions are the same, the API returns the correct look direction for both. When you use a camera offset, the player model no longer looks in the direction of the selection.

**Comment by Zughy** [comment]
I understand more clearly now, thanks everybody. So yeah, I guess something like `get_crosshair_intersection_point()` ? Quite a long name though

**Comment by hecktest** [comment]
You can call it `get_pointed_thing`.
Ultimately, a function like that would have to perform a raycast, so it wouldn't be any better than doing the raycast yourself, only saving you a bit of math.
