### ISSUE TITLE
Quick-configure controller input

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#10728]
@m42uko
Regarding issues outlined in #10624

A correct solution to the problem of differences between controllers would be to provide a "configure all" dialog,
where the player is asked to press every button and tilt every axis in sequence. That way you won't have to rely on external databases of controllers, and setting up takes a few seconds.

Because _some_ controller manufacturers insist on using a shared analog axis for L2/R2 (utter idiocy), any half-axis must be mappable as a button, and any button must be mappable as a half-axis in order for all controllers to work. This is best done by abstracting controller input behind a layer of virtual axes and buttons.

With both of those implemented, controller support could finally be considered a done feature.

**Comment by rubenwardy** [comment]
The configuration part of this is a prerequisite for a solution based on controller mapping databases. It's also good to allow players to remap their controllers.

Generally, users don't want have to set up their controllers - especially if it's common - so having a DB would be a good idea

So, the first step would be to add the ability to rebind controller mappings and such - without a setup UI or database. It's required for either approach

**Comment by hecktest** [comment]
A controller DB wouldn't be a good idea.
Databases pose numerous problems:
- It must be a sizeable blob on the user's hard drive.
- If it's not on the user's hard drive, you must **phone home** for it - many users won't like it.
- If it comes from a third party like another project maintaining such a database, its format might be of limited use to us. It might also be incomplete.
- If the database is our own, we might not have enough users for it to matter.
- If the users do not supply the maps willingly, are you going to **phone home even more** to get their configs?
- Nobody can verify the correctness of a mapping without owning the same controller - DB poisoning is possible.

A well executed quick-config dialog provides like 80% of the utility of a database. It takes between 10 and 40 seconds to fully map a new controller in this way, just press every button in sequence as prompted. This method requires no connectivity or storage.

Mapping virtual buttons manually in .conf can be a stepping stone, but it's not something you should expect an average user to bother with, it's very tedious and requires knowing the exact indices and polarity of your controller's buttons and sticks.

**Comment by m42uko** [comment]
I completely agree with @rubenwardy here. The infrastructure created for the controller DB is a prerequisite for the GUI mapper anyways. The DB itself is the smallest part here (in terms of effort). So it makes sense to start with it.

@hecktest, Let me quickly go through your concerns:

First of all, I completely agree with you here: **No phoning home**. My goal would be to integrate the DB into the release, meaning that, if new controllers come out, it'll take until the next release until they're supported. I think this is acceptable and gets rid of the whole phoning home thing. Also, I highly doubt the controller DB will be a *sizable blob*. From what I've seen so far, these are usually no more than a few hundred kilobytes at most.

Then, regarding how to fill it, I would want to rely on an external DB such as [SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB) (still need to look into what else is available). Yes, theoretically, it can be poisoned, but the larger the user base the less likely it is. And even if it is poisoned, so what? Then that specific controller will be broken, which it would have been anyways without the DB. If it's not 100% complete for our purpose, we can "dynamically" extend it, but I'd like to have *something* rather than *nothing*.

With all that being said, I 100% agree with you that, for feature completion, we definitely need a good GUI dialog to customize the controller bindings. It's just that I think the DB (and infrastructure for it) should take priority for now.

> using a shared analog axis for L2/R2 (utter idiocy)

Ugh, what the?! That honestly sounds like a pretty rare case, and like something that wouldn't even by supported by most other games on the market, so I doubt we'd really have to support this. Do you have some examples?

**Comment by hecktest** [comment]
> Ugh, what the?! That honestly sounds like a pretty rare case, and like something that wouldn't even by supported by most other games on the market, so I doubt we'd really have to support this. Do you have some examples?

_Every Microsoft controller, and any controller that attempts to emulate one_. I'm serious. This dates back to the original Xbox controller and how its L/R were in fact one seesaw axis, but XInput controllers on Windows still carry that quirk whenever they are translated to DInput. I have no idea if Xbox games and other native XInput users suffer from this, but as a generic controller, XInput is definitely crippled. Sadly, other popular drivers like WinSCP propagate this error by pretending they are XInput devices. (Say what you want about the chinese adware DS3 driver but at least it'll map to damn near anything)

Also, depending on the input API used, directional buttons may be translated to analog axes despite physically being buttons, because they're often mapped as something called a "POV hat". This is another case where a half-axis might need to map to a button.

Then there's controllers that actually have analog buttons, like every Sony controller - with the right driver, literally every button can be an axis.

Other controllers with soft buttons or triggers also exist - anyone attempting to use those might be at the mercy of the adapter to determine whether those are one axis, individual axes, or buttons, or sometimes _both at once_.
