### ISSUE TITLE
Registering colon (":") as a node name causes permanent map breakage.

### ISSUE THREAD

**Issue by random-geek** [minetest/minetest#10769]
##### Minetest version

6d7067fd37a8084aca139ecab552982e0ee99582

##### OS / Hardware

Operating system: Windows 10 64-bit
CPU: AMD Ryzen 7 1700

##### Summary

Minetest allows mods to register a node with only a single colon (":") as a name. Joining a world with this node registered causes wrong and unknown and nodes to appear everywhere, along with errors about missing name-ID mappings. The problems persist even after disabling the mod.

##### Steps to reproduce

Make a new mod, and paste this into init.lua:
```lua
minetest.register_node(":", {})
```
Create a new world (I used devtest) and enable the test mod, then join the world. There should be unknown nodes everywhere.

**Comment by rubenwardy** [comment]
This is expected and fine. `:` disables name checks

**Comment by rollerozxa** [comment]
My hypothesis for the world being covered in unknown nodes is because it is putting a dust biome layer with 1 node layer of "" on top, hence why it doesn't appear in i.e. snowy biomes with an actually defined dust node.

Normally it wouldn't do anything but when "" is a node it now starts placing nodes there, which act strange and has the possibility of taking the look of any other loaded node when I was testing it.
