### ISSUE TITLE
Client and Server sometimes do different position and velocity calculations

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#10825]
Latest.

On a slow server this:
https://github.com/minetest/minetest/blob/5.3.0/src/collision.cpp#L248

will cause client and server to come to different velocity and position calculations leading to visible jumps where there is some server lag (slow Lua). It's not uncommon to have server dtime of more than 0.5s, it's, however, very unlikely on the client.

I propose we remove that 0.5s limit (or replace it with something more reasonable.)

This is in part related to #10739, but not directly.
(I think #10739 is by just a laggy server. The client gets ahead and when it sends the new player pos the server is behind on updating the attached entity.)

Edit: This is relevant when the player is attached to an entity.

**Comment by Zughy** [comment]
I don't know if it's related but on my server there is an item allowing players to bounce ([code](https://gitlab.com/zughy-friends-minetest/block_league/-/blob/master/bl_weapons/bouncer.lua)). We noticed that if the PC of the person who's using it is a bit of a toaster, most of the times it allows you to jump higher than the ones having a decent PC

**Comment by TheTermos** [comment]
> I propose we remove that 0.5s limit (or replace it with something more reasonable.)

Please don't go there.
Dtime limit is necessary, lifting it would make things even worse.

Client and server always come to slightly different results, that's unavoidable, natural consequence of client and server step times being independent and of different duration.
What you perceive as lag client side - warping, ejecting, that's mostly visual glitches that get corrected via updates because of the limit, the only thing removal of the limit would accomplish is that those visual glitches become reality.

Actually if it were up to me I'd lower the limit even more, 0.5s translates to an uncontrolled move of 2 nodes (at Standard Minetest Velocity of 4n/s) which can already make a life/death difference, and it gets way worse when acceleration comes into play, with dtime that long entities can unintentionally go supersonic.

That's about entities, player is a different story and totally fubar because of being controlled client side which is probably the worst of all MT faults.
But **player isn't affected by this limit** as their dtime is chopped up in pieces of max 0.01s before being passed to collision detection.

**Comment by hecktest** [comment]
I'd rather fix the reasons why the delta ever reaches 0.5s in the first place.

**Comment by TheTermos** [comment]
> I'd rather fix the reasons why the delta ever reaches 0.5s in the first place.

Exactly.
Well, some of that is mods' fault, but even on a clean local singleplayer world dtime periodically exceeds 0.6. I suspect that may have to do with map generation, good idea to track it down.

**Comment by lhofhansl** [comment]
Try MineClone2. Most server steps take more than 0.5s especially when parts of the map have to be generated. Together with attachment anti-cheat it is basically broken; the position of the play is constantly reset and there's almost no progress.

The current system is broken and we no control over any of the mods/games. Any better proposals?

**Comment by lhofhansl** [comment]
> But player isn't affected by this limit as their dtime is chopped up in pieces of max 0.01s before being passed to collision detection.

@TheTermos in my case the player is, because (s)he is attached to an object. I forgot to mention that part.

**Comment by TheTermos** [comment]
> Try MineClone2. Most server steps take more than 0.5s especially when parts of the map have to be generated. Together with attachment anti-cheat it is basically broken

I feel for you but there's only so much you can do about broken mods/games. Recently I accidentally caused an infinite loop in lua, not only it brought the server to a halt, but the entire operating system, which is probably not a good thing.
On servers running MCl2 I've seen they usually slow the mob spawn ABMs down to a crawl, or remove mobs altogether, hope that helps.

> @TheTermos in my case the player is, because (s)he is attached to an entity. I forgot to mention that part.

You can't win with that kind of lag, jumpiness is expected, also the attachment code seems still buggy.

> That not how it works, though. CollisionMoveSimple will find the `nearest_dtime` of a collision, whether you limit dtime or not.

Let's just get it out of the way: unlike you, I do understand how CollisionMoveSimple works, more or less ;)
This issue is one of many shots in the dark in attempt of fixing player related issues in places where player related fixes don't belong, that is in collision.cpp . This is how localplayer is malicious cancer spreading the disease to less FUd parts of the code.

Trust me, increasing the limit isn't the solution, it'll make everything worse for everyone.
Instead let's look for actual causes of attachment issues and server lag.

**Comment by lhofhansl** [comment]
Fair enough. I'm not claiming I understand the collision code. It's a lot of code! :)

It's just that the issue here is not really whether we limit the dtime or not, but that instead the more client and server come to the same position the less jumpy it would be.
I do not mean this inflamatory but I feel that is standard game programming: Physics behave correctly even when the machine is too slow. Time moves independently from the physical time on the machine.

In my case with a player attached to an entity the server will still reset the player position, but it is much closer to what the client arrived at, and the jumping is far reduced. It's the difference between completely useless to acceptable.
That was by simply removing the dtime limit. Collisions are still calculated correctly because it is taking the trajectory of the entity in account. In fact it seems that with the limit we'll make collision detection less reliable as the server now works off an incorrect speed. I really do not see the point of that.

I hear what you are saying about local player, I do not see a good way out of that.

FWIW, I have been looking at server lag from various angles in the past year or so and fixed a bunch of issues. I reducing blocks being resent to the client, improved the ABM time budget, fixed multithreaded mapgen, etc. The latest are using zstd for compression and/or asynchronous map compression to reduce lag from compression. And I am thinking about how to allow mapgen Lua code to run asynchronous to the server step.

**Comment by TheTermos** [comment]
> It's just that the issue here is not really whether we limit the dtime or not, but that instead the more client and server come to the same position the less jumpy it would be.

I understand what you're saying, and in fact, in a trivial sense it's true that removing the limit would make client and server more in sync in certain situations, but it would also otherwise cause a server side catastrophe,
so yeah the client and the server would be more in accordance in a more catastrophic kinda way.

**Comment by lhofhansl** [comment]
Thanks for discussing. I mean it.

> but it would also otherwise cause a server side catastrophe

This is the part I do not understand. The server has a time, acceleration, and velocity, and from that it does its calculation, including collision.
What is the catastrophe? (that's a real question, not rhetorical :) )

**Comment by TheTermos** [comment]
Imagine you want an object to walk up to a node then turn left, so you set some velocity ad wait for it to reach the waypoint, but then there's a lag spike, the move lasts for 2 seconds, so the object moved 8 nodes past the target during a single step and now it is who knows where.
Or you want to make it jump, so you set some velocity upwards, let's say 6. but there's a spike and dtime gets more than a second gravity is 10 so velocity becomes negative. Yup, it won't budge.
Or you want a moving object to decelerate nice and smooth, so you set some acceleration opposite to velocity and wait for velocity to reach certain threshold, but there's a spike, acceleration works for 2 seconds straight, the object just gets blown back with great force flying like a bullet in the opposite direction.

So now with your fix objects randomly teleport to wtf places, but it also made objects uncontrollable via scripting, so nobody's using them, no objects for you to attach a player to and have issues, nobody sees evil, everybody's happy.

I've been working with entites and I'm telling you, 0.5 is already too long and causes hell of a problem.

**Comment by lhofhansl** [comment]
Fair enough. I guess there's no good way to deal with large server spikes.
I guess we could at least try to catch up - i.e. if we limited dtime once, remember how much we lost and try to catch up if there is lower lag soon.
In any case, closing this one.

**Comment by lhofhansl** [comment]
Just for completeness, I improved this for my case by reducing the generate emerge queue and number of emerge threads. Now map generation is severely slowed down, but the server lag is too.
