### ISSUE TITLE
List styling exception

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#10866]
Engine commit: https://github.com/minetest/minetest/commit/8dae7b47fcc1c26251c8006efbc9ee8af152f87a

Test code: `style_type[list;size=0.01;spacing=0]` and hover the list.

```
Thread 1 "minetest" received signal SIGFPE, Arithmetic exception.
0x000055555582ca86 in GUIInventoryList::getItemIndexAtPos(irr::core::vector2d<int>) const()
```

@v-rob

**Comment by v-rob** [comment]
This PR has a depressingly embarrassing amount of errors.  See, I didn't test the PR that much because there had been three PRs previously made, so I was just continuing them.  I expected those to have had testing by that point, so I didn't do tests that were as comprehensive as I normally would have, but I was quite wrong.

This is probably a divide by zero error, and the other issue is another imgsize vs slot_size error.  I will put out a fix PR tomorrow, and I will wait for more testing before merging that.

**Comment by Desour** [comment]
The code doesn't handle sub-pixel sizes:
https://github.com/minetest/minetest/blob/8dae7b47fcc1c26251c8006efbc9ee8af152f87a/src/gui/guiInventoryList.cpp#L222-L223
