### ISSUE TITLE
Connected fence gates Z-Fighting at mapblock boundaries.

### ISSUE THREAD

**Issue by MysticTempest** [minetest/minetest#10910]
##### Minetest version

```
Mientest v5.4-dev 
Git commit, & newer: 6d7067f
```

##### OS / Hardware

Operating system: Ubuntu Linux 18.04
CPU: AMD Phenom(tm) II X6 1035T Processor

GPU model: AMD Cayman PRO [Radeon HD 6950]
OpenGL version: 4.3

##### Summary

The connected fence gates from 'minetest_game' are having very noticeable Z-Fighting issues at mapblock boundaries. 

So far it seems to only affect those nodes, but it's caused by a change in Minetest. So hopefully this is the correct place for the report.

##### Steps to reproduce

On this commit is where the gates start Z-Fighting:
https://github.com/minetest/minetest/commit/6d7067fd37a8084aca139ecab552982e0ee99582

On the previous commit before that one, everything is fine:
https://github.com/minetest/minetest/commit/07e0b527cf3e6e4f1bf36823940216efef59d8c9

---
Steps in-game:

1. Create a new world in Minetest Game.
2. Give youself Jungle, and Aspen Fence Gates; the color difference makes the Z-Fighting extra noticeable.
3. Start placing so they connect to each other along mapblock boundaries(position multiples of 16). 
	Example coordinates: (0 0 0) or (16 0 16)
	See the constant flickering of the Z-Fighting.

5. Build a short ways away, & see the older/expected behavior like in v5.3
	Textures will occasionally flip to the neighbor's node texture. But, it will be a smooth, and instant transition.

---
Preview of z-fighting:

![screenshot_20210203_181551](https://user-images.githubusercontent.com/32621758/106826182-01485f80-664c-11eb-9354-4ba87909d83c.png)

**Comment by SmallJoker** [comment]
@hecktest Do you have an idea what's going on there?

**Comment by An0n3m0us** [comment]
I feel like I might be missing something here, but I'll post my thoughts anyway;

To me, the glitching is not surprising, but why they _don't_ glitch in 'normal cases' is surprising.

The fence gate are models, and they overlap when they are placed next to each other (right?).

So that's why they are glitching. The faces of both fence posts are overlapping.
Here's an example in a 3D software:

![image](https://user-images.githubusercontent.com/49789044/106924675-382f7b80-6707-11eb-8e60-6dbeb2c54853.png)

Same thing in Minetest (but the glitching only occurs at the coordinates mentioned by the OP):
![test](https://user-images.githubusercontent.com/49789044/106925279-d6bbdc80-6707-11eb-8741-b192d2bff400.png)

**Comment by DeltaNedas** [comment]
could be solved by making fence gates have half-posts when connecting to other gates

**Comment by rubenwardy** [comment]
@sfan5  why did you remove bug and add discussion? This is either a bug in MT or MTG
