### ISSUE TITLE
get_short_description's description finding algorithm is flawed

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10911]
##### Minetest version
```
5.4.0-dev
```

The `lua_api.txt` says:

```
 * `get_short_description()`: returns the short description.
     * Unlike the description, this does not include new lines.
     * The engine uses the same as this function for short item descriptions.
     * Fields for finding the short description, in order:
         * `short_description` in item metadata (See [Item Metadata].)
         * `short_description` in item definition
         * first line of the description (See `get_description()`.)
```

It behaves as promised, and there is no bug,

However, I think this order of finding the short description is a flawed design. If an item has the metadata field `description` set, it is ignored by `get_short_description`, so it will instead use the node definition's `description`. This is awkward and does not make sense IMHO.

Here's how it *should* be:

```
     * Fields for finding the short description, in order:
         * `short_description` in item metadata (See [Item Metadata].)
         * `short_description` in item definition
         * first line of `description` in item metadata (See `get_description()`.)  <<< NEW!
         * first line of `description` in item definition (See `get_description()`.)
```

Since `short_description` is new in 5.4.0-dev, I think it should be fixed before release.

**Comment by Wuzzy2** [comment]
## Steps to reproduce

1. Install and activate `luacmd`
2. Start Minetest Game
3. `/lua item = ItemStack("default:apple")
4. `/lua item:get_meta():set_string("description", "Line1\nLine2\nLine3")`
5. `/lua print(item:get_short_description())`

Expected: "Line1"
Actual: "Apple"

**Comment by sfan5** [comment]
If you're suggesting a new ordering why not this one?
<pre>
     * Fields for finding the short description, in order:
         * `short_description` in item metadata (See [Item Metadata].)
         * first line of `description` in item metadata (See [Item Metadata] / `get_description()`.)  <<< NEW!
         * `short_description` in item definition
         * first line of `description` in item definition (See `get_description()`.)
</pre>

It'd make more sense to me if the metadata always took precedence over the nodedef.

**Comment by rubenwardy** [comment]
@Desour

**Comment by Wuzzy2** [comment]
@sfan5, you're right. Very good idea. I didn't think this through 100%. :D

**Comment by rubenwardy** [comment]
Current documentation:

> 1. `short_description` in item metadata (See [Item Metadata].)
> 2. `short_description` in item definition
> 3. first line of the description (See `get_description()`.) 
 
The `get_description()` function checks in meta and then in the definition, meaning that Wuzzy's original suggestion and the documentation are identical.

The problem is that `short_description` always exists in the item definition, it's derived from `description` automatically during register time. This means that step 3 will never happen.

## Change behaviour to meta over def (re: sfan5)

With this option, you can still set `def.short_description` from the description automatically.

## Fix bug, keep explicit over derived (as currently documented)

This option would match the documentation for `get_short_description()`. You would need to make it so that `short_description` is only ever set manually, and is otherwise nil.

`short_description` being nilable is annoying for modders who don't have an itemstack around. They'd need to make one to get the short description:

```lua
ItemStack("default:dirt"):get_short_description()
```

## Conclusion

So :shrug:.  It's definitely important that the meta description is used for the short_description if it's not otherwise specified. It's just whether it should override the item definition.

**Comment by Wuzzy2** [comment]
Maybe add a `minetest.get_[short]_item_description(item, ignore_meta)` function to deal with the awkwardness of reading `short_description` when it's nil.
This function takes an itemstring or ItemStack and an optional `ignore_meta` boolean and returns the appropriate description, according to above rules. If `ignore_meta` is `true`, it will skip metadata-given descriptions in the priority list.

The `description`/`short_description` logic is now complex enough that we should start recommending modders to always use functions, rather than reading it directly. I think reading from the def directly is a bit problematic, especially the `short_description`, because of the underlying complexity. Reading `description` from the def directly is probably safe, tho.
