### ISSUE TITLE
Add support for all input bindings in Change Keys dialog (mouse, dig, build, etc)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10927]
## Problem

If you open the key config menu in the game or main menu, you can set your custom keys, but you cannot set mouse clicks. Minetest supports using mouse clicks now, but only via `minetest.conf` for now (`KEY_LBUTTON, `KEY_MBUTTON`, `KEY_RBUTTON`).

Likewise, the recently-added keybinds for digging and building are not exposed in the key config menu yet.

So the only way to change the mouse binds for now is by editing `minetest.conf` by hand.

## Solution

* Recognize mouse clicks when re-binding new keys
* Expose `keymap_dig` and `keymap_place` in the key config menu

**Comment by mk-pmb** [comment]
Also could we please have an option to unbind certain keys? I don't want any of my keys to take a screenshot. I don't want to have to log off just to undo (via text editor) accidentially assigning a screenshot key. Yes it's rare, but it's annoying when it happens. Some users won't even be able to unset screenshot that way. Even if they can use a text editor correctly (as in, don't break the file format on save), it's rather non-intuitive that instead of deleting the line, you have to assign `false`.

**Comment by y0himba** [comment]
I would like to add that side mouse buttons would be nice to be exposed as well.  I have no idea the term but something like KEY_MBUTTON4 ?

**Comment by Desour** [comment]
Note: Mouse buttons should also include wheel up/down.

**Comment by Wuzzy2** [comment]
Okay. Feel free to label this as duplicate.
