### ISSUE TITLE
Password complexity rules (specified by server?)

### ISSUE THREAD

**Issue by codeandfix** [minetest/minetest#10961]
## Problem

Actually the player can choose any password.
there are many solutions out there to force player use secure password.
actually the following options should be added

## Solutions

a) min.pass.length (default to 8 chars)
b) max.pass.length (maybe hardcoded to 20 chars)
c) add complexity check (at least not equal to playername or against dicts or force at least two of four from {[A-Z],[a-z],[0-9],[^specialchars])}

## Alternatives

mods can do this, but this is not a mod job i think

**Comment by rubenwardy** [comment]
I support this. However, for part c I suggest using an entropy checker rather than arbitrary rules. Entropy checkers tend to show up as progress bars for weak to strong under a password box

This probably requires #8138

**Comment by sfan5** [comment]
Only the client has the ability to do these checks on the password, so are you suggesting this should be done client-side?
Depending on how exactly that works the server may not be able to announce its wanted password settings. And we surely don't want to force these on server owners either.

**Comment by rubenwardy** [comment]
I think if the server requires passwords, a minimum password length (and optionally complexity) should be required

**Comment by Zughy** [comment]
localhost servers should be an exception though: as a modder, I want to be able to test them logging in with passwords like "a", "b" etc

**Comment by rubenwardy** [comment]
> localhost servers should be an exception though: as a modder, I want to be able to test them logging in with passwords like "a", "b" etc

You don't have to specify a password in local player. Or on a server, unless they enable `disallow_empty_passwords = true`

**Comment by codeandfix** [comment]
all password complexities should be set disabled on server side, so a serveradmin can always reduce requirements to a lowest level or no password at all. password complexity protection is a decission of the admin only i think.
users can choose complex passwords if they like.

**Comment by hecktest** [comment]
Password policies suck. It's not your responsibility to protect users from their own bad habits, and password policies often get in the way of the good ones.

A plain lowercase passphrase is stronger than a 10 random char string, yet many naive policies will reject the former.

If you make the user break their habits, they're more likely to just write down their super strong password on a post-it note taped to their monitor.

**Comment by codeandfix** [comment]
Yes, password policies suck. especially if the policy designer want to mix nearly all possibilities like A-Z,a-z,&%$",0-9 etc.
I think a simple policy - like windows does, is a good compromise. so you have to use at least 2 of these items.
yes a simple password can be secure. but the problem is not that a players building is griefed.
maybe you grant a good behaving player access too special areas and so they are compromised, too

**Comment by S-S-X** [comment]
> If you make the user break their habits, they're more likely to just write down their super strong password on a post-it note taped to their monitor, reducing the password's security from weak to zero.

I believe for most Minetest games this is a lot better option than having password that is easy to guess.
I mean writing your password to post-it note taped to monitor is actually better for your Minetest server account security compared to using very easy to guess passwords that are not written on post-it note.

**Comment by HybridDog** [comment]
I'd like to have my passwords for all servers encrypted with a master password stored in my ~/.minetest folder and use gnome-keyring to store the master password so that I don't need to enter the master password every time I start minetest.

**Comment by hecktest** [comment]
All password policies suck, there is no good compromise. Sorry for stirring this pot of stupid again but since I keep seeing it in my email, I'll bite.
So first of all, we're talking about accounts for a block digging and placing game that has no encryption or validation on its traffic besides its auth step. There is basically nothing worth protecting, and passwords are the least of your problems.

If some admin uses a bad password and loses control of his server, that's really his problem. If he's this bad with security, his server probably has other holes already. Minetest itself probably comes with a dozen of these, if someone were bored enough to check.

Every single policy proposed in this thread forbids the use of diceware or battery staple, while permitting passwords short enough to actually be within range of a brute attack. If you do not understand what those things are and why this is bad, you shouldn't be messing with security in the first place. Instead of downvoting me, try actually researching this.

@HybridDog 
How about an identity file like SSH keys? That would be both strong enough and convenient. Still not warranted for playing a stupid block game, but it could be useful for server staff, for the same reason ssh key auth is. (no passwords no problem)

**Comment by S-S-X** [comment]
> All password policies suck, there is no good compromise.

This is not completely true, there's account hijacking that happen all the time and account hijacking that happens a lot less often.

First thing happens because player password can be *guessed* in just few tries because it is either empty, default password, player name, 1234 or qwerty.
Password policy that protects player accounts against these will also solve maybe about 99% of account hijacks.

This can be done with server side mod but having it available client side, possibly with configuration option, would also help.
For some Minetest use cases it could be useful to have full password policy server side but not really needed for most servers out there.

> If some admin uses a bad password and loses control of his server, that's really his problem.

I don't really see any reason to even think about admin account security, it is expected that you'll understand higher importance of account if hosting public servers.

> Every single policy proposed in this thread forbids the use of diceware or battery staple

I did not propose anything specific before but you should be able to read that my proposal would not forbid either of those but only easily guessable passwords that can be "brute forced" by hand in less than one minute.

> while permitting passwords short enough to actually be within range of a brute attack

It is Minetest, really you should forget about brute force attacks and focus on real problems that happen all the time. If brute forcing become problem for server then it should be handled with fail2ban or some other rate limiting firewall server side. If it becomes problem because of leaked db then it should be handled by informing players some other way.

> If you do not understand what those things are and why this is bad, you shouldn't be messing with security in the first place. Instead of downvoting me, try actually researching this.

Really, to mess with this topic one does not have really have to understand that much about security, basics would be enough. 
Terrible password policies are often selected because people who made decisions think that they understand security while in reality they do not.
People who do not understand security but do understand UX should mess with security, yes there's often conflicts between these two but cooperation can also result in a lot better security with good UX.

> How about an identity file like SSH keys? That would be both strong enough and convenient.

That would be fun feature but not convenient for everyone, there's a lot of non technical people playing Minetest and many using operating systems that require bit more tinkering and less out of box things to aid with public key authentication.

Btw, this already catched multiple accounts with bad password and those were fixed, some asked how to change password and now they know:
https://github.com/minetest-beerchat/beerchat/blob/e21e16bab94b435f91a7f68f9c6535c7f5ad02f3/plugin/password.lua#L16-L23

**Comment by 0-afflatus** [comment]
Yup, there is no good reason for hardcoding this. Everything you suggest can be adequately done with mods although I like HybridDog's suggestion of making it compatible with Gnome keyring (and others), but that's another issue really.
Security just isn't that big an issue.

**Comment by rubenwardy** [comment]
> Yup, there is no good reason for hardcoding this. Everything you suggest can be adequately done with mods

Mods cannot do this, it needs to be done client side. The server never sees a user's password, secure remote password is used instead

**Comment by rubenwardy** [comment]
> Every single policy proposed in this thread forbids the use of diceware or battery staple, while permitting passwords short enough to actually be within range of a brute attack. 

Not true, I mentioned entropy password checkers

**Comment by HybridDog** [comment]
Using an asymmetric key pair (what is also done for SSH) has the disadvantage that the player cannot join the server on another computer unless he/she copies the private key, in which case he/she should encrypt the private key with a password.
Copying the key to e.g. a mobile phone takes some effort, and instead of encrypting a private key with a password, GNOME keyring or something similar together with a strong Minetest password can be used.

I think using Gnome keyring or something similar is good for password complexity because players would be less tempted to write short passwords to be able to join the server faster. If the server passwords are encrypted with a master password, the player can copy the encrypted server passwords to another device while the passwords stay confidential.

I assume that Minetest is often played by children who don't know much about password security. Instead of enforcing a password policy, maybe it suffices to show a formspec which teaches the player how to set a good password before he/she enters a password and joins some server the first time. If after that the player still decides to set a bad password, it's his/her own fault because he/she has been warned.

**Comment by mk-pmb** [comment]
@0-afflatus @HybridDog
I think Gnome Keyring should belong in the MineTest login manager thread: #1566

**Comment by mk-pmb** [comment]
> a) min.pass.length (default to 8 chars)

Ok if optional and configurable

> b) max.pass.length (maybe hardcoded to 20 chars)

Why?

> c) add complexity check

Yes, but only reasonable methods. No useless fake security please.

**Comment by mk-pmb** [comment]
On another note, can admins with special password ideas not close registration and make their own registration form on a website? Then we wouldn't need to concern client code with all the policy ideas people will have.

**Comment by S-S-X** [comment]
> On another note, can admins with special password ideas not close registration and make their own registration form on a website? Then we wouldn't need to concern client code with all the policy ideas people will have.

I don't think it is possible to do this with "change password" dialog. Also while partially possible still doing it with anything external would be easy way to remove benefits of SRP.

**Comment by mk-pmb** [comment]
You're right. They'd need an option to disable the built-in Change Password as well, and use their own or 3rd-party software for SRP with password policy checks.
(In an ideal web dev scenario, their custom SRP software could even be a JavaScript running in the browser. Let's leave the real world problems of this approach to other threads.)

**Comment by S-S-X** [comment]
Been thinking about this few times and seen many problems with bad passwords and people not knowing how to change password.

I do think that proposed basic idea is good but provided solutions are not that good because of being too strict.
_(too strict for players who should be targeted and that does not include server admins)_

### Proposed solutions from issue description

Read `extremely simple passwords` as 1234, qwerty, server default password, player name or similar really extremely simple. For example here 5969 is not considered extremely simple.

> a) min.pass.length (default to 8 chars)

If extremely simple passwords are disabled some 4 character _configurable default_ should be enough.

> b) max.pass.length (maybe hardcoded to 20 chars)

There should not be maximum password length limits, that is completely useless suggestion and does not serve any purpose.
Using words I can easily use 40 characters and have secure password that I can memorize instantly without storing it in any password manager or post-it note. That's just few words.

> c) add complexity check (at least not equal to playername or against dicts or force at least two of four from {[A-Z],[a-z],[0-9],[^specialchars])}

Complexity check by default should be for extremely simple passwords.
Configurable for sure if server owner wants complicated passwords instead of secure passwords but by default requiring any specific character class is just bad idea.
This should also be configurable and very permissive by default only blocking extremely simple passwords.

All restrictions should be disabled completely for single player mode, if whole thing is client side then possibly same could be also considered for servers on private networks (even if this could mean tunneled connection: if user has that then almost sure there is either manager who knows or user himself is resourceful enough to know how to handle passwords).

### What is good enough and why?

For example "there", "8822" or "verycool" are very good passwords for regular minetest player account compared to passwords apparently used for a lot of accounts: server default password, player name or 1234.
These passwords are good enough minimum because you really cannot brute force these by hand without extreme luck.
This is not to claim that these are really "secure" passwords but they are a lot better than extremely simple passwords and can make huge difference with account hijacking through password guessing.

### Real problem with passwords

a lot of people playing minetest do not even know that they can change password, there's been a lot of players asking how to change password after server starts spamming _"Please change your password"_ until player has changed password.
Many do not care but they should care at least a bit because of other players, there password policy that prevents outright stupid passwords _(with some 20% chance to guess first try)_ would be very good solution without really making situation worse for anyone else.

If automated password testing ever becomes problem for your server it is extremely simple to prevent that with basic operating system tools and/or minetest mod (simply limiting attempts and banning bad actors).

_restricting too much can easily go wrong while minimal restrictions can make situation a lot better for everyone without causing much trouble for anyone_

**Comment by SwissalpS** [comment]
if harder passwords are required, many more will be requesting password-reset. This can only be done if they supply an email, phone number or other method of identification when first signing up.

**Comment by mk-pmb** [comment]
Somewhat related: #11925 "Support keyfile as login method",

**Comment by Darin755** [comment]
https://www.starlab.io/blog/why-enforced-password-complexity-is-worse-for-security-and-what-to-do-about-it

Adding password complexity requirements often does nothing and can ever hurt security. Instead, Minetest should enforce a minimum password length with a sane default. It should be enforced on the creation of new passwords not old ones unless explicitly specified. Also, for testing, you could include a simple option that disables all password requirements. 

Another useful security feature might be to automatically lock old accounts. Old abandoned accounts could be a significant security risk as the are pretty much unmonitored. Not that Minetest is that big of target but it would be a nice feature. When determining whether to lock an account it should look at last login time along with the amount of time spend playing. If a significant time was spent playing then it should take a long time to lock. However, if an account has only 5 min of time spent it should take a shorter time to lock. Users should be informed about the policy and have a way to recover an account with a old password and some sort of check like a basic CAPTCHA

**Comment by appgurueu** [comment]
> Another useful security feature might be to automatically lock old accounts.

It's absolutely not engine business to implement an inflexible solution here. Mods can implement this via the auth handler API, and there are definitely server admins who have systems like this in place.

**Comment by sfan5** [comment]
Maybe we should just close this? It doesn't look like any solution can be agreed upon and IMO it's not that important anyway.

**Comment by SmallJoker** [comment]
> a) min.pass.length (default to 8 chars)

Duplicate of #4394 (rejected).

**Comment by appgurueu** [comment]
Closing this is probably fine.

I don't really see this being worth the effort, just to introduce a controversial feature that might very well end up being counterproductive. Since this needs to happen on the client (no, mods can't do this) we'd have to implement a way to query the password requirements of a server before connecting (arguably a lazy solution would be to do this over the serverlist, but that wouldn't work for servers not on there). To comment on b and c:

> b) max.pass.length (maybe hardcoded to 20 chars)

Bad idea. I don't think users setting too long passwords is much of a problem. And if it is, it's on them. I don't see a technical or practical reason for us to enforce such a limit.

> c) add complexity check (at least not equal to playername or against dicts or force at least two of four from {[A-Z],[a-z],[0-9],[^specialchars])}

These tend to be frustrating for users and don't necessarily even improve security.

Also worth noting: The user experience would probably be terrible if each server had its own password requirements.
