### ISSUE TITLE
Sporadic client-side delay when detaching and teleporting an entity on the same step

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#11008]
##### Minetest version
```
5.4.0
```

##### Summary
Title. I'd say 50%

##### Steps to reproduce
Join the spectate mode of any minigame of my Minetest server (A.E.S.). When leaving, sometimes you won't be teleported to the lobby immediately. What the code does is detaching you from the player you were following AND teleporting you back on the same step. Proof: https://gitlab.com/zughy-friends-minetest/arena_lib/-/blob/master/src/api/in_game.lua#L226-232

**Comment by SmallJoker** [comment]
`set_pos` -> `TOCLIENT_MOVE_PLAYER` is sent on channel 0 + reliable
`TOCLIENT_ACTIVE_OBJECT_MESSAGES` (attachments) are sent on channel 0 + reliable OR channel 1 + unreliable

https://github.com/minetest/minetest/blob/66e8aae9f2a28ee31ffe30694fdb61a8fdceb8d7/src/server.cpp#L2023-L2034

however, the attachments are sent reliably, hence on the same channel which ensures the packets to arrive in correct order.

https://github.com/minetest/minetest/blob/66e8aae9f2a28ee31ffe30694fdb61a8fdceb8d7/src/server/unit_sao.cpp#L120-L123

The problem is that`UnitSAO::sendOutdatedData` is processed each entity step, whereas `LuaEntitySAO::sendPosition` does send a packet immediately.

Fixed since https://github.com/minetest/minetest/commit/375bcd65c1903957e3a640cefffcc8df164b78bd
