### ISSUE TITLE
Split param2 into categories

### ISSUE THREAD

**Issue by v-rob** [minetest/minetest#11019]
## Problem

Minetest's param system is not very suited to combining different paramtypes.  This is especially noticeable in `colorfacedir`, where the 5 bits of facedir only leave 3 bits for the color palette, or only 8 colors.  Other features like #9193 would have similar issues, and combining facedir, color, and that would be simply impossible.  Eight bits simply isn't enough if multiple things need to be combined.

## Solutions

Some paramtype2's are necessarily exclusive and don't work together at all.  Others can work with just about anything else.  I can see a few logical categories that paramtype2's could be grouped into:
* Orientation, or the direction of the node:
    * `wallmounted`
    * `facedir`
    * `degrotate`
* Hardware coloring: `color` (ignoring `colorwallmounted` and `colorfacedir`, as those bleed into multiple categories)
* Miscellaneous that are mostly incompatible with each other:
    * `flowingliquid`
    * `leveled`
    * `glasslikeliquidlevel` (could honestly be merged with `leveled`)
    * `meshoptions` (to be fair, `meshoptions` with `leveled` and the `plantlike_rooted` drawtype could be useful, but not every use-case can be satisfied)
* Other groups might be added, e.g. #9193.

Therefore, I would suggest the deprecation of param2 and replace it with multiple parameter fields.  In other words:

```lua
minetest.register_node("cool:node", {
    drawtype = "nodebox",
    param_orientation = "facedir",
    param_color = "palette",
    param_misc = "leveled",
    nodebox = {
        type = "leveled",
        -- ...
    }
}

-- ...
minetest.set_node(pos, {name="cool:node", orientation=o, color=34, misc=64})
```

There are multiple problems with this idea, however.  Map compatibility/size could be a concern, although probably not a lot.  `MapNode` would increase in size (`u16 content, u8 light, u8 orientation, u8 color, u8 misc`=6 bytes, 2 extra than before), although a discussion on IRC a while back ascertained that this wouldn't be a huge problem.

The biggest problem would likely be compatibility with `param2` in `minetest.set_node`.  Consider the following pieces of code:
```lua
-- Setting a blank node
minetest.set_node(pos, {name="cool:node"})
-- Set node, but preserve facedir
local node = minetest.get_node(pos)
minetest.set_node(pos, {name="cool:node", param2=node.param2})
-- Set facedir, e.g. in screwdriver
minetest.set_node(pos, {name="cool:node", param2=lookup_table[rotation]})
```

With param2 deprecated, how can one interpret the intent, i.e. what should the new param values to be set to?  The first is easy: everything will be set to zero anyway.  However, in 2 and 3, it's very difficult to know which param values to change to what.  Param2 could only contain the same values it does now, e.g. pack `color="palette"` and `orientation="facedir"` into legacy `paramtype2="colorfacedir"` format, but this clobbers the intention of 2, which is to keep the params the same while the node is different.  There is no way to detect the difference between the intent of 2 and the intent of 3 with 100% certainty.

The only solution I see is to preserve backwards compatibility but break forwards compatibility, i.e. pack the values into the legacy param2 format when possible, but make no such attempt with combinations that have no equivalent in the old param2 format.  Therefore, things like screwdrivers or code that swaps node names will continue to work with all old mods, but new mods that use param combinations may not work properly.  This is suboptimal, although it happens periodically with the API anyway.

This is mostly conceptual, however.  I don't know the full complexity or implications of it all, but I think multiple param groups would be pretty nice to have.

**Comment by SmallJoker** [comment]
Related issues: #6979, #6663, #10950

So far my thoughts were only about combining the various param2 fields into a 1-byte `union` (like with ClientEvent) to give it manageable names. It might also help to extend the features per depending on the drawtype, and reducing the risk for tremendous RAM usage due to unused values.

**Comment by v-rob** [comment]
Well, RAM usage would increase 1.5 times for node memory usage, which would kind of stink, but if a player can explore X mapblocks currently before running into RAM issues, he can only explore 2/3 * X mapblocks with extra param fields, which doesn't sound terribly bad to me.

However, while a bit union might be good for code quality, it wouldn't help a whole lot in terms of paramtype combination.  The big issue is facedir, which takes a whopping five bytes, leaving everything else with only three.  The only paramtypes that use three bytes are `flowingliquid` (according to the docs) and `colorfacedir` (obviously).  Facedir is very common, so it's the big limiter for paramtypes.  Also, I wonder whether or not extra param fields would actually turn out to be unused -- mods like luscious certainly would use them a lot!

I think staying with a 4-byte MapNode forever is too limiting for nodes, which are really the foundation of Minetest.  We should extend it, but strategically.  Adding every feature is bad, e.g. 32-bit content IDs + 1 byte param1 + 1.5 byte rbg444 colored lighting + 3 param categories from this PR + #9193 param category = 10.5 bytes + 1.5 bytes padding (ouch, 3 times the memory usage).  So, my opinion is that the question is how to extend it, not whether to extend it.

(Side note: looking through those other issues, quite a few people really need to learn about processor byte alignment and struct padding.  So many incorrect claims about increasing MapNode size!)

**Comment by Desour** [comment]
Can't we make param2 to a packed bit struct?:
- Define a fixed order for paramtype2s, eg. `wallmounted, facedir, meshoptions, leveled, color, ...`. (New types need to be added to the end.)
- Define how many bits each paramtype needs. (There might also be types which can take different amounts of bits, like color. Such types could be split up into color1, color2, color3, ....)
- When registering nodes, you specify which paramtype2s you want, eg.: `paramtype2s = {wallmounted = true, color5 = true}`.
- In the example, the param2 byte then consists of 3 bits wallmounted, then 5 bits color. wallmounted comes first because it's first in the order.
  => For every node, we can determine the bit-offset of each of its param2-values.

Advantages include:
- Easy backwards compatibility.
- Much flexibility, eg. simply make the param2 bigger, and the modder can decide what they want to use it for.
- Not as much bit-wasting.
- Unused param2 bits can still be used by mods for custom purposes.

The modding api should also stay easy, if helper functions are added.

------------------------------

>The big issue is facedir, which takes a whopping five bytes

An additional simpler facedir that just rotates around one axis (eg. y-axis) would just need 2 bits (I think, you meant bits there, not bytes).

Tbh, I'm not sure what you were referring to with "a bit-addressable 1-byte `union` (like with ClientEvent)", maybe something similar as my suggestion? ClientEvent looks like it's an algebraic data type, which doesn't make much sense if we want static paramtype2s.

**Comment by v-rob** [comment]
Your suggestions and SmallJoker's are essentially the same with the difference that you suggest the possibility of additional bytes than just one.  It's certainly a more space-efficient system than mine.  TBH, I think I like that idea better than my own (that is, when it works on multiple bytes), and it could make things like rgb444 (12 bit) color possible instead of just a palette.

However, SmallJoker's concern seems centered specifically on increasing the size of MapNode.  Even if we added just one byte, MapNode would go from 4 bytes to 6 bytes due to alignment.  The big question is whether it's OK to increase this, and if so, then by how much?  Consideration must also be put in for other things like colored lighting, which can't be put alongside expanded param2s in a 6 byte MapNode.  We have to choose features selectively because they can't all be put together without a cost in RAM, speed, and/or map size.

> (I think, you meant bits there, not bytes)

Oops, yes.  That would be some hefty facedir!

**Comment by sfan5** [comment]
My opinion on this is that while the proposed param2 categories would make nodes much more flexible in any situation I think that defining a fixed param2 meaning (or combinations of meanings) is good enough.
To make the current system more useful extending param2 should obviously be discussed.

Worth reading in case haven't seen already: https://irc.minetest.net/minetest-dev/2021-02-14#i_5785882
