### ISSUE TITLE
Toggle autojump with set_physic_overide()

### ISSUE THREAD

**Issue by AFCMS** [minetest/minetest#11012]
## Problem

`autojump` is only a setting for now, and is not realy useful, except with Android.
I suggest to allow mods to toggle per player autojump with set_physic_overide()
This will allow making autojump armor and many other cool stuff.

## Solutions

Ability to toggle autojump with set_physic_overide()

## Alternatives

?

**Comment by Zughy** [comment]
I don't think it's useful. If you're able to jump properly, it won't change anything if you have an armor with that equipment or not. It makes sense as it is now

**Comment by AFCMS** [comment]
@Zughy Auto-jump is really helpful when traveling
Also, being able to toggle auto-jump with lua will make auto-jump more flexible (armor is not the only usecase for this feature)

**Comment by Desour** [comment]
:-1: Autojump shouldn't give any advantages. And something that doesn't give any advantage shouldn't be restricted by the server.

I think what you are looking for is stepheight. In the past, mobile players had a step height of a whole node, so they had stairs without building stair nodes. This was replaced by autojump because the bigger stepheight was cheaty.

**Comment by SmallJoker** [comment]
What you want are in-game setting changes. Mods should not have control about assistance features.

See #6722.
