### ISSUE TITLE
Codepages support (utf-8) for all platforms

### ISSUE THREAD

**Issue by 4aiman** [minetest/minetest#1106]
All releases of windows up to Win7 Enterprise (inclusive) do not support utf-8 properly.
Setting locale via LUA doesn't work too. For exmple it's impossible to set russian_Russian.65001 locale albeit it IS installed.

What's the big deal?
Well, while game chat works OK, windows clients can't see non-latin characters in the game (infotext, HUDs).

The percentage of installed win/lin OS all over the world is self explanatory in terms of what should be supported. 

So far, the only way to let Windows see non-latin characters is to decode mods' files into, say, CP1251 and use os.setlocale() to set that codepage.

However, this breaks chat non-latin sumbols support on Linux. It fact, any input via fields in a formspec turns into hieroglyphs.
Also the MOTD is displayed wrongly.
But HUDs and infotexts are shown normally.
As for windows players - they can chat and set text fields of signs using non-latin characters normally.

Moreover, linux users can see signs' text in non-latin characters, but cannot add any of the non-latin characters (but can delete existing ones partially and "save" the text).

So, the problem is in the input "field" fields in the formspecs.

**Comment by 4aiman** [comment]
So.. no one is concerned in fixing this?
I mean, there's no "bug" or "enhancement" kind of a label...

PS: Ppl @ MT forums are *still* misinformed about the roots of this "codepage-feature"..

**Comment by Fixer-007** [comment]
I've noticed that too at least with infotexts as of today, Win7, wrong characters displayed due to UTF8-CP1251, for example, if you press Shift+M to mute volume, you will see smth like this 
![default](https://cloud.githubusercontent.com/assets/16494741/26287080/520ef18c-3e7c-11e7-80f9-f819d3227c63.png)

**Comment by Wuzzy2** [comment]
It may sound stupid, but I wonder what happens if you replace all calls of the form `narrow_to_wide(gettext("I am a string. Translate me!"));` with `wgettext("I am a string. Translate me!");`. To be honest, I am really just guessing here. :grinning: 

I can't test this, I am on GNU/Linux.

By the way, “UTF8-CP1251”? WTF is this? UTF-8 + Windows code page combined? This sounds like a sick joke to me. :confounded: 

@Fixer-007

**Comment by Fixer-007** [comment]
I'm not sure, probably happens because windows and irrlicht use different encoding.

**Comment by paramat** [comment]
Still a valid bug? (can't judge).

**Comment by Fixer-007** [comment]
Should be, will check.

**Comment by Fixer-007** [comment]
Can't check since that buggy message is now displayed in english (needs translation).
