### ISSUE TITLE
Fedora 34 Aarch64 Bug: SIGSEGV

### ISSUE THREAD

**Issue by ric96** [minetest/minetest#11095]
I'm not sure if this is the right place to post this but I've had no response on Bugzilla and F34 is BETA now.

bug: https://bugzilla.redhat.com/show_bug.cgi?id=1934757

**Comment by sfan5** [comment]
I can confirm this with `minetest-5.3.0-5.fc34`, running in gdb the backtrace isn't any useful either:
<pre>
Program received signal SIGSEGV, Segmentation fault.
0x000000020010eb84 in std::ostream& std::ostream::_M_insert<unsigned long>(unsigned long)@plt ()
(gdb) bt
#0  0x000000020010eb84 in std::ostream& std::ostream::_M_insert<unsigned long>(unsigned long)@plt ()
#1  0x00000002001303f8 in _start () at /usr/src/debug/minetest-5.3.0-5.fc34.aarch64/src/porting.h:284    <- this is beyond the last line
</pre>

Since Minetest on aarch64 works in other circumstances there's nothing we can fix here.

**Comment by ric96** [comment]
I've built master on f34 and that works fine. Can we consider bumping the rev to 5.4 on f34?

**Comment by sfan5** [comment]
That's something you'd have to ask the Fedora package maintainers (not here).

**Comment by ric96** [comment]
> That's something you'd have to ask the Fedora package maintainers (not here).

gotcha, opened another bugzilla request for that. I'm not too hopeful, my last bug report went unanswered.
