### ISSUE TITLE
Core support for player based permissions

### ISSUE THREAD

**Issue by 0siribix** [minetest/minetest#11217]
So here's my idea: 
Core recognizes a set of permissions like interact, dig, destroy, walk, breathe, heal, fly, see, etc. I'm thinking these could be saved in metadata. Client should receive permissions and obey these; as in, client doesn't allow interacting with a node if this player doesn't have the permissions for it. Server now has the ability to check if client is cheating. I think server should be able to not send metadata (like container contents) if player doesn't have permission to view them.

I'm a veteran coder but new to minetest and haven't figured out all the nuances so please go easy on me if anything sounds dumb or obviously inefficient. The idea I have for implementation is using metadata to store this info but I think it may be more efficient to implement in the core and add a new protocol code. 

Consider this: Server has tables/groups of permissions defined. Server sends permissions to the client on connect. So the server stores nodes with links to permission tables and which users they apply to. We also need to store tables of nodes/permissions for checking against cheating and for manageability.

User/owner will register an area xyz (that would be another permission to add - is user allowed to change permissions for all blocks in this area). User can then set permissions for this area. This definition is saved in the world data and all nodes are linked to that permissions table. On connect, the client receives all permissions tables and the same links from those nodes. The client knows already that it can't dig, interact, see, or breathe in this area because connecting player does not have permissions for this area. If the player is able to enter this area or dig a node, the server will not accept it and can flag the player as possibly cheating.

This should make protection mods much more efficient and also allows for other possibilities. Examples off the top of my head are being able to heal only in certain areas, adding areas where players float up or can fly. or having magical areas where players can't see

Thoughts?

**Comment by Emojigit** [comment]
You can now use the privs system to handle it.

**Comment by 0siribix** [comment]
Is it already possible to set a priv to only work in certain areas?

**Comment by sorcerykid** [comment]
This idea seems reasonable, but unfortunately Minetest doesn't offer area-based metadata storage (at least not natively). 

However, there is an AreaStore data structure for use in conjunction with protection mods. It would be entirely suitable for the purposes you've described as well. A simple solution would be to map each area ID to a corresponding key in a separate table that contains the list of permissions for that area.

Take a look at the Areas mod, as it does something quite similar. You can probably adapt the existing code-base quite easily.

https://github.com/minetest-mods/areas/blob/master/internal.lua

Of course, this doesn't afford any degree of client-side prediction. But I'm not sure if that's even necessary, since this mechanism is efficient enough for protection mods. There might be some corner cases, like preventing a user from entering an area, that would benefit from a realtime response rather than the slight delay due to network latency. I'm not sure, however, if that's really common enough to warrant the compatibility-breaking changes necessary to implement all of this into the engine.

**Comment by sfan5** [comment]
Permissions aren't quite as fine grained as you describe them but essentially this is already doable:

`interact` (digging, placing, ...) and `fly` exist. There are various way to prevent player movement. Healing and breathing are up to the game.
The privileges are global, but that isn't an issue. Mods can automatically grant and revoke them when entering or leaving an area.

By the way, linking individual nodes to permissions/privileges is likely less efficient than existing solutions invented by protection mods or already provided by the engine.

**Comment by 0siribix** [comment]
Looking into doing this with SSCSM
