### ISSUE TITLE
Shadowmaps cannot be disabled by the server

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#11365]
5.5.0-dev

#11244 was merged prematurely, clearly for ideological and hype reasons rather than considering quality or utility.
Just look at this fine example:
![shadowmap](https://user-images.githubusercontent.com/42101236/122640948-81a2c500-d102-11eb-8203-b4370f0a3de8.jpg)

Off the top of my head
- performance is an abysmal burden on an already slow map renderer, turning shadows on is basically a trap
- unloaded blocks can not cast shadows
- layered geometry like decals produces artifacts
- settings that have no business being controlled by the client (orbit inclination) actually are
- shadow orbit inclination is not tied to skybox sun orbit inclination
- there is no consideration for custom time of day scripting
- there is no consideration for overcast scenes
- there is no consideration for any kind of environment that doesn't involve a sun (which is supported by the rest of the skybox api)
- the mismatch between GI sunlight and shadowmap sunlight has been handwaved rather than solved
- the shadows darken all scenes they affect with nothing to make up for it

Above all, client controlled shadowmaps are an artistic decision forced upon mod and game developers. Because I don't believe this feature can ever be salvaged, I just want a global off switch per client, akin to skybox settings. Not per node or per object - that would be an undue server bandwidth and code size burden. Per material flags have utility, but they are no replacement for a global setting.

Please don't change this to feature request, this isn't a feature request, things are actually broken by this change.
Please also refrain from giving any unsolicited art direction advice, and in general, let's not do #9985 all over again.

**Comment by NathanSalapat** [comment]
It's a client setting, and doesn't it default to false. It shouldn't effect anybody that doesn't turn it on.

**Comment by SmallJoker** [comment]
Well then, perhaps don't enable it until that's sorted? Dynamic shadows are disabled by default.

**Comment by sfan5** [comment]
As more or less discussed on IRC this issue mixes a few things:
* Bugs with how shadowmapping works
* Apparent lack of integration with the skybox API (are shadows cast when the sun is disabled?)
* Lack of server influence over client-side choices

The first two are undoubtedly bugs and should be looked at first. Whether the last is an issue or feature request is a question of definition(\*), but let's not discuss that here.
(\*) Generally Minetest is missing definitions what makes it an engine, what is allowed to be hardcoded and to which extent. There is also no entry on the roadmap for this.

**Comment by hecktest** [comment]
I can disable it myself, but clueless clients will enable it and blame me for the bad graphics and performance. **I cannot make the game look and run good for anyone who has this enabled.** While it is possible for a client to brick their experience with a bad config in other ways, none are as deceptive as this trap of a feature, which is prominently featured in the main options menu with no warning for the horrors it may unleash.
In #9985 people were also like "just DiSablE sHaDErS loL" and it's still just as much of a crappy excuse as it was back then.

The performance itself is enough to give Minetest a bad name, I'm afraid. The engine barely keeps it together as it is, and throwing this on top is just making it crumble under the weight. Would've mentioned it in the PR but I wasn't around at that time, though I doubt anyone would listen.

I don't expect to convince anyone this was a bad idea (it's horrible) but please don't force me to eat its consequences in any way.

**Comment by hecktest** [comment]
@sfan5  
> As more or less discussed on IRC this issue mixes a few things: [...] 

This is a bit of a misrepresentation; this bug is about the feature being incompatible with some existing graphics which was an acceptable reason last time. I can point out other problems, like why this feature is bad and why I want nothing to do with it, but the main reason is how it was forced with no opt-out for game developers, _again_. (at least this time I noticed before a release) Everything else is just excuses and kicking the problem down the road; making this about forcing settings in general sounds like a great way to avoid fixing it.

For a modder, this kind of environment can be pretty stressful. Minetest seems like it's both an engine and not-an-engine depending on what's convenient at the moment, and the concerns of modders are pushed aside in favor of what gets the most thumbs-up emojis. It seems like there is a lot of bias in the development process, but nobody wants to be the one to admit it. The Minetest community wants to have its cake (new content) and eat it too (bias towards porting minecraft features).

As also mentioned on IRC, I'm willing to provide the fix in the form of a skybox flag, but this was apparently not good enough... hence I'm waiting for some input on #11366, just give me a green light on either in a reasonable time so that it can be done before 5.5. (or flag as a blocker so that this isn't a worry in the first place)

**Comment by lhofhansl** [comment]
> #11244 was merged prematurely, clearly for ideological and hype reasons rather than considering quality or utility

Huh? If you don't like it don't turn it on.

I mentioned this before... Can we please watch the tone?
This was Herculean effort and I strongly appreciate this work.
All that infamatotory - and factually false - statements like the one cited do is discouraging future work.

I suggest we close this one and file issues for specific problems to fix.

**Comment by v-rob** [comment]
I think as a first step, shadows should be marked as experimental.  That should be enough (for now) to ensure that people don't assume the feature is broken when it's really that the feature is still in progress.

**Comment by hecktest** [comment]
@lhofhansl 
Excuse me, did you just skim the thread? It doesn't look like you've actually read any of it.

Minetest sells itself as a game engine, it's been doing that for years now. Despite that, one cannot actually design and make a decent game in this engine because the dev team keeps pulling the rug from under any potential developers. Anyone with less patience and investment into this thing would've already quit, and from what I've heard, many already have.

If an engine has no dynamic directional lights and runs at about 90 FPS on a good day, and someone creates their assets with that feature set in mind, is it okay to suddenly force shadow mapping and tank the framerate to 15 FPS, with no way for the developer to mitigate this? No other game engine does this, the decision to use things like shadow mapping is always within the game developer's domain. If it isn't, people go and find a better engine. This is an architectural mistake inherited from the initial scope of being a Minecraft clone, but instead of slowly chipping away at existing instances and improving, you keep repeating it and adding to the pile. 

Due to Minetest's unique distribution model and online features, it is not an option for a developer to enact a version freeze, especially not for the online-only experiment I wanted to perform. I cannot simply stay on 5.4 forever, or at least, that offers me no benefit over just making a fork, which every issue like this just tempts me to do. If I'm forced to fork or otherwise leave, MT will lose yet another opportunity to grow. I came to this community with a healthy share of good will and a plan that would benefit everyone, did not complain about API breakage _as long as it could be worked around_, fixed bugs that nobody else wanted to touch, discovered many new ones by pushing the engine to its limits - and what for? I take a break for half a version and come back to everything being broken and a whole new round of gaslighting about what's a bug and what isn't, and a barrage of lectures about my attitude or whatever. I can't even discuss a simple issue, or even _offer to fix it_ without at least being made to offer a good feature along with it. This environment isn't just hostile, it's straight up _abusive_. It seems like content creators and users are actually at the bottom of whatever hierarchy exists around here.

Yes, this PR was merged out of hype. (wow shiny!) It wasn't really tested or even decently proofread by anyone, just read the code files it introduces. Maybe the maintainers value some things more than code quality or even a stable result, or maybe some contributors are just more equal than others. Maybe I'm doing this whole thing wrong, maybe instead of cleaning up after others I should start writing my game's features into the engine whenever it suits me, accomodating for no one else, and rely on hype and politics to get them merged.

**Comment by NathanSalapat** [comment]
> If an engine has no dynamic directional lights and runs at about 90 FPS on a good day, and someone creates their assets with that feature set in mind, is it okay to suddenly force shadow mapping and tank the framerate to 15 FPS, with no way for the developer to mitigate this? No other game engine does this, the decision to use things like shadow mapping is always within the game developer's domain. If it isn't, people go and find a better engine. This is an architectural mistake inherited from the initial scope of being a Minecraft clone, but instead of slowly chipping away at existing instances and improving, you keep repeating it and adding to the pile.
> 

Shadow mapping isn't forced....

**Comment by lhofhansl** [comment]
@hecktest I have nothing else to say to this. I will not contribute further on a flame issue.
@v-rob I agree.

**Comment by hecktest** [comment]
> Shadow mapping isn't forced....
It is.  Imagine you make a game that couldn't ever look good with shadows on, and someone adds shadows to the client and fails to give you a way to instruct the client to not use them. You're at the mercy of the user guessing the right settings to get a proper experience, and your art style becomes effectively unsupported. This is a forced downgrade. We've been over this already, why is a breaking change suddenly okay?

**Comment by sfan5** [comment]
> This environment isn't just hostile, it's straight up abusive.

This is ironic coming from you. You know who is making this environment abusive? It is <b>you</b>.
Most of the comments you write contain _at least_ one paragraph dedicated to claims of everyone else's incompetence, speculation of motives, rants or general negativity. There is no lack of good points brought up by you but the tone reduces any indication of good will to nothing.

This is under **no circumstances** an acceptable interaction style on the issue tracker and I am not willing to tolerate this any longer.
You are welcome to engage constructively in other issues.

**Comment by hecktest** [comment]
As worked out in several IRC conversations, fixing a related bug (shadows being present without a sun) will provide a workaround for this. Further work in #11366 will make the API for this more flexible.

But the main problem is that we need to tighten guarantees for game developers so that they can expect a stable environment to develop content in. Then we ought to document it somewhere visible, and avoid merging commits that break that promise unless there is a plan to resolve it before the next stable release. An instance of this promise being broken should be a blocker just like unexpected API breakage would.

The modder can be expected to follow the engine's development and perform some nominal work to upgrade to a new release, so opt-outs rather than opt-ins are fine. The burden on the downstream and/or admin should be reasonable; a few lines of code, minimal additional network traffic and no undue performance cost for a disabled feature.

**Comment by neoh4x0r** [comment]
> 5.5.0-dev #11244 was merged prematurely, clearly for ideological and hype reasons rather than considering quality or utility.
>
> Above all, client controlled shadowmaps are an artistic decision forced upon mod and game developers. Because I don't believe this feature can ever be salvaged, I just want a global off switch per client, akin to skybox settings. Not per node or per object - that would be an undue server bandwidth and code size burden. Per material flags have utility, but they are no replacement for a global setting.

**I believe this issue should be closed...**

Shadow maps are a feature that is still **in-development** -- it has issues, etc, that need to be addressed/tweaked.

One should not be using anything from **mater** on a production server -- with the expectation that everything will run without issues.

The only thing that **master** should be used for is to determine if an issue in a stable branch has been fixed in the latest dev version and for adding new features.

IMHO: Production servers should be using the latest stable branch (meaning no current-dev features).

Also per **occam's razor** the simplest (and easiest) thing to do is to inform server players that shadow maps should be turned off for best client-side performance / appearance -- it really doesn't need to have a "global-off switch" accessible from the server-side.

**Comment by Wuzzy2** [comment]
Here's a compromise idea (especially for next version): Keep the setting as-is, but remove the shadowmaps drop-down list from the settings menu, just keep the setting in the "All Settings" tree instead and explicitly add the word "EXPERIMENTAL" and a explanation in the setting description and name. That way, if the graphics breaks, it's not our fault. ;-)

**Comment by sfan5** [comment]
Has been discussed: https://irc.minetest.net/minetest-dev/2021-09-04#i_5870705

It is my opinion that even if we do this gamedevs will (rightfully) still complain about having no control over it, therefore I suggested hard-disabling it for a release.

**Comment by lhofhansl** [comment]
I respectfully disagree with a hard-disable. Gamedevs have no control over whether I turn on waving plants or water, or tone mapping, or whether I turn on opaque water, or how far I set visible range, etc.

That said I do think is that we should add a Lua API to set the shadow strength (0 disables it completely). That way game devs can use this for mood, less shadows on a cloudy day, strong shadows on sunny islands, or no shadows. Down the road that should even be a biom setting.

Maybe we can handle this similar to how we handle the zoom feature where a mod can explicitly override zoom and disable it.

In any case, on *my* client, in the game that *I* am playing, I still want to be able to override this without the need to patch and recompile. Maybe - again like zoom - we allow setting it client side in "Creative Mode"

**Comment by lhofhansl** [comment]
For zoom we're using a player property. Mod can override that to achieve the effect they want. Can we do that same for shadow strength?

**Comment by Wuzzy2** [comment]
The concern from game devs is that shadow mapping can ruin an otherwise carefully-designed game. For many voxel games, the simple shadow system is the point. Also, shadow mapping is deceptive cuz nodes appear much darker than their actual light level. That might be OK if the light level is not important for your game, but for some games, it is.

Settings are nice and such, but in games in which shadow mapping will actively ruin said game, letting players enable it without any warning or anything is a recipe for disaster, especially if the game was carefully designed *without* shaddow mapping in mind.
Shadow mapping is not comparable to "fancy leaves" or "waving plants" since those are relatively small effects. Shadow mapping, however, is a MASSIVE graphical change with huge implications. So it should definitely be treated with care.

On the other hand, I know that players want to do everything.

Here's my idea:
* Add a mod function or whatever that prevents shadow mapping from being applied
* In the `lua_api.txt`, write that disabling shadow mapping server-side is3 recommended if the gameplay/graphics would be too broken with shadow mapping. It should be seen as a kind of technical note for the client, and should always be done for a reason. It should not be used to deny players to use this feature just for the sake of it.
* Add a clientside setting that, if set to `true`, will ignore the server/game choice. This setting should have a clear warning that game quality might detoriate if it is being used. Default is `false`

That way, game devs have some control on whether shadow mapping is a thing, but that choice can still be overridden by the player at the end.
Also, with my definition, it seems that many games would not really need to disable shadow mapping. Like, Minetest Game is probably fine. It is the few instances of game in which shadow mapping would actually ruin things for which this is meant.
If game designers use this disabling responsibly, players would never need this clientside override. But I added this idea anyway to provide an "escape hatch", basically

**Comment by lhofhansl** [comment]
@Wuzzy2 I agree with your three points. That's what I was trying to get it.

**Comment by v-rob** [comment]
I'd personally prefer an all-or-nothing approach to this (i.e. giving the server full control over disabling things like smooth lighting and waving leaves as well as shadow mapping) because that would make the most sense (for instance, a game's theme may be best suited to no fanciness at all, so hard lighting).

With that said, I think that giving shadow mapping temporary special treatment is fine for now; however, the need for special treatment may be mitigated by shadow maps being compiled out for 5.5.  By 5.6, things can be hammered out.

**Comment by x2048** [comment]
@lhofhansl @Wuzzy2 I'd love to see shadow strength controlled from both player and mod side, something like `final strength = mod value * player setting`. Screens are different, and the same shadow intensity value produces drastically different results on e.g. the two laptops I have.

The mod value would range from 0 (None) to 1 (Sunny day shadow), and player could adjust the maximum intensity for their screen.

**Comment by lhofhansl** [comment]
> may be mitigated by shadow maps being compiled out for 5.5

That's what I'm trying to avoid. :)

Maybe as a compromise we can remove the shadow part from the main settings page and keep the default off. That way you can enable it if you bother to go to advanced settings but most people won't.

**Comment by Wuzzy2** [comment]
I think implementing a per-setting control is going to be MUCH more complicated than a simple global on/off/override switch. It also goes WAY beyond what this issue was proposing anyway. Per-setting control is nice, but should be a long-term goal, especially considering the many problems the shadow mapping still has (those should be fixed first before even more features are piled up).

For the short term, I think a kill switch is more than enough. Also remember this issue is a blocker, please do not overload it with additional requests

**Comment by v-rob** [comment]
> Maybe as a compromise we can remove the shadow part from the main settings page and keep the default off. 

> Has been discussed: https://irc.minetest.net/minetest-dev/2021-09-04#i_5870705

---

> For the short term, I think a kill switch is more than enough. Also remember this issue is a blocker, please do not overload it with additional requests

Never said anything to the contrary.  I think compiling it out is the best solution for 5.5.  I'm just saying that in the future, shadow maps shouldn't get extra special treatment.  Higher priority treatment, certainly, but there's nothing intrinsically special about shadow maps.

**Comment by lhofhansl** [comment]
In that case, and for the record, I'll note my express disagreement with compiling it out.
(You can blow up so many things with the advanced settings and somehow shadows break the bank.)

**Comment by v-rob** [comment]
Personally, I think an experimental setting would be sufficient, but I'm probably biased as I always play singleplayer and thus have full control over everything instead of server vs clients.  However, I'm convinced that compiling it out is the best compromise for now because, while there may be some disappointment among users, server owners/game makers will have no problems, and ultimately, we'd be in the exact same place we were before shadow maps even existed.  Unless someone comes up with some server-side control before 5.5, that's probably the only solution that won't cause uproar.

**Comment by sfan5** [comment]
>  Add a clientside setting that, if set to `true`, will ignore the server/game choice. This setting should have a clear warning that game quality might detoriate if it is being used. Default is `false`

You can argue this point if only MTG and MCL exist, but for all other games it brings the problem right back.

Take for example nodecore, the sky always looks the same and there is no sun. When shadows are forcefully enabled, from where does the light come?
This is a trick question of course, no matter what you answer it will be wrong.
If you allow users to force shadows on and they *will* do this (especially if you put it in the main menu) you also force game authors to deal with this.

Now if you are advocating for an override switch after shadow mapping has all the server APIs envisioned, there would be no point when the server says "nope I don't have any light sources".

**Comment by neoh4x0r** [comment]
---

**To me this is the root of the issue:**

Current features, in varying states of development, are all being lumped together.

---

Obviously in its current state **shadowmaps** are an experimental feature.

I think the easiest thing for now (from an architectural view) is to:

Use a branch paradigm like the following (similar to Gnu/Debian, etc):
```
*Experimental*: Things that are not ready yet (shadowmaps should go here for now)
    *Unstable*: Active development
     *Testing*: Things that need to be tested
      *Stable*: Things that are polished enough for release
```
A server operator (and its clients) should be using _**stable**_ for production servers/clients.
Anyone wishing to test current features should be using _**testing**_ and not on production servers/clients.
No one should be actively/directly using anything from _**Unstable/Experimental**_.

**Shadowmaps** should be moved into the _**experimental**_ branch; maybe even moved into its own
branch (tagged with "experimental").

This would give use an invariant (a rule-based assumption that is always true):
**If it's an experimental/unstable feature, then no one is using said feature**.

This change to the **branch paradigm** also has the added benefit of handling any future features
that could cause similar issues.

If we segment those features into the different branches that reflect the "experimental/unstable, etc"
paradigm it will make it much easier to deal with.

**Comment by x2048** [comment]
> The point of moving to experimental is so that minetest development can move on without the need to implement some "quick fix".

Hmm, right now with SM commits interleaved with a lot of other useful stuff, branching off and creating some 'stable' branch sounds like much more work than just #if'ing it out.

**Comment by lhofhansl** [comment]
> This is a trick question of course, no matter what you answer it will be wrong.

:)

> If you allow users to force shadows on and they will do this (especially if you put it in the main menu) you also force game authors to deal with this.

Agreed. IMHO (and it is really just MHO) removing it from the main menu is all that is needed. Clients can mess up so many things already via fiddling with the "Advanced Settings")

> Shadowmaps should be moved into the experimental branch; maybe even moved into its own
branch (tagged with "experimental").

If you mean a separate git branch... No, it will bitrot and be unusable when we want it.

I think we need to agree on a short term (5.5.) and a long term (5.6+) solution.

Can we agree that (1) for 5.5. we remove the shadows setting from the main menu (and leave default off), and (2) for 5.6. we'll make it server API driven (global, player, biom, or whatever we think is best)?

**Comment by Wuzzy2** [comment]
Yes, remove shadow mapping from the main settings menu since it's basically experimental. Also mark the setting as experimental in the "All Settings".
This solution has the obvious benefit in that it needs the least work. Great if you're in a hurry.

The other proposed solutions need more effort.

**Comment by v-rob** [comment]
Actually, compiling it out sounds just as easy because you just remove the setting altogether.

As a summary for how things stand, the two camps for 5.5's behaviour are as follows (core developers only, and correct me if I'm incorrect):
* **Compile out**: celeron55, sfan5, SmallJoker, hecks, v-rob
* **Experimental in advanced settings**: lhofhansl, nerzhul

Of course, some people have expressed that they can be fine with either, but they lean towards compiling out to be on the safe side.

**Comment by ronoaldo** [comment]
I honestly don't understand the point against this feature since, for instance, you can just grab a texture pack and it will change all the hand crafted work done by the creator regardless. If the reason is to give control to server owners, it would make sense to do it consistently and not just for shadows, wouldn't it?

As a user, (and server owner) I would be much more happy if the setting is an experimental option, rather than it being something ripped off from the release.

I'm not a core dev, just my two cents.

**Comment by runsy** [comment]
NOOO, I don't want to do without shadows. Because:

1) Shadows are long overdue.
2) The problems are few and far between. 
3) It goes fast. If someone has a cave-age PC, it's easy, let them buy a new one, but don't screw the rest.
3) Modders or game creators to update their obsolete products to fit this, not the other way around. because of a few who have their stuff broken you can't implement .... no.
4) I use 5.5-dev. I enjoy the shadows. I would find it fatal if it was "removed" from me.

**Comment by erlehmann** [comment]
> If someone has a cave-age PC, it's easy, let them buy a new one, but don't screw the rest.

Cool, are you planning to give money to everyone who is affected by performance problems?

> Lazy modders or game creators to update their obsolete products to fit this

This has nothing to do with being lazy. How do you propose a mod prevents shadow-related bugs?

Also, requiring every mod to deal with new engine breakage would be requiring useless busywork.

**Comment by runsy** [comment]
> > If someone has a cave-age PC, it's easy, let them buy a new one, but don't screw the rest.
> 
> Cool, are you planning to give money to everyone who is affected by performance problems?

Let's see, my friend, the first thing they tell you in the guides to optimize games is: "Disable or reduce shadows". It is one of the things that consumes more resources. Precisely the shadows are optional, so that people who have medium or low PCs can reduce or eliminate them.

So the shadows in Minetest are always going to be a burden unless you have a powerful computer. No matter what implementation is done.

Anyone who pretends to play with shadows and that the performance does not drop is simply a fool.

> > Lazy modders or game creators to update their obsolete products to fit this
> 
> This has nothing to do with being lazy. How do you propose a mod prevents shadow-related bugs?
> 
> Also, requiring every mod to deal with new engine breakage would be requiring useless busywork.

The shades work well for me.

> Also, requiring every mod to deal with new engine breakage would be requiring useless busywork.

Breakage would be if there were crashes, small minor bugs would not be a problem. Mods that depend on light levels can be adapted.

**Comment by runsy** [comment]
The first photo above is of a character that is not square, but a super detailed and round mesh. Let's see Minetest is a cubic game. Of course it looks bad. But with standard models everything is fine.

Or is it that we want the Minetest engine to be like Crisys. Come on, a little bit of please...

**Comment by runsy** [comment]
My proposal, put it in the next version as experimental in options. And if people use them in servers, that's up to them, let the servers and players wake up.

In version 5.6, the devs will be able to polish the small bugs.

If it is removed from the main branch I tell you what will happen: There will be no shadows in a thousand years.

**Comment by v-rob** [comment]
> The shades work well for me.

Cool.  Other people have found that they don't work and cause issues for their games, and that's the issue here, not whether they work for an individual person.

> The first photo above is of a character that is not square, but a super detailed and round mesh.

Why shouldn't we support that?  Who's to say that Minetest has to be blocky?  To be sure, blocky things generally work very well in Minetest, but I don't see any rules that say we refuse to support non-blocky stuff.

> If it is removed from the main branch I tell you what will happen: There will be no shadows in a thousand years.

It's not being removed, the intent is only to disable it from the front end (i.e. no settings for it will be available, but the code will exist).  Plus, that statement is deliberately fatalistic to try and influence the decision and has no grounding in reality -- this is a really popular feature, and many of the devs like it, otherwise it wouldn't have gotten merged so fast in the first place.

**Comment by 0-afflatus** [comment]
I like the shadows. That's not a technical reason for anything and they are far from perfect yet.
The only issue worth talking about here is that it needs to be possible to disable them both on the client and the server. That really should not be controversial.

**Comment by benrob0329** [comment]
I'm gonna put my 2 ~~cents~~ bucks in the jar as another game developer, feel free to disagree with me.

I think that the effects of this are way overhyped and that a knee-jerk reaction is the worst thing we could do in response to it. Lots of the suggestions for new APIs (or worse, hardcoding existing APIs to have effects on shadows) are making massive assumptions about the direction and feature-set to come. We don't yet know whether shadows will be multi-source, or if they'll stay single source for performance/technical reasons. We don't know whether shadows will respect all world properties properly and be reflective of how the lighting would look and thus make many of these points moot. We just don't know, and trying to make decisions for a feature which is still as WIP as this is will bite us in the ass.

You could argue that they should have never been merged, but then it would have likely never been merged at all (like many large features). I think that it's perfectly reasonable to introduce a new feature as WIP for testing with a wider audience, and mature it over one or two releases as feedback comes in. It's really quite silly to think that everything players and coders can mess around with needs to be perfect or stable, these things take time and imperfect progress is better than no progress at all. Imagine if we did gamedev like that, nothing would ever get done!

In the end, yes, the shadows look bad for some games. How many that players actually interact with? Well, Hecks' game isn't public yet (and afaik won't be for quite some time) so the effect on that is moot for players until released. Nodecore "looks bad" with them, but it doesn't actually break gameplay, so once again not a big deal. IKEA has been tweaked to support them anyways as of current master. MTG and forks (which is still the majority of MT's actual playerbase) seem to be fine. Mineclone2 & Co. are the only games I can think of where this would actually affect gameplay due to light-level mob spawning, but then so do shadow mods in MC proper too ~~so it seems fitting~~ so anyone coming from that would already expect as much. It seems to me that most of our playerbase won't be _harmed_ by enabling shadows (although framerates will suffer), and some might even enjoy having them around despite the issues.

If we try to cater to the assumption that people are hopelessly idiotic, we'll lose. We need to have a reasonable amount of notice for those looking to try out this feature (because informed consent is important) and beyond that, it's simply not our problem. I'm not against shoving it into All Settings (although I do think it's overkill), but I am absolutely for adding a caution to the setting (we're asking users to be cautions while proceeding, not to stop proceeding entirely).

I am absolutely against compiling out shadows, I think that such a proposal is horribly overkill and even detrimental to our ability to improve them and gain feedback appropriately. I am also against adding in premature APIs which make assumptions about future features and the intended use of them just for the sake of getting a release out.

While Lua-controlled graphical options are long overdue, let's actually add that in properly when we have time to think through the intended uses of those options and how they can be make more useful with that, instead of just repeating CSMs all over again by making them completely useless due to complaints which more often reflect other unaddressed issues than anything particularly new.

**Comment by erlehmann** [comment]
> Mineclone2 & Co. are the only games I can think of where this would actually affect gameplay due to light-level mob spawning, but then so do shadow mods in MC proper too so it seems fitting so anyone coming from that would already expect as much.

I think https://github.com/minetest/minetest/issues/11972 will be a problem too, not only for MineClone2 & MineClone5 & Mineclonia, but also for all other games and mods that have a sunless sky (e.g. space games, games where being deep underground switches the skybox etc.).

**Comment by runsy** [comment]
Yes, Juanchi also supports shadows. now. And the future Samz.
