### ISSUE TITLE
Add AVIF support

### ISSUE THREAD

**Issue by GrimPixel** [minetest/minetest#11434]
AVIF is a new image format with unmatched advantages like smaller size and shorter loading time. I guess it might be used for textures.
https://jakearchibald.com/2020/avif-has-landed/

**Comment by hecktest** [comment]
Most content made for Minetest uses a pixel art style, with low color counts and sharp edges. A lossy format is useless for this purpose. As you can see on the page you linked, avif actually _loses_ to png in the lossless case!

With a good deflate implementation like PNGOUT, you can crunch png even harder, possibly beating even this guy's contrived lossy-to-lossless comparison. I'd try it myself but his page is so bleeding edge that it curiously fails to serve me the png and jpeg examples (and only those, hmm).

**Comment by HybridDog** [comment]
I think the [JPEG XL](https://jpegxl.info/) format would be better suited for textures.
In comparison to other formats which mainly target compression ratio, the JPEG XL en- and decoding are additionally designed to be fast. The JPEG XL format supports lossless and lossy compression.

I compressed the default textures with oxipng -Z and oxipng -omax, and converted them losslessly to JPEG XL with cjxl -s 9 -q 100.
Here are the resulting file sizes: [jxl_png_comparison.txt](https://github.com/minetest/minetest/files/6797226/jxl_png_comparison.txt)
In sum, the PNG files are 85.421 KB and the JPEG XL files are 68.040 KB.

**Comment by v-rob** [comment]
I think the only mod I've seen which didn't use PNGs was sofar's skybox mod, which used JPEGs.  This format could possibly be an advantage for ultra HD texture packs, but basically nothing else.  After all, how much compression can be gotten out of a 16x16 texture that PNG doesn't already do?  I don't think it's especially worth it for us.

**Comment by hecktest** [comment]
Benchmark of PNG vs JXL:

`png` - Naive PNG from my working folder, most are uncompressed
`pnc` - PNG as emitted by Magick with no options, normal compression
`pno` - PNG crushed by Ken Silverman's PNGOUT (this is what my server would send you)
`jxl` - JXL emitted by the latest stable build of Magick (with `-compress Lossless` for whatever that's worth)

- `BodyTexture` : An organic UV mapped texture of a nude featureless humanoid. No eyes or any other features are present; only shading gradients. 24 bpp but using only 1814 unique colors.
- `BodyTexture_256` : 8-bit dithered reduction of the above.
- `gui` : HUD and formspec shared tileset, paletted, mosaic of varying tile sizes, 8 bpp.
- `woods, ancient, terrain` : Node texture tilesets, uniform 32x32 tiles, 8 bpp.

All textures are 256x256 in size; I use `^[sheet` tilesets for convenience.
Transparency is done with `^[makealpha` applied to the background color.

```
bytes    name
12299 ancient.jxl           
 6006 ancient.pnc           
 6543 ancient.png           
 4910 ancient.pno           
 6195 BodyTexture.jxl       
47339 BodyTexture.pnc       
47339 BodyTexture.png       
43888 BodyTexture.pno       
 6361 BodyTexture_256.jxl   
31295 BodyTexture_256.png   
29510 BodyTexture_256.pno   
 7515 gui.jxl               
 2526 gui.pnc               
 3744 gui.png               
 1878 gui.pno               
 9418 terrain.jxl           
 7637 terrain.pnc           
 8151 terrain.png           
 6375 terrain.pno           
20904 woods.jxl             
11398 woods.pnc             
14263 woods.png             
 9967 woods.pno             
```

The result for `BodyTexture` is remarkable but suspicious - it's probably a lossy image, and I literally cannot find another working encoder, any relevant options for magick, or even something to preview this with. There's a new fancy image format made every damn week it seems, all these FLIFs, AVIFs, whatever, and they can never seem to even provide decent tools to try them out with.

In all other images jxl still loses to PNGOUT, so it's either worse than png in the common case or straight up disqualified for lack of a working, easy to obtain lossless encoder.

PNG does not need a replacement because it's already very close to the theoretical maximum of what you can do with a lossless representation of a 2D image. Instead of putting more vaporware on the table, try looking for ways to optimize your PNGs harder.

**Comment by HybridDog** [comment]
> […] I literally cannot find another working encoder […]

I used the encoder/decoder tools from the [JPEG XL reference implementation](https://github.com/libjxl/libjxl).

> There's a new fancy image format made every damn week it seems, all these FLIFs, AVIFs, whatever, […]

FLIF is a predecessor of FUIF, which is a predecessor of JPEG XL. I don't think JPEG XL is going to be replaced very soon:
"The L is supposed to mean Long term, since the goal is to make something that can replace the legacy JPEG and last as long as it did."
https://gitlab.gnome.org/GNOME/gimp/-/issues/4681#quotes

> In all other images jxl still loses to PNGOUT, so it's either worse than png in the common case […].

The encoder and decoder are still in development and receive improvements and don't use the strongest compression effort by default. I passed the `-s 9` flag (slowest compression), which should always be used for the small textures in my opinion.

> PNG does not need a replacement because it's already very close to the theoretical maximum of what you can do with a lossless representation of a 2D image.

A theoretical maximum only makes sense if there's a defined probability distribution over all possible images; for example, it can be likely that neighbouring pixels have a similar colour.
For common images such as Minetest textures the meta-adaptive [ANS](https://en.wikipedia.org/wiki/Asymmetric_numeral_systems) and other JPEG XL features should outperform the PNG compression.
