### ISSUE TITLE
Minetest appdata project_license should be fixed

### ISSUE THREAD

**Issue by akozlovskiy119** [minetest/minetest#11441]
Please see https://github.com/flathub/net.minetest.Minetest/issues/32. The main points are:

- `CC-BY-SA-3.0` license is not considered free by FSF and OSI, see https://spdx.org/licenses/
- `LGPL-2.1+` is [deprecated](https://spdx.org/licenses/LGPL-2.1+.html) and should probably(?) be renamed to `LGPL-2.1-or-later`
- Official appstream documentation  [suggests](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-project_license) to list only code licenses in `project_license`:
> The license given in the project_license tag should be the ‘main’ license of the project. For a software project, this is typically the license for the code. It is not recommended to include the license for accompanying documentation (for example) in project_license, as that could confuse users. In particular, the CC-BY-SA-3.0 license which is commonly used for documentation is not an (FSF or OSI) approved license for free software, so including it in project_license results in the project as a whole being considered non-free. 

I am not very familiar with licensing issues, so I ask the authors to look into this carefully.

**Comment by sfan5** [comment]
I'm not sure whether only listing the code license makes sense. Minetest is an engine and of limited use without a game shipped with it.

Okay well that's not the entire story, you can join multiplayer servers and download games in-game without a bundled game (though note mainmenu resources are also CC-BY-SA).
The current distribution of "Minetest" is composed of the engine and a game called "[Minetest Game](https://github.com/minetest/minetest_game)", whose textures are CC-BY-SA-3.0 licensed and essential for its' functioning. Just omitting it doesn't feel like it's intended that way.

**Comment by akozlovskiy119** [comment]
I still don't understand - does that mean that `minetest_game` is non-free? This is confusing.

**Comment by rubenwardy** [comment]
Minetest Game is not nonfree and CC BY-SA is not a nonfree license - it's just not a code license, so isn't approved as a code license

**Comment by akozlovskiy119** [comment]
Then why specify it in `project_license`, despite the clear recommendation in the appstream documentation? I'm referring to @sfan5's previous comment:

> I'm not sure if it only makes sense to list the code license.

**Comment by rubenwardy** [comment]
because it is a project license, and it wasn't clear that project license actually means source license

The fix here is to remove CC BY SA from the list

**Comment by akozlovskiy119** [comment]
Well, yes, not so intuitive. Maybe in the future there will be `source_license`, `resources_license`, `documentation_license` and so on.

**Comment by sfan5** [comment]
> Then why specify it in `project_license`, despite the clear recommendation in the appstream documentation?

I wouldn't call it a *clear* recommendation. The documentation says that for a "software project" (a game is one, right?) it is "typically" the code license. It also talks about not using the docs license but we aren't doing that.

**Comment by rubenwardy** [comment]
Yeah, we have CC BY-SA resources such as images, it's not the documentation

**Comment by 0-afflatus** [comment]
>  including it in project_license results in the project as a whole being considered non-free.

> I am not very familiar with licensing issues, so I ask the authors to look into this carefully.

Minetest seems to pass DFSG well enough. Debian are one of the strictest enforcers of Free Software guidelines, so your statement above is false. Best to leave licensing issues alone unless there is a genuine problem.

**Comment by Wuzzy2** [comment]
OOOOooofffff ... So okay, claiming that CC BY-SA 3.0 is non-free is kind of a stretch, to be honest.

FSF considers CC BY-SA 4.0 to be free. The FSF doesn't seem to have said anything about the CC BY-SA 3.0. So the FSF neither classified it as free or non-free. Note that "does not consider to be free" does NOT means the same as "does consider to be non-free". Maybe the FSF never considered this license to begin with. If you REALLY care about this, maybe just send them a mail? Lol.

Anyway, to conclude from that that CC BY-SA 3.0 is therefore non-free is a HUGE stretch. If it is non-free, proof it. Name the specific clause that is in violation of free software principles. But just because FSF hasn't explcitly supported it so far does not mean it is non-free. The FSF does have a clear and explicit rejection of the -NC and -ND clauses in all CC licenses of any version, however.

The same reasoning goes for the OSI, obviously.

To me, it looks like this:

Are you allowed to use the work without discrimination? Yes.
Are you allowed to change the work? Yes.
Are you allowed to share the work, commercially or non-commercially? Yes.
Are you allowed to change the work and share those changes, commercially or non-commercially? Yes.

The only conditions are attribution and ShareAlike, but those have historically always been accepted by the free software movement. Overall, this sounds pretty free to me.

What the FSF does say about CC licenses in general is the following:

* -NC and -ND is definitely non-free.
* Always specify which precise CC license applies.
* You shouldn't use CC licenses for code. But this seems to be more for pragmatic reasons (since those licenses were never written with code/software in mind), not because of ethical concerns. See also: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software (FSF agrees with this)

----


That having said, the other parts of the issue look OK to me. Obviously, deprecated license identifiers should be updated.

> (though note mainmenu resources are also CC-BY-SA).

This means mentioning the CC BY-SA as media license is definitely correct.

**Comment by akozlovskiy119** [comment]
Please don't go too far with this. I am not claiming anything about licenses, I am not pushing for relicensing or something. All the info is from the relevant links that I attached.

My original issue was about gnome-software labels Minetest as proprietary. This has a very negative impact on Minetest popularity because it confuses people and may discourage them from trying Minetest at all, flatpak or not.

Is `CC BY-SA 3.0` free or non-free or even outside the concept of a free license and why it is not in appdata's [`spdx-free-license-ids.txt`](https://github.com/ximion/appstream/blob/master/data/spdx-free-license-ids.txt) file is another problem and should be discussed with appstream authors, with SPDX (Linux Foundation), with FSF and OSI. So if you have enough knowledge about this, please write to them, it will be better for everyone.

**Comment by sfan5** [comment]
Is there any news on clearer policies what we should write into the license field?

**Comment by akozlovskiy119** [comment]
No changes in appstream docs but `CC-BY-SA-3.0` was added to the list as DFSG-free, see https://github.com/ximion/appstream/commit/a608640c921024d3dc8af3031497846e3e3e195e and https://github.com/ximion/appstream/commit/5680d02dcccccf156b3f9b16b71fe6c9e6758bab. Gnome-software UI was changed and Minetest now displayed as community built so I believe problem resolved?
![Screenshot from 2022-01-31 14-17-40](https://user-images.githubusercontent.com/22382143/151858073-338fa31c-dccb-435f-b59b-a1c48b3f7f53.png)

**Comment by sfan5** [comment]
Yep, looks good.
