### ISSUE TITLE
Add farlands at the end of the world as a reward for those who venture that far out.

### ISSUE THREAD

**Issue by Destroyinator69420** [minetest/minetest#11489]
And perhaps some structures to be discovered at the end of the world as an additional reward for those who venture that far out. Maybe some loot in those structures as well?

**Comment by Warr1024** [comment]
Farlands were an accidental emergent feature of some game(s) due to floating point precision loss, but while an interesting curiosity they were never particularly playable.  They have appeared as fan tributes/references in other games, but are not necessarily appropriate in every game.

If you would like a game to add this as a feature then you should request it with that game, not for the engine.  It's also up to the games whether venturing that far is actually something worth rewarding in the first place.

**Comment by rubenwardy** [comment]
Thanks for the suggestion. Games are responsible for adding gameplay content like this. Additionally, farlands are a bug that doesn't make sense to replicate unless you're making a Minecraft clone, which isn't the only type of game that Minetest supports
