### ISSUE TITLE
Clarification of vector representation compatibility

### ISSUE THREAD

**Issue by TurkeyMcMac** [minetest/minetest#11529]
## Problem

The documentation says this about vectors:

> Internally, [a vector] is implemented as a table with the 3 fields `x`, `y` and `z`. Example: `{x = 0, y = 1, z = 0}`. However, one should *never* create a vector manually as above, such misbehavior is deprecated. The vector helpers set a metatable for the created vectors which allows indexing with numbers, calling functions directly on vectors and using operators (like `+`). Furthermore, the internal implementation might change in the future.

The problem is, it's quite useful to use vectors and regular tables interchangeably. For example, if you receive a position as a callback argument, the most convenient way to operate on it is with the `vector.*` functions. Likewise, it's useful to be able to change a position with the vector arithmetic functions then pass it as an argument to e.g. `minetest.set_node`.

The interchangeability I describe is currently used by such mods as [mobs_redo](https://notabug.org/TenPlus1/mobs_redo/src/master/api.lua#L512) and [beds](https://github.com/minetest/minetest_game/blob/92701885d086e5123c2c8cca0774e9d9e2327558/mods/beds/api.lua#L10).

## Solutions

I think that the `vector.*` functions should continue to accept tables without the vector metatable. I don't think this is much of a constraint.

I also think that Minetest API functions should continue to accept vectors as positions. This is my main point of concern.

Any alternative vector implementation would probably have to stay mutable to be position-compatible. The only alternative implementation I can think of would be to use LuaJIT's `cdata` rather than tables, which would fulfill this. `cdata` would probably work with almost all functions as long as they only get and set the `x`, `y`, and `z` fields of the position. The exception is type checking. I know that at least some of the API functions implemented in C++ check that their position arguments are tables, and under this solution they would have to be changed if the vector implementation were changed.

The documentation I quoted should be changed to reflect the chosen solution.

## Alternatives

I think that treating a table without a metatable as a vector is doable whatever the solution. An alternative to allowing vectors to be used as positions would be to add a function `vector.to_table(v)` to convert a vector to a position table. This would just be a bit less intuitive/convenient for users of the API.

**Comment by sfan5** [comment]
@Desour thoughts?

**Comment by Desour** [comment]
I guess the documentation could have more details...

* The main purpose of the builtin `vector.*` lib is that it's compatible with what the minetest api provides, and the other way around:
  * `minetest.*` functions that require a pos, direction or similar (this doesn't apply on 2d positions and some other things that don't make much sense to be a vector) must always be able to take a `vector.*` vector.
  * Callbacks give you `vector.*` vectors. (If not, then that's a bug and should be fixed.)
  * I guess it's fine if something says that it needs a pos, then that will be a value (of type table) that you can access via `.x`, `.y` and `.z`.
 
* There's *very* much code (in mods) that doesn't use the `vector.*` helpers, and also code that passed simple tables to `vector.*` helpers. We can't simply break compatibility for this from one decade to the next. In fact, I think, the `minetest.*` functions just assume that you can access the vector elements via `v.x` and co..
  There's also this paragraph for `vector.*`:
  https://github.com/minetest/minetest/blob/eefa39e47b4ef1f6a51854461efee99777ae20fd/doc/lua_api.txt#L3253-L3254

* You can't necessarily use no-metatable table vectors and `vector.*` vectors interchangeably for apis provided by new mods. They may require you to use `vector.*` vectors, which allows them to assume that their function arguments have metatables. (Ie. directly use `+` on your argument instead of first using `vector.add`.)
  The same might apply to new apis provided by minetest itself.

* You can't use `vector.*` vectors exactly like simple tables, ie. `v.add` will never evaluate to `nil` and `v[1] = 42` will modify `v.x`.
  However, I don't know of any mod which has broken because of these minor differences.

* The `vector.*` helpers' main purpose is to make the api easier to use. It doesn't make much sense to give helpers that can't be used with minetest's api and don't have an implementation that provides superior performance, many people would not use that.
  Nothing speaks against using your own performant vector helpers and converting them to and from `vector.*` vectors.

* After looking a bit into the api doc, I saw in several places that it shows tables of the form `{x=..., ...}` where vectors are expected (eg. [here](https://github.com/minetest/minetest/blob/eefa39e47b4ef1f6a51854461efee99777ae20fd/doc/lua_api.txt#L8478)). I guess this can cause much confusion.
What should be written there instead? (`vector.new()` if a 0-vector is the default, maybe? But what if there is no default?)

* A possible alternative implementation that stood in the room was using array-like tables (`{x, y, z}` instead of `{x=x, y=y, z=z}`) that provide `.x` access via its metatable (see also #9612). Then you could use `v1[1]` in `v1:add(v2)` to maybe gain a marginal performance benefit.
  I'm not sure if one would want to directly expose a `cdata` to mods. For some types (ie. arrays and pointers) I'm pretty sure that it's unsafe. So, you might want to hide the `cdata` eg. in the metatable of a table anyway.

Uff, this became longer as I thought and may contain redundancies, sorry for the wall of text.
