### ISSUE TITLE
Documentation API Formspec "Background9"

### ISSUE THREAD

**Issue by sirrobzeroone** [minetest/minetest#11559]
##### Minetest version
5.4

##### Summary
The background9 to me could use a slight clarification inside the API - The line below implies, that the image must be sized in these dimensions - I think it has just been copied from background. It didnt gel with my understanding of 9 slice and when I ran some tests MT engine adheres to the normal/accepted 9 slice behaviour that you would expect if you have used it before:

* Example for formspec 8x4 in 16x resolution:
* image shall be sized 8 times 16px  times  4 times 16px
https://github.com/minetest/minetest/blob/e7b05beb7d90b4ea53ef13da86ff8b8ccde1193b/doc/lua_api.txt#L2465

Fully agree that it works better and easier for user to visualise - however for a 9 slice its not required and the key is the middle pos x,y,x2,y2. It might make it easier for new users if the wording was something like the below?:

```
Example for formspec 8x4 in 16x resolution:
The image could be sized 8 times 16px  times  4 times 16px, 
however for a 9 slice background this is not a requirement.

Using middle definition "x" or "x,y" will result in less control 
of the background look compared to using "x,y,x2,y2" and 
it's best to use "x,y,x2,y2" if not using an image in multiples 
of 16x/32x etc resolution.
```

Just a suggestion :)

**Comment by v-rob** [comment]
Yeah, those docs about image sizing really don't necessarily apply to 9-slice background, so could be removed.  I don't fully understand "it's best to use "x,y,x2,y2" if not using an image in multiples of 16x/32x etc resolution", though--the "x" and "x,y" forms are just shorthands for "x,x,x,x" and "x,y,-x,-y", respectively, so it makes no difference whether it's 16x/32x or otherwise, only whether the borders have a uniform width.
