### ISSUE TITLE
Cannot build standalone server with headers on CMake 3.5 through 3.10

### ISSUE THREAD

**Issue by JosiahWI** [minetest/minetest#11564]
##### Minetest version
```
N/A
```

##### OS / Hardware
Operating system: N/A
CPU: N/A

GPU model: N/A
OpenGL version: N/A

##### Summary
https://cmake.org/cmake/help/v3.21/command/target_include_directories.html states that using target_include_directories to set `INTERFACE` includes on `IMPORTED` targets was introduced in version 3.11. Our minimum version is 3.5, but we use this 3.11 feature to set includes on the `IrrlichtMt::IrrlichtMt` target for building the server. We can fix this by:
- bumping the minimum version to 3.11 (probably undesirable for us)
- setting the include property manually (standard straightforward solution)
- adding logic to use the variable directly in that one case (results in confusing interdependent logic split between two files).

Credit to discord user Juri for original report.

##### Steps to reproduce
Build the server (without the client) on any CMake version < 3.11

**Comment by debagos** [comment]
Good day, thank you for reporting what I initially reported on Discord.
But I already created a bug report and it's already closed, which is why you probably missed that out.

Your summary is pretty accurate and helped me understand the problem better :)

The original report is: https://github.com/minetest/minetest/issues/11562.
An PR with a small discussion on that topic you can find here: https://github.com/minetest/minetest/pull/11563.
