### ISSUE TITLE
Formalize protocol version bump release policy

### ISSUE THREAD

**Issue by Warr1024** [minetest/minetest#11603]
Modders require some way to differentiate between different releases where different features are present.  Not all features that may be relevant are automatically covered by things accessible to modders, e.g. when a feature has a major bug fixed this is not always applied to the "features" list, and bugs that affect how clients interpret and present things need to be detected on a per-client basis.

For this reason, it was proposed that, at least for the main official Minetest release client, at least one mechanism is needed that would allow a mod to differentiate between each different public official release.  Much discussion has already occurred, including #10368 and #10933 with proposed solutions, and #10387 explaining why the existing situation is inadequate for this purpose.

The general consensus was reached among the devs involved that the simplest and most effective solution for this would be to just ensure that the protocol version was bumped by at least 1 for each public release.  This is also more broadly sensible, since the "protocol version" has historically been treated as covering only the IDs and structures of packets, but what constitutes a "protocol" really should encompass meaning and interpretation, and thus different client behavior interpreting existing packets constitutes a change to the protocol in a broader sense.  The protocol version would provide a single place for modders to look for at least a good sense of what version a client is probably running, and thus how they are likely to interpret information sent by the server, so bug workarounds and the like could be decided upon.

We got as far as noting this new policy in the release procedures at https://dev.minetest.net/Releasing_Minetest#Before_releasing, but it's marked as "pending discussion" still.

The purpose of this issue report is to conclude that discussion, and (at least I hope) ratify this protocol bump as part of the official release process.

**Comment by Warr1024** [comment]
Alerting all core devs who were also involved in the above past discussions:
@rubenwardy @sfan5 @SmallJoker @hecktest @v-rob

**Comment by SmallJoker** [comment]
Suggested wording:

Unless already done within the development process, the protocol version is to be increased when client-specific API changed. This includes changes which were implemented without a protocol version bump, such as new tailing package data.
Same goes for the formspec version even when the changed API is backwards-compatible.

**Comment by Warr1024** [comment]
I want to clarify that the version bump needs to be done any time behavior as presented to the client could possibly change, which should mean every release.  If we haven't done sufficient change to justify a protocol version bump, then we surely haven't done sufficient change to justify a release.

The only exception I would consider would be an emergency hotfix point release that only fixed a server crash or something and had no effect on client code.  However, the complexity of actually checking for this condition in the release process is not worth it just to avoid a protocol version bump.

I am alright with SmallJoker's wording if we just trim the unnecessary and confusing "when client-specific API changed" part.

**Comment by sfan5** [comment]
I previously advocated for not bumping the protocol version if the formspec version has been bumped but I changed my mind. It's better the other way.

> The only exception I would consider would be an emergency hotfix point release that only fixed a server crash or something and had no effect on client code.

Unless the hotfix release is done from master (has never happened so far) a backported release *cannot* raise the protocol version as its meaning would conflict with a future bump done on the master (=development) branch.

Also I don't think it's unreasonable to allow coredevs to decide about the need of a bump. It doesn't have to be defined to the smallest detail, after all we have coredevs with enough experience to assess this accurately.

　
Suggested wording:

  If not a patch release: If changes have been made to client behavior that is relevant for server modding (e.g. new HUD types/node fields/packets, significant fixes to existing features) since the last release then ensure `PROTOCOL_VERSION` has been increased.
  Doing this is supposed to provide modders with the ability to accurately detect whether features they care about work on a particular client. **If unsure**, err on the side of caution and bump anyway. Also note that `strict_protocol_version_checking`  relies on this to work accurately.

**Comment by Warr1024** [comment]
I don't think it's unreasonable to _allow_ the coredevs to decide whether a version bump is needed, I just think that placing the burden of this decision on them is unjustified.  So far we have had very few actual instances where two client versions were undifferentiable and it's caused modders problems (the 5.2/5.3 thing is the only one I know).  The issue is just that there is a high cost associated with this mistake (you can't unrelease a release to all the people who already downloaded it and now expect it to Just Work) and there's a very low cost associated with the alternative (it could lead to protocol version exhaustion in the next 20000 to 30000 years).

Including a bunch of "if unsure" or "if necessary" sort of implies that being able to correctly make this choice is considered at least a significantly likely path, if not the majority case, for any arbitrary dev following the process.  That may be the case most of the time, but we do see turnover, not everyone can understand every bit of work done by somebody else in a cycle, the commit messages don't necessarily encompass all the implications of each change, nobody has the time and energy to read every line of changed code, and we just ultimately make mistakes no matter what we try.  A good process should attempt to exclude the opportunity for error, not try to preserve it.

Also, my understanding of ALL of our processes is that there's already an implicit "only if reasonable" stipulation, i.e. if there is a special circumstance that renders a process or policy unreasonable, then we will do what is reasonable instead when that happens.  So there is no need for a trap door to be built around the policy.

The purpose of this policy is, insofar as is possible, to create _certainty_ for modders that they can correctly predict a client's capabilities _including_ unforeseen or later-discovered bugs or quirks.  Iffy language will get rid of that certainty.

Here's the language I propose:

> If not a patch release: Ensure PROTOCOL_VERSION has been increased since the last release.  If it has not, then increase it by one.
> Doing this is supposed to provide modders with the ability to accurately detect whether features they care about work on a particular client, including detecting bugs or quirks that may be unknown to core devs at the time of release. Also note that strict_protocol_version_checking relies on this to work accurately.

**Comment by sfan5** [comment]
> Also, my understanding of ALL of our processes is that there's already an implicit "only if reasonable" stipulation, i.e. if there is a special circumstance that renders a process or policy unreasonable, then we will do what is reasonable instead when that happens. 

Dunno, I take the written down policies seriously and try to make exceptions only for very good reasons.
This is also the reason I proposed an escape hatch wording.
It looks like we essentially don't disagree and it's just a matter of how devs are assumed to interpret this.

**Comment by v-rob** [comment]
Honestly, I doubt that there will be many instances in which we wouldn't bump the protocol version, so I'd just advocate for bump on all non-patch releases, and if an exception seems necessary, then we all gabble at each other over IRC like we always do.  That being said, the exact policy doesn't matter much to me as long as we consistently bump the protocol version when necessary.

**Comment by celeron55** [comment]
I think the problems resulting from realizing a feature breaks something after a release was already made without a protocol bump can be greater than the problem of having to update a client when the protocol version is bumped in a minor release without there actually being incompatibility.

I would go with always making sure the protocol version is bumped between minor version releases. It's simple, and we're not running out of protocol versions anytime soon at that rate. There's value in not having to think about something.

So, I'm fine with "If not a patch release: ensure that PROTOCOL_VERSION has been increased since the last release.".

**Comment by sfan5** [comment]
Wiki page edited.
