### ISSUE TITLE
5.5 release plans

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#11600]
## Background

Per our rough release schedule 5.5 would have been targeted for August. But then the shadowmapping PR was merged, necessitating a way for games/mods to toggle it off (and other things, it's too hardcoded atm). Since our code does not support swapping out shaders at runtime this led to @hecktest planning to rewrite the renderer, which is currently ongoing.

## Proposal

This was briefly discussed in the [last meeting](https://dev.minetest.net/Meetings#2021-09-04). I propose releasing 5.5 relatively soon without waiting for the renderer re-do.

This would necessitate solving the following issues:
* #11365 and other problems
  <i>suggestion</i>: Disable shadowmaps in the C++ code (so that it cannot be enabled even if you know which setting to change) and hide the mainmenu combobox for release.
* #11437
* #11611 
  <i>suggestion</i>: Remove or merge the PR that fixes it, not a big deal.
* #11576
  <i>suggestion</i>: PR exists but we might want to write a simpler one.
* #11669
* ~~#10632 (note: added to milestone by popular demand)~~
* #11753
* #11775

This would also mean prioritizing features we want in 5.5 and doing a feature freeze of at least 2 weeks.

## Reasons

There's of course the generic "features & fixes" but I think in particular these make an early 5.5 release valuable:
* long-standing bugs solved: Working fullscreen, better copy-paste (Linux/Windows), IME support (Linux)
* For the first time in years a working macOS build can be built without patching/hacks/whatever people were doing before
* (indirect) Releasing with IrrlichtMt prepares downstreams for having to use it so that will all be figured out by the time 5.6 comes out

## Compatibility considerations

So far no previously supported configurations have been dropped.
Android can continue to use GLES1, the OpenGL driver continues to support as low as 1.4.

**Comment by sfan5** [comment]
ping @minetest/engine

**Comment by Wuzzy2** [comment]
Please add #11110, it's a bugfix to one of the core features (the "uses" of tools before they break, this number is way off) and is already marked for the 5.5.0 milestone. The bugfix is fairly complicated but I have tested it deeply already; the longer this PR is lying around, the harder it will be to merge.

I COULD continue and plug all my other 16 PRs for attention <https://github.com/minetest/minetest/pulls/Wuzzy2>, but won't do it. ;)

**Comment by AFCMS** [comment]
I would like to have:
* https://github.com/minetest/minetest/pull/10265 
* https://github.com/minetest/minetest/pull/11545
* https://github.com/minetest/minetest/pull/10731 maybe, but not 100% needed

These prs are actually finished and will speedup some important parts of mcl2 development

**Comment by SmallJoker** [comment]
For the record: Shadowmapping will likely be disabled in C++ for this release to temporary resolve its rendering issues and the wanted server-side controls.

**Comment by Andrey2470T** [comment]
Maybe better to postpone the 5.5 release and to wait for when the renderer is rewritten? I would not like to see (and I think many other) the raw shadows feature with impossibility _even_ to test it. Otherwise then it would be better to hide it in the release features list and not mention about it in order not to confuse users.

**Comment by appgurueu** [comment]
I'd like to see several of my bugfix PRs merged:

One approval:
* https://github.com/minetest/minetest/pull/10796
* https://github.com/minetest/minetest/pull/10795

Ready for review:
* https://github.com/minetest/minetest/pull/11578
* https://github.com/minetest/minetest/pull/11427

**Comment by erlehmann** [comment]
> Maybe better to postpone the 5.5 release and to wait for when the renderer is rewritten?

No please not.

> I would not like to see (and I think many other) the raw shadows feature with impossibility even to test it.

You can test it today! It lags the game horribly and breaks enough stuff that I think it was merged carelessly.

**Comment by v-rob** [comment]
I agree that we shouldn't wait for the renderer and do a release; it doesn't look like hecks will be done with it for some time yet.  I agree that shadowmapping should be disabled in the C++ for release builds: with the amount of controversy surrounding it, it's best to keep it out of a major release for now.

I don't have any particular feature requests or bugfixes that I want to push for, but bugfixes in general are good, of course.

**Comment by sfan5** [comment]
Here's my 5.5 wishlist btw (minus recent PRs that I expect to get merged anyway):
* https://github.com/minetest/minetest/pull/11615
* https://github.com/minetest/minetest/pull/11498
* https://github.com/minetest/minetest/pull/11495
* https://github.com/minetest/minetest/pull/11465
* https://github.com/minetest/minetest/pull/11438
* https://github.com/minetest/minetest/pull/11110
* https://github.com/minetest/minetest/pull/10810
* https://github.com/minetest/minetest/pull/10795
* https://github.com/minetest/minetest/pull/10729

**Comment by NathanSalapat** [comment]
> You can test it today! It lags the game horribly and breaks enough stuff that I think it was merged carelessly.

Does it still lag if you turn the shadows off? It could just be your computer isn't powerful enough to do those.. You shouldn't expect new features to never require more processing power/ram. I personally have yet to see anything breaking due to the shadows.

Performance without the shadows should be expected to be the same as builds before the shadow mapping was introduced of course.

**Comment by Wuzzy2** [comment]
Please add this small typo fixing PR, merge it preferably BEFORE the string freeze:

#11623

**Comment by erlehmann** [comment]
> Does it still lag if you turn the shadows off?

No.

> It could just be your computer isn't powerful enough to do those..

Even on a reasonably powerful modern computer (Thinkpad X390) turning on shadows can make the game unplayable.

> I personally have yet to see anything breaking due to the shadows.

I think shadows break at least 3D mode and rendering of drawers mod when turned on.

**Comment by hecktest** [comment]
Don't wait for me, I'm a little busy with my actual job and probably won't resume the renderer work until winter.

If you re-add TGA, please keep it deprecated. It's a lousy format for network transmission and we have APIs for procedural image generation now.

I'm in favor of disabling shadows not just because of the lack of API consideration (the PR was just unfinished), but also due to the poor quality and performance. The feature might need a complete redesign; what Liso implemented was grossly overkill, slow and low quality. Dude was just following a tutorial mixed with bad advice from some alleged "gamedev" friend, almost anyone could have done that. His PCF is not actually PCF but absurdly wasteful monte carlo integration with dozens of samples in a fragment. The normal bias was causing gaps which were "fixed" by disabling greedy meshing on the map - but there are still gaps visible in the Sam model, because normal bias is in fact garbage and maybe sort of "works" on 30k vert military soldier models in a console shooter, not here. (personally I found it useless even in a 'modern' project on another occasion, and went with linear bias)

We probably do not need _colored, transparent shadows_ in a block game when not even big commercial engines bother to provide such a thing out of the box, last time I checked. We have a drawcall bottleneck that should probably have been dealt with before piling up more drawcalls on top of it. The shadow is not even cascaded allegedly because of the drawcall cost - that should have been the signal to abort the feature instead of downgrading it just to make it work. Not cascading a directional shadow reduces its close-up resolution by about 4x-8x and so you need to use ultra settings to make it look even remotely passable.

If it were up to me I'd scrap the whole thing and go with simple 2x2 PCF, linear depth bias, transparency only by dithering or not at all, and no color. It's reasonable to not support alpha blended shadows, that's the kind of a luxury feature that's not worth the VRAM it costs. But first, we must reduce the drawcalls so that we can actually have enough spare CPU time to do cascaded shadows. From what I've seen, the lowest hanging fruit at the moment is occlusion culling - you could probably free up enough draws for cascaded shadows just by tightening that up. And above all, actually filter the scene graph properly for shadows and have per-material flags for it - I remember the early video demos showing a _flame_ casting a shadow, and that is just embarrassing.

Note that this still wouldn't fix the jarring mismatch between shadows and existing voxel light, and the fact that it puts a visual effect above consistent simulation, something I thought was unacceptable and contrary to what voxel games are about. Remember when `get_node_light()` wasn't lying? With shadows, it no longer corresponds to what clients actually see. Oops. Therefore, shadows are only viable in games where light simulation isn't actually that important, like shooters. This is why they must be server controllable.

**Comment by sfan5** [comment]
> If you re-add TGA, please keep it deprecated. It's a lousy format for network transmission and we have APIs for procedural image generation now.

Good idea and I agree. We will probably be able to remove it in two or more versions after deprecating it.
Thanks for chiming in btw.

**Comment by appgurueu** [comment]
> > If you re-add TGA, please keep it deprecated. It's a lousy format for network transmission and we have APIs for procedural image generation now.
> 
> Good idea and I agree. We will probably be able to remove it in two or more versions after deprecating it.
> Thanks for chiming in btw.

You will be able to remove it in 6.0.

**Comment by erlehmann** [comment]
> If you re-add TGA, please keep it deprecated. It's a lousy format for network transmission and we have APIs for procedural image generation now.

TGA is a *really* easy format to write pixel data and reading it back in without having to rely on engine features. I believe that is why it was chosen – judging from the MineClone2 commit messages, PNG was tried out as well at that time, but ultimately not chosen. Why, I can not say – but I can assure you that as long as something *works*, MineClone* developers largely do not care for theoretical purity (even if they publicly claim otherwise).

Please just keep TGA in, the code for the decoder is minimal, feature-complete, battle-tested in the real world, and the format does not change. Removing TGA support will create useless busywork to make sure that MineClone* maps do not break on upgrade.

You could of course introduce some seamless way to upgrade existing maps – but that would, of course, necessitate the ability to read TGA textures to be able to convert them to some other format (probably PNG), which would mean you would have to keep the code in at least on the server side.

**Comment by v-rob** [comment]
Why _shouldn't_ people rely on engine features?  The engine features should be best, most standard, and most reliable, and engine features are being added.  If it's not too hard for Minetest to have a TGA reader, it's not too hard for MineClone to have a TGA reader for compatability.  TGA should be deprecated.

**Comment by erlehmann** [comment]
> Why shouldn't people rely on engine features?

As the TGA removal showed, engine features are sometimes randomly remove. :stuck_out_tongue_winking_eye: 

More seriously: Game & mod devs do not target the latest and greatest APIs. Debian sid still contains Minetest 5.3.0!
Whoever believes that devs are mostly targeting the latest and greatest is *seriously* out of touch.

> The engine features should be best, most standard, and most reliable, and engine features are being added. If it's not too hard for Minetest to have a TGA reader, it's not too hard for MineClone to have a TGA reader for compatability. TGA should be deprecated.

The workload of “keeping a small file format decoder that never needs to meaningfully change” is almost negligible. I can even volunteer for maintenance of that code if you want to avoid all that work, i.e. fixing bugs in it once they crop up.

In comparison, the workload of “updating both MineClone2 and MineClone5 so existing user's worlds do not break” is not only substantial, but will most likely not be done by the people who are so hell-bent on breaking existing worlds in the first place.

I think you can deprecate stuff all you want, but if the MineClone2 and MineClone5 developers do not upgrade their games in some way that keeps existing map art working in time for whatever deprecation is happening, then whoever removes TGA for good *while it is still in use* will be *that* person who ruins some kids' Minetest worlds for no other reason than wating to get rid of legacy code.

**Comment by hecktest** [comment]
Wow, I had no idea I'm such a villain. So evil in fact that I dropped everything and implemented a PNG encoder the moment I heard that removing TGA might break a game, despite that game being the most uninspired thing one could possibly make in MT, and despite the fact that it relied on an undocumented feature and we have every right to not care.

**TGA is a very inefficient format.** Most MT servers are plagued by long media downloads, and most admins and even modders are not capable of identifying and remedying this issue. (If Mineclone devs were even one bit aware of this, they would've used PNG from the start. Do they even use RLE?)
I've heard that a server can produce a lot of these map images, that sounds like a recipe for disaster.

In another thread you implied that my "low quality" PNG implementation is also inefficient. (Because it lacks predictors? Those only matter with gradients. )
The deflate algorithm performs a better version of RLE in its sliding window stage, and combines that with Huffman coding. It's impossible for TGA to outperform PNG when both are compressed, even without predictors. You are clearly not arguing in good faith here and you're just plain wrong about most things.

So you got a procedural image API made just for you and you don't like it, and now you're getting slow deprecation for your awful format, and you still don't like it. If nothing we do is good enough for Mineclone people, then maybe we should just bump the version to 6.0 immediately and let them fend for themselves.

**Comment by erlehmann** [comment]
@hecktest breaking stuff *other people actually use* and then demanding that other devs change to whatever new stuff you came up with *immediately* and that all the users endure the ensuing breakage because the previous solution was *stupid* is something that I think can *at best* be described as careless or stupid … and we both know you are not stupid.

That you bring up the PNG encoder or that it is not *literally illegal* to remove features that worked for years in a minor release wtihout there being a discussion or deprecation shows that you still do not care about breakage. Other developers obviously do, which is why TGA has been re-added for the time, and will hopefully only ever be removed when it does not break stuff anymore.

From what I have experienced you behave like a “rockstar coder”, who follows “move fast and break things” and implicitly expects other people to fix whatever you broke. While it may feel like you personally get things done faster that way, usually projects that follow that idea either take way longer to achieve good quality or break all the time – hiding behind “all software has bugs”. I have  seen it lead to persistent interpersonal conflict (i.e. drama) and making people so uncomfortable they either (usually silently) quit projects (which might be as simple as no longer reporting bugs) or start harassing whoever they see responsible for breakage.

There is a solution: Create your awesome APIs first and pull the plug on the old stuff when it is literally not bothering anyone.

**Comment by erlehmann** [comment]
> TGA is a very inefficient format.

Yes, but a) in use b) stupidly easy to write without getting it wrong c) not so inefficient that it was even a noticeable source of lag.

It is easy to sucessfully convince yourself something is strictly better if you insist on ignoring how and why it is used right now.

**Comment by erlehmann** [comment]
> In another thread you implied that my "low quality" PNG implementation is also inefficient. (Because it lacks predictors? Those only matter with gradients. )

Are you referring to https://github.com/minetest/minetest/issues/11613#issuecomment-919644496 maybe?

If you did, note that there I wrote “low-effort” and not “low quality”. So, are you referring to another thread?

The PNG implementation in https://github.com/minetest/minetest/issues/11613 is indeed quite inefficient.
If you do not believe it: Open up the generated checkerboard texture in GIMP, save it & compare filesizes.

**Comment by erlehmann** [comment]
> It's impossible for TGA to outperform PNG

Attached to this post is a file containing a 16×16 pixel graphic of a smiley I just drew.

* The TGA file has 98 bytes (as saved by GIMP)
* The PNG file has 99 bytes (saved wtih GIMP, then used pngcrush)

I wonder, what if there was some kind of game in which many textures were so small?

(Maybe you can make that PNG file smaller somehow? If so, please tell me about it.)
[smiley.zip](https://github.com/minetest/minetest/files/7181904/smiley.zip)

**Comment by sfan5** [comment]
This issue for prioritizing PRs for 5.5, not arguing about TGA.
If you want to do that do it elsewhere or better: just stop, claiming an uncompressed file format is superior to a compressed one is ludicrous.

**Comment by Wuzzy2** [comment]
Division by zero bug:
#11627

**Comment by kneekoo** [comment]
> > It's impossible for TGA to outperform PNG
> 
> Attached to this post is a file containing a 16×16 pixel graphic of a smiley I just drew.
> 
> * The TGA file has 98 bytes (as saved by GIMP)
> * The PNG file has 99 bytes (saved wtih GIMP, then used pngcrush)

A valid size comparison would be getting a server-side TGA file and save that as PNG. If the TGA is uncompressed, it just can't compete with PNG.

> > If you re-add TGA, please keep it deprecated. It's a lousy format for network transmission and we have APIs for procedural image generation now.
> 
> Good idea and I agree. We will probably be able to remove it in two or more versions after deprecating it.
> Thanks for chiming in btw.

Please keep in mind that some distros are still behind, with the most recent [Debian (Bullseye) release having Minetest 5.3.0](https://packages.debian.org/bullseye/minetest) in their repository. The good thing is [5.4.1 made it to sid](https://packages.debian.org/sid/minetest), but it will take a while to be backported and who knows how long it will take them to upgrade to 5.5 when the time comes - if ever, considering 5.4 never made it into Debian Buster. The situation is [identical for Ubuntu](https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=minetest), but at least there a PPA for it and its derived distros. So while we should definitely see Minetest move forward, anything that doesn't hurt to be kept for longer in the engine, even deprecated, would actually help.

**Comment by sfan5** [comment]
Updated the issue list in the first post, should have all blockers now.
My personal wishlist is about done. Unless another coredev has specific PRs in mind I don't think any more big features are going into 5.5. Personally I'd like to get it done in December and we still have existing issues to work through.

**Comment by ShadowNinja** [comment]
This isn't a big feature, but I'd like to get at least the "print server list error message" part of #11342 in so that users can see why server announcement isn't working, especially if we make changes to how the server list validates announces.

**Comment by erlehmann** [comment]
I think that https://github.com/minetest/minetest/issues/11989 must be fixed before the release of Minetest 5.5.

**Comment by erlehmann** [comment]
I think that https://github.com/minetest/minetest/pull/11866 should be in 5.5. as lua mapgens and structure placement by mods in general in the outermost mapblock are buggy right now (since `minetest.find_nodes_in_area()` has been changed to not be able to find all nodes in the outermost mapblock actually).

Note that it is impossible to fix corrupted maps at a later point. Additionally, merging it would prevent a few crashes at the map border that are really easy to trigger right now.
