### ISSUE TITLE
Remove (or preserve) non-TTF font support

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#11611]
XML code in IrrlichtMt was removed in minetest/irrlicht@729c214c003efb738c08f27817d569feb318dbf5, breaking this feature since we have PNG+XML [fonts](https://github.com/minetest/minetest/tree/master/fonts).
It would be possible to preserve this by switching XML out for a simpler text format that is read from Irrlicht. (stub code is still [here](https://github.com/minetest/irrlicht/blob/master/source/Irrlicht/CGUIFont.cpp#L65))

This is a reminder to either remove the remaining non-TTF code or do something to readd support *before* 5.5.0.

Removing non-TTF support has come up a bunch of times (see below) with the primary reasons being that almost nobody uses it, colored text does not work, bold/italic does not work and it only provides a limited character set.
* https://irc.minetest.net/minetest-dev/2017-02-14#i_4811037
* https://github.com/minetest/minetest/issues/9386#issuecomment-584288046
* https://irc.minetest.net/minetest-dev/2020-08-17#i_5722963

**Comment by appgurueu** [comment]
If non-TTF font support is preserved, please use a simple format like JSON instead of introducing yet another obscure MT-only format. Example:

```
{"texture": {"filename": "mono_dejavu_sans_280.png", "hasAlpha": true}, "characters":{"$": {"r":[67, 0, 84, 43], "u": 3, "o": 2}}
```

**Comment by sfan5** [comment]
IrrlichtMt needs to be able to read it on its own but it doesn't link to jsoncpp.
I was considering a simple space-separated format and it's not like anyone will touch for the next 5 years...

**Comment by rubenwardy** [comment]
I think that freetype should be required, and I'm skeptical about creating yet another custom format

**Comment by erlehmann** [comment]
While you can still have pixel fonts with TTF, it is quite difficult to make sure they are crisp, i.e. displayed without artifacts.

I use GNU Unifont almost everywhere. Whenever I switch resolutions (i.e. get a new display), i have to figure out which combination of resolution and fontsize prevent antialiasing. i have not yet found a way to automate that – disabling antialiasing at the wrong combination of resolution & fontsize will just result in an ugly mess.

**Comment by erlehmann** [comment]
I am also skeptical of new font formats. I think most usable simple file format for pixel fonts is the Unifont .hex file format, but it only allows for 16×8 or 16×16 characters: https://en.wikipedia.org/wiki/GNU_Unifont#.hex_format

**Comment by erlehmann** [comment]
In general, since non-TTF pixel fonts were working perfectly before on some configurations (e.g. mine) and seemed to have noticeable speed benefits (spamming the chat no longer reduces FPS so much that spammers can lag other players just by pasting a wall of text) and provide crisp text that is easy to create, I would advocate the following steps:

1. Restore the pixel font support – unconditionally.
2. Make a decision on a possible replacement format.
3. If a replacement format is decided, implement it.
4. Once a replacement format is implemented:
   4. a) Deprecate the old format and output warnings in the next major release that support for it will be removed in the release after that.
   4. b) Implement a migration tool from the old to the new format.
   4. c) Migrate all the fonts in the repository.
   4. d) Migrate user fonts if an old font is found at loading time.

Right now, users who do use Minetest without Freetype (most likely to use one of the several previously supported Pixel fonts delivered with Minetest in the fonts directory) will not be able to start Minetest at all unless they figure out on their own that a) pixel font format support was removed even though pixel fonts are still delivered b) Freetype has to be activated. One could *at least* expect a proper error message in that case.

In general, I think it is a bad idea to remove working features from Minetest without collecting user feedback, providing deprecation notices for at least one major release, and some kind of upgrade plan.

**Comment by erlehmann** [comment]
For me, some very important questions about any possible solutions here are:

1. Does the approach break previous user setups without providing a remedy?
2. Does the approach make it harder for artists and developers to create or modify pixel fonts?

I would be surprised if a majority of the people advocating supporting only the TTF font format have ever created or modified a TTF file.

I would also be surprised if anyone had issues creating or modifying pixel fonts that are delivered with Minetest right now and were supported from 2014 until very recently.

**Comment by sfan5** [comment]
> I am also skeptical of new font formats. I think most usable simple file format for pixel fonts is the Unifont .hex file format, but it only allows for 16×8 or 16×16 characters: https://en.wikipedia.org/wiki/GNU_Unifont#.hex_format

We're not looking for a new format for the glyph data. What needs a new format are [these](https://github.com/minetest/minetest/blob/master/fonts/mono_dejavu_sans_10.xml) XML files which specify the position of each character in the PNG and some kind of offsets.

> pixel fonts that [...] were supported from at least 2014 dceb9f7 until very recently.

Not really. They were broken from roughly 2016 until 233cb86e864affe3dee8f60503584f1eb7e36287 (2019) and they *are* broken in the current release when MT is installed system-wide (only fixed recently: e15cae9fa0f99f597f349a7ba07d149cd91cc2d8).
Given this you cannot seriously tell me that anyone has been using these.

**Comment by erlehmann** [comment]
> We're not looking for a new format for the glyph data. What needs a new format are these XML files which specify the position of each character in the PNG and some kind of offsets.

Then I would advocate TSV if you want easy parsing. (Not CSV, there are too many dialects of that to be useful.)

> Not really. They were broken from roughly 2016 until 233cb86 (2019) and they are broken in the current release when MT is installed system-wide (only fixed recently: e15cae9).
> Given this you cannot seriously tell me that anyone has been using these.

I see, I did not know that. I never use the system wide installed version of Minetest.

**Comment by v-rob** [comment]
Non-TTF fonts have been constantly broken on and off.  There's really no reason to expect them to magically be fully supported by everyone suddenly in the future.  No one has ever seriously complained about not having TTF fonts to my knowledge.  They also make it more difficult for implementing features -- non-TTF fonts can't have their font size changed, italicized, or bolded, and they don't support fallback fonts in Minetest.  

As for the other concerns, Minetest doesn't cater directly to font creators, so ease of creation isn't really a big problem.  Secondly, TTF fonts are also crisp if you use the correct font at the correct font size.

So, non-TTF fonts might be somewhat faster on old computers, but they are a big pain for everything else.  I would oppose re-adding them.

**Comment by erlehmann** [comment]
> No one has ever seriously complained about not having TTF fonts to my knowledge.

Why is it that if someone complains about something, there are often people pointing out that no one complained before? It adds very little to the discussion in my opinion. Is it meant to be dismissive towards the complaint?

> non-TTF fonts can't have their font size changed, italicized, or bolded, and they don't support fallback fonts in Minetest.

Can you elaborate on not supporting fallback fonts?

> TTF fonts are also crisp if you use the correct font at the correct font size.

Do you know a way to figure out optimal font size for a resolution automatically? I always just try it out.

**Comment by v-rob** [comment]
> Why is it that if someone complains about something, there are often people pointing out that no one complained before? It adds very little to the discussion in my opinion. Is it meant to be dismissive towards the complaint?

No, it _does_ add something to the discussion.  You've started complaining about the removal of features based on evidence that other people need them.  But no one _has_ needed bitmap fonts, unlike TGA.  They couldn't have because they've been broken for _years at a time_.  I'm not being dismissive; I'm being practical.  If no one has complained about a feature that has been entirely broken for years, it would seem to point to the fact that no one needs it.  I don't want to support features in Minetest that are mainly cruft.

> Can you elaborate on not supporting fallback fonts?

Honestly, as it stands, fallback fonts probably (although I can't guarantee) are possible for bitmap fonts if we absorb the code into our codebase, but the real difficulty is that I fear that bitmap fonts will stand in the way of proper text layout and Unicode support.  They don't have the same information encoded in them as TTF fonts.  Again, I can't guarantee that this will be a problem, but I'm raising the concern now.

> Do you know a way to figure out optimal font size for a resolution automatically? I always just try it out.

Well, I would assume you set the font size to the height in pixels of the font, although I haven't tried it out myself.  So, for an 8x16 font, try setting the size to 16.  If that doesn't work, guess and check would work.  It's all on the user's side anyway, so they can change the size as much as they like until it works perfectly.  However, I don't think this can be done programmatically.

**Comment by erlehmann** [comment]
@hecktest complained about a pixel font (GNU Unifont) scaling badly as a TTF:
https://github.com/minetest/minetest/issues/11455#issuecomment-885303785

I now suspect the *only* way to get crisp pixel fonts is restoring non-TTF support.
If you do that, I will work on integrating GNU Unifont as a pixel font into Minetest.

**Comment by v-rob** [comment]
I have yet to be convinced that non-TTF is actually useful enough to justify the extra technical debt to maintain it, and I have yet to see anyone else besides you that really wants them back.  One person does not justify a large engine feature, especially when there are a lot of reasons against it.

However, saying that crisp pixel fonts cannot be done without non-TTF is not true.  I did mention in the Unifont issue (https://github.com/minetest/minetest/issues/11455#issuecomment-885188343) that a font rasterizer that does not apply smoothing is quite possible, and absolutely any TTF font could then be used.  If there is enough support for crisp pixel fonts, it would be reasonable to code this and would be way, way simpler than taking on non-TTF code again.

**Comment by erlehmann** [comment]
@v-rob the difference is that the pixel font code actually exists, the hypothetical crisp rasterizer you just came up with does not.

**Comment by v-rob** [comment]
The other difference is that non-TTF code is much, much larger and harder to maintain -- we're talking thousands of lines of code.  My pixel rasterizer, on the other hand, would amount to disabling alpha blending when drawing the glyphs, which would only require tweaking some things in IrrlichtMt, probably amounting to less than one hundred lines of code total.  Compare a few thousand lines of code to less than a hundred _plus_ the fact that my rasterizer would support different sizes, colors, styles, Unicode fallback, etc. without any extra effort since it's literally TTF.  Non-TTF is ridiculous in comparison.

**Comment by erlehmann** [comment]
@v-rob now that sounds cool!

**Comment by sfan5** [comment]
BMFont seems like it has too many features. We wouldn't want to claim to support a format and then only implement a tiny fraction.

**Comment by jingkaimori** [comment]
It's impossible to use png+xml font in recent pre-build minetest releases.
Fonts introduced by png+xml is [dejavu font](http://dejavu.sourceforge.net/samples/DejaVuSansMono.pdf), which isn't pixelfont at all
Pixel font can be introduced by ttf font format, and these font seems work well. Here is my test result, using [kenney's pixel font](https://www.kenney.nl/assets/kenney-fonts) as monospace font and set font size to 48, tested game and mod is devtest and mesecon-luacontroller
![screenshot_20211108_182005](https://user-images.githubusercontent.com/36156959/140725193-0b9a0fd9-6c3e-4aaa-8f90-afc4431ceb82.png)
So this section of code can be removed safely

**Comment by erlehmann** [comment]
>  It's impossible to use png+xml font in recent pre-build minetest releases.

That is probably only because @sfan5 removed the XML support in irrlichtmt, which broke that.

I think it would be simple to add it back in, just do a `git revert` on the offending commit(s).

I have said it on IRC and I want to say it again: I think intentionally breaking a feature and then requiring discussion to fix it (and not just reverting the breakage) in is bad form in any case. Even if I agree with the outcome, it creates the impression that it never worked anyway.

> Pixel font can be introduced by ttf font format, and these font seems work well.

Unfortunately, if a pixel font loaded as TTF is rendered blurry at a specific size depends on your DPI.

I.e. there is exactly one font size (in pt) per monitor configuration at which Minetest will render pixel font TTFs not blurry and you get to that size usually by trial and error until it looks right. That is a regression, I think?

According to @sfan5, at exactly 96dpi Minetest will render 16pt Unifont as 16px Unifont, i.e. not blurry.

The linked picture shows Minetest rendering Unifont 16pt at 120dpi on the left and at 90dpi on the right.

https://mister-muffin.de/p/Y6F8.png

**Comment by v-rob** [comment]
> That is probably only because @sfan5 removed the XML support in irrlichtmt, which broke that.
>
> I think it would be simple to add it back in, just do a git revert on the offending commit(s).

Ugh, no.  It's been said many times before, TTF support has been broken for years on and off over the span of many releases.  It's not a simple XML vs. no XML issue.

**Comment by erlehmann** [comment]
> TTF support has been broken for years on and off over the span of many releases

What was broken there? TTF support worked fine for me at all times (not counting the blurriness).

**Comment by erlehmann** [comment]
> It's not a simple XML vs. no XML issue. Maintenance is a real issue.

I can offer to help maintain the pixel font subsystem. Would that change anything?

**Comment by Wuzzy2** [comment]
I vote for removal. If it makes maintaining the codebase easier, go for it. I don’t really mind.

**Comment by Wuzzy2** [comment]
I have been informed that "pixel" fonts have been supported since 2014. Whoops. OK, so removal is probably a bad idea then …

And I see there’s already a bugfix in the pipeline, so …

Just forget my previous comment. :P

**Comment by sfan5** [comment]
> I have been informed that "pixel" fonts have been supported since 2014. Whoops. OK, so removal is probably a bad idea then

Not really, see https://github.com/minetest/minetest/issues/11611#issuecomment-917981090.
With all the features it is missing I am very sure **nobody** has ever used for the only thing that TTF currently can't do (which are sharp pixel fonts). It is also not available to games or mods so not covered by the compatibility guarantee.
