### ISSUE TITLE
Perhaps rename Minetest to something more aligned with the purpose and goals?

### ISSUE THREAD

**Issue by TuringZauber** [minetest/minetest#11657]
_<sub>This was previously a microblogarticle, hence the writing style</sub>_

One of the first things I always think about #minetest is: why the name? What does it test?
It sounds like "yeah we're not ready yet don't use this".

For example #Hagrid is a great software. You know it's development name? Garbage Pile. Yeah! You want to rename that before launch. And I think Minetest also needs to have a name which resembles it's spirit.
Freemine.
OpenCraft.
TheSandbox.

FLOSS projects can eclipse the original. For example #R eclipsed #S for professional data ppl

**Comment by appgurueu** [comment]
A rename is a heckton of work which doesn't appear quite worthwhile solely for advertisement purposes at the moment.

**Comment by ExeVirus** [comment]
Haha, yep it's been considered, nope, not likely to change.

It's actually okay... It doesn't hold us back and it forces our games to be better named. 

And don't worry, I personally am working on getting minetest into retail boxed versions with a guide and poster and whatnot, so we'll have more exposure to the general public (in the US) soon enough.

It's already grown a ton, and keeps attracting new people all the time. Feel free to contribute mods or engine code more yourself :)

But as for rename: it's just hard to at the point, and unlikely to happen without Celeron55 using all his remaining power to try to rename, and even that is unlikely to happen. Especially because all the existing game and mod code use "minetest.function" syntax....

**Comment by Emojigit** [comment]
Actually the minetest.function syntax can be fixed by "minetest = freemine" etc

But I disagree renaming because this name is good.

**Comment by TuringZauber** [comment]
okay

**Comment by SmallJoker** [comment]
Duplicate of #5670.
See also: https://forum.minetest.net/viewtopic.php?f=5&t=17133

**Comment by TuringZauber** [comment]
> I personally am working on getting minetest into retail boxed versions with a guide and poster and whatnot, so we'll have more exposure to the general public (in the US) soon enough.

With _Minetest_ as the name? There are several forks[[1]](https://wiki.minetest.net/Overview_of_Minetest_forks) of Minetest. Some of them have genius name (e. g. Voxelands). Perhaps we should get _that_ into retail?
I think it would also be pretty important to get Minetest on Steam and other digital distribution platforms.

**Comment by ExeVirus** [comment]
Hey the name sucks, but that's not really going to stop it from selling.

Minecraft was also a bad name haha.

As for steam, harder to respect open source there, and I think you have to
pay to list, and no one should pay for an open source game from an online
store.

The retail box makes sense because you get a physical flash drive, physical
guide, stickers, poster, and box. Very different proposition than
essentially scamming people to pay for it

**Comment by TuringZauber** [comment]
> As for steam, harder to respect open source there, and I think you have to
pay to list, and no one should pay for an open source game from an online
store.

There _are_ already open source games on steam, e. g. https://github.com/tobspr/shapez.io

> The retail box makes sense because you get a physical flash drive, physical
guide, stickers, poster, and box. Very different proposition than
essentially scamming people to pay for it

For many people in WEIRD countries digital download is the primary way of video game acquisition.
Think about it: in the last few months how many physical retail products have your friends and you bought and how many digital ones? For many people, digital distribution is the single most important way of downloading a game.

The argument about scams also does not hold up. First of all, nobody said anything about the game pricing on steam (you implied it wouldn't be gratis). Second of all, in what way would a physical box protect against scams or bootleg variants? It makes no sense to assume a retail box being somehow more scam-resistant than a digital download (where a vendor the user already trusts vouches for the ability to refund the games).

**Comment by TuringZauber** [comment]
The issue is not resolved. Please unlock/open https://github.com/minetest/minetest/issues/5670 or re-open this issue

**Comment by ExeVirus** [comment]
We don't disagree, but sometimes projects have too much history to bother
rebranding.

Especially open source ones.

I will likely brand the retail one as minetest, but with other actual
minetest  games as the headliners. There's bigger fish to fry, and a name
hasn't stopped us yet.

**Comment by PhaedraStorm** [comment]
An old survey [[direct link]]() concluded that 76,6 % of the player base would be _**in favour**_ or renaming MineTest. Perhaps the survey should be thought over again?

![image](https://user-images.githubusercontent.com/6533815/144137925-b34d6409-f605-42a7-b113-3141ba7aaf75.png)
(this image shows only a extract, please use the direct link above for more details).

**Comment by PhaedraStorm** [comment]
> There's bigger fish to fry, and a name hasn't stopped us yet.

Yeah but _this_ is an fish two pals of me and I are very interested in frying specifically. One of which developed one of the popular gamemodes.

**Comment by benrob0329** [comment]
Look, we've hashed and rehashed the name thing for years now. It's not going to happen, no matter how much anyone goes "look, here, _logic_ and reasoning!" because its a lot of work nobody gets paid to do and there are far more constructive uses of our free time (like actually improving the engine or making games which are what anybody is actually going to care about).

That poll is from 2016, and indeed in 2016 a lot of name bikeshedding was had. Which while yes, over 3/4 of the voters agreed that the name should be changed, the largest homogeneous chunk of them won by a plurality saying that the current name is fine. Not that a portion of the MT community would decide this, open source projects are usually closer to a free-form meritocracy (or what you might call an obligarchy) because those who do are those who do.

Name your games well, advertise those, not MT itself. Nobody cares that UE4 is called UE4, only that Sea of Thieves is fun.

**Comment by rubenwardy** [comment]
These conversations always generate a lot of talk without being productive at all, resulting in no changes. It's more productive to work on other things

Also, the only person that can rename Minetest is @celeron55

**Comment by saxnot** [comment]
I'm also in favour of renaming MT

**Comment by tacotexmex** [comment]
I've always toyed with the idea of doing an automated dry-run rename in order to investigate how bad of a workload a rename would actually be. I imagine a Github fork with automatic upstream syncs and a Github Actions that automatically

1. replaces all mentions of _Minetest_ with _Newname_.
2. Adds an alias back to _minetest._ API calls for compatibility.
3. Builds binary artifacts

All this as a proof of concept, ofc.

**Comment by PhaedraStorm** [comment]
@tacotexmex better yet, provide a central place to store the `name`.
That would make it even easier to use Minetest as an engine similar to Unity/Godot/Unreal/... games which are not _Unity_ on the desktop shortcut, the steam store etc. When this is an engine then guess re-packaging it should be as easy as possible e. g. for creating the official YourLand Game Launcher or something

**Comment by Rick-W-Storm** [comment]
Any updates?
I would like this to get done very much.
Please open this issue and assign it to me

**Comment by rubenwardy** [comment]
It's not possible to assign it to you. The only person who can do this is celeron55. And this issue has been rejected anyway

**Comment by Rick-W-Storm** [comment]
On 2021-12-07T16:09, rubenwardy wrote:
> It's not possible to assign it to you. The only person who can do this 
> is celeron55. And this issue has been rejected anyway

Ok.

# Registrations are open for our betted-named fork

Some things to look forward to:

- being paid for your contributions
- we'll put the game in steam store / GOG / HumbeBundle (to be decided yet)
- funding will go to registration foundation for the betterment of our 
open voxel game (perhaps charity gGmbH in germany, not yet decided)
- public elections similar to other open source projects
