### ISSUE TITLE
formspecs aiming to be full screen are cut off

### ISSUE THREAD

**Issue by wsor4035** [minetest/minetest#11669]
affected Minetest version: 5.4+
OS / Hardware: tested on windows

issue: formspecs height is limited from being full screen since 5.4. 5.3 and below work.
test code: can be run in sp with worldedit `//lua local formspec = {"formspec_version[3]","size[6,20]","position[0,0]","anchor[0,0]","label[0.5,0.5;test]",} minetest.show_formspec("singleplayer","test:test", table.concat(formspec))`

5.4
![image](https://user-images.githubusercontent.com/24964441/135734574-d67f2cac-e59f-4d8f-b5cd-ff0b8419990a.png)

5.3
![image](https://user-images.githubusercontent.com/24964441/135734589-c7df21b2-151e-448d-b745-13386131d78f.png)

<https://github.com/minetest/minetest/pull/10144> seems suspect

**Comment by SmallJoker** [comment]
@v-rob ping

**Comment by wsor4035** [comment]
in theory if you remove https://github.com/minetest/minetest/blob/master/src/gui/guiFormSpecMenu.cpp#L3261-L3266 and replace references to it to mydata.screensize.x/y the problem should be resolved

**Comment by v-rob** [comment]
#10144 does, in fact, cause this behaviour of limiting the formspec to the screen size.  However, your second screenshot is not fullscreen, but rather _larger_ than the size of the screen.  It has the same issue as #7603, which is definitely a bug.  So, this is actually not a regression: I don't think allowing formspecs to be cut off is any good.

So, the actual thing of this issue is whether formspecs should be allowed to fill the entire screen or keep the current behaviour of 90% of the screen.  The rationale of me adding that was that having some formspecs be centered boxes and have larger ones touching the borders seems bad user design to me.  So, this issue should debate whether this is actually good behaviour or not.

However, even with the 90% removed, you still can't have fullscreen formspecs.  It would turn out to be one of these:
![image](https://user-images.githubusercontent.com/31123645/135790782-b9d42243-5e35-46b4-ba4b-5c9a64c15ffd.png)
Because we can't have proper aspect ratio managing with the current formspecs.  With a 5% border on each side, you'll never have this oddity, since it'll always be a centered box:
![image](https://user-images.githubusercontent.com/31123645/135790920-bb13dc7d-2e4e-4489-9a3e-70331898df55.png)
So, I'd argue for keeping the current behaviour.

**Comment by wsor4035** [comment]
vrob: yes, the second image does over extend, i could change the units to 15 to resolve that issues, still doesnt disapprove the point.

with the current (regression) behavior you are breaking any main menu concepts such as ones found in https://github.com/minetest/minetest/issues/6733 which use full screen elements. 

"So, the actual thing of this issue is whether formspecs should be allowed to fill the entire screen or keep the current behaviour of 90% of the screen. The rationale of adding that padding was that having some formspecs be centered boxes and have larger ones touching the borders seems bad user design to me. So, this issue should debate whether this is actually good behaviour or not."

In regards to the above quote, the engine should not needlessly limit game and mod creators, especially just because one person *thinks* that ones touching borders are bad design(example of wanting *the ability* to do a full height backgroundto the left side for configuring items in a game shown on the 3/4 showing on the left ). In fact, keeping this would be a step backwards in the attempt to de hard coded features of the engine, it would be better to allow game and mod devs to make these decisions themselves and not be artificially limited by the engine. in specific regards to " some formspecs be centered boxes " if this is your ultimate goal, then should the anchor and position elements even allow moving to the edge of the screen? or bgcolor allowing to color the whole screen?

**Comment by wsor4035** [comment]
oddly enough, the only option for modders and game devs that want a full width and/or height elements is to be stuck on version 5.3 max by a artificial limit imposed by the engine because "touching borders seems bad" in a personal opinion

**Comment by v-rob** [comment]
OK, but what about people who _don't_ want the formspec to touch the screen borders?  If we remove the 90%, they can't have what they want.  Do the border-touchers overrule the non-border-touchers?  We can't have both without adding an option.

But as I said, proper fullscreen formspecs aren't possible even _without_ the 90%.  See the above images -- you can't manage the aspect ratio.  No main menu design or any other GUI that requires fullscreen can work with formspecs, 90% or not.

**Comment by wsor4035** [comment]
"OK, but what about people who don't want the formspec to touch the screen borders? If we remove the 90%, they can't have what they want. Do the border-touchers overrule the non-border-touchers? We can't have both without adding an option."

modders are free to make there formspec whatever size they desire, i fail to see how allowing touching borders(but not exceeding) would hurt this.

**Comment by wsor4035** [comment]
re minetest-dev irc https://irc.minetest.net/minetest-dev/2021-10-05#i_5883873 this issue will be resolved by @v-rob making a pr for padding[x,y]

**Comment by SmallJoker** [comment]
> modders are free to make there formspec whatever size they desire, i fail to see how allowing touching borders(but not exceeding) would hurt this.

On a side note: How would Android players close the formspec if double-tapping outside is not possible? Does the "Back" button work for formspecs?
