### ISSUE TITLE
String too long for serializeString16

### ISSUE THREAD

**Issue by loosewheel** [minetest/minetest#11850]
##### Minetest version

```
5.4.2
```

##### OS / Hardware

Operating system: Linux
CPU: i5 M520

##### Summary

String too long for serializeString16

##### Steps to reproduce

I put 100k into the metadata of an item and dropped to see if this problem was still occurring, and the game crashed.

In the file builtin/game/item_entity.lua, in the set_item function on line 84
`wield_item = self.itemstring,`
is being set with the full item string including all metadata. I didn't think this needed all that so I coded this function to strip all but any pallet_index
```
local function item_to_string_stripped (stack)
	local s = ItemStack (stack)

	local t = s:to_table ()
	local palette_index = (t and t.meta and t.meta.palette_index)

	t.meta = { }
	if palette_index then
		t.meta.palette_index = palette_index
	end

	return ItemStack (t):to_string ()
end
```
and changed the line to
`wield_item = item_to_string_stripped (stack),`
Then I put 1Mb into the metadata of the item and dropped it, and the game did not crash. I only got the warning:
WARNING[ConnectionSend]: con(18/1) Packet quota used up for peer_id=2, was 1024 pkts
It appears the problem is being caused by too much data in the properties of the ObjectRef.

**Comment by SmallJoker** [comment]
Already mentioned once here: https://github.com/minetest/minetest/issues/8977#issuecomment-756870048

> It appears the problem is being caused by too much data in the properties of the ObjectRef.

No. The entity data within `core.luaentities` (i.e. all `self.` variables) are server-side only. What's sent to the client are the object visuals and properties specified by `set_properties` and its initial values.

The problem might occur as soon you attempt to pick up the dropped item. `serializeString16` can only send strings that are shorter than 2¹⁶  characters. Please provide a proper backtrace to see where the issue is coming from. A possible solution might be to throw a proper Lua error for insanely big ItemStacks.

**Comment by sfan5** [comment]
#11511 deals with this problem. In 5.5.0-dev the engine no longer crashes on dropping items with too much metadata.
Regardless limiting the amount of metadata written to items is considered the mods responsibility.

**Comment by erlehmann** [comment]
>  Regardless limiting the amount of metadata written to items is considered the mods responsibility.

Mineclonia has an example of how to get rid of overlong item metadata for dropped items:

https://git.minetest.land/Mineclonia/Mineclonia/pulls/132/files

**Comment by erlehmann** [comment]
> A possible solution might be to throw a proper Lua error for insanely big ItemStacks.

Do not do this! It would break shulker chests – portable chests that have an item form – in Mineclonia.

Shulker chests have a serialized inventory in their meta. We have already fixed the crash (see above).

**Comment by erlehmann** [comment]
Could this be closed or is there still something that can be done?
