### ISSUE TITLE
3rd person view z offests do not invert from back to front views

### ISSUE THREAD

**Issue by MisterE123** [minetest/minetest#11965]
##### Minetest version

```
5.5
```

##### OS / Hardware

Operating system:Windows
CPU:

GPU model:
OpenGL version:

##### Summary

When the player's 3rd person view offset is changed with 
``` player:set_eye_offset(vector.new(0,0,0), vector.new(0,10,-5))```

the -5 z offset does indeed back the view away from the player in rear view 3rd person

I would expect it to back it away from the player in front view 3rd person also, but instead it brings the camera closer to the player model, so that all you can see is the head.

The z offset should be inverted when in front view.

This is a bug when working with larger player models

**Comment by lhofhansl** [comment]
+1 let's fix this. I'll do PR.

**Comment by srifqi** [comment]
The problem is that there is no documentation about whether the third-person offset will be applied in respect to rear-view's direction or front-view's direction.

> * `set_eye_offset([firstperson, thirdperson])`: defines offset vectors for
  camera per player. An argument defaults to `{x=0, y=0, z=0}` if unspecified.
>     * in first person view
>     * in third person view (max. values `{x=-10/10,y=-10,15,z=-5/5}`)

Currently, the offset is calculated using the rear-view's direction:
```
    front   player   rear
      |       |       |
      >  >    P       <  <
         |               |
      +offset         +offset
```

Is it really fine with just negating the offset for front-view:
```
    front   player   rear
      |       |       |
   >  >       P       <  <
   |                     |
-offset               +offset
```

... or should we have a third argument for front-view, i.e. `set_eye_offset([firstperson, thirdperson, thirdpersonfront])`? It can be optional and defaults to negative of the offset. This will allow mods to specify the relative camera position in case of long model or offsetted model like a dragon/snake/bus/train.
