### ISSUE TITLE
Grant `basic_debug` privilege by default

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#12011]
(please add this to 5.5.0 milestone)

I am the one who made the PR that hides part of the debug screen by default (coordinates, yaw, pointed node, entity HP, seed, etc. but not FPS, version, lag, etc.). The rationale was that I wanted to allow games to stop players from getting this info for free. This makes sense for games when players must craft a compass first or whatever. See: #9315

I also added the `basic_debug` privilege which basically gives players those gameplay info back.

After having thought long about it (and many players having complained in the forums), I have come to the conclusion that maybe the change as it stands was not so great after all. My previous argument was that servers should just grant the `basic_debug` priv to get back the old behavior. But then I realized that some servers can be *notoriously* slow to react to such things. I'm afraid that the 5.5.0 release will de facto cause many players lose the ONLY convenient (although hacky) access to coordinates on servers on which it matters.

I'm afraid this can be a major disruption to players and annoy a lot of players. I heard they are already preparing the pitchforks … :D Releasing 5.5.0 with this change as it stands now might be bad.

So I have an idea on how to avoid this disruption in a simple way: Grant the `basic_debug` privilege by default. That way, the games that want to hide the info can now hide it and longstanding server playerbases will NOT be affected.

This change sounds very simple and easy, right? Well, not really. Because privileges granted by default to singleplayer cannot be revoked. But if this privilege cannot be revoked, it is pretty pointless. :D
I don't know if this is a bug but either way, this means that before `basic_debug` can be granted by default, it needs to be possible to revoke default privileges. I don't know if this counts as 'feature'.

Either way, I think this issue must be dealt somehow before 5.5 release. Having hundreds of players lose access to coordinates after an upgrade is too high a price to pay. I previously would just have blamed server operators for that but this is an unrealistic expectation.

If this can not be done in time before release, I sadly see no other option than a full revert of #9315 for now. :-(

**Comment by erlehmann** [comment]
With my player hat on, I agree with @Wuzzy2 here: I know people who hold off upgrading their client for that reason.

With my game & mod developer hat on, I also agree with @Wuzzy2: Knowing coordinates has been an integral part of Minetest for a long time. A game should be able to revoke it, but many games do not contain compasses or maps at all & would therefore leave player stranded.

**Comment by sfan5** [comment]
Isn't this more of an MTG thing? IMO The engine shouldn't do this (yes I know games can work around it).

For MTG I think the following would be an useful default:
* Grant `basic_debug` to all new players
* Include migration code to grant `basic_debug` to all existing players *once*

**Comment by rubenwardy** [comment]
It's way too late to have this discussion in the engine

I support adding a basic_debug mod to MTG to add this priv, it would be simple

**Comment by Wuzzy2** [comment]
MTG has the downside that it's only 1 game. Not all servers are MTG. Many are MCL, too.

Crazy idea: Auto-grant this privilege in `builtin`. Then games can revoke it if needed and old behavior is still preserved. I haven't tested if this actually works, however.

**Comment by Desour** [comment]
I'm still for a situation where subgames (or mods) have to explicitly disable the unwanted debug info (pos, yaw and so on) explicitly via the lua api.
This way the debug info would only be hidden if there are alternatives, like navigation items, or if a (new) subgame wants to not have such info available at all.

Like it's now, basically all mods and subgames that depend on this info, and never had the option (as priv for debug info) or reason (for hud elements) to explicitly allow debug info, will be broken.

**Comment by sfan5** [comment]
<hr>

Ok so after an [IRC discussion](https://irc.minetest.net/minetest-dev/2022-01-29#i_5929421), it was brought to the table that `basic_debug` might be total rubbish and should be reverted for release. The reasons are the following:
* It is a breaking change because games have to take action to preserve the previous behaviour
  * this was considered okay during discussion of [#9315](https://github.com/minetest/minetest/pull/9315), but @Wuzzy2 changed his mind now
  * this is obviously fixable for MTG (as suggested already) but other games are a concern
* It being a privilege instead of an HUD flag is awkward when games/mods need control over it
  * the original argument was that mods have no business touching these, Wuzzy also changed his mind on this

As it stands we want a decision between the following:
1. **Keep the feature** and **grant `basic_debug` for new and existing users in MTG** (assuming this is wanted, looks like it)
2. **Disable/revert the feature so a better implementation can be made eventually**


Potentially relevant: Games might have been written that target 5.5 and expect coordinates *not* to show
<hr>

**Comment by v-rob** [comment]
I don't have a strong opinion on `basic_debug` one way or another.  I think the best solution is probably the one that takes the least work at this point TBH.  It might just be best to revert since that way we aren't locked into an API we don't like later.  For what it's worth, I don't think having coordinates visible has hurt many games very badly, so it's not a _huge_ deal at the moment.

**Comment by rubenwardy** [comment]
I'm fine with a revert, hud flag was my original preferred implementation anyway

**Comment by sfan5** [comment]
In favor of revert (all opinions so far):
* v-rob
* ruben
* HuguesRoss (IRC)
* me

PR created → #12016

**Comment by SmallJoker** [comment]
I also had concerns regarding the slow adoption (or no adaption) of servers for the new privilege. HUD flags (for example) would definitely be a more versatile way for customization.
Hence :+1: for #12016 for now.

**Comment by x2048** [comment]
After having read the thread, count me in for a revert.

**Comment by Sharpik** [comment]
And wouldn't be helpfull to implement /grant_to_all <perm> and /revoke_from_all <perm> commands, which goes through the user database and adds the mentioned permissions to everyone (even for those who are offline)?

That might help in this case too.

**Comment by lhofhansl** [comment]
Neutral here.
I like the fact that in-game info is hidden by default, but either way is cool.

**Comment by sorcerykid** [comment]
I just wanted to chime in that I question why the privilege was called "basic_debug". I'm not sure what the rational is for that name, and why "debug" wasn't chosen instead. Either way, I think this should be managed via HUD flags as has been already suggested, rather than via the privilege system.

**Comment by rubenwardy** [comment]
> I just wanted to chime in that I question why the privilege was called "basic_debug". I'm not sure what the rational is for that name, and why "debug" wasn't chosen instead.

"debug" already existed, and enables wireframe
