### ISSUE TITLE
Improve mod dependency system

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#12034]
## Problem

Currently, Minetest only does dependencies based on mod names. This results in a number of problems.

ContentDB attempts to mitigate these problems by requiring packages to only use a mod name if they have the "right" to use it - either by being the first to use it, or being a replacement/fork.

Problems:

* **Mods need to have the same name** to act as a replacement. Replacement mods may start off as a direct replacement, but will over time diverge from the original mod.
 
  For example, Mods Redo started off as a replacement for Simple Mobs, but by this point they're no longer truly compatible - Mobs Redo contains many API features that Simple Mobs doesn't.

  Another example are the two doors mods by [sorcerykid](https://content.minetest.net/packages/sorcerykid/doors/) and [tenplus1](https://content.minetest.net/packages/TenPlus1/doors/). Both are based on doors, but neither are compatible.

  A directly related problem is that it's not possible for a mod to choose a particular fork of a mod.

  See https://github.com/minetest/minetest/issues/11416

* There's **no way to specifying compatible games**. Instead, mods are used as dependencies. ContentDB has been requiring new games to use a namespace for non-unique mod names.  For example, GameName would need to use `gn_mobs` rather than just `mobs` if their implementation isn't based on Simple Mobs/Mobs Redo.
 
  However, this is suboptimal and there are many older games that have been let through that don't follow this. Repixture, for example, uses the `default` name despite being in no way compatible with MTG's default.

  There's been a number of complaints from game authors about this system.

  See https://github.com/minetest/contentdb/issues/221

## Solutions

Honestly, no idea how to solve all these problems

Perhaps:

* A way for mods to specify `provides`.  Obviously Mobs Redo can't rename at this stage, but if they did then this feature would allow this:
	* The fork would have `name = mobs_redo`, and `provides = mobs`
	* Other mods can depend on either `mobs` for Simple Mobs compatible, or `mobs_redo` for Mobs Redo compatible
	* Problems:
		* What if the parent mod becomes incompatible with the fork?
		* ...
* The ability for mods to specify a list of compatible games. Minetest would grey out/hide any games not compatible
	* How to allow forks of games without running into the first problem

* The ability for mods to depend on Author/Modname combinations
	 * This would prevent forks from existing

**Comment by rubenwardy** [comment]
This whole thing is a mess

Games made in Unity/Godot avoid problem 2 by distributing their own clients. It's not possible for a mod to be installed on the wrong game

As for problem 1, from what I see they simply don't implement dependencies :upside_down_face:

**Comment by rubenwardy** [comment]
Python solves this problem by depending on package names, rather than library names. I have no idea what happens if you have two packages installed that provide the same libraries

**Comment by erlehmann** [comment]
> The ability for mods to specify a list of compatible games. Minetest would grey out/hide any games not compatible

I think this is a dangerous and ultimately counterproductive idea.

IMO it is very important for mods to depend on *mods*, not on *games*, so that additional mods for one game work for drop-in replacements. For example, after adding `mcl_colors` to Mineclonia (which is just a table of colors), `mcl_speedrun` worked in Mineclonia too, even though it was written for MineClone2 (`mcl_speedrun` was not even on contentdb AFAIK).

Allowing mods to depend on games would probably be a repeat of the “everyone depends on minetest_game” story, but worse.

**Comment by rubenwardy** [comment]
I'd rather that mods that only support Minetest Game were marked as such. That would make it much easier to find mods that supported your particular game.

Also, I was assuming in my suggestion that there would be some way for forks to inherit compatibility

**Comment by erlehmann** [comment]
> What if the parent mod becomes incompatible with the fork?

To this I want to add that it can be unclear what you would even consider the parent mod. For example, the mcl* games have different creative and technical directions – but we do collaborate, which mostly means cherry-picking commits, or developers adding similar features to the same mod. But due to differing development philosophies, some feature that was developed for Mineclonia might linger in review for some weeks (or months even, sorry for that), while MineClone5 could already have it.

For example, just [yesterday @kay27 asked me if he can merge the WIP branch for a feature I made (ruined portals)](https://git.minetest.land/Mineclonia/Mineclonia/issues/203#issuecomment-31124).

Now this is not finished, so he ultimately did not take it. But consider what would have happened if I had made a mod that was waiting on review and it was finished, just waiting for review. Obviously I would allow him to use the code in MineClone5, but then it would certainly be published on contentdb before I could do it myself (Mineclonia reviews are done with much more attention to detail, while MineClone5 is basically “if it does not crash, it can be in the game”).

Now in this case: What would you, as steward of contentdb, consider the original mod? Would you go by publication time?

**Comment by erlehmann** [comment]
> I'd rather that mods that only support Minetest Game were marked as such. That would make it much easier to find mods that supported your particular game.

I have a different suggestion to find mods that support a particular game with less effort: Evaluate reverse dependenciesj

Finding mods for a specific game could be “for each mod in a game, find all mods on contentdb that depend on this mod”.

@rubenwardy I think just having a search option on contentdb for reverse dependencies would help this use case a lot.

**Comment by rubenwardy** [comment]
> I have a different suggestion to find mods that support a particular game with less effort: Evaluate reverse dependencies!
> 
> Finding mods for a specific game could be “for each mod in a game, find all mods on contentdb that depend on this mod”.
> 
> I think having a search option on contentdb for reverse dependencies of games would help with finding related mods a lot.

That is computationally expensive, and doesn't help once you have installed the mods

**Comment by Oblomov** [comment]
The `provides` is a very powerful and useful mechanism for replacement. Versioning could help solve the “persistent compatibility” between forks (mod B could declare compatibility with mod A up to version N, but not with version N+1). This of course assumes that versioning information is properly and consistently used and checked in mods.

FWIW, I really like the way these things are managed in Debian's APT system, as it provides an extremely powerful and flexible way to specify dependencies, reverse dependencies, conflicts, replacements, etc. [Documentation can be found here](https://www.debian.org/doc/debian-policy/ch-relationships.html).

The key specifications are:
* `Depends`: a list of packages that the package depends on (hard-requirements)
* `Recommends`: a list of packages that this package benefits from; strongly encouraged for installation, but not requirements
* `Suggests`: a list of packages that this packages benefits from (weaker than `Recommends`);
* `Conflicts`: a list of packages that this package cannot be co-installed with

and in reverse:
* `Enhances`: a list of packages that are improved by this package (this is the reverse of `Recommends`/`Suggests`);
* `Provides`:  a list of packages that should be considered “installed” when this package is installed


Each of the lists can include versioned or unversioned package specifications, with versioning including inequality, as well as alternatives. An example for MT could be:
```
Depends: simple_mobs | mobs_redo (>= 1.50), ether, ingots
```
for a mod that depends on the `ether`, `ingots` and _either_ `simple_mobs` (any version) _or_ `mobs_redo` (versions after 1.50).

Conversely, a mod could claim to be compatible with a specific version of `mobs_redo` with:
```
Provides: mobs_redo (=1.56)
```

**Comment by erlehmann** [comment]
A real case of compatibility problems: MineClone2 and Mineclonia add new functionality mostly by means of separate mods, while in MineClone5 new functionality is added to existing mods – and sometimes mods are even changed in incompatible ways. This is obviously a bad development practice … but how could this be handled short of telling mcl5 devs “please do not do that thing”? It is somewhat mitigated here because it is part of a game, but I think it should be possible to conflict with specific games, maybe?

**Comment by runsy** [comment]
My big idea:

Obviously the best solution is not to have all mods appear, but only those that are compatible with the game since:

AVOIDS CRASHES.

That the game can mark a compatibility mode, preferably in minetets.conf.

1) If unchecked, you see all mods.
2) If checked, only mods that are compatible are shown.
3) The mod creator must set the compatible games. COMPATIBLE_GAMES =
4) By default and without setting otherwise, all mods will be compatible with MTG.
5) Case of forks and mods modifications: Pull the ears of the creators for being stupid and creating problems.

**Comment by Wuzzy2** [comment]
The whole mod naming system becomes a clusterfuck when it comes to games. Because if you copy a mod that was originally standalone into a game, and then *another* game add this mod, you technically have a naming collision.
Now, the “solution” is that both games add a little prefix to the modname but this often involves like rewriting giant dependency trees, or worse, APIs.

I think it is simply unreasonable to demand from game authors to rename all the mods because "importing" mods is common.

IMO the core problem here is that all mod names are considered global. Under this ideology, if one game takes the mod name xyz, it is locked for EVERY other game (maybe even as a standalone mod?). Obviously, this just isn’t pragmatic at all. The elephant in the room is `default` which varies *wildly* between games. There is also the assumption that just because a game includes a mod named `xyz` that means it “provides” it for mods outside of the game. But more often than not, a mod is really meant for in-game use only.

Now, games *could* do just name ALL their mods in a way that they have a prefix. It's possible but very annoying. It blows up the mod names. Also, many games probably are not able to rename their mods without creating MASSIVE compability issues at this point.

I think one solution to this could be to allow mods to depend on a mod which must be in a certain game. Maybe a format for `mod.conf` like `<gamename>/<modname>`, e.g. if you write `repixture/default` in `mod.conf` as dependency, it means the `default` mod from the game with the game ID `repixture`. Oh, this solution requires proper game IDs / “technical names” to work as well.

That having said, I probably should finish the mod renaming orgy for Hades Revisited. I do not plan a renaming orgy for all of the other games I maintain because of backwards-compability.

**Comment by Wuzzy2** [comment]
> Another example are the two doors mods by sorcerykid and tenplus1. Both are based on doors, but neither are compatible.

Okay, this is bad and should be just straight-up forbidden AND enforced. To be clear, I fully support a strict “right to the name” as long we’re talking about standalone mods. Force the person who was later to the party to rename it or else get their mod booted of ContentDB. It’s harsh, but this really seems like the simplest solution; I don’t think building complicated compability layers just because people don’t respect naming rights is reasonable. This really needs to be fought harder because otherwise the problem with double/triple/quadruple/... mod names will just become worse and worse.

I think naming rights are much more defensible on standalone mods, as naming collisions are obvious to see. I’m less stringent for game mods because I think game mods could be treated to be somewhat like in their own little “namespace” (see previous post). Also, in game mods, naming collisions are way more likely and the only sure way to prevent that right now is like forcing games to add a mod prefix which is not going to happen as I previously explained.

**Comment by sfan5** [comment]
> I think one solution to this could be to allow mods to depend on a mod which must be in a certain game. Maybe a format for `mod.conf` like `<gamename>/<modname>`, e.g. if you write `repixture/default` in `mod.conf` as dependency, it means the `default` mod from the game with the game ID `repixture`. Oh, this solution requires proper game IDs / “technical names” to work as well.

This is flawed as well. Consider that someone forks minetest_game and renames it, suddenly all mods would stop working even though there is no technical incompatibility at all.
If you allow games to "pretend" to be a different game ID in an attempt to fix this, then you have all games claiming to be the lowest common denominator.

**Comment by rubenwardy** [comment]
I had to blacklist Repixture in my game support algorithm because it causes so many false positives. I really wish it would just just rename default, there's only [one mod](https://content.minetest.net/packages/Hugues%20Ross/cartographer_repixture/) on CDB that supports it, and you can solve world compatibility with aliases. We're strictly enforcing names in games currently, especially default, so if Repixture was submitted today it wouldn't be allowed on ContentDB.

> Force the person who was later to the party to rename it or else get their ~~mod~~ **game** booted of ContentDB. It’s harsh, but this really seems like the simplest solution

:eyes:

----------

This issue is intended to resolve some of the issues with the global mod name system. I'm struggling to see a way that isn't super brittle or complex though.

Another problem I see with a `repixture/default` system is that mods depending on `default` would still get repixture, you'd need to update all mods to use `minetest_game/default` which will be quite disruptive. Another problem is that you can't use this format without dropping support for previous Minetest versions, as they won't understand a new syntax like this. I think that `default` is a special / extreme case here.

Another alternative I was thinking about would be a  system where mods can say which games they're compatible with, rather than using the dependency system directly. So:

```
supported_games = minetest_game, repixture
conflicting_games = some_mtg_fork
```

games would then do something like:

```
id = some_mtg_fork
support_mods_for = minetest_game
```

> If you allow games to "pretend" to be a different game ID in an attempt to fix this, then you have all games claiming to be the lowest common denominator.

My solution to this would be `conflicting_games`, and tools on ContentDB to let game and mod authors enumerate the games and mods

**Comment by rubenwardy** [comment]
ContentDB has now implemented support for `supported_games` and `unsupported_games` in mod.conf. These are experimental, and are used in the CDB UI. More info: https://forum.minetest.net/viewtopic.php?p=411597#p411597

**Comment by FreeLikeGNU** [comment]
I'd like to have a multiple depends for a cross compatible mod with something like:
`depends = default | mcl_core, mobs | mcl_mobs `
so that the mod would have to have either default or mcl_core and either mobs or mcl mobs

**Comment by rubenwardy** [comment]
closing as #13851 is opened
