### ISSUE TITLE
Have privileges inheriting some others

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#12130]
## Problem

Consider a mod that differentiates what moderators and admins can do, using two different privileges, `boo_mod` and `boo_admin`. You now expect that `boo_admin` inherits `boo_mod` but I can't find anything in the Privileges definition section in the docs that allows me to do that

## Solutions

add an `inherits` field in `minetest.register_privilege`, that automatically assigns all the privileges listed in `inherits` when the registered privilege is granted to a player.  

If you fear people might abuse it, assigning whatever registered privilege inside the server, limit it to privileges registered only by the mod calling the registration (so I can inherit `boo_mod` but I can't inherit `fly`)

**Comment by Desour** [comment]
Being a moderator or admin is a role rather than a priv.

Why do inheriting privs need to be implemented in the engine? A mod that wants to check a priv should only check for the minimal thing that is needed (that is, a priv that inherits from no other priv). More complex systems for managing the privs should be implemented in mods imo.

(Actually I recently planned on making a mod for a simple role system. There would be a role for each priv, and other roles that are defined through a set of rules that they inherit.)

**Comment by wsor4035** [comment]
you can already do this in mods, see register_priv, specifically
```
on_grant = function(name, granter_name),
        -- Called when given to player 'name' by 'granter_name'.
        -- 'granter_name' will be nil if the priv was granted by a mod.
```
