### ISSUE TITLE
Minetest recalculates normals if they don't match the winding order

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#12430]
##### Minetest version

```
5.6.0-dev
```

This is a regression introduced in https://github.com/minetest/minetest/commit/1175f48d05 @x2048 

##### Summary

In previous Minetest versions, face normals set in the B3D would override the winding order of the triangle. Now the winding order of the triangle overrides the face normal if the calculated normal points in another direction. This requires matching winding order & generated normals when generating models.

##### Steps to reproduce

Verify the normals being completely wrong for the attached B3D model [`cube.zip`](https://github.com/minetest/minetest/files/8883790/cube.zip).

`init.lua`:
```lua
minetest.register_entity("testentities:normals", {
	visual = "mesh",
	mesh = "cube.b3d",
	backface_culling = true
})
```

then `/spawnentity testentities:normals`.

![Screenshot](https://user-images.githubusercontent.com/34514239/173186894-43e21121-9bca-4bcb-b1e8-2f7b2a3a07e0.png)

##### Additional context

I don't know whether the winding order or the explicitly set normal should take precedence here. It is possible to trivially fix this by reversing the winding order if the normal points in the opposite direction:

```lua
local function fix_winding_order(indices)
	local poses = {}
	for i = 1, 3 do
		poses[i] = modlib.vector.new(vertices[indices[i]].pos)
	end
	local tri_normal = modlib.vector.triangle_normal(poses)
	if tri_normal:dot(normal) <= 0 then
		modlib.table.reverse(indices)
		modlib.table.reverse(poses)
		tri_normal = modlib.vector.triangle_normal(poses)
		assert(tri_normal:dot(normal) > 0)
	end
	return indices
end
```

Probably low priority.

**Comment by appgurueu** [comment]
"silently" is not quite correct as this gets logged to infostream

**Comment by x2048** [comment]
I will remove the workaround added in 1175f48d05. Many models in various games (MCL2, Juanchi, RePixture) will not receive correct shadows until normals are fixed or nullified. B3D exporters for Blender are known to write wrong normals into the model (vertex normals and not split normals)

**Comment by appgurueu** [comment]
> I will remove the workaround added in [1175f48](https://github.com/minetest/minetest/commit/1175f48d05888fba705363729ecf5ef2c75f0c5d). Many models in various games (MCL2, Juanchi, RePixture) will not receive correct shadows until normals are fixed or nullified. B3D exporters for Blender are known to write wrong normals into the model (vertex normals and not split normals)

I don't think removing the workaround to fix this low-priority issue is a good idea...

**Comment by x2048** [comment]
>I don't think removing the workaround to fix this low-priority issue is a good idea...

I see it as a really good chance to fix issues in the production pipeline for Minetest. Shadows are a good incentive to fix the production tools and for the game authors to review/fix their models. If we keep the workaround now reinforces broken behavior, and removing it later will be way harder.

**Comment by Desour** [comment]
>B3D exporters for Blender are known to write wrong normals into the model (vertex normals and not split normals)

I guess you're referring to [this](https://github.com/GreenXenith/io_scene_b3d/blob/f189786f7281400fbd25c7bb9d56687509138b23/export_b3d.py#L1128-L1138), as mentioned in [irc](https://irc.minetest.net/minetest-dev/2022-06-15#i_5985043).
Using an average of the neighbouring faces' normals would normally not result in completely broken normals. (And if you don't want the edge to be seen later, taking the average actually favourable.)
The problem is rather that the b3d exporter uses the normal vectors as if they were points. Afaik the correct transformation would be to make a 4D vector with 0 in the w component, then to multiply by the transposed of the inverse of the model matrix (of `mesh_matrix`) (from the left, obviously), and then to swap y with z (multiply with `TRANS_MATRIX`). This is obviously not what the b3d exporter does there.

Minetest shouldn't have to handle broken meshes. But if it has to, there should be a warning, and adjusting the winding order is probably better, imho.

**Comment by appgurueu** [comment]
> Minetest shouldn't have to handle broken meshes. But if it has to, there should be a warning, and adjusting the winding order is probably better, imho.

I would have been fine with a warning. It was just very weird when the normals MT were using didn't match the normals I were feeding it. Something like "face normal doesn't match winding order, recalculating face normal from winding order"

**Comment by x2048** [comment]
@Desour The problem is different: Blender has 3 sources of normals: vertex normals, face normals and loop/split normals. We are using vertex normals (which are always 'average'), and we should be using is loop/split normals. I made a patch for that [here](https://github.com/GreenXenith/io_scene_b3d/pull/7), and it contains screenshots of how editing the model in Blender would reflect in Minetest.

**Comment by x2048** [comment]
> t was just very weird when the normals MT were using didn't match the normals I were feeding it.
...
> Minetest shouldn't have to handle broken meshes. 

That's why I want to remove the workaround entirely.
