### ISSUE TITLE
Get rid of first time join passwords

### ISSUE THREAD

**Issue by ixPost** [minetest/minetest#12544]
I don't see why we should have to enter a password when joining a server for the first time. It's enough to tell the user the risks of joining new servers, & asking if they want to continue.

**Comment by rubenwardy** [comment]
Thanks for the suggestion

This has already been removed in 5.6.0-dev, will be released as part of 5.6.0

**Comment by ixPost** [comment]
> Thanks for the suggestion
> 
> This has already been removed in 5.6.0-dev, will be released as part of 5.6.0

😱

**Comment by rollerozxa** [comment]
Since there is no central authentication system in Minetest you will always need to register an unique account on each server, which includes setting a password to protect that account (this is also enforced by most servers themselves). So passwords themselves will not been removed in 5.6.0 but the multiplayer login/register system has instead been refined to be less obtuse, including removing the first time join dialog in favour of a more straightforward register dialog.

![image](https://user-images.githubusercontent.com/60856959/179273166-7f038aa9-68c8-4453-8e84-6ccbc27279c6.png)

**Comment by ixPost** [comment]
> Since there is no central authentication system in Minetest you will always need to register an unique account on each server, which includes setting a password to protect that account (this is also enforced by most servers themselves). So passwords themselves will not been removed in 5.6.0 but the multiplayer login/register system has instead been refined to be less obtuse, including removing the first time join dialog in favour of a more straightforward register dialog.

Thank you for commenting that, if the password was removed then EugeniusBaptista(he play's on Librety Land.) could take my stuff.

**Comment by ixPost** [comment]
> You see all my other multiplayer games don't have these passwords.

Actually most of my other (multiplayer)games are about fighting, it's not like you build any thing there.
