### ISSUE TITLE
Error: game specified in default_game [minetest] is invalid

### ISSUE THREAD

**Issue by runsy** [minetest/minetest#12548]
Today version. 5.6-dev 17-july
`
2022-07-17 13:13:50: ERROR[Main]: Game specified in default_game [minetest] is invalid.`

I solved putting a default_game setting in my customized minetest.conf.

But I Think is is an error that mandatory field.

**Comment by Zughy** [comment]
How were you able to trigger it?

**Comment by runsy** [comment]
> How were you able to trigger it?

Simply updating to the new version.

**Comment by Zughy** [comment]
Mmm.. It didn't happen to me

**Comment by rubenwardy** [comment]
This happens when Minetest Game isn't installed

**Comment by runsy** [comment]
So, no low priority. High priority. Minetest (engine) NEVER should depend on MTG.

**Comment by rollerozxa** [comment]
This "error" is a literal non-issue, this is only intended to make Minetest Game be selected rather than devtest in regular bundles of the engine. If you were to ship the engine with another game or with no games at all it will simply fallback.

**Comment by rubenwardy** [comment]
If you don't provide a --gameid when creating a new world using the command line, it'll fallback to the default game which is minetest_game. If the default game isn't installed then it throws an error.

There are some options here:

1. Remove default_game, select first game that isn't devtest
2. Remove default_game, select only game that isn't devtest, error otherwise
3. Keep behaviour as-is
4. Set default_game to "" by default, and use either 1 or 2 to auto detect
5. Remote default_game, error if the user doesn't provide `--gameid` by command line

**Comment by runsy** [comment]
> This "error" is a literal non-issue, this is only intended to make Minetest Game be selected rather than devtest in regular bundles of the engine. If you were to ship the engine with another game or with no games at all it will simply fallback.

So why not default fallback to The Samz or Juanchi. This has no sense, MTG has to be removed from the formula. Cos Minetest is an engine that have to have no favorite games.
