### ISSUE TITLE
Devtest tiled:tiled_n texture is misleading

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#12559]
##### Summary

`scale` is only documented for work for world-aligned nodes. But `tiled:tiled_n` sets it to 8 and also uses the tiled texture that has 8x8 parts.
To an observer this falsely suggests that the tiling is broken.

It should use a different texture and not attempt to set scale=8.

**Comment by Wuzzy2** [comment]
Sounds like this particular node is just invalid then and should not exist in DevTest at all. Since node-aligned textures are the default, it is already used in all other test nodes implicitly. So maybe this test node can be removed completely.

Half-off-topic idea: Extend the tooltips of most "weird" items like `tiled:tiled_n` to roughly explain what they are expected to do (so everyone can see if an item misbehaves).
