### ISSUE TITLE
can minetest server support 500 online players?

### ISSUE THREAD

**Issue by xudaquan2009** [minetest/minetest#12601]
## Problem

I run a minetest server on windows and  DB is postgresql.
when more than 150 clients login, client can't open the map.

but i want that 500 players online, can minetest server support?

**Comment by mieu12** [comment]
Possibly. Not too sure either but I'm sure a server can support any amount of players as long the device can handle it. WARNING: Make sure to have enough disk/CPU

**Comment by Zughy** [comment]
Please ask these questions on one of our communities https://www.minetest.net/get-involved/

**Comment by sfan5** [comment]
In theory the server can support very high player numbers, but there are some parts that might slow down because they are not particularly efficient with large numbers. In practice probably nobody has surpassed 80 players on a single server.

You will have to increase the `emergequeue_limit_total` setting to make sure the server can still service map loading and generation (`num_emerge_threads` can also help).
If you encounter any other issues that can be reproduced please open a bug report.

**Comment by rubenwardy** [comment]
You'll need a very very powerful server to do this, to an infeasible scale. Minetest only supports vertically scaling - improving the hardware. You'll need a server with high single core performance and strong networking. Minetest doesn't really have enough players to get 500 on a single server

Depending on the game type, a more feasible way to support 500 players would be to use a reverse proxy to make multiple Minetest servers appear to be a single server. You would then be able to move players between servers without them noticing. This would work well for a minigames server as you could run a server per minigame session and then use the reverse proxy to make it appear as a single server. There's been several attempts to implement software like this in Minetest, the most prominent I know of is https://github.com/HimbeerserverDE/multiserver. The MC equivalent of this is called Bungiecord.

**Comment by sfan5** [comment]
I just stumbled upon this post of mine, it also contains some advice: https://forum.minetest.net/viewtopic.php?p=402811#p402811
