### ISSUE TITLE
Get client version and platform

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#12603]
# User Agents

A User-Agent string is useful to let server mods to easily handle different type of Minetest clients, just like what websites do. Minetest servers can then give the best playing experience (i.e. changing the inventory formspec) or to find out Minetest client versions (previously done by inspecting the formspec version, though formspec version before MT5.5.0 are not bound to a specific version).

Here are some examples of User-Agent string:
* Minetest 5.6.0 (stable) on Linux: `Minetest/5.6.0 Linux`
* MultiCraft 2.3.0 (if they also applied the changes) on macOS: `MultiCraft/2.3.0 Darwin`
* Minetest 5.7.0-dev on Android: `Minetest/5.7.0-GITHASH Android`
* Minetest 5.7.0-dev dirty on Windows: `Minetest/5.7.0-GITHASH-dirty Windows`

I'm not expecting the User-Agent string can be fully reliable (they could be hacked by simply modify the source codes), but to provide basic information about the clients to the server.

**Comment by erlehmann** [comment]
User agent strings are a bad idea and the web is a good example for that. They ultimately lead to things like everyone pretending to be `Mozilla/5.0` as in `Mozilla/5.0 (Linux; Android 4.0.4; HTC Desire P Build/IMM76D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19` so that newer clients still work with older server code that was never updated.

Additionaly, this way each mod would have to maintain a mapping of UA strings to feature sets it wants to support.

I am pretty sure that you probably need one of these things instead:

* a way to track users or get statistics about clients built into the engine
* a way to get client supported features, e.g. formspec version on the client – similar to the display feature thing by @rubenwardy
* graceful degradation or progressive enhancement for formspecs, so the engine handles this automatically (not sure if possible)

**Comment by Zughy** [comment]
@rubenwardy I think that changing the title name and keeping the two comments about user agent strings is confusing (it was for me at least). I'd suggest to create a different issue for this rather than just completely change the title

**Comment by rubenwardy** [comment]
It would be nice if @Emojigit could have used the issue template as well

**Comment by Zughy** [comment]
closing then, please OP open a new issue following the template

**Comment by sfan5** [comment]
Also note #10632 and related discussions.
DPI, screen size and touch support are useful indicators for mods while I don't really see a need to know whether the user is using Linux, Windows or macOS.
