### ISSUE TITLE
Shader failed to generate

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#12613]
##### Minetest version

```
Tested on: 5.5.0, 5.5.1
```

##### OS / Hardware

Operating system: Android 6.0.1 (API level 23)
CPU: Mediatek MT6734

GPU model: Mali
OpenGL version: ES 3.1

##### Summary

The shader is bugged in the first time open the game

the world is black
and a lot of error text appear

video:
https://youtu.be/mWZ2RR1R__k
##### Steps to reproduce

Install Minetest (yes, this bug only appear first time)
Open the game
Set video driver to OGLES2
Turn on shader
open a world or join a server

**Comment by rollerozxa** [comment]
Can reproduce, happens on 5.5 if you switch from OGLES1 to OGLES2 and enable shaders without first restarting Minetest (assumedly tries to compile OGLES2 shaders on an OGLES1 context... which does not work). Does this still occur after you've restarted Minetest?

**Comment by oong819** [comment]
its only happen in first time open the game

**Comment by oong819** [comment]
this probally a duplicate of something like setting dont be saved in first time open the game

**Comment by rollerozxa** [comment]
This would be user error. Changing the video driver is an advanced setting and the description for the setting states a restart is required for the setting to take effect. 

The real issue would seem to be that the shader settings are immediately being enabled in the main menu settings tab since it checks for the setting's value rather than what Irrlicht video driver is actually running at the moment.

**Comment by sfan5** [comment]
Needs re-testing.

**Comment by oong819** [comment]
As i remember, i did the all the thing in reproduce steps in 5.7.0 (normal thing i do every time i re-install Minetest) and it's completely normal, but i will not trust my memory, but i also ran out of storage space to install Minetest
