### ISSUE TITLE
Add blog integration to mainmenu

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#12769]
Inspired by a launcher featuring a news tab, I'm considering a mainmenu integration for "news" which would just poll the blog. The blog could use a convenient JSON API (equivalent to the RSS feed) to allow Minetest to pull the latest articles. I also wonder whether we should render articles to hypertext form (or just provide a "view in browser" option).

I am willing to work on this.

**Comment by Zughy** [comment]
I think it'd be best to differentiate between a launcher and a main menu. I picture the blog integration within the former (alongside features like changing version)

**Comment by appgurueu** [comment]
> I think it'd be best to differentiate between a launcher and a main menu. I picture the blog integration within the former (alongside features like changing version)

I don't like the concept of "launchers" at all. While version management is "meta" enough to warrant a launcher (e.g. it requires extensive permissions, is highly platform specific etc.), news aren't. I can very well imagine putting this in the mainmenu to replace or complement the "About" section.

**Comment by Zughy** [comment]
In my mainmenu proposal, the about section is even less visible than now, relegated in the Settings section (last entry). Anyway, every game I've ever played (yes, this is more of a platform yadda yadda) always put news in the launcher rather than inside the very game, so that you can read what's new even before launching the actual game (I guess also because the launcher fits the role, as it acts as a billboard without too many input, launching the game and few settings aside)

**Comment by rubenwardy** [comment]
I don't support doing this at this time. Perhaps after the mainmenu redesign we'd find a space for it
