### ISSUE TITLE
Add Privacy Policy (now required by Google Play)

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#12809]
I'm unable to upload to Google Play as it now requires a privacy policy.

You should always write privacy policies yourself, and not use an automatic generator. They're not too hard to write, and you want it to be accurate. Here's ContentDB's privacy policy, as an example: https://content.minetest.net/privacy_policy/

Rather than a markdown file in this repo, it could be better to add it to the website

**Comment by appgurueu** [comment]
The only requests Minetest makes to centralized servers are those to ContentDB & the serverlist. I assume the serverlist would need a privacy policy. Otherwise linking to the CDB & serverlist privacy policies should be enough. Perhaps we should also add a note about which data the client sends to the various servers, but how that is logged & stored varies from server to server.

**Comment by rubenwardy** [comment]
The privacy policy would need to mention the serverlist, update checker, and ContentDB. It can link to each service's privacy policy for more information, but should probably have a summary of the data it sends.

It should also mention the ability to connect to third-party servers, but say to check the server's privacy policy

**Comment by HybridDog** [comment]
As far as I know, traffic sent to servers is not encrypted and not authenticated, so a man in the middle can read and modify, for example, chat messages (issue #10206). 
Should the privacy policy mention this?

**Comment by srifqi** [comment]
As a trigger, I created [a draft privacy policy for Minetest Android port](https://gist.github.com/srifqi/81e60c92b30c6f824dce3d9cb065b751) based on a variety of examples. This draft is not to be implemented as is, but as an initial document that can be developed further.

https://gist.github.com/srifqi/81e60c92b30c6f824dce3d9cb065b751

**Comment by rubenwardy** [comment]
I suggest making it a general privacy policy, rather than linked to Android. ContentDB's full name is ContentDB, it shouldn't be expanded to content database. You can link to ContentDB's privacy policy

**Comment by SmallJoker** [comment]
@srifqi Unless someone else is coming up with an even more refined version, would you be interested in creating a PR for that? Improvements could then be discussed there.

**Comment by rollerozxa** [comment]
I just tried to publish an app onto Google Play that got rejected for an invalid privacy policy. In the rejection email they also listed this checklist of requirements for a privacy policy, which could be useful to check against:

> Please review the following compliance checklist for privacy policies. Your privacy policy must:
> 
> * Be linked on your app’s store listing page in Play Console and within the app itself.
> * Hold reference to the entity (for example, developer, company) named in the app’s Google Play listing or the app.
> * Include a clear labeling as a privacy policy.
> * Be readable in a standard browser without any plug-ins or special handlers (no PDFs).
> * Be available on an active, publicly accessible and non-geofenced URL.
> * Be non-editable.
> * Comprehensively disclose how your app accesses, collects, uses, and shares user data. This must include:
>    * Disclosing the types of personal and sensitive user data your app accesses, collects, uses, and shares; and any parties with which any personal or sensitive user data is shared.
>    * Secure data handling procedures for personal and sensitive user data.
>    * Developer’s data retention and deletion policy.

Most of them are pretty obvious and I think the draft would meet all of these requirements. But they also want it to be linked inside of the app as well, so there would probably need to be a button to the privacy policy crammed somewhere in the about tab.

**Comment by sfan5** [comment]
FWIW I have an app on the Play Store where the privacy policy is *not* linked inside it.

**Comment by rollerozxa** [comment]
> > FWIW I have an app on the Play Store where the privacy policy is _not_ linked inside it.
> 
> The requirements for new apps may have changed since then however.

Not unheard of for Google Play rules to be enforced inconsistently, but I really would hate for 5.7.0 to not be available on Google Play yet again.

**Comment by appgurueu** [comment]
Perhaps worth noting that by default, Minetest servers send a list of currently online players to the publicly accessible serverlist. That is, your activity (personal data) on servers which send this data - all listed servers except for unofficial/modified ones - is practically publicly available.

**Comment by Wuzzy2** [comment]
I read the draft (2nd revision) as a non-lawyer, here are some of my complaints:

> Other Server Owners may collect other information when you connect to **his/her** server(s)

(found in a couple of other places)

Please use the "singular they" instead of "his/her". E.g.:

> Other Server Owners may collect other information when you connect to **their** server(s)

Note that "his/her" isn't synonym with "everyone" since you're forgetting people who go by non-normative pronouns (like many enbies do).

> Encrypted backups of our services may be shared with our selected staff members. The keys and the backups themselves are given to different people, requiring at least two staff members to read a backup.

Which staff? Minetest isn't a corporation.

> We may be required to share information with law enforcement.

Clarification would be nice. The law enforcement of which nation? Will you actively report all "suspicous activity" to the feds or only when you're forced to?

> It may collect information about your traffic data such as […] cookies

This doesn't make sense, cookies aren't really "traffic data", cookies are data to store state. Tbh I don't know what you mean with "traffic data" anyway, this term is vague. Is it data that is transferred? Any collected data that somehow relates to traffic? Probably needs a rewrite/rewording.

> Other Server Owners may place his/her server(s) in any country. Please be sure to read the privacy policy for the servers you are using.

Yeah, this advice is useless, many servers don't have a privacy policy and even if, how on Earth are you, the player, going to find it before you join? This is a pipedream.

**Comment by rubenwardy** [comment]
A lot of the weirdness of this privacy policy come from parroting random parts of ContentDB's privacy policy - it would be better to just link to CDB's privacy policy like

> When you use the "Browse online content" tab, Minetest will contact ContactDB. See [ContentDB's privacy policy](https://content.minetest.net/privacy_policy/)

**Comment by appgurueu** [comment]
> > Other Server Owners may collect other information when you connect to **his/her** server(s)
> 
> (found in a couple of other places)
> 
> Please use the "singular they" instead of "his/her". E.g.:

It isn't even need singular they here, you can use plural they just fine since you're referring to the mixed group of server owners. "their servers" reads absolutely fine and better than "his/her server(s)".

**Comment by SmallJoker** [comment]
@srifqi Sorry for my late answer. I am not aware of any specific file names but would recommend putting it next to Minetest's README.md file, perhaps naming it `PRIVACYPOLICY.md`/ `PRIVACY.md` or something along those lines.

**Comment by rubenwardy** [comment]
I would suggest putting it on the website instead, as app-privacy-policy.md

**Comment by srifqi** [comment]
I have updated [the draft](https://gist.github.com/srifqi/81e60c92b30c6f824dce3d9cb065b751). Please note that I am not a lawyer nor an English native speaker, so please give more concrete suggestions as I may not be able to write/create the sentences by myself.

For the PR, I defer to create it until at least there is a consensus among core developers as to where this document should be.

**Comment by Charleston314** [comment]
I made this PR adding a privacy policy to the main repository, but it can always be copied over to a website as well. Also, it might be a good idea to change the policy to only apply to the Google Play Store release, since that is the only one we need it for. I welcome any comments or edits to the commit in question.
