### ISSUE TITLE
Footstep sound loops fast while standing still at very high or low coordinates

### ISSUE THREAD

**Issue by debagos** [minetest/minetest#12817]
Minetest Version: 5.7.0-dev@https://github.com/minetest/minetest/commit/b1233056b76aa803123cc304d323887ad5fdfbae

Watch this video with sound:

https://wunderwelt.one/footstep_bug.mp4

It's only happening at very high or low coordinates.
x=30,000 y=0 z=30,000 -> not happening
x=30,000 y=-30,000 z=30,000 -> happening
Only the Y axis matters.

**Comment by Niklp09** [comment]
I can confirm with mt master

**Comment by TurkeyMcMac** [comment]
The problem looks to be here: https://github.com/minetest/minetest/blob/b1233056b76aa803123cc304d323887ad5fdfbae/src/collision.cpp#L256-L258

I think the problem is that, if the function returns here, `result.touching_ground` is not set, even if it should be. This probably only happens at high coordinates due to floating point rounding error.

It seems this wasn't a problem before 1317cd12d74dba4ff765d6e18b0b30cdf42002a3. @appgurueu
