### ISSUE TITLE
Smoother yaw changes of entities and players

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#1283]
Position changes on entities are already smoothed (since long time ago).

I tried to also make yaw changes smoothed (currently, they aren't, which looks bad) to no avail recently.

_SmoothTranslator in content_cao.cpp_

**Comment by benrob0329** [comment]
+1

**Comment by Fixer-007** [comment]
:+1:

**Comment by paramat** [comment]
Is anyone capable and interested in coding this? Closing in 1 month if not.

**Comment by rubenwardy** [comment]
is this done yet? Watching in game it looks like rotation is interpolated, is this issue for making it smoother?

**Comment by Fixer-007** [comment]
Is there way to check? I've tried mobs_redo and they still instaturn without smoothing.

**Comment by SmallJoker** [comment]
The player positions are already interpolated client-side, but not yaw changes:

https://github.com/minetest/minetest/blob/18b921015a33c6e597f480bccc7e2974af33c4ea/src/content_cao.cpp#L1296-L1302

**Comment by MarkuBu** [comment]
You mean smoothed like this?

https://www.youtube.com/watch?v=73wUZuHR2x4

**Comment by MarkuBu** [comment]
Here is a more actual video

https://www.youtube.com/watch?v=QuqXuyg8PrE

FYI: this is all done in Lua. I use vectors for movement and I directly set yaw from these vectors. No need for any kind of fancy smoothing algorithm or I/P or PID controller.

If this calculation would be done in the engine the movement would be much smoother. I am limited to the on_step resolution.

It is still possible that the mob makes a fast rotation if the vector changes the direction very fast, but it is still acceptable

**Comment by Fixer-007** [comment]
>You mean smoothed like this?
>https://www.youtube.com/watch?v=73wUZuHR2x4

Yes

**Comment by MarkuBu** [comment]
The code behind is just for moving. There is no "intelligence". I just find a path to the player and the mob follows the path. The code needs some optimization, but works as expected in most cases.

I think this is how mob movement should be done. There is no need for PID controller or rotation speed limiter and as demonstrated in the videos it works pretty well

**Comment by benrob0329** [comment]
No offence, but the movement in both of those videos is not what I would consider "smooth". Its choppy, and stepped. Its definitely a step in the right direction, but we still need proper rotation smoothing on the client side.

**Comment by benrob0329** [comment]
Missed that, sorry.

**Comment by MarkuBu** [comment]
Well, you are right that it is currently not perfect. But I think it could be done even better in Lua because it is not finally optimized and I think I have a few bugs I need to fix.

And you are also right that the rotation could be smoother, but I think a "speed limit" on the client side is the wrong way because this could be end in weired situations because the server does not know the actual yaw. He might calculate a new velocity, but the mob looks in the wrong direction. 

It will look like the white sheep in this video. They move sometimes backwards and then rotate. I used in this code some kind of rotation speed limit

https://www.youtube.com/watch?v=0wC3JlKkvv0

You can't decouple moving and rotation

**Comment by paramat** [comment]
#6825 merged.
