### ISSUE TITLE
Add Procedurally Generated Animations Support

### ISSUE THREAD

**Issue by FossFanatic** [minetest/minetest#12982]
## Problem

Minecraft, back in the older days, used to not have animations as image files.

Instead, they used to be procedurally generated, and this made the animations unique every single time.

It would be neat if it was possible to do something like this with the Minetest engine as well.

## Solutions

Make it possible to have procedurally generated animations like Minecraft used to.

## Additional context

https://minecraft.fandom.com/wiki/Procedural_animated_texture_generation

**Comment by Desour** [comment]
Already possible. You can procedurally generate textures in mods, encode them as png, and send as dynamic media.
For client-side generation we need sscsm first.

**Comment by rollerozxa** [comment]
Doing that kind of thing on the fly using dynamic media would fill up the client's memory as sent dynamic media never gets removed. Best would in fact be implementing it for SSCSM, where client scripting can generate and display an item or node's texture programmatically without the network or image format overhead (basically, just like Minecraft's programmatically generated animations used to work, doing it on the client rather than on the server)

**Comment by TurkeyMcMac** [comment]
@FossFanatic How about you request texture creation/manipulation on https://github.com/minetest/minetest/issues/8057.

**Comment by TurkeyMcMac** [comment]
I added the request to that issue. I'll therefore close this one.
