### ISSUE TITLE
some privacy issue

### ISSUE THREAD

**Issue by Zweihorn** [minetest/minetest#13057]
@sfan5 @stefanbeller @Ekdohibs

Did you intentionally want to publicly distribute the email addresses of the MT developers?

If not, you should consider the deletion of the `github.com/minetest/minetest/.mailmap` file from this repository.

**Comment by rubenwardy** [comment]
The email you use for Git is public, removing that file won't change that

**Comment by Zweihorn** [comment]
Maybe true. However, some persons are listed with more than one email address.

Anyway not my cup of tee.

**Comment by Zweihorn** [comment]
@rubenwardy - May be not true for everybody.

I took the effort to check the GitHub documentation

- - -  
If you'd like to keep your personal email address private, you can use a noreply email address from GitHub as your commit email address. To use your noreply email address for commits you push from the command line, use that email address when you set your commit email address in Git. To use your noreply address for web-based Git operations, set your commit email address on GitHub and choose to Keep my email address private.
- - -  
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address

**Comment by rubenwardy** [comment]
The email you **use for Git** is public. When using GitHub, you can use a noreply email address for Git instead of your actual email - that noreply email address will then be the public one.

The email addresses in mailmap are the email addresses used for Git commits. Sometimes authors use different email addresses over time. For example, I started with a gmail email and then moved to `@rubenwardy.com` when I bought that domain. The point of the mailmap file is to tell Git that these two email addresses are the same person

**Comment by Zweihorn** [comment]
No problem with that claim and closed.

**Comment by Zweihorn** [comment]
BTW

My Git email address is:  4863737+Zweihorn@users.noreply.github.com

This is **not** my private email address intentionally.

**quot capita tot sensus**
