### ISSUE TITLE
Development Test header uses Minecraft font

### ISSUE THREAD

**Issue by ConstBool** [minetest/minetest#13145]
##### Minetest version
Any

##### OS / Hardware
Operating system: Computer
CPU: Processor

##### Summary
The header used in the built in Development Test game uses the Minecraft font. Minetest really should not use the Minecraft font for legal reasons.

##### Steps to reproduce
Obtain a faithful font file of the Minecraft font such as from [here](https://www.fontspace.com/minecraft-font-f28180). Write "Development Test" in an image editor with Anti-Aliasing disabled and at 16 pixels. You will see it is pixel perfect when comparing against the Development Test header image text.

**Comment by sfan5** [comment]
Header image added 2020 in commit 083b285f4319c470f307f0b52f03a2fb68facd38 by @Wuzzy2, claims "the same license as for Minetest" which is a bit vague but would mean CC BY-SA 3.0.

The font you linked claims to be public domain but it is questionable how that could be true when it is reproduces a copyrighted font (presumably) perfectly.

**Comment by iliekprogrammar** [comment]
For reference, above is in Minecraft, below is in Minetest:

![comparison between the text "development test" in MT and MC](https://user-images.githubusercontent.com/51074650/212540631-4472fdd7-0b2c-4dab-90e4-65f3bbd775d6.png)

Not ideal.

**Comment by rollerozxa** [comment]
Can indeed reproduce. Instead of using a Minecraft TTF font recreation like linked I recreated the text using the original bitmap font inside of the game. It matches pixel perfectly.

![header](https://user-images.githubusercontent.com/60856959/212555768-c7029322-08cf-4074-912d-300210188850.png)

**Comment by rollerozxa** [comment]
Worth noting though that I'm not sure whether the pixelated Minecraft font originates with Minecraft or if it's just a generic font that was taken by Minecraft (there are a lot of pixelated fonts do look similar), but I don't know for certain so I'd just assume it was made for Minecraft and copyrighted by Mojang.

**Comment by Wuzzy2** [comment]
The font I used was from I believe a public domain source, but I am not sure. I swear I did *not* rip from Minecraft itself.

The font could be identical because it's the other way round: Minecraft used a public domain font. ;-) But this is just guessing at this point. Since you're very nervous about this, and the commit is my "fault", I am posting a PR very soon which will use the "undefined" font suggested by rollerozxa. This one is SIL Open Font License, Version 1.1.

If that isn't safe enough for you, I suggest Gohu Font, which is WTFPL (which we then can convert into any license we want). https://font.gohu.org/
