### ISSUE TITLE
Infinite view range no longer works

### ISSUE THREAD

**Issue by rollerozxa** [minetest/minetest#13224]
##### Minetest version
```
5.7.0-dev latest master
```
##### OS / Hardware
GPU model: AMD Radeon RX 560
OpenGL version: 4.6

##### Summary
Infinite view range no longer works after commit https://github.com/minetest/minetest/commit/2715cc8bf68a2cc8cd583cd5b0bb732ee13a1b49. It should show all loaded mapblocks independent of the viewing range set.

##### Steps to reproduce
Turn up the view range really high and fly around for a bit. Enable infinite view range and turn down the view range. All previously loaded parts of the terrain should be visible, but aren't.

**Comment by Desour** [comment]
If there's an unloaded sector between, the blocks behind it are not drawn.
(I already commented on this in original PR, but thought it was no issue.)
Related: #13198

**Comment by lhofhansl** [comment]
Hmm... This has to do with:
`getBlocksInViewRange(cam_pos_nodes, &p_blocks_min, &p_blocks_max);` and `MapBlockFlags blocks_seen(p_blocks_min, p_blocks_max);`

Since this is searching for visible blocks now, the computation needs to be limited somehow.

I suppose with infinite view_range we can just consider all blocks + the relevant mesh-holding blocks, frustum cull, occlusion cull, and show what remains.

@x2048

**Comment by lhofhansl** [comment]
I suppose with the more recent change in mesh-chunking we did not actually have to remove the old logic for culling.

@x2048 I wonder if the old way is sometimes faster when many air-only blocks have not been transmitted to the client.
Previously the logic had to only consider loaded blocks, now it also has to consider unloaded within range and assume that they are transparent.

**Comment by MathPlusEnglish** [comment]
I thought the infinite view range was removed.

**Comment by rollerozxa** [comment]
> I thought the infinite view range was removed.

Only the default keybind. You can remap it yourself.
