### ISSUE TITLE
SSH public key authentication

### ISSUE THREAD

**Issue by caffeinatedblocks** [minetest/minetest#13267]
READ: I have the willingness to make this happen, but I'm not going to do it unless I'm assured that it will be accepted by the core dev team. I'm submitting this issue only to find out if I have core dev support, and if there is any community interest.

## Feature

I would like to add SSH public key authentication to minetest.

This would be an OPTIONAL feature that would enable password-less registration and authentication, and also pave the way for minetest protocol encryption.

1. Client/server could each be configured to generate a unique key pair on first run.

2. Client subsequently, or thereafter, has functionality to:

    a) generate a new key pair (with optional password-protected private key for additional security)
    b) register to servers with private key (client would send only username and public key)
    c) authenticate with that private key (client and server would exchange public keys and complete authentication similar to SSH)
    d) export existing key (to move key to another device)
    e) import existing key (to load existing key from another device)

3. Server only needs to store public keys.

4. Client can track server fingerprints to help ensure you're connecting to the server you registered with to prevent DNS spoofing and other attacks.

5. Updating key could take place one of two ways:

    a) if you still have your old private key: new public key could be pushed to any server you've previously registered with by sending <username>:<old_key>:<new_key>
    b) if you lost your key, or are signing in with a new device, you could generate a new key and ask a server admin to install the new key for you: server admins should have chat commands to facilitate this process, e.g. /addkey <player_name> <public_key> or /replacekey <player_name> <public_key>

6. Keys could also be revoked/removed as needed:

    a) players could /revokekey all or /revokekey <key_index>
    b) admins should have similar functionality

### Benefits

- This would make it very easy for clients to securely connect to multiple servers without ever needing a password.
- Authentication happens without exchanging any secrets whatsoever (where SRP discloses salt, at least, to anyone who asks).

### Future extensibility

Once this is implemented, it could be used to very simply encrypt packets back and forth between client and server while keeping UDP and still not requiring TCP since client/server would already have exchanged public keys.

**Comment by Montandalar** [comment]
A few thoughts

1. SSH keys can have passphrases, so even SSH authentication can still require a password field (this was mentioned but briefly).
2. The session itself would want to switch to time-limited symmetric key encryption because this type of encryption is much, much faster to perform and we do not want to drag performance.
3. The session encryption could be implemented independently from the SSH authentication itself and still work fine over the existing SRP as long as the shared secret exchange algorithm is in place.
4. Since this will not replace SRP authentication, how, in UI/UX terms do you intend for end users to configure what authentication method they are using? What about joining servers on older protocol versions?

**Comment by vintprox** [comment]
Sounds amazing!

**Comment by rubenwardy** [comment]
Duplicate of #11925

SRP disclosing the salt is not a problem, SRP is used so that Minetest doesn't need to trust the server - the server has access to all the information including the salt.

Supporting this feature would add complexity that not many users would use. Unlike SSH users, a large proportion of players are non-technical. Using an SSH public key is a technical and user experience barrier.

It would not make adding network encryption any easier as SRP already results in a shared key that could be used to set up encryption - and has the benefit of knowing that the server you're communicating with is the same one you originally registered on. 

The only compelling use cases of public keys for me would be if either:

1) the keys were stored in a centralised auth server to implement a fault tolerant login system (we already don't want to do this)
2) the keys could be automatically generated and used as a "remember me" feature (there's probably simpler ways to do this)

**Comment by nerzhul** [comment]
i understand your need but it's clearly niche for technical users, i think @rubenwardy explained properly issues implementing such feature

**Comment by caffeinatedblocks** [comment]
> Duplicate of #11925
> 
> SRP disclosing the salt is not a problem, SRP is used so that Minetest doesn't need to trust the server - the server has access to all the information including the salt.
> 
> Supporting this feature would add complexity that not many users would use. Unlike SSH users, a large proportion of players are non-technical. Using an SSH public key is a technical and user experience barrier. When judging a piece of work, you need to weigh up the risks/complexity against the benefit (including number of users impacted)
> 
> It would not make adding network encryption any easier as SRP already results in a shared key that could be used to set up encryption - and has the benefit of knowing that the server you're communicating with is the same one you originally registered on.
> 
> Some compelling use cases of public keys for me would be if either:
> 
>     1. the keys were stored in a centralised auth server to implement a fault tolerant login system (we already don't want to do this)
> 
>     2. the keys could be automatically generated and used as a "remember me" feature (there's probably simpler ways to do this)  Related: [saving username/password login per server basis #1566](https://github.com/minetest/minetest/issues/1566)

1. This is not exactly the same as #11925, and that issue is closed. If anything, that one could be reopened and this one could be merged into it to extend it.
2. SRP 6a has been broken many times over and is still debatable.
3. Right, the salt is NOT known... until the server discloses it... to anyone who who merely asks for it...
4. Key based authentication is well-known, widely adopted, time tested, and thoroughly proven.
5. This would be an optional feature only for those who wish to use it. It could even be hidden away in a top-secret setting that needs to be enabled manually via GUI or minetest.conf for those of us who are savvy.
6. Anyone who operates a server and who also builds/tests and has had to cycle login/restart/repeat hundreds of times per month like I do would surely agree that this method would be preferable over typing/pasting a password every single time irrespective of any other arguments.
7. A centralized auth server adds another point of weakness. Just as with SSH, each user should be responsible for their own keys. Keys are easy to import/export and move around.
8. Would you send your social security number or other sensitive personal information over an SRP-encrypted channel? If you think my point is moot and I'm being ridiculous, consider all of us who have kids out here playing online who would really like to see some measure of encryption built into chat, at least. Personally, I'm far more concerned about my kids safety than I am anyone stealing my identity.

**Comment by rubenwardy** [comment]
If SRP is broken then that needs to be addressed for the benefit of all users. Adding a new auth method that won't be used won't help things

**Comment by NathanSalapat** [comment]
@caffeinatedblocks not to be rude, but adding encryption to chat won't protect your kids when literally anybody can join the server and see their chat messages.

**Comment by caffeinatedblocks** [comment]
> @caffeinatedblocks not to be rude, but adding encryption to chat won't protect your kids when literally anybody can join the server and see their chat messages.

1) That argument is about as valid as saying "adding two-factor authentication to your bank login won't protect you when literally anybody can run up, punch you in the face, and snatch your laptop/phone while you're logged into your account."

2) Use case: public / shared / free wifi, on a semi-private (closed-to-registration) server where there is a reasonable expectation of privacy

3) You get notified when people join a game. You don't get notified when someone's capturing your packets.

4) The least of my concerns is the casual passerby popping in. More concerning is that it would take very little effort for someone to specifically target my kids and learn things my kids would never say if they knew some stranger was listening in. 

5) It's 2023, are we really debating "is that really necessary" in regard to encryption and privacy?

**Comment by rubenwardy** [comment]
Encryption is necessary and the issue for that is #10206 

This issue is about SSH public key authentication, which is not needed for network encryption

**Comment by caffeinatedblocks** [comment]
@rubenwardy 
> If SRP is broken then that needs to be addressed for the benefit of all users. Adding a new auth method that won't be used won't help things

The point is that Minetest's "security" is literally one step above sending plain-text passwords. It offers no encryption, and even only as far as convenience is concerned, it doesn't even offer to remember my password so I don't have to enter it in every single time.

The other day, just for giggles, I wrote my own SRP 6a client reading a very public document (https://www.rfc-editor.org/rfc/rfc2945). Having no idea what "random salt" my minetest client originally generated when registering with the server, just knowing my password, I was able to log right in to the server. Why? Because as soon as ANYONE attempts to connect using your username, the server sends them your salt! What the heck is the point of having the salt?

Bottom line: I can connect to any MT server, keep note of admins' usernames, then simply connect back to the server with their username, collect all their salts, and run a dictionary attack just as if there was no SRP.

That's what makes SRP a joke. It's not even computationally expensive.

Here's the big secret as published in [RFC-2945](https://www.rfc-editor.org/rfc/rfc5054.html):

N = AC6BDB41324A9A9BF166DE5E1389582FAF72B6651987EE07FC3192943DB56050A37329CBB4A099ED8193E0757767A13DD52312AB4B03310DCD7F48A9DA04FD50E8083969EDB767B0CF6095179A163AB3661A05FBD5FAAAE82918A9962F0B93B855F97993EC975EEAA80D740ADBF4FF747359D041D5C33EA71D281E446B14773BCA97B43A23FB801676BD207A436C6481F1D2B9078717461A5B9D32E688F87748544523B524B0D57D5EA77A2775D2ECFA032CFBDBF52FB3786160279004E57AE6AF874E7303CE53299CCC041C7BC308D82A5698F3A8D0C38271AE35F8E9DBFBB694B5C803D89F7AE435DE236D525F54759B65E372FCD68EF20FA7111F9E4AFF73
g = 2

Everything else I need to know is right in Minetest's open source code:

s = 16 random bytes
k = sha256( N | g )
x = sha256( s | sha256( I | p ))
v = powmod(g, x, N)

3 cheap hashes and a powmod is not "security."

**Comment by sfan5** [comment]
> Anyone who operates a server and who also builds/tests and has had to cycle login/restart/repeat hundreds of times per month like I do would surely agree that this method would be preferable over typing/pasting a password every single time irrespective of any other arguments.

FYI #7832 was added for this reason

> SRP 6a has been broken many times over and is still debatable.

Can you elaborate on this? SRP 3 (which we don't use) might have issues but I can't find any information on SRP 6a vulnerabilities or it being so much as "broken".

> Right, the salt is NOT known... until the server discloses it... to anyone who who merely asks for it...

However, this is exactly what the SRP specification says.

> Bottom line: I can connect to any MT server, keep note of admins' usernames, then simply connect back to the server with their username, collect all their salts, and run a dictionary attack just as if there was no SRP. [...]

In your situation you can use a dictionary to compute millions potential verifiers, but how do you tell which verifier matches the one the server has?
With my admittedly shallow knowledge of SRP I don't see how this is possible.

**Comment by fluxionary** [comment]
> If SRP is broken then that needs to be addressed for the benefit of all users. Adding a new auth method that won't be used won't help things

i've found an article that explains the issues w/ SRP more clearly, and suggests an alternative: https://blog.cryptographyengineering.com/should-you-use-srp/

>  I can connect to any MT server, keep note of admins' usernames, then simply connect back to the server with their username, collect all their salts, and run a dictionary attack just as if there was no SRP.

SRP isn't great, and sharing the salt is a mistake, and using sha256 vs. a cryptographic hash isn't great. but to run a dictionary attack like that, you'll also need the hash stored on the server, and if you've got access to that, the server probably has bigger issues. the server operator can easily brute-force a bunch of weak passwords, though, and gain access to user accounts on other servers if they re-use passwords. #10961 has some discussion about ways to require stronger passwords. 

while i'd personally love the results of this proposal, it's a lot of work, and i agree w/ @rubenwardy that it isn't suitable for most users. if @caffeinatedblocks writes the main PR, that's one thing, but the core devs will still have to maintain the code going forward. 

additionally, if a user loses their key, how would an admin restore access? currently (after validating that they are who they say they are), i just set the password to a short random string, /msg the user, and tell them to change it. i suppose this proposal implicitly assumes that password based access will still also be an option - i can delete the key they lost, and set a password. but then, as long as the account has a password, the key provides no additional security?

**Comment by sfan5** [comment]
FWIW I found out that our SRP implementation might be vulnerable to this (since it's a port of csrp): https://www.computest.nl/nl/knowledge-platform/blog/exploiting-two-buggy-srp-implementations/

I don't know if @est31 has time to investigate this, if not I'll attempt it myself sometime.

**Comment by rubenwardy** [comment]
SRP vulnerabilities should be a separate issue

**Comment by Desour** [comment]
> FWIW I found out that our SRP implementation might be vulnerable to this (since it's a port of csrp): https://www.computest.nl/nl/knowledge-platform/blog/exploiting-two-buggy-srp-implementations/

Mentioned commit that fixed it in csrp: https://github.com/cocagne/csrp/commit/7a1484e4b1c64b9e542612679aa67cbfe085a292
It looks like we don't have that bug:
https://github.com/minetest/minetest/blob/master/src/util/srp.cpp#L722
(And we probably never had it: https://github.com/est31/csrp-gmp/commit/e91130a97e25aab90394476ea2c151bdbdae948f)

(Why are we not using an unmodified lib for crypto functions, but a self-made thing?)

**Comment by est31** [comment]
@Desour yes I agree, csrp-gmp seems to not be affected. It was fixed in https://github.com/est31/csrp-gmp/commit/e91130a97e25aab90394476ea2c151bdbdae948f#diff-5144536c1faa90eaba1e97de54e59f36ab3555917f984537d58fbcddbffa01adR622 , in order to get it RFC 5054 compatible.

**Comment by est31** [comment]
@caffeinatedblocks

> I would like to add SSH public key authentication to minetest.

The authentication protocol introduced with SRP was laid out to support multiple authentication methods, if my memory serves me well. Adding other methods, like a public key based scheme, is possible.

I have been thinking about adding public key based schemes based on ed25519 ever since I've added SRP support, but I've always ended up not making concrete PRs, because I didn't think it would be worth it: it wouldn't be useful to 95% of users, but in order to be useful to the 5%, a large percentage of servers at least would have to enable ed25519 support at build time (I doubt you will get maintainers to accept something that adds a non-optional dependency for this thing that is not useful to 95% of users).

> also pave the way for minetest protocol encryption.

SRP is already a PAKE, that's all you need from an auth protocol to enable subsequent encryption.

> Because as soon as ANYONE attempts to connect using your username, the server sends them your salt! What the heck is the point of having the salt?

The point of a salt is mainly to prevent people from creating rainbow tables for all users, and finding out if a salt. See [this](https://security.stackexchange.com/a/131734) stackexchange answer. The job of a salt is to be unique. It's job is not to be secret. You are thinking of a pepper.

Yes, the attacker gains *minor* advantages from learning a salt, one is that the attacker knows that the user exists, and the other is that they can *prepare* a brute force attack by building a local rainbow table, so once they get the hash in the future, they can exploit it faster. None are real showstoppers though.

@Desour

> Why are we not using an unmodified lib for crypto functions, but a self-made thing?

Back in the day it was seen too involved to use openssl: maintainers would have rejected the adoption of SRP at all. The creation and inclusion of csrp-gmp was a compromise: had I not done it and insisted on using openssl or such, minetest would still have had the old protocol which was way worse. Sadly there was no self-contained library written in C or C++ that was as trustable as cSRP.

If you want to improve the situation, you could propose a build time option to use openssl's SRP implementation instead of the vendored lib. I would definitely be in favor of something like that. It seems that openssl's implementation is receiving [continued vetting from researchers](https://doi.org/10.1145/3460120.3484563).

@fluxionary 

> using sha256 vs. a cryptographic hash isn't great

sha256 *is* a cryptographic hash. What you mean is using a computationally hard/key stretching function. Here I must say that over the years since I've designed the protocol my views on the usefulness of key stretching have changed. Mostly because I realized how extremely horrible the passwords are that users adopt... Back then my argument was that even a stretched password will be easy to crack if it is "asdf", but we are talking about trying to attack hundreds, if not thousands of passwords at the same time. Such attacks are easier by the same factor that it's easier 

So yes, ideally minetest would switch to a new protocol that uses argon2 (or scrypt or bcrypt, something built on RandomX, etc). This could either be done via the continued use of SRP, together with the scheme plugged in to provide the "password", or via a different PAKE altogether. Switching to another PAKE would probably require going through the list of proposed PAKE schemes, finding out whether there are good well maintained implementations, whether the schemes themselves are the newest or also outdated, etc.

-----------

So as a summary, if you want to improve the authentication story of minetest I would suggest that minetest:

1. adds a build time option to use openssl's SRP mode (or some other big trusted library that supports SRP).
2. adopt key stretching
3. select a better (hopefully the best) PAKE, and then switch to it

You can also combine 2 and 3 and do it in one step. Encryption and stuff, while I support it, is entirely orthogonal.

**Comment by est31** [comment]
Hmm it seems that openssl is deprecating SRP: https://github.com/openssl/openssl/commit/76cb077f81c96e98d2f2042478c916ed2fdeda16, https://github.com/openssl/openssl/commit/13888e797c5a3193e91d71e5f5a196a2d68d266f . Might be better to ask them whether doing so is a good idea, before relying on it.

**Comment by caffeinatedblocks** [comment]
@sfan5 
> > Bottom line: I can connect to any MT server, keep note of admins' usernames, then simply connect back to the server with their username, collect all their salts, and run a dictionary attack just as if there was no SRP. [...]
> 
> In your situation you can use a dictionary to compute millions potential verifiers, but how do you tell which verifier matches the one the server has? With my admittedly shallow knowledge of SRP I don't see how this is possible.

The database stores the salt/verifier pair as follows: #1#<salt>#<verifier>

The verifier is generated as such:

N = AC6BDB41324A9A9BF166DE5E1389582FAF72B6651987EE07FC3192943DB56050A37329CBB4A099ED8193E0757767A13DD52312AB4B03310DCD7F48A9DA04FD50E8083969EDB767B0CF6095179A163AB3661A05FBD5FAAAE82918A9962F0B93B855F97993EC975EEAA80D740ADBF4FF747359D041D5C33EA71D281E446B14773BCA97B43A23FB801676BD207A436C6481F1D2B9078717461A5B9D32E688F87748544523B524B0D57D5EA77A2775D2ECFA032CFBDBF52FB3786160279004E57AE6AF874E7303CE53299CCC041C7BC308D82A5698F3A8D0C38271AE35F8E9DBFBB694B5C803D89F7AE435DE236D525F54759B65E372FCD68EF20FA7111F9E4AFF73
g = 2
s = 16 random bytes
k = sha256( N | g )
x = sha256( s | sha256( I | p ))
v = powmod(g, x, N)

Since, per SRP 6a spec, server returns salt upon initial authentication request for a particular username (I), it's relatively pointless. Since N, g, and s are all common and well-known, the "cryptographic hash" is essentially just a hashed salted password, similar to storing, for example:

password = "abc123"
salt = "xyz789"
stored password = #1#xyz789#<sha256(password | salt)>

If I know the salt, all I need to do is guess the password (common dictionary attack).

Salt does only one thing: it slows an attacker down. For example, if an application used the same salt for every password, one would be able to compute all possible hashes with the given salt and run a single dictionary attack against the entire database. With a different salt for each password, you'd have to run the entire dictionary attack individually against each known salt -- exponentially increasing the time required to do so.

The problem is that this theory is entirely baseless. Nobody cares about cracking every password. An attacker only wants high value accounts (those with most privileges), so they're only targeting a small subset anyway (at most, a few different salts). It's only helpful if the attacker only has a list of passwords and no way to know what privileges might be on the other side of cracking that password. Most people design their databases such that all the information you need is in one table though (minetest uses two: auth (player, password) and user_privileges (player, priv)) -- but that doesn't matter, because anyone can join a server and see who they admin is (or who the admins are). Once you crack that one password, the rest are trivial to reset anyway. Why would you want any password but the admin anyway?

In traditional plain-text password systems, the salt is protected, because you only need the password to authenticate (the same is true of SRP 6a). If I can get my hands on a copy of the database, I can crack all the passwords completely offline without ever so much as attempting to authenticate to the server itself. I have all the hashes and salts, so all I need to do is calculate hashes with those salts until I find a match, at which point I can log in on the first try (which is why some organizations enforce password rotation... hoping that if this happened, the user would have been forced to change their password by the time the cracker managed to find a match).

1. I doubt minetest server admins are rotating their passwords regularly
2. Minetest is offering up the salts like candy on Halloween -- to anyone who comes knocking
3. Knowing the salt, all I need to do is brute force dictionary attack the server (which minetest does not prevent in any way, and since we don't log authentication failures, admins wouldn't even know it's happening)
4. If I get my hands on a copy of the auth database, I don't even need to touch the server

Considering that most minetest servers are not run by professionals (in terms of systems administration or hosting), but rather people who are unaware of these risks, this is a huge security risk. Not because "oh no, someone could come and really grief my server!" but because admins have server privileges and an attacker could use minetest as an attack vector to gain access to the entire server.

Implications: imagine I go and hack a bunch of servers, execute arbitrary code, compromise the entire server, and start creating bot nets / spam relays / whatever. Now suddenly all the major hosts stop allowing/supporting Minetest because it poses a risk to their systems and reputation.

Just my 2¢ -- take it as you will.

**Comment by est31** [comment]
@caffeinatedblocks I have already explained above that your view of salts is not correct. They provide a specific, but real improvement, without them being meant to be secret. Many websites keep them secret, which certainly doesn't hurt, but SRP requires the salt to be shared. That doesn't make any more attacks possible than before. 

The knowledge of the salt doesn't help the attacker at all unless they also know the verifier, which does stay secret in minetest as it does with password-in-the-clear schemes. Websites that offer these clear login schemes very often store the salt together with the password hash. So usually a hack of the database gives the attackers both the hash and the salt.

The online attacks you describe below are not made easier with the adoption of salts.

The SRP protocol doesn't allow for peppers per se, although you could move the verification part to SGX enclaves/HSM modules if you really wanted. Then a hack of minetest server's user databases won't allow offline brute force attacks.

**Comment by Desour** [comment]
>Implications: imagine I go and hack a bunch of servers, execute arbitrary code, compromise the entire server, and start creating bot nets / spam relays / whatever. Now suddenly all the major hosts stop allowing/supporting Minetest because it poses a risk to their systems and reputation.

Just FYI, mods can't execute arbitrary code, they are sandboxed (unless they are "trusted", but that can't be set from within the sandbox).

---------

Getting back to topic, these requests are generally about auth methods that require more initial configuration, more work when migrating to a new device, and more knowledge, but are more comfortable in the long run, because you don't have to remember something for each server, and that are more secure, because the user won't lazily choose a weak password, or because of concerns about SRP's security.

As long as there is only one of these advanced auth methods, maintaining should be no too big issue, as the devs will be among the ones who use this feature.

However, we also want easily accessible good security, so that it's available to as many users as possible. Hence, something that is too complex to setup is not good.

I think I'd generally prefer some password manager thing (see also #1566) over a different auth protocol.
The biggest advantage here is that it's independent from what the server supports, so you can for example also use it on older servers.

**Comment by farooqkz** [comment]
An interesting and reasonable use of such a feature is for auth of server admins or mods. However a much less complex workaround is giving the admins/mods ssh access(not necessary with shell access) so that they could connect to server as localhost. Then admin stuff or risky tasks could be done only if the admin is connected through localhost. And mods can already check for a player's IP address.
