### ISSUE TITLE
Ghost entities

### ISSUE THREAD

**Issue by immagiov4** [minetest/minetest#13297]
##### Minetest version

```
5.6.1
```

##### OS / Hardware

Operating system: Ubuntu 22.04.2 LTS
CPU: Intel(R) Xeon(R) CPU E5-2630 v4 4core

##### Summary
Sometimes calling `get_children()` on a player returns entities with almost no methods except for `get_hp()` and `is_player()`. This is a problem because if you try to call any other method (such as `remove()`), the game crashes.

##### Steps to reproduce
I haven't found a way to reproduce this. What I know is that the "ghost" entities are not attached to the player anymore, because they disappear after I remove them (from within their on_step callback). May this bug be somewhat lag-related?

**Comment by sfan5** [comment]
> This is a problem because if you try to call any other method, the game crashes.

In what way? Error message?

**Comment by immagiov4** [comment]
> > > This is a problem because if you try to call any other method, the game crashes.
> > 
> > 
> > In what way? Error message?
> 
Yes, an "attempt to index a nil value" error (referring to a line like `entity:remove()`)

>  What do you mean? I thought removing them was not possible.
>  It would be good if you could describe what you are doing in details or post example code.

Sorry, I wasn't clear enough: I remove the entity but then, for some reason, the `get_children()` seems to think it's still there. I have no example code for this, 'cause I can't reproduce it in my local server. It happens on the AES server in the Fantasy Brawl minigame, but I have now way of knowing which entity caused it (because the "ghost" entities have no `get_luaentity()`). All I know is that I create an entity, attach it to the player and then it gets destroyed after x seconds in the on_step callback.

**Comment by sfan5** [comment]
> Yes, an "attempt to index a nil value" error (referring to a line like `entity:remove()`)

All entity references returned by the engine have the metatable set, so it's not possible that a method is nil. I would investigate other mods you have and check if they do some advanced things like operate with fake players.

From your description the following should reproduce it but I can indeed find nothing wrong:
```lua
-- use with /spawnentity
minetest.register_entity("test2:thing", {
	initial_properties = {
		visual = "cube",
		textures = {"smoke_puff.png", "smoke_puff.png", "smoke_puff.png",
			"smoke_puff.png", "smoke_puff.png", "smoke_puff.png"},
		static_save = false,
	},

	on_activate = function(self, staticdata, dtime_s)
		self.timer = 0
		self.object:set_attach(core.get_player_by_name("singleplayer"))
	end,

	on_step = function(self, dtime, moveresult)
		self.timer = self.timer + dtime
		if self.timer > 2 then
			local parent = self.object:get_attach()
			self.object:remove()

			print("we were attached to " .. tostring(parent))
			local children = parent:get_children()
			print("which has " .. #children .. " children now:")
			for _, obj in ipairs(children) do
				local line = "  " .. tostring(obj)
				if obj:get_hp() == nil then
					line = line .. " (broken ref)"
				end
				if obj == self.object then
					line = line .. " <- this is us"
				end
				print(line)
			end
		end
	end,
})
```

**Comment by immagiov4** [comment]
![immagine](https://user-images.githubusercontent.com/55757849/223536697-ba5d32a0-dadd-47b5-83f2-ea246891d3a7.png)
These are our mods, but I don't think any of them operate with fake players (our sure don't). What kind of advanced things could cause get_children to return entities with no methods? Moreover, when trying to dump the ghost entity (`dump(player:get_children()[entity_index])`), it prints the userdata metatable, don't know if that's useful (I don't know much about metatables). I'd also like to highlight that is not something that happens everytime, but maybe in a match out of three.

**Comment by fluxionary** [comment]
this may not be related, but on the your-land server, since 5.6.0 or 5.6.1, we've noticed that occasionally the results of `get_objects_inside_radius` and `get_objects_in_area` will be entities which are neither players, nor "live" entities (`get_luaentity()` returns `nil`). i was never able to reproduce the issue in a controlled environment. it caused several crashes, which were solved by adding appropriate checks to those functions.

**Comment by sfan5** [comment]
FWIW I think this should still be tagged "unconfirmed bug" because nobody has posted the actual code they used in connection with the bug, nor the actual error message.

**Comment by Zughy** [comment]
Happened to me as well and it doesn't seem related to children entities in particular https://gitlab.com/zughy-friends-minetest/block_league/-/issues/133

Basically someone hit an entity that wasn't really there anymore. `get_hp()` still existed ([a few lines before the 1st line of code linked in the issue, L196](https://gitlab.com/zughy-friends-minetest/weapons_lib/-/blob/be3311a7515a3e533cb71dba4147624c4c4da2a2/src/api/weapons.lua#L188)) but `get_luaentity()` didn't (the 2nd line of code). Like fluxionary, I don't know how to reproduce it in a controlled environment

**Comment by appgurueu** [comment]
"Attempt to index a nil value" on a line like `entity:remove()` means `entity` is `nil` (if `entity.remove` was `nil`, the error would be "attempt to *call* a nil value"); either the object has been invalidated, or it is a player.

I don't think this makes much sense, but we return a HP of 1 (!) for invalid entities: https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_object.cpp#L248-L252

We should probably deprecate this behavior.

A check like `obj:get_hp() > 0` is probably not very helpful. It only excludes dead players. It may give you invalid entities.

I believe `is_player` will simply return `false` for invalid entities: https://github.com/minetest/minetest/blob/fe6da3a16bd2d284085d35e450f2896b460b252b/src/script/lua_api/l_object.cpp#L848

I think this once again demonstrates how much of a footgun invalid object refs are, hence is possibly related to https://github.com/minetest/minetest/issues/14687

> this may not be related, but on the your-land server, since 5.6.0 or 5.6.1, we've noticed that occasionally the results of `get_objects_inside_radius` and `get_objects_in_area` will be entities which are neither players, nor "live" entities (`get_luaentity()` returns `nil`).

This sounds like invalid object refs. See the linked issue and also this [MTG issue](https://github.com/minetest/minetest_game/issues/3120#issuecomment-2127894697). To sum it up: *While* you are iterating your objects and doing something to them (say, punching them), other objects may be invalidated. A classic example would be blowing up an entity with attached entities. The parent may kill its children, leaving you with invalid object refs.

This issue is not fixable without changing the API or adding a new API: These functions return lists. They can't remove objects from these lists after the fact (okay, technically they could, but that would be a potentially inefficient mess). A proper design requires an iterator which skips invalidated objects.

**Comment by appgurueu** [comment]
Tagging this possible close as outlined in https://github.com/minetest/minetest/pull/14769#issuecomment-2184078785
