### ISSUE TITLE
Whitelist curated serverlist as a solution to needed serverlist moderation

### ISSUE THREAD

**Issue by MisterE123** [minetest/minetest#13326]
## Problem

So, particular pressing server-list issues came up, read here: https://irc.minetest.net/minetest/2023-03-14#i_6063157

Basically, the serverlist is open to any server, and the time has come when we may need to ban particular servers from the list.

The problem is that if we ban by IP or by keyword, the bans will be ineffective and easy to circumvent, and in the case of keywords, will create false positives as well as being easy to circumvent with pseudonyms.

## Solutions

A default, white-listed, serverlist curated from content database.

For the Minetest Engine, that will require support in the main menu.

The idea is to have two serverlists: a curated one and an uncurated one. The uncurated one is disabled in Android and other stores. It is also hidden by default in the desktop release but is easy to enable with a checkbox in the settings tab.

The Minetest client will support multiple serverlists, which will be listed in minetest.conf
All enabled serverlists will be merged in the join game tab

On android, where the uncurated list is not provided, it will still be possible to access the uncurated list by typing in the address of the list into the setting for it.

## Alternatives

Do nothing -- I think that's a bad idea; the kind of stuff linked should not be presented to kids, and this suggestion adds enough of a moral and legal barrier.

Blacklisting:
Ban by IP - Easy to circumvent
Ban by keyword - Easy to circumvent, false positives

Only host a curated serverlist <- that would be ill-recieved by the community and be anti-freedom

## Additional context

"Its parents responsibility" <- yes, and it still is. This just lessens the burden.

"its been fine until now" <- yes, until now our community was small enough that it wasn't necessary. Maybe it's still not necessary. It will be necessary at some point, probably soonish.

BTW, this gives the opportunity to provide a better experience to first-timers. A curated serverlist could provide screenshots, since its already integrated to content database

The white-listing process for the curated list will mirror mod curation on CDB.

As pointed out in the IRC thread it is inconsistent to curate mods/games but not the serverlist.

I will leave it to devs to create an issue on content database and the serverlist for implementation if they desire.

Important to note: the problem we need to solve is not that there is a server that does this stuff, we seriously cant, and probably shouldn't, control that (freedom and whatever). The problem is that it is specifically advertising it on the server list, which is sure to attract teenagers. That is a problem we need to deal with.

**Comment by Wuzzy2** [comment]
:-1: This will effectively ban every server by default then. This is an extreme measure and will make the server list very small (unless you approve everything anyway). And what exactly do servers have to prove to the admins to show they're "worthy" of being serverlisted again?

Do you have any formal rules to suggest? Because right now, there does not seem to be a clear rule, so I'm afraid decisions will be arbitrary, potentially making many server operators angry because they feel they have been punished for no reason. Yes, delisting the servers from the server list WILL feel like a punishment, even if you don't mean it that way. Keep that in mind.

Also, who is going to do the hard work of reviewing servers all the time? The one poor soul who is willing to do this boring job will clearly not have time or willpower to review every server every day but servers come and go quickly. This will likely nuke the whole server list because there is no way you will manage to review every server and keep everything up-to-date without getting bored by this job after 5 minutes. And we have so many servers. A whitelist means there will be effectively only a small list of "elite servers" left and it is extremely hard as a new server to gain a foothold. Not because you violated any rule. But because the reviewers had no time for you.

If the reviews of servers go as fast as the reviews for the "Mod Releases" thread, then the server list will be empty for months. :D

The question of who will do the constant review work is absolutely crucial but I have not seen an answer to that. So I am going to assume the answer is "nobody" (or almost nobody).

Also, how do you justify the discrimination against Android users, exactly? Is this a Google rule? If yes, which one?

There are too many unknowns in this proposal and I am extremely skeptical. This sounds like a non-starter to me.

I'm not against server bans in general (like, when some server does a phishing attack or attempts spam/flood), but I am against banning all servers by default.

**Comment by MisterE123** [comment]
@Wuzzy2 
To be clear, there will be two server lists.
One that is curated, the other not. Typically, servers start out on the uncurated list.

To get on the curated list, you apply on Content Database.

The formal rules are content database's inclusion policy as it stands and as it is applicable to servers.

The criteria for being accepted is "not obviously violating the policy". I'm not going to suggest how much attention to detail should be given in the review (that is for others to do), but it should be much easier than mod review since there are no licenses to check. It could be as simple as reviewing the description, or as complicated as logging on and checking it out (that's too much IMO)

Then if there are problems reported to staff, the staff can review it on a case-by-case basis.

@GoodClover I will point out that you suggest that "Servers should have to report if they're age-restricted/NSFW/whatever" ... that requires a punishment such as banning if they do not. We are back to the original problem that blacklist bans are inherently ineffective. Getting a new VPS is easy for changing IP's. Banning someone will inherently make them want to thwart the ban; thwarting it should more effort than is reasonable.

Whitlisting a curated list in addition to a normal list sidesteps the issue completely.

**Comment by rubenwardy** [comment]
It might be better to have published rules for the current server list, and labels for things like moderation level and content warnings

**Comment by GoodClover** [comment]
The server that sparked this's owner has said (on IRC):
> Look i dont wanna make any enemies. i think some kind of age rating system for servers in the server list would be good. and i would use it.
> what i mean by "don't wanna make enemies" is that if the decision is made to blacklist my server from the minetest server list, i will make no attempt to circumvent it. but i think a better solution is some kind of server flag and/or a clear set of rules for servers on the list to adhere to. If a rule is made prohibiting all servers with adult content, i will voluntarily remove my server from the list.

They are looking at adding an in-game age verification of some kind.
I have requested they comment here.

**Comment by GoodClover** [comment]
@MisterE123 I do not maintain anything like a server-list, however I suspect curating a while list would be more work than bonking an IP every now and then?
I'm all for curated lists, but not by default as the central one.
