### ISSUE TITLE
Chest items bug

### ISSUE THREAD

**Issue by PavanLuca** [minetest/minetest#13387]
##### Minetest version
```
5.6.1, flatpak version
```

##### OS / Hardware
Operating system: Zorin OS Core
CPU: AMD® V140

##### Summary
When dragging an item from a chest into a user's object that has a count of 2 or more items on that slot the game displays that count on the chest item. Perhaps that count is a fake, you can't really get that count amount, otherwise this would be a bad cheat.
![Schermata da 2023-03-25 02-59-29](https://user-images.githubusercontent.com/123581658/230111919-497403bb-3a94-4d00-9962-4cb957a13000.png)
![Schermata da 2023-03-25 02-59-40](https://user-images.githubusercontent.com/123581658/230111930-66cd784c-706d-4add-8b23-f860162d5712.png)

##### Steps to reproduce
Move a single object from a chest to an item with a total count on your inventory. Maybe use clicks rather than drag and drop.

**Comment by Zughy** [comment]
Both @wsor4035 and I have tried to reproduce the bug with no luck. It might be a bug related to CTF mode (the server you're playing in), closing

**Comment by fluxionary** [comment]
i can reproduce this. this happens when the inventory move is refused. 

get e.g. a shared chest from sokomine's chesttools, have one player put the chest in their own protected area (e.g. areas mod), then have another (non-privileged) player come and drag an item from their inventory onto an item in the chest. 
![image](https://user-images.githubusercontent.com/25628292/230133693-9a5106da-2dca-4299-82bd-cce7d52873f4.png)
![image](https://user-images.githubusercontent.com/25628292/230133788-a424f2d4-1ded-4d57-9201-58ab20a253c0.png)

**Comment by PavanLuca** [comment]
So can this be fixed by Minetest team or what else? I know that I can't swap the 2 items as the chest is protected but the game could at least place the item on my inventory and then place the other item under the cursor control to replace it somewhere else inside my inventory, so not swapping from my inventory to the protected chest.
