### ISSUE TITLE
Modder control over fog.

### ISSUE THREAD

**Issue by mecha-moonboy** [minetest/minetest#13421]
I have been trying to take beautiful screenshots of some cave mods, and I need to be in fly mode with noclip in order to get fog so that I can see the size and shape of caves. Otherwise, the illumination from generated blocks is flat and not very appealing. I cannot achieve the effect of fog in survival.

It would be excellent if there were methods/properties that allowed modders control over fog color and strength. This would also allow more creativity for biome colors and themes, themes at different y levels, and overall, more control over the feel of the game.

With fog in noclip fly mode (not ideal color or strength, but I take what I can get):

![screenshot_20230411_185811](https://user-images.githubusercontent.com/42070776/231340889-aa01f3d7-3203-43fe-b408-417f64a0b2dd.png)

Without fog, what it would look like in survival:

![screenshot_20230411_190123](https://user-images.githubusercontent.com/42070776/231340983-1453e1cd-fd55-4c9f-a01e-e3d7f6094a6a.png)

**Comment by Desour** [comment]
Related (duplicate?): #8142

**Comment by lhofhansl** [comment]
I think we should fix this via the sky api. It already has fog-tint and sky color settings.
We can add both fog color and fog distance (and fog start while we're at it) to it.

**Comment by lhofhansl** [comment]
@sfan5 Following up on the discussion on IRC:
- fine to use the sky api
- we'll allow setting the fog distance, fog color, and fog start ( range [0-1) )
- if the server sets a fog distance the following needs to happen:
The client needs to disable range_all (and disabling fog?)
The client can still set a smaller viewing_range than what the server request (since that is a performance thing).
The client also needs to send this the server-set distance as its wanted range to avoid sending unnecessary blocks.

**Comment by lhofhansl** [comment]
I'll do a PR as soon as I find some time.
