### ISSUE TITLE
on_dieplayer and on_hpchange reasons

### ISSUE THREAD

**Issue by bas080** [minetest/minetest#1342]
Wouldn't it be nice to have a reason given each time a player is damaged, e.g.
```
player:set_hp(damage, reason)

player:punch(puncher, time_from_last_punch, tool_capabilities, direction, reason)

minetest.register_on_player_hpchange(function(player, hp_change, reason)
```
... where 'reason' is a simple text string containing something like "lava", "fire", "mob_sandmonster", "ethereal:crystal_spike" etc.

This would come in very handy for award or death messages or even stats on a players game :)

-------------------------------

Instead of just a player the on_dieplayer should also pass the node or entitiy that killed it as a parameter.

A suggestion:

```
minetest.register_on_dieplayer(params                                                                              
  print(params.player) --the player that got killed
  print(params.killer) --returns the player that killed him/her
  print(params.node) --retruns the node that inflicted the final blow
end)
```

This might require for the set_hp(hp) function to also ask for extra information on the reason for the hp reduction.

**Comment by indriApollo** [comment]
I could really use such feature for an upcoming arena mod

**Comment by nerzhul** [comment]
@ShadowNinja seems a good idea !

**Comment by Wuzzy2** [comment]
This should include all possible ways to damage a player. It makes sense to include these parameters in the damage callback as well, because it's similar.
And there should be no way for a player to die which doesn't “send” the relevant data to the callback.

Possible damage/death sources:
- Punch from entity (including other player)
- Using a Lua function, such as `set_hp(0)`
- Fall damage
- Drowning
- `damage_per_second`
- (post more if I forgot something)

**Comment by raymoo** [comment]
If `set_hp` always gives a reason then it should have a required reason argument for the caller, because it's not that useful to just know that the HP was set.

**Comment by Wuzzy2** [comment]
Well, for starters, the fact that a Lua function was used is a start to distinguish from hardcoded sources such as fall damage.
We can't just make adding a reason into `set_hp` mandatory because this would break pretty much everything.
As I already stated in #5971, if we add a reason argument, we should immediately standardize the most common death causes, otherwise it will quickly degrade into an unholy mess.

**Comment by raymoo** [comment]
Maybe breaking compatibility for this would be an option since we are going to version 0.5+?

**Comment by paramat** [comment]
We're not breaking API compatibility, but maybe this can be done without an API breakage.

**Comment by raymoo** [comment]
State this in the other issue, but damage reasons should be structured and <b>not</b> just a simple string. A table with a reason type and extra data specific to each type would be useful.
