### ISSUE TITLE
Custom auth handler - player login - missing password entry

### ISSUE THREAD

**Issue by RepComm** [minetest/minetest#13544]
https://github.com/minetest/minetest/blob/a8ec6092e2f433e1904a50dd6c1d4349180a98bb/src/script/cpp_api/s_server.cpp#L37

Hi, I am working on a [pocketbase](https://pocketbase.io) backend for minetest authentication.

The password the user inputs, referenced in the source link above, is not passed to lua, and cannot be used with a custom auth handler.

The proper use for pocketbase is to not expose passwords of users, even to admin accounts, and therefor cannot be queried by pocketbase API calls to satisfy minetest's weird edge case.

I will be modifying the Cpp call to get_auth by passing in the password as an additional argument, which should not affect existing auth handlers.

A work around I considered is to just allow the player to join with a blank password, then use formspecs to force the player to input a password that gets sent to pocketbase that way, but this is a large amount of work that I'd like to avoid.

Maybe if my solution doesn't get merged at some point, I'll make a work around for folks who don't want to use a minetest fork / build themselves, but for now I'll try fixing in a pull request.

**Comment by rubenwardy** [comment]
This is intentional - Minetest uses srp to authenticate without sending the plain text password. Remember that minetest is unencrypted, sending the plaintext password is a bad idea

The auth handler API is more for storing auth data and handing privileges. It's not for implementing custom auth methods. It would be nice to make this possible, we could add a new auth method that opens up a web URL on the client and does something like OAuth, this would be very flexible for a lot of use cases

**Comment by RepComm** [comment]
I'll have to settle for a player privileges update based on querying pocketbase on player join.
Not the solution I wanted, but I guess it works for now.

The link to SRP says that it does not require another backend, but it should probably be worded as 'is incompatible with any other backend'.

Thanks for clearing this up. I'll close this for now.

**Comment by rubenwardy** [comment]
Swear there's an issue for custom auth already, all I can find is one for LDAP: #8858
