### ISSUE TITLE
Some drawtypes cause z-fighting underwater since 5.8.0-dev

### ISSUE THREAD

**Issue by Desour** [minetest/minetest#13569]
##### Minetest version
```
Minetest 5.8.0-dev-1b51ff333 (Linux)
Using Irrlicht 1.9.0mt11
```
Does not happen with:
```
Minetest 5.7.0 (Linux)
Using Irrlicht 1.9.0mt10
```

Bisected, issue exists since: 35929d27e3a93085c3a27180c1805711dcfe95d5
cc @numberZero 

##### OS / Hardware

GPU model: AMD vega 8
OpenGL version: OpenGL 4.6

##### Summary

Nodes with drawtype `glasslike`, `glasslike_framed`, `allfaces`, and possibly more z-fight when placed underwater (in a pool of liquid nodes (tested with liquid source nodes)).
This does not happen in 5.7.0.

(This was originally reported in #13499 by @runsy. Reopened because issue template was not used.)

##### Steps to reproduce

* Start devtest.
* Get a `glasslike` node (or whatever you want to test) from the chest of everything.
* Place it underwater.
* Look at it.
* Do the same in 5.7.0.

**Comment by runsy** [comment]
Not only flowing liquids.

![imagen](https://github.com/minetest/minetest/assets/13217027/48254ae6-6e29-4b0b-8f11-81108cf28670)
![imagen](https://github.com/minetest/minetest/assets/13217027/766b2573-486c-4795-85a3-d5f83902005a)

This only-one-face nodebox shows the same issue.

**Comment by runsy** [comment]
The vine is defined here:

minetest.register_node(creeper_name, {
		description = S(def.desc),
		drawtype = "nodebox",
		walkable = false,
		paramtype = "light",
		paramtype2 = "facedir",
		tiles = {tile},
		inventory_image = inventory_image,
		wield_image = def.wield_image or def.inventory_image or def.tile,
		use_texture_alpha = "clip",
		node_box = node_box,
		groups = {
			snappy = 2, flammable = 3, oddly_breakable_by_hand = 3, choppy = 2, carpet = 1, leafdecay = 3, leaves = 1,
		},
		sounds = sound.leaves()
	})

**Comment by NathanSalapat** [comment]
Your definition doesn't help us runsy, as you haven't included what the tiles or node_box tables are.

**Comment by runsy** [comment]
> Your definition doesn't help us runsy, as you haven't included what the tiles or node_box tables are.

It is a flat pane:

helper.nodebox.flat_b = {
	type = "fixed",
	fixed = {
		{-0.5, -0.5, 0.5, 0.5, 0.5, 0.5}, -- Flat Plane Back
	},
}

**Comment by lhofhansl** [comment]
@numberZero Any ideas?

**Comment by SmallJoker** [comment]
The provided example by runsy uses a nodebox which cannot be solved easily because Minetest currently has to draw all faces in case the nodebox has an opening (see-though). Hence that particular issue cannot be fixed yet.

However, by enabling backface culling this scenario no longer causes z-fighting:
![glass vs glass under water](https://github.com/minetest/minetest/assets/1497498/2e1b5f6f-6dea-40c0-afb9-8450004a7be3)

However, flowing liquid does yet not support backface culling. Either you get z-fighting (left) or incorrect colorizing (right), see variable `draw_liquid_bottom`

![z fightning vs seethough](https://github.com/minetest/minetest/assets/1497498/6228f562-fe79-4c5a-85a3-f04ef9b2846e)

I did yet not check how 5.7.0 looked like but similar issues might occur there as well.

Diff used for testing:
```diff
diff --git a/src/client/content_mapblock.cpp b/src/client/content_mapblock.cpp
index 0274c767b..a9afb76f6 100644
--- a/src/client/content_mapblock.cpp
+++ b/src/client/content_mapblock.cpp
@@ -461,7 +461,7 @@ void MapblockMeshGenerator::drawSolidNode()
                                        continue;
                                if (n2 == nodedef->getId(f->liquid_alternative_source))
                                        continue;
-                               backface_culling = f2.solidness >= 1;
+                               backface_culling = true;
                        }
                }
                faces |= 1 << face;
diff --git a/src/nodedef.cpp b/src/nodedef.cpp
index 383edae36..55e154596 100644
--- a/src/nodedef.cpp
+++ b/src/nodedef.cpp
@@ -858,21 +858,21 @@ void ContentFeatures::updateTextures(ITextureSource *tsrc, IShaderSource *shdsrc
                is_liquid = true;
                break;
        case NDT_FLOWINGLIQUID:
-               solidness = 0;
+               solidness = 1;
                if (tsettings.opaque_water)
                        alpha = ALPHAMODE_OPAQUE;
                is_liquid = true;
                break;
        case NDT_GLASSLIKE:
-               solidness = 0;
+               solidness = 1;
                visual_solidness = 1;
                break;
        case NDT_GLASSLIKE_FRAMED:
-               solidness = 0;
+               solidness = 1;
                visual_solidness = 1;
                break;
        case NDT_GLASSLIKE_FRAMED_OPTIONAL:
-               solidness = 0;
+               solidness = 1;
                visual_solidness = 1;
                drawtype = tsettings.connected_glass ? NDT_GLASSLIKE_FRAMED : NDT_GLASSLIKE;
                break;
```

On a side note, `nodedef->getId(f->liquid_alternative_flowing)` should probably be cached.

**Comment by Desour** [comment]
For comparison:
5.7.0:
![screenshot_20230610_001939](https://github.com/minetest/minetest/assets/7613443/c72b8280-40b0-40db-9ed7-b3db28477ef2)
master:
![screenshot_20230610_002017](https://github.com/minetest/minetest/assets/7613443/90397fc8-0f94-4836-b9be-1a68f6efd34c)

And here another screenshot (150% nodebox from devtest, a flat nodebox as described by runsy, allfaces but without backface culling):
![screenshot_20230610_003554](https://github.com/minetest/minetest/assets/7613443/9ca810d8-ea07-437f-96ec-64914b1d4ca8)
It looks the same in 5.7.0 and master. I can not reproduce a regression with the flat nodebox.

---- 


Could we maybe move all the faces of full nodes an eps inwards?

**Comment by runsy** [comment]
To check the flat nodebox dissapearing iuin certain angles:

fixed = {
	{-0.5, -0.5, 0.0, 0.5, 0.5, 0.0}, -- Flat Plane Vertical
},

![floraz_jungle_creeper](https://github.com/minetest/minetest/assets/13217027/c440d529-08c4-48d1-9849-8d58d814bd4b)

**Comment by runsy** [comment]
Well, i have solved the flat pane use changing from "clip" to "blend":

use_texture_alpha = "blend",

**Comment by numberZero** [comment]
The underlying issue is well-known, it is #9276. Sorry that my PR exaggerated it, need to force some backface culling probably, like it was in FastFaces.

> Could we maybe move all the faces of full nodes an eps inwards?

No, that would cause other problems. What we could is to use [glPolygonOffset](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glPolygonOffset.xhtml) as was suggested in #9276.

**Comment by Desour** [comment]
> The underlying issue is well-known, it is #9276.

Just to make clear: This issue also happens without waving liquids.

> > Could we maybe move all the faces of full nodes an eps inwards?
> 
> No, that would cause other problems.

Just out of interest, what are these problems? :eyes:

**Comment by lhofhansl** [comment]
So fast-faces had some logic where within a scan column it found adjacent "similarly transparent" nodes and would cull those backfaces. That would not work between these columns, and hence just eliminate some of the z-fighting only... Assuming I understand the old code correctly.

Getting rid of fast-faces is still the right thing, IMHO. Not sure how to fix it if we do not want to search the space of adjacent transparent nodes to find backfaces that could be culled.

Or ... maybe I misunderstand :)

**Comment by numberZero** [comment]
> This issue also happens without waving liquids.

Like https://github.com/minetest/minetest/pull/6903#issuecomment-356716195? That should’ve been fixed... but isn’t.
One problem is that overlaid quads are split across different diagonals. Fixing that fixes *most* z-fighting, but not all. I suspect the vertex coordinates aren’t exact integers like they should be.

> > > Could we maybe move all the faces of full nodes an eps inwards?
> > 
> > 
> > No, that would cause other problems.
> 
> Just out of interest, what are these problems? :eyes:

I should’ve written “may”. It may cause gaps at edges due to rounding errors. Not a major problem, FastFaces had it all along. But there may be something else I simply don’t remember right now.

> Not sure how to fix it if we do not want to search the space of adjacent transparent nodes to find backfaces that could be culled.

To my understanding, search space remains the same: it has to check for adjacent solid nodes already. Only checks will change a bit.

**Comment by Desour** [comment]
> > This issue also happens without waving liquids.
> 
> Like [#6903 (comment)](https://github.com/minetest/minetest/pull/6903#issuecomment-356716195)? That should’ve been fixed... but isn’t. One problem is that overlaid quads are split across different diagonals. Fixing that fixes _most_ z-fighting, but not all. I suspect the vertex coordinates aren’t exact integers like they should be.

Umm, I don't usually see the glitches shown in those screenshots.

> It may cause gaps at edges due to rounding errors.

Oh right, I forgot that inner edges exist. x)
