### ISSUE TITLE
Floats In Texture Modifiers

### ISSUE THREAD

**Issue by FossFanatic** [minetest/minetest#13706]
## Problem

Floats don't work in texture modifiers. If you try to use floats in a texture modifier, it automatically gets rounded down to the nearest integer number instead.

## Solutions

Allow floats in texture modifiers, as this would allow for much more flexibility when it comes to texturing things.

## Additional context

For instance, I want to use `[sheet` to grab a texture which is 182x22 from an image which is 256x256.
To do so I just simply have to do `image.png^[sheet:1.4065x11.6363:0,0`, but since the floats automatically get rounded down, the result instead is `image.png^[sheet:1x11:0,0`, which ruins the image.

**Comment by appgurueu** [comment]
Allowing only integers for pixel coordinates and texture dimensions is very sane. There are no "half pixels" in a texture. `[sheet` exists to allow you to retrieve tiles from tilesheets; it should not be made to support floats just to enable a dirty hack you came up with.

I think we should have better support for percentages relative to texture dimensions however to make resolution-agnostic texture modifier usage easier. Currently you either have to (1) resize everything to a certain resolution (say, 512²), then do your operations on that resolution, or (2) restrict yourself to texture modifiers which support percentages, such as `[lowpart`.

Which brings me to your "use case": `[sheet` is the wrong tool for the job. You don't want to extract a tile from a tilesheet, you want to crop an image. This can be achieved (for the fixed resolutions given in your post) using `[combine:182x22:0,0=image.png`. If you want percentages, you could use `[lowpart` to crop vertically, then rotate and use `[lowpart` again to crop horizontally, then rotate back.

You might want to take a look at [these texmod docs](https://github.com/minetest/minetest_docs/blob/master/doc/texture_modifiers.adoc). Bear in mind that they are slightly outdated since the last texmod PR got merged though.
