### ISSUE TITLE
`air_equivalent` is undocumented

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#13722]
While looking through the `builtin` sources, I discovered the air node has a special field `air_equivalent = true`.

I don't know why it's there and this field is entirely undocumented. What's more confusing, it does not seem to be used anywhere in the code, neither in builtin nor C++ nor Minetest Game.

What is the purpose of this? If there is any purpose, I request that it'll be mentioned in `lua_api.md`.

**Comment by sfan5** [comment]
I know this used to be a node property back in (at least) 0.3.
If it's not used it should be removed.

**Comment by Zughy** [comment]
@rollerozxa this is my favourite part  

![image](https://github.com/minetest/minetest/assets/63455151/cced7ee1-6b42-41ba-85e9-56d068b39291)

I think it's safe to be removed if it doesn't sort any effect

**Comment by Wuzzy2** [comment]
I will not shed a single tear if this is removed. It was never documented so it's OK. If mods depend on undocumented behavior, it's their fault when things break.

**Comment by erlehmann** [comment]
This parameter was used internally to see if grass could grow underneath a node, i.e. if it propagated light.

Removing a node property that has been truthy for a long time without figuring out the consequences seems either really stupid or really careless to me (choose your poison).

**Comment by rollerozxa** [comment]
Since the previous zipgrep had expired, here's a new one, archived as to not expire: https://web.archive.org/web/20230911164208if_/https://content.minetest.net/zipgrep/501df1d6-4355-4fd8-8afb-947ea023aa6e/

Removing this might break NodeCore and some other packages if they don't get fixed.

**Comment by erlehmann** [comment]
> Removing this might break NodeCore and some other packages if they don't get fixed.

What “fix” do you have in mind? This property seems actually useful for me if you want to handle air, ignore and similar nodes correctly as, well ”air equivalent” in a game.

**Comment by rollerozxa** [comment]
> > Removing this might break NodeCore and some other packages if they don't get fixed.
> 
> What “fix” do you have in mind? This property seems actually useful for me if you want to handle air, ignore and similar nodes correctly as, well ”air equivalent” in a game.

Well I was thinking checking for an airlike drawtype, but that would drag in other invisible nodes you might not want to be treated as an air equivalent so... Might be best to keep it anyways.

**Comment by erlehmann** [comment]
> Well I was thinking checking for an airlike drawtype

IMO this is most likely the wrong approach – think about it for a moment from a game/mod dev perspective …

**Comment by srifqi** [comment]
The `air_equivalent` was first added in 4a6b9a6ac1b07239474bce8d3ebf772ce75e862e (May 2011) for the engine and in d2eed169aed84c8e3860912dfcd8da15db334c79 (November 2011) for the `builtin`.

It was removed in c1479a273266709d6d0775c690dce31a7a430aa5 (November 2011). The `light_propagates` and `isLiquid()` properties were used instead:

```
air_equivalent = light_propagates AND (NOT isLiquid())
```

(Note: There is `light_propagates`, but also there is `sunlight_propagates`.)

I am guessing that those two lines were missed when the `air_equivalent` was being removed since the time between d2eed169aed84c8e3860912dfcd8da15db334c79 and c1479a273266709d6d0775c690dce31a7a430aa5 is only a few hours.

-------

Choices:
- Remove it (since it is undocumented), but also announce the removal in the next release.
- Mark it as deprecated and add a way to get a node's light propagation property and its liquid-ness in Lua.
- Document it as a Lua-spesific property (not used in the engine).

**Comment by rubenwardy** [comment]
That makes sense, I was wondering if it was related to light/sunlight propagates

**Comment by erlehmann** [comment]
IMO the easiest way to have no breakage is to leave it in and document it, ideally based on what mods actually do with it.

> Mark it as deprecated and add a way to get a node's light propagation property and its liquid-ness in Lua.

What would be the actual advantage here of having every mod to build their `air_equvalent` themselves?

**Comment by sfan5** [comment]
> So far, both “check for air and ignore” [...] seem to be obvious, but wrong answers to me.

Why?
It originally existed to declare under which nodes grass grows, this behavior is no more and it doesn't make sense for a game engine to dictate this.
Every modder who used this property was probably under the impression that it did something else.
The easiest way to keep the old behavior (regardless of whether it was used correctly or not) is to explicitly check for air or ignore.

**Comment by erlehmann** [comment]
> > So far, both “check for air and ignore” [...] seem to be obvious, but wrong answers to me.
> 
> Why?

Mods seem to set `air_equivalent` for their own nodes. They do not set it for air or ignore – likely *because it was already set*.

Piranesi restoration project for example does this: https://gitlab.com/search?search=air_equivalent&nav_source=navbar&project_id=41386041&group_id=128051&search_code=true&repository_ref=master

> It originally existed to declare under which nodes grass grows, this behavior is no more and it doesn't make sense for a game engine to dictate this.

I full agree with you here.

> Every modder who used this property was probably under the impression that it did something else.

Sounds plausible, but I can not possibly know. Did you ask modders who used it what they used it for?

IIRC @Warr1024 elaborated on IRC a bit on using `air_equivalent` in NodeCore, what did you think about that?

> The easiest way to keep the old behavior (regardless of whether it was used correctly or not) is to explicitly check for air or ignore.

This assumes that mods never set `air_equivalent` for their own nodes, which enough of them seem to do.

Since you came to a different conclusion than I did – at which mods did you look before deciding what to to?

**Comment by sfan5** [comment]
> This assumes that mods never set air_equivalent for their own nodes, which enough of them seem to do.
> Since you came to a different conclusion than I did – at which mods did you look before deciding what to to?

Zero.
If mods/games want to keep an informal standard for whatever `air_equivalent` is supposed to mean going that is their responsibility.
