### ISSUE TITLE
Dehardcode the zoom key and convert it into AUX2 or similar

### ISSUE THREAD

**Issue by immagiov4** [minetest/minetest#13763]
### Problem

Some games don't need zoom functionality, and, if they want, games can implement their own zoom method.

### Solutions

Dehardcode the zoom key and convert it into AUX2. See https://github.com/minetest/minetest/issues/13760#issuecomment-1694778281

### Alternatives

I can't think of any.

**Comment by jeremyshannon** [comment]
This would work perfectly for Exile's use case. That'd let me keep AUX1 as a modifier for  airboats and potentially other things

**Comment by Zughy** [comment]
I suggest F or R as a default aux2 key. Z is not that easy to hit in comparison.

R might have more sense for games where you need to reload

**Comment by appgurueu** [comment]
I don't see why we would need to get rid of the zoom key, breaking backwards compat.

Mods could implement zooming themselves given aux2, but you run into two problems:

* Lack of clientside logic makes it jankier than it has to be.
* Lack of convention will make many mods want to use aux2 - hence it can't be used exclusively for zooming.

There is an alternative which I think might realistically happen medium-term (though we should first get SDL done): Fully custom controls (not just "aux2"), see #12488.

**Comment by Zughy** [comment]
@appgurueu about point n°1, I use a custom zoom function (altering `set_fov()`) on my minigame when right-clicking whilst holding a sniper weapon, and I haven't noticed any janky behaviour in years. I can't say the same thing about raycasts :P

> I don't see why we would need to get rid of the zoom key, breaking backwards compat

The real issue is that we have a builtin key and function for zooming, due to Luanti origins. This also creates issues such as #13760 (and I guess #12951)

> There is an alternative which I think might realistically happen medium-term

Which means "at least one year, possibly two". We can't expect game devs to wait for such a long time for something that should be quintessential in an engine (custom keys), especially if we consider that this issue is two year-old, and it's not like people weren't complaining before that. Here we're asking for just one single additional key, basically what's also being asked in #11446.  

I'd like to put a bounty for an additional key because as a modder I feel limited; at the end I really don't care whether is on this one or the one I've last mentioned

**Comment by grorp** [comment]
I don't like the idea of adding aux2 (and potentially more auxes in the future). We don't need more keybinds with cryptic names and no consistent meaning, aux1 is already confusing enough.

If we add more auxes, we won't ever be able to get rid of them again because of backwards compatibility, even when a proper solution arrives.

Instead, we should allow games to add custom keybinds with meaning, with name and default key, re-bindable by the user (and eventually also including touchscreen support), as suggested in the issue referenced by appgurueu and also by rubenwardy in https://github.com/minetest/minetest/issues/11446#issuecomment-883458358.

I do however support removing the "zoom disabled" message, since that would make the zoom key more useful as a generic key short-term, and we already have it in the API anyway. You could also rename the zoom key to aux2, but what benefits would that even have at this point?

**Comment by medleymedley** [comment]
I'd settle for just the option to hide the zoom button on mobile in games where its not supported.
