### ISSUE TITLE
Bad tooltip position with real coordinates (formspec v6)

### ISSUE THREAD

**Issue by lua-rocks** [minetest/minetest#13777]
### Minetest version

```true
Minetest 5.7.0 (Linux)
Using Irrlicht 1.9.0mt10
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Operating system and version

Manjaro 23.0.0 Uranos

### Summary

I have a custom inventory background texture 390x230 pixels:

![inv3](https://github.com/minetest/minetest/assets/82697845/3739dbd4-3c08-462b-a996-049404b1c6a7)

When I use this formspec (with real coordinates) cursor is over the first letter of the tooltip and it's obstructing the description:

```
formspec_version[6]
size[390,230]
style_type[list;spacing=3,3;size=16,16]

listcolors[#00000000;#00000000]
bgcolor[#00000000;true]
background[0,0;0,0;inv3.png;true]

list[current_player;craft;138,43;3,3;]
list[current_player;craftpreview;233,62;1,1;]

list[current_player;main;119,135;8,3;8]
list[current_player;main;119,204;8,1;]
```

![inv-x1](https://github.com/minetest/minetest/assets/82697845/c339f91d-1f1a-42a8-8cb7-4659d903cbf9)

This issue can be fixed by dividing all the coordinates by 10 in the form spec, like this:

```
formspec_version[6]
size[39.0,23.0]
style_type[list;spacing=.3,.3;size=1.6,1.6]

listcolors[#00000000;#00000000]
bgcolor[#00000000;true]
background[0,0;0,0;inv3.png;true]

list[current_player;craft;13.8,4.3;3,3;]
list[current_player;craftpreview;23.3,6.2;1,1;]

list[current_player;main;11.9,13.5;8,3;8]
list[current_player;main;11.9,20.4;8,1;]
```

But then another problem arises: when resizing the window, the scaling of elements becomes imprecise, and they shift by a random number of pixels.

This shift isn't noticeable with just the background texture, but when I add image-buttons for inventory tabs and stretch the window, the tabs start dancing. This doesn't happen in the first case.

**Comment by lua-rocks** [comment]
You know, I've experimented with formspecs, and I've come to the conclusion that I have no idea how to make it pixel-perfect, regardless of the resolution or coordinate system: https://forum.minetest.net/viewtopic.php?f=6&t=29765

**Comment by lua-rocks** [comment]
Second case is not an issue anymore! But I still don't know, if it possible to fix tooltip position if size is too big.

**Comment by Desour** [comment]
Note that there was a bug with background elements, fixed since #13320. If you use such big formspec sizes as in your first formspec, that issue is probably rounded away.
(Normally one doesn't use that big formspec sizes, btw..)

Can reproduce. The tooltip offset position not scaling correctly is a bug.

**Comment by lua-rocks** [comment]
> Normally one doesn't use that big formspec sizes, btw..

I'm just trying to make a pixel-perfect GUI and copying the coordinates of all elements from the graphics editor instead of setting them by eye.

**Comment by rubenwardy** [comment]
No comment about the bug, but you should probably be using 9 slices for the background and buttons

**Comment by lua-rocks** [comment]
Thank you for the advice, @rubenwardy. I would do that for a proportional texture, but my textures have a fairly irregular shape. For example, the inventory is a bag with straps of varying lengths hanging from different sides. So, it's more convenient for me to use a regular texture.

In any case, it's no longer a problem for me. I've [already figured out](https://forum.minetest.net/viewtopic.php?f=6&t=29765) how to overlay images on the background with pixel-perfect precision 🙂.

**Comment by lua-rocks** [comment]
Update: actually, these artifacts are possible even with real sizes!

😭😭😭

![изображение](https://github.com/minetest/minetest/assets/82697845/8162c0a4-fb05-4f60-84e1-62c8f17fca2d)

**Comment by lua-rocks** [comment]
```
formspec_version[6]

size[240,160]
background[0,0;240,160;pixel-perfect-test-bg.png]
image[48,32;48,16;pixel-perfect-test-fg.png]
label[16,16;Edit me in realtime!]
```

![изображение](https://github.com/minetest/minetest/assets/82697845/7a2aa088-5e2c-4ab2-98c2-620f19f32167)

**Comment by lua-rocks** [comment]
`style_type[label;font_size=64]` doesn't help.

**Comment by Skamiz** [comment]
Pretty sure that the tooltip issue is due to specifying your formspec sizes in pixels rather then inventory slots as you are supposed to do.
Basically, you are making your formspecs extremely large and when minetest squeezes them back down, so they fit on your screen, the tooltip position gets somewhat offset. Is what I am guessing is happening, since I never had this issue working with real coordinate formspecs.

Unrelated notes about pixel perfection:
As a first step, you might need to adjust your 'gui_scaling' setting. At least for me, the default scaling made inventory slots 57 pixels across my screen which makes it impossible to scale up a lower resolution texture and have everything aligned perfectly.
Personally I had to set it to 1.123, so that inventory slots would be 64 pixels on my screen. That way, if I make my textures to display at the same resolution as an item in an inventory list, each texture pixel will correspond exactly to 4x4 screen pixels, and nothing is being squished or stretched by unprecise scaling.

Secondly, about your shown inventory background texture. The space between slots of an inventory list are precisely one quarter the size of the slots, so when your slots are 16x16 pixels, then the border between them must be 4 pixels wide, instead of 3.

**Comment by lua-rocks** [comment]
@Skamiz Thank you for the advice. Tomorrow, I'll experiment with `gui_scaling`. But are you sure that changing this setting is a universal solution and won't lead to different results on different screens? I still have a lot of doubts about the accuracy of your method. I'm afraid that there might not be a perfect method at all.

**Comment by rubenwardy** [comment]
Mods/games shouldn't change GUI scaling, that's a setting for users

> Thank you for the advice, @rubenwardy. I would do that for a proportional texture, but my textures have a fairly irregular shape. For example, the inventory is a bag with straps of varying lengths hanging from different sides. So, it's more convenient for me to use a regular texture.

You could split your background into multiple textures - for example, one for each strap and such. This may be less convenient but would scale better

**Comment by Skamiz** [comment]
oh, a misunderstanding, I only meant that you should change the scaling for yourself, so that textures are scaled accurately without any squishing or stretching on your screen, and you can take screenshots and manually count pixels yourself in your image editor of choice, if necessary.

It's pretty much impossible to guarantee pixel perfection on the screen of other users. The best you can do is make sure that your textures are displayed at the same resolution as the items in an inventory slot. That way either both the items and the formspec are pixel perfect, or both the items and the formspec are squished.

See attached image. On the left is a glass pane at default scaling and on the right is a glass pane with adjusted scaling.
![Screenshot from 2023-09-11 14-21-20](https://github.com/minetest/minetest/assets/48406239/b963cb09-e33c-4299-bb86-6782b6a9be0b)
Even though in the original texture each dot on the glass is 1 pixel, with the default scaling (on my screen at least) some appear to be larger then others.

Thus the best thing you can do as a dev is set your gui scaling to something that allows you to work with precision and the rest is up to the end user.

**Comment by lua-rocks** [comment]
Okay. If coordinates should always be specified in inventory slots rather than in pixels, then all the problems I described are not a bug. Let me close this issue and create a new one with an improvement proposal.
