### ISSUE TITLE
Allow `place_param2` values of 0 to be predicted client-side

### ISSUE THREAD

**Issue by rollerozxa** [minetest/minetest#13784]
### Minetest version

```true
Minetest 5.8.0-rollerozxa-904d01562 (Linux)
Using Irrlicht 1.9.0mt12
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Operating system and version

Linux

### Summary

When adding `place_param2 = 0` to a node to enable the client to predict the direction of a node (e.g. planks in MTG are rotatable but should only ever be rotated at one angle when placed), it ignores the value as 0 is also used for nodes without any param2 prediction, leading to flickering textures on the client.

### Steps to reproduce

1. Go into MTG, grab planks
2. Try to place them not in the direction they usually go (east or west)
3. Watch the top texture briefly flicker

**Comment by sfan5** [comment]
To no surprise this is because "0" is the neutral value so it is ignored. I wasn't totally sure if this should be a bug or feature request, now it's the latter.

**Comment by celeron55** [comment]
This goes quite deep. The network protocol requires an additional boolean value in order to enable telling the client "yes, my 0 is 0, not a command to ask you to figure out param2 on your own".

Currently 0 has a double meaning, it's only 0 if the client doesn't determine magic needs to happen based on various separate conditionals: https://github.com/minetest/minetest/blob/1a568cc491f460197bdf29eeb19d2b480f42aa71/src/client/game.cpp#L3630

**Comment by sfan5** [comment]
> place_param2 = 0 works on the server-side, see e.g. planks on MTG which can only placed in one direction

I see.
The cause for this is a bit complex: since the server placement runs in Lua which can differ between `nil` and `0` it works there. The C++ definition does not have that distinction. Incidentally that only makes a difference on the client, hence the mismatch you see.
