### ISSUE TITLE
Regression in splitting inventory stacks on Android

### ISSUE THREAD

**Issue by rollerozxa** [minetest/minetest#13822]
### Minetest version

```true
5.8.0-dev master, using Github workflows produced APK
```

### Operating system and version

Android

### Summary

There has been a regression when handling stacks on Android, as it is no longer possible to split stacks on Android, something that requires two simultaneous fingerpresses.

I've tested it in latest Minetest master and can reproduce, but I haven't bisected the issue. Some pointers for bisecting the issue:
- I've had reports of this from people running ROllertest 2023.8.4, which is based off somewhere around commit 28fce8aad58a10b45248c5dbc4ce8b0a534740a2.
- The previous version 2023.5.16, based off commit 15fb4cab15c8d57028a2f616e1b443e8dc02e4f9 does not have this issue, inventory stacks work like they should.

### Steps to reproduce

1. Go into a world (MTG creative, whatever...) and give yourself a stack of items.
2. Attempt to distribute them across inventory cells, by grabbing the stack with one finger held down, moving it across inventory cells and tapping with a second finger.
3. An item is supposed to be placed in that slot, but isn't.

**Comment by SmallJoker** [comment]
Possible culprit which happens to be in between the time frame you specified: 252c79d

Unfortunately the logs and builds no longer seem to be available to test this easily by installing the apk.

**Comment by Unacceptium** [comment]
i've tried this in different versions and forks, this bug only present in 5.8 based versions.

**Comment by srifqi** [comment]
I can confirm this issue on Android 13.

**Comment by grorp** [comment]
There's another, related regression, probably also caused by #13146: Item tooltips don't show anymore on Android. This worked on Minetest 5.7.0.

**Comment by srifqi** [comment]
(While this issue is being fixed, here is a temporary solution that might help users/players.)

Even though it is currently impossible to put a single item from a stack in touch-screen devices, we can still split a stack (evenly) using single finger:

1. Tap the stack to select it.
2. Tap and drag over empty slots.
3. The selected stack will be distributed evenly to hovered empty slots.

By using that splitting technique, we still can put a single item from a stack using two adjacent slots:

1. Tap the stack (first slot) to select it.
2. Tap the empty slot (second slot) and drag to the first slot.
3. Tap the second slot to select it.
4. Tap the second slot and drag to the first slot.
5. Repeat step 3–4 until the second slot only has one item.

That would be very tiring for a lot of stacks, though, e.g. when crafting something.

https://github.com/minetest/minetest/assets/4017302/f447f57a-0729-4709-a2e2-bc1118b42291

(This is tested using [5.8.0-rc1](https://forum.minetest.net/viewtopic.php?t=29937) on Android 13.)

**Comment by Unacceptium** [comment]
@rubenwardy i have noticed it yesterday, and i wanted to comment it here lol. i'm actually ok with this method at this moment, but i still cant see the item description thing idk how its called..

**Comment by Unacceptium** [comment]
No need for PR!!!!

Single Stack Splitting Works With Different Method!!!!!!!!!
METHOD:
get the whole stack up. release your finger. tap and hold a
button. move finger to decided slot without releasing finger. click with second finger to drop one item!!!!!!!

Tooltips Working With Different Method Too!!!!!
sorry for bad english.
METHOD 1:
hold first finger outside inventory. when holding, hold and move second finger
from outside the inventory. move finger above items and buttons. tooltip shows up!
METHOD 2:
touch and hold single finger on a button, then move it without releasing above items and buttons. tooltip shows up!
video:
https://youtu.be/JsySpPkigwQ?feature=shared

**Comment by srifqi** [comment]
> Single Stack Splitting Works With Different Method!!!!!!!!!
> Tooltips Working With Different Method Too!!!!!

That does work, but not very intuitive and more like a workaround. That also will not work if there is no button in the inventory menu.

> No need for PR!!!!

We definitely need a fix/better way for this action (because it works in 5.7.0).

**Comment by Unacceptium** [comment]
@srifqi i posted that comment in this look and way, because it suprised me, and i wanted to post what i found as fast as i can, so i don't minded the whole text out...
and you are true, this needs a fix, but i think that fix SHOULD inplement a way for tooltips.
