### ISSUE TITLE
Rename translation script to something more obvious

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#13897]
Right now the file name is `mtt_update.py`, where I suppose the 2nd "t" stands for translate. It took me a bit before finding it in the util folder, as I consider the title not obvious (and I was helped by the latest commits name next to the files). All the other files in the util folder are straightforward.

Suggestions:
* mod_translations_update
* translations_update
* I don't know, but I'd avoid specifying the `.tr` format in case Minetest starts supporting new formats such as `.po`§

I also suggest doing that before 5.8, so to avoid linking problems

**Comment by Wuzzy2** [comment]
Yeah, agreed. `mtt` stands for Minetest Translation Tools because I pulled it directly from my script collection of the same name. So this part is just a "historical" artifact. MTT also includes a checker script which has not been included officially so far.
https://codeberg.org/Wuzzy/Minetest_Translation_Tools

I'm not sure which name to choose. And please add this to the 5.8 milestone because it should def. be done before release.

**Comment by srifqi** [comment]
- `translation_updater.py`
- `mod_translation_updater.py` (signifying for mods)
- `tr_updater.py` (`tr` as in `.tr` files)
- `mod_tr_updater.py`
- `updatetr.py` (like `updatepo.sh`)

**Comment by Zughy** [comment]
I think `mod_translations_updater.py` instantly conveys what it does, +1 for me

**Comment by srifqi** [comment]
So, the changes are
- `util/mtt_update.py` -> `util/mod_translation_updater.py`
- `util/README_mtt_update.md` -> `util/README_mod_translation_updater.md`

**Comment by Wuzzy2** [comment]
Oh lol, I was about to do this myself today but someone was faster. :D

Thanks.
