### ISSUE TITLE
Restore the +/- numpad default behaviour (increase/decrease viewing range)

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#13890]
### Problem

It's not possible to use +/- on the numpad anymore to increase/decrease the viewing range, since some 5.8.0-dev commit

### Solutions

Restore such behaviour

### Alternatives

Issue forms are kinda annoying

**Comment by grorp** [comment]
As stated on IRC, this is caused by #13773.

> "Numpad Plus" and "Plus" are now considered two different keys, and "Increase Viewing Range" is still bound to "Plus" by default
> I'm not sure what can be done about this problem. I don't think that PR should simply be reverted, it's useful to be able to bind e.g. "1" and "Numpad 1" to different actions.

rubenwardy's suggestion:

> Should be bound to both keys by default then

https://irc.minetest.net/minetest-dev/2023-10-11#i_6121252

**Comment by erlehmann** [comment]
@grorp say, is https://github.com/minetest/minetest/pull/13773 also causing https://github.com/minetest/minetest/issues/13899 maybe?

(If it does, my suggestion would be to revert that thing instead of binding more keys.)

**Comment by erlehmann** [comment]
I have confirmed that reverting the change from #13773 also fixes the regression where I can not input a + at all because it needs a modifier key on my layout: https://github.com/minetest/minetest/issues/13899#issuecomment-1783971474

**I think commit d57c936b080f404df0b544561242b0c45c57f04d should simply be reverted due to causing multiple regressions.**

The idea is simply not very good if it results in users of layouts where “+” needs a modifier key to not be able to use a “+” at all.
