### ISSUE TITLE
Translation updater: comments are moved on top if they precede the first file name

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#13946]
1. Run the translation updater script with `-p`
2. Put a comment below the first file name
3. Run the script again
4. The comment is now on top

@Wuzzy2

**Comment by erlehmann** [comment]
I can try to help you debug this if you provide:

1. The command you have run, verbatim. Is the ”translation updater script” named `util/mtt_update.py`?
2. Test input (ideally a minimal input file that only serves to demonstrate the bug you found).
3. The entire output you got.
4. The entire output you expected.

**Comment by srifqi** [comment]
It seems like comments following a source file comment are treated as header comments. This might be fixed by stopping the script from adding the next comments after a source file comment to header comments.

```diff
diff --git a/util/mod_translation_updater.py b/util/mod_translation_updater.py
index a6b3286b3..0870399e3 100644
--- a/util/mod_translation_updater.py
+++ b/util/mod_translation_updater.py
@@ -308,6 +308,8 @@ def import_tr_file(tr_file):
 				elif line.startswith("#"):
 					# source file comments: ##[ file.lua ] ##
 					if line.startswith(symbol_source_prefix) and line.endswith(symbol_source_suffix):
+						if params["print-source"]:
+							in_header = False
 						# remove those comments; they may be added back automatically
 						continue
 
```

I am not sure whether it should be done only when the `print-source` is enabled. It has no effect when `print-source` is disabled because all comments on the first string will be moved to the top anyway.

**Comment by Wuzzy2** [comment]
Good bug report and analysis. Can confirm everything.

Bugfix PR is ready! #13974
