### ISSUE TITLE
Settings search function focuses different tab depending on locale

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#13973]
### Minetest version

```true
5.7.0-377-g1242f1011
```

### Active renderer

OpenGL 1.4

### Irrlicht device

X11

### Operating system and version

Debian 11.8

### CPU model

Intel(R) Core(TM) Duo CPU      T2400  @ 1.83

### GPU model

Intel Corporation Mobile 945GM/GMS, 943/940GML Express Integrated Graphics Controller (rev 03)

### OpenGL version

1.4

### Summary

The search function in the new settings filters tabs by name and then focuses one of them.

It is unclear to me why that happens, but it seems to depend on locale. Maybe this depends on collation?

Example:

* The query “size” in the settings dialog with `LANG=de_DE.UTF8` focuses on the tab “Grafik” (German for “Graphics”).
* The query “size” in the settings dialog with `LANG=C` focuses on the tab “Accessability” (not “Graphics”).

This seems to be true even when the language is changed inside Minetest, e.g. Minetest in French started with `LANG=de_DE.UTF8` focuses on the tab “Graphismes” (probably French for “Graphics”)

### Steps to reproduce

1. Start Minetest with the environment variable `LANG` set to some locale that your OS supports (e.g. `de_DE.UTF8`).
2. Click the settings button (it has two gray circles and is located in the upper right of the interface).
3. Search for “size” in the settings dialog.
4. Note down which tab is focused.
5. Repeat the previous steps with a different value for the environment variable `LANG` (e.g. `C`).

**Comment by grorp** [comment]
This looks like intended behavior. The search function selects the page that best matches your search query. Since setting names and descriptions are localized, the best page for a single search query can change depending on the selected language.

In your example:

- The query “size” in the settings dialog with LANG=C focuses on the tab “Accessibility” (not “Graphics”).

    -> "Accessibility" contains 4 settings that match this query.

- The query “size” in the settings dialog with LANG=de_DE.UTF8 focuses on the tab “Grafik” (German for “Graphics”).
    
    -> The "Graphics" category contains "Remember screen size", which is not translated to German for some reason. Other instances of "size" are translated to German, and are thus not matched.
