### ISSUE TITLE
Re-design formspecs format

### ISSUE THREAD

**Issue by ShadowNinja** [minetest/minetest#1399]
The current formspec design is very ugly, and makes extending elements or adding more advanced elements very hard.  You can't add another field to an element without making every previous field required, and the resulting strings are unreadable without looking at the specification to find out what a field means.

Therefore we need a new formspec design.  The best way to design the new formspec would probably be with Lua tables.  I've come up with an example design:

``` Lua

local formspec = {
    width = 5,  -- Optional
    height = 5, -- Optional
    {type="button", name="test button", text="Test"},
    "\n",
    "Here are some elements in tabs:\n",
    {
        type = "tabs",
        tabs = {
            ["Table"] = {
                type = "table",
                elements = {
                    {"Test 1", ">>>>>>>>>", {type="button", name="clickme", text="Click me!"}},
                    {{type="image", src="test.png"}, "/////////", "^^^^^^^^^"},
                },
            },
            ["List"] = {
                type = "list",
                elements = {
                    "These are a few",
                    "lines of text that",
                    "you can select.",
                    {
                        type = "button",
                        name = "list button"
                        text = "Along with a button.",
                    },
                },
            },
        },
    },
}
```

Text fields are shortcuts for `{type="text", text="<...>"}` and ements are auto-placed be default.  This can be serialized in Lua module format or JSON format.

Clients will have to support old formspec strings for a release or so, and servers will have a Lua wrapper that converts formspec strings to objects for a few releases.

Also: Ways to specify colors and similar text properties should be discussed.

HTML may be an option, if we can find a way to implement it that isn't horribly slow.

**Comment by RobertZenz** [comment]
Have you considered using a third-party library, like [Crazy Eddie's GUI System](http://cegui.org.uk/) (which offers an Irrlicht module/renderer) and exposing that directly to the LUA API?

**Comment by RobertZenz** [comment]
I'd like to add the idea of an object/instance based approach, even though I do not know how the GUI is implemented in C++, and therefor can't say if such a thing would play nicely with it. Consider it food for thoughts.

    -- Note that "ui" is a global factory for UI elements.
    local window = ui.window()
    local label = ui.label("Some text")
    local button = ui.button("Press me", function()
            -- Event handling of the button goes here.
        end)
    
    window:add(label)
    window:add(button)

Even though it is a lot more verbose than previous approaches, it is more readable in my opinion. I guess you noticed that any layout is completely missing from that example, that's because I wanted to give a simple example, and also because I'm not 100% sure how to implement layouts in this case.

An idea would be to create containers that already have the needed layouts.

    local window = ui.window()
    local content = ui.grid_container()
    
    -- Note the additional parameters that denote column and row.
    content:add(ui.label("Some text"), 0, 0)
    content:add(ui.label("More text"), 1, 0)
    
    -- Note the additional parameters that denote how many columns/rows the element does span
    content:add(ui.button("Press me", some_function), 0, 1, 2, 1)
    
    -- Created GUI/layout:
    --
    -- +-----------+-----------+
    -- | Some text | More text |
    -- +-----------+-----------+
    -- |       Press me        |
    -- +-----------------------+

Creating multiple containers with different layouts would allow to nest them to any layout needed. Though, having a container with a grid layout that allows elements to span multiple rows/columns would already suffice for many/most use cases, especially if you can anchor elements on the far sides.

Instances of the elements could be kept around and updated as needed, for example:

    local window = ui.window()
    local label = ui.label("Initial text")
    
    -- Some time later in a callback
    label:text("New text")

Which would obviously change the text of the label in GUI.

Such an approach would technically also allow easier reuse of components, and providing "ready to use" components with rather ease.

**Comment by MirceaKitsune** [comment]
I only support this if existing formspecs and their functionality will always remain compatible! Personally I think Lua tables are better suited as well, and am actually confused why a string was used to begin with.

**Comment by C1ffisme** [comment]
I really, REALLY hope this gets implemented.

**Comment by numberZero** [comment]
@C1ffisme, me too =)

Sadly full-featured implementation would require client-side Lua. But even without core changes, you can use more readable notation (like this: https://github.com/numberZero/libform/blob/master/example.lua), although you’re restricted to the features present in the default formspec language (especially when dealing with node metadata; if using `show_formspec`, tabs and some other features may be emulated)

The way suggested by @RobertZenz fits nicely in C++ code, but in Lua you can write something like this instead (note that you may mix named and unnamed table entries):
```lua
local myform = ui.Form{
	size = { 8, 9 },
	elements = {
		fuel = ui.Inventory{
			pos = { 2, 3 },
			size = { 1, 1 },
			default = uilib.ContextNodeInventory("fuel"),
		},
		source = ui.Inventory{
			pos = { 2, 1 },
			size = { 1, 1 },
			default = uilib.ContextNodeInventory("src"),
		},
		name = ui.Field{
			pos = { 2, 4 },
			size = { 4, 1 },
			label = "Furnace name",
			default = "",
		},
		ui.Label{
			pos = { 0, 0 },
			text = "Furnace",
		},
	},
}
```
IMO that fits better in Lua (and better than using plain tables), and you can still serialize it as you like: to JSON, Lua tables, or even standard formspec (if you have all the necessary values as formspecs don’t support variable references)
```lua
local myfurnace = uilib.ContextNode({x=0, y=5, z=0}) -- to replace "context" inventory refs to "nodemeta:0,5,0"
local formspec = myform:toFormspec{
	name = "My best furnace",
	fuel = myfurnace,
	source = myfurnace,
}
```

**Comment by rubenwardy** [comment]
smartfs does something similar

**Comment by raymoo** [comment]
FRP imo

**Comment by Wuzzy2** [comment]
As a modder who has worked with formspecs for a long time now (references: L-System Tree Utility [ltool], Documentation System [doc], Easy Vending Machines [easyvend], contributions to Unified Inventory and some other mods), I think I should give my thoughts on this, too.

I personally don't really have a problem with the current formspec syntax at all. I mean, as long as it is correctly documented and their semantics are clear, I can't see why it should be a problem. But I have no strong feelings about the syntax, so feel free to convince me otherwise. I also can't follow the claim that the syntax is somehow “unreadable”. It is totally readable for me. But your readability may vary. ;-)

But right now, I doubt switching to tables or whatever other syntax would really help with anything. It's just a fancier syntax but it won't solve any of the underlying problems. I think that some people find the syntax awkward is probably one of the least “problems” with formspecs. I even doubt it is actually a problem.

Formspecs have much bigger problems:
* Documentation is rather poor and incomplete. I think it should be completely proofread and then rewritten and then proofread again to make sure all features are included. Specifically, I miss the following information:
   * What happens if user exists / hits Esc?
   * How do the coordinate systems work? (document it for EACH widget if they differ from the norm)
   * Which user events (e.g. button press) trigger `on_receive_fields`? And which fields are then sent?
   * How to parse the returned `fields`? It must be documented for ALL widgets seperately. For some fields this is not obvious and I was only able to figure it out with trial-and-error, NOT with the documentation
   * Probably a bunch of other gotchas I am not even aware of
* The returned fields are totally awkward and inconsistent. I see no logic behind when Minetest triggers a `on_receive_fields` and which of the fields in the formspec it actually sends. For example, text in text fields is send on a button press, but checkbox values are not sent, instead they are **only** sent after you clicked them. 
* VERY inconsistent coordinates, also very poorly documented. Some formspec elements use inventory slots while some other formspec elements use some other system or even have an offset for … reasons. None of this is documented. This makes proper alignment of widgets especially in widget-heavy formspecs hard or even impossible to do. https://github.com/minetest/minetest/issues/3872
* This frustrating bug: https://github.com/minetest/minetest/issues/4482
* Many important widgets are still missing:
    * Scrollable automatic-line breaking multi-line text: https://github.com/minetest/minetest/issues/3807
    * Containers which can contain other widgets and be scrolled
    * Clickable text (like hyperlinks)
    * (Note: I might post new issues about those suggestions later)
* No way to check which widgets are supported: https://github.com/minetest/minetest/issues/4834
* Generally, an overall “quirkiness”. When learning to use formspecs, I often run into lots of small “quirks” or gotchas, basically there are way too many surprises and/or unexpected behaviours. This is just a feeling of mine but I think this summarizes many of the problems with formspecs

As long the bigger underlying problems are not fixed, I think changing the syntax will really only be a cosmetic change.

I would fully accept any compability breakage if it means that we end up with a much more consistent and logical system which can be used without hacks. And iirc formspecs never left “experimental” status anyway.

**Comment by juhdanad** [comment]
What about Irrlicht XML? http://irrlicht.sourceforge.net/docu/classirr_1_1gui_1_1_i_g_u_i_environment.html#a23e53c388d45358c53304d095f0b029b

There are numerous GUI editors for Irrlicht, and item lists can be implemented as custom GUI elements.

**Comment by rubenwardy** [comment]
Formspec also aren't very good with responsiveness

**Comment by rubenwardy** [comment]
Renamed this issue, there is good discussion in here however it lacks focus. The worst thing about formspecs isn't its format, but the inconsistency and lack of layoutting. Changing the formspecs format I'd be :-1: as it's just further work in broken code

**Comment by paramat** [comment]
:-1: 
Discussion moved to #6527
