### ISSUE TITLE
:bug: Name the 3 most annoying bugs you'd like to see fixed

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#14004]
After a long and useful discussion on the forum:  https://forum.minetest.net/viewtopic.php?t=29949 I've decided to run this experiment.

Name the 3 most annoying bugs that you'd like to see fixed and add a **brief** explanation of why in your opinion such bugs should be prioritised compared to the rest.  

The idea is to make use of the "high priority" label so that development can be more community driven. What's the criteria that determines whether a bug should obtain or not the label? Frankly I still don't know, but it wouldn't be an experiment otherwise, would it? I'd like to see what comes out of it and core devs can simply ignore this topic if they want - I don't want to add a bigger burden onto their back.  

Speaking of devs, of course "high priority" doesn't mean "now devs have to fix it or I'll stomp my feet until they hurt" (we're all volunteering), but rather something that can be pointed out (e.g. in the blog with a call to action) to people that would like to contribute to Minetest and don't know where to start (alongside the "good first issue" label).  

**Rules**
1. do not propose your own issues
2. please post all the bugs in one single message
3. keep debates to a bare minimum and consider commenting directly under the offending bug if you've got observations related to it; use reactions so to avoid spamming my mail inbox, thanks :pray: 

That being said, have fun! (I've removed the ones labelled "low priority")  
https://github.com/minetest/minetest/issues?q=is%3Aopen+is%3Aissue+label%3ABug+-label%3A%22Low+priority%22

**Comment by APercy** [comment]
entity rubber banding
the password field being "cleaned" before I finish the typing
light propagation through slabs, stairs and other opaque cut blocks

**Comment by rollerozxa** [comment]
(Are we supposed to write all three of our bugs in the same comment or can I split them up? Latter makes more sense, and this was the only one I could think of right now.)

`env_meta.txt` corruption rendering worlds unable to be opened unless you delete the file, caused by a bug in `fs::safeWriteToFile` that primarily occurs on Windows. (#9425) Haven't experienced it myself, but there is always every now and then someone who runs into this problem and asks for help about it in the Discord server.

The bug is especially terrifying because the engine will not display any kind of user facing error (only writes it to debug output), just kick you back to the main menu when attempting to load a world with a corrupted `env_meta.txt` file, making the player assume something way worse has happened to their world than just a metadata file that only contains LBM and time data (losing it is a bit unfortunate, but not a major setback for your world).

**Comment by erlehmann** [comment]
* https://github.com/minetest/minetest/issues/13519 Android black screen → This simply prevents people from playing Minetest.
* https://github.com/minetest/minetest/issues/6905 Inventory rendering performance → FPS drop in inventories for everyone.
* https://github.com/minetest/minetest/issues/13511 OGLES2 fullbright entity rendering issues → Looks needlessly ugly.

@Zughy how will this be evaluated? I suggest approval voting (i.e. count how often each bug was mentioned), it is very simple.

**Comment by Zughy** [comment]
The lowest common denominator of my 3 bugs is they can  break games and you can't do anything (or close to anything) to prevent it:
* #10842. This is basically a built-in hack. For instance, you can win minigames like [Colour Jump](https://content.minetest.net/packages/MrFreeman/colour_jump/) and [TNT Run](https://content.minetest.net/packages/debiankaios/tntrun/) by just opening the chat after jumping. If you're playing online and you're falling into a lava pit, you can prevent it if you're fast enough (and ask a friend to come rescue you)
* #11081. It's unthinkable that builders/level designers should take (also) this aspect into account
* #11523. It turns the player into a client-side ghost who's probably not even aware of their condition. High likely to make the game crash in the following minutes

(@rollerozxa added a rule about that)
(@erlehmann that's one idea)

**Comment by RecentRunner** [comment]
https://github.com/minetest/minetest/issues/6905
https://github.com/minetest/minetest/issues/3069
https://github.com/minetest/minetest/issues/12582

**Comment by Warr1024** [comment]
Not sure what "do not propose your own issues" means ... do you mean that you shouldn't vote for an issue if you were the one who _submitted_ it?  So we can only vote for issues filed by somebody else then?

**Comment by Zughy** [comment]
@Warr1024 people tend to consider their reports more important, so by preventing them to list their own issues we completely avoid the problem. There are 200+ bugs, for sure there is no scarcity

**Comment by hecktest** [comment]
#11531

**Comment by jordan4ibanez** [comment]
If someone knows the ID of the issue where you can float when you're on a nodebox, please let me know

**Comment by fluxionary** [comment]
* https://github.com/minetest/minetest/issues/13297
* https://github.com/minetest/minetest/issues/12566
* https://github.com/minetest/minetest/issues/12857

**Comment by immagiov4** [comment]
- #13568 
- #10037: right now to stop the player we must attach them to an entity, which is an nuisance and can possibly cause bugs like [#12092](https://github.com/minetest/minetest/issues/12092)
- #10733

**Comment by nininik0** [comment]
1. #10842 
2. #13580 
3. #13511

**Comment by ancientmarinerdev** [comment]
Thanks for this, Zughy. I've added 3 here. I may chance my mind, but thought i'd get something down for now.

1) Death screen is avoidable, leaving player in bugged state #7879 
 
https://github.com/minetest/minetest/issues/7879

This is a game breaking bug that has happened multiple times to many players. Due to the impact and frequency, it really needs to be prioritised. It's probably very much related to https://github.com/minetest/minetest/issues/11523 which was listed by Zughy, but I fear if that is resolved in isolation, it may not fix this bug which can surface in many ways. The issue is a player can get into a bugged state without that formspec present and multiple ways can cause it.


2) minetest.dig_node in protected areas will not work (even if you own the area) #13563 
https://github.com/minetest/minetest/issues/13563

This is a bug (even though there was an exhausting hours long debate about whether it was) which makes any form of automation unimplmentable without nasty hacks. It really takes away from multiplayer experience, and the engine should have a prescribed way of doing this. 

3) Seeing through blocks glitch #12429 
https://github.com/minetest/minetest/issues/12429

Takes away from multiplayer experiences when people can find cave bases around them easily on vanilla client.

**Comment by Warr1024** [comment]
1. #11531
2. 🤷
3. 🤷

**Comment by Wuzzy2** [comment]
My list of personal pet-peeves used to be large (see https://forum.minetest.net/viewtopic.php?t=15084), but now it has shrunk to only one entry:

1. #4759 because entities are quite important and it's very frustating that you never can 100% trust `minetest.add_entity` to *actually* spawn the item. This makes any development related to spawning extremely annoying.

(I think rule 1 makes no sense. A bug is a bug, no matter who posted it. Btw, this issue above has already "earned" high priority anyway, lol)


----


I too think the "High priority" label needs to have more meaning. Currently it is very unpredictable when it is used. And I feel it is used way too rarely. High Priority is actually SUPER high priority because it is only used for things like serious crashes or game breakers. This is fine, of course, but there are still many bugs that I think are kinda important, but not SUPER important. These issues get overlooked since they don't get any priority label.

I propose to add a new priority label. It is lower than High priority, but higher than the "default priority" (=no label).

Oh, and the fact we have no medium priority label bugs me, too. If an issue has no priority label, it can mean two things: Either the priority was not chosen yet, or it is *deliberately* at medium priority. This is ambigious. Maybe a script could be used to auto-label all old issues without a priority label with Medium priority?

This is the new priority label system I propose:

* High priority
* Elevated priority (new!)
* Medium priority (new!)
* Low priority

Another problem with High priority right now is that it is not really well-defined. It often seems to be based on personal taste of whoever labels it rather than objective criteria.

So I suggest to have some objective criteria to classify issues. This also has the benefit to reduce possible debates whether issue XYZ is important or not. In general, the priority of a bug should be determined by its "pain factor": How much of Minetest is broken with this bug, how many people suffer under it, and how likely/easy is it to trigger this bug? The worst bugs are bugs that break Minetest completely, and everyone get them on a regular basis.

Some examples (this is debatable, of course):

* High: Obvious crashes, game breakers, critical data loss, security vulns, a key feature is very broken, serious performance problem, licensing/FOSS problems
* Elevated: Generally anything that is "annoying" a lot of people while not High priority. It does not destroy the gameplay experience entirely, but it still degrades it notably. A not-so-important feature is broken.
* Medium: Something is behaving clearly wrong but the gameplay still works mostly fine. Major documentation problems (like, when it says the opposite of the truth)
* Low: Typos/grammar/language issues, ultra-rare bugs, bugs in obscure features that few people use. Minor documentation problems

I will not propose priority criteria for feature requests tho, this is a different discussion.

----

PS: It makes no sense that proposing your own issues is technically against the rules. A bug is a bug, no matter who found it.

**Comment by ancientmarinerdev** [comment]
I agree on the whole being able to raise your own bugs. You likely raised them because they had impact to you or players of you game. You know best that it is a major issue. Serious bugs will inevitably get more than 1 vote, but even if they don't, they were at least cared about enough because of their impact.

You could have critical bugs, and high priority bugs. I think it is more descriptive, but agree about the fact you need 2 levels of high priority. I would also agree with the medium label. It makes it to triage priority also, as you can search everything that isn't a priority (well in gitea you can, not sure about github).

**Comment by kromka-chleba** [comment]
The first one is annoying as hell:

1. https://github.com/minetest/minetest/issues/9357
2. #14014 
3. https://github.com/minetest/minetest/issues/12719

Rationale (for the 1st):

Have some extra cores for the server? Too bad because using them will slice your world in half.
I have a vague understanding of the problem, but I thing the bug may be a problem once this PR gets merged: https://github.com/minetest/minetest/pull/13092

**Comment by NouriIbrahim** [comment]
The game crashes randomly when people open Minetest and try to log in, it happens randomly, not always.

**Comment by Wuzzy2** [comment]
If I ignore bugs I am not allowed to post, I currently only have one bug:

1. #3075

This bug basically makes the waving liquids feature totally useless IMO. I always play without waving liquids because of the ugly bug. I like waving liquids, but this bug ruins it.

**Comment by fluxionary** [comment]
* #6193
* #13486
* #14018

**Comment by BamsGianYagami** [comment]
All we had to do is controller support for every platform

**Comment by Zughy** [comment]
Thanks to everyone participating. The majority of issues has been labelled as "High Priority", using my point of view as yardstick. Closing, probably see you with something similar in the next roadmap brainstorm!
