### ISSUE TITLE
add option to adjust transparency of water in setting

### ISSUE THREAD

**Issue by TheCorruptCat** [minetest/minetest#14019]
### Problem

I am unable to adjust transparency of water in settings

### Solutions

add a slider from 0 to 1 on how transparent the water would be

### Alternatives

Add an option in some config menu

**Comment by GreenXenith** [comment]
It's up to the game how something should look. If I, as the game designer, do not want you to see through water, you aren't going to. If I want you to see a little but nit much, then that is how it should be.

The only reason you are even allowed to make liquids opaque when it is transparent by default is due to (rather outdated) performance concerns. Honestly if it makes that big of a difference, the problem should be fixed at the rendering stage.

I would go so far to say that games should have complete control over liquid opacity and the client setting for opaque liquids should be removed entirely.

But for this issue specifically, the opacity of a liquid is defined by its texture, with the opaque water setting simply removing the alpha channel. It wouldn't make much sense as en engine setting. And remember that a client setting would apply to all liquids, not just water. If anything, this should be a MTG setting for the server to configure (and use the opacity modifier on the texture or something).

**Comment by jordan4ibanez** [comment]
Might be able to turn that idea into a shader element, maybe. Remove any application of alpha and override with a uniform or the like.

**Comment by TheCorruptCat** [comment]
@GreenXenith  I think the player should be able to have complete control over the game
