### ISSUE TITLE
Reduce main menu padding on desktop

### ISSUE THREAD

**Issue by rollerozxa** [minetest/minetest#14037]
### Problem

Currently the main menu has way too much padding on desktop, which is especially noticeable on low window sizes:

![image](https://github.com/minetest/minetest/assets/60856959/b66a8c17-b1dd-47f7-b4cb-30c439fe434a)
Image courtesy of Warr1024 (at 1028x603), you can see that the package names get cut off and generally doesn't make great use of screen space.

### Solutions

Reduce the padding. This could be accomplished by using the `padding[]` formspec element, as used in ROllertest on desktop to make the main menu formspec take up more space, along with offsetting the dialog vertically using `position[]`, giving the game header more room to breathe. 

This might come at a cost of the main menu looking ridiculously large at larger screen sizes, but having it be usable at any reasonable size (and especially the default 1024x600 size) should be preferred I think.

### Alternatives

N/A

**Comment by Warr1024** [comment]
A noteworthy feature of that screenshot is actually the "Disable Texture Pack" button ... it's the only way to tell that that texturepack is actually enabled, thanks to that information being cut off to make room for padding.

**Comment by rollerozxa** [comment]
Yeah, it was quite funny. :)

---
Looking at how the main menu looks like in the default window size, 1024x600, this is how it looks like out of the box:

![image](https://github.com/minetest/minetest/assets/60856959/71c3e83f-9468-486f-a81c-1496b847ecc5)

![image](https://github.com/minetest/minetest/assets/60856959/8302d0b1-3c72-48c7-82bf-6b2a9440612c)

Adjusting the padding and position (`position[0.5,0.6] padding[-0.05,-0.05]` as an example here, you can stuff it into [builtin/fstk/tabview.lua#71](https://github.com/minetest/minetest/blob/master/builtin/fstk/tabview.lua#L71) for testing), this is how it could look:

![image](https://github.com/minetest/minetest/assets/60856959/57236bda-75a2-40b7-b376-d8076f7c40b5)

![image](https://github.com/minetest/minetest/assets/60856959/9e6fccd9-9857-4f35-b032-9ec4dd1e6297)

**Comment by grorp** [comment]
> Reduce the padding. This could be accomplished by using the padding[] formspec element, as used in ROllertest on desktop to make the main menu formspec take up more space, along with offsetting the dialog vertically using position[], giving the game header more room to breathe.
>
> This might come at a cost of the main menu looking ridiculously large at larger screen sizes, but having it be usable at any reasonable size (and especially the default 1024x600 size) should be preferred I think.

It actually looks ridiculously large on my 1920x1080 screen.

I think that changing the formspec padding is not the solution to the mainmenu being too big or too small depending on window size. You can't improve the overall situation by that, you can only improve the situation for certain window sizes (while making it worse for others).

This problem is caused by the fact that formspec coordinates are proportional to the window size. You can change that by setting something called `fixed_size` on the `size` formspec element: https://github.com/minetest/minetest/blob/771da80bbb85c9fa4f0dcf0f3d04f46a0a20239f/doc/lua_api.md#sizewhfixed_size.

Here are two screenshots that show what it would look like:

1024x600
![screenshot fixed size 1024x600](https://github.com/minetest/minetest/assets/82708541/b6bc14b5-32b9-406d-a38a-8d2cedeea1c5)

![screenshot fixed size 1920x1080](https://github.com/minetest/minetest/assets/82708541/57445c68-9c17-41d2-8dfe-476ff32e94c6)

What do you think? I'm not sure myself, now the mainmenu looks too small in my eyes on the larger window.
