### ISSUE TITLE
Small hitbox of jump button(android)

### ISSUE THREAD

**Issue by RedMatrix1** [minetest/minetest#14077]
### Minetest version

```true
5.8.0
```

### Active renderer

GLES 3.2

### Irrlicht device

Android

### Operating system and version

Android 13

### CPU model

Helio-G96

### GPU model

Mali-G57 MC2

### Summary

Sometimes you can’t press the jump button, you should rather press the center (doesn’t always work)

### Steps to reproduce

I just pressed the jump button, it didn't worked, I had to aim with my finger

**Comment by rollerozxa** [comment]
what

**Comment by RedMatrix1** [comment]
> what

🫥, I don't know, you're either stupid or you or

**Comment by rollerozxa** [comment]
It doesn't get fixed by removing your user data, the jump button is just placed in an unfortunate location where most of the touch area gets covered by palm rejection on some smartphones when you are holding another finger on the screen (e.g. holding one finger on the joystick and attempting to press the jump button).
