### ISSUE TITLE
Server step sometimes "pauses" since recent 5.9.0-dev changes

### ISSUE THREAD

**Issue by grorp** [minetest/minetest#14181]
##### Minetest version

```
Minetest 5.9.0-dev-bc336480e6-dirty (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.1692716794
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: Fedora Linux 39 (Workstation Edition)
CPU: Intel® Core™ i7-4790K × 8

##### Summary

In recent 5.9.0-dev versions of Minetest, I've observed that the server step sometimes "pauses", i.e. `minetest.register_globalstep` Lua callbacks stop running for a while.

This happens both with the "Host Server" checkbox enabled and without.

##### Steps to reproduce

1. Create a new Devtest world with the "flat" mapgen. Disable decorations and the like.

2. Put this code into a mod:

    ```lua
    local last_time

    minetest.register_globalstep(function(dtime)
        local now_time = minetest.get_us_time()
        print(string.format("[step] dtime(MT)   = %f", dtime))
        if last_time then
            local dtime_real = (now_time - last_time) / 1000000
            print(string.format("       dtime(real) = %f", dtime_real))
            if dtime_real > 0.5 then
                local c = string.char(27)
                print("       " .. c .. "[31;1;4mHuh, there's been a gap of more than half a second!" .. c .. "[0m")
            end
        end
        last_time = now_time
    end)
    ```

3. Join your world. Grant yourself the "fast" privilege and run in one direction for some time

##### What I expect

A steady stream of `[step] ...` messages appears in the console.

The message `Huh, there's been a gap of more than half a second!` only appears very rarely. If it appears, the `dtime` reported by Minetest roughly matches the actual `dtime`.

This is not only what I expect, but also what I observe if I revert commit 322c4a5b2b8343c3942555c6a337e765ef84c3c4.

##### What I observe

A stream of `[step] ...` messages appears in the console, but it often stops for a few seconds.

The message `Huh, there's been a gap of more than half a second!` appears after each of these stops. When it appears, the `dtime` reported by Minetest is much lower than the actual `dtime`.

```
[step] dtime(MT)   = 0.001954
       dtime(real) = 0.002533
[step] dtime(MT)   = 0.002484
       dtime(real) = 0.002486
[step] dtime(MT)   = 0.002494
       dtime(real) = 0.001580
[step] dtime(MT)   = 0.001580
       dtime(real) = 0.001044
[step] dtime(MT)   = 0.001028
       dtime(real) = 0.000619
[step] dtime(MT)   = 0.001002
       dtime(real) = 2.220502
       Huh, there's been a gap of more than half a second!
[step] dtime(MT)   = 0.001682
       dtime(real) = 0.002542
[step] dtime(MT)   = 0.002491
       dtime(real) = 0.002499
[step] dtime(MT)   = 0.002505
       dtime(real) = 0.001260
[step] dtime(MT)   = 0.001261
       dtime(real) = 0.001036
[step] dtime(MT)   = 0.001022
       dtime(real) = 0.000249
```

**Comment by Desour** [comment]
Tested in singleplayer, in master. Wasn't able to reproduce.
I only got some >0.5 steps when I've set viewing range high enough. And the dtime was correct:
```
[step] dtime(MT)   = 0.953992
       dtime(real) = 0.952163
       Huh, there's been a gap of more than half a second!
```

I noticed that your usual dtime is *really* low. With a non dedicated server (if you start a server from gui), you have to set really high `fps_max` to get that.
So, I've set my `fps_max` to 1000.
I got high server steps every now and then, but the dtime still was correct.

I think what happens for you is that with you low dtime you trigger this condition in `Server::AsyncRunStep()`:
https://github.com/minetest/minetest/blob/bc336480e6317fec4eea03b055bcf9602ff633d7/src/server.cpp#L607-L608

I tried using even higher `fps_max`, but didn't get as low dtimes. And I had to set my view distance low, to actually get lower dtimes. And indeed, I achieved it:
```
[step] dtime(MT)   = 0.099092
       dtime(real) = 3.044888
       Huh, there's been a gap of more than half a second!
```

I've tried lowering the 0.001f threshold, and it fixed the bug for me.
I think the condition is meant to only be triggered if the game is paused, and `AsyncRunStep()` is called explicitly with `0.0f`. So we might even be able to use `==`.

Btw. the reason why this only happens after https://github.com/minetest/minetest/commit/322c4a5b2b8343c3942555c6a337e765ef84c3c4 is because server dtime is no longer weirdly limited.

**Comment by Desour** [comment]
PR: #14182
