### ISSUE TITLE
Inventory items unresponsive after tab interaction until LMB click on formspec

### ISSUE THREAD

**Issue by zmv7** [minetest/minetest#14250]
### Minetest version

```true
Minetest 5.8.0 (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.1702233742
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```

### Active renderer

OpenGL 4.6

### Irrlicht device

X11

### Operating system and version

Archlinux current

### CPU model

AMD Ryzen 5 5600

### GPU model

AMD Radeon RX 570 4GB

### OpenGL version

4.6

### Summary

After interacting with tabheader(switching tab or even clicking on current tab), you can't interact with inventory items until you click LMB anywhere on the  formspec(except tabheader).
Video with mouse events overlay provided
[TabheaderBug.webm](https://github.com/minetest/minetest/assets/72821250/ed49a29f-b0d4-40a3-9167-f451a5339994)

### Steps to reproduce

1. Open the formspec that contains `list[]` and `tabheader[]` elements (e.g. `sfinv`).
2. Make sure you have some item(s) in the inventory
3. Click on the current tab of the tabheader(or switch to another then go back to inventory tab)
4. Try to pick up item using mouse wheel or RMB. - the items won't pick up
5. Click LMB anywhere on the current formspec page(except tabs)
6. Repeat step 4 - now items will pick up/move

**Comment by zmv7** [comment]
Same issue on 5.9.0-dev-025516a with SDL Irrlicht device

**Comment by jeremyshannon** [comment]
So that's what that is! I've noticed trouble with picking things up sometimes in 5.8.0. Exile uses tabs all over the place, and yes, when I've clicked a tab, I can't interact with anything until I've clicked the formspec again first.

**Comment by zmv7** [comment]
I assume the issue came together with android controls change

**Comment by j-r** [comment]
The problem is that the tab interaction eats the up event (for the tab switching itself) so GUIFormSpecMenu:OnEvent never sees it and thinks the button is still down (m_held_mouse_button remains set), effectively ignoring the following button down events until the next up event resynchronizes the internal state to reality.

One could relax the m_held_mouse_button != BET_OTHER condition a bit to allow processing down events of the allegedly held button (indicating that the up event somehow got lost), or prevent the up even from getting lost, or never even set m_held_mouse_button in the !s.valid() cases at all, or something else:-)
