### ISSUE TITLE
Mac build minetest-osx-bin-20140629.1367895

### ISSUE THREAD

**Issue by SingingBush** [minetest/minetest#1429]
the Mac build from https://github.com/mdoege/minetest/releases/ running on OS X 10.9.3

unable to do much with the gui, cannot create a world, tabs unresponsive to click events

**Comment by chum** [comment]
I am having this issue "out of the box"

* Built from sources
  816bca32ac69f58b7de881d68689c6a1e3897a0e (HEAD -> master, tag: 2017-08-16, origin/master, origin/HEAD)
* Had to add stack.yaml to get around libiconv link errors
   extra-lib-dirs:
      - /usr/lib
* I'm on MacOS Sierra 10.12.6

My test/failure case:

$ cmake . -DRUN_IN_PLACE=TRUE
$ make -j 1
$ ./bin/minetest

> Game launches, clouds move, says "MINETEST" like the imgr image earlier in this thread.
* Click NEW button.  It responds as it should, displaying a new world "dialog".
* Click in the World-Name field (where cursor is already blinking).  This step is optional, I did it to "help things along"
* Start typing a world-name: Foo

EXPECTED RESULTS:  Worldname field fills with "Foo"
ACTUAL RESULTS: the letters "foo" appear in my terminal window, intermixed with the game log output.

Continuing...

* Click in seed field.
> Cursor moves there
* Type "123" for seed

EXPECTED: Seed field populates
ACTUAL: "123" in my terminal window, as if I'd typed it there.

Continuing...

* Click create world button

EXPECTED: World is created, soon I will be playing minetest!
ACTUAL: Error dialog.  "An Error Occured:  No worldname given or no game selected"

I suspect this last failure is due to the prior ones, and that the real issue is that the game (minetest) isn't picking up any of my keystrokes.

Please help.

NOTE: launching the MineTest.app package (pre-built binary) works as expected.  This is an issue with built-from sources.

**Comment by tacotexmex** [comment]
If you look at [how brew compiles minetest](https://github.com/Homebrew/homebrew-core/blob/ec2da05a0dc0a47727da888239d219bd604b6b7e/Formula/minetest.rb#L58) it uses `make package`, not `make`. That creates a zip file, that contains a macOS-style .app container.
