### ISSUE TITLE
Combination of texture modifiers [combine and [sheet

### ISSUE THREAD

**Issue by AspireMint** [minetest/minetest#14306]
### Minetest version

```true
Minetest 5.4.0-win64
to
Minetest 5.8.0-win64
```

### Active renderer

OpenGL 4.6.0

### Operating system and version

Windows 10

### Summary

Combination of [combine and [sheet modifiers does not work as I would expect.
`size[4,5]image[0,0;4,8;[combine:16x32:0,0=default_cobble.png:0,16=^(default_wood.png^[sheet:4x4:0,0)]`
Not only it moves texture to wrong position, it creates tiny pixel with random color.
See image:
![formspec_modifier_bug](https://github.com/minetest/minetest/assets/37676291/977da344-242a-46d8-9623-7b3cf4d04b87)

### Steps to reproduce

```
minetest.after(3, function()
	minetest.show_formspec("singleplayer", "formimage:image",
		-- This without [sheet modifier works - correct position of wood texture
		--"size[4,5]image[0,0;4,8;[combine:16x32:0,0=default_cobble.png:0,16=default_wood.png]"
		
		-- This does not work correctly - wrong position of wood texture, tiny pixel with random color
		"size[4,5]image[0,0;4,8;[combine:16x32:0,0=default_cobble.png:0,16=^(default_wood.png^[sheet:4x4:0,0)]"
	)
end)
```

EDIT: no error messages

**Comment by sfan5** [comment]
what you wrote:
* `[combine`
  * 16x32
  * 0,0 is `default_cobble.png`
  * 0,16 is (empty string)
* `^` ¹
* `(`
  * `default_wood.png`
  * `^`
  * `[sheet`
    * 4x4
    * 0,0
* `)`

The empty string part should throw an error but other than that it's working as designed.

Now going by the expected image you probably accidentally put a `^` too much (marked ¹ above).
Still, it wouldn't work because braces don't replace quoting.
What you want is this `"[combine:16x32:0,0=default_cobble.png:0,16=default_wood.png\\^[sheet\\:4x4\\:0,0"`.

btw: don't put texture strings into formspecs without escaping, it's going to mess up sooner or later.

**Comment by appgurueu** [comment]
Yep, that's not a valid texture modifier. Ideally the engine would produce an error for these; with sfan's PR, it does. In the meantime, you could throw [modlib's texture modifier parser](https://github.com/appgurueu/modlib/blob/master/minetest/texmod/read.lua) at them; it is stricter than Minetest's (and might produce a more useful error message).
