### ISSUE TITLE
To s or not to s, that is the question

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#14372]
### Summary

I ran across this while working on https://github.com/BuckarooBanzay/luacheck/pull/1.

Our docs say

> ### Registered callback tables
> 
> All callbacks registered with [Global callback registration functions] are added to corresponding `minetest.registered_*` tables.

But our code does

https://github.com/minetest/minetest/blob/4843890c565bc54d67d65a01610f81eb3875d996/builtin/game/register.lua#L530-L563

(the attentive reader may have spotted a subtle difference: some of our `registered_*` tables have an `s` suffix, like `registered_on_placenodes`, while others do not, like `registered_on_priv_grant`; there seems to be no consistent rule being followed here)

### Steps to reproduce

Access `minetest.registered_*s` vs `minetest.registered_*`, or just :eye: :lips: :eye:

### What we can do

1. Create aliases for the -`s` tables without the `s` to match what the docs say.
2. Deprecate the -`s` tables.

(or the other way around)

Other suggestions?

**Comment by Desour** [comment]
### Another Proposal

Prefer consistency. `core.register_<thing>` -> `core.registered_<thing>s`, always.

One exception though: If only one can be registered (e.g. `register_authentication_handler`), it's singular `core.registered_<thing>`.

(And obviously add aliases for the old names.)

**Comment by rubenwardy** [comment]
My issue with that is that `registered_on_generateds` does not make grammatical sense, "generated" isn't a thing that can be plural

**Comment by alerque** [comment]
If you want everything to be grammatical I think you'd need to change the scheme entirely and use `registered_*_hooks` instead of `registered_*s`. Some projects and programmers care about natural language grammar more than others, some even prefer the less linguistic/natural more technical/mechanical approach.

**Not my circus not my monkeys**, I just came here as the maintainer of `luacheck` looking to check if there was an official stance and/or community consensus and what linter rules should be canonical.

**Comment by fluxionary** [comment]
> My issue with that is that `registered_on_generateds` does not make grammatical sense, "generated" isn't a thing that can be plural

it makes grammatical sense if you read the "on_generated" part in the quotative sense, as in "the registered 'on_generated' callbacks", similar to how "there are two 'the's in the sentence 'the man went in the house'" is grammatical even though 'the' isn't a noun and can't be plural. 

that said, i'm not in favor of changing the status quo - other than documenting what's already there - because it'll mostly be a headache for mod maintainers with very little practical use except for not annoying pedants. 

of the two existing proposals, i prefer Desour's.

**Comment by grorp** [comment]
I agree with fluxionary that it doesn't make much sense to rename all these tables just to have consistent "s". We'll have to keep the old names anyway for backwards compatibility, and then we'll have two names for the same thing, with the only difference being an "s" at the end.

**Comment by grorp** [comment]
#14509
