### ISSUE TITLE
Android: Allow players to change the button layout

### ISSUE THREAD

**Issue by AdityaMH** [minetest/minetest#14456]
### Problem

As you can see, jump and sneak button blocking my shortcut inventory
![Screenshot_20240312-101559](https://github.com/minetest/minetest/assets/33791472/b05c5f08-a5d0-4286-95e8-9bd392df6a11)

### Solutions

Add custom layout button only for touchscreen device.

### Alternatives

Actually no other alternative

**Comment by grorp** [comment]
Changing the button layout currently requires forking Minetest. A number of forks have been created for this purpose, including ROllertest, the NodeCore Android app and partially MultiCraft.

To make the official app viable for more players and to avoid mobile players having to maintain their own Minetest forks, we should allow players to customize the button layout.

I support this 👍

I'm working on this, but it will be some time until I'm done. You can look for the branch in my fork if you really want to, but the code is a mess.

I'm prioritizing this over the "add on-screen dig and place buttons" part of #13229 because having more buttons will make the problems with the current button layout worse, and hardcoding a different one isn't really a solution.

We should also allow game/mod makers to select a set of buttons to be shown and to provide a default layout and button textures. However, player customization is more important and can be done first IMO.

**Comment by Orisphera** [comment]
I think there are a couple of alternatives. One is to limit the hot bar width to a smaller value. I don't know if there currently is multi-row or scrolling, but one of these needs to be implemented anyway in case it's longer than the screen. The other one is to just move the controls up. Both would solve the problem in the report, but I think **the best option*** is to make it possible to fully customise the layout, including the hotbar width limit, its position, and an option to make Aux1 both a separate button and triggered by the joystick. Of course, fully implementing it may be more work than good, so **start with** button positions or hotbar width and then make the option to make Aux1 triggerable both ways. Also, for continuous values, there should be presets (e.g., buttons just above hotbar)
