### ISSUE TITLE
Add a flag to pwdfield[] to send a hash instead of raw plaintext

### ISSUE THREAD

**Issue by GreenXenith** [minetest/minetest#14476]
pwdfield[] sends raw passwords. It should have an option to hash before sending.

**Comment by rubenwardy** [comment]
This might be a small protection against eavesdroppig. But a man-in-the-middle could manipulate the formspec to ask for the password in plaintext. Some form of network encryption is long overdue, even if just for formspec and chat

(In case you're wondering, this isn't a problem with the SRP login or change password because it is a PAKE and the server can't ask the client to send plaintext)

**Comment by nininik0** [comment]
theres another issue with the pword box and it is that sometimes you enter the pword it vanishes OR when you scroll it vanishes too. and its annoying for people like me who have a 27-character password for mt.....
