### ISSUE TITLE
Mod translation updater: S"Hello"-type calls aren't picked up

### ISSUE THREAD

**Issue by rollerozxa** [minetest/minetest#14494]
### Summary

Say you have some code like this:

```lua
minetest.chat_send_all(S"Hello")
```

Omitting the brackets when there is only a single string argument is valid in Lua and is used in mods like i3, but the translation updater doesn't pick up on this.

### Steps to reproduce

Run the script on the above code put in a lua file and try to generate locale with the tool.

**Comment by appgurueu** [comment]
Labeling this as a feature request because strictly speaking the script is "correct" in that it should handle the forms it claims to pick up correctly. Supporting another form (aside with `S'...'` for consistency? and perhaps `S[[...]]`, possibly with equals signs) is a sensible feature request which I support however - I personally like to use this syntactic sugar.
