### ISSUE TITLE
Meaning of empty string as formname is undocumented

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#14528]
Sometimes, you receive an empty string as the `formname` in `on_receive_fields` of nodes and `minetest.register_on_player_receive_fields`.

However, the meaning of this empty string does not seem to be documented in `lua_api.md` right now.

----

I suspect this is what this means:

* In `minetest.register_on_player_receive_fields`, it means something happened in the player inventory formspec
* In `on_receive_fields`, the `formname` is always the empty string

Am I correct?

**Comment by Wuzzy2** [comment]
Related issue: #7005 (which is not about documentation).

Suggested documentation update:

For `minetest.register_on_player_receive_fields`:

> `formname` is an unique formspec identifier set by `minetest.show_formspec`. Special case: The empty string refers to the player inventory.

For `minetest.show_formspec`:

> `formname` must not be empty

For `on_receive_fields` (node):

> `formname` is currently always the empty string. Do not rely on it to identify the form

**Comment by appgurueu** [comment]
> Am I correct?

Yes:

##### `minetest.register_on_player_receive_fields`

The empty string is indeed used for the inventory formspec (see `TextDestPlayerInventory` in `src/client/game.cpp`, testing confirms this).

It should be noted that `formname` is merely unique by convention. Mods can easily mess up here.

##### `minetest.show_formspec`

Indeed we currently allow an empty formname here (!), and this is passed to `register_on_player_receive_fields`. The docs should forbid this so that the empty formname is unique to the inventory formspec.

Side note: We should probably have a warning if the empty string is passed.

##### `on_receive_fields`

The server technically reads form names from the packets, but the form names being written are always the empty string, due to these packets only being produced by calls of the form `m_client->sendNodemetaFields(m_p, "", fields);` in `src/client/game.cpp`.

Side note: The server should probably reject non-empty formnames, unless there's a backwards compatibility reason I'm missing.

(It also doesn't make much sense for a mod to use this name. The formspec will always be the node formspec.)

I've opened a PR: #14601
