### ISSUE TITLE
Linux Mint Freeze

### ISSUE THREAD

**Issue by LWFlouisa** [minetest/minetest#14592]
### Minetest version

```true
Minetest 5.8.0 (Linux)
```

### Irrlicht device

1.9.0mt13

### Operating system and version

Linux Mint 21

### Summary

Minetest takes up a lot of CPU usage similar to the CPU usage found in the Linux Kernel a few days ago.

### Steps to reproduce

When you load up Minetest, after a certain amount of time the operating system will completely freeze, and you wont be able to do anything until the graphics stop rendering. Notably this takes up a lot of CPU usage.

**Comment by Zughy** [comment]
Hi, please provide CPU/GPU info to help us understand the problem better

**Comment by appgurueu** [comment]
> Minetest takes up a lot of CPU usage similar to the CPU usage found in the Linux Kernel a few days ago.

This is confusing: What "CPU usage found in the Linux kernel"? Wouldn't this indicate an issue with your installation rather than with Minetest?

> When you load up Minetest, after a certain amount of time the operating system will completely freeze, and you wont be able to do anything until the graphics stop rendering. Notably this takes up a lot of CPU usage.

Could you be more specific than this? For example, have you excluded the possibility of your system running out of memory and then effectively freezing due to "swapping to death"?
