### ISSUE TITLE
Minetest in Playstation 2

### ISSUE THREAD

**Issue by CuloArdido** [minetest/minetest#14724]
I recently discovered that [TyraCraft](https://github.com/Wellinator/tyracraft) exists (a recreation of Minecraft for the Playstation 2) and I was wondering, how feasible would it be to port Minetest to that console (either using the [Tyra](https://github.com/H4570/tyra) engine or also porting Irrlicht)?

**Comment by rollerozxa** [comment]
PS2 only has 32MB of RAM so it would likely be extremely constrained to port the full Minetest engine to the PS2. TyraCraft can get away with it since they're assumedly writing it from scratch with PS2 limitations in mind rather than trying to shoe-horn a program written for computers where e.g. RAM is more plenty.
