### ISSUE TITLE
`range = 0` still allows players to operate on the node they're inside

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#14742]
### Minetest version

```true
5.8
```

### Summary

Title. I've tried things like `range = -1` and `range = false` but nothing happened. Here a basic example:

https://github.com/minetest/minetest/assets/63455151/845a17fe-94fc-4226-a863-dbcffdc93e50

And here it's when it becomes problematic: the spectate mode of my mod attaches the spectator onto the player, overriding the hand with `range = 0` so there is no way they can interfere with the match (I've left the spectator visible just for the video). However, if they hold down the drop key in 3rd person view and click, they can hit the player because of (I guess) issues with children coordinates (#10304?), that consider them compenetrated with the player; so I had to cancel the damage through `register_onpunchplayer`

https://github.com/minetest/minetest/assets/63455151/b081d46f-9f9b-44ec-9974-0e1e42a64285

### Steps to reproduce

```lua
minetest.register_node("test:ghost_hand", {
  description = "Ghost hand",
  range = 0,
})

player:get_inventory():set_size("hand", 1)
player:get_inventory():set_stack("hand", 1, "test:ghost_hand")
```

**Comment by grorp** [comment]
ref: #6651

**Comment by appgurueu** [comment]
This makes sense, mathematically speaking: If you're inside something, you have distance 0 to it, so you are able to point at it with range 0 (range is inclusive). I also think we should ideally avoid changing this behavior for backwards compatibility reasons.

What we can and should do however is add a special value (`range = false` on the API side of things? negative range?) to disable pointing completely. I tried something like this way back in #10356 but my approach was flawed.

(For this reason, I would technically consider this a feature request rather than a bug. I also think this is a duplicate of the issue linked by grorp.)

---

To prevent players from interfering with the world, you would usually revoke `interact`. It seems that clients without `interact` still can point and interact with things (as far as client prediction is concerned), but the server ignores it (as it should)? That looks like a client prediction bug to me.

P.S.: For now a hacky workaround via the new "pointability" API should be possible. You could give spectators a "hand" which does not let them point players, which you can identify by armor group. (The hand should still have range 0 to degrade gracefully on older clients.)

**Comment by Zughy** [comment]
I don't think I agree, as a modder I expect range 0 not to point at anything, but debating over mathematics would probably counterproductive. I'd de a fan of -1.

About the hacky suggestion.. Yeah, that's a pass

**Comment by Wuzzy2** [comment]
This is a duplicate of #6651. Because you're essentially requesting the same thing as that one.

**Comment by SwissalpS** [comment]
As a minetest modder, I expect range = 0 to be the origin node. range = 1 are the eight nodes around it.

I also prefer negative range to disable rather than changing type to boolean.
That is, if there isn't a better solution such as revoking interact for spectators.

**Comment by Zughy** [comment]
> if there isn't a better solution such as revoking interact for spectators

I honestly don't want to mess with a privilege such as `interact`, I find `range = -1` to be a cleaner solution. But, well, closing in favour of 6651
