### ISSUE TITLE
Add a option on android to allow double click emulate the left click instead of the hold click

### ISSUE THREAD

**Issue by sotha1** [minetest/minetest#14756]
### Problem

Hold click is often too bad to play on mobile (e.g. when you are fighting with a monster, you have to hold to attack and that's not fast as it could be.) so, if you double click instead of it, you can fight much faster.

### Solutions

add a option in the menu to enable this (but not enable as default, once when you want to build fast you will tap the screen multiple times and this will emulate the left click), so just enable it sometimes when necessary

### Alternatives

other solution: to avoid the need of go to menu to enable this, what must be impossible to do in live combat in multiplayer, you can enable a area in the screen that when you touch it, your single clicks will be a left click instead.

### Additional context

(this is a example of the alternative solution)
![minetest double click](https://github.com/minetest/minetest/assets/149703967/99d07188-54c5-45ee-abf0-2b8e2f2c0e0c)

**Comment by grorp** [comment]
In Minetest 5.9.0-dev, you can already punch entities/players with short taps instead of long taps by default, so being able to punch with double-tap wouldn't be useful.

If you want to try it, you can find the latest build at https://github.com/minetest/minetest/actions/runs/9528603560. The APKs are not signed, so you have to sign them before you can install them.

**Comment by sotha1** [comment]
thank you, that's pretty good.
