### ISSUE TITLE
Default and minimum of `repeat_dig_time` introduces regression

### ISSUE THREAD

**Issue by AsumFace** [minetest/minetest#14776]
### Minetest version

```true
5.8.0-dev (fac9aac82129edd5d77c3aca3e9e6bbf39cc3220)
```

### Operating system and version

Fedora 40

### Summary

Pull request https://github.com/minetest/minetest/pull/14295 introduces the client config option `repeat_dig_time` which implements a type of cooldown for digging. The default and minimum value for this setting are 0.15 s, which unfortunately changes the behavior of tools that have intentionally been made extremely fast. We have been having such tools on the servers Tunnelers' Abyss and Centeria for many years, so it is not a contrived use case.

Seeing that this is more of an accessibility setting, I believe it should not put limitations on the game design by default nor alter useful existing behavior unless a user explicitly desires so.

Changing the minimum and default to 0.0 appear to be sufficient to restore the old behavior while allowing the user to choose a slower value.

### Steps to reproduce

For the purpose of demonstration the game devtest is used and its tool `basetools:pick_mese` altered.

1. Change the values in `groupcaps` in the tool registration from 0 to 0.01 as follows:
```lua
		groupcaps={
			cracky={times={[1]=0.01, [2]=0.01, [3]=0.01}, maxlevel=255},
			crumbly={times={[1]=0.01, [2]=0.01, [3]=0.01}, maxlevel=255},
			snappy={times={[1]=0.01, [2]=0.01, [3]=0.01}, maxlevel=255},
			choppy={times={[1]=0.01, [2]=0.01, [3]=0.01}, maxlevel=255},
			dig_immediate={times={[1]=0.01, [2]=0.01, [3]=0.01}, maxlevel=255},
		},
```
2. Dig anything.
3. Repeat with the commit of the pull request reverted.
4. Observe that digging is much faster in the version prior to the change.

**Comment by grorp** [comment]
Minetest has always set `nodig_delay_timer = 0.15` in case of a dig time of `0.0`. This resulted in inconsistent behavior because it meant that tools with a dig time of `0.01` dug way faster than tools with a dig time of `0.0`.

The PR in question made the behavior more consistent by also applying the minimum of `0.15` in cases where `0.0 < dig time < 0.15`.

The dig time calculation is too hardcoded and there is no way to influence this behavior, so the complaint is justified either way.

> Changing the minimum and default to 0.0 appear to be sufficient to restore the old behavior while allowing the user to choose a slower value.

That's not enough to restore the old behavior. You also have to re-add the special case for `dig time == 0.0`.

While the proper solution would be deharcoding this (somehow?), I suppose restoring the old behavior and documenting its quirks properly is the best thing we can do here at the moment.

**Comment by grorp** [comment]
> An alternative to it would be to add a separate toggle setting for old/new behavior and using `Requires:` to hide the setting value when the old behavior is selected. The advantage of that is that it gets rid of the inconsistency. 

This seems like making things even more inconsistent to me.

**Comment by Desour** [comment]
I think we should have a separate setting for instantaneous (dig time 0) dig delay and overall min dig delay. Torches, mescons wires, and similar nodes have always been special.
(If we had a proper key binding system, where one could also change settings via key press, one could even make something where the player can dig instant-dig nodes faster if a special key is hold.)
