### ISSUE TITLE
Use a DLL for Lua on Windows

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#14797]
### Problem

I've noticed that there isn't a lua51.dll in the /bin/ folder in the Windows release. This means I cannot make MT use a different build of Lua or LuaJIT without recompiling the whole thing. Being able to change the Lua version and implementation is important if you depend on the 5.2 LJ compat mode or new features such as `buffer.encode`.

### Solutions

Ensure that the official build process for Windows spits out a lua51.dll instead of linking it statically. Users can then drop their own replacement or just delete it to use whatever they have installed systemwide.

### Alternatives

There isn't an alternative because `-DLUAJIT_ENABLE_LUA52COMPAT` is potentially mod-breaking and LuaJIT is now a rolling release.

**Comment by sfan5** [comment]
We had to make changes to the Lua source to fix C++ exception/error handling so swapping that with another version is no longer possible.

For LuaJIT I guess static linking was chosen because it's easier. This can be changed to a DLL and you could theoretically replace it when you're careful about choosing a compiler with a compatible calling convention/libc.

As for `buffer.encode` the luajit used by current windows builds is new enough to have it, it's just not available in the sandbox.

**Comment by hecktest** [comment]
Interesting, well, I use 5.2 compat features so I'd run into this regardless. In the meantime I found #14201 which is smoother than 
the mingw buildbot and does produce the DLL by default, so this is more or less fixed.
