### ISSUE TITLE
leveldb randomly not saving changes to map data

### ISSUE THREAD

**Issue by Ryan-Nolan** [minetest/minetest#1479]
So this issue has been affecting our server for a couple of week now. 
At first we though it was lag, so we moved to a bigger server but the issue still persisted. 

Its hard to explain so ill explain it the way I did to VanessaE: 

Let say we have a building its already been saved, etc, then we go build let say a new wall in there, I go away from the building for a few minutes, come back and the new work I did is gone, almost like the client didn't send the data to the server.  this is where it gets weird. the data is definitely getting sent to the server because other players can see exactly what I see. 

So to be clear, it is not the issue where chunks are being regenerated otherwise the entire building would be gone. It is actually failing to save. 

The annoying bit is that it is its random it doesn't always happen and I cant find a patterned as to when it happens, so I cant reproduce it on demand. 

When it happens though it isn't just one user that affected. all the users playing at that time are affected. 

All other data still saves fine. inventory and player data etc.

**Comment by ERIIX** [comment]
Just happened to me on 0.4.13 (Debian build from jessie-backports).  Quite frustrating.

For me, I could get the database working again by killing the server, then using LevelDB's repair function from Python.  If you have the LevelDB module installed, it's as simple as "import leveldb;leveldb.RepairDB(location)", where location is the map.db directory in the world that won't save correctly.

As far as I can tell, I've only lost the changes since that started happening, and nothing that was already there was corrupted, but I'm planning to hold onto a backup from less than an hour before it started just in case.  I don't know any way to merge data back in, but I can always open multiple clients and rebuild what I see.

One more note for anyone the repair command doesn't work for (hopefully nobody):  If you're looking through your backups to find where it started, "minetest --server --migrate sqlite3 --world location", where location is the world restored from backup, appears to always return an error immediately when the corruption has occurred, even if the actual migration would take a good bit of time, so that's a quick and easy way to identify backups that occurred after the corruption began.

**Comment by Ryan-Nolan** [comment]
I believe this can be closed now? Its not been mentioned in over a year and half. and I've not experienced it since... I'l close this but if anyone has this experience... feel free to re-open it
