### ISSUE TITLE
Don't deprecate Redis (discussion)

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#14822]
### Problem

#14679 deprecates Redis as a database backend; is it expensive to keep around? I can't find any discussion on this.

Yes, Redis (or Valkey) makes no sense to use locally on the same machine as the MT instance, but it's ridiculously scalable when used as a networked DB. I've discovered Redis recently and wanted to use it for all game data that isn't the MT world itself; I didn't even know it was a supported map backend until now. If the Redis support is kept, I'll be able to keep the non-map data in the same cluster as the map and have one huge thing less to worry about.

PostgreSQL isn't a good replacement for Redis because PostgreSQL isn't Redis, it's an SQL database. Redis is Lua-programmable and that makes it uniquely very compatible with MT mods; advanced users can offload some processing to the database cluster itself. I think it's a huge loss to get rid of this. I'd say it's the "fattest" DB backend available, it's not for someone's Pi home server but it's exactly what I need.

### Solutions

Keep Redis around unless there's a very good reason not to.

### Alternatives

Programmable database engine API that lets people implement any storage layer they want. I'm fine re-adding Redis support as user code, though that sounds a bit dumb when the code already exists.

### Additional context

If there's a significant cost to maintaining this, I'm willing to fund bounties.

**Comment by Warr1024** [comment]
Ironically, Redis has one of the simplest protocols of any backend, i.e. with the thinnest abstractions, and given that MT used very few features of any database it uses as a backend, it's one of the most promising ones to emulate.  This made Redis the best candidate for implementing pluggable storage backends externally.

Minetest deserves pluggable storage backends, whether internally or externally.  Either of hacks' proposed solutions would work for this.

**Comment by lhofhansl** [comment]
Redis does not make sense for MT, nobody should use it, so let's remove it.

If we want a simple API for pluggable - which I agree with - that's a different topic and shouldn't lead to keeping a bogus backend around.

**Comment by sfan5** [comment]
> is it expensive to keep around? I can't find any discussion on this.

The maintenance cost is close to zero. 

> but it's ridiculously scalable when used as a networked DB.

Which concrete benefit does this translate to when used with MT? I can't tell.

> Redis is Lua-programmable and that makes it uniquely very compatible with MT mods; advanced users can offload some processing to the database cluster itself.

This sounds cool and interesting but I see zero opportunity to use this with the map data.
Note that the backend is not supported for any other types such as mod storage. Any mods wishing to do that would have to use their own redis binding anyway, so that's not a reason to keep it in the engine.

> Programmable database engine API that lets people implement any storage layer they want.

fully agree with what @lhofhansl said for this point

> How is a key-value database less fitting for the job than a relational one?

(nobody said this)

> When do we ever iterate over the blocks with the need to filter them by content?

minetestmapper actually performs better on a Postgres backend because we store `x`, `y` and `z` as columns instead of a single mangled number, which enables filtering for areas directly in SQL.
This would be an useful change to implement in the sqlite backend too. I can even think of a few cases where the engine could use this for a speedup.

**Comment by sfan5** [comment]
That's pretty nontrivial given you will need to write a full map data decoder outside of Minetest.

But sounds like boils down to "it's convenient because I'm using it anyway". Given the situation I can think we can keep it.

Pluggable backends aren't easy since you need one (or better several) new Lua states to avoid blocking the main thread and then that also necessarily needs access to `require`. Alternatively you have a .dll or .so, which is even less accessible.

**Comment by nerzhul** [comment]
note: unlogged tables on postgres can achieve a very huge performance gain, with some possible data loss
appart that, keep or remove, i have no concerns, i'm the original dev which provided postgres to replace redis to have strong database engine for servers, at the era where redis and sqlite were the only available
