### ISSUE TITLE
Add Verification of map.sqlite Sanity Before Starting a Game

### ISSUE THREAD

**Issue by MetaNomad** [minetest/minetest#14887]
### Problem

Continuing to play with a corrupted database can cause significant issues down the line, as players might not realize that their progress is being made on an unstable foundation. This can lead to substantial loss of work and frustration when the corruption is finally discovered.

### Solutions

I propose adding a verification step to check the sanity of the map.sqlite database before starting a game. This check could be implemented as an optional feature, allowing players to enable or disable it based on their preferences and resource availability.

Benefits

- Prevention of Data Loss: Early detection of database corruption can prevent players from losing significant amounts of work.
- Improved User Experience: Players can be alerted to potential issues before they invest more time in a potentially unstable world.
- Optional Feature: By making this an optional feature, players can choose to enable it if they are concerned about database integrity, without affecting those who prefer faster startup times.

### Alternatives

- Manual Integrity Check Tool: Provide a standalone tool or an in-game option that allows players to manually run an integrity check on their map.sqlite database whenever they suspect an issue.
- Warning System on Crash: Implement a system that logs crashes and suggests a database check on the next startup. If the game crashes unexpectedly, it could recommend running a verification before continuing.
- Enhanced Logging and Alerts: Improve logging around database interactions and provide alerts if unusual patterns are detected that might indicate corruption.

### Additional context

Recently, [I experienced a situation where a sudden power outage interrupted my Minetest game](https://forum.minetest.net/viewtopic.php?t=30812). Upon restarting, everything seemed fine, and I continued playing and building. However, I later discovered that my map.sqlite database was corrupted due to the abrupt interruption [EDIT : No, it came from a bad configuration of my backup tool, see below]. Unfortunately, Minetest allows continued gameplay with a corrupted database, which led to further complications as I unknowingly built upon a corrupted world.

**Comment by appgurueu** [comment]
Please refrain from "improving" your issues using AI generated boilerplate.

Your issue is very vague: What kind of "corruption" specifically are you referring to? How does it manifest, how can it be detected?

Ensuring ACID compliance is the job of the database (in this case, SQLite), and SQLite is known for being very good at this. We could hardly hope to do a better job.

The problem is however that we don't exactly use SQLite properly: We'd have to guarantee that consistent map states are updated in one big transaction, which I don't think we're currently doing properly - among other things, we have multiple database files, which can get out of sync (though at least they're somewhat independent) - and which might also come at a performance cost.

If we were able to "detect" a corruption caused by this, we should also be able to fix it, meaning I don't see the point in this issue yet.

**Comment by SmallJoker** [comment]
Mapblocks of map version >= 29 are currently compressed with `compressZstd`, older ones with `compressZlib`.

Example: https://github.com/facebook/zstd/blob/dev/examples/streaming_compression.c#L18

All we might need to "fix" this is to use `ZSTD_CCtx_setParameter(stream.get(), ZSTD_c_checksumFlag, 1);` in `comrpessZstd`.

**Comment by MetaNomad** [comment]
Please forgive me, English is not my native language, and I am not an expert in databases.

All I can tell you is that I noticed the "map.sqlite" file of my game was corrupted using the command `$sqlite3 map.sqlite "PRAGMA integrity_check;"` which returned errors like:

```
On tree page 99135 cell 251: 2nd reference to page 131357
On tree page 99135 cell 249: Rowid 23819277 out of order
On tree page 99135 cell 239: Rowid 23819048 out of order
On tree page 99135 cell 239: 2nd reference to page 131356
On tree page 2459 cell 7: Rowid 23819647 out of order

```
With the message `Error: stepping, database disk image is malformed (11)`

It's not a big deal, it was due to a sudden power outage that must have interrupted while the file was being handled.

I am simply stating that the game allowed me to continue playing on this file despite this. It was by observing very strange behaviors (map blocks "disappearing", empty chests, etc.) that I decided to investigate. I have an automatic backup of my world every 3 hours, and by checking each backup, I realized that for several days all my backups had the same error `Error: stepping, database disk image is malformed (11)`. 

I don't have enough knowledge in SQL or C to know what should be done. Only that as a player, I would have preferred to be warned that something was wrong with the "map.sqlite" file rather than being allowed to continue playing.

**Comment by appgurueu** [comment]
Thanks for the additional information.

As Krock pointed out, SQLite with default settings should be robust against such corruption. Could you share your database settings? Have you perhaps changed them to obtain better performance (at the cost of robustness)?

Minetest could run `PRAGMA integrity_check;` or the cheaper (but less thorough, though it should be sufficient to detect your corruption here) `PRAGMA quick_check;` itself. That should be fairly simple to implement (though I would argue that if this is due to changed database settings, it is the admin's responsibility to run these checks, potentially themselves). But first, we should get to the bottom of your issue.

**Comment by MetaNomad** [comment]
I just tried the `PRAGMA quick_check;` command and it gives the same error message as `PRAGMA integrity_check;`, so I imagine that this simple check should be enough.

I haven't changed anything in the database settings (in fact, I don't even know how to do that). I'm using Minetest 5.8.0, which I compiled on Debian 12. I haven't made any modifications, except for adding numerous mods, sometimes of questionable quality.

For my initial problem, it seems that multiple entries with the same 'pos' were the issue. I resolved it by dumping the corrupted file and removing the duplicates. But since I didn't know how to decide which of the two entries to keep to recover the buildings I had constructed over several days, I also dumped the latest backup for which the integrity test returned "ok", then compared the entries to keep those that were most different from the old backup. When there was no corresponding reference in the old backup, I chose to keep the one whose BULK had the greatest complexity, assuming it was the expected result of a mapchunk where I had made constructions. This was done [with the help of a Python script that I shared on the forum](https://forum.minetest.net/viewtopic.php?t=30812).

But I did all this just because I really wanted to recover the buildings I had constructed in the past few days on the corrupted file. If the game had warned me that the map.sqlite file was problematic right away, I would have simply restored the latest backup without looking further.

Unfortunately, regarding the initial problem, I didn't create a ticket because I "suspect" it was due to the power outage (the date and time match), but in fact, I don't know for sure. I made many other changes, tested dubious mods, and restored backup several times during that period, so I am unable to provide truly useful information to determine what really happened.

I just found it abnormal that the game could launch despite a corrupted database, not only for an admin but also for a regular singleplayer user, that was the point of the ticket.

**Comment by appgurueu** [comment]
Well, first of all, what were the implications of the corrupted database? Did this cause end user issues further down the line?

I just ran `PRAGMA synchronous;` on a `map.sqlite` and this produced the default of `2` which should be "safe", so I am somewhat confused.

If you still have a copy of the corrupt DB file: Have you tried `.recover` in the `sqlite3` CLI?

Since you state that you are making and restoring backups: How are you creating these? (You need to be careful here, or your backups may be inconsistent.)

Relevant: [How to corrupt a SQLite database](https://www.sqlite.org/howtocorrupt.html). Highlighting some points:

* Backup or restore while a transaction is active
* Deleting a hot journal
* Mispairing database files and hot journals
* Disk drives that do not honor sync requests

It seems that at least some points can't be expected to be remedied by users, so an option to check the database file on startup seems sensible.

In the meantime, you could write yourself a startup script for Minetest like so:

```bash
if [[ $(echo "PRAGMA quick_check;" | sqlite3 ~/.minetest/worlds/myworld/map.sqlite) == "ok" ]]; then
    minetest --server --worldname myworld
else
    echo "database is corrupt, restore from backup"
fi
```

**Comment by MetaNomad** [comment]
Okay! I spent hours digging my logs, and I think I figured out where my problem came from! I use rsync for my backups, and I misconfigured it, which resulted in a temporary '.sqlite-journal' file getting mixed up with a .sqlite file from a different backup (I didn't know that sqlite used such temporary files). So you were right, the problem was indeed on my end, my bad.

Regarding the integrity check, yes, I had already created a script that ran with my backup.

Indeed, it was due to user error, so if you believe that the game itself is not meant to fix my stupid mistakes, feel free to close the issue.

Thank you for your involvement.

**Comment by appgurueu** [comment]
I'm glad you were able to get to the bottom of this :)

I don't think having Minetest run a consistency check on the database is a good way to tackle this. Since this would increase load times (requires a full database scan) and is of interest probably only to a few server owners who have reason to suspect that their map might be corrupted, it would have to be an off-by-default option.

But then it wouldn't help identify cases like yours, since an unsuspecting user wouldn't enable the setting to begin with. 

The "power users" (who may need this due to explicitly enabling DB features which put the DB at risk of corruption) are also unlikely to benefit from a Minetest feature, since they can (and may prefer) to solve this using a simple (and perhaps more versatile) script like the ones you and I wrote.

So all in all I think this feature isn't necessary.

What we might try to do however is getting the SQLite backup wisdom written down somewhere, be it in this repo or someplace else where server owners find it.
