### ISSUE TITLE
add a way for mods to register placeholders for `minetest.format_chat_message`

### ISSUE THREAD

**Issue by boulbousNaranha** [minetest/minetest#14930]
### Problem

Currently a lot of mods that want to add chat prefixes like factions, ranks etc do so by registering callbacks
in `minetest.register_on_chat_message` that override the default chat behavior. These mods break every other mods that registers on `minetest.register_on_chat_message`, like my mod that considers messages starting with an "!" as special command or any other mods that try to change the message format

### Solutions

Mods should be able to register placeholders for the `minetest.format_chat_message` function

```lua
minetest.register_placeholder("rank", function(name, message)
  return "admin"
end)
```

now if the `chat_message_format` setting is set to `[@rank <@name> @message]` the messages would always get
prefixed with `[admin]`

### Alternatives

none that i can think of

### Additional context

The `chat_message_format` setting is global and other worlds might not have those prefixes defined, so each message would get prefixed with `[@rank]` in this case

Mods that define placeholders would require an additional install step by the user manually setting `chat_message_format`

IMO these issues aren't a big deal since this is something that only server owners would do, and they dont change worlds often and configuring the settings shouldnt be an issue for them

**Comment by appgurueu** [comment]
> These mods break every other mods that registers on `minetest.register_on_chat_message`

This is only true of carelessly written mods. There are multiple (slightly hacky) things mods can already do here (but some don't):

* Try to register their callback *as late as possible*, so e.g. your callback that gets run on `!<msg>` wouldn't be affected if it is registered "early enough". One way to achieve this is to optionally depend on mods that register such callbacks who should register them first, another popular one is to register inside on mods loaded (which may break if multiple mods do this).
* Run *subsequent callbacks themselves*. The `minetest.registered_on_chat_messages` table is there, you can run the following callbacks yourself.

> or any other mods that try to change the message format

Why can't all of these mods override `minetest.format_chat_message(name, message)`, calling into the previous definition?

> Mods should be able to register placeholders

I'm not very convinced implementing this in the engine is the way to go; if you think this is a good API for mod interop to agree upon, why not standardize it via a library mod (analogeous to e.g. player monoids for example)?

Furthermore, I'm not convinced this really solves the problem, because as you note

> Mods that define placeholders would require an additional install step by the user manually setting `chat_message_format`

... which is basically just pushing the problem to the user; and if mods tried to set `chat_message_format` themselves, we'd be back to square one.

**Comment by boulbousNaranha** [comment]
> This is only true of carelessly written mods. There are multiple (slightly hacky) things mods can already do here (but some don't):

Most mods dont do these, most likely because this isnt documented/recommended anywhere. `ctf_chat` is the only mod i found that does this. IMO having to think about the load order or having to run all the callbacks yourself is a bad API and most modders will ignore it (like they do right now)

> Why can't all of these mods override minetest.format_chat_message(name, message), calling into the previous definition?

they can but they either:

- implement their own placeholder, which has the same problems as my solution
- ignore the `chat_message_format` setting and append/prepend what they want. IMO this goes against the point of having `chat_message_format` in the first place and the format is decided by load order

> I'm not very convinced implementing this in the engine is the way to go; if you think this is a good API for mod interop to agree upon, why not standardize it via a library mod (analogeous to e.g. player monoids for example)?

Well i thought implementing things in the engine is the best way to standardize and it fits in the engine since it just opens up an API for what the engine already did with the `@message`, `@name` and `@timestamp` placeholders 

> >Mods that define placeholders would require an additional install step by the user manually setting chat_message_format

> ... which is basically just pushing the problem to the user; and if mods tried to set chat_message_format themselves, we'd be back to square one.

Yeah this is a shortcoming of this solution. My excuse is that this is only something that server admins use, so a little configuring isnt a big deal in this case.
I thought of a hacky way to overcome this though,
if `chat_message_format` is set to its default value, all placeholders would would be prepended before the player's name. This means that things work out of the box but users have the option to set the order/remove placeholders they want
This could be a problematic for mods that want to add placeholders after the player's name or message, but i cant think of a mod that would do this
