### ISSUE TITLE
regression: minetest.hud_replace_builtin("health", nil) throws an error in the latest 5.9.0 release of Minetest

### ISSUE THREAD

**Issue by Splizard** [minetest/minetest#14965]
### Minetest version

```true
Minetest-5.9.0
```

### Operating system and version

All

### Summary

In prior versions of Minetest, hud elements could be removed by passing `nil` as the definition. In Minetest 5.9.0, there appears to be a breaking change that causes mods depending on this behaviour (to configure HUD on startup) to raise an "assertion failed!" error.

```
ModError: Failed to load and run script from C:\Games\minetest-5.9.0-win64\bin\..\games\buildacity\mods\builda\init.lua:
C:\Games\minetest-5.9.0-win64\bin\..\builtin\game\hud.lua:99: assertion failed!
stack traceback:
	[C]: in function 'assert'
	C:\Games\minetest-5.9.0-win64\bin\..\builtin\game\hud.lua:99: in function 'hud_replace_builtin'
```

### Steps to reproduce

`minetest.hud_replace_builtin("health", nil)`

**Comment by appgurueu** [comment]
Could reduce this to a warning, but really this is a mistake on the modder's part which should be brought to their attention, so I don't think a crash is inappropriate, especially since our docs never explicitly allowed passing `nil` here. Might want to improve the error message.

The correct mechanism to disable builtin HUDs is via HUD flags.
