### ISSUE TITLE
Touchscreen autodetection regression

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#14973]
### Minetest version

```true
5.9.0
```

### Operating system and version

Windows

### Summary

* Some Windows users are reporting that touchscreen controls are enabled by default for them. Just because their laptop has a touchscreen doesn't mean that touchscreen controls should be enabled by default. Instead, controls should be enabled on touchscreen interaction on these platforms: #14542

See #14400

**Comment by sfan5** [comment]
> Some Windows users are reporting that touchscreen controls are enabled by default for them. Just because their laptop has a touchscreen doesn't mean that touchscreen controls should be enabled by default.

Since this was literally brought up we should have been more careful about merging a change that is incomplete without further work.

**Comment by grorp** [comment]
> * Touchscreen autodetection doesn't depend on SDL, meaning that controls are getting enabled for non-SDL builds. This should be disabled and the touchscreen controls setting ignored

This only affects Windows. Touchscreen autodetection on Linux can stay without SDL, since CIrrDeviceLinux supports touch.

If it was only this, I'd just replace

https://github.com/minetest/minetest/blob/dc7a7a0ed98e10f80c7ca5ce071300ada7922eab/src/defaultsettings.cpp#L80

with

```cpp
#elif USE_SDL2 && defined(_WIN32)
```

> * Some Windows users are reporting that touchscreen controls are enabled by default for them. Just because their laptop has a touchscreen doesn't mean that touchscreen controls should be enabled by default. Instead, controls should be enabled on touchscreen interaction on these platforms: #14542

We should probably remove the Windows touchscreen autodection code completely, at least in its current state. Unlike the Linux code which looks for device type, it looks for touchscreen presence.

**Comment by rubenwardy** [comment]
> If it was only this, I'd just replace

I think we also need to make sure "Touchscreen" settings are hidden on unsupported platforms and the touchscreen setting is completely ignored
