### ISSUE TITLE
Duplicate entries for installed mods in Content Tab/Mod Select (+ other problems)

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#15004]
### Minetest version

```true
Minetest 5.10.0-dev-debug-48845de46 (Linux)
Using LuaJIT 2.1.1720049189
Built by GCC 14.2
Running on Linux/6.10.4 x86_64
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Summary

![image](https://github.com/user-attachments/assets/00a36bb2-accb-4055-896d-b5bdba2f4c40)
![image](https://github.com/user-attachments/assets/0e62528e-379d-4f1d-8aee-bdaa7324d686)

### Steps to reproduce

Install something from CDB, maybe on a fresh MT instance

**Comment by sfan5** [comment]
caused by 1fb49e9ca7c66251503be47608243f124061bf44 / #14905

This also causes modpacks to not show as enabled in the mod selection menu:
![grafik](https://github.com/user-attachments/assets/126b9c15-269e-42ed-871d-7f4d70af6414)
(in fact it's also duplicate there but neither of them are shown in green)

it also causes mods to not load apparently: https://irc.minetest.net/minetest-dev/2024-08-18#i_6193560

the root cause is that for `RUN_IN_PLACE=1` builds the share and user path for mods is identical.
