### ISSUE TITLE
Deprecation warning on minetest.close_formspec() call

### ISSUE THREAD

**Issue by jeremyshannon** [minetest/minetest#15011]
### Minetest version

```true
Minetest 5.9.0
```

### Operating system and version

Devuan Daedalus (eq to Debian Bookworm)

### Summary

A warning of `Deprecated call to `minetest.show_formspec`:`formname` must not be empty (at ...p/minetest-master/bin/../games/Exile/mods/lore/login.lua:94`
is caused by the following on line 94:
` minetest.close_formspec(playername, "") -- forcibly close the previous fs`
but the lua_api says:
`to close a formspec regardless of the formname, call     'minetest.close_formspec(playername, "")'`

Background: I discovered that if a player had opened a formspec, like inventory or whatever, it would prevent Exile from opening its formspecs, which could break the login queue (that shows the intro text and does a few other things) and leave them stuck in a pre-spawned state, waiting for them to close a formspec that never appeared.
 Ensuring that all formspecs are closed before displaying the important ones was the only fix for that which worked.

### Steps to reproduce

Do what the lua_api says to do in order to close any open formspec

**Comment by appgurueu** [comment]
Sorry for causing this, I was not aware that `show_formspec` was in fact used to implement `close_formspec` when I added this deprecation warning. I should have been more careful. I have opened a PR to fix it.

> Background: I discovered that if a player had opened a formspec, like inventory or whatever, it would prevent Exile from opening its formspecs

This is weird, are you still able to reproduce this? For me, showing a formspec supersedes the inventory formspec. You shouldn't have to use `close_formspec` for this (though it is very possible that due to other bugs you do in fact have to).

**Comment by jeremyshannon** [comment]
I'll try again with 5.9.0, but it was difficult to make it happen. It happened most often to folks on android clients (multicraft?), but I was able to do it a couple of times before.
 It might have been the letter formspec rather than inventory?
