### ISSUE TITLE
Allow remote authentication via federation

### ISSUE THREAD

**Issue by Darin755** [minetest/minetest#15082]
### Problem

Right now a player has to create a new account on each server. This can be tedious and can even open the door up to impersonation and username conflicts. Ideally there should be a way to create an account on one server and then use it on other servers. This could also be used for #5813

### Solutions

I think it could work like the following:

1. A user selects a server (server B) they would like to join that they do not have an account on
2. A user checks a box and enters the server URL (server A) that they have an account on
3. A user can login to server B like it was server A

Behind the scenes there would need to be some cryptographic magic. First off, **user passwords should never be sent to a different server**. 

**Idea 1:**
What should happen is that server B sends a authentication request to server A. Server A should then send a random bit of data. Server B should then sign/encrypt the data with the password and send it back. Server A then can check the password. The key is that if server A or rather something masquerading as server A could not get the password. I don't like the approach for several reasons but the biggest one is that it involves trusting server B which is very problematic. Also someone could stand up a fake server A that accepts all authentication requests.

**Idea 2:**
 - TBD
 - The cryptography should happen client side with both server A and B having ways of verifying identity. This is obviously very tricky.

### Alternatives

Minetest could setup a centralized account server. This would make account management easy and would allow for compliance with laws like the GDPR. However, this is also a central point of failure and could end up running into legal trouble. It also cost money.

### Additional context

It also would be nice to have user metadata like appearance and what not.

**Comment by Darin755** [comment]
Related: #5813 #10961 #10206  #1566

**Comment by red-001** [comment]
Servers can already federate by sharing their login database. There's nothing technical holding it back apart from - perhaps - the requirement the login name, is the same as the player name, is the same as the user identifier.

I would take the lack of federation among servers now as indicating server owners-operators don't want federation. Supporting custom login extensions might be more useful, can use that for federation if someone wants to, or something more immediately useful like password reset functionality.

**Comment by appgurueu** [comment]
> Server A should then send a random bit of data. Server B should then sign/encrypt the data with the password and send it back. Server A then can check the password.

We're using SRP. Server B doesn't (and shouldn't) know the password.

> Also someone could stand up a fake server A that accepts all authentication requests.

This issue is inherent to any kind of federation where you trust another server with auth. Servers would need something they derive trust in other servers from.

**Comment by Darin755** [comment]
> > Server A should then send a random bit of data. Server B should then sign/encrypt the data with the password and send it back. Server A then can check the password.
> 
> We're using SRP. Server B doesn't (and shouldn't) know the password.
> 
> > Also someone could stand up a fake server A that accepts all authentication requests.
> 
> This issue is inherent to any kind of federation where you trust another server with auth. Servers would need something they derive trust in other servers from.

Yeah it is definitely a hard problem to solve

**Comment by AFCMS** [comment]
I have wanted something like that for a long time.

What I ideally want is a way to have Minetest servers use an external server doing authentication. It would allow building things like having to create an account on a web service (with all account stuff, like email verification, password reset, etc) and then having Minetest servers relying on this service to validate user/password. And also using a single service to authenticate to multiple Minetest servers.

There is some kind of way to override the [authentication handler](https://github.com/minetest/minetest/blob/master/doc/lua_api.md#authentication-handler-definition), and I tried implementing something like that a long time ago, but it can't be done with enough flexibility for the user and developpers (IIRC you are forced to "ignore" the builtin features using ugly hacks instead of having a proper way of disabling them, for exemple the clients shouldn't have the register button if registration can't be handled by the minetest server. Currently best you can do is throw an error message at the player if they try this.)
