### ISSUE TITLE
async mapgen memory leak

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#15169]
### Minetest version

```true
Minetest 5.10.0-dev (Linux)
Using LuaJIT 2.1.0-beta3
Built by GCC 11.4
Running on Linux/6.10.10 x86_64
```

### Irrlicht device

X11

### Operating system and version

Ubuntu 22.04

### CPU model

AMD Ryzen 7 7840HS

### GPU model

Radeon 780M

### Active renderer

OpenGL 4.6

### Summary

Using new async mapgen feature seems to have a memory leak.

### Steps to reproduce

Using new async mapgen feature to generate cocoa pods in yesterday's farming redo, created new world with mod enabled and flew in a straight line, memory quickly shot up to over 1GB usage and climbing.

Reverted to older on_generated function to generate cocoa pods, enabled mod in new world, flew straight and memory slowly went up and sat around 600mb.

This is the commit from yesterdays release using async to today's revert which works fine:

https://codeberg.org/tenplus1/farming/commit/e3bf5f92a7d6faccce0f6e0f8569d43d20ddf897

**Comment by SmallJoker** [comment]
Using `/emergeblocks here 150`

master: 564 MB, completed after 4414 ms
farming redo @ commit e3bf5f9~1: 1.4 GB, completed after 10494 ms
farming redo @ commit e3bf5f9: 604 MB, completed after 9750 ms

**Comment by Desour** [comment]
You're not calling `get_light_data()` in the fine working version.
You'd normally have a global `data` variable for it:
```lua
local data
minetest.register_on_generated(function(vmanip, minp, maxp)

	--if maxp.y < 0 then return end

	local min, max = vmanip:get_emerged_area()
	local area = VoxelArea:new({MinEdge = min, MaxEdge = max})
	
	data = vmanip:get_light_data(data)

	-- Eliminates the high RAM usage. Comment to provoke.
	collectgarbage("collect")
end
```

**Comment by tenplus1** [comment]
@SmallJoker - Does collectgarbage("collect") only clear the memory used inside that function or everything ?

**Comment by SmallJoker** [comment]
@tenplus1 It frees the garbage of the entire Lua instance, hence do not overuse it.

More importantly: make use of the additional argument pointed out by @Desour : `data = vmanip:get_light_data(data)`. That will limit the memory usage to a single re-used table (per Lua instance), resulting in lower memory usage and decreased need to run the garbage collector at all.

**Comment by appgurueu** [comment]
While Desour is right that modders can be conscious about allocations, many won't be (consider e.g. the example code linked in this issue, though assuming jungle trees are sparse enough it should be fine), and more sophisticated mapgens might require plenty of allocations. We're offering GC'd scripting, so we should make sure that works well (while of course also enabling modders to minimize GC load via the appropriate APIs).

`collectgarbage("collect")` is an ugly workaround since it's hard to tune properly, especially when the necessary variables are unknown. A better idea to tune the GC would be to use `collectgarbage("setpause", ...)` and `collectgarbage("setstepmul", ...)`. We could try to set some more aggressive defaults here.

Yet I'm hesitant to chalk this up to poor GC tuning. LuaJIT's `luaconf.h` defines the following defaults:

```c
#define LUAI_GCPAUSE	200	/* Pause GC until memory is at 200%. */
#define LUAI_GCMUL	200	/* Run GC at 200% of allocation speed. */
```

Based on these I would expect to see 2x, maybe 4x the memory usage vs live memory. But what we're seeing is much worse. Essentially, there is at most one live `data` table at a time. With `collectgarbage("collect")`, I'm seeing a consistently reasonably low memory usage of about 24 MB. But without it, essentially no GC seems to happen:

<details>

```
12387.313476563
23364.375976563
34341.438476563
45318.500976563
56295.563476563
67272.625976563
78249.688476563
89226.750976563
100203.81347656
111180.87597656
122157.93847656
133135.00097656
144112.06347656
155089.12597656
166066.18847656
177043.25097656
188020.31347656
198997.37597656
209974.43847656
220951.50097656
231928.56347656
242905.62597656
253882.68847656
264859.75097656
275836.81347656
286813.87597656
297790.93847656
308768.54003906
319745.60253906
330722.66503906
341699.72753906
352676.79003906
363653.85253906
374630.91503906
385607.97753906
396585.04003906
407562.10253906
418539.16503906
429516.22753906
440493.29003906
451470.35253906
462447.41503906
473424.47753906
484401.54003906
495378.60253906
```

</details>

**Comment by hlqkj** [comment]
Re-using allocated memory is (or should be, apparently) basic knowledge. Re-using tables to work on map data when using the VoxelManip in Lua mapgens (and not only map data actually) is basic knowledge as well, it's well documented, and it has been widely known since... always. (E.g. [here](https://forum.minetest.net/viewtopic.php?t=16043).)

So is this *really* a bug, or is it just the Lua's GC trying to do its job? Do we really need stuff like this:

> We could also do additional explicit time based collectgarbage calls.

(which could actually worsen the performance of well-written code) just to run after badly coded mods?

**Comment by kromka-chleba** [comment]
>Re-using allocated memory is (or should be, apparently) basic knowledge. 

You mean C++ or what? The API is written in Lua and I expect garbage collection to work.

>(which could actually worsen the performance of well-written code) just to run after badly coded mods?

Lua is a garbage collected language. I don't see anything that implies "bad coding" in the minimal reproducer posted by SmallJoker.

>So is this really a bug, or is it just the Lua's GC trying to do its job?

From what I can see in the minimal reproducer posted by SmallJoker, yes this is indeed a bug. The function only uses local variables and yet the GC doesn't collect garbage.

**Comment by hlqkj** [comment]
> The function only uses local variables and yet the GC doesn't collect garbage.

Then my understanding of [this](http://lua-users.org/wiki/OptimisingGarbageCollection) was wrong - apologies:

> Question: Basically I want to minimise the amount of temporary memory being allocated, so that I can reduce the frequency GC is called (and maybe reduce the hit of each GC?). Can anyone give some hints on this topic? For instance, if I have local variables declared inside function A, will the local variables allocate memory each time A is called?
> 
> (ET) No. Local variables are kept on a stack and will not affect the GC. [...]

**Comment by appgurueu** [comment]
A lot to unpack. Let's start with this:

> We could also do additional explicit time based collectgarbage calls.

Not a big fan. If tuned well this could be okay, but I think the `malloc_trim` situation has shown that we are likely to fail at this. I also think time is sort of the wrong variable to tie this to.

Sure, you can ensure that you don't use too much time that way if you have a rough estimate on GC runtime (which you don't), but it can't really work well in general - for example when you're allocating a lot in a short timeframe and the manual `collectgarbage` just isn't kicking in soon enough. And when you're allocating very little over a long timespan it'd be a waste of CPU time (though arguably if tuned well an acceptable one, especially since it's on a separate thread). It'd be a hacky hotfix. I'd much prefer we figure out why the GC isn't working as it should and fix that.

> Re-using allocated memory is (or should be, apparently) basic knowledge. Re-using tables to work on map data when using the VoxelManip in Lua mapgens (and not only map data actually) is basic knowledge as well, it's well documented, and it has been widely known since... always. (E.g. [here](https://forum.minetest.net/viewtopic.php?t=16043).)

First, this knowledge isn't as basic or widespread as it may appear to someone familiar with the matter. The forum thread you linked is half a decade old and full of posts by experienced long-time modders and core devs. I just checked out our docs and from a brief look at documentation surrounding `get_data` I don't see an explicit word of advice to use it, so there is at least a documentation deficiency here. To a user it would seem like `get_data()` is the cleaner API, even. And if GC was working as expected, there wouldn't be much of a problem. Sure, there'd be a slight (but very manageable) performance hit from the unnecessary allocations, but it should all work as expected. A user does not and should not expect using a slightly suboptimal API to result in abysmal memory usage in a GC'd language.

Second, there are all kinds of reasons to do allocations in mapgen code. A mapgen may be using sophisticated spatial data structures for example. A user might construct a vector (and often this isn't even terribly much of a performance concern). Or various other reasons for auxiliary data structures, all of which require you to allocate stuff. And sure, modders should try to minimize this and to optimize their mapgens, but GC should work well by default.

> So is this really a bug, or is it just the Lua's GC trying to do its job?

I will only believe that the GC is doing it's job at all if I see a profile where `collectgarbage("count")` decreases from one step to the next. And even then I will strongly doubt that it's doing it's job properly because the memory usage we're seeing here is multitudes above what I would expect given the GC tuning parameters. In general I expect GC to result in something like 2x memory usage vs live memory.

> I forgot to mention that I'm hosting a server (private) running `musttest_game` which makes extensive use of the async mapgen since when it has been introduced. You can have a look at it yourself to see that when I say extensive I really mean it. No issues with it so far.

That's valuable information, thanks. So either you somehow manage to trigger the GC heuristic (perhaps via multiple smaller allocations?), or you just leak so little that it doesn't end up mattering over the uptime of the server.

It'd be interesting to see whether this is also an issue on PUC Lua 5.1.

**Comment by appgurueu** [comment]
@sfan5 I take it you have been unable to reproduce the issue?

**Comment by sfan5** [comment]
I can, but it's not a memory leak and arguably not a bug (or *our* bug either way).
The memory usage rises, but eventually garbage-collection kicks in:
<pre>
758768.6484375
769745.5546875
780722.4609375
791699.3671875
802676.2734375
813653.1796875
824630.0859375
835606.9921875
846583.8984375
857560.8046875
868537.7109375
879514.6171875
890491.5234375
901468.4296875
912445.3359375
923422.2421875
934398.6015625
945375.5078125
758770.0234375
45273.7890625
56250.6953125
67227.6015625
78204.5078125
89181.4140625
100154.0546875
111130.9609375
122107.8671875
133084.7734375
144061.6796875
</pre>
that is at peak ~950 MB of garbage

We can tag it as (Bug)(Upstream issue)(Can't fix) or (Not a bug) but there is nothing for us to do either way.
