### ISSUE TITLE
Some special char cannot be used in filename of texture

### ISSUE THREAD

**Issue by jingkaimori** [minetest/minetest#15185]
### Minetest version

```true
Minetest 5.10.0-dev-58ea11c-dirty (Windows)
Using LuaJIT 2.1.0-beta3
Built by MSVC 19.40
Running on Windows/10.0.19041 x86_64
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Windows 10 22H2

### CPU model

Amd Ryzon 7 5800U with Raedon graphics

### Active renderer

OpenGL 4.6.0

### Summary

Image files which name containing some special char cannot be used as texture.

### Steps to reproduce

Make sure that `testnodes_name[.png` and `testnodes_name-.png` exists in texture directory.

* `testnodes_name-.png` works;
* `testnodes_name[.png` does not work, result in dummy image;
* `testnodes_name\\[.png` does not work, result in dummy image too;
* `testnodes_name\[.png` does not work, result in error from lua.

Special chars includes `[^`. other special chars in texture DSL cannot appear in file name, such as `:,`.

```lua
minetest.register_node("testnodes:special_file_name", {
	description = S("Texture with special file name"),
	tiles = {{
		name = "testnodes_name[.png",
	}},
	groups = { dig_immediate = 2 },
})
```

**Comment by appgurueu** [comment]
Not a bug. Texture names are intentionally restricted, as they should be, otherwise texture modifiers become even more of a mess than they already are. We *especially* don't want to allow texture modifier special characters like `[` in texture names. There is also practically next to no reason for modders to want to use such special characters. Various escaping schemes that comply with the current name restrictions can be implemented by modders themselves should they be necessary. And Lua rejecting `"\["` is not a Minetest bug, that's just what a sensible programming language does when you feed it an invalid escape code.

https://github.com/minetest/minetest/blob/24efd7dc9146c61fb090420e7619b7c2000fddcf/src/network/networkprotocol.h#L249

This should be documented however, but that is relatively low priority.

**Comment by nininik0** [comment]
This isn't a bug- it's a normal code staple.

**Comment by appgurueu** [comment]
> This isn't a bug- it's a normal code staple.

It is not a code bug, but it is a documentation "bug" (it's undocumented).

**Comment by appgurueu** [comment]
> I'd like to take this issue. How can I help?

https://github.com/minetest/minetest/issues/15185#issuecomment-2360834349 needs to be documented in `doc/lua_api.md`. Probably somewhere in the "texture modifiers" section, which essentially applies to (almost?) all places where we take texture strings.

**Comment by nininik0** [comment]
Yea we need a textures section in the API MD file and it should say stuff abt characters.
This is kinda like normal code not accepting special characters for names, used in the code itself

**Comment by AndyKhang404** [comment]
Sorry for late respond, I got busy with school.
https://github.com/minetest/minetest/pull/15275
Am I doing this right? Did I messed anything up?

**Comment by appgurueu** [comment]
As it turns out this is already documented, albeit not in the texture modifier section:

https://github.com/minetest/minetest/blob/1b2d24791a4b6c625e694db83aa85afb8ed1818f/doc/lua_api.md#textures-sounds-media-models-locale

Thus this issue degrades to "improve documentation because it may be a bit hard to find" rather than "fix something not being documented" at best.
