### ISSUE TITLE
writing to mod directories has valid uses, why deprecate instead of making documentation warning? 

### ISSUE THREAD

**Issue by FatalistError** [minetest/minetest#15184]
### Minetest version

```true
after 5.9
```

### Operating system and version

all

### Summary

My mod generates 3d models at load to dynamically send. These models may be different every time so they exist in a temp folder, switching to a whole new system for purposes such as this seems incredibly redundant. I can imagine that this being a feature can be useful for numerous purposes, why deprecate?

### Steps to reproduce

.

**Comment by sfence** [comment]
Is "minetest.dynamic_add_media" function unusable in this situation?

**Comment by rubenwardy** [comment]
Writable mod directories are detrimental to security and can result in data loss. They also don't work when mods are installed system wide, as system wide directories are read-only.

Minetest now provides a separate persistent writable directory per mod:

```lua
local models_dir
if minetest.get_mod_data_path then
    models_dir = minetest.get_mod_data_path() .. "/tmp"
else
    models_dir = minetest.get_modpath(minetest.get_current_modname()) .. "/tmp"
end
```

**Comment by rubenwardy** [comment]
For more context, see https://github.com/minetest/minetest/pull/14486

**Comment by swagtoy** [comment]
I'm kind of mixed on this, so I'll answer sincerely.

I think there are genuine cases for a mod _STORING_ data. Skins? Sure. Configurations? Certainly. Caching? Moving data between worlds? You name it.

But there are also problems:

1. I have to enter the mods directory to delete data... what?? No!
2. I want 2 worlds to have separate data! Only solution would be to hijack the code or rename the mod, or have the moddev be generous and write his code to work for multiple worlds.
3. Ok, one mod offers a way to clear its data, but what about this other, weirder mod?

So this leads to believe a 2nd, better solution would be preferred. Only thing that comes to mind would be a genuine, real mod storage system, which allows for clearing, separating between worlds, instead of just jotting stuff down into the mods directory. But we have metadata systems and all that, so why don't we just make it simple?

So I support the deprecation, but I do believe a better system for this could be achieved.

**Comment by appgurueu** [comment]
@swagtoy 

* Mod storage is per-world, per-mod k-v storage. This is probably what you will want to use by default.
* Mods can also use `minetest.get_mod_data_path`. This is a decent replacement for writing to the mod folder, especially since dynamic media can now be registered at load time. (Relying on media loading to happen after mod loading was sketchy anyways.)
* Mods can also write to the world folder if mod storage doesn't suit their needs.

So really I don't see much of a problem here. You could argue that some edges may be rough, but there is no limitation that can't be overcome here.

**Comment by swagtoy** [comment]
@appgurueu Yeah, you're correct. I cant justify writing to a mod directory at all though, just some cleaner alternatives.

Mods can indeed fallback to just writing to the world if it suits them
