### ISSUE TITLE
Fix incorrect Documentation for `set_bone_override`

### ISSUE THREAD

**Issue by SumianVoice** [minetest/minetest#15329]
### Problem

The current `lua_api.md` entry for `set_bone_override` is technically incomplete and has undocumented behavior.
https://github.com/minetest/minetest/blob/3f306a407c5efde4640aaee57acadd10ec84f329/doc/lua_api.md?plain=1#L8266
However, this is not quite true; the current wording implies `absolute` is optional and only has the stated behavior if it is set to `false`, but `absolute = nil` has the same behavior as `absolute = false` meaning that values that are `absolute ~= false` can also trigger the behavior.

### Solutions

It should be changed to an equivalent of:
```md
* `absolute`: If set to `false` or `nil`, the override will be relative to the animated property:
    [...]
```

### Alternatives

Or the behavior could be changed so that `absolute` is actually true by default as the docs imply (more work, but I honestly prefer this).

### Additional context

Other parts of the documentation have a similar wording but have the api-stated behavior only. For example node definitions --> `pointable` needs to be `false` to disable pointing, and setting it to `nil` will allow pointing as a default. Raycasts are the same, with optional parameters which need to `== false` to have effects. The current pattern is that if a thing is described as being "if it is false" then it is only if it is false, and setting it to true is optional.

Described more intuitively; if someone says "if you set this to `23` then it will do `X`", you would be surprised if you set it to `-1` and it still did `X`. It's undefined behavior, even if the literal words are not technically 'lying'.

Ideally the whole entry on `set_bone_override` should be more explicit as it is unclear whether e.g. `absolute` should be within the `override` parameter or the `position` and etc parameters, but that's a style and communication issue, not a technical one.

**Comment by appgurueu** [comment]
Thanks for the report. You are right, the documentation has some issues. I've made a PR to fix it: #15353, could you take a look?

> Or the behavior could be changed so that absolute is actually true by default as the docs imply (more work, but I honestly prefer this).

In hindsight so do I, but as it turns out I did document the `absolute = false` default in the table: `{ vec = vector, interpolation = 0, absolute = false }` (though it's easy to miss, so I restated that in the prose), so I'm afraid to change that now due to our backwards compatibility guarantee (though the change would be pretty trivial: `prop.absolute = lua_toboolean(L, -1);` -> `prop.absolute = lua_isnil(L, -1) || lua_toboolean(L, -1)`).
