### ISSUE TITLE
Server meathods of checking client features

### ISSUE THREAD

**Issue by Xeno333** [minetest/minetest#15394]
### Problem

If a server is hosting a game that requires a settings to be enabled, mainly for rendering, there should be some way for the server to check such. For instance, say that a game needs `enable_auto_exposure = true` for weather or the clients `core.features.hotbar_hud_element = true` for UI, this works fine for single_player as all one needs to go is check these fields. 

For a server though there is no way to check these things. Sure they can set a mininum protocol version, but this does not solve rendering setting problems.

### Solutions

On connection clients should send their local `core.features` perhaps attach it to `player:get_client_features()` and pass all `int`, `float`, `bool`, `flags`, `noise_params_2d`, `noise_params_3d`, `v3f` and `enum` settings, excluding `path`, `string` and `filepath` for security/privacy reasons.

### Alternatives

None

**Comment by appgurueu** [comment]
I think it would be better to solve the underlying issue of letting servers set these settings as a game engine should, see #11227 and #13539, which is itself somewhat of an ugly crutch for features that should be API-controlled rather than setting-controlled.

What you're proposing here would only serve as an ugly crutch: Check for bad settings -> warn/kick user -> user must change their *global* settings to fix this.

Consider also:

* Two servers a player plays on doing this => bad UX, they have to change settings every time they want to join a server.
* That a combination of settings might very well be a unique per-user identifier, so this is also something to keep in mind when talking about privacy.

With all of this in mind I think implementing this feature request is not a good idea.

**Comment by Xeno333** [comment]
> I think it would be better to solve the underlying issue of letting servers set these settings as a game engine should, see #11227 and #13539, which is itself somewhat of an ugly crutch for features that should be API-controlled rather than setting-controlled.

I see. I do think that #13539 offers a cleaner solution to the settings part of this problem. It does not though solve the problem I was refering to with `core.features`, now this can faily easily be done by checking protocol version.

> What you're proposing here would only serve as an ugly crutch: Check for bad settings -> warn/kick user -> user must change their global settings to fix this.

This holds as a good point, but for this _is_ the only solution for things that require settings like this. 

I think I will close this though, as if #13539 is implimented then the second part of this issue, `core.features`, can be handeled simply with protocol checks.
