### ISSUE TITLE
Rename IPC and improve documentation

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#15391]
Luanti recently got a feature called "IPC" in the Lua API.

The feature is good but I think the name is misleading. The abbreviation is never explicitly written out in the documentation but I believe IPC was meant to stand for "Inter-Process Communication". This doesn't make sense here since all communication here happens between threads of the same Luanti process. The name "IPC" would make sense if Luanti would communicate to other processes.

I propose to rename the IPC feature.

Some suggestions:

* ITC (=Inter-Thread Communication)
* IWC (=Inter-Worker Communication)
* LMS (=Lua Metadata Sharing)
* ??? (insert your own here)

I also think the documentation is a little bit lacking in the following areas:

* The abbreviation should be written out in full at least once
* It is not clear where the data ends up when calling `core.ipc_get` and `core.ipc_set`. Is it shared between only particular Lua environments or *all* possible Lua environments simultanously?
* `core.ipc_poll(key, timeout)` has a warning that it should be used carefully and not "too long" but this is too vague IMO. It would be better if this section gave a rough estimate on what is too much and how to determine/test your code is too inefficient.

**Comment by sfan5** [comment]
> I propose to rename the IPC feature.
> Some suggestions:

The problem with these suggestions is that none of them are an established term.
"IPC" is clear and known outside of Luanti, even if we don't technically have literally have different processes here¹.

The closest concept in [LuaLanes](https://lualanes.github.io/lanes/) is a "linda".
In Java this would be a "ConcurrentMap", but that wouldn't be a good name for a global table.
POSIX has shared memory - "shm" for short.

¹: In fact that is merely an implementation detail. It would be complicated but perfectly compliant if the engine started spawning async workers as processes instead of threads.

> The abbreviation should be written out in full at least once

sure

> It is not clear where the data ends up when calling core.ipc_get and core.ipc_set. Is it shared between only particular Lua environments or all possible Lua environments simultanously?

"The engine provides a generalized mechanism to enable sharing data between the different Lua environments (main, mapgen and async)." not clear enough?

> core.ipc_poll(key, timeout) has a warning that it should be used carefully and not "too long" but this is too vague IMO

I don't see a mention of "too long" and the description says exactly what it should. The ideal amount of sleeping to do in mod code is zero.
But if you have to then the tools are there and the decision on how much lag your mod should cause is up to you.

(Technically if the server is below the target step time and has no more work to do you can sleep a bunch and not cause delays. But Lua has no way to tell.)
