### ISSUE TITLE
#13880 broke TNT launching in the tnt_revamped mod

### ISSUE THREAD

**Issue by cowingtonpost1** [minetest/minetest#15479]
### Luanti version

```true
Minetest 5.9.0-dev-08ee6d8d4-dirty (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.1723681758
Running on Linux/6.12.0-0-edge x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```

### Operating system and version

Reproduced on both latest Alpine Linux and Docker in Ubuntu 22.04

### Summary

I used git bisect and commit 0383c44f0d6d0c18fc05640c9c018858c2ca1190 broke TNT launching in the tnt_revamped mod. In 5.8.0, You could place tnt in a line and the explosion would launch the nearby TNT.  In later releases, TNT just ignites other TNT but does not launch it.

### Steps to reproduce

Install tnt_revamped and Minetest Game. Open a world in 5.8 and place some TNT and light it which launches as intended. Repeat the same steps but in a newer version and the TNT ignites the other nearby TNT but does not launch it.

**Comment by appgurueu** [comment]
Very likely an instance of #14614. `tnt.boom` (which [does the launching of objects in radius](https://github.com/minetest/minetest_game/blob/c7be7c165fa3e8e20ec0569da3b19682feb0c72a/mods/tnt/init.lua#L424), including the newly spawned TNT entity) is called inside the TNT entity's `on_step`. It will miss the newly spawned TNT entities since we're inside `on_step`, which guards against mutation of the active entity map.

Some possible (hacky) workarounds that come to mind for until there is an engine fix:

* Move the call to `boom` outside of the entity's `on_step` via `core.after(0, boom, ...)`
* Manually keep track of freshly added entities and override `get_objects_inside_radius` to include them
* Modify `tnt.boom` to keep track of freshly added entities (avoids overriding `get_objects_inside_radius`)

---

Relatively unrelated side note: "Tweak" mods like TNT revamped are.. not so fun to debug, because it doesn't suffice to just look at the mod, you have to see how it interacts with MTG. (It also depends on MTG implementation details, which could change in the future.)
