### ISSUE TITLE
Compile Error on Debian 12

### ISSUE THREAD

**Issue by bullkang** [minetest/minetest#15512]
### Luanti version

```true
Luanti 5.10.0 
(https://github.com/minetest/minetest/archive/refs/tags/5.10.0.tar.gz)
```

### Irrlicht device

SDL

### Operating system and version

Debian 12

### CPU model

Intel i5-2540M (4) @ 3.300GHz

### GPU model

Intel 2nd Generation Core Processor Family 

### Active renderer

OpenGl 3.3

### Summary

Following the instructions on minetest-5.10.0/doc/compiling/linux.md:
After running: cmake . -DRUN_IN_PLACE=TRUE
I get the following error:
CMake Error at irr/src/CMakeLists.txt:224 (find_package):
  By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL2", but
  CMake did not find one.

  Could not find a package configuration file provided by "SDL2" with any of
  the following names:

    SDL2Config.cmake
    sdl2-config.cmake

  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
  provides a separate development package or SDK, be sure it has been
  installed.

### Steps to reproduce

Described above.

**Comment by sfan5** [comment]
You seem to be following the instructions to compile Luanti 5.10.0 but without a source checkout of the latest *development* version. Use the documentation that corresponds to your version.

**Comment by bullkang** [comment]
Thank you @sfan5! that worked! After cloning https://github.com/minetest/minetest.git version and installing the dependencies, (I was missing many components), it built correctly.

Also thank you and all who have made this great game available for everyone to enjoy!

**Comment by ephestione** [comment]
Not reopening, yet I faced the same error.
I had installed the dependencies listed in the Linux compiling instructions, I even tried the steps [here](https://stackoverflow.com/questions/54005991/what-happened-to-findsdl2-in-cmake) but I had to use -ew- flatpak in the end.

**Comment by tycode** [comment]
@ephestione 

I encountered this same exact problem but it turned out I'd done something silly:

While installing dependencies, I noticed I needed to do an `apt upgrade`, so I did so and rebooted... then I forgot I hadn't actually gone ahead with installing the dependencies and carried on with trying to build luanti, thinking all dependencies were installed. After a lot of mucking around, I eventually realised what had happened, installed the dependencies (listed [here](https://github.com/luanti-org/luanti/blob/master/doc/compiling/linux.md)), and then of course it was fine. 🤦

Basically, this error will show up if `libsdl2-dev` is not installed, because that package is what installs the file `/usr/lib/x86_64-linux-gnu/cmake/SDL2/sdl2-config.cmake`. It's unfortunate that it's a misleading error message, but then again there's no way for CMake to know where the file should come from.

So in case you're still using the flatpak, hopefully this'll solve your problem and you can switch to a proper build from source. (Personally I agree about flatpak, I don't want to ever have to use it and so far I never have.) And if anyone else ends up here after doing what I did, here's your answer... 🙂

FWIW, here's my complete build instructions for v5.11.0 on Debian 12 - this assumes you have a `~/src` directory and want to install things into individual directories in `~/opt`:

```sh
sudo apt install cmake g++ gettext libc6-dev libcurl4-gnutls-dev libfreetype6-dev libgl1-mesa-dev libgmp-dev libjpeg-dev libjsoncpp-dev libluajit-5.1-dev libogg-dev libopenal-dev libpng-dev libsdl2-dev libsqlite3-dev libvorbis-dev libzstd-dev make zlib1g-dev
cd ~/src
git clone https://github.com/luanti-org/luanti
cd luanti
git checkout 0cb7735125c4d44026c874fd269669806d8d70d4  # this is 5.11.0
cmake . -DRUN_IN_PLACE=FALSE -DCMAKE_INSTALL_PREFIX=$HOME/opt/luanti
make -j$(nproc)
make install
~/opt/luanti/bin/luanti  # to run
```
