### ISSUE TITLE
Discussion: Eventually move to a free irc platform

### ISSUE THREAD

**Issue by jujubeja** [minetest/minetest#15514]
Libera.Chat officially banned some countries like China, Iran, etc., which is bad for a gaming community 😒 You can't even bypass it with a proxy.

[OFTC](https://oftc.net/) [Hybridirc](https://hybridirc.com/) [Rizon](https://www.rizon.net/)  should be considered instead of Libera.Chat

**Comment by sfan5** [comment]
source?

**Comment by appgurueu** [comment]
Libera.Chat is a free IRC platform. It is unfortunate if countries like China, Iran, etc. are not free, but unfortunately that isn't something we can do much about.

> You can't even bypass it with a proxy.

You probably need to get a better proxy.

Either way I don't think this is something we can or need to do much about.

Note also that we have Discord (proprietary) and Matrix (free software) communities as alternatives for chatting, and the forums for more elaborate posts. If all of those are banned too, I think you're just out of luck. It's unreasonable to expect the Luanti project to "move" to some niche IRC sites just because they don't happen to be banned (yet) in some nonfree countries (why?).

**Comment by sfan5** [comment]
Before it makes sense to discuss this any further I am still waiting for a source that "Libera has officially banned" certain countries.

**Comment by appgurueu** [comment]
> OFTC ranks fourth in terms of users

At a spectacular one third of users. Suggesting everyone move to that because of this one issue (which probably isn't even Libera's fault) is not a workable suggestion. You also still haven't answered my question as for why the alternatives don't work for you.

> Before it makes sense to discuss this any further I am still waiting for a source that "Libera has officially banned" certain countries.

I think it's probably the other way around: e.g. China has blocked Libera.Chat. I don't have a good source but see e.g. this [Archlinux Forum Thread](https://bbs.archlinux.org/viewtopic.php?id=278850).

**Comment by appgurueu** [comment]
> this is intentional by libera.chat

You have provided no evidence for this whatsoever. I see no "your country is banned" there. The message says

> SASL authentication to a NickServ account with a verified email address is required to connect from your current network. Please see https://libera.chat/guides/sasl for configuration assistance.

So it would appear this is a configuration issue on your part.

**Comment by sfan5** [comment]
I believe (but can't confirm) that Libera does not use this IP-range based restriction to discriminate countries or regions, but rather to deal with abuse that often comes from the likes of VPN and other anonymous infrastructure.
You say you use Proton VPN, which would trigger this.

If you can't access Libera on your normal Internet connection you could ask someone else to create an account for you. Or try contacting Libera staff for assistance.
