### ISSUE TITLE
get_current_modname returns nil

### ISSUE THREAD

**Issue by ChaoticLeah** [minetest/minetest#15527]
### Luanti version

```true
luanti-5.10.0-win64
```

### Operating system and version

Windows 11

### CPU model

Core i7-12700H

### Summary

Running `core.get_current_modname()` or `minetest.get_current_modname()` will return nill. This can cause a lot of things to crash.

### Steps to reproduce

Make a basic mod.

mod.conf
```
name = test
description = test
optional_depends = default, mcl_core
min_minetest_version = 5.0
```

init.lua:
```lua
minetest.register_chatcommand("test", {
	func = function(name, param)
		minetest.chat_send_all(tostring(core.get_current_modname()))
	end,
})
```

Running /test in game will print out `nil`. It should print out `test`

**Comment by appgurueu** [comment]
That's expected behavior. The documentation for `core.get_current_modname` has this to say:

> returns the currently loading mod's name, when loading a mod.

Your chat command does not run while the mod is loading. It runs after all mods have loaded.

Feel free to submit a PR to improve the docs if you think they're unclear.

---

Side note: I'm not sure what you expect `core.get_current_modname` to do after load time, or why you would need to use it after load time in a mod.

At any point in time, a couple of different functions by different mods may be on the call stack. Which one of those is currently running? Well, essentially all of them, but they're nested, their execution is intertwined. By a strict definition you could say the mod on top of the call stack - that is, the mod in which the function from which you are calling `core.get_current_modname` was defined. But for practical purposes that isn't terribly useful. Can you blame that mod for a crash, or did maybe the calling mod violate a precondition? You don't know. 

Anyways, if you want to look at something you can do, see my debug mod, specifically [the prefix tree which maps mod file paths to mod names](https://github.com/appgurueu/dbg/blob/master/src/shorten_path.lua) and [my implementation of `debug.traceback` which makes use of this](https://github.com/appgurueu/dbg/blob/972511bab12d39b2a00c4b5a16f0ef98f39a55e5/src/dbg.lua#L143-L198).
