### ISSUE TITLE
`get_player_control()` always returns everything false on `register_on_rightclickplayer`

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#15529]
### Luanti version

```true
5.10
```

### Operating system and version

Pop!_OS

### Summary

I wanted to differentiate between a right click and a sneak + right click but it doesn't seem to be possible

### Steps to reproduce

1. Add this code
```lua
core.register_on_rightclickplayer(function(player, clicker)
  local p_name = clicker:get_player_name()

  minetest.chat_send_player(p_name, dump(player:get_player_control()))
end
```
2. Launch a server (localhost is fine)
3. Sneak/move/whatever and right click some other player
4. returned list has everything set to `false`

**Comment by appgurueu** [comment]
I think you made a subtle mistake there: `player:get_player_control()` should be `clicker:get_player_control()`, otherwise you're getting the controls of the clicked player (which in your example probably were none). I would call the parameters `clicked` and `clicker` maybe to make it clearer what is what (though then they are just one typo away from each other, ugh; maybe someone else has a better idea for the name?).

**Comment by Zughy** [comment]
Oooooh, silly me, thank you! Yep, that's a bit confusing
