### ISSUE TITLE
Add asymmetric crypto Lua API

### ISSUE THREAD

**Issue by Darin755** [minetest/minetest#15583]
### Problem

I am looking for a way to do asymmetric crypto for a mod that doesn't involve writing a ton of code. More specifically, I'm looking to do a cryptographic signatures to allow for in game verification of a identity. However, I also think that it would also be beneficial to have encryption features as well.

### Solutions

Basiclly I'm looking for an API to do the following:

 - generate either a RSA 2048 or RSA 4096 private and public key 
 - encrypt a string
 - generate a signature from a string
 - decrypt a encrypted string to get the original text
 - verify a signature based on a public key

### Alternatives

Maybe there is something in the API I missed

### Additional context

I am working on a mod that is designed to scale digilines to allow for a system that kind if mimics the internet. For this to work there needs to be a system that can hand out unique digiline channel names to nodes. This is totally possible without any cryptography (see dhcp) but I am looking to tie a channel to a cryptographic key for security and reliability.

**Comment by sfan5** [comment]
This sounds like out-of-scope for me.
Cryptography is not something you simply implement yourself, so we're be looking at a library -- [libsodium](https://doc.libsodium.org/) being an obvious choice due to its high-level API.
We would be adding this as a hard-dependency to Luanti without having even a single use case for this on our own.

**Comment by appgurueu** [comment]
Worth pointing out also that if we're looking at servers, there's always the option of having a trusted mod `require` a lua crypto library that is installed systemwide (typically via luarocks).

> Cryptography is not something you simply implement yourself

Honestly, given the use case in this issue, I legitimately think that a homegrown / pure Lua implementation might, while of course inadequate for proper crypto, be acceptable here, since this is just about "in-game crypto":

> I am working on a mod that is designed to scale digilines to allow for a system that kind if mimics the internet

So I will leave the pure Lua RSA impl I wrote for fun a while ago here: https://github.com/TheAlgorithms/Lua/blob/main/src/crypto/rsa.lua. Paired with pure Lua bigints in the async env this could be fine for in-game crypto. If somebody finds a way to exploit this, say via a timing side-channel attack, that just makes the in-game crypto more interesting in my opinion ;)

---

More generally, I think that "bundle everything into Luanti" is probably the wrong approach. Some libraries are too far out of scope to be considered part of what a (voxel) game engine should bundle and will have to be obtained through other means.

**Comment by Darin755** [comment]
> This sounds like out-of-scope for me. Cryptography is not something you simply implement yourself, so we're be looking at a library -- [libsodium](https://doc.libsodium.org/) being an obvious choice due to its high-level API. We would be adding this as a hard-dependency to Luanti without having even a single use case for this on our own.

Yeah this is probably would be hard to make work for a relitively small benefit. I think it is a bad idea to roll your own crypto for obvious reason. 

I do see that there is some work to implement QUIC for Luanti. I realize that work is a little far off but if crypto is implemented for QUIC could that be reused for mods?

**Comment by sfan5** [comment]
Even if we have a library that implements QUIC it might not expose its crypto primitives (or also support different crypto implementations).
Still all the required glue code to expose the crypto API to Lua would need to come from somewhere or be written from scratch by us. So not likely either.
