### ISSUE TITLE
[DISCUSSION] Remove some client-side postprocessing options

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#15592]
### Problem

Many post-processing features have to be enabled on the client before a server can use them.
As a results games and mods cannot be sure that their effects actually show as desired on the client. The client can "veto" most effects.

Since shaders are now required for Luanti, and PP does not consume too much extra GPU resources, we can remove the client side "vetos" and give all control to games/mods.

### Solutions

Remove client PP and related settings. We could start with
- Post Processing
- Enabled Bloom
- Volumetric lighting
(And hence force them enabled on the client)

Later we can move more features to pure server control.

### Alternatives

1. Leave it the way it is.
2. Allow the a mod/game to detect the client settings and issues warning if needed.

**Comment by NathanSalapat** [comment]
It would make things a lot easier for game developers to not need to worry about their users not enabling a graphical effect in the settings. Another option would be to default enable all, and the users that find it too taxing on their system could turn them off.

**Comment by Zughy** [comment]
Also, games can always implement their own in-game settings to give players the possibility to tweak graphics (e.g. through a formspec), so big :+1: for me

**Comment by sfan5** [comment]
Problem: If someone has OpenGL ES 2.0 without certain extensions then our post-processing code is unable to work.

> PP does not consume too much extra GPU resources

are you sure?
IIRC we found it to be significantly slower on Android and hence disabled it. (might have improved in 36edc3f161de03e3c5e8b507d2d6699f0d728ab9)

**Comment by mruncreative** [comment]
But why? Some people really hate bloom for example. I see no reason to force people to have any graphics enabled unless it's game breaking.

**Comment by grorp** [comment]
The idea sounds nice, but I have some concerns in addition to sfan5's:

For some effects, e.g. bloom and volumetric lighting, we pay a cost as soon as they're enabled on the client, even if disabled by the server, since they're set up when creating the rendering pipeline. If we remove the client setting and move all control to the server, that will need to be refactored so that the server can truly enable/disable effects, with the pipeline being recreated on change.

At least on my Android device, bloom and volumetric lighting cause a big performance drop (60 FPS when disabled, 28 FPS when enabled), so allowing the server to force them enabled seems like a bad idea. Devices have very different GPUs and it's usually a more enjoyable gaming experience to have good FPS without fancy effects than to have bad FPS with fancy effects.

The alternative approach suggested by NathanSalapat above would avoid this problem.

**Comment by Zughy** [comment]
@grorp about Android: game devs can always disable those settings for Android players, since if I recall correctly we're able to spot whether they're on a mobile device or not

**Comment by mruncreative** [comment]
Oh yeah, OS and device based discrimination. Really awesome. Just what everyone wanted.

**Comment by mruncreative** [comment]
Independent game developers have shown a strong incapability when it comes to implementing any settings at all by themselves. Just take a look at games based on the Unity engine. They either expose no settings to the user at all or the VERY FEW settings the pre-build settings menu the engine comes with allows to configure.
Unlike other engines this engine comes with a main menu, so there is no excuse to move the handling of settings to games themselves.

**Comment by grorp** [comment]
>  about Android: game devs can always disable those settings for Android players, since if I recall correctly we're able to spot whether they're on a mobile device or not

Conceptually, I agree that it should be up to the game, not the engine, to deal with this problem. Games should be able to ruin the experience for players, simply because they also need that amount of control to be able to create a good experience. However, making this work is difficult:

You can only detect whether they're using the touch controls. This doesn't mean they're on Android. More importantly, there are also powerful Android devices and not-so-powerful Windows laptops, so this approximation doesn't work out.

The user is usually the one who knows best what their device can handle. A game could always provide its own settings dialog for users to disable effects, but that's less convenient for the user than a global setting.

**Comment by kromka-chleba** [comment]
> Many post-processing features have to be enabled on the client before a server can use them.

Would anything bad happen if the server force-enabled the setting and the client just ignored it? That would be better than removing settings.

>    Enabled Bloom

I don't like the bloom effect because last time I checked it looked as if I had blurry vision. IRL human eye is bad enough.

>    Volumetric lighting

Another thing that obfuscates vision, not really a fan of this effect and it's certainly overused.

>    (And hence force them enabled on the client)

Not sure how removing these settings helps in any way. The second alternative sounds better.

**Comment by Zughy** [comment]
> A game could always provide its own settings dialog for users to disable effects, but that's less convenient for the user than a global setting.

True, but that's what we already do with games launched via Steam and the like, I don't see much of a difference.

Alternatively, we could have a global setting called "default quality" or something, that games can read to understand what settings should be enabled and what shouldn't, I don't know

**Comment by mruncreative** [comment]
> Alternatively, we could have a global setting called "default quality" or something, that games can read to understand what settings should be enabled and what shouldn't, I don't know

That's literally what the Unity pre-build settings menu has and it's terrible in my opinion.

**Comment by Desour** [comment]
If an effect affects game mechanics (e.g. very blurry or dark vision (not a feature as of now with PP, afaik), fog), that should of course not be veto-able. But in almost(?) all cases (that I have seen so far, in any game, not just luanti-based), it's purely for aesthetics.

Btw., PP is not the only case where the client can veto, there's also, for example: waving liquids/plants/leaves, translucent liquids, enable sound, shadows.

>and PP does not consume too much extra GPU resources

If this issue is just about features not taking too many resources, you'll have to take volumetric lighting at least from your list. On my machine, it's quite slow.

>@grorp about Android: game devs can always disable those settings for Android players, since if I recall correctly we're able to spot whether they're on a mobile device or not

If a game is fine with disabling it on android (which is the wrong thing, btw, hardware capabilities don't depend on the OS), or more generally disabling it for a subset of their players, the effects aren't mandatory after all, so the game will also be fine with a client veto.
If it is not fine with disabling the effects ever, the game does not support all platforms that luanti supports, which is completely fine, in theory, but in practice it's just sad, because it will probably just be applied too eagerly (i.e. applied even though it's not strictly necessary for gameplay), and will just exclude a part of the player base.

>Independent game developers have shown a strong incapability when it comes to implementing any settings at all by themselves. Just take a look at games based on the Unity engine. They either expose no settings to the user at all or the VERY FEW settings the pre-build settings menu the engine comes with allows to configure.
Unlike other engines this engine comes with a main menu and a pause menu, so there is no excuse to move the handling of settings to games themselves.

I'd like to second this. If you look at web games (e.g. shockwave flash), for example, there are so many that use the x and z keys for actions, which is horrible for QWERTZ users (and probably also AZERTY), and have no option to change keys whatsoever. Or take luanti subgames that add music without an option to change its volume separately from other audio (or per track, *cought cought* itb beeping music). Implementing settings menus is much extra work, so, if possible, the luanti engine should take care of it.

Lastly, I'd like to say that I really dislike bloom, and would not want it enabled just because some stupid modder or server owner wants to blindly enable all the "fancy" effects.

**Comment by Zughy** [comment]
> Or take luanti subgames that add music without an option to change its volume separately from other audio

(*cough cough* [audio_lib](https://content.luanti.org/packages/Zughy/audio_lib/) *cough*)

**Comment by mruncreative** [comment]
Not everyone is going to use something that doesn't ship with the engine.

**Comment by Zughy** [comment]
That's their problem, libraries exist to make your life easier

**Comment by mruncreative** [comment]
It will end up being the user's problem.

**Comment by Zughy** [comment]
Yes, because the dev doesn't care, when they have the tools nonetheless. So it's dev's fault. Player_api doesn't ship with the engine anymore, but that doesn't make it less useful

**Comment by appgurueu** [comment]
First off: I think that this is definitely a good idea *in theory*. Postprocessing just means you don't render directly to the screen, and processing a 2d texture on the GPU is very efficient, and necessary even for simple, cheap effects like say color inversion or increased / decreased saturation. Ideally, we should be able to just have `enable_postprocessing` be `true` by default. This would be friendlier both for players and game devs.

However, there seem to be practical problems which we will have to address first.

> But in almost(?) all cases (that I have seen so far, in any game, not just luanti-based), it's purely for aesthetics.

Aesthetics are a *big* part of a good game. Consider a hypothetical [^1] dystopian game which wants to be desaturated (and say, become saturated and colorful as the player wins the game). The atmosphere is completely destroyed if the settings are wrong.

Also, I doubt your claim. If I remember correctly, Nodecore uses blur to punish you for hurting yourself: The more you're hurt, the less you see. VoxeLibre uses negative saturation (#15062) which also diminishes the ability of the player to recognize things. Both of these are more than just "eye candy". 

> Btw., PP is not the only case where the client can veto, there's also, for example: waving liquids/plants/leaves, translucent liquids, enable sound, shadows.

We should probably reconsider some of these as well. This is an engine giving you game settings.

> The user is usually the one who knows best what their device can handle. A game could always provide its own settings dialog for users to disable effects, but that's less convenient for the user than a global setting.

Frankly I'd challenge this. To name just one obvious issue, settings are currently global and clientside. Maybe I want to have a setting enabled on a creative server where I want to enjoy the glory of my builds, but want it to be disabled on a PvP server where I need good FPS. Game-controlled settings can do better here. They can also be much more specifically tailored to the game more generally, making it easier to find and change relevant settings, and as has been said before preventing you from changing essential gameplay elements.

[^1]: But given the game jams, frankly not so hypothetical :P

**Comment by mruncreative** [comment]
> VoxeLibre uses negative saturation

I wish they did not.

**Comment by sfan5** [comment]
I think in essence we all agree. The given examples have just pushed this discussion into one particular side, because most people consider bloom an eye candy feature and there is definitely value in retaining client control of it.

It would help to have a list of mod-controlled effects which currently depend on post-processing.

**Comment by lhofhansl** [comment]
Thanks for the discussion. The given example just seemed a simple place to start, and it seems those were bad ones to start with.

In theory I would extend this to all features including "waving liquids/plants/leaves, translucent liquids, enable sound, shadows" (as @Desour mentions above).

From the discussion it's not immediately clear where to go from here. Opinions range from:
- I don't like bloom/etc, so I as the user should be able to disable it.
- What about Android?
- Games can have their own settings
- It makes it easier on games if they can rely on certain client effects (if it's part of the game)
- We have bigger settings problems (I certainly agree with this. Try to increase the viewing_range on Android, including the server send/generation distance, it'll take you about 10 minutes, and that is if you know the names of all the settings you'll need to change)
- etc

I just wanted to get a feeling for this. Maybe it's best to leave this as is for now. We can leave this open for a few more days and then close it.

Thanks again for the discussion.
