### ISSUE TITLE
Enable FMA in LuaJIT

### ISSUE THREAD

**Issue by kno10** [minetest/minetest#15600]
### Problem

FMA optimization is [not enabled by default in LuaJIT](https://luajit.org/running.html), because it can change results. Roughly said, values can differ when computed with and without FMA because FMA uses a higher accuracy internally on modern CPUs.
FMA is faster and more accurate.
(Fused-multiply-add computes y=mx+a in one instruction, typically in one clock cycle. It uses internal CPU registers which apparently are often ~80 bit wide (~64 bit mantissa, ~15 bit exponent, aka "binary64 extended"), downcasting the result only after the addition; regular fp64 math performs an additional downcast after the multiplication)

As we do not rely on these late digits, luanti should be fine with the higher speed and accuracy from using FMA when available, and not using FMA when not.

### Solutions

Enable FMA optimization in LuaJIT

### Alternatives

Keep as is.

**Comment by appgurueu** [comment]
To quote the docs you linked:

> Note that -Ofma is not enabled by default at any level, because it affects floating-point result accuracy. Only enable this, if you fully understand the trade-offs of FMA for performance (higher), determinism (lower) and numerical accuracy (higher). 

Note the determinism point. I believe enabling this feature has the possible consequence that the assertion in

```lua
local function fma(m, x, a)
    return m*x + a
end
assert(fma(m, x, a) == fma(m, x, a))
```

can fail if the first call is interpreted and the second one is JIT'ted and optimized to use FMA.

This could break code in various unexpected ways (I would argue that it only breaks somewhat smelly code, but still.)
could essentially fail.

Hence this feature request needs stronger backing in the form of benchmarks motivating it, or conversely, making educated claims about the likelihood of this breaking things.

**Comment by appgurueu** [comment]
I googled around a bit and found [this](https://siboehm.com/articles/23/Inlining-FMA-FP-consistency):

> I wrote microbenchmarks and looked at [instruction latencies](https://uops.info/table.html), and FMA is around ~30% faster than a multiply followed by an add.

I imagine this is essentially the maximum performance improvement we could hope for; practically it will be much less, because we don't have code that just does a lot of FMAs due to all the surrounding code and Lua overhead.

I tried to write a very simple benchmark to see what ideal gains on LuaJIT could look like:

```lua
local fmad = 1
for _ = 1, 1e9 do
	fmad = fmad * 0.75 + 0.42
end
print(fmad)
```

but I have been unable to observe LuaJIT even making any use of FMA when using `luajit -O+fma -jdump=+Arsa fmabench.lua`. The assembly emitted for the loop is identical whether FMA is enabled or not. I'm probably doing something wrong (what?) in my benchmarking.

Currently I'm leaning strongly towards rejecting this. FMA is disabled by default for a reason, because stability (even of contrived or crappy code) is much more important than minuscule (if any) performance improvements. `a * b + c` should yield consistent results, otherwise code may break.

**Comment by kno10** [comment]
It is actually not "less deterministic", as long as you are on *one* system. As you noted, this is only a problem that the same function with and without FMA *may* in some extreme cases return different results. Such extreme cases probably do not even occur in minetest. And in these cases, FMA is always more accurate.
As long as you never, e.g., kick one player because he computed a different value than the server, this will not make any difference for minetest.

FMA is very useful when computing *distances* because `x*x+y*y+z*z=fma(x,x, fma(y,y, z*z))` (using fma(a,b,c)=a*b+c operand order); its almost as if the operation was built to make distance computations faster.
As long as `c` is not negative, the difference `a*b+c-fma(a,b,c)` supposedly is pretty much limited to the last bit of the mantissa due to rounding, i.e., to one ULP. If c is roughly -(a*b), the accuracy of FMA can be much higher because the naive computation suffers from [catastrophic cancellation](https://en.wikipedia.org/wiki/Catastrophic_cancellation). This can happen here in some angular computations.

However, I was pointed to a note that FMA in LuaJIT is currently not supported on amd64, because it only supports SSE not AVX, and FMA is an extension to SSE typically coming with AVX CPUs), so I am closing this.

**Comment by kno10** [comment]
Note that it *may* be a good idea to investigate if using FMA helps luanti with some precision issues on large coordinates (>32000 and <-32000), but in the C/C++ part. But here I'd suggest using intrinsics then.

**Comment by appgurueu** [comment]
> It is actually not "less deterministic", as long as you are on one system.

I think you're misunderstanding something. With FMA, you have at least two different code paths that get run to compute `a*b + c`. There's the bytecode, and then there's the JIT'ed machine code. (For the sake of simplicity we can ignore that the JIT is tiered.)

In bytecode, this is two separate operations, a multiplication and an addition. You can see that using `luajit -bl fmabench.lua` - here's the excerpt corresponding to the loop body:

```
0006 => MULVN    5   0   1  ; 0.75
0007    ADDVN    0   5   2  ; 0.42
```

And as we've already established, this may compute something different than the FMA "equivalent" due to the latter having higher precision (and due to repeating fractions this is not at all unlikely).

Hence, if we enable FMA, the same computation can and will at different times yield different results depending on whether it is interpreted or not. And that is certainly less deterministic, and on the same system, and just one scenario. Other added inconsistencies include:

* LuaJIT with FMA vs with FMA on: You've saved a result from a previous computation which was computed without FMA. Now you're recomputing the same result with FMA. They don't match. (Which theoretically could result for example in failing unit tests or inconsistent mapgen.)
* LuaJIT vs PUC Lua 5.1
* Context in which LuaJIT can apply FMA vs context where it can't or won't (so `f() + c` could be different from `a*b + c` where `f` returns `a*b` because LuaJIT can't inline `f`)

So yes, it is safe to say that enabling FMA makes code *less deterministic*, whether you're on the same system or not, and violates the most basic assumptions (the same code produces the same result). The LuaJIT docs are stating this for this reason, and it is disabled by default for this reason. 

(FWIW, FMA computations should be consistent across systems, because they are specified exactly by IEEE754. The problem is that FMA computations are used inconsistently by LuaJIT.)

> Such extreme cases probably do not even occur in minetest.

Why not? I'd bet they do occur.
Note that you would need to make a statement about the likelihood of code being negatively affected by this behavioral change in *all Luanti mods*, which I doubt you can.

One theoretical example: You're computing distances. Code could rely on |x - y| <= |x - y|, for example, it could be looking for objects that are "at least as close" to x as y, and would not wish to exclude the current object y. Due to the aforementioned reasons, this simply inequality wouldn't hold anymore, and that code would potentially be broken.

> FMA is very useful when computing distances

This still does not make a practical statement about performance gains. In particular it fails to take all the Lua overhead into account. If you have even a simple `vector.distance(v, w)`, there's a lot more going on behind the scenes than a few FLOPS. And even if there was a very minor gain on distance computations (and you de-abstracted the vector distance and only used local variables and everything), that does not imply that the overall performance improvement is going to be significant at all. This smells like premature optimization.

> Note that it may be a good idea to investigate if using FMA helps luanti with some precision issues on large coordinates (>32000 and <-32000), but in the C/C++ part. But here I'd suggest using intrinsics selectively then.

I don't think that would be sufficient at all given our computations. We will probably need to bump our types to be more precise in the long run, especially if we want to increase world dimensions.

**Comment by appgurueu** [comment]
Out of curiosity, I also ran some benchmarks on my ARM64 phone via Termux. I can confirm that FMA is applied there with `-jdump=+Arsa`.

To my greatest surprise however, the aforementioned benchmark consistently runs for ~3s *with* `-Ofma`, and ~2s *without* it, that is, it is **enabling FMA slows things down considerably**. I might report this anomaly to LuaJIT once I've analyzed it more thoroughly.
