### ISSUE TITLE
In stable PPA .desktop file has wrong icon name.

### ISSUE THREAD

**Issue by tengwar** [minetest/minetest#1564]
It says "minetest-icon" instead of just "minetest".

Ubuntu 13.10 x64.

**Comment by nerzhul** [comment]
Is this issue still valid ?

**Comment by ShadowNinja** [comment]
@nerzhul: Distrps may have patched around it, but it is still an issue AFAIK.

**Comment by HEXcube** [comment]
> Changing the name to minetest breaks it on every other distro. -- 7993696

@ShadowNinja That's coz commit 7993696  wasn't done properly. According to conventions,

    Icon=minetest
is indeed the correct way of naming icons and is in compliance with [freedesktop icon naming specification][freedesktop]  which is the standard for Linux desktop. It also ensures **compatibility with icon themes**. However, for this to work simply changing the `Icon=` entry in *desktop* file isn't enough. Like @LotekHeavy pointed out, the associated svg file will also have to be renamed from `minetest-icon.svg` to `minetest.svg`. That is, Minetest icon would have to be installed as

    /usr/share/icons/hicolor/scalable/apps/minetest.svg

Since commit d790aca reverted 7993696, a commit for fixing this issue will have to do the following things:

- Rename `minetest-icon.svg` in [misc folder][misc-folder] to `minetest.svg`
- Edit [CMakeLists.txt][cmakelists] so that *CMake* still finds the renamed icon file.
- Change pretty much every file which refers to `minetest-icon.svg`. ([Search in repo for minetest-icon.svg][search])

  [freedesktop]: http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#guidelines "Link to Freedesktop Icon Naming Specification"
  [misc-folder]: https://github.com/minetest/minetest/tree/master/misc "Folder containing minetest-icon.svg"
  [cmakelists]: https://github.com/minetest/minetest/blob/master/CMakeLists.txt "Instructions for CMake"
  [search]: https://github.com/minetest/minetest/search?q=minetest-icon.svg "Search Minetest's GitHub repo for files referring to minetest-icon.svg"

**Comment by HEXcube** [comment]
Hi, I did the changes necessary to make Minetest's desktop file freedesktop compliant and submitted a pull request - #3134 . @ShadowNinja and @nerzhul will u guys look into this issue and review the pull request?
