### ISSUE TITLE
single-player fails because "wrong password"

### ISSUE THREAD

**Issue by cyanse** [minetest/minetest#1625]
My boxes are not on the internet, just on my basement network.
But connecting with the "Server" tab fails with a "Wrong password" error message.
Does Minetest use just that one error message for any failed login attempt?

**Comment by lonevetad** [comment]
Hi,
i have a singleplayer world but i cannot login because of "i failed password". But i ever setted a password !

The log show this two last lines:
2016-10-21 14:20:29: ACTION[Server]: Server: User singleplayer at 127.0.0.1 supplied wrong password (auth mechanism: SRP).
2016-10-21 14:20:29: ERROR[Main]: Access denied. Reason: Invalid password

**Comment by Fixer-007** [comment]
maybe you tried to run "Server" with singleplayer and password?

**Comment by lonevetad** [comment]
Hi,
sorry for the late (and my bad English).
No, i haven't tried to run "Server". But i fixed it.
I found a file, containing few player's informations, but that file was very strange, because of it not contains informations like the player life, the item stack and other stuffs, it was holding strings similar to a hash code and the permission (chat, fast, fly, cheat, ecc..). I removed the part starting with "password:....." and everything gone right.
