### ISSUE TITLE
Code cleanliness - everthing in convert_json is called id_raw

### ISSUE THREAD

**Issue by iqualfragile** [minetest/minetest#1632]
more or less all the string variables in src/convert_json.cpp are called id_raw, which does not represent their content

**Comment by paramat** [comment]
Comments?

**Comment by iqualfragile** [comment]
this is not really a request but a code cleanness issue

**Comment by paramat** [comment]
Any core dev support?

**Comment by Zughy** [comment]
@paramat there is no trace of any `id_raw` string since 2017 (https://github.com/minetest/minetest/commit/dc3ca09e0e0e25f40cccae12c73830b0334ffb60#diff-8eef1ab32517de88ab7e6bde6241b0f4). No trace [today](https://github.com/minetest/minetest/blob/master/src/convert_json.cpp) either. This issue can be closed
