### ISSUE TITLE
Cyrillic characters in chat window

### ISSUE THREAD

**Issue by SmartDen** [minetest/minetest#1638]
I have a bug in version 0.4.10. If i try to type cyrillic characters in chat windows, they will not be shown and in linux console i see chinese hieroglyphen. But if i type cyrillic text in game console it's all right.
Here some screenshots:
Typing in chat window:
![2014-09-16 11 02 33](https://cloud.githubusercontent.com/assets/4517396/4284908/35515b9c-3d81-11e4-9993-2bd24b61c727.png)
After pressing Enter(see linux console)
![2014-09-16 11 02 45](https://cloud.githubusercontent.com/assets/4517396/4284910/40f3bd00-3d81-11e4-8ec8-71830416ed6c.png)
Enter a text in game console:
![2014-09-16 11 03 00](https://cloud.githubusercontent.com/assets/4517396/4284913/44d97572-3d81-11e4-9524-b7b3082f4333.png)
Options(USE_FREETYPE=1)
![2014-09-16 11 03 23](https://cloud.githubusercontent.com/assets/4517396/4284914/47c863e2-3d81-11e4-99b6-602cb076ee98.png)

Hope it can be fixed soon. It's pretty annoying to open console each time i want say something in russian.

Thanks.

SmartDen

**Comment by neoascetic** [comment]
#2574 is related

**Comment by YuGiOhJCJ** [comment]
I don't think this bug is related to the irrlicht 1.7 engine because with the "irrlicht-1.7/examples/05.UserInterface" example included with irrlicht, the interface is managing correctly french characters : 
![irrlicht_french](https://cloud.githubusercontent.com/assets/2247896/7651314/44776300-faff-11e4-863a-f69e9e99c371.png)
With minetest 0.4.12, the french characters are not managed correctly : 
![minetest_french](https://cloud.githubusercontent.com/assets/2247896/7651387/2072e5d2-fb00-11e4-981a-5348efb26ed8.png)
Maybe mintest developers should follow the "irrlicht-1.7/examples/05.UserInterface" simple example to handle keys.

**Comment by 4aiman** [comment]
In #1106 there is a link to an old build by xyz where input was working.
Why not use that code base  (and that "hack" he mentioned ) to finally fix the chat?

**Comment by Fixer-007** [comment]
As of 0.4.16 cyrillic characters work fine for me in chat under Windows 7.

**Comment by YuGiOhJCJ** [comment]
In Minetest 0.4.12, the "à é è À É È" french characters are working correctly in the console (pressing the "F12" key) but are not working in the chat window (pressing the "T" key). Same problem in the window allowing to edit sign text.
In Minetest 0.4.15, the chat window does not exist anymore. Indeed, pressing the "T" key now opens the console. But the window allowing to edit sign text is still present. So, I did some tests in this window and the "à é è À É È" french characters are working correctly.
So, it seems to be fixed.

Well, there is still a problem but I think it is not related to this issue: Pressing the key "7" on a french AZERTY keyboard should gives the "è" character. But this key is not working: https://forum.minetest.net/viewtopic.php?id=3792

**Comment by nerzhul** [comment]
@YuGiOhJCJ the 7 character problem on azerty is fixed in irrlicht 1.9 but we cannot fix it ourselves. thanks for reporting this old issue. Closing as remaining bugs are only upstream issues

**Comment by alwayshopeless** [comment]
If you got this problem now on Linux, you need disable iBus for Minetest.

```
#!/bin/bash
unset GTL_IM_MODULE
unset XMODIFIERS
minetest
```

**Comment by samaharalop** [comment]
**How to Tell if You’re Being Cheated on Through Messenger**

Messenger is a popular platform for communication, but it can also become a channel for secrecy and potential infidelity. If you suspect your partner might be cheating on you[ through Messenger](https://hackfreeonline.com/messenger/
), there are subtle signs to watch for. Keep in mind, however, that communication and trust are key, and assumptions can sometimes lead to unnecessary conflict.

### **1. Unusual Messaging Patterns**
One of the first red flags is a noticeable change in messaging behavior. If your partner suddenly becomes overly secretive about their phone, spends excessive time chatting late at night, or starts deleting conversations, it could indicate they’re hiding something. Additionally, receiving frequent notifications [from Messenger](https://hackfreeonline.com/messenger/
) without explanation might raise questions.

### **2. Increased Privacy Measures**
If your partner begins using passwords or fingerprint locks on Messenger when they hadn’t before, it may suggest they’re trying to shield their activity. Similarly, if they frequently close the app or switch screens when you’re nearby, it might signal discomfort about you seeing their conversations.

### **3. Hidden or Blocked Friends**
Check for any suspicious changes in their friends list or blocked contacts. Some individuals may block certain people to keep them hidden from their partner. Additionally, if their chat history with specific individuals seems incomplete or nonexistent despite frequent communication, they might be deleting messages.

### **4. Discrepancies in Stories**
Infidelity often involves lies or inconsistencies. If your partner’s stories about their whereabouts or activities don’t match up with their messaging history, it could be a cause for concern. For example, if they claim to be busy but are actively chatting online, it’s worth questioning.

### **5. Overreaction to Questions**
Lastly, pay attention to how your partner responds when you ask about their Messenger activity. A defensive or overly aggressive reaction could indicate they’re hiding something.

While these signs may raise suspicions, they are not definitive proof of infidelity. Open communication is crucial. Instead of jumping to conclusions, have an honest conversation with your partner about your concerns to address the issue constructively.
