### ISSUE TITLE
add lastlogin and firstlogin to auth.txt - maybe add autoexpire/noexpire

### ISSUE THREAD

**Issue by codeandfix** [minetest/minetest#1657]
auth.txt should save the first and last login date of a user.
so you can drop old users. forcing passwords blocks all good nicks too soon.
maybe nicks should expire like in IRC (nickserv from ircservices). also some should have a noexpire flag.

**Comment by lightonflux** [comment]
Any news on problem?? Sound easy to implement and extremely useful. Especially for protection mods that lead to servers with abandoned but protected houses that ruin the landscape.

**Comment by paramat** [comment]
Old and quiet isue.
Is anyone capable and interested in coding this? Closing in 1 month if not.

**Comment by ExeterDad** [comment]
If player files have been migrated to the (or a) database, a column called "creation_time" is created in the player table. But currently the date is not referenced by anything in core so is sitting there useless unless accessed with external database queries.
I think it would be more sensible to make the date accessible rather than write the date in auth.txt as a dupe.
Unfortunately I'm incapable of writing the code myself.
It may be worth noting that migrating existing player files will cause players to have a creation_date of the time of migration as the timestamp is created automatically by the database when the row is added.

**Comment by paramat** [comment]
Old, low priority and little dev interest.
