### ISSUE TITLE
Incomplete mapblocks being saved to database

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#1815]
How to reproduce: (with a Lua mapgen)

1) Manipulate the mapgen, so it throws an error while building the terrain
2) Fix the error
3) Rejoin and enjoy the TNT-effect

Basically, the database should not save incomplete mapblocks, but in this case, it does.

**Comment by paramat** [comment]
This happens to me too if one of my lua mapgens is buggy, it doesn't concern me because lua mapgens should always be tested in a test world first, a buggy lua mapgen is expected to result in a buggy world.

**Comment by bugreport0** [comment]
I think you are missing the point of why this is dangerous.
Lua mapgens are a slightly slower than regular mapgens.  If the server goes down in the middle of generating a piece of the map, then that piece of the map is forever corrupt.

> When on_generated() is called, the mapblocks in the central area are considered finished generating
This is the wrong way to think about this bug.  Lua mapgens are a replacement to the aweful bultin-map generators in minetest, not an additional step in generating terrain.  Minetest needs to give lua mapgens equal safety guarantees that a built-in mapgen has.

>a buggy lua mapgen is expected to result in a buggy world
This actually has nothing to do with "buggy" mapgens.  If you have a LUA mapgen that is 100% bug free and never crashes, this will still mess up your map database ... as noted above because if the server goes down for other reasons in the middle of generating terrain, that chuck is forever lost and corrupted.

**Comment by SmallJoker** [comment]
This has partially been solved with the command `/deleteblocks`

**Comment by paramat** [comment]
Okay raising priority, but this is beyond my expertise.

**Comment by bugreport0** [comment]
First off, let me apologize for the tone/attitude I took with my last post.
Second, thanks for the great response, and giving it a second look.

May I offer a suggestion??
What if we did something like this?  I think it might not take to much time to code, but I'm not sure.

1. Add a new lua function called:

minetest.replace_mapgen(function(minp,maxp,seed))

Details:

The main purpose of this function is to provide the same safety guarantees to lua map generators that the default minetest map generator has.  This function completely replaces ALL builtin minetest map generator functions, include extras like generation of nyancats and cactuses.
This function should be used when you want to completely replace the builtin map generator, so that you have the same safely guarantees against dataloss.
Additional notes:
Any on_generated functions will still run after this, like before.  However, on_generated functions do not have the same safety guarantees against dataloss. A server crash at just the right time could prevent on_generated functions from getting saved to the database.

How to use replace_mapgen:

1. Replace "function" with the function of your choice.  It receives the same three variables as the on_generated function.
2. Returning from the function saves the map.  The map will not be saved to the database until AFTER you return.  If you never return from the function, those chuncks of the map remain ungenerated.  (Would it be a good idea to make it return "true" to save to the database and "false" to indicate an error and not save?)

Implementation details:

1. When a new chunck is ready to be generated (because a player visits it, for example), it immediately calls the function in replace_mapgen
2. minetest waits for the return status
3. If it returns "true" minetest saves those blocks within minp and maxp to the database.
4. Should we allow it to return "false" and not save to the database?
5. After the chunck has been saved, it calls any registered on_generated functions like normal.

**Comment by bugreport0** [comment]
Extra note:
Would a VERY SIMPLE fix be to just do this?
* Wait until all the on_generated functions have finished before saving the map.  (Since minetest knows how many on_generated functions have been registered, it can tell when they have all finished.)

Would something like this be easy to do with the way the codebase is organized?

**Comment by paramat** [comment]
> the database should not save incomplete mapblocks, but in this case, it does.

As kwolekr stated, all mapblocks are already generated, so this doesn't happen. How can the engine decide whether blocks are messed up or not by lua mapgen? it can't. If there is a crash during on-generated then there's no way to continue lua mapgen to complete the mapchunk.
