### ISSUE TITLE
Improve client authentication

### ISSUE THREAD

**Issue by ShadowNinja** [minetest/minetest#1943]
Currently client autgentication is very insecure.  A client simply sends a SHA-1 hash of their player name and password to the server.  There are practical ways to exploit this and do very, very bad things.

Issues with the current system:
  * SHA-1 is no longer considered secure for password hashing.  SHA-2 is better, although bcrypt and scrypt seem best.
  * The player name salt has minimal entropy, so it isn't very effective.  16-32 (cryptographic) random bytes should work well.
  * It's impossible to implement case insensitivity properly since the username is hashed case sensitively.
  * Other known severe security issues.

SRP has been proposed as a solution for these problems.   A C library (dependent on OpenSSL) can be found here: https://github.com/cocagne/csrp

**Comment by nerzhul** [comment]
You are right. Authentication is a problem. 
I'm working on network but i'll look at the auth problem after that

**Comment by Zeno-** [comment]
I don't know if it's possible but part of this work should include a script to update current player hashes would be great (if it's possible of course). If it's not possible then some mechanism must be thought about to prompt users of existing public servers to update their password and not allow login until they do.

**Comment by nerzhul** [comment]
sha256 is good, but maybe we need a diffie-hellman like method to change the hash over the network and decode it on server. Or if we use TCP use SSL for authentication ?

**Comment by ShadowNinja** [comment]
@nerzhul SHA-2 is an improvement, but it doesn't solve a number of other serious issues.  I'm not sure what you mean by a diffie-hellman-like method.  Using TLS is overkill and only prevents MITM attacks.  SRP is much, much better.  The server is left with a token that is not password-equivalent it's not vulnerable to MITM.

@Zeno- Here's how I was thinking of doing it:
Server and client exchange protocol versions and client sends old hash.  If server supports better auth then client begins negotiation.  If server has an old hash it verifies the hash sent by the client, negotiates with better auth, and stores the better auth token.  After you've connected to a server with a client that supports the better auth the old method no longer works.  If the server has an improved token it ignores the legacy hash sent by the client.  After a version or two legacy compat can be dropped.

**Comment by Zeno-** [comment]
@ShadowNinja That sounds reasonable

**Comment by est31** [comment]
The server token *is* password equivalent, at least same equivalency as a hash used in combination with challenge-response. Your protocol needs this password equivaleny in order to check whether the password is correct. If the server has a way to check whether a password is correct however, it can iterate that as often as it wants, and do an offline brute-force. But SRP isn't better than any challenge-response in this regard. The main advantage of SRP is that no MITM can manipulate the login procedure in a way such that they get data to offline brute-force the password.

Without encryption, we are always open to MITM, can't change that. Only difference is that the password is now safe.

I'm for ed25519 based ssh-like authentication, and could code an example if requested.

**Comment by ShadowNinja** [comment]
@est31 SRP leaves you with a non-password equivalent token, so you can't use it directly.  You can always brute-force something if you can verify correct passwords, you can't protect against that, you can just make it really slow.

You can protect from MITM without encryption -- after all setting up that encryption requires some methods that are safe from MITM.

We don't *need* encryption for this though, and unless some of its other advantages are needed it's just a waste of bandwidth, time, and CPU.

**Comment by nerzhul** [comment]
@ShadowNinja i may study all of this, but i think we will work on it after merging all networking layer and before next release, as soon as possible after merge, sure

**Comment by jynolen** [comment]
Hello everyone,
For my first contribution we deal with the authentication.
The use of Diffie Helman is corret but we have a major problem : the MITM attack.
But I think we have to stay focus f what we want. 

==== If we want to secure the communication, we can use Diffie Helman to generate a secret key used in the communication bet ween server & client. Using DH is correct if we make the assumption that we DON'T want to authenticate the server.

==== If we wan't to authenticate the server in order a make the client sure that it's talinkg to the right guy, we need a PKI infrastructure. So a Root CA etc, etc,
It can be done by publishing the public key of each server on a specific git repo or smtg else (it's possible without a big infrastructure)

******* No matter the solution we choose know I make the assumption that the communication is secure.

About the security of password. the goal is to authenticate the client and even we have somebody who can watch the exchange of data, make him unable to steal client identity on the server.

==== The enrolment on the server will be on a very secure channel (SSL) and consist for the client to send it's userid (login) and a secure hash of the password (shaX),

==== For the login, the server will send to the client a random unique piece of byte, the client type the password, in intern we perform the following step 
==***** Hash the password
==***** Hash the piece of byte
==***** Use the piece of byte's hash as salt, hashed password as password in a PBKFD2 Function (derivation of key)
 This is what the client send to the server, the server will process the same and will compare the result. If equals grant the access overwise denied it.


Thank's for reading and hope I'm not out of the topic.

See ya

**Comment by est31** [comment]
Hi @jynolen! I think that PKI is too much, as nobody would want to host the "single point of failure". An SSH-like model where an attack is possible only on first login is enough, I think. Also, it hasn't been decided yet whether to encrypt the connection at all. About your proposed login protocol, I think that SRP is better than using challenge response (see [here](http://sprunge.us/CMdH) for a good challenge-response protocol proposed by @sfan5), as SRP doesn't make it possible to offline-brute-force the password just from a MITM perspective (except they intercept the "enrollment" procedure).

**Comment by jynolen** [comment]
Hi @est31 ! Thank's for your feedback, in so many protocol the vulnerability is in first connection.
About the process of developpement, do we have to make a consensus before coding ?

**Comment by Zeno-** [comment]
You don't need consensus,  but if you have started (or are planning to start) I'd strongly suggest opening a pull request early in the process so that feeback can be provided early. It does not matter if your effort is not finished... add WIP (work in progress) to the PR title so it does not get merged before it's  ready...

**Comment by jynolen** [comment]
About the hash algorithm, we might use the Whirlpool hash, the performance are good and security too, it was used by true-crypt for container. What do you think ?

**Comment by ShadowNinja** [comment]
SHA-2 or Whirlpool ought to be fine, as long as the hashes aren't password equivalent and the protocol's safe from MITM.

I'd very much prefer if you used a tested protocol like SRP instead of rolling your own though.

**Comment by est31** [comment]
As long as it isn't NTLM hash like the hash algo is good. Even keeping SHA-1 would be OK too, after all collisions are irrelevant.
Having SRP is better than rolling a challenge response protocol. SRP also authenticates the server.

**Comment by nerzhul** [comment]
SHA1 is broken, SHA256 is the minimum this year.

**Comment by est31** [comment]
SRP is merged now, but not actively used, because protocol 25 is not final.
* salts are [32 bytes](https://github.com/minetest/minetest/commit/82e35edff52d88dcd64a9bfc9d2c4c93f1341b78#diff-2f6369328116e9b654242a7597658a48R549) by default, but the protocol doesn't impose any restrictions, the client can freely chose
* we still use the username for additionally salting the stored password verifier, but its only after it has been lowercased.
* We use SHA-2 for hashing, although SHA-1 would have been good too. "harder" hash algorithms will make it harder to brute-force the hash database side, but also require clients to do the same processing.
* Because we use SRP, no MITM-attacker can offline brute-force the password. Servers still can, but no authentication protocol can stop this from happening.
* As the salt is chosen by the client, password reuse over servers is possible now, you have to keep in mind though that they can mount brute-force attacks.

I suggest we don't close it until protocol 25 gets activated.
