### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#2045]
Tested on two different servers, after less than 30 minutes of playing, memory use went from around 20% to around 75%, then slowly climbed until Cinnamon crashed and I almost ran out of memory.
Screenshot taken just after I started Minetest and joined a server: 
![screenshot from 2015-01-03 18 37 45](https://cloud.githubusercontent.com/assets/8821916/5604211/487d381c-937b-11e4-8397-1e2e2704518b.png)

Screenshot taken just after closing Minetest due to near loss of memory: 
![screenshot from 2015-01-03 18 49 26](https://cloud.githubusercontent.com/assets/8821916/5604212/5b09d364-937b-11e4-8924-1d47e50b76dd.png)
Edit: I'm using version 0.4.11-44-gd91559b

**Comment by ShadowNinja** [comment]
You can run Minetest in valgrind's massif tool to see what's using up the memory.
If you're running a local server it could be a mod that's storing things and not clearing them though.

**Comment by Wayward1** [comment]
Hmm, never used valgrind before, I'll try that. And they were both public servers, neither of them mine.

**Comment by Wayward1** [comment]
Just finished running Minetest through massif, but I have no idea what to do next lol

**Comment by ShadowNinja** [comment]
I can't load that file here.  `ms_print` (3.10.1, latest) says `Line 11: expected 'empty' or '...' after 'heap_tree='`, even though that line is `heap_tree=empty` and `massif-visualizer` (0.4.0) has a parse error on the first comment line.  I tried to read the raw file, but nothing stook out.

I've heard from @sapier than the node id mappings for MapBlocks aren't freed, so that might be the source.
You can also try valgrind's memcheck tool (the default) if there's actually a full blown memory leak rather than just holding on to data too long.

**Comment by Zeno-** [comment]
I can confirm this. I'll collect more massif data (I have lots already but it's from just before 0.4.11 was released so I'll get some new data).

**Comment by Zeno-** [comment]
http://pastebin.com/p0pH2JRW

(note: add a new line at the end of the paste; i.e. there should be 1318 lines)

**Comment by t4im** [comment]
Does this issue still exists after a39c136?
gregorycu and sapier fixed major leaks associated with entities leading to such massive ramusage after short time on servers with e.g. pipeworks, which seems to be fixed now after said commit.

**Comment by Wayward1** [comment]
Most likely the same as #2653, and therefore is probably fixed by <a href="https://github.com/minetest/minetest/pull/3033">#3033</a>
