### ISSUE TITLE
Enter should submit chat on android

### ISSUE THREAD

**Issue by sapier** [minetest/minetest#2061]

**Comment by sapier** [comment]
Well chat formspec has only a single text field so here it would be possible. Yet chat is just a regular formspec how is it supposed to behave if there's more then one text edit?

**Comment by ShadowNinja** [comment]
@sapier You'll have to handle the chat window and console specially.

Also, the chat window should auto-select the text field and open the text input box.

Alternatively you could just forgo showing the chat formspec at all and just show the Android text input box, since on Android there's nothing useful in the formspec.

**Comment by sapier** [comment]
I agree about the merge. Well there is something usefull about it beeing formspec we don't have to handle different input mechanisms.
Yet as I wrote in #2062 if this is going to be replaced by console anyway I don't wanna spend time on it now.

**Comment by rubenwardy** [comment]
It does for me on the latest master
