### ISSUE TITLE
Extend protection api to allow for protection from specific actions

### ISSUE THREAD

**Issue by t4im** [minetest/minetest#2250]
### Status quo

`boolean minetest.is_protected(pos, name)`
Currently lacks returning the protection status depending on conditions:
i.e. against what is being protected.
### Proposal

I propose a simple backward compatible extension of `is_protected`, that does not require any code change.

After the decision to make it public api and add to the documentation mods could instantly begin to use it, as it is being directly passed to the protection mods.

 `boolean minetest.is_protected(pos, name, action)`
if `action == nil` or unknown assume our current status quo, that is permissions to `dig` or `place`, which are the most frequent checked actions anyway.
- Old protection mods will work as-is, assuming these permissions anyway.
- New protection mods will have to check action for `nil` and assume the same in that case.
- New protection + protected in combination can flexibly start making exceptions.
### Examples
- An spawn area might be protected against anything but `inventory` actions (by simply having that check in the inventory callbacks). This would allow placing public technic machines there for everyone to use without having to fear those machines getting "misplaced".
- The bucket mod could check for `fill` allowing players to allow others to fill up that renewable water even in protected areas but not to do anything else.
- doors could check if the protection mod allows a player, even though he may not change anything, may enter the area through the door

**Comment by crazyR14** [comment]
This is a brilliant idea :)

**Comment by ShadowNinja** [comment]
Seems like a good idea, but it won't be efficient.  If we were using Lua 5.2 or above we could use bitops, and with 5.3 we have operators for them, but in the abscence of those it will have to be a table like `{dig=true, place=true}`.

`is_protected` shouldn't be expected to be especially efficient though.  Some mods can check positions quickly while others might have to look for a specific node nearby and/or read meta.

**Comment by est31** [comment]
:+1:

**Comment by Rogier-5** [comment]
I have another suggestion for an improvement in the protection API.

The current API can be used to prevent users from making changes in areas that are owned by others. However, it is not possible to also grant users additional powers in areas that they [i]do[/i] own, powers they can't use elsewhere.

I propose that the API be changed so that is_protected returns two values: whether the player can perform the requested action, [i]and[/i] whether it has any special authority over the node at all:

access_denied, area_protected = is_protected(pos, player, action)

For existing users, nothing changes (they still use the 'access_denied' value, which tells them all they need).

Any new mod could use the area_protected value to grant additional powers that the user does not have elsewhere.

**Comment by nerzhul** [comment]
Could be interesting.
Another interesting change could be a restricted server interact but protection allow interactions in some dedicated areas to player with rights. Instead of a global allow with some interdictions

**Comment by neoascetic** [comment]
+1

**Comment by t4im** [comment]
It should not be a table, since that indeed will lead to many people creating *new* tables over and over again, which is indeed not very efficient.

I was talking about Strings, which lua interns anyway. So comparisons are done on identity, which should not have any performance implications.

**Comment by paramat** [comment]
Enough dev interest to keep open?

**Comment by paramat** [comment]
Any core dev interest? Nerzhul expressed interest 3 years ago.

**Comment by paramat** [comment]
No core dev support or response for 3+ years so closing. Core devs feel free to reopen if you support it.
