### ISSUE TITLE
Question: Minecraft protocol compatibility

### ISSUE THREAD

**Issue by wiseoldman95** [minetest/minetest#2298]
Are there any plans to make Minetest compatible with the Minecraft protocol? Specifically, the 1.7 or 1.8 protocols.

It's worth noting that this would allow it to work with [MC-server](http://mc-server.org/) and CraftBukkit. It's also worth noting that perhaps some code could be borrowed from MC-server to implement this.

**Comment by PilzAdam** [comment]
No, there are no such plans.

**Comment by wiseoldman95** [comment]
Theoretically speaking ( Not really sure if I'll actually do it), if I implement it myself, would my code be accepted?

**Comment by PilzAdam** [comment]
@wiseoldman95 I don't know how you plan to do this. Currently all content definition is send from the server to client when the client connects. How would that work with MC servers?

**Comment by ShadowNinja** [comment]
This would be very hard to implement because Minetest internally works quite differently.
In addition to content definitions, the block size is quite different (16x128x16 vs 16x16x16) and the map size is very different (2^32 x 256 x 2^32 vs 2^16 x 2^16 x 2^16).
I've heard that another open-source game with MC protocol compatibility had to drop that support due to copyright issues or something similar though.  Terasology maybe?

**Comment by wiseoldman95** [comment]
Regarding the legal side: I am no lawyer but I thought that re-implementations are legal. (E.g. Mono, openJDK, etc)

**Comment by wiseoldman95** [comment]
I haven't checked the technical side yet, and I don't know if it's even feasible. My question was a hypothetical one, I wanted to know if you're simply not planning to implement it or if you're actually against implementing it (for legal reasons or any other reasons).

**Comment by nerzhul** [comment]
No, minetest isn't minecraft and minecraft server authentication works différent. Also there are copyrights.

**Comment by wiseoldman95** [comment]
Fair enough.
