### ISSUE TITLE
CheckButton for Invert Mouse in the Settings (gui)

### ISSUE THREAD

**Issue by hunter688** [minetest/minetest#2303]
Please add checkbutton for changing Invert Mouse in the gui.

invert_mouse variable in the minetest.conf

**Comment by rubenwardy** [comment]
Check buttons and radio buttons would be good to have.

**Comment by nerzhul** [comment]
I agree

**Comment by Calinou** [comment]
> I agree

We should probably make a list of what's GUI-able:

* field of view (text + slider)
* invert mouse (checkbox)
* view distance min/max (text + slider)
* clouds (checkbox)
* view bobbing amount (text + slider)

It is a good idea to have a text **and** a slider (like nvidia-settings), so that you can quickly fine-tune values while letting newbies change values easily.

**Comment by PilzAdam** [comment]
006ef5b4a5e362eed848ca26b411a8059d74b965
