### ISSUE TITLE
Mapgen v6 generates floating desert stone

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2384]
It surprises me that this is not on GitHub yet, but anyways:

Sometimes the map generator v6 generates floating desert stone.

Here is a screenshot taken in 0.4.11:
https://i.imgur.com/rYopIhB.jpg

Coordinates: (734, 19, -893)
Seed: 1483374557963899909

I have seen a couple of other places on other worlds such floating “desert caverns” or “desert rings”, but I do not know the coordinates or seeds anymore.

A quick check in the developer version (after 0.4.1.2) showed that a few oddities seen in the screenshot are gone, but not all.

Also note this is a pretty odd place I found.

Maybe or maybe not related, if you fly to the nearby desert, you will notice that the cacti are spawned in a surprisingly regular grid-like pattern (look from above).

**Comment by BlockMen** [comment]
AFAIK it's related to dungeons. Try if they appear aswell with disabled dungeon.

**Comment by C1ffisme** [comment]
It's REALLY wierd when a dungeon spawns as a tree, like at the bottom of the picture.

**Comment by Wuzzy2** [comment]
Nope, they don't appear when dungeons are disabled.

**Comment by paramat** [comment]
These are slices of desert temples, the desert versions of dungeons, you will also find cobble versions of these. It's a very old bug which has very cool results, these are the 'magickal floating dungeon ruins of Minetest' which i consider one of the best features of vanilla Minetest, so this bug must and will be preserved. The cobble/stone rings are a parody of Minecraft's Nether and End portals, the larger floating dungeons are perfect for converting into epic player bases. Luckily these are not too common so retain their charm.

**Comment by kilbith** [comment]
@paramat : truncated pieces of dungeons scattered everywhere are cool ? Seriously, such kind of wacky/far-fetched ideas are deplorable for blasting that legit issue. mgv6 is intented to be a familiar environment, stable and not weirdish for some exotic delusions (you already have v5 and v7 for that)...

@Wuzzy2 : re-open the issue, please.

**Comment by Wuzzy2** [comment]
Paramat: WTF? That's a very lame excuse for not fixing the bug. Or you are just trolling. I can't tell.

And I agree, MGV6 should create “typical” landscapes, not weird bullshit. Magical floating dungeon ruins are clearly not my understanding of a typical landscape and every player with an IQ over 25 will see the weird floating dungeons as bug, not as feature. :P

kilbith: Sorry, I cannot re-open the issue.

**Comment by Amaz1** [comment]
I agree with paramat. I think that these are a great feature/bug-that-became-feature of Minetest.
However, I think that there should be an option to enable/disable them, so that those who don't want them can disable them and vice-versa.

**Comment by paramat** [comment]
No not trolling or making excuses :) sorry if my post seemed harshly worded it wasn't meant to be, i have edited it a little. Also, closing the issue quickly was not meant to cause offence i was just being efficient and trying to process issues as fast as possible.
Dungeons have been this way for several years with very few players complaining, many players love the floating ruins. I actually feel sorry for those who cannot see the wonder in these.
In any creative/artistic project often unplanned things arise which are actually wonderful and should therefore be preserved instead of coldly, mechanically being removed just because they were unplanned. These things often become a project's most unique and precious features.
These are actually fairly rare, if they were more common i agree they would become too familiar and probably irritatiing.
I was told by hmmmm these are difficult to fix, it seems to be a result of a rare glitch in how mapchunks are generated, these rare glitches create other bugs in Minetest, it is not actually a mistake in the code that causes these.
Minetest is not real life, mysterious and magickal content is very welcome. Personally i find the experience of exploring a landscape to occasionally find floating ruins truly and literally wonderful. They also make by far the most awesome bases for players.
Mgv6 is indeed meant to be stable and preserved, this is actually a reason to keep these since they have become such a part of Minetest's character.

**Comment by Zeno-** [comment]
A bug is a bug

**Comment by paramat** [comment]
Perhaps i'll try stopping dungeons being generated into the mapblock shell around a mapchunk to see if this makes a difference, it could then be possibly made a minetest.conf option.
It's okay to reopen this i guess for more opinions.

**Comment by kilbith** [comment]
@paramat, you already have the v5 and v7 mapgens as "mysterious and magical" playgrounds.  You should open your eyes in v6 and observe that it's a faithful / lifelike environment that some players can further appreciate and feel not disoriented.

As usual, you have a personal aversion against realism, but please do not impose your personal wacky views on an historical familiar-looking mapgen... for a bastard result.

EDIT : closing an obvious bug report is not correct from a core-dev.

**Comment by paramat** [comment]
It's been this way for years, it's actually much more controversial to remove these, it's a like removing mese or nyancats because they are weird, if we did these things we are actually removing Minetest's character. The reason these ruins are very rarely discussed as a problem is because they have become a part of Minetest, they mostly tend to upset people who are new to the project.
Anyway, i might see if i can clean these up with an option in minetest.conf, then we can all be happy :)

**Comment by ExeterDad** [comment]
I respect your point of view paramat. And your points are valid, I'm sure many folks would miss them if they just vanished suddenly. I however am not one of them. So if you could fix and create a option, I would be happy :)

**Comment by paramat** [comment]
So currently dungeons are generated out into the mapblock shell around a mapchunk, i'll try adding an option to prevent this, which might clean up the floating stuff. However the dungeons would then be cutoff at mapchunk edges, possibly having missing walls, just so you know, i hope this won't be a problem for you guys because they are ruins after all.

**Comment by MT-Modder** [comment]
We should open a poll on the forums. Then after sometime take the votes into account. I personally love this feature-bug. Ever sense I started playing minetest I've treasured these structures and use them for bases/homes.

**Comment by Zeno-** [comment]
@MT-Modder Why can't they be bases/homes but not bases/home floating in the air?

**Comment by twoelk** [comment]
I agree that there should be at least one mapgen that is more conservative and does not include any floating structures of any kind
(as much as I enjoy being surprised by such structures now and then) 
that being said I do think the dungeonsystem could be improved somewhat.

**Comment by MT-Modder** [comment]
@Zeno- I'm not saying there can't be bases/homes anywhere else, that's just what I do with them :smiley:. I love them for the same reasons as paramat.

**Comment by C1ffisme** [comment]
I think that paramat has valid points. If we REALLY cared about realism, then we should have made a physics generator, not a cubic world with little ammounts of physics. It's fun to see things that happen by accident. Sometimes mistakes can be funny, or advantagous. If minetest were perfect, then it wouldn't be a very fun game, because imperfection makes us who we are.

**Comment by paramat** [comment]
Ahhh :) okay i feel better now for sleeping. Sorry for closing the issue that was a mistake, making this an optional fix is a good idea i should have thought of that. If i come across as unpleasant that is of course just a result of my mood at the time and never something personal.
I will prepare a PR with the possible fix i mentioned, then hopefully someone can put the time in to test it by exploring for a while? If it works i will merge it. So no need for a poll.

**Comment by MT-Modder** [comment]
Okay, I wish I could figure out how to compile successfully so I could test. Good luck with the optional fix.

**Comment by Wuzzy2** [comment]
If you really insist on floating dungeons, doing this in a mod seems to make much more sense, it would also me much more flexible. I never understood why dungeons were hardcoded in the mapgen in the first place. Whatever, now they're in, and can be deactivated, so there is no point in removing dungeons completely from the mapgen.

Or, as other have suggested, just add a config setting:

`mgv6_weird_floating_dungeons = true` to activate nostalgia mode.

I hope this should be an acceptable comprimise.

**Comment by C1ffisme** [comment]
@Wuzzy2 I think that title is a little long. How about 'mgv6_dungeon_fix = true'?

**Comment by paramat** [comment]
Yes my PR, coming soon, will have a config setting with the default 'floating dungeons = true', it will operate in all mapgens too =) I will of course test it myself but extra testing by others would be welcome, as this involves taking some time to explore.

**Comment by paramat** [comment]
I should quickly say, there is good reason for the default to be how Minetest has been for years, even if some see it as a 'bug'. I'm in a good mood now so please don't anyone push their luck by arguing that the default should be no floating dungeons ;) just consider yourselves lucky i am putting the work in to make this an option. It may seem that a 'bug'fix should obviously be the default, but not so in this case, as i will explain below.

**Comment by paramat** [comment]
You might notice that any structure that is generated out into the mapblock shell around a mapchunk (small and large pseudorandom caves and dungeons) occasionally glitches and does not behave the way it should. For example you will find large caves that have long flat walls running along a mapchunk.

The reason PR caves and dungeons are 'overgenerated' is to enable them to overlap to create large multi-mapchunk structures, long cave routes and large dungeon complexes. Dungeons rarely intersect currently but have a density parameter that if increased would make them intersect more often. Adding user-settable dungeon params is planned for the future and i will code it if i can.

My 'fix' for this issue is not directly a 'fix' for these obscure glitches with overgenerated structures, no one yet knows how to fix that. My 'fix' will actually be an option to disable the overgeneration feature of Minetest, which then in turn has the side-effect of fixing the floating dungeons. That is another reason why the default must be having dungeon overgeneration enabled, because that is an intended feature. The dungeon code does not intend to have floating dungeons, they are meant to only replace pre-existing terrain and not project out of the terrain or hang in the air.

**Comment by paramat** [comment]
Good grief ... after all that my first attempt actually had the opposite effect, floating dungeons everywhere to the point of being irritating: https://github.com/paramat/minetest/commit/812040aa5d559db08ec6855bb583de19201cb8b4
I will now look into the dungeon generating code in detail to try and solve this another way.

**Comment by C1ffisme** [comment]
@paramat By the way, during that preiod, could you make torches in dungeons be a setting? I spent **DAYS** just trying to get torches to appear in them. So, I think a setting for that would be nice, rather than having to build minetest a certain way.

**Comment by paramat** [comment]
There is already a (player inaccessible) option for torches in dungeons, could possibly be made a config option? although torches in ruins don't really make sense.

**Comment by C1ffisme** [comment]
@paramat Yeah, I want it player accessible.

We could add mobs to dungeons...

**Comment by paramat** [comment]
Exactly, the code is there for testing but could be used by users for other purposes. I'll see if the torches are placed sensibly. What are other's view on making dungeon torches optional?

**Comment by MT-Modder** [comment]
I think torches are a good Idea for when creative mode is enabled, but I too am neutral about it.

**Comment by paramat** [comment]
Just checked, the torch placing code places one torch on the floor in the centre of each room, which is no good.

**Comment by C1ffisme** [comment]
@paramat Yeah, do you think you could put it on the top, or replace "default:torch" for "mapgen_light" so that people can pick a block? (I made a 'lava lamp' in my fork)

**Comment by paramat** [comment]
Nope :) it's not important enough for core code, should be done in lua by a mod.

**Comment by paramat** [comment]
See https://github.com/minetest/minetest/pull/2448 needs testing.

**Comment by paramat** [comment]
Now merged! Sorry for the fuss i made, it is a good idea to have an option and the fix turned out to be simple.
'enable_floating_dungeons = false' in .conf.
This will also disable the complete dungeons that sit on the terrain but project out of it:

![screenshot_2366229226](https://cloud.githubusercontent.com/assets/3686677/6566839/ca5bf724-c6b6-11e4-954e-5211e1f5e6dc.png)
