### ISSUE TITLE
Relatively ugly mapgen artifacts (mgv6)

### ISSUE THREAD

**Issue by Zeno-** [minetest/minetest#2396]
Present in commit fdb9140825716be49c99e6a27bb123432b9cb285
and commit 338e66af5f0a645e5d161ca83d048b27c3095165
(i.e. did not bisect or check before 338e66a)
```
mgv6_spflags = jungles, biomeblend, mudflow
seed = 51351515151515
water_level = 1
```

![1](http://i.imgur.com/Bd7ZZRZ.jpg)

![2](http://i.imgur.com/1pJF9ZF.jpg)

![3](http://i.imgur.com/aHjKWO3.jpg)

**Comment by kilbith** [comment]
I confirm this : https://lut.im/MBE5i7Pu/NUV317gj

And I notice some straight things like that here and there...

@paramat

**Comment by Zeno-** [comment]
Actually, it's present way back in https://github.com/minetest/minetest/commit/6b4307791af9aab3620 so maybe it's not worth worrying about :)

**Comment by C1ffisme** [comment]
I may have seen these a few times. Although why do we call them artifacts? Dosen't artifact mean something along the lines of treasure or something? Sorry, whenever I hear the word artifact, I think of the cart thingys from Age of Empires.

**Comment by kilbith** [comment]
@C1ffisme : you're going to telling nonsense on the whole repo for how long ? GitHub is not a forum. You ought move your noise elsewhere, boy.

**Comment by paramat** [comment]
I have seen these occasionally for a long time, they are ugly and worrying at first but they are curved so i think these are just a result of how mgv6 terrain is generated from noise. These may be very low cliffs along the curve where 'height select' is blending between the 2 terrain noises, Since mgv6 terrain is not allowed to be changed, and has not been changed for years these may be present at these locations 2 years ago, anyone want to try that?
I won't close this without discussion and explanation though ;)
I might try adjusting 'terrain base' or 'terrain higher' to see if these really are cliffs, i'm curious how these are formed.

**Comment by C1ffisme** [comment]
@kilbith No reason to critisize people. I wander off from subjects sometimes. Technically, since github is a place for a younger class of teenagers too, it isn't a place for cursing, either.

**Comment by rubenwardy** [comment]
GitHub is for developers. We don't swear cause it's not professional.

**Comment by C1ffisme** [comment]
@rubenwardy True, true, but nevertheless, we should be more kind. Right now we treat each other like trashcans. Even the minetest wiki or minetest dev wiki says to watch your language on the forum.

@kilbith Even if you are right, talk paralel to other people. The correct way to speak is:
```Please, keep the conversation ontopic.``` as a reminder, rather than kick people in the shins like:
```Get out of here! You are a (something really bad, I won't give an example)! You have no place here!```

Speaking of which, we are offtopic. Let's get back ONtopic.

**Comment by rubenwardy** [comment]
You shouldn't need reminding to stay on topic. It's a simple google/search for computer artifact to find this: http://en.m.wikipedia.org/wiki/Digital_artifact
Also, where did he swear at you?

**Comment by C1ffisme** [comment]
He didn't swear in this one, but I know he has. Not that other people haven't on minetest before. :p (again)

Yeah, I just need to spit my opinions and memory at occasional moments. This is the only place I get to communicate with the developers of minetest (And please don't start a forum account conversation. That would REALLY get offtopic.).

**Comment by paramat** [comment]
So i tried changing some mapgen noise parameters to alter the lines, the only one that had any effect was mgv6 mud noise, which decides how much depth of biome material is added on top of stone, this makes sense as this would gradually change across the terrain in steps of 1 node, causing long lines to appear. I changed the mud noise seed and the lines were still present but in a different pattern.
So i'm sure this is not a bug, okay to close?

**Comment by Zeno-** [comment]
Closing
