### ISSUE TITLE
Automatic line breaks for tooltips

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2440]
If you have a long line in a tooltip and a low screen/window resolution, this line may not fit entirely on the screen, so part of the text can not be seen.

I suggest that tooltips get automatic line breaks, if neccessary, similar how textareas get automatic line breaks.

Note: This can currently be worked around by adding manual line breaks every 80 characters or so.

**Comment by paramat** [comment]
Any more comments?
Is anyone interested in coding this sometime? if not closing in 1 month.
Is it not better to control the breaks by carefully formatting and manually adding them? Leaving it to be automatic seems sloppy.

**Comment by paramat** [comment]
Old and no support, low priority.

**Comment by Wuzzy2** [comment]
Seriously? Whenever I use any multi-line widget I have to add tons of boilerplate code only to get the line breaks right. This can't be right.

And even this is a very crappy solution and **not** a suitable workaround as my boilerplate code is completely unaware of the actual widget's width. In my big modpack named “Help” I make heavy use of a complex and terribly-hacked-together fake multi-line widgets in which I did exactly that. Line length is limited to exactly 80 (even if the actual widget is much wider) because I can not make any assumtions about the screen width, so I am forced to use a very low line count.

Look:

![](https://i.imgur.com/ugmGZTH.png)

> Is it not better to control the breaks by carefully formatting and manually adding them? That is not a 'workaround', leaving it to be automatic seems sloppy.

No. Automatic line aren't sloppy, they a pretty much standard practice in basicallly … all of modern software (for example the browser in which you read this very text :P). *Manual* line breaks are sloppy.

**Comment by paramat** [comment]
> In my big modpack named “Help” I make heavy use of a complex and terribly-hacked-together fake multi-line widgets in which I did exactly that. Line length is limited to exactly 80 (even if the actual widget is much wider) because I can not make any assumtions about the screen width, so I am forced to use a very low hardcoded character count.

Ok i see your problem, but this issue is for tooltips, which are meant to be used as small boxes that will always be smaller than anyone's game window. Your use is a rare and hacky use of tooltips.
Note that your limited length lines are much more readable than if they were full width, and ideally your tooltip box should not be that wide.

Yes automatic line breaks are standard generally, but you're referring to multiple general usage, here we're talking about MT tooltips which is a very different thing. I would not expect tooltips to line-wrap as i would expect them to be small or narrow boxes with manually chosen line breaks.
