### ISSUE TITLE
Eye-like brightness 

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#2450]
Our eye can see a large spectrum of brightness levels.
When you were in a dark room and go outside where the sun is shining, everything looks damn bright but after some seconds, you can see everything in a normal brightness.

The same thing could be added for Minetest. This prevents from too bright sceens and thousands of torches to make a cave brighter.

What do you think?

**Comment by MT-Modder** [comment]
I like it :+1:

**Comment by LeMagnesium** [comment]
Good idea, would need quite a log of work to change the player's view's brightness, store it, and calculate the changed, but it is possible. Also, there shouldn't be too much light, otherwise our real eyes would hurt. The idea is good, but it must be optional :+1:.

**Comment by MoNTE48** [comment]
:+1: Good idea!

**Comment by C1ffisme** [comment]
:+1:

**Comment by TeTpaAka** [comment]
While adding this, there should be also an option to set the perceived lightness from lua to support different player classes. :+1:

**Comment by paramat** [comment]
Interesting idea but i'm not keen, even as an option, due to the complexity and processing of detecting and storing the brightness of what the player sees. Also, our real eyes will already be doing this looking at the monitor. This is similar to the request for motion bluring: there's no need to add it because our real eyes are already motion bluring looking at motion on the monitor.
With a delayed player-eye adjustment the screen would inevitably be ultra-bright every time the player moves into a brighter area, this is unhealthy for our real eyes. if the adjustment was instant this would be better and more simply done with alpha settings or a custom light table.

**Comment by TeTpaAka** [comment]
Wouldn't it be possible to modify the lighttable dynamically and cap to bright values? That way, the current system is more or less kept and the brightness will not be too much while still enlighting dark areas.

**Comment by Calinou** [comment]
Eye adaption is possible using shaders. For an example, look at [Tesseract](http://tesseract.gg). I think [Terasology](http://terasology.org) does it too.

**Comment by paramat** [comment]
Torches were made darker a while ago, we could make them a little brighter as a simple way to mimic this. Light levels are already compressed compared to real life so Minetest in a way already brightens dark areas, note that even deep underground away from all light the screen is never completely black.

**Comment by Zeno-** [comment]
> note that even deep underground away from all light the screen is never completely black

Well, that could be easily changed.

**Comment by paramat** [comment]
I think it's that way for good reason, to make more use of the limited light range we already have. Light level zero actually has a very low amount of light, making it black would further reduce light range, no one wants that.

Addressing everyone firmly, not harshly...
You should not even contemplate a feature with this deep level of realism for an inherently abstract, simple voxel game, otherwise there would be hundreds of other realistic human behaviours to add. Celeron has stated that realism is in no way a goal of Minetest. If you want realism you should go and play a photo-realistic game, that's where these sort of features belong. The very nature of a voxel game is extreme abstraction and simplicity that enables the modifiable open world we love. Voxel games are not imperfect representations of a real world, they are perfect representations of a completely abstract world which just happens to have some similarities to the real world. The character you control is not a human being so many realistic features are just not needed.

The devs are already overwhelmed trying to fix bugs and maintain the simple features we already have, so please everyone restrain yourselves and think: is this really suitable for an ultra-simple abstract virtual world? is it a complex processing heavy feature that will soak up dev's precious time coding, debugging and maintaining? Is there a much simpler way to do much the same thing?

Personally i am currently working full time on Minetest and all my time is filled with bugfixes, maintainence and adding simple new mapgen features. I am being delayed in adding a new mapgen and diverted from working on my lua mods which i miss like crazy. This is why the devs so often say no to complex, realistic and unsuitable feature requests. Celeron's central philosophy for Minetest seems to be K.I.S.S. for good reason.

In this case we should make a PR for a higher torch light level or a user-customisable light table, that is quick and easy to do and adds no processing load or dev time for bugfixing and maintaining.

**Comment by ShadowNinja** [comment]
@paramat: You may like Minetest that way, but others may like it as realistic as possible given the basic constraints like grid node placement.

Fancy effects are good as long as they're configurable.  There are higher-priority things, but this is still good.

**Comment by SmallJoker** [comment]
@paramat
I respect your and Celeron's targets of this game. I agree, Minetest would be completely overloaded with complex human-like features.
If this gets addedn, then surely with an turn on/off setting and some additional configurations.

**Comment by hoodedice** [comment]
Do you mean *HDR*?

(doc: https://developer.valvesoftware.com/wiki/HDR)
(doc: https://developer.valvesoftware.com/wiki/Advanced_HDR)
(img: https://developer.valvesoftware.com/w/images/7/73/HL2_LostCoast_17.jpg)
(img: https://developer.valvesoftware.com/w/images/2/2a/Lostcoast_bay.jpg)
From Half Life: Lost Coast, a technical demo. HDR is available in the unity5 game engine, and in Valve's source engine games, and many others.

Personally, my opinion on the matter:
1. HDR is very very nice, and if implemented properly*, will boost Minetest's graphical appeal by a factor of at least 9000.
*See HDR in Euro Truck Simulator 2 -- 4am seems like 7am, due to faulty HDR, too bright.
(http://cloud-4.steamusercontent.com/ugc/39735969223916793/C0E7DE2ADFADE64F09557EF5392E8C16299F2007/)
2. HDR is very very expensive on the hardware. We have tons of other graphical things to fix before we can even *dream* about implementing Bloom or HDR. Thanks to RBA and others, we at least have live shaders, which in itself is a big thing.
3. I'm not sure about the current state of the game, having being AWOL for a while, but related to 2, we need to shift graphics stuff to the GPU before we can start processing high end things. Apologies if someone already started work towards this end. If we can push things to the GPU, we will have a lot more power at hand to do stuff.
4. We have an engine refactor in progress. As such, concentrating on that should be of paramount importance =D

@paramat : Also, I do not think that your eyes keep adjusting to a monitor's screen. AFAIK, HDR works by, in simple words, changing the contrast of different parts of the scene, or in valve terms, changing the exposure of the camera. This means that your screen brightness is always the same. Your eyes are always adjusted to the monitor brightness, and HDR in its entirety is just a gimmick.

**Comment by Calinou** [comment]
> 2. HDR is very very expensive on the hardware.

It is rather cheap if done well, actually. It can be done using shader stuff.

**Comment by est31** [comment]
eb3840a3f88dd9902ff1c5ea50d90a7f33e08d82 fixed this

**Comment by ShadowNinja** [comment]
RBA's "HDR tone mapping" doesn't seem to include the "HDR bloom" effect that this issue mentions.
In fact, the tone mapping just seems to make everything a bit brighter.

**Comment by Fixer-007** [comment]
Not only brighter, it is tone mapping after all :)
