### ISSUE TITLE
connect_to_raillike group doesn't work as it should

### ISSUE THREAD

**Issue by MT-Modder** [minetest/minetest#2479]
If you test this patch: https://github.com/minetest/minetest_game/pull/435
you can see that when a regular trail of gunpowder starts to burn the facedir is reset. I've added param2 to the burn function but this still doesn't fix it. Any suggestions?

**Comment by Wuzzy2** [comment]
I have tested it, and it is weird.

I have temporatily disabled the timer and the automatic destroying of burning gunpowder, then I placed some gunpowder and burning gunpowder trails.

It seems the issue is *not* that the “facedir is reset”, but that the burning gunpowder simply does not connect with the gunpowder in the first place.

Sigh. I thought the `connect_to_raillike` groups were implemented?

BTW, I used `connect_to_raillike=3` for both nodes.

My used Minetest version is: de6d5ce2cd68cf43ded6f739e58af7de4ef5e28f

**Comment by Wuzzy2** [comment]
Okay, it sees to be an engine issue. Apparently the commit which is supposed to add conntect_to_raillike group support does not work at all.

I have written a small mod for testing this:
http://rghost.net/8NhTfPLY5

This mod adds 4 pseudo-gunpowder trails in 4 different colors. All have `connect_to_raillike=100`, so all of them should connect to each other, regardless of color.

But they don't:
https://i.imgur.com/AbHQAS0.png

It looks like Minetest treats all 4 trails independently.


If the above link is dead and you need the file, plase contact me.


I tested in: de6d5ce

**Comment by MT-Modder** [comment]
Oh okay that seems like it would be easier to fix rather than a facedir issue :-)

**Comment by MT-Modder** [comment]
Has this been fixed? You(kwolekr) didn't comment a commit.

**Comment by Zeno-** [comment]
Ooops
Was it this commit: 709f4a50f73fd6c61412cf77516ed767893486ab?

**Comment by MT-Modder** [comment]
Yeah that's it :). Thanks

**Comment by C1ffisme** [comment]
I found another bug where normal nodes with connect_to_raillike won't connect to raillike nodes.

**Comment by MT-Modder** [comment]
@C1ffisme Damn and the numbers for the group are the same?

**Comment by C1ffisme** [comment]
Yes. Avoid swearing, Mt-modder.
