### ISSUE TITLE
New, round item selector HUD from Voxelands

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#2552]
Source of this idea:
![Hud](http://sandbox.ltmnet.com/images/vl/1503.00.png)

The round selection area is small and can hold 8 items like with the current HUD.
I hope this gets added to Minetest to improve the gameplay.

**Comment by PilzAdam** [comment]
How does this improve gameplay?

**Comment by Calinou** [comment]
This is not an improvement over the current one.

There's a reason we use bars (horizontal or vertical) instead of circles.

If you want to improve intuitiveness, switch to a vertical bar, not to a circle.

**Comment by kilbith** [comment]
> This is not an improvement over the current one.

This is not an absolute statement either... 
It adds stylistic variety, it feels minimalistic and exposes the world better.

Ideas : 
**[1]** The "ring of item boxes" could fold/unfold in pressing a key.
**[2]** A coloured selection around the item box.

Note : this shouldn't replace the current HUD style, just optional.

**Comment by C1ffisme** [comment]
> Note : this shouldn't replace the current HUD style, just optional.

I agree with kilbith. This should be optional, but still available. I personaly think it looks good.

**Comment by Megaf** [comment]
Please don't, this is one of the things I hate the most in modern games, just don't add that.

**Comment by C1ffisme** [comment]
@Megaf You don't have to keep it on. It will (hopefully) have a setting.

**Comment by paramat** [comment]
Sorry, no thanks, this is a bad design.
The design style, being round amonst other things, is unsuitable for Minetest.
It's less intuitive which number key refers to which item.
It's too small, the items are hard to see, if it were larger and/or expanded to hold more items it would start to clutter the central screen area, that's why flat bars are better.
It covers the wielditem and unnecessarily displays the wielditem we can already see.
Being unsuitable and unnecessary it should not be an option, that's just more bloat and more maintenance work for devs.

**Comment by SmallJoker** [comment]
I know, many people like the current HUD, but as an optional feature, it would give an alternative if players want to try something else.
The icons could be displayed bigger to be better visible. (there's still some space in those fields)

The wielditem was moved a little to left to not be covered by that circle.

**Comment by Zeno-** [comment]
> The design style, being round amonst other things, is unsuitable for Minetest.

Umm, the hearts and bubbles are round. I fail to see how something being round is unsuitable for Minetest

**Comment by indriApollo** [comment]
@Zeno-  Yes but they are pixelated, following a cubic visual style. I share the views of Paramat and Celeron55, otherwise we are just a voxel copy of Gmod :)

**Comment by Zeno-** [comment]
@indriApollo Huh?

Are you saying that a round HUD is not enough like minecraft?

I don't see the connection between following a cubic visual style and what the HUD displays. If everything must be pixelated then we must also remove freetype support and use only bitmap fonts.

**Comment by Holyphoenix** [comment]
"otherwise we are just a voxel copy of Gmod" -What's wrong with that?

I don't think its worth it to add it as an optional feature even though I think it looks nice. Including multiple hardcoded UIs in minetest just sounds ugly to me.   

I wouldn't mind having a more customizable UI though.  Maybe draggable windows that we can place where we want and a possible styling file similar to css or less for making customizations would be cool.

**Comment by paramat** [comment]
Sure, the roundness being stylistically unsuitable is a somewhat subjective issue, but looking at that screenshot it's speedometer style really does look out of place.
The randomly scattered icons in the corners are messy, and rely on a small difficult to read percentage value to be displayed instead of a shrinking bar that is clear even when you are focussed on the world.
The way the circular item selector overlaps the wielditem makes the item icons even more unclear.
I'm surprised and disappointed in Voxelands for using such a poor HUD.

It's much better to have one good design (what we have already) than to have a variety of good and bad designs just for the sake of choice, that philosophy leads to a hugely bloated and difficult to maintain game with a poor diluted character. We should just KISS =)
As hmmmm has said recently, Minetest is so broken at the moment the last thing we should do is fix what isn't broken, we are already very much under-staffed with devs busy with basic maintenance and bugfixes.

**Comment by rubenwardy** [comment]
Minetest is an engine, no? We need the HUD and Formspec systems to be flexible enough to do things like this, even if we don't utilise them.

**Comment by darkrose** [comment]
There's 3 kinds of responses the new voxelands hud gets:
"I saw a picture of it and it's not like minecraft, that sucks"
"I saw a picture of it and don't know how it works, that sucks"
"I played with the new hud, it's awesome"

Also, there's a license conflict if anyone tries adding this to minetest.

**Comment by rubenwardy** [comment]
There's only a licence conflict if you use the code from voxelands, not the
inspiration. I don't suggest that we do, the better solution would be a HUD
rewrite which would allow us to make our own things like this.

**Comment by kilbith** [comment]
[Inspiration] ItemWheel, by @BlockMen : https://forum.minetest.net/viewtopic.php?p=176010#p176010

**Comment by BlockMen** [comment]
Improved version https://forum.minetest.net/viewtopic.php?p=176081#p176081 :)

**Comment by paramat** [comment]
@SmallJoker old issue, still want to request this?

**Comment by SmallJoker** [comment]
A request for this feature isn't present.

**Comment by tchncs** [comment]
I think the current voxelands hud is very beautiful.
While knowing it is already decided for you, i wanna say anyway - it would be nice if minetest supports such things so people may be able to write such a thing as a mod.
The linked mod attepts are interesting but not as efficient as the voxeland version i would say.

**Comment by C1ffisme** [comment]
The thing that gets me about this is that it seems to be saving screen space in the middle of the screen for... nothing at all.
