### ISSUE TITLE
Skipped on_item_eats functions

### ISSUE THREAD

**Issue by LeMagnesium** [minetest/minetest#2615]
Hello,
I recently found something very strange while working on the new hunger mod. Here is the explaination : the new [hunger](http://github.com/BlockMen/hunger/) mod by @Blockmen is using a new way to know when players eat some food without changing the function in the on_use fields of their definition : it registers a function in the `core.on_item_eats` table, which (is supposed to) launch this function whenever a player eats something, an item with `on_use = minetest.item_eat(foo,bar)` . However, while using the mod, I noticed that the function was never launched. After a complete day of removing mod per mod, using another game, and even read some of the builtin registration function, I discovered something : the game we were using (@Ombridride 's [one](https://github.com/Ombridride/minetest-minetestforfun-server/tree/master/minetestforfun_game) ) contained another call to `minetest.register_on_item_eat` with a function returning true to cancel the engine's answer to eat, and to stop its job. But when I removed it, hunger's function started to run, and could make the hunger system work. So why?
In a nutshell, when the engine is parsing the `core.on_item_eats` table, whenever one of the functions returns the itemstack or true (to abort its job, or to cancel the engine answer), the following functions (registered after) are skipped, because **the engine stops parsing when a functions cancels the engine answer by returning the itemstack**.
It means that something like : 

    minetest.register_on_item_eat(function()
	    print("foo")
    end)

    minetest.register_on_item_eat(function()
    	print("bar")
    end)

    minetest.register_on_item_eat(function(hp_change, replace_with_item, itemstack, user, pointed_thing)
    	print("done")
    	return itemstack
    end)

launches the three functions while this : 

    minetest.register_on_item_eat(function(hp_change, replace_with_item, itemstack, user, pointed_thing)
    	print("done")
    	return itemstack
    end)

    minetest.register_on_item_eat(function()
    	print("foo")
    end)

    minetest.register_on_item_eat(function()
    	print("bar")
    end)

only sends "done" (and both of these pieces of code break hunger's system because the mod is loaded after). (tested on minetest_game at https://github.com/minetest/minetest_game/commit/fe7a982343c2836e61b44743bf28115c7df7abb2 with engine at 0a413265cb7057b5303733dd32cf802a9ecf6105 )
This can be a big problem whenever a mod is loaded before another one and contains a on_item_eat function canceling the engine answer while the other one, for example, only send a debug print, or plays a sound at the player.

**Comment by Ombridride** [comment]
+1, 
I confirmed and aprouved we need an update/upgrade/improve of this function...

**Comment by rubenwardy** [comment]
This is expected behaviour. The other callbacks, eg: on formspec fields receive, do this. You can run the other callbacks and still modify the itemstack by not returning an itemstack or true, as it's pass by value. However, the default action will run.

I am the author of minetest.register_on_item_eat.

It would be useful to be able to override default behaviour without stopping the other callbacks from running. The point of cancelling is so that the other functions don't process the event twice, but I guess it is realistic that there is only one hunger mod installed at a time.

**Comment by rubenwardy** [comment]
I suggest either separating effects (sounds, etc) from mechanics (hunger) but it needs to be done in a backwards compatible way.

Why do the call backs in the subgame return non nil? They shouldn't if they don't modify it.

**Comment by rubenwardy** [comment]
This is the code in question: https://github.com/Ombridride/minetest-minetestforfun-server/blob/a1dfa30979a782e3ec0213df05ac53f25b1833d8/minetestforfun_game/mods/default/init.lua#L93
It doesn't seem compatible with HUD/hunger, anyway, it relies on the default processing of food. A register_on_hp_change callback might be better for it.

**Comment by LeMagnesium** [comment]
This piece of code was suppressed, but anyway, if it's an expected behavior, there is no reason I keep this issue open. It will be closed in 2 days , so if anyone wants to let an opinion or propose something else, they are free to do so.
And hud_change callback could be a good idea, but must start after the on_item_eat process is finished (if the hud_change is from some food) and the engine did its work (increasing hp, or nothing).
Thanks for responding @rubenwardy .

**Comment by Wuzzy2** [comment]
I recently bumped into this issue again. This is causing me some headache.

Here's the deal: There are two mods:

`hbhunger` now calls this function and returns a modified itemstack.
But the `awards` mod also calls this function and does not return anything. This is because it only wants to detect *when* something was eaten but not change the eating behavior.

I think the current design is somewhat flawed. I understand the rationale that there shouldn't be multiple itemstack-modifying eating mods. But what I don't understand that as soon any mod returns an itemstack, no other mod is even allowed to know that something was eaten at all.

More awkwardly, it appears the order in which the callbacks were added matters. So if the itemstack-returning callback was added first, it stops all callbacks after it. But if it was added last, the other callbacks will run.

So for now I did a hacky workaround in `hbhunger` by forcing it to run its callback last. And it somehow works. Strange.
