### ISSUE TITLE
Verbose logging bloated regression

### ISSUE THREAD

**Issue by est31** [minetest/minetest#2636]
When you are starting minetest in singleplayer (connecting to remote servers triggers this too) and are running with the `--verbose` flag, you get many many messages of the kind `INFO[main]: ClientEnvironment::processActiveObjectMessage(): got message for id=0, which doesn't exist`.

I have found out that commit 8804c47e59b550ec9a533de662f086af623d68c1 has caused this regression, to be more precise the change that replaced `0` with `datas.size()` in `NetworkPacket pkt(TOCLIENT_ACTIVE_OBJECT_MESSAGES, 0, peer_id);`. If you change it back to 0, the messages disappear. This isn't of course a proper fix of the root cause, which either lies in networkpacket, or some other lower layer networking code. Therefore medium priority.

@nerzhul can you have a look at this?

**Comment by est31** [comment]
Additional information: when I'm adding to `handleCommand_ActiveObjectMessages` the  logging line `errorstream << "got message with length " << datastring.length() << std::endl;`, I'm seeing that in the bloating case the client gets messages of length 102, in the non-bloating case it gets messages with length 51.

**Comment by nerzhul** [comment]
Datas.size is set in packet constructor , this reserve packet size directly instead of reallocate memory in putRawString. I will look at a modification on this handler tomorrow, this copy isn't needed, we should write datas to packet directly

**Comment by est31** [comment]
I don't understand: Where is a copy?

**Comment by jayarndt** [comment]
I think the problem is that `NetworkPacket::putRawString()` has an edge case triggered by the written string being the exact same length as the free space in the packet. Then, instead of increasing the size of the packet by the amount the buffer was exceeded, it increases the packet size by the size of the written string. Thus, the packet ends up being twice the size it needs to be and padded with zeros.

The client, after processing the good first half of the packet, runs into the spurious zeros and interprets each 4 bytes as a message for object 0 of zero length. For each spurious message, the client then complains that it can't find object 0.

**Comment by est31** [comment]
2923eafaca929e129ba81504676d3770cff5f681
