### ISSUE TITLE
Possibility to rotate entity's collision box

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2721]
I have a feature request:

Add the possibility to rotate the collision box of entities. Currently, it is always static.

**Comment by C1ffisme** [comment]
:+1: 

Yes.

Please.

Add.

Now.

**Comment by ExcaliburZero** [comment]
This would be quite useful. :+1:

**Comment by Calinou** [comment]
> This would be quite useful.

Easier said than done.

**Comment by RHRhino** [comment]
I think we already had this feature request some month ago. I think it was refused (or ignored) because it is difficult to add. They had to rewrite the collision system, because it is based on block position instead of the mesh and block faces, if I remember correctly. However, better ask someone of the devs who is well versed with this topic.

**Comment by 4aiman** [comment]
@RHRhino this was asked years ago, not months ;)

Sapier to the rescue! )))

@Calinou  
Ellipse won't work.


@everyone 
Let collision box to be cubic, but make it to take size of a rotated mesh. 

*Example:*

With yaw == 0, a cow would have ```{-0.5, -0.5, -0.2,  0.5,  0.5,  0.2}``` collision box.
With yaw == 45 degrees, a cow would have a collision box that is a minimal rectangular cuboid in which the whole mesh fits. That well may be equal to ```{-0.55, -0.5, -0.55,  0.55,  0.5,  0.55}```

**Comment by paramat** [comment]
Might be very difficult as collision probably works with aligned cuboids as these are simple.

**Comment by paramat** [comment]
> Let collision box to be cubic, but make it to take size of a rotated mesh.

Seems the only way to do it.

**Comment by paramat** [comment]
@Wuzzy2 Could you update the title? Are you still requesting fine rotation of a box?
if so i am -1.
 
Fine rotation will make collision detection very much more intensive due to angles.
Instead, the cuboid box could perhaps change dimensions depending on the rotation of the object, but that has it's own problems. Imagine a long narrow object, when aligned with axes no problem, but if at 45deg to the axes its collisionbox would be a huge square shape that would itself be a problem.

**Comment by paramat** [comment]
Related #1586 once we have a rotating collisionbox it would be simple to set the selectionbox to this.

**Comment by paramat** [comment]
Very difficult as explained, and very intensive for collision code.
