### ISSUE TITLE
Sound pitch

### ISSUE THREAD

**Issue by KenneyNL** [minetest/minetest#2727]
Similar to how Minecraft makes 'random' sounds by slightly changing the pitch of the sounds played, could be added to the SoundParameters property. This would eliminate a lot of sounds, thus file size.

``` lua
minetest.sound_play("testmod_foobar", {
    to_player = "foo",
    gain = 2.0,
    pitch = math.random(-1, 1),
})
```

Previous discussion:
https://forum.minetest.net/viewtopic.php?f=5&t=11031

**Comment by celeron55** [comment]
This has one important design concern: SimpleSoundSpecs are stored statically in for example node definitions for the footstep sounds. In those cases a simple numeric pitch parameter does not allow making random pitches because the pitch would be the same all the time.

As random pitches are likely needed for footsteps and similarly defined sounds, something like `{random_pitch = [0.9, 1.1]}` needs to be supported instead or additionally.

(Review for bounty: OK with a different API)

**Comment by FreeLikeGNU** [comment]
It would be nice to set pitch of a sound played through the lua api for doing things like mining punching etc.  Sounds can get tedious without this.   Is just adding multiple copies of the same sound file at different pitches acceptable?

**Comment by HybridDog** [comment]
There's a minetest.sound_play and minetest.sound_stop function, l don't think adding a minetest.sound_pitch function would be very difficult.

**Comment by rubenwardy** [comment]
You have to remember about latency and lag, that's the problem. Sounds and effect would be better managed by client side lua - although that should stop setting the sound_play() pitch.

**Comment by HybridDog** [comment]
you could also add sound modifiers similar to the texture modifiers

**Comment by thePalindrome** [comment]
I'd like to see this happen sometime, it's pretty easy from openal, just using alSourcef(source, AL_PITCH, pitch_variable)

Perhaps we could get this going for 0.4.16?

**Comment by Rui-Minetest** [comment]
https://github.com/minetest/minetest/commit/ff73c7a5da6ab8ac0bb678ebf25b83e805397029
