### ISSUE TITLE
Players not connecting to boats or carts

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#2733]
In the latest 3831 build when right-clicking to enter a cart or boat, players are not connecting to the actual vehicle but can still control it while standing away from it...  bug...

**Comment by rubenwardy** [comment]
This is due to https://github.com/minetest/minetest/commit/21878c9d5c364faa1f43c84c51804d9b7dbe376f

**Comment by est31** [comment]
This is likely caused by 21878c9d5c364faa1f43c84c51804d9b7dbe376f (aka `[3831](http://bazaar.launchpad.net/~minetestdevs/minetest-c55/upstream/revision/3832)`) should be **fixed** by 990a96578f20244626b6b9f67f8e79a7e2e614ea (aka `[3832](http://bazaar.launchpad.net/~minetestdevs/minetest-c55/upstream/revision/3832)`).
