### ISSUE TITLE
Better tab complete

### ISSUE THREAD

**Issue by nolsen42** [minetest/minetest#2788]
It'll be easier to perform nick/item/command completion, so instead of typing the full thing, you just type enough letters then just tab it until you got what you want.

**Comment by Snipie** [comment]
Yes, this would be nice.

**Comment by est31** [comment]
I'm planing to add this since some time, but haven't gotten around yet to write it.

**Comment by est31** [comment]
However, limited tab completion is already present, however only in the f10 console.

**Comment by Snipie** [comment]
@est31 How is that ? I've just tried it and it's not working.

**Comment by est31** [comment]
Only working for nicks.

**Comment by C1ffisme** [comment]
Yes please! They have this in Minecraft (Yes, I know, another minecraft ref, just ignore) and it's extremely helpful when you need to say... Get your coords for the /fill command.

**Comment by hunter688** [comment]
any kind of tab completion will be very useful, complete nicks, ingame commands, commands arguments etc...

**Comment by Dragonop** [comment]
Yeah,this would be cool. +1

**Comment by HybridDog** [comment]
it could work this way:
* if the client presses tab, the text he/she is writing and the cursor position become sent to the server
* the server passes the text to lua
* builtin, mods etc. can change the text, then it's sent back from lua
* if it was changed, the new result and cursor position are sent to the client
* if the text of the client is the same as before (because of asynchrony), it gets replaced with the new one and the cursor position is set (optional)

**Comment by HybridDog** [comment]
l added CSM chat autocompletion. l'd be glad if you help testing it.
https://github.com/HybridDog/minetest/tree/tabacl

**Comment by paramat** [comment]
Any more comments?
Is anyone interested in coding this sometime? if not closing in 1 month.
