### ISSUE TITLE
Attachments experience movement delays, triggered randomly

### ISSUE THREAD

**Issue by MirceaKitsune** [minetest/minetest#2813]
I found a weird and annoying issue with attachments. As much as I implemented the initial attachment code, I cannot figure out what is causing this and why. It might be an Irrlicht bug, although I'm inclined to suspect something Minetest side as well.

When an object is attached via obj:set_attach, there will be times when it follows its parent smoothly as it moves around, instead of instantly duplicating its position and rotation like it should. The problem is only triggered randomly too: Sometimes I would restart the game and it works fine, at other times there's the movement delay.

I only tried this by parenting a Lua entity to a bone on my player's model, then watching myself in 3rd person view as I moved around. Some of the objects are firmly attached to me, while others follow me slowly and it looks off... which does which is always random whenever I start the game.

**Comment by est31** [comment]
Yea seen it too.

**Comment by stujones11** [comment]
I can confirm this too. fwiw, this bug does not seem to be present in the 0.4.10 client.

**Comment by MirceaKitsune** [comment]
Can anyone do a GIT bisect and see which commit between 0.4.10 and latest master introduced this issue? Obviously I can try it myself, but currently I'm working on several mods and can't mess up my GIT setup, so it might have to be a while later for me.

**Comment by stujones11** [comment]
I have finally figured this one out, at least the problem I am seeing.

I decided to bisect this because I was sure this problem did not exist in 0.4.10 
and have found that it started when we switched to b3d format for the player model.

You can prove this by installing my wield3d mod https://github.com/stujones11/wield3d

Use third-person view to witness the 'hand-switching' of the attached item when the player moves.
Now checkout the xhack branch which is simply an older version that used a custom directx model.

The reason I thought the problem did not exist in 0.14.10 was because my test world used an older
version of the wield3d mod.

Unfortunately reverting to directx format is not really a solution here because it had it's own
issues, the model included with the original wield3d has been especially modified to work around them.

**Comment by 0-afflatus** [comment]
Is this what makes riders on horses and boats 'disappear' as well?

**Comment by stujones11** [comment]
Nah, different issue mate #3681

**Comment by DS-Minetest** [comment]
Afaie this problem only appears if the attach bone string is not empty.

**Comment by raymoo** [comment]
Something I noticed is that nametags for the objects don't lag behind, only the objects do. The nametags are rendered as if the objects were properly sticking to the player.

**Comment by stujones11** [comment]
> Afaie this problem only appears if the attach bone string is not empty.

For what I can tell, the lagging effect seems to happen only for objects attached to the player, as opposed to the player being attached to an object. However, there is a bug somewhere in either Irrlicht, the b3d exporter or the player model itself that causes that attachment to be inverted when the main armature bone crosses the 0,0,0 rotation vector.

I am not 100% sure this is the same problems reported by the OP but a problem nonetheless.

Related: https://github.com/minetest/minetest_game/issues/1447#issuecomment-265825919

**Comment by raymoo** [comment]
LocalPlayer is updated sooner than other objects to be responsive to player controls. If that is what is causing the attach delay then we will be a lot closer to a fix (for the delay problem).

**Comment by tacotexmex** [comment]
Just a visual example of the issue:
![namnlost 1](https://user-images.githubusercontent.com/25328789/41704377-5cbcd4cc-7536-11e8-9106-80920c4b98db.gif)

**Comment by Warr1024** [comment]
It looks like the root cause of the problem is in ActiveObjectMgr::step, it simply walks through m_active_objects in whatever arbitrary order they are in and runs step for each.  If the parent object is updated first then the attached object will appear correctly attached.  If the child object is updated first, then it will be attached to the position of the parent object on the _previous_ frame.

The fix is probably either to enforce partial ordering of m_active_objects so that parent objects are always listed before their child objects, or to only call step on non-attached objects and make them responsible for recursing down to attached objects after running their own step updates.

**Comment by Warr1024** [comment]
Since this problem is non-deterministic, it would really help if I could get some _statistical_ information from commenters.  Especially things like:

- What is roughly the probability of seeing the issue with each attempt?
- What do you need to do to separate attempts?  Just quit to menu and reload the world?
- About how many times in a row should I expect to need to test to see at least one instance of the problem?

Additionally, if somebody could publish a _minimal_ repro mod, especially one that can more reliably recreate the issue, that would expedite testing.

**Comment by Warr1024** [comment]
One odd thing I noticed is that it seems to depend on visual type.  `wieldmesh` ents seem to experience this while `upright_sprite` ones don't.  If I have multiple ents attached to a player and some are `wieldmesh` and some are `upright_sprite` then either all of the `wieldmesh`es lag and none of the `upright_sprite`s do, or none of the ents lag.

That seems to suggest that it's not a problem with step order as I had suspected and that it's something specific to `wieldmesh`...

**Comment by SmallJoker** [comment]
Cannot reproduce using:
 * Minetest 5.2.0-dev (few days old)
 * `gauges` mod
 * `wield3d` mod

Other than instant position glitches which are possibly caused by restarting the mesh animation, I don't see any lags.
https://krock-works.uk.to/u/attachment_no_lags-2019-11-19_19.40.53.mp4

**Comment by SmallJoker** [comment]
0) This is a client-only issue
1) The player is initialized as invisible because you don't want to see your own head's insides
https://github.com/minetest/minetest/blob/97764600e27f8872768a28ac4a379d1d82f86952/src/client/content_cao.cpp#L350-L352

2) Irrlicht cannot attach scene nodes to invisible scene nodes. It requires to detach and re-attach them, Minetest currently does not do that when changing the perspective.
3) Even if Irrlicht doesn't handle attachments, Minetest will still do it. Just bad that the instant position update is never run, and is probably very outdated.
https://github.com/minetest/minetest/blob/97764600e27f8872768a28ac4a379d1d82f86952/src/client/content_cao.cpp#L835-L841

**Comment by Warr1024** [comment]
Ah, I didn't think about the client step and client framerate being out of sync.  That would be consistent with what I'm seeing, I suppose.

I can repro the issue on MT-master using NodeCore dev branch (a.k.a. NodeCore Alpha from CDB).  Create a new world, dig some sand or leaves so you have something in your inventory, then enter third person front view.  Some 10% of the time or so, entities are loosely attached and if you spin left/right, you'll see items in your hand or on your bandoliers lagging a step behind.  Make sure at least one of them is wieldmesh, because the upright_sprite ones that are there initially don't ever show the bug.  I often have to quit the world back to the menu as many as 10 times before I can repro it.

I can try to put together a more minimal, direct test case mod, including covering the other draw types, which are affected differently.  It's very interesting that upright_sprites seem unaffected (I have _never_ been able to see them lag), while wielditems are.  The obvious difference I see in the code has to do with how they're attached to their parent nodes; upright_sprites upon being added, and wielditems via a separate setParent call.

**Comment by hecktest** [comment]
Just to clarify something; someone here said that using a directx mesh somehow fixes this, well, no, I use .x exclusively and this still happens. Irrlicht does not differentiate between model formats after importing them.

I've noticed three ways an attachee can break. One is the transform delay. Another is the attachee vanishing when you board a vehicle.
And then there's the blinking in #9129

All of those issues seem related. You wanted statistics:
- Transform delay occurs most of the time, about 9 times out of 10, need to relog to reroll this. I've had no success resetting it by crossing the player send distance boundary. The hat may be lagging on one client but not on another. Still looking for a more reliable repro.
- Hat disappearing when boarding a vehicle, this I managed to reproduce every time by travelling far from one "boat" to another and boarding it. The other player can still see the hat. Cycling the camera (even front TPP to back TPP) makes it reappear. "Far" here probably means object send distance.
- Blinking on setting properties, not random at all. Dependent on drawtime _and_ on the transform delay status, so it's actually related. Does not happen with a high framerate and no transform delay. With the transform delay, high FPS does not prevent it.

Two things I haven't tried are: reattaching the hat while already in the game, and fiddling with network reliability.

**Comment by hecktest** [comment]
Oh wow, it can be different between stereo eyes.
![stereo](https://user-images.githubusercontent.com/42101236/69194961-c4697900-0b2a-11ea-859c-2c8339922d35.jpg)

**Comment by hecktest** [comment]
Actually, it seems that in 3D, one of the eyes is always correct.
![3d](https://user-images.githubusercontent.com/42101236/69195333-a18b9480-0b2b-11ea-8a29-3b1979cb3e6e.jpg)

**Comment by Warr1024** [comment]
Reattaching the hat doesn't do what you want either.  In third person view you can only see ents attached to your player if they were attached at the time you changed perspectives.  Since you can't detect when things have gone awry server-side, you'd have to regenerate the ents frequently, which will just lead to unreliability for players looking at their own models and probably flicker for other players.

It seems like, if Irrlicht had some callback we could hook that happens right before rendering a frame, then we could do the necessary manual attachment processing there, but I don't know Irrlicht well enough for that.

Are you sure it's always correct in one eye?  It could just be that the 2 eyes manifest the error independently of each other because they don't necessarily process the scene in the same order.

**Comment by hecktest** [comment]
It appears from my testing that at least one eye (always right, cyan) will always see the attachment in the right spot. Almost as if the transform didn't make it in time for one of the shots (the red, left one), but rendering it once fixes the problem. You can easily test this even without any fancy glasses.
And no, I didn't mean reattachment as a workaround (gods forbid), just to see if it triggers a "reroll".

One thing of note is that wrapping the helmet spawn/attach snippet in a minetest.after with a 2 second delay greatly increases the chances of the helmet being attached correctly, as opposed to doing it on player spawn. (extra bug: doing this in third person mode will not show the attachment until you cycle the camera, again, this seems related to the stupid delay where objectrefs will not show up for a few good seconds after logging in) 

Adding an extra 0.5s delay between spawning and attaching makes it even more stable. There's a timing issue in here somewhere, like if something is out of phase with another thing, then it will not work.
...Wait, rendering order maybe? If the parent transform is simply higher in the list of things to render, it may look right, but if it's above then the dependent one may have only the last frame's matrix to work with, because that isn't evaluated until the parent object is about to get drawn. Think about it, this only happens with bones. Are the bones just not animated until the related skinned mesh is drawn, as an optimization? This is something that just occured to me, I have not looked at the relevant code yet.

**Comment by Warr1024** [comment]
Oddly enough, which things lag and which don't seems to depend on which *mesh*, not which *entity*.

Note how the mallet always jiggles, whether on the body or in the hand, even though those are 2 entities changing mesh, not swapping attachment positions.  The charcoal neither jiggles in hand nor on the body.  The upright_sprites never jiggle in any position.

![test](https://user-images.githubusercontent.com/324806/69596911-3d0c8180-0fd2-11ea-9f46-35d696dff2d4.gif)

**Comment by LoneWolfHT** [comment]
Doing the same test as you I only get the lump to move :thinking:
![NC](https://user-images.githubusercontent.com/28972859/69599226-21e54600-0fc1-11ea-86c2-9e0a97ca1b3b.gif)
Using a tempered lode mallet

**Comment by MirceaKitsune** [comment]
Just dropping in to confirm this is exactly the effect I remember seeing. I didn't have the means to record a video of it at the time, but I'm glad others did to show exactly what's happening.

**Comment by hecktest** [comment]
Any changes in properties are a "reroll", it is possible for things to spontaneously break or fix themselves when you change meshes or textures.

**Comment by Warr1024** [comment]
@LoneWolfHT In your test, you should have cycled through the inventory to where you had the prills in your hand and seen if they jiggled while in your hand instead of the bandolier.  My hypothesis is that they would.

It seem like each _specific_ mesh either lags, regardless of which entity is using it, or it doesn't.  Upright sprites and other types use different attachment code, and it seems they never lag in practice, though it _could_ be because they get initialized earlier or something.

If you can find an item whose mesh lags _sometimes_ but not always, depending on which entity is using it, then that would disprove the hypothesis, but so far I haven't seen any counterexamples.  It seems like the fact that it's dependent on the mesh and not the entity should be a clue...

**Comment by LoneWolfHT** [comment]
Well, testing more it looks like sometimes it works perfectly. But then at other times only certain items will move, regardless of whether they are in the bandolier or the wielded item.
Moving them around in my inventory doesn't affect which items are rubber-bandy. This happens through multiple reloads of the world. The items and how many of them are affected seems to be random. I've never seen the slots rubberband
