### ISSUE TITLE
Support textures in folder

### ISSUE THREAD

**Issue by asl97** [minetest/minetest#2821]
this would allow us to group texture together in different folder.

note: googling texture folder only show a bunch of Texture Packs result

``` lua
inventory_image = "example/texture.png"
```

**Comment by est31** [comment]
If you have too much textures, you can make a new mod, and make your mod depend on it.

**Comment by RobertZenz** [comment]
I'd like to extend this feature request to support arbitrary sub-directories for textures/models/sounds etc..

That would allow mod and game makers to split up these, quite big, directories into a meaningful structure. It isn't always feasible to split a mod into further smaller mods, may it be technically or because of aesthetics.

**Comment by paramat** [comment]
PR #6412

**Comment by paramat** [comment]
#6412 merged.
RobertZenz please open a new issue if you are still active here.
