### ISSUE TITLE
Ability to launch singleplayer game from command line removed

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#2959]
d6cc0d8223b6d1366eafef22fd0fa9541c0f06ec

**Comment by rubenwardy** [comment]
@Zeno-

**Comment by rubenwardy** [comment]
This was how it was done before: https://github.com/minetest/minetest/commit/d6cc0d8223b6d1366eafef22fd0fa9541c0f06ec#diff-7ec3c68a81efff79b6ca22ac1f1eabbaL1340

**Comment by Zeno-** [comment]
@rubenwardy confirmed

**Comment by Zeno-** [comment]
@rubenwardy I've changed to unconfirmed bug because the behavior seems the same as prior to the refactoring

**Comment by est31** [comment]
Note: right now `minetest --worldname name --address '' --go` is working.

**Comment by rubenwardy** [comment]
That's rather unintuitive as a command.

I used git blame to look for the bug, and read the diff - git bisect takes
ages and never works for me. It was sapier that added this feature at my
request. Sorry for blaming that commit if it's not the cause.

**Comment by Zeno-** [comment]
It's not intuitive at all, I agree. But it's the incorrect commit.

I don't find any of the "implied" command lines intuitive because there are implications on top of implications... I vaguely recall "fixing" the behaviour you mention and had to "fix" it back because it was not was expected.

Maybe the best way to progress from here is to supply a full command line and a description of how you expect that command line (and options) to behave. 

IMO the command line options (and the implied things especially) need review because they're quite confusing at the moment. 

See also: IRC log from today

**Comment by rubenwardy** [comment]
I've read the logs. (I always read the #minetest-dev logs to keep up/catch
up)

    minetest --worldname name  --go

The above has never worked afaik, but it's how I'd like it to work.
It used to work like this:

    minetest --worldname name --name tester --go

-----

Also the following command:

minetestserver --worldname myworld --gameid minetest --port 30000

Doesn't create `myworld` if it doesn't exist, but creates `world` instead
(it's a hardcoded fallback).

Other things that would be nice:

* create world
* install mod
* uninstall mod
* ability to set settings from the command line
    * all options are just minetest.conf settings that don't get saved in
the end.

**Comment by rubenwardy** [comment]
GitHub is being a stupid pain in the ass, please just click the hidden part above.

**Comment by rubenwardy** [comment]
I thought it was that commit due to this section:

```
-	std::string address = g_settings->get("address ");
-	if (commanded_world != "")
-		address = "";
```

**Comment by Zeno-** [comment]
Yeah, it's not quite that simple :-(

**Comment by rubenwardy** [comment]
https://github.com/rubenwardy/NodeBoxEditor/commit/6ffa94e844e3870b88cba751a0124c4b7d686ac1

**Comment by rubenwardy** [comment]
Another issue should be created on the subject of command line ease-of-use and consistancy.
