### ISSUE TITLE
Add set_player_velocity method

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2960]
This is a follow-up issue of #1176.
I want to have a method for players to set the player's velocity: `set_player_velocity`.

---

Notifications:
@Elinvention (fixed #1176)

**Comment by est31** [comment]
The problem is that the velocity returned by get_player_velocity isn't accurate in no way, its invented by the client, whether its right is in total control of the client.

**Comment by tenplus1** [comment]
Simply being able to set player velocity would be enough to handle things like knock-back from mob hits and tnt blasts...  Getting player velocity is another story...

**Comment by est31** [comment]
knock-back is prominent enough I think to be made an extra engine feature. e.g. `apply_player_knockback(intensity, length, custom_flags)`.

**Comment by nerzhul** [comment]
@tenplus1 is right, modify playervelocity is good thing when player is stun, or slowed by an ability

**Comment by Wuzzy2** [comment]
Possible use cases:
* A tool which pushes the player in some direction, enabling stuff like extra jumps and other fun stuff
* Brake: One-time use item to reduce the speed of the player (i.e. to avoid/reduce potential fall damage)
* Knockback (if not implemented elsewhere already)
* Setting the player velocity after leaving a moving vehicle, i.e. boat, flying carpet, … (would always default to 0 speed as of 0.4.12).

**Comment by Elinvention** [comment]
Well it's broken if you use a modified client, if you want to cheat. A modified client that reports to the server a constant speed? I think we can always add some checks to anticheat.
If you want I can add `set_player_velocity` (I see a setSpeed in player.h) but of course it will be "broken" just like `get_player_velocity`.

**Comment by est31** [comment]
We can have this when we get clientside scripting.

**Comment by Wuzzy2** [comment]
I don't get it. Why should the client be allowed to set the speed at all? I never asked for this.

Isn't it possible for the server to “force” (server-side) a certain speed of the player?

**Comment by asl97** [comment]
isn't this kind of idea broken by design?

server handle logic
____
if the server logically force the speed, a modified client can just ignore it + any attempt at resetting pos.

it most likely wouldn't work all that great with anti cheat even if the client isn't modified.

1. lets say server set the speed to be lower
2. network lag happen and client receive the message late and reduce the speed to late
3. client move further than the server expected
4. server reset client pos
5. ???
6. people complain about reset with anti cheat enable

____
client handle logic
____

server side anti cheat wouldn't be effective (false positive == complain), client side anti cheat could be remove.

**Comment by Wuzzy2** [comment]
Oh, this doesn't sound good.
It still seems like a hole in the Lua API to me, because apparently it is perfectly okay to set the velocity of objects, but player objects seem to be the exception. :-/

**Comment by est31** [comment]
And object behaviour right now is pure shit. It isn't a place we should draw inspiration from.

**Comment by pgimeno** [comment]
More uses:
- Conveyor belts / treadmills / escalators
- Water currents

Anti-cheat is not necessary. There can even be an option in the client to disable speed changes. It's an effect that adds realism.

**Comment by Ferk** [comment]
Isn't there already a customizable gravity value that sets acceleration on the player?

Imho, there should be a `set_acceleration` / `get_acceleration` with a `{x=0,y=-9.8,z=0}` default value that can be used to customize the direction of this per-player gravity.

This way you could have crazy worlds where the gravity might be in a different direction, or use short bursts of acceleration changes (something like #1489 would be nice) for various effects.

**Comment by pgimeno** [comment]
Being able to set a constant acceleration is not enough. An inertial velocity state can't be obtained with acceleration alone, without constant corrections, which are infeasible server-side and resource-consuming client-side.

Thinking more about it, this would need having:

- a node type that sets and keeps the player's velocity to a constant while the player is on it (e.g. conveyor belts)
- another similar node type that does the same when penetrated (and a way to resolve conflicts, because a player can penetrate more than one node at once) (e.g. water current)
- a function that sets the client-side player's velocity to a certain value non-permanently, possibly in relation to its current velocity (e.g. stepping off a moving vehicle, being pushed back by a mob)

All three can be implemented without any client-side scripting. Player keys would affect the velocity, so for example you can climb an escalator the wrong way and stay steady if the velocities match.

**Comment by sofar** [comment]
After scratching my head for over a month why I can't figure out how to make a TNT blast push a player back... I find this bug.

Yes, this is a bug IMO

**Comment by o-jasper** [comment]
Prefer "all objects equal". `apply_force`/`apply_acceleration` could add to current acceleration? It'd also *not* require the user to add manually to the players speed.(and get the timestep right, etcetera)

I dunno how this whole server-client stuff works, as i understand it, the server essentially does everything and tells the client? (If i were starting from scratch, which i am not, i'd try go for a synchronized-simulation with merkle-like structures to figure what to send. I am more likely do do this ["for lua generally"](https://github.com/o-jasper/alt_require.lua) than this though, shameless plug)

**Comment by o-jasper** [comment]
Feel a lot of things, like jetpack, hoverboard etcetera would be doable.

**Comment by HybridDog** [comment]
>Feel a lot of things, like jetpack, hoverboard etcetera would be doable.

They're already doable by attaching, see the boats mod.
But you can't use a gatling gun to fly around by shooting down.

**Comment by o-jasper** [comment]
Yeah, everyone knows you need duct-tape for *that*.

**Comment by o-jasper** [comment]
Cool, can mess around with the jetpack code i have.. Also solves the issue how to make it show someone has it on. 

Seems like i have to write some code myself to detect things that might be collided with, and have to add friction, gravity myself, fall-damage myself. Thought some of the baseline stuff would be enforced. (it is fine really.. there a lib for that?)  (btw: don't have nice models.. Also searched a bit for jetpacks, haven't found any yet)

Perhaps nodes could have a "on_touched(by_obj)", if it runs last, nodes could implement friction themselves.

**Comment by raymoo** [comment]
It could help to have a "forces" system, where a player has one or more forces applied to them, each of which has an acceleration which may change from step to step. For example, an air resistance force could be used to implement the current tendency of a player to slow down when not actively trying to move. This would work naturally with something like a conveyor belt, because you just have to set a constant acceleration and the player would speed up to the point that the acceleration equals air resistance.

**Comment by o-jasper** [comment]
[Got some half-done code for jetpack](https://github.com/o-jasper/minetest-jetpack), also normals and force from that.. (essentually just dumping link..)

**Comment by paramat** [comment]
Any more comments? We now have CSM.

> We can have this when we get clientside scripting. Not before.

@red-001 @nerzhul
