### ISSUE TITLE
Feature request: Implement dividing entire stack evenly into inventory slots when you left click and drag

### ISSUE THREAD

**Issue by sloantothebone** [minetest/minetest#2963]
Minecraft has this.

**Comment by asl97** [comment]
minetest does too,  but it's tricky to use.

**Comment by yo-we** [comment]
middle click (place 10 items from stack)
  and
right click (separate stack in two even portions)
  work perfectly for me. Could you please explain?
--> I am using Minetest-0.4.12 and MT-0.4.12 "nearly dev" on Windows and Linux PCs.

**Comment by sloantothebone** [comment]
Try right clicking and dragging, like the 'how to reproduce issue' tells
you to. And if that works ok, great, you're using 0.4.12 and I'm using the
daily release.

**Comment by paramat** [comment]
Quite complex, as the number per slot is constantly updated depending on how many slots you have passed over.
Low priority and we are not Mojang.
Anyone interested in coding this? If not closing in 1 month.

**Comment by paramat** [comment]
Old issue and no support, low priority.
:-1: Rather specialised.

>  Minecraft has this.

his means nothing, you need to give a good reason for the feature.

**Comment by asl97** [comment]
@paramat The only reason for this is to make it easier to craft item requiring stacks that isn't a 'power of two'<sup>1</sup> with just one stack of item.

If we want to create sandstone from sand, the current system isn't so troublesome.
<details>
  <summary>Click to expand graph</summary>

Let's say we have enough for three sandstone (3 * 4 = 12)

<table>
<tr><td>12 sand</td></tr>
</table>

Right click select half split
<table>
<tr><td>6 sand</td></tr>
<tr><td>6 sand</td></tr>
</table>

Right click select half split again
<table>
<tr><td>3 sand</td><td>3 sand</td></tr>
<tr><td>3 sand</td><td>3 sand</td></tr>
</table>

Simple enough
</details>

____
However stuff like books, stairs, doors, buckets aren't as simple, there simply no quick simple way to equally split them.
<details>
  <summary>Books</summary>

<table>
<tr><td>9 paper</td></tr>
</table>

Right click select half split
<table>
<tr><td>4 paper</td></tr>
<tr><td>5 paper</td></tr>
</table>

Right click select half split again
<table>
<tr><td>4 paper</td></tr>
<tr><td>3 paper</td></tr>
<tr><td>2 paper</td></tr>
</table>
</details>

<details>
  <summary>Stair</summary>

<table>
<tr><td>18 wood</td></tr>
</table>

Right click select half split
<table>
<tr><td>9 wood</td></tr>
<tr><td>9 wood</td></tr>
</table>


Right click select half split again
<table>
<tr><td></td><td>4 wood</td></tr>
<tr><td>5 wood</td><td>4 wood</td></tr>
<tr><td></td><td>5 wood</td></tr>
</table>

Right click select half split again
<table>
<tr><td></td><td></td><td>4 wood</td></tr>
<tr><td></td><td>3 wood</td><td>4 wood</td></tr>
<tr><td>2 wood</td><td>2 wood</td><td>3 wood</td></tr>
</table>
</details>

<details>
  <summary>Doors</summary>

<table>
<tr><td>18 wood</td></tr>
</table>

Right click select half split
<table>
<tr><td>9 wood</td><td>9 wood</td></tr>
</table>


Right click select half split again
<table>
<tr><td>4 wood</td><td>4 wood</td></tr>
<tr><td>5 wood</td><td>5 wood</td></tr>
</table>

Right click select half split again
<table>
<tr><td>4 wood</td><td>4 wood</td></tr>
<tr><td>3 wood</td><td>3 wood</td></tr>
<tr><td>2 wood</td><td>2 wood</td></tr>
</table>
</details>

<details>
  <summary>Buckets</summary>

<table>
<tr><td>9 ingot</td></tr>
</table>

Right click select half split
<table>
<tr><td>4 ingot</td><td></td></tr>
<tr><td></td><td>5 ingot</td></tr>
</table>


Right click select half split again
<table>
<tr><td>4 ingot</td><td></td><td>2 ingot</td></tr>
<tr><td></td><td>3 ingot</td><td></td></tr>
</table>
</details>

Not to mention the blocks made from 9 item stacks as well as third party mods like technic cables, mix ingots, motors, transformers etc etc.

____
<details>
  <summary>There is the split into 3 stack equally using the multi-split method but it's troublesome too</summary>

Credit to https://www.youtube.com/watch?v=pdlA6oFNBBw

<table>
<tr><td>99</td></tr>
</table>

Right click select half split
<table>
<tr><td>50</td><td>49</td></tr>
</table>

Right click select half split again
<table>
<tr><td>25</td><td>74</td></tr>
</table>

Right click select half split again
<table>
<tr><td>62</td><td>37</td></tr>
</table>

Right click select half split again
<table>
<tr><td>31</td><td>68</td></tr>
</table>

Right click select half split again
<table>
<tr><td>65</td><td>34</td></tr>
</table>

Right click select half split again
<table>
<tr><td>32</td><td>67</td></tr>
</table>

Right click select half split again
<table>
<tr><td>66</td><td>33</td></tr>
</table>

Right click select half split again
<table>
<tr><td>33</td><td>33</td><td>33</td></tr>
</table>
</details>

____
All those require over half of a dozen of clicks can be simplified into just a few clicks and drag.

The basic idea itself isn't so complex.

item logic:
```
floor(item number / split) = number that goes in each stack
item number % split = left over to remain on cursor
```
update logic:
```
force replace all slot in list with number that goes in each stack and update selected item count
```
return after update logic to prevent default item moving handler<sup>2</sup> from running

flow logic:
We create a new array/list when [selecting item](https://github.com/minetest/minetest/blob/1b3e4e1/src/guiFormSpecMenu.cpp#L3440)
On [left mouse down after selected item](https://github.com/minetest/minetest/blob/1b3e4e1/src/guiFormSpecMenu.cpp#L3463)
We create a copy of selected item if required<sup>3</sup>, add the index s into the list and trigger an update
When the [mouse move](https://github.com/minetest/minetest/blob/1b3e4e1/src/guiFormSpecMenu.cpp#L3507)
We add the index s to the list if it is valid and trigger an update
When the [mouse is released](https://github.com/minetest/minetest/blob/1b3e4e1/src/guiFormSpecMenu.cpp#L3484)
We finalize the inventory state (empty the list so when the player drag it again, it wouldn't redistribute the stack).
____
1. stack of 2, 4, 8, etc etc.
2. all code under [line 3529](https://github.com/minetest/minetest/blob/1b3e4e1/src/guiFormSpecMenu.cpp#L3529)
3. for the update process since we will be overriding selected item count.
