### ISSUE TITLE
right click and drag inventory bug

### ISSUE THREAD

**Issue by sloantothebone** [minetest/minetest#2964]
When you right click and drag a stack on the inventory spreads 1 item per slot into the inventory. But when I click and drag, it doesn't work unless I do it again. It alternates working and not working.
How to reproduce the issue:
1. Start a new world, doesn't matter which game
2. Gather up a stack of 10 or 20 items.
3. Try dragging them across the inventory several times.

**Comment by est31** [comment]
confirmed.

**Comment by est31** [comment]
@Zeno- is that a bug, or actually a feature?

**Comment by PilzAdam** [comment]
When the feature was added items where always placed when dragging, but people complained because apparently they used drag and drop with the right mouse button to move half a stack of items. In order to fix the behavior was changed: one was required to grab the item, release the left mouse button, press the right mouse button and when pressing again it will start placing them into the slots you move your mouse over.

This "fix" is ridiculous. For example, if you want to fill the whole crafting grid, you'd need to place one item with a click&release before you can place the other 8 items by holding the button.
A proper behavior would be to "activate" the place on hover function after the first mouse button is released after picking up the stack. This way, you would be able to grab a stack and instantly be able to fill all the slots you like. Also these weird people that use drag and drop to move their whole stacks around won't notice any change, because they don't release any button after picking up the stack.

**Comment by sloantothebone** [comment]
Maybe there should be an easy to use lua API to define this, or an option in the settings to choose several different ways of how this works so people can decide which they like the best.

**Comment by Zeno-** [comment]
The "fix" wasn't a fix, but more of a revert to previous behaviour. At the time I seem to recall supporting the idea of a modifier key (like holding down ALT or something) to evoke the autodropping, but for some reason that was not liked.

**Comment by sloantothebone** [comment]
Is it going to be fixed?

**Comment by sloanonlinux** [comment]
Ok I believe the code for dragging is at  src/guiFormSpecMenu.cpp.

**Comment by Zeno-** [comment]
The code is +/- line 3352

```
			// Keep count of how many times right mouse button has been
			// clicked. One click is drag without dropping. Click + release
			// + click changes to drop one item when moved mode
```

**Comment by DonBatman** [comment]
I wouldn't mind it if shift was used.

**Comment by sloanonlinux** [comment]
I propose a solution of putting a checkbox next to the crafting that says autodrop.

**Comment by ForbiddenJ** [comment]
Hey guys. Same happens to me whether I use unified_inventory or minetest_game's builtin one. It bugged to the point where I individually place items unless I'm trying to fill more than a few slots near each other. Having shift for turning on autodrop would be nice.
