### ISSUE TITLE
Error when changing a world's game.

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#3005]
A fatal error occurs when changing a world's game by editing world.mt, and then starting the world from the Server tab.

18:53:26: ERROR[main]: MAINMENU ERROR: /usr/share/minetest/builtin/mainmenu/tab_server.lua:120: attempt to index local 'game' (a nil value)
18:53:26: ERROR[main]: stack traceback:
18:53:26: ERROR[main]:  /usr/share/minetest/builtin/mainmenu/tab_server.lua:120: in function 'handle_buttons'
18:53:26: ERROR[main]:  /usr/share/minetest/builtin/fstk/ui.lua:118: in function 'handle_buttons'
18:53:26: ERROR[main]:  /usr/share/minetest/builtin/fstk/ui.lua:155: in function </usr/share/minetest/builtin/fstk/ui.lua:148>

**Comment by kilbith** [comment]
It only happens if the subgame's name don't exist. Be more careful.

By the way, please mention that you're using [0.4.12-stable](https://github.com/minetest/minetest/blob/stable-0.4/builtin/mainmenu/tab_server.lua#L120) and not [current HEAD](https://github.com/minetest/minetest/blob/master/builtin/mainmenu/tab_server.lua#L120).

**Comment by nanepiwo** [comment]
I checked, and it work now. The error should be more informative though.

**Comment by rubenwardy** [comment]
@nanepiwo, it has been fixed.

**Comment by nanepiwo** [comment]
OK, closing.
