### ISSUE TITLE
Fully integrate minimap with Hud interface

### ISSUE THREAD

**Issue by kwolekr** [minetest/minetest#3051]
As a modder, I want the ability to move, modify attributes of, and enable/disable the minimap as with any other Hud item.
As a developer, I want the Minimap to be integrated with Hud for flexibility and consistency with other items drawn on the screen.
# Acceptance Criteria:
- Minimap drawing is performed in the Hud interface instead of directly in Game
- Mod writers can use any of the standard Hud lua APIs to modify attributes of the Minimap.  At least the following attributes must be modifiable: visibility, screen position, size, mode

**Comment by est31** [comment]
I agree, visibility and screen position are good candidates for hud to set. This is what its meant for.

The mode is a higher level property, than the hud api. Wielditem changes aren't tracked by hud either, or if you lose hp.

If we make the mode settable by the server, we should also let the server send a flag to "freeze" a mode, so that the client can't change it. Also we should make the server be abled to specify the modes.

I'm ok with sending the "freeze_mode" flag (or "disallow_client_to_switch_modes" if you want to call it that way) or the actual selected mode, via the hud mechanisms, not because hud is a place for it, but to spare additional packets.

Also, we should have two set_minimap_mode HUD_CHANGE messages, one where you only specify a value that the user can reach from their keystrokes (from the predefined mode list), and one where the whole mode definition is sent.

A mode definition should include:

* render mode: "radar", "surface"
* shape: "square", "round", or "custom"
* in case of "custom", the actual names of the textures (overlay and mask)
* zoom
* resolution (the hud level resolution is only how its displayed, not how its actually created)
* whether to display other players (also what to do if the alpha of their nametag is set to maximum)
* whether to display a player marker
* whether to rotate the minimap with the player, or whether to keep it solid

**Comment by BlockMen** [comment]
Should be done before next release IMO.
@RealBadAngel *bump*

**Comment by est31** [comment]
@RealBadAngel if its okay for you, I would like to implement it.

**Comment by RealBadAngel** [comment]
sure thing

**Comment by Wuzzy2** [comment]
As a modder, I welcome more freedom to modify the minimap even more very much, especially when it will be possibly to separately enable/disable the radar and minimap.

Similar issue: https://github.com/minetest/minetest/issues/4378

**Comment by paramat** [comment]
2 separate HUD flags now enable surface mode and radar mode, so that radar mode can be more expensive to 'earn' in survival mode.

**Comment by Wuzzy2** [comment]
The task has been completed now. You can close this.

**Comment by pyrollo** [comment]
Commit 81c66d6efb9fb0ab8a03b40e2bc22aa49eff9a04 solves this issue.
