### ISSUE TITLE
Texture name organization

### ISSUE THREAD

**Issue by ShadowNinja** [minetest/minetest#3180]
(From my understanding) texture names are currently just stashed into a global namespace, where everything from the stone texture to sepcial textures generated at runtime by the engine are stored.
This has resulted in some collision-avoidance techniques such as having every mod prefix their textures with their modname and an underscore.  However, this is a rather ugly solution.

I propose that a sort of VFS is used for texture names, eg: `tiles = {"/mod/default/stone.png"}`.  For compatibility the mod's "current directory" for this VFS should be `/mod/<mod_name>/` (so `"default_stone.png"` -> `"/mod/default/default_stone.png"` which would eventually be updated to remove the extra mod name).  The "root" folder could contain folders like `mod` and `core`.

Texture packs should organize themselves in a way similar to the VFS too, although I'm not sure what would be the best way to do this compatibly (or it could just be temporarily breaking).

This could go along with #2821.

**Comment by RobertZenz** [comment]
Are you talking about how the mods organize textures or how the engine organizes them?

**Comment by RobertZenz** [comment]
As far as I can see, that would remove the feature (yes, for me it is a feature) that mods can override arbitrary textures. Which is quite neat if you want to write an extension of something.

Once more, a very good solution to the "all textures munched in one directory" would be to support sub-directories in the texture directory. That would allow the mods to organize they're textures in a meaningful way, while other mods still have the possibility to override them. Texture packs would then need to mimic that structure, of course.

With that in place, your suggestion would also be possible because mods can simply stuff their textures into a sub-directory with the mod name.

**Comment by est31** [comment]
The current system is perfectly fine IMO, especially one is abled to override textures from other mods and to use textures from other mods. What you propose only removes the first feature, and has no real benefit.

There is no point in requiring mods to prefix "mod", and in replacing the underscore with slashes, beyond "change for change's sake".

The slashed directory system of unix is great if you have a state connected to it, and you have a PWD. Then one doesn't have to specify the full path, but relative from the PWD. There is more to that than just replacing underscores with slashes.

We could get some actual improvement if we add a feature that you don't have to write the (current) mod's name. E.g. we could make textures with a leading underscore resolve to the current modname, like `_stone.png` → `default_stone.png`, both on the disk and when referencing a texture by its name.

The only benefit of doing it with a `mod_name/texture_name.png` like approach would be that #2821 would be easier realizeable. However, we could realize #2821 also by just doing the following:

1. You can reference textures in mods either with `texture = {"default_stone.png"}`, or, if the texture lives in your own mod's namespace, with `texture = {"_stone.png"}`
1. If a texture file name on the disk doesn't start with an underscore, its an "absolute" texture, which you can use to reference textures from other mods. putting it into a subdirectory doesn't affect the way it is referenced.
1. If a texture file name on the disk starts with an underscore, its a "relative" texture, and its name is constructed with prefixing "modname_" and adding the subdirectories, just with a "_" separator instead of "/" like for unix or "\" like (in some places) for windows. E.g. you have stored a file named "_stone.png" inside the directory "mods/default/textures/ores/", then it can be referenced via "default_ores_stone.png" or, from inside the mod via "_ores_stone.png".

Using "_" instead of "/" would be OS independent.
I'm not sure what should be done with files like "mods/default/textures/_ores_stone.png", we could disallow _ useage if the file name starts with a _, or we could allow it to allow flexibility, and just say that behaviour is undefined if you both have "mods/default/textures/_ores_stone.png" and "mods/default/textures/ores/_stone.png".

**Comment by PilzAdam** [comment]
I agree with @ShadowNinja that the current system could be changed, but I don't like your suggestion. It would break mods which are currently using the textures of other mods.

The new system should help structure texture packs and still allow it that mods can override any textures, while being backwards compatible.

**Comment by tenplus1** [comment]
The current texture naming works fine and allows for mods to override where available...  Personally I would keep it as is...

**Comment by cheapie** [comment]
I really don't see why it matters if it's default/stone.png or default_stone.png. The latter works, so there doesn't seem to be any real reason to change it.

**Comment by celeron55** [comment]
Uh... why?

Also, prefixing the name is not any lesser of a "collision-avoidance technique" than having a rigid structure like what you propose. This is almost purely change for the sake of change.

If this is to just ease the amount of textures per directory, then why not just define that putting textures in a subdirectory "foo" means the same thing as prefixing the texture with "foo_", and implement this in the engine?

**Comment by paramat** [comment]
:-1: 
Disapproved.
