### ISSUE TITLE
LocalAnimations are not really locale

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#3193]
Hi @est31 , it's for you :p
Today i worked on Player class to look at the different usages and i noticed that local animations are also present server side... for nothing.

Here is a commit example to refactor this:

http://gitlab.unix-experience.fr/epixel/epixel/commit/60424a393d4d4f8112b5f26a554e679f159c46d9

Did you agree with backporting it into minetest ?

**Comment by est31** [comment]
@nerzhul from what I see, we need to store the LocalAnimations on the server as well in order to be able to give it to lua via the `get_local_animation` callback? It makes only sense to remove it from the server if you remove that callback, like you did in your commit. But the question is, why should that callback be removed?

**Comment by nerzhul** [comment]
This callback is simply never call. Nowhere.

**Comment by RobertZenz** [comment]
@nerzhul But it is API currently, no? So it might be needed at some point in the future of is already used by some mod.

**Comment by est31** [comment]
It is a lua API callback, written for and to be used by mods.
