### ISSUE TITLE
Redesigning the settings tab

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#3254]
We need to redesign that tab to free up some space, add new GUI options (like any good user-friendly menu) and order the options in their respective categories.

Here's what I propose vaguely : 
- Setting categories on the left as a textlist.
- It may have sub-categories inside of categories (particularly for graphics stuff).
- Some things like the shaders could be synthesized with a Low-Medium-High ranking for simplicity.

![menu](https://cloud.githubusercontent.com/assets/7883281/10517596/b89eeaa6-735d-11e5-958e-d596d9546dc5.png)

I'm requesting any feedback to find out what should be included (or not) in the new menu.

**Comment by PilzAdam** [comment]
It should automatically parse minetest.conf.example, the default settings or a new special markup file to always show all possible options.

I'd personally prefer the special markup file:
```
[Graphics]
# Description for fov
#name type default min max
fov   int  72      30  160
# Description for font_path
font_path path fonts/liberationsans.ttf

# Possible types: int, float, path, string, enum (with all possible values explicitly listed), struct (with named and typed members; e.g. for noise params), list
```

**Comment by kilbith** [comment]
@PilzAdam We can't impose one formspec element per value type (e.g. the int value of vrange is better tweaked with a scrollbar, but the FSAA one is better with a dropdown).

Also that markup does not envisage a subtle placing on the menu.

**Comment by est31** [comment]
If we have one such file, it should be automatically generated. Then we can also generate minetest.conf.example from it, and only have one single place to add/remove settings.

**Comment by PilzAdam** [comment]
Some work on it: https://github.com/PilzAdam/minetest/commits/lua_settings
This already works, but it doesn't have any type dependent edit dialog yet.

@est31 see the branch above; at the end of tab_settings.lua there is `createMinetestConfExample()`. `settings.txt` can't be created by e.g. `defaultsettings.cpp`, since it contains more information. Maybe we can generate `defaultsettings.cpp`?

**Comment by kilbith** [comment]
Quick testing of @PilzAdam implementation... This is KISS and flexible, but maybe too technical-looking yet compared to regular names (without _), and other formspec elements. The category titles should be colored too.

Certainly a good start anyhow, PR incoming ?

**Comment by est31** [comment]
I think it needs categories and perhaps non-technical names that can be translated using fgettext. For this we probably need to figure out how to do make xgettext detect it.

**Comment by RHRhino** [comment]
I always wondered why the window is so small instead of full screen. It's quite a long list to scroll. Is there maybe a setting to make the window full screen? (I mean the menu window not the minetest window) Or could we split up the setting into catagories like it's done in the ingame menu?

**Comment by PilzAdam** [comment]
@kilbith @est31 Updated the branch. Changes:
* Added support for readable names (in brackets behind the setting name in settings.txt)
* Added a checkbox to switch between "technical" and readable names
* Added support for gettext (button names, comments, readable names)
* Added dropdown for boolean edit dialog as a proof of concept
* Moved settings.txt to builtin to be platform independent
* Colored categories
* Added `createTranslationFile()` which creates a string with a bunch of fake gettext() calls with all readable names and comments of the settings; this way xgettext can detect them.

Note that `settings.txt` is currently a mockup and someone should create a better version of it.

**Comment by PilzAdam** [comment]
Added support for enums. Sadly the values can't be translated, so they need to be explained in the comments.

What is still missing:
* The `path` type; maybe we can even open a file browser in the mainmenu.
* The `mapgen_flags` for mapgen flags; a list of checkboxes would be cool here.
* The `noise_params` type; since they are always the same structure I think they deserve a special treatment in the GUI.
* Fancy input for `float`  and `int`; if max and min are specified then use a slider, else use a input field with input validation.
* The engine support arbitrary structs in the settings, but there is none that uses this (except noise params, but the get a special treatment); this is low priority.
* Maybe a fancier GUI.

I think that the current version is good enough, though, if we just use `string` for all these types. Can someone please come up with an up-to-date and fancy `settings.txt` now? IMO it would be mergeable then and the stuff listed above can be done later.

**Comment by kilbith** [comment]
OK it's getting better... I can attempt a fancier/up-to-date `settings.txt` if noone beats me.

![capture d ecran de 2015-10-16 17-04-38](https://cloud.githubusercontent.com/assets/7883281/10545278/2bd77892-7428-11e5-99a3-999c02ab2daf.png)

**Comment by kilbith** [comment]
@PilzAdam Some work on `settings.txt` : http://paste.ubuntu.com/12798255/
I've fixed some typos, style, missing readable names and descriptions, and german-specific spelling (all-in-one wording).

Questions : the keymapping has been omitted intentionally ? Did I missed something ?

**Comment by PilzAdam** [comment]
@kilbith my mockup was loosely based on minetest.conf.example, which has a horrible structure. Maybe it would be better if you would write it from scratch, based on defaultsettings.cpp.

For the keys settings: Add them to settings.txt so they get added into the automatically generated minetest.conf.example, but I'll ignore them in the GUI and add a button to bring up the old key change menu.

**Comment by kilbith** [comment]
OK added the keymapping with the `key` type + a few polishing : http://paste.ubuntu.com/12798640/

I think it's straightforward enough to not need a rewrite from scratch (too much work anyways). And we're already accustomed to this structure.

**Comment by PilzAdam** [comment]
#3258

**Comment by kilbith** [comment]
Victory : https://github.com/minetest/minetest/commit/006ef5b4a5e362eed848ca26b411a8059d74b965
