### ISSUE TITLE
Links to documentation within example.conf? 

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#3285]
Many descriptions are very technical in minetest.example.conf. 

If we explain them all in the comments that might be too much and duplicates the work when the documentation has to be changed. 

Do you thing it would make sense to add a wiki link like this?

```
#    Maximum number of forceloaded blocks.
#    http://dev.minetest.net/minetest.forceload_block
#    type: int
# max_forceloaded_blocks = 16
```

**Comment by est31** [comment]
If we want to have such links, we shouldn't have to manually specify them in settingtypes.txt, rather go with automatically generated urls like `http://wiki.minetest.net/setting:setting_name#version-0-4-13` or so.
Also, I'd only link to the normal wiki. The dev wiki is for mod, game and engine devs, not for users.

**Comment by PilzAdam** [comment]
If you want to do this then there should be a way to click links in the settings menu.

**Comment by paramat** [comment]
Problem is the wiki is almost always very out of date (it's also much less accessible to a dev making changes to code), so this would confuse more than help, also it would bloat the .conf file.
A simple text file added to the repo is a better idea for explanation of conf.example, changes to this can then be included in a dev's PR, instead of separately accessing and editing the wiki (devs would find this irritating and too time consuming to do and will not bother).

**Comment by ObaniGemini** [comment]
Maybe could you do as teeworlds organization and create minetest-documentation repository on GitHub ?
It would be less instinctive for simple users, but would enable cooperative work on documentation, and would enable the usage of .md text files.

**Comment by paramat** [comment]
I think this should be closed, i doubt we want to do all this work for links to an always-outdated and therefore unhelpful wiki.
