### ISSUE TITLE
License location not obvious

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#3342]
The Readme does have a notice that the code is covered by LGPL, but it is not very clear where to find it. Wouldn't it be better to move the license to the root of the source tree, name it one of the more standard LICENSE/COPYING, or at least mention where it is in the readme?

**Comment by PilzAdam** [comment]
It clearly states where you can get it if you are unable to find it in our tree.

**Comment by rubenwardy** [comment]
I agree, you have to scroll down quite a bit.

**Comment by Calinou** [comment]
Please reopen this; https://github.com/minetest/minetest/blob/master/doc/lgpl-2.1.txt should be put at the root of the directory as `LICENSE.txt`.

**Comment by rubenwardy** [comment]
I agree with Calinou. It's what the license says you should do.

**Comment by est31** [comment]
@rubenwardy I can't see this stated anywhere. lgpl-2.1.txt is provided as it seems only for shipping a version of the license with the source code. Putting it into the root dir might make the job easier for scanners etc. but I don't think that's that a priority. It would be much more useful to move the detailed description of what is licensed under which license from `README.txt` into the `LICENSE.txt` or `LICENSE.md` file, to make it easier to be found.

However, @celeron55 has placed it into the README and I'd respect his descision, he is the most major copyright owner after all.

**Comment by celeron55** [comment]
I'm okay with moving stuff around, but I'm not okay with flooding the root directory with miscellanous stuff like this. Is it really so important?

Many projects have much more obscure license locations, especially as you can't even find their license on their websites. When I want to find out a license of a thing, I don't download the code. I go to the website and read it from there.

Our website isn't as CTRL+F friendly as I would like though because it doesn't state the word "license" anywhere; it just says "released under ...".
