### ISSUE TITLE
Minetestserver need a bunch of ram for players

### ISSUE THREAD

**Issue by verymilan** [minetest/minetest#3409]
Hi there, it seems like Minetest need alot of Ram for every player...is this a bug?
It going only to need more - if there less players, it will hold its memory usuage.
We are on the latest commit.

2Gig from this load are from SSDB we're using as Database Backend.
![muchmem](https://cloud.githubusercontent.com/assets/10698140/11457021/98a3123c-969d-11e5-9c85-96778b7283a8.png)

...this KVM has actually 4G RAM and 4G Swap.

**Comment by est31** [comment]
Which mods do you have? which game?

**Comment by est31** [comment]
What you describe is leaky behaviour.

**Comment by 0-afflatus** [comment]
You must be swapping out nearly all the time then?
I'm going to have to look at my memory usage.
How many players did you have on, and were they all exploring new territory?

**Comment by tchncs** [comment]
> Which mods do you have? which game?

Oh, [alot of extramods](http://illuna-minetest.tk/servermods/) and the game is the regular minetest_game with less customizations only in recipes or axespeed for example.

>  How many players did you have on, and were they all exploring new territory?

Im not sure about your first question, because the munin image in my first post.
Well, one player is [much exploring unter the earth with an autominer](https://media.tchncs.de/u/milan/m/minetest-autominer/)...

> You must be swapping out nearly all the time then?

Yes, the first action from the server is to put ssdb into the swap, then minetest follows some time after it.

**Comment by 0-afflatus** [comment]
> Im not sure about your first question, because the munin image in my first post.
Sorry, I didn't look at it closely enough. :-/

**Comment by DI3HARD139** [comment]
Thats kinda odd. I run over 104 mods and I see about 100-200MB per player on Ubuntu 14.04.2 Desktop x64.

**Comment by tchncs** [comment]
> Thats kinda odd.
Agreed. And it breaks my well sleep also.

Here some new screenshots.
The emty space was ... no joking... a full disk -.-' 
^im happy that noone felt it and there is nothing broken.
Looks like i have to check the munin settings for mail notes on warnings....

anyway:
![2015-12-02-233607_1920x1200_scrot](https://cloud.githubusercontent.com/assets/10698140/11573353/1d71d4f6-9a06-11e5-931c-d4c902232f1b.png)
![2015-12-03-213154_1920x1200_scrot](https://cloud.githubusercontent.com/assets/10698140/11573354/1d739dcc-9a06-11e5-8041-aaa3d5f90398.png)

The "cuts" are from restarts - yesterday i checked changed some code from tnt to let it only use by privileged players....and lava...will check that :P 

And i let restart the minetestserver now every morning on ~4oclock am.
But as you can see, it was damn heavy - there was not much players ... some activity, testing the new tnt, yes, but very less players.

**Comment by tchncs** [comment]
Today it was nearly no playeractivity.
The most work has some automatic pipeworks/mesecons system done (autocrafter for example).
Again im near seven Gig of memory usuage!

**Comment by tchncs** [comment]
Hello? Anyone here?

**Comment by DI3HARD139** [comment]
What's the OS and Minetest Build #? If the minetest build was compiled by you, were there any modifications to the build?

**Comment by tchncs** [comment]
Hi, i i not confuse something, i compiled with this command the latest time:

```
cmake . -DRUN_IN_PLACE=1 -DBUILD_SERVER=1 -DBUILD_CLIENT=0 -DENABLE_REDIS=1
-DREDIS_LIBRARY=/home/minetest/hiredis/libhiredis.so 
-DREDIS_INCLUDE_DIR=/home/minetest/hiredis 
-DENABLE_LUAJIT=1 -DLUA_INCLUDE_DIR=/home/minetest/luajit-2.0/src 
-DLUA_LIBRARY=/usr/local/lib/libluajit-5.1.so -DCMAKE_BUILD_TYPE=Release 
-DENABLE_SPATIAL=1 -DENABLE_GETTEXT=1
```

Its Debian sid on stable updates.

**Comment by nerzhul** [comment]
@tchncs warning redis can take a lot of ram too.
But yes there is a pseudo memleak, RemotePlayer objects aren't cleanup from memory at player leave, there is a re-use system, but generally this system is stupid and should be removed to cleanup properly player sessions

**Comment by tchncs** [comment]
>warning redis can take a lot of ram too. 

Yes, of course this was the first memproblem, so we switched to ssdb, which simulate an redis for minetest but stores as leveldb. The cool thing is, that this let us control the mem usuage.
Actually, because this issue here, ssdb is using max. 1G of memory.
Its a really cool backend and players talk about an performance improvement since we switched from redis :)

>But yes there is a pseudo memleak 

did you think that this happends because of players playing with mesecons and pipeworks?
On the other hand, its not the first time that players have fun with this mods on that server...it was never a problem before. The leak is since...maybe...one month?

**Comment by tchncs** [comment]
```sync && echo 3 | sudo tee /proc/sys/vm/drop_caches```

...does not work. 
Is there any other way to clean the memory of the minetest processes without restarting them?

**Comment by est31** [comment]
If there is a leak, there is no real way from the outside. @tchncs the best way to fix the issue is to e.g. start minetest in valgrind in leak check mode. Leak check then prints the leaked memory on application exit.

**Comment by tchncs** [comment]
Because it was magically away some time i did not more to debug this.
A few days ago i updated minetest minetest_game and some additional mods an bam! 
Its back. I was able to remove some intensity by doing a `make clean` and build again but slowly it needs more....and more....and more... memory.
Valgrind does not work:
```
 ERROR[Main]: /home/minetest/minetest/src/script/cpp_api/s_base.cpp:4e: ScriptApiBase::ScriptApiBase(): A fatal error occured: luaL_newstate() failed
```

It is a productionserver. I cannot play so much :(

**Comment by ShadowNinja** [comment]
@tchncs: The valgrind error is a known issue with LuaJIT.  Either use a LuaJIT build with valgrind support enabled, or use non-JIT Lua.
valgrind's default memcheck tool probably won't be very helpful BTW, try valgrind's massif tool.

**Comment by Zeno-** [comment]
@est31 actually, (valgrind) massif might be a useful tool to use as well as it can point to exactly *what* is using all the RAM

**Comment by rubenwardy** [comment]
If this can be reproduced, please bump
