### ISSUE TITLE
Add a command to toggle auto save of world

### ISSUE THREAD

**Issue by Elinvention** [minetest/minetest#3482]
When I still played Minecraft, there was a useful command /save-off to disable auto save. This way we could blow everything up and simply restart the server to bring everything back.

Of course we should inform all the players when such a command is given and perhaps some kind of visual notification that disappears when /save-on is given back. We could also add /save-all to force save of all data to disk and that would be useful in some cases when debugging odd engine bugs too.

If this is feasible with Minetest's many back-ends, I think it would be a nice addition.

**Comment by est31** [comment]
It is feasible. Just don't send any save commands.

To be honest, I see the fact that minetest auto saves as a great feature, you don't have to type ctrl+s in order to save your precious work from a computer crash. But I understand your usecase and would welcome it in the engine, as long as the default is to auto-save.

In order to fully disable auto-save, it should stop saving at least to the player files and the map (including the objects).
In fact, I can imagine stuff like @rubenwardy 's CTF subgame profit from this change. Also note that saving in map is sth that's easily exposed via the lua API.

**Comment by kaeza** [comment]
@Wuzzy2's tutorial world/game could also possibly benefit.

**Comment by C1ffisme** [comment]
This would have to come with a few warning labels, though. We don't want any noobish players trying out this command, and then building a life-sized replica of [Insert large, real-life building here].

Maybe this should be disabled unless in multiplayer? (You could still run it by going to the "server" tab in minetest and playing the game, this just adds a bit more of security.)

**Comment by rubenwardy** [comment]
CTF needs a persistent map for the duration of a match, so all edited blocks need to be loaded or saved.

> This would have to come with a few warning labels, though. We don't want any noobish players trying out this command, and then building a life-sized replica of [Insert large, real-life building here].
> Maybe this should be disabled unless in multiplayer? (You could still run it by going to the "server" tab in minetest and playing the game, this just adds a bit more of security.)

If the command is something like /disable_saving, then it's their fault for running it.

**Comment by C1ffisme** [comment]
Alright then, I won't stop you, but I'm just suggesting before someone posts this kind of thing to the forums as a bug report, or a review or something.

**Comment by rubenwardy** [comment]
A command like that is really self explanatory.

**Comment by est31** [comment]
I'd manage it as a setting, and expose it via the /set command. This is complicated enough to keep novice players out.

**Comment by C1ffisme** [comment]
@rubenwardy Most people would know not to touch it, but some people can be just that dumb. Sometimes people just don't get it, and then 'test it out' to see what it does. I would probably have done something with /deleteblocks if it had existed when I had first tried out Minetest in 0.4.1.

@est31 Probably the best idea. The /set command is advanced enough that people would start looking for documentation, before fiddling around.

**Comment by rubenwardy** [comment]
If you ran a command called "disable_saving" thinking that it wouldn't
disable saving, then you don't deserve support. Please keep your comments
sensible and think "does this actually help this issue thread, or is it
just useless noise?"

As for a setting, it would be annoying if it's not made per world.

**Comment by C1ffisme** [comment]
@rubenwardy I'm just saying this, because I can still remember being 10, 11 years old. At that time, I wanted to try things out. Maybe what I said may never happen, I can't predict the future, but most programs with a command like this do come with at least a confirmation dialogue.

As for "useless noise", it is possible to edit and delete my comments, so they cannot do any real harm, unless I were to create an amount of spam that would take a few hours to find all of and delete.

**Comment by Rogier-5** [comment]
> CTF needs a persistent map for the duration of a match, so all edited blocks need to be loaded or saved.

This sounds more like some kind of checkpoint support, with the ability to revert the state of the world to a previous checkpoint. That's probably also useful for a tutorial world. Disabling autosave would just be a special case.

> In order to fully disable auto-save, it should stop saving at least to the player files and the map (including the objects).

And mods would have to be prevented from writing status files (and other files) as well ? E.g. travelnet. I suppose this is not trivial in general...

Wouldn't copying the world directory and the database, and starting a new server provide all the support that is needed ? Such a feature might even be added to the GUI. Maybe it is even possible to switch directories while the server is running ? To avoid the need to duplicate the database, adding support for querying a second, read-only database if a block is not found in the primary, writable, database, could be added to minetest ?.

**Comment by Elinvention** [comment]
Mods that write to files themselves... Mods shouldn't do that, but use a minetest API as suggested in #3374. When that issue is solved, we could just return a different return status to mods that use the database API, warning them that auto save is disabled. We could also buffer all operations in ram (exactly the same as the map database) and then write them on disk only if the admin issue a /save-on or /save-all.

**Comment by est31** [comment]
Probably, yes.

**Comment by Warr1024** [comment]
One of the major use-cases for something like this, which I don't see discussed yet, is for server operators who want to make backups of the game world.  Since you can't guarantee atomicity and consistency while the server is running (your backup might end up with a partial write) I find that it's currently necessary to *shut down the entire world for the duration of the backup*.  Having a way to flush all current pending data to disk, and suspend all subsequent writes until resumed, while leaving the game running, would help mitigate this.

#3374 would certainly make it easier to ensure atomicity/consistency in backups, but having the ability to suspend world writes could help avoid performance problems caused by concurrent access to the back-end, such trying to get an exclusive lock to write to a sqlite db while the backup process holds a long-running shared lock to read it.

**Comment by rubenwardy** [comment]
Doesn't seem to be that much interest for how many difficulties this could cause

**Comment by lhofhansl** [comment]
I have found myself in need of something like this. I have a small change that simply allows querying a secondary database if a block is not found in the primary one. That way multiple scenarios are possible:
1. Both DBs are persistent. In that case one can have a base DB that won't be changed and all changes get saved into the normal DB.
2. The normal DB could use the dummy backend. In that case it's now possible to start from a base map always, have a normal game, but always go back to the beginning.

It's actually just about 10 lines of code.

@rubenwardy
