### ISSUE TITLE
Death message repeats until respawn

### ISSUE THREAD

**Issue by 4Evergreen4** [minetest/minetest#3565]
It seems that if the player doesn't respawn immediately after dying in fire or lava _(or any node that has a `damage_per_second` field)_.  The death message is triggered over and over again until they respawn or are out of the condition that caused them to die.  This doesn't appear to happen with drowning.

![Repeated death message](http://i.imgur.com/rjLMN0u.png)

You can see the repeated message in the top left corner _(though it is hard to see because of the lava)_.  It also appears that `register_on_dieplayer` is triggered until respawn as well.

**EDIT:** Found the offending commit using git bisect: c552d293fa340a1484d0b918b3341d7d141e7931

**Comment by veikk0** [comment]
I can confirm this. Tested with Minetest 0.4.13 and the latest minetest_game. This only happens when dying in lava or burning to death, not when drowning or falling.

I also noticed that once dead by burning or by lava and sitting on the respawn screen, the game keeps detecting that damage is being done to the player. After dying in lava this message keeps printing in the terminal: `ACTION[ServerThread]: singleplayer damaged by 8 hp at (15.94,1.5,-0.001)`. Same with dying in fire, except the damage done is 4 hp.

**Comment by ObaniGemini** [comment]
Yes this is still there and arrived with 0.4.13 I think

**Comment by wilkgr76** [comment]
Yes. Question: Since the respawn formspec is triggered, why do we still have this message?

**Comment by Fixer-007** [comment]
To inform player about death?

**Comment by wilkgr76** [comment]
@Fixer I thought the formspec did that?

**Comment by Fixer-007** [comment]
Hmm, I've seen such error spam myself, can confirm.

**Comment by jhcole** [comment]
I wrote a simple mod to limit on_dieplayer callbacks to once per death until this gets fixed. It seems to work.
https://github.com/FozLand/one_death

**Comment by Ekdohibs** [comment]
Can confirm this still happens.

**Comment by paramat** [comment]
Multiple death messages only happen for me in creative mode, where also in terminal i can see repeated 'player takes damage' messages.

**Comment by presstabstart** [comment]
I **think** I fixed it. Will send a PR shortly.
