### ISSUE TITLE
Secondary F2 Chat Mode

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#3618]
Chat is great in Minetest, but often it feels lacking compared to other text communication stuff, like IRC.

What I am proposing is that F2 feature a secondary mode (press twice to switch to) which persists the chat log onscreen so that one does not need to press F10 to see the log.

In addition, a key to toggle chat on-screen when depressed would be nice (a la +chat in other games).

**Comment by everamzah** [comment]
Further explanation/appeal:  One is unable to use the F10 console to display the chat log and the ESC Pause menu at the same time.  If displaying a persistent chat log on screen isn't possible, then perhaps an option to set PAUSE_MENU_FPS (?) if F10 console is dropped.

I use the ESC Pause menu a lot when I have Minetest client running in order to reduce framerate (personally set to 5), in order to reduce the amount of energy the computer consumes.

**Comment by paramat** [comment]
> What I am proposing is that F2 feature a secondary mode (press twice to switch to) which persists the chat log onscreen so that one does not need to press F10 to see the log.

Why not just use F10?

Your second comment is very low priority and there is an issue for F10 being visible over other menus already.
