### ISSUE TITLE
Enter key is sometimes registered twice in formspecs

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#3637]
For example, try setting minimal view range in advanced settings by going into it and typing 60 (as an example), after that press Enter on a keyboard. With this it will apply the value, go back to menu and go back into that settings again. So you can't exit via Enter, only by Esc.

**Comment by est31** [comment]
Confirmed. It works if you press the Enter key only a very short time. Still a bug IMO.

**Comment by ShadowNinja** [comment]
I've also noticed this when starting Minetest.  Sometimes when I hit enter to run the executable I hold the key long enough for Minetest to it and enter the game immediately.

**Comment by paramat** [comment]
@PilzAdam

**Comment by PilzAdam** [comment]
@paramat this is a general formspec issue; not limited to the settings menu.

**Comment by Rogier-5** [comment]
I did some investigation into this some time ago, and I got the impression that the bug is probably in irrlicht.

From what I remember:

What happens (presumably), is that the widget acts on the keypress event of the (enter) key, instead of waiting for the key-release event. This causes the window to be closed, and the window below then receives the key-release event (i.e. sees another 'enter') and acts on that...

In (even :-) more technical terms: when the enter-key event arrives, the widget probably does not check whether the key is *still* depressed (i.e. whether the event was just a keypress), or whether it is not (the key was pressed and released). If the key is still depressed, then the widget should ignore the event. Only if (or once) the key has been released should it be acted upon.

If the key was only hit very briefly, then the key-press event is also a key-release event: i.e. the 'still depressed' flag will indicate that the key is no longer depressed. If the keypress was slower, then there will be separate keypress ('still depressed') and key-release ('no longer depressed') events.

**Comment by paramat** [comment]
> Sometimes when I hit enter to run the executable I hold the key long enough for Minetest to register it and enter the game immediately.

Happens to me too.

**Comment by Rogier-5** [comment]
#4344 is probably caused by the same or a very similar irrlicht bug.

**Comment by rubenwardy** [comment]
Can't reproduce
