### ISSUE TITLE
Automatically fix mods if they break the mod naming convention.

### ISSUE THREAD

**Issue by Splizard** [minetest/minetest#3645]
This would make it a ton easier for new users to install mods, I have personally seen people installing mods who get frustrated when they have to name the folder in an exact specific way.

**Comment by rubenwardy** [comment]
Rather than renaming the dir automatically, mod.conf should be used.

**Comment by Splizard** [comment]
What about with old mods? Which don't have a mod.conf, in fact none of the mods I have contain a mod.conf file.. Is there a problem with renaming the folder?

**Comment by rubenwardy** [comment]
You misunderstand, I mean create a mod.conf

**Comment by rubenwardy** [comment]
Although that could be rather confusing.

**Comment by Splizard** [comment]
Oh I see what you mean :) yes that would work too

**Comment by ShadowNinja** [comment]
auto-fix was proposed in #1062, but dropped because the names are unpredictable and you can't figure out what it should be without running the mod and checking for what node definitions it creates.
`mod.conf` is the correct way to do this.

We could print a warning if the name isn't specified in `mod.conf`.  This would encourage mods to make use of `mod.conf`, preventing these issues.

**Comment by est31** [comment]
:+1: to @ShadowNinja 's proposal

**Comment by rubenwardy** [comment]
we have mod.conf now
