### ISSUE TITLE
Defaulting to Mapgen V7

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#3655]
Cc: @paramat 

Mapgen V6 has had its day. Feature-wise it is stuck in the past while Mapgen V7 is stable, more interesting and polished since more than a year.

I suggest to make Mapgen V7 the new default mapgen.

**Comment by tenplus1** [comment]
+1

**Comment by paramat** [comment]
Mgv7 terrain is fairly stable, the biome system is still being improved and i don't like the idea of freezing it and calling it 'stable'. So if mgv7 is made default it will be officially 'unstable' but with fairly stable terrain, the biomes may change slightly with time but the worst result would be some straight-edged biomes.

I'mnot sure if mgv7 is suitable for young children or newbies as it's large scale and searching for certain resources or biomes can require long journeys. But then we could make clear mgv6 is the option for an easier world.

Having mgv7 default would improve people's first reactions and game reviews for those people who jump straight into the default mapgen.

**Comment by MoNTE48** [comment]
I would like to see the option to increase or decrease the size of biomes.
for example
mgv7_biomes_size = 2
1 - small, 2 - default, 3 - big, 0 - 1 biome only

**Comment by C1ffisme** [comment]
@MoNTE48 I would also like to see that, since in my subgame, I can't seem to tweak biomes to make them a bit smaller.

I would also like the same feature, but to apply to caves, since in V6 caves appear very commonly, but in V7 they are infrequent. Big, but infrequent.

For example : 
v6 mapgen:
![screenshot_20160207_134109](https://cloud.githubusercontent.com/assets/9893266/12874767/9184cace-cda0-11e5-874c-77257d88b30d.png)
v7 mapgen:
![screenshot_20160207_134028](https://cloud.githubusercontent.com/assets/9893266/12874769/999c7bbc-cda0-11e5-9a89-45749da584d0.png)

@paramat The idea of travelling far is not a problem for MC, but they have portals and minecarts. Maybe if we get a decent mode of transport in the game, this could be fixed?

**Comment by paramat** [comment]
Size of biomes can be adjusted by changing the noise 'spread' values (750, 750, 750) in heat and humidity noises, make sure all 3 numbers are equal.
Caves can be tuned by adjusting cave noise 'scale', 'offset' and 'spread'.

**Comment by C1ffisme** [comment]
Note that I also found no lava in V7. Maybe add small springs on the sides of cave walls?

@paramat Hmm... My biomes don't seem to use the normal perlin noise arguments that decorations, etc. do. Lemme look into that a bit more...

**Comment by paramat** [comment]
Lava caves in mgv5/v7/flat/fractal start at y = -256

**Comment by C1ffisme** [comment]
Okay, I found one, though I do notice that the lava cave looks exactly like a v6 lava cave.

I'm all for it! :+1:

**Comment by paramat** [comment]
Yes the same large pseudorandom caves are used for most mapgens.

**Comment by C1ffisme** [comment]
@paramat Hmm... Maybe make the v7 lava caves be a bit bigger, just to fit the massiveness of everything else in v7 mapgen?

Also, I might add some little springs in the normal caves, just for a bit of variety. But just a suggestion ;).

**Comment by 0-afflatus** [comment]
:+1:

**Comment by celeron55** [comment]
http://irc.minetest.ru/minetest-dev/2016-03-22#i_4563823

In my opinion v7 is currently not a good general-purpose mapgen. It leaves out all small-scale detail and only focuses on large-scale terrain, and fails to be very interesting in that also. Defaulting to it would disappoint more players than sticking to v6 for now would.

Mapgens tend to be quite one trick ponies; v6 is the best that we currently have in the "jack of all trades" category. I hope it can be replaced some day with something that truly does its role better though.

**Comment by paramat** [comment]
Watching some let's play videos in mgv7, players often are a little intimidated by the size of the biomes, especially if they are in a grassland biome 1000 nodes across with no trees to punch. Mgv6 is friendlier for newbies but not as visually stunning as mgv7 (which has improved a lot over the last year).
As we're still fiddling with mgv7 and the biome system, and because we have shadows at y = 63 in all mapgens other than mgv6, i'm happy to stay with mgv6 for now.

**Comment by Fixer-007** [comment]
Yeah, shadow problems are annoying in those mapgens.

**Comment by paramat** [comment]
I'm not concerned with moretrees shadows, that's a problem with l-system generation which is not used in core mapgen.

celeron55 i somewhat disagree with your opinion of mgv7, what you write is similar to your opinion 3 years ago, it has changed somwhat since then, mountains are higher and i've added mgv6-type cliff terrain. Although certaonly it is larger scale, but i don't see that as a problem apart from scaring a few newbies.

Mgv6 is not that good, it has no rivers, no savanna or glacier, and no hills above y = 47, it repeats every 256 nodes. Mgv7 is much more epic and varied, the new biome system has 10 biomes.
For 0.4.14 i'm okay with staying with mgv6 but soon (0.4.15) i feel we can switch to mgv7 or something else if i come up with a new mapgen.

**Comment by ObaniGemini** [comment]
I think I would prefer to default to valleys.

**Comment by paramat** [comment]
Adding milestone just for consideration.

Mgv7 will soon have bushes that provide wood in grasslands, so there is more chance of spawning near a wood supply enough for a few tools.
It will still be possible to spawn in the deserts or tundras and need to walk hundreds of nodes to find wood, but that's the fun challenge of Minetest which avoids everyone settling within 250 nodes of spawn, which is what mgv6 allows.

**Comment by RHRhino** [comment]
@paramat will there be a further development of mgv6? Like mgv6.5 keeping the mgv6 terrain and caves, but with the mgv7 biome system?

**Comment by paramat** [comment]
I have thought of that, it would have to be an option instead of a new mapgen, it would be easier as a new mapgen but hmmmm opposes doing it that way, it would be a lot of work and i'm not much inspired to work on mgv6.

**Comment by RHRhino** [comment]
yeah maybe someone else has some time and inspiration to work on that. 😃

**Comment by paramat** [comment]
I'm probably the only person who could do it.

**Comment by Fixer-007** [comment]
Valleys :}

**Comment by C1ffisme** [comment]
What about being able to define the size of your world as a parameter? Putting a small value would result in tiny hills and biomes, while putting in a larger value would mean colossal mountains and world-covering biomes.

**Comment by paramat** [comment]
Those can be done by editing the noise parameters.

**Comment by paramat** [comment]
#4829 merged.
