### ISSUE TITLE
Rendering issue on nodebox below water

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#3704]
"Homedecor glowlight white top" block under water gets corrupted look that changes depending on camera view. Can be found at Liberty Land server (coordinates are in pic)

Tested on fefa148

![gl5w7mw](https://cloud.githubusercontent.com/assets/16494741/13030227/b5aa9658-d2ab-11e5-9eb6-544da6525b7b.png)

**Comment by RealBadAngel** [comment]
For the record. This is years old issue. Nothing new.

**Comment by paramat** [comment]
I guess z-fighting because the node below is a nodebox.

**Comment by RealBadAngel** [comment]
@paramat thats faulty water mesh code in content_mapblock.cpp

**Comment by paramat** [comment]
> It treats nodeboxes same way as plantlike etc - node that have no adjacent solid face next to water

Not sure it's 'faulty', it seems inevitable.
Nodeboxes often have faces that are not positioned identically to a normal cubic node, the faces are often inside the cube, so any surrounding nodes such as water have to always render their faces that 'face' the nodebox. If the nodebox has a face at a conventional cube position it then z-fights with the rendered water face because 2 textures occupy the same plane.

Avoiding this would mean analysing the nodebox for faces that are 'normal cube faces' and this disabling adjacent water faces from rendering.
But what about a stair node where half is against the 'cube face' and half is set back?

![screenshot_20180118_170020](https://user-images.githubusercontent.com/3686677/35110647-37658ee6-fc71-11e7-8c5b-19b3b335138e.png)

Whether we render the contacting water face or not there will be a visual bug, and we can't start dividing the water face into subregions to individually render or not render them.

**Comment by benrob0329** [comment]
Coukd we could make water render over everything else, and get rid of the air gap?

**Comment by paramat** [comment]
That's non-trivial, see the discussions about adding 'plantlike rooted' drawtype (underwater plants) which is the same issue.

**Comment by paramat** [comment]
Seems either un'fix'able or very complex to do anything about, any core dev support for attempting to improve this?

**Comment by paramat** [comment]
Tried it in MTG:

![screenshot_20181012_013311](https://user-images.githubusercontent.com/3686677/46841477-17b5b780-cdc0-11e8-9082-7e8d6d0a0260.png)

Works but now the water surface is not visible from underneath.
Here's unchanged code:

![screenshot_20181012_013418](https://user-images.githubusercontent.com/3686677/46841497-2f8d3b80-cdc0-11e8-8e58-a5613dda04b8.png)

Now with all water source faces except the top one backface culled:

![screenshot_20181012_013609](https://user-images.githubusercontent.com/3686677/46841509-4469cf00-cdc0-11e8-8664-257df4860930.png)

Removes most visible z-fighting and preserves water surface being visible.
```
	tiles = {
		{
			name = "default_water_source_animated.png",
			animation = {
				type = "vertical_frames",
				aspect_w = 16,
				aspect_h = 16,
				length = 2.0,
			},
		},
		{
			name = "default_water_source_animated.png",
			animation = {
				type = "vertical_frames",
				aspect_w = 16,
				aspect_h = 16,
				length = 2.0,
			},
			backface_culling = true,
		},
	},
```
