### ISSUE TITLE
New style water makes nodes like waterlilly to look like flying in the air

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#3734]
Screenshot of the issue: https://i.imgur.com/OpAGUyj.jpg
Disabling "new style water" solves the issue.

**Comment by paramat** [comment]
New style water should be removed i think.

**Comment by C1ffisme** [comment]
@paramat But... But...

I don't see a reason why it should be removed. It's not that hard to turn off.

**Comment by RHRhino** [comment]
Isn't the new style water disabled by default anyway?

**Comment by paramat** [comment]
Yes it is.
I think it has to be removed because all mapgens now have waterlilies, and the decoration API now enables water surface decorations, so it will look embarassingly sloppy when lowered water is enabled.
I might attempt the removal myself.

**Comment by BlockMen** [comment]
@paramat So you really want to remove a drawtype from engine because of one (!) node defined by minetest_game? Really?

**Comment by PilzAdam** [comment]
new_style_water is obsolete because a) it never really worked well and b) it's functionality is now covered by shaders. As you can see in the screenshot the node is only half full, because the shader effect that lowers water and new_style_water are both applied. This is not supposed to look like this.

**Comment by BlockMen** [comment]
The "lowered water" by shaders causes even more issues than new_style_water:
1st) the water height is not reduced, it is just drawn with an offset, so the waternode is drawn inside the node below.
2nd) water has no top-face drawn when a node above exists.

So your proposed way of being better, @PilzAdam, is even worse than with new_style_water. And would you be so nice and explain what actually did "never really worked well" ?

**Comment by paramat** [comment]
RBA intends to remove waving water and redo water shaders anyway, keeping water surface level with other nodes and using surface effects instead.
We could leave the drawtype in but remove the option to use it, but is it useful for anything?

**Comment by kilbith** [comment]
@RealBadAngel wants to remove the new style water as well : http://irc.minetest.ru/minetest-dev/2016-02-18#i_4537922

**Comment by PilzAdam** [comment]
@BlockMen "never really worked well" mainly means that it doesn't have smooth lighting, which looks really bad on the generally flat water areas. It also had some other issues, like not drawing the top-face if a solid node is above it (or maybe I fixed that a while ago, can't remember right now).

The point is that the problems with lowered water in shaders can be fixed, while new_style_water's problems are a lot harder to fix.

Btw, I didn't say that the shader effect is better. The main problem is that both effects shouldn't exist at the same time; so I tend to drop new_style_water because shaders are generally more flexible.

**Comment by BlockMen** [comment]
@PilzAdam Not having smooth lighting is a general bug of special drawtypes, so that is not a really valid argument. Or we have to remove flowing liquids aswell then.

And wrong, as I already said, the missing top-face is a bug of the "full node water", but not for "new_style_water".

@paramat 
> Now we have rivers draining into ocean, there will be a gap where they meet.

Have you tested it? I doubt there are gaps since flowing water is lowered then aswell (at least it always was).

**Comment by RealBadAngel** [comment]
Jeija's waving water and new style water shall be removed, both are broken and unfixeable.

**Comment by BlockMen** [comment]
@RealBadAngel since you claim this now aswell. What is broken in new_style_water? All special drawtypes have no smooth lighting, so this is not something it can be blamed for.

**Comment by RealBadAngel** [comment]
@BlockMen you should rather ask whats wrong with liquids in general. Everything ;)
And additions build on top of broken base are even making things worse.

**Comment by paramat** [comment]
No i haven't tested river water, just a guess.

**Comment by BlockMen** [comment]
> And additions build on top of broken base are making things even worse.
@RealBadAngel What makes it wores. Please describe the actuall issues that are causes by the new_style_water itself, not by general issues that it shares with other drawtypes.

@paramat Well, no valid argument then.

**Comment by RealBadAngel** [comment]
@BlockMen "totally fucked up" is not a valid argument?
![screenshot_20160221_144942](https://cloud.githubusercontent.com/assets/2177790/13202955/3ac11e20-d8ab-11e5-8f2c-a1adabecb237.png)
![screenshot_20160221_145244](https://cloud.githubusercontent.com/assets/2177790/13202954/3abdca9a-d8ab-11e5-82ba-21b1ca23bcb3.png)
![screenshot_20160221_145350](https://cloud.githubusercontent.com/assets/2177790/13202956/3ac258bc-d8ab-11e5-84fe-4efe476b131b.png)

**Comment by Fixer-007** [comment]
@RealBadAngel This is probably not new style water bug but this https://github.com/minetest/minetest/pull/3755

**Comment by paramat** [comment]
Yes that's #3755 it'll look better soon.

**Comment by paramat** [comment]
New style water has been removed.
