### ISSUE TITLE
Friendly "permission denied" message instead of core dump

### ISSUE THREAD

**Issue by indriApollo** [minetest/minetest#3781]
I inadvertently built minetest as root, then switched to my regular user and launched the game only to be greated by : 

```
ERROR[Main]: An unhandled exception occurred: Failed to open log file debug.txt: Permission denied
[...]
Abandon (core dumped)
```

No big deal, I fixed my permissions with : 

```
sudo chown -R <user>.<user> minetest/
```

But wouldn't it be better if some window opened or a textmessage in the menu told me to check my file permissions ?

**Comment by C1ffisme** [comment]
:+1:

**Comment by xeranas** [comment]
@indriApollo not sure if it worth effort to fix it. It potentially adds some if/else weight for this particular edge case and give no value to gameplay. If you able build game by yourself it very likely that you will know how to dealt with such situation.

Need think about localization too. If this is OS level messages then you likely get build-in translation for this message:

> ERROR[Main]: An unhandled exception occurred: Failed to open log file debug.txt: Permission denied

If Minetest will try "wrap" your situation with "friendly" message it may end up with same message because due same reason localization resources will be locked too or if "friendly" message will be hardcoded (not-localized) string then for foreign national player see it as "unfriendly" (foreign language) message either.

This is just a thougth. I'm not MT dev and I do not know current localization situation in MT.

**Comment by nerzhul** [comment]
logging file should not trigger an abort. Locales yes i think

**Comment by est31** [comment]
@xeranas in theory you are right but I think debug.txt is opened before we open localisation files, so we cant translate stuff at this stage yet. A way to solve this would be to load localisation files first but that has the disadvantage that any errors that occur with localisation files loading dont get into debug.txt, so it would be best to keep it this way.

**Comment by indriApollo** [comment]
@xeranas has a good point. This issue isn't needed anymore.
