### ISSUE TITLE
Bypassable security using upvalues

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3788]
@kaeza has brought this up in IRC: You can get parts of the insecure environment using upvalues. See this example: https://gist.github.com/kaeza/ab039940f9ef786d64ca

**Comment by sfan5** [comment]
See, this is why I am against mod security.
There will always be some way to bypass it and truly malicious mods won't be hindered by it.

About the actual problem: Exposing the whole debug module seems like a bad idea, why do we do it?

**Comment by est31** [comment]
IDK, ask @ShadowNinja . What about disallowing all of debug except getinfo? http://irc.minetest.ru/minetest-dev/2016-02-26#i_4545398

**Comment by kaeza** [comment]
The [SandBoxes](http://lua-users.org/wiki/SandBoxes) article on the Lua Users Wiki has a complete list of what is and is not considered "secure", and for what reasons (see section *Table of Variables*). Some things may prove hard to implement correctly without extensive changes to Minetest. As a simple example, we use `setmetatable` to set defaults for e.g. item definitions (via `__index`).

I personally think that security for Minetest is not yet "production-ready" (if such a thing even exists). The current implementation is not secure at all for reasons explained in the article.

I partly agree with @sfan5. With all due respect to authors, having half-assed "security" is worse than no security at all, because it gives a false sense of security.

@sapier may want to chime in too.

**Comment by PilzAdam** [comment]
I'd suggest removing security settings from all user documentation and settings menu until it can be safely called "secure".

**Comment by est31** [comment]
Let's see whether the issues can be fixed until the feature freeze for the next release and if they weren't fixed, we can still remove the setting from docs until the release?

**Comment by ShadowNinja** [comment]
This can be fixed by simply removing `getupvalue` from the security whitelist.
Look good? : http://ix.io/oLD/diff

**Comment by ShadowNinja** [comment]
abd4a79acbdfcea0bb661b8065ef3ac8f3e25e80
