### ISSUE TITLE
expose image handling methods to lua modding api

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#3869]
as per: https://forum.minetest.net/viewtopic.php?f=7&t=14164&sid=81179b7d00015ac48d5bf3634ba886b3#p210309

what is required is the ability for a mod to use core/irrlicht image functions, particularly:
1. open an image file
2. return the image width, length, pixel bit depth, color format
3. return the pixel color value at a given x,y or range of x0-x1,y0-y1
4 close the image handle?

new files to be created: (?)
src/script/lua_api/l_image.h
src/script/lua_api/l_image.cpp

irrlicht classes and methods:
irr::video::IImageLoader::loadImage() -- some DEMs have no file extension but all are GeoTIFF
irr::video::IImage::getDimension()
irr::video::IImage::getBitsPerPixel()-- most DEMs are 16bit greyscale
irr::video::IImage::getColorFormat() -- maybe

**Comment by bobombolo** [comment]
Is it possible to create an IImage object using IImageLoader in c++ then pass the IImage object to Lua or would you write lua interfaces for all the methods you might want to do with the IImage object in c++ and then pass the results (tables, often) to Lua?

as a note, the use-case we have in mind for the realterrain mod is that there will either be many requests for individual pixel values (one per voxel footprint), or bulk requests for the values of a range of pixels, say the mapchunk footprint. it should also be noted that the source images are often rather large. using lua image manipulation libraries we discovered that it is best if the tool can leave the image file handle open due to the costly time and memory (cache) overhead involved in opening the image for each pixel read, so whatever the solution will be for this feature it will likely be one that leaves the image open. finally, the use-case includes having several images open at once so if the IImage object is not passed to Lua, but rather stays open in c++, there will need to be a way to reference which one is being accessed.

sorry for the ignorance I am revealing with these notes and concerns, but I have never passed anything from c++ to Lua... I have a sense that passing the complex IImage object to Lua is not the way that it works...

**Comment by C1ffisme** [comment]
This is actually a good idea.

**Comment by celeron55** [comment]
This is actually more difficult than was initially thought because the Minetest server isn't actually linked with the Irrlicht library. It only needs a few headers from there for some simple data types. This is done so that servers don't need to install the irrlicht library which generally would pull all kinds of X and OpenGL things that server owners do not want to install. 

So... really there needs to be some kind of an option for enabling these image things which isn't enabled by default. Which might kind of kill the whole point of this thing.

Thoughts?

**Comment by bobombolo** [comment]
yes that sort of kills it. what if the user is playing singleplayer, does the server invoked for singleplayer still not have those irrlicht links? is it only the standalone server that lacks them? it could still be useful to singleplayer client play where additional players connect to the first client that creates the game unless all this does is launch the standalone server.

**Comment by PilzAdam** [comment]
@bobombolo these servers are linked against Irrlicht, but we don't want functions in our API that don't work on all servers.

**Comment by celeron55** [comment]
I guess we could just throw the STB image library in there to be used by the server for this purpose: https://github.com/nothings/stb/blob/master/stb_image.h

It's small, stable, suitably licensed and very portable. Can anyone think of a good reason for not using it for this?

**Comment by bobombolo** [comment]
For the purposes of realterrain including an image library only helps if it supports TIFF format and can read 16-bit pixel values. It looks like STB meets this.

**Comment by bobombolo** [comment]
stb_image does not allow for pixel access. the entire image gets read into a char type variable.
https://github.com/nothings/stb/issues/358

**Comment by bobombolo** [comment]
how about this one: https://github.com/jcupitt/libvips

apparently you can get pixel access without loading the entire image into memory: http://www.vips.ecs.soton.ac.uk/supported/8.3/doc/html/libvips/VipsRegion.html

but is this a standalone library that can be included in minetest core or is it just a set of bindings? also is it small enough for inclusion in core?

**Comment by rubenwardy** [comment]
this is rather specialist, I suggest just using Luarocks and require
