### ISSUE TITLE
Player falling through blocks after restart when noclip enabled

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#3870]
To reproduce: 
- enable noclip, stop the game, run it again, you will go down rapidly up to -110 and stop in the blocks. You will need some tries to reproduce the fall.

Another problems:
- fly up few blocks high, stop and restart game, after some tries you will go through blocks again
- fly up few blocks high, stop, disable noclip and restart game, after some tries you will fall down to ground

minetest build 095f623

**Comment by DonBatman** [comment]
I have experienced this as well

**Comment by LazyJ** [comment]
This has been happening for a few months. I figured it was due to lag. When I connect to servers in the UK or Russia (the other side of the globe from where I live) I log out in the air and then when I return after a few days, I see the media bar progressing and then I see the underground moving rapidly up the screen and the F5's y coord is sinking rapidly. By time my privs are recognised by the server, I have fallen over y-1000 into the ground. This also happens when I connect to Minetest servers in the US/Canada, just less deep.

However, if I log out and then log back in within moments, both shutting down my client or not in between, then I don't fall through the ground. So the time lapsed between logins seems to play a part in this.

**Comment by 0-afflatus** [comment]
Yep. This happens to me on my own server.

**Comment by red-001** [comment]
This has happened to me before.

**Comment by C1ffisme** [comment]
My hypothesis is that when Minetest starts, flying is not taken into account and neither is block collision. The player falls several blocks. Then the map is loaded, fly is taken into priority again and the player is below the Earth.

The fortunate thing is, if it only works with noclip on, that means that only people who are able to get up anyway can solve this problem.

**Comment by 0-afflatus** [comment]
It would be kind of useful if fly / no-clip / fast status was remembered.

**Comment by paramat** [comment]
@Fixer-007 is this fixed by #3965 ?

**Comment by Fixer-007** [comment]
Will check

**Comment by Fixer-007** [comment]
As of build 45eab34 / 7 Nov 2016 I can't reproduce it anymore. Closing.
