### ISSUE TITLE
Add games that should be bundled with Minetest

### ISSUE THREAD

**Issue by lnjX** [minetest/minetest#3949]
There you can declare and vote for games to be bundled with Minetest:
https://forum.minetest.net/viewtopic.php?f=15&t=9103
https://forum.minetest.net/viewtopic.php?f=15&t=9116

**EDIT**:
I don't want to bundle my game anymore, but some other games (as the tutorial game) might be cool.

OLD OPINION:
I think my game [Minetest TNG](https://forum.minetest.net/viewtopic.php?f=15&t=14145&p=209153) is ready to be bundled and I was surprised there already voted people for it!
It would be really cool if my game and the tutorial game would be bundled with Minetest (0.4.14)!

^^ Maybe somebody could add it to the 0.4.14 milestone, that this won't be forgotten.

**Comment by ObaniGemini** [comment]
I agree that there should be some example games with stable builds.

**Comment by C1ffisme** [comment]
I'm not sure if we're ready to have a mobs mod inside of Minetest...

Maybe we could slice it down and merge it with Minetest Game, like we did Minetest NeXt?

**Comment by LNJ2** [comment]
@C1ffisme I don't really want that my game will be merged (not at the moment). And why no mobs? - The most people add mobs anyway. And it is not Minetest Game - It's Minetest TNG, we would have both. Those people who want mobs can use it, the other people can further use MTG - Why not?

**Comment by MoNTE48** [comment]
@LNJ2, Minetest use LGPLv2.1+ lic. Your game - GPLv3+. 
Your game will never be official Minetest build, yet it will not change the license.

**Comment by LNJ2** [comment]
@MoNTE48 But c55 didn't wrote that it have to be LGPLv2.1+! He only wrote these rules:
1) you are developing a subgame,
2) it is ready to be released to anyone who downloads Minetest,
3) it's name is not "minetest_game", "minetest", "minimal" or "minimal_game",
4) you aren't planning to discontinue it anytime soon,
**5) it's released under a free license (permissive [preferably] or copyleft)**

**Comment by C1ffisme** [comment]
@LNJ2 No, some people can't use them, since they either bloat their worlds with mods until it looks like dreambuilder, or they are 0gb.us and their computers are... unspeakably bad.

**Comment by LNJ2** [comment]
@C1ffisme All mobs in CME have got a lifetime and after that time has elapsed they'll die/despawn, so the worlds won't bloat with mobs (If you mean that, you wrote mods). And people with really really bad hardware can just use MTG (as I said). I have not so good hardware (Intel HD Graphics 4000, i5 3210U) and I can play my game without problems.

**Comment by C1ffisme** [comment]
No, I meant mods. Some people will download something like homedecor. And then something like unified inventory. And then moreblocks. And then they keep downloading new mods that look cool.

Soon, they learn how to code their own mods, and now they add their own badly textured nodes to their game.

Suddenly, they have a world where you can't remove any of the thousands of blocks and items, since you will get unknown nodes and items.

**Comment by LNJ2** [comment]
After this conversation: http://pastebin.com/Mf8PUp8L in #minetest-de I changed my opinion and I wouldn't say  no if you would like to add it but I agree that it is not so important to add it. But what about other games?? like the tutorial subgame (and world)?

**Comment by rubenwardy** [comment]
It's definitely about time for this. 
Make it happen.

**Comment by rubenwardy** [comment]
@celeron55

**Comment by kilbith** [comment]
Definitely no.

Most of subgames heavily rely and copy code from Minetest Game (TNG is a good example of this). Beyond the fact that they lack of originality, they get always discontinued and outdated a couple of months after the ephemeral fad and excitement fade away.

They're also (mostly) not solid enough to be shipped officially because lack of quality control.

**Comment by C1ffisme** [comment]
Actually... Why are you even posting this... here?

You can post your requests on the forum, but this is Github.

So we have a big topic to make requests like this, and you need to make an entire Github issue? (Which apparently is some big deal.)

**Comment by DonBatman** [comment]
@C1ffisme it might be because it was said a long time ago that it2said subgames wouldbe included.

**Comment by LNJ2** [comment]
@C1ffisme I don't think that an issue is something big, if there are 594 opened (Yesterday it were 602 :+1:). And I wrote this on GitHub that something happens!

**Comment by rubenwardy** [comment]
celeron55 thinks that there should be multiple subgames bundled.

> @celeron55 
> The games will be picked so that there is minimal overlap, while the desires of most people are catered for, while keeping the package size reasonable. The recommended games will be reconsidered for each release, but it is very desirable that they don't need to be removed for a long time.

It demonstrates the variety.

> @kilbith
> Most of subgames heavily rely and copy code from Minetest Game (TNG is a good example of this). 

Why is that bad? Reuse is good. Most games will have trees and dirt. I don't want to have to rewrite these.

> @kilbith
> they get always discontinued and outdated a couple of months after the ephemeral fad and excitement fade away

That's a non-argument, choose a game which has good quality already and then let the community develop it (which would include core MTG devs)

Please note that once the subgames are added to the release they are added to the release at their current state, we don't tend to create patches to old stable versions. If the subgame isn't maintained, and becomes outdated, then it could not be included for the next release.

> @kilbith
> They're also (mostly) not solid enough to be shipped officially because lack of quality control.

Mostly? We're not saying to bundle all subgames, but only the good ones.

-----------------------------------------

I think a game like Wasteland would be a nice addition. Unfortunately @BlockMen has left. A good loyal fork would need to be found/maintained.

The power of Minetest imo isn't with mods, but is with subgames.

Yes, whether more subgames are packaged in this upcoming release depends on whether or not any subgames are good enough quality to be packaged. But that doesn't mean `definitely no`, it doesn't have to be this release. Subgames could be chosen as candidates and then be maintained and undergo quality control in time for the release after 0.4.14.

**Comment by paramat** [comment]
The tutorial game is not yet ready according to it's creator and is discussed elsewhere.
You are not sure about adding your own subgame, that should be considered in the forum anyway.
Apart from those points this issue is just links to the forum, so closing.

**Comment by DonBatman** [comment]
I disagree with closing this. After being told that subgames would be included I think that subgames should be considered. There has been no real argument made as to why games should not be included or any discussion on what games are close enough to be included. I think at a minimum it should be discussed what is required to make a subgame good enough to include.

**Comment by ObaniGemini** [comment]
I agree with closing. We should stop flooding the Github notifications whereas we can discuss on the forum (with even more people)

**Comment by 0-afflatus** [comment]
There is a huge conflict of opinion here.

I think all games (apart from minimal) should be packaged separately.
But the community has been promised that subgames would be included. Being told that no subgames are considered suitable yet sounds really disingenuous (that's not a personal crit). I think there needs to be a clear statement that subgames are not going to be included in any foreseeable release in order to offset user expectations.

**Comment by rubenwardy** [comment]
I think that there needs to be a clear acceptance criteria that subgame developers can work towards. I propose the following:

1. Public and generic acceptance criteria is posted on the forum.
2. Subgame devs read and adjust their subgames.
3. When subgame devs feel that their subgame is ready, they propose their subgame somewhere.
3. Feedback is given (by core devs and the community). Ie: what is needed before it is considered ready.
4. If the game is considered to have potential
    1. Subgame development is forked to an organisation like minetest-games
    2. Subgame undergoes QA
    3. When the subgame completes all feedback and requirements, it can be added to a ready-to-add list.
5. Or if the subgame needs more work from original author, goto 2.

There needs to be a way of giving feedback otherwise this will never happen.
We'll continue to have a monopoly of MTG and its mammoth default mod.

**Comment by kilbith** [comment]
> choose a game which has good quality already and then let the community develop it (which would include core MTG devs)

That's unrealistic. MTG devs are either semi-away or too busy to care about other subgames.

Now speaking about the quality of these subgames, they're mostly Minetest Game + additional extras because it's the easiest way to go. These extras are not in mainstream because they're either half-baked or rely on hacks, I have plenty of examples in mind.

Personally I wouldn't ship an end-product with so few quality assurance.

The only game that came to my mind to be worth an inclusion for its originality, consistency and level of polish is VoXus and to a lesser degree, Pixture. The rest is a bunch of Frankenstein's because so few modders are able to create fresh new concepts from scratch.

Please note I'm excluding specialized subgames like CTF in my feedback.

**Comment by rubenwardy** [comment]
CTF would not be appropriate anyway, as it's a multiplayer game.
It doesn't have to be core MTG devs, only include them if they wish.

Just because they're mostly low quality doesn't mean that there won't be a few which are good quality, and doesn't mean they will be low quality for ever. I don't think any subgames will be ready on time for 0.4.14 anyway. We do need to start the process though. Even if the subgames that attempt to be included aren't included in the end, they will still be better quality than before.

The alternative to this is having a good mod/subgame installer in the main menu, and not bundling any subgames by default.

**Comment by LNJ2** [comment]
The old mod-installer was really nice and a good pro point on every Minetest review. It would be very cool if somebody would remake it (or get the old one working again), for mods and games!

I think with a mod/game installer there would be no need to bundle another game, than MTG.

**Comment by 0-afflatus** [comment]
@kilbith VoXus? The game that never even got started? Please get real.

@rubenwardy that looks like a sane procedure. We already have 3 & 4 in forum pages, so really the way forward is to set up a minetest-games group or similar - the first task would be to draw up acceptance criteria, one of which would be LGPL2.1 compatibility. I agree with kilbith that this should not be left to the MTG team. It is high time we got away from the idea that MTG is the only subgame "in the village".

**Comment by est31** [comment]
:+1: Minetest can and should be more than MTG. The alternative subgames may receive less attention than MTG, but that's partially because they don't get shipped with minetest.

We do need some criteria for new subgames. E.g. we could require that every subgame is substantially different from each other, so we don't have five subgames trying to be the best minecraft remake, but there should be an emphasis on different gameplay, etc. Also only subgames that have been maintained for some time already should be shipped. And of course subgames need to fullfill the same quality standards than MTG does (esp. regarding texture consistence and code quality).

**Comment by Ferk** [comment]
I think the subgame installer would be the best way to go. Not everyone might want to download a whole set of games every time he installs/upgrades minetest. Some might only want MTG, others might not want MTG at all and just use whatever other game they like best.

Imho, having a dedicated database and stuff as it was before was overcomplicated. For subgames you don't even need to care about dependencies, it could be as simple as a plain text file the clients read to fetch the more or less curated list of games that can be downloaded.

**Comment by 0-afflatus** [comment]
> Not everyone might want to download several MB of games every time he installs/upgrades minetest.

And Debian based distros are likely to want to package them separately.

**Comment by DonBatman** [comment]
I would rather see a game installer then games included.

**Comment by Ferk** [comment]
> And Debian based distros are likely to want to package them separately

Isn't there already a ~/.minetest for locally installed stuff and a /usr/share/[...]/minetest for system-wide stuff? The installer could use the local one without interfering with the games installed by the package-manager.

But for those who only play multiplayer and don't want to host their own server it's not even needed to have any game installed.

**Comment by 0-afflatus** [comment]
@Ferk that's an argument against bundling. Debian will install any packaged games that it distributes to /usr/share/games/minetest/games/, however it will prefer to package them separately. This is separate from user-installed games, which as you say go into ~/.minetest . The client would need to pull in minetest_game as at least a recommended dependency, regardless of whether people are going to use it. Anyway that's really an issue for the Debian maintainers. I guess if any subgames are maintained in separate repositories and pulled in as required, as MTG is, then my comment is somewhat irrelevant.

**Comment by notanewbie** [comment]
It would be nice to have some sort of way to install mods and games through Minetest. Isn’t it possible make a menu that could show all the mods and games in the forums and be able to download them into the appropriate folder?

**Comment by C1ffisme** [comment]
@notanewbie Er... um... That's only just on the brink of being out-of-scope of this issue. In fact, the idea of this is to prevent needing to use a store to make MTG good.

**Comment by red-001** [comment]
So any chances of a game getting bundled next release other then minetest game?

**Comment by tacotexmex** [comment]
As I still don't understand why subgames aren't bundled, let's see the con arguments one more time.

> 1. Most of subgames heavily rely and copy code from Minetest Game
> 2. they lack of originality
> 3. they get always discontinued and outdated a couple of months after the ephemeral fad and excitement fade away.
> 4. They're also (mostly) not solid enough to be shipped officially because lack of quality control.

1. Recent @paramat quote of that Minetest Game is:
> MTG is currently a simple core to add mods to, it's not meant to be fun, exciting, a complete subgame or any kind of specific subgame. MTG is lacking many things and this is intentional.

How would this be in any way bad when it's the _actual purpose_ of MTG?

2. Yes, most of them do, but most wouldn't be bundled anyway. Pixture, Voxelgarden, Adventuretest all have their own character and traits.

3. Again, yes, most of them do, but most wouldn't be bundled anyway. Some of them don't. And let's not overlook the immense incentive that people playing a subgame developer's game creates. If no games are bundled, the games that do exist are played less and receives less attention from developers and players alike.

4. Like in argument 2 and 3, were not talking about bundling 10 games. 1-3 would do fine.

**Comment by kilbith** [comment]
I've commented on this issue one year ago and I don't care anymore whether more subgames get bundled or not. Then I'd appreciate it if you do not ping me any further on this matter, thanks.

**Comment by tacotexmex** [comment]
Good. Then I'd like to propose Pixture by kaadmy and Voxelgarden by CasimirKaPazi.

**Comment by ThomasMonroe314** [comment]
I agree with including more sub-games than just MTG, because not only would it allow for more people to find the right style of play for them, but it would also let people see what this game is capable of.

When i first started, i got bored very quickly with the MTG, so i wanted to look for other games like this, but then i found the MT community. I am one of a few people that play and are computer literate so i got into modding and the like. I think that in order to see where this game(MT) is headed is to look at the subgames built off of it.

I found that most of them were either reverting back to classic MC play, or adding some sort of experience factor and goals(skyblock for instance).

**Comment by Fixer-007** [comment]
I agree with k-lbith 2 Apr 2016 reply. In my opinion you need to finally start working on MTG to make it something nice already, so you don't need to rely on modded to even enjoy the game (6 years, c'mon).
Apart from that we probably need Tutorial, stuff like skyblock, etc.

**Comment by tacotexmex** [comment]
> you need to finally start working on MTG to make it something nice already, so you don't need to rely on installing mods to start enjoying the game

👇 

> MTG is currently a simple core to add mods to, it's not meant to be fun, exciting, a complete subgame or any kind of specific subgame. MTG is lacking many things and this is intentional. 
— https://github.com/minetest/minetest_game/issues/1782#issuecomment-309144944

**Comment by jastevenson303** [comment]
The core issue is whether Minetest should come with a multitude of sub-games, more than whether which ones.

I've always maintained that Minetest should come with only one sub-game: minimal.  The mod/game store/repo should be implemented and the user decides.

**Comment by ThomasMonroe314** [comment]
@jastevenson303 I believe that multiple subgames is one of the goals celeron55 has for this project.

**Comment by paramat** [comment]
Yes, bundling multiple games was already decided. This issue is about which ones.

**Comment by ThomasMonroe314** [comment]
maybe a little bit after 0.5.0 comes out we can focus more on this than features

**Comment by rubenwardy** [comment]
:-1:

Bundling games raises a tonne of issues - it ties the game with our development cycle, resulting in an outdated game, and negatively impacts other games. I support removing Minetest Game from the default installation, and showing a window on first run / when there are no games installed to install a game from ContentDB
