### ISSUE TITLE
Add option to enable multi-processing for Singleplayer

### ISSUE THREAD

**Issue by Rui914** [minetest/minetest#3975]
Multi-processing is faster than single-processing, so I think that is good.
I usually run server and client to manual.

**Comment by nerzhul** [comment]
hmmm what is your problem ?

**Comment by sofar** [comment]
This is non-actionable and way too broad. Just because in general it's good to enact threading to speed up tasks that can be parallellized, it doesn't mean that you can just flip a switch and it even further doesn't mean that it would even make a difference.

If there is a place where there is a proven to be a bottleneck (with data to back it up), and making code run in parallel would actually be (1) possible and (2) help, then it's worth filing a bug.

**Comment by est31** [comment]
singleplayer already does "multi-processing", meaning that it runs multiple lightweight processes in the same minetest process. These lightweight processes are also called threads.

There is no difference in performance between "multi-processing" (as in having separate server and client processes) and multi-threading.

Yes, when you press esc, the game stops, but that only is an added feature.

Therefore, this feature is already implemented as threads, closing as invalid.
