### ISSUE TITLE
minimap right shift does not work

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#3978]
With left_shift + F9 you can toggle between a square and round minimap. But you can't with right_shift + F9.

Please make it possible to also use the right shift key. It is nearer to F9 and the descriptions is always shift not left shift.

**Comment by paramat** [comment]
I think it's this way because Rshift + F9 is awkward to do with the right hand, Lshift + F9 is easy with 2 hands. I'd prefer it was kept simple :-1:

**Comment by PilzAdam** [comment]
I'd consider this a bug. It shouldn't matter which shift key the player prefers.

**Comment by lightonflux** [comment]
The right shift is the only one that i can use with one hand, otherwise i have to move one hand from the mouse to the keyboard and back again. 

Different hardware layouts, different keys etc. But for almost all applications counts shift is shift.

**Comment by paramat** [comment]
I was wrong about this, removed my -1.

**Comment by JRottm** [comment]
Responsible for this behavior is game.cpp, lines 2567-2568:
```
        } else if (wasKeyDown(KeyType::MINIMAP)) {
                toggleMinimap(isKeyDown(KeyType::SNEAK));
```
So, actually it's not Shift-F9, but it's SNEAK+MINIMAP keys which you need to press. Both keys can be redefined in the config, and per default sneak is L_shift. To make this work the way you like we'd have to define an *alternative* sneak key, which isn't easy, because we'd have to extend the code to allow multiple keys assigned to the same function i.e. make sneak = L_shift or R_shift.

**Comment by paramat** [comment]
^ That.
