### ISSUE TITLE
menu_clouds = false results in a black background

### ISSUE THREAD

**Issue by DonBatman** [minetest/minetest#3986]
If you turn of clouds it makes the background black. Not sure if this is a bug or I am asking for a feature request. It should default to a nice background.

Shreenshot of what I get.
http://i65.tinypic.com/rvge4h.jpg

This is from master branch on github. downloaded 2 days ago.

**Comment by paramat** [comment]
Perhaps it should be an empty blue skybox when disabled?

**Comment by DonBatman** [comment]
I don't know what the best image would be but I know the black screen is not friendly.  

I also noticed that if you put an image in the minetest_game/menu folder and call it background.png it shows up if you are on the singleplayer tab but if you go to any other tab the background does not display.

**Comment by ObaniGemini** [comment]
Or maybe a background similar to minimal ?

**Comment by MoNTE48** [comment]
In MultiCraft I've been disabled MainMenu clouds and using background images, but it works in a strange way. Look what I had to do:
https://github.com/MultiCraftProject/MultiCraft/blob/master/src/defaultsettings.cpp#L353 --settings
https://github.com/MultiCraftProject/MultiCraft/blob/master/builtin/mainmenu/init.lua#L131 --init.lua because the settings does not work everywhere.

**Comment by paramat** [comment]
Dirt is possibly the most ugly texture choice.

**Comment by sofar** [comment]
a tiled ```default_stone.png``` would be decent.

**Comment by DonBatman** [comment]
I like the clean look of clay but it does not tile very nice. I modified mine to tile properly.

![default_clay](https://cloud.githubusercontent.com/assets/9045998/14590534/98e49c84-04b1-11e6-8186-0106b913edc7.png)

**Comment by kilbith** [comment]
The mainmenu is automatically looking for `default_dirt.png` when present in a texture pack. Otherwise it looks for  `dirt_bg.png` in the engine textures folder (`base/pack`) as fallback.

Dirt is an excellent choice and the default one for a reason, as it's a fundamental element, and because it goes well with the stone header. Example with PixelBOX's dirt : 

![capture d ecran de 2016-04-18 11-37-59](https://cloud.githubusercontent.com/assets/7883281/14599946/906e3674-055a-11e6-8df0-84e80bdd5c45.png)

**Comment by DonBatman** [comment]
The issue is that the dirt_bg.png that textures.lua points to is in textures/base/pack/dirt_bg.png. That image is not a dirt image. It it a black image. 
https://github.com/minetest/minetest/blob/master/textures/base/pack/dirt_bg.png

**Comment by DonBatman** [comment]
Here is where it got changed.
https://github.com/minetest/minetest/commit/5d88501a5799dbee8623ce9920423948659368fa#diff-9026d79794bfd25a1407f16d9063039c

**Comment by MoNTE48** [comment]
Wow, never seen. :-о Perhaps png it has been some mistake. My apologies!

**Comment by DonBatman** [comment]
@MoNTE48 that was actually the minimal dirt texture anyway. It looks worse then having a black screen.
I think we do need a new texture.

http://imgur.com/PtLkjZd

**Comment by MoNTE48** [comment]
@DonBatman, Horrible texture. I just can not look at it without tears
Yes, but dirt on minetest_game were horrible, too. Need 64*64 texture

**Comment by DonBatman** [comment]
If we want dirt as the image I suggest the image from minetest_game.
http://imgur.com/WOaRd8D

The default clay is nice and clean looking but might be too light.
http://imgur.com/5cFRW1q

I tried a few others like cobble and stone but there was too much grey and the logo blended in too much. 

The default_wood.png looks nice but a bit too busy. Need less visual noise.
http://imgur.com/GTaq9Am

Sandstone looks really nice and sandstone brick is not bad.
http://imgur.com/6PVpjDU
http://imgur.com/nKQMskK

**Comment by C1ffisme** [comment]
@DonBatman How about metal blocks, mixed with buttons or wires from mesecons to look like an 'engine'?

Just an idea.

Just a thought, though, shouldn't we talk about this [here](https://github.com/minetest/minetest/pull/3818)?

**Comment by DonBatman** [comment]
@C1ffisme a custom image would be nice but that means we would have a larger image. I am not sure what others think of larger images. Also, with a single image you would have to make sure it scales right for different screen sizes. 

About discussing this in pull 3818, I would rather discuss a simple solution here and have it merged so it is in 0.4.14. Making it more than a simple texture change should be in another thread IMHO.

**Comment by sofar** [comment]
Given that there is already a mechanism to display a different background, I think this issue is resolved.

However, the issues remaining are:

(1) - Disabling clouds doesn't change the background to dirt (a restart is needed)

(2) - Why does it have to be dirt? Couldn't a subgame choose a different texture?

Of these, (2) is clearly a feature, and not as important, but (1) is a bug, and a bad one too, that should be fixed.

**Comment by DonBatman** [comment]
@sofar the code is fine. The texture was changed by mistake a while ago. Even if that was reverted it would be ok although it uses the poor quality dirt image from minimal game.

**Comment by MoNTE48** [comment]
I (or you) can do pr and add dirt from minetest_game as a temporary solution. This is 10 times better than the minimal bg

**Comment by sofar** [comment]
It should still change immediately when switching texture packs, and not require a game restart.

**Comment by paramat** [comment]
I think any dirt is too noisy, it makes the tab buttons unclear.
A clear empty skybox would make sense.

**Comment by paramat** [comment]
Added to milestones, easily fixed.

**Comment by paramat** [comment]
See #4010

**Comment by 14NGiestas** [comment]
What about put a setting and let the player choose the background?
background_type = `tiled`,`fullscreen`,`centered`
background_path = '/path/to/image/image.png'

**Comment by paramat** [comment]
#4010 is merged.
