### ISSUE TITLE
Remove minimal_game from release builds

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#4006]
minimal_game it just kind of garbage to end player. It is necessary (probably) as the teaching aid or to  debug build, but it should not be present in the release build.

**Comment by rubenwardy** [comment]
Relevant: https://github.com/minetest/minetest/pull/1740

**Comment by MoNTE48** [comment]
@rubenwardy, after 1.5 years of lazy developers may evolve or become extinct? ))

**Comment by est31** [comment]
I am with @kahrl on the issue of 1740, but about not packaging minimal_game for android release builds is a good idea.

Minimal is sometimes very useful, I use it often during development.

**Comment by MoNTE48** [comment]
@est31, But this increases the size of the repo and simply do not need to release. It may be worth adding to the release build ONLY minetest_game? This will reduce the size and removes the confusion.

**Comment by est31** [comment]
As I said, packaging is a different matter than keeping it in the repo. Removing minimal_game from android packages or other packages in release mode is okay.

Also, the repo size doesn't decrease only because we remove sth: git stores all history.

**Comment by DonBatman** [comment]
I agree with @rubenwardy and @MoNTE48. Minetest is made for the end user. Minimal is for developers, not the end user. When someone downloads from minetest.net they should be getting a polished game and not one that is for developers.

**Comment by rubenwardy** [comment]
My opinion has changed since then: minimal should stay in the dev repo, but should be removed in release builds.

**Comment by C1ffisme** [comment]
I agree with @MoNTE48 and the others. It adds confusion when someone has downloaded Minetest for the first time, and they don't put Minetest Game in their build. Some thoughts might go through their heads once they start up minimal:

- Did I install a corrupted version? (Yes, some will think this because they don't know what corruption is.)
- Is this a fork/fake?
- Do I need a texture pack or mod?

If no games are installed in Minetest, it should link you to Minetest Game.

**Comment by rubenwardy** [comment]
If you only have minimal installed, the following message is shown when creating a world:

> Warning: The minimal development test is meant for developers.
> Download a subgame, such as minetest_game, from minetest.net

Since #1743

**Comment by DonBatman** [comment]
My opinion is that, like rubenwardy said, minimal should be removed from releases. What happens in dev versions is another story. When people download from minetest.net or google play store they should not get development stuff. Anyone downloading from github should know enough about minetest to know what it is or know enough to google it or ask on the forums.

**Comment by tobyplowy** [comment]
@DonBatman I totally agree minimal development build should not be in the full release.

**Comment by paramat** [comment]
I agree, where this can be done, but for players compiling from source code minimal will be present in the repo at the 'stable release' commit.
I wonder if we need minimal at all.

**Comment by DonBatman** [comment]
@paramat There are devs who use minimal. There might be resistance to getting rid of it. As I have already said I see no reason for it being removed from github since anyone compiling will likely have the knowledge to either know the different or can figure it out.

**Comment by est31** [comment]
> I wonder if we need minimal at all.

I use minimal as my main subgame for development.

Sometimes I enable debug features (printf etc) or something, and a fatter game like minetest_game will just make my console buffer freak out.

Similar for when I test a new feature, I don't want to spend tens of seconds to load media and other stuff when I will close the game in three seconds again because I have tested it (or got the debug printf I needed, etc).

It may make a bad impression on new users, but if they install minetest from git then they should expect a development version.

Less experienced users are encouraged to use the ppa or windows downloads. Let's remove it from there, I completely agree with that, I do not agree with it being removed completely from the codebase.

**Comment by Zeno-** [comment]
I use minimal also: for debugging, profiling and all sorts of things. I also use minetest_game

Summary
I don't think minimal should just be removed from the repo
I agree that it's not necessary in end-user pre-built downloads (PPAs, Windows downloads, APK etc)

**Comment by paramat** [comment]
Yeah agreed, it could always just be hidden as some mapgens are.

**Comment by 0-afflatus** [comment]
As a sub-game developer I agree with est31 and Zeno here.
I don't have any opinion on android or Windows builds.

**Comment by Dragonop** [comment]
I use minimal dev test to test my mods, mainly because I'm too lazy to download anything else, and you want to take it away from release builds? Lolwut, no thanks. :-1:

**Comment by tobyplowy** [comment]
@Dragonop It Could Be a hidden feature so you can enable it in the Advanced options?

**Comment by C1ffisme** [comment]
@Dragonop That doesn't make a lot of sense, because most mods require content from Minetest Game. (Such as mese crystals, diamonds, or different types of wood.)

**Comment by 0-afflatus** [comment]
> most mods require content from Minetest Game

That's an interesting comment. I don't know whether that is true or not, but it seems to be an argument for keeping minimal as easy way to test for MTG dependencies. Naturally I have a vested interest in more mods **not** depending on MTG's default mod as it makes it much more complicated to  integrate them into other games. Of course there are many cases where that cannot and maybe should not be avoided, but having minimal available as a 'control' seems like a Good Thing from where I'm standing.

**Comment by C1ffisme** [comment]
> Naturally I have a vested interest in more mods **not** depending on MTG's default mod

Well, mod**s**, but yeah.

Most of the ideas I'm thinking of are just crafting recipes. Of course, certain mods might require river water for a water wheel, or some kind of fuel. (Using diamonds as power crystals maybe?)

I'm not sure why MTG would be laggier than minimal, since the only real difference is that there are more blocks and items. Even TNT, about the laggiest thing in Minetest Game has to be placed by a player, and I don't know a lot of people who want to test mods and blow up TNT at the same time. (Even then, TNT [uses voxelmanip](https://github.com/minetest/minetest_game/pull/862) now.)

**Comment by rubenwardy** [comment]
> I'm not sure why MTG would be laggier than minimal

It isn't laggier, is just takes longer to load.

**Comment by C1ffisme** [comment]
@rubenwardy Not all that much, though. (At least, on my computer.) Maybe we should time both?

**Comment by cheapie** [comment]
I like the idea of having it in the repo (for those of us that, say, want to test something), but I do agree that it doesn't make sense in a release package.

(basically, exactly what DonBatman said up there ^^^ somewhere)

**Comment by Dragonop** [comment]
@C1ffisme MT-game took 2 minutes to load for me, last time I made a mod, of course.

**Comment by C1ffisme** [comment]
@Dragonop Do you have the loading time for minimal for a comparison?

(It also might help to know any other mods you are using with your tested mod.)

**Comment by Dragonop** [comment]
@C1ffisme 15-25 seconds, depends on the mod. No mods, as I was [testing ](https://github.com/Dragonop/claycrafter)[my ](https://github.com/Dragonop/fan)[own](https://github.com/Dragonop/tools_obsidian).

**Comment by red-001** [comment]
Yeah minimal shouldn't ever be included in release builds. After all it's just a dev tool and not a very good one at that. If people need it they can use latest git or download it themselves.

**Comment by C1ffisme** [comment]
Question, if we remove minimal from builds and software store downloads, are we going to delete it from the player's system in the next version, or only remove it from builds and keep minimal if it's already installed on their system?

Also, as a compromise, we could add an option to hide minimal from view unless you turn on a setting. That would hide it from normal users, while giving modders the ability to use minimal. (The ability to hide subgames except in debug mode might also come in handy if one wants to make a 'testing ground'  or 'minimal' subgame to go along with their default one.)

**Comment by paramat** [comment]
:+1:

**Comment by C1ffisme** [comment]
While people have complained about Minetest Game having longer loading time, I feel like the answer to that is simple: Just download minimal from github if needed. Someone on the Minetest Forums can create a pinned post in Subgames or Mods that gives instructions to download minimal for people interested in speedy load times and helpful debug tools.

**Comment by TMcSquared** [comment]
I agree with some of the people who've spoken above, mimimal looks *very* sloppy to an outsider and might turn them away just because of the terrible textures(no offense to whoever did them). I mean, the first time I booted up Minetest, I accidentally did minimal because I thought it wouldn't lag my comp as much as the full-on game...lo and behold I saw basically a bunch of bad textures and nearly 0 game-play aspects. I didn't open MT for another 3-4 months after that xD

**Comment by paramat** [comment]
Yes as it is currently i feel it shouldn't be in release builds.

**Comment by TMcSquared** [comment]
Even if it was improved, it is still a developer testing tool, and not something that is meant for users to play on a regular basis.

**Comment by SmallJoker** [comment]
Closing in favour of #6987. This issue is older but the other has a larger activity.
