### ISSUE TITLE
How many devs play multiplayer?

### ISSUE THREAD

**Issue by 0-afflatus** [minetest/minetest#4011]
I'm seriously wondering how many devs and core contributors regularly play multiplayer mode in earnest. I'm asking this here because I want to gauge visibility of multiplayer issues. Occasionally playing multiplayer for testing purposes doesn't count.

Choices:
a) Regularly play on one or more multiplayer servers
b) Mostly play singleplayer
c) Multiplayer for testing purposes
d) I'm just a coder, I don't actually play the game very often.

I did consider a forum post, but I believe that the busiest devs would ignore that and I'd just get a lot of less helpful comments from regular players. This is a serious question and I'm prepared to explain my thinking further if it isn't obvious.

**Comment by C1ffisme** [comment]
To be fair, I don't spend any time at all on servers, be it Minetest or Minecraft anymore. Except for LAN servers.

To be fair, I'd probably go (reluctantly) with option d. Although I still take some occasional time to play around with this fun engine, that lets me do whatever I want.

![screenshot_20160213_104217](https://cloud.githubusercontent.com/assets/9893266/14681761/1e6427ca-06e8-11e6-8aba-90fe2d2c5f2e.png)

**Comment by est31** [comment]
Can you do this as forum poll or something? This is an issue tracker.

**Comment by C1ffisme** [comment]
@0-afflatus said:
> I did consider a forum post, but I believe that the busiest devs would ignore that

Although, I do agree with you, @est31. This is an issue tracker. And... *Sigh*, sometimes a feature request tracker.

**Comment by rubenwardy** [comment]
This issue would be better phrased to discuss multiplayer issue, rather than as a complaint against devs not playing multiplayer to see multiplayer issues.

**Comment by 0-afflatus** [comment]
It's not a complaint, it was a genuine question. Yes I can do it as a forum poll instead.

**Comment by paramat** [comment]
Ha just found this issue.
> I want to gauge visibility of multiplayer issues

There is an implication that those who do not regularly play on servers are blind to multiplayer issues, which is nonsense. Core devs deal constantly, intensely and in-depth with multiplayer issues raised by players, so are very aware of them, in fact, probably more aware than most players who are not doing this.
Contributors' PRs are reviewed by these core devs who are aware of multiplayer issues.

Core devs and major contributors play less on servers because they are coding more, almost everyone is working voluntarily so has limited time and energy.
