### ISSUE TITLE
Surface material issue in mgvalleys

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#4015]
![screenshot_20160405_164252](https://cloud.githubusercontent.com/assets/3686677/14706615/a761e858-07b7-11e6-939e-7cbc5697b531.png)

@duane-r 
Not a blocker but if it can be fixed for release that's good.

**Comment by duane-r** [comment]
I can't tell what I'm looking at here. What do those blocks actually read as? Can you post a seed/location?

**Comment by duane-r** [comment]
The green on the side of the blocks is being caused by the snow side texture:
https://github.com/minetest/minetest_game/blob/master/mods/default/textures/default_snow_side.png

**Comment by ExeterDad** [comment]
I believe he is referring to the dirt blocks on top of a snow layer.
![snow-side](https://cloud.githubusercontent.com/assets/9083807/14709066/a30b78de-079c-11e6-94e5-617d3f7c350c.png)

**Comment by paramat** [comment]
Sorry it was an old deleted world. This may be around y = 47 but not sure, it was in rough mountainous terrain.
Yes the bug is surface biome nodes below other dirt blocks.

**Comment by duane-r** [comment]
I haven't been able to duplicate this anywhere. It looks like a boundary issue, from what you're saying. I find lots of exposed stone at the chunk boundary, but that's about it.

I'm fairly sure the problem is not in the grass abm, given that it happened in so many blocks at once, but I can't see why generateBiomes would be dropping two surface blocks unless a second mapgen thread is rebuilding one of the chunks in a different way or there's a very tiny cave where air is being replaced by stone for structural support in the upper chunk after the cave puts down a surface block in the lower chunk. Maybe the removal of "node_max.Y + 1" in the cave method is an issue?

I hesitate to do anything without a repeatable case.

**Comment by DonBatman** [comment]
@duane-r I found the same thing. The pos and seed is in the image.
http://imgur.com/zErJTcU

**Comment by duane-r** [comment]
Well, I'm doing something wrong. This is my screenshot of the same place (I think).
http://duanerobertson.com/img/surface-material-problem-01.jpg

I'm using the latest code from master (as of last night), and no mods. I get no sand and no doubling. (And why would there be sand in one and not the other?) The terrain shape looks the same, so we've got the same noises.

Don, if you make another world with the same noise, does the problem come up consistently?

**Comment by DonBatman** [comment]
@duane-r This is from the latest master.
http://imgur.com/MXl3Aw5

**Comment by duane-r** [comment]
So you updated to the latest master and the doubling went away (but the odd sand is still there)? If that's so, do you remember the last time you pulled? Or did the problem just not carry over when you remade the world? (Or am I missing the problem again?)

**Comment by DonBatman** [comment]
I pulled yesterday. My first image was from a pull a couple days ago.
The latest build does not show the doubling.

**Comment by paramat** [comment]
Okay i think this was solved then by my recent commit to mgvalleys, thanks everyone for testing.

**Comment by paramat** [comment]
I think this was the code that placed biome surface nodes in tunnels misbehaving, somehting i fixed in all mapgens recently fe349d401d2d414f1ddc02c471c01d948bd89ee6
