### ISSUE TITLE
No "delete fav." button shown when initially opening client tab

### ISSUE THREAD

**Issue by est31** [minetest/minetest#4043]
If you start minetest and open the client tab, then a favourite entry will be selected but there will be no "delete fav." button. Similar if you return from a joined game

**Comment by est31** [comment]
**cc** @kilbith

**Comment by kilbith** [comment]
I know, that's not a bug but inherent formspec behavior. Visually the entry is "selected", but to be internally selected the entry have to be clicked once when you first open the mainmenu or return back to it.

**Comment by est31** [comment]
Then it seems you know how to fix it?

**Comment by kilbith** [comment]
No, it's formspec / irrlicht low-level of abstraction, and not something new.

**Comment by est31** [comment]
@kilbith the connect button is displayed as well, so what's the problem?

**Comment by kilbith** [comment]
The "Connect" button is always set by default. The "Del. Favorite" button shows up conditionally.

**Comment by est31** [comment]
@kilbith but you know which entry will be selected initially? So you just have to apply the condition on the initially selected entry in order to find out whether to display the "del. fav." button

**Comment by kilbith** [comment]
> but you know which entry will be selected initially?

No, as I said nothing is "selected" internally when the mainmenu first appears. It's purely virtual selection unless if you click once.

The other fields are saved because it's set in `minetest.conf`. The other datas for the entry index and the description are stored in the global table `gamedata` which is emptied when connecting to a server or at initial state.

You'll have to dig in low-level gears if it's really important for you or eventually I can use a workaround by setting `menu_favorite = boolean` in `minetest.conf` when an entry is selected.

**Comment by est31** [comment]
We could also revert #4007 as it has less bugs (like this one and #4030) and users don't like it either (see #4028).

**Comment by kilbith** [comment]
?! Don't be idiotic, you've absolutely no legitimate reasons for reverting my commit. Bugs you're referring are not related to my changes and #4030 was an omission for updating a file which is fixed now.

I got 3 approvals for my PR + some positive feedbacks from users. Users who dislike it are minority (from whose you seem to belong).

**Comment by est31** [comment]
Hmm existing code doesn't init the selected server either. So its not related to @kilbith 's commit. Sorry for having blamed you.

**Comment by est31** [comment]
I'll open a separate issue about it.
