### ISSUE TITLE
LBM's stop getting generated after a while

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#4050]
I'm having a weird issue with LBM's stopping to activate my action function.

My use case is mcimport: I want to update the map light for every block as it gets loaded. I've made an LBM that has `nodenames = {"air"}` and that does a map light update. 

This works only for about 2 minutes or so. After that, the LBM function never gets called anymore.

Obviously I'm generating an enormous amount of lbm's this way, and I know it's not the most efficient method (but I can't use mapgen callbacks as the terrain already _is_ generated).

**Comment by paramat** [comment]
Hopefully this is due to your use case and not happening in-game for replacing doors.

**Comment by sofar** [comment]
I've found a solution to my actual problem, however we should still investigate this.

**Comment by sofar** [comment]
reproduced by @Fixer-007, affecting door replacement. LBM's just stop after a while.

**Comment by est31** [comment]
Seeing that @sofar has the issue when running from mcimport, and @Fixer-007 has the issue with a locally saved server map, I have a theory for the cause of this bug.

Both these map creation methods have one thing in common: they both don't create full chunks. I think @sofar even has singlenode air mapgen for that, right?

So my theory is now that the mapgen runs at loadtime. Its enough that the mapgen loads the blocks and then does nothing with them: as long as the timestamp gets updated, the blocks are considered "new", so the lbm's wont run on them.

Well its hard to say whether its a bug with the local map saving/mcimport, the lbms, or the mapgen here. Probably if you fix one of the three the bug is fixed (provided my theory is correct).

* You could fix local map saving/mcimport to always save in full chunks : this would also remove the need for singlenode air mapgen
* You could do the lbm checks at mapgen block loading : This would also remove possible problems with LBM checks not being done in incomplete chunks that are incomplete out of some other reason
* You could fix the mapgen to not write into complete blocks in non full chunks anymore, and use other methods to find out when to do mud reflow, etc.

**Comment by Fixer-007** [comment]
My world for testing: [Just Test.zip](https://github.com/minetest/minetest_game/files/242731/Just.Test.zip)

**Comment by sofar** [comment]
```mcimport``` forces a singlenode mapgen for converted maps, to prevent mapgens from overwriting the landscape:

https://github.com/sofar/mcimport/blob/master/mcimport.py#L33

(note that the solution to fixing my light issue is right here as well)

**Comment by sofar** [comment]
@est31 would the problem go away if we mark the LBM introduction time as `0' instead of ~140000000  ?

**Comment by est31** [comment]
@sofar if the LBM introduction time is earlier, less blocks get their LBMs run, not more. And with 0, you have basically deactivated LBMs.

**Comment by sofar** [comment]
hmm, so forcing the LBM's to re-run is the only fix ..

**Comment by ShadowNinja** [comment]
Note that the mapgen has other issues with incomplete chunks -- specifically it calls Lua on_generated callbacks, causing, e.g., moretrees to greif the map as it's loaded.  The easiest way to fix this is to set chunksize=1.  I'm told this affects cavegen somehow, but that doesn't really matter in an imported map.

**Comment by sofar** [comment]
Not for 0.4.14. Arguably not a bug. @paramat, please remove milestone.

**Comment by Fixer-007** [comment]
Wait, how people gonna play on converted maps like NYC and other with all those broken doors?

**Comment by est31** [comment]
It is a bug.

**Comment by sofar** [comment]
Yes, I'm not claiming the issue is nonexistant. However, it affects only a limited amount of users.

I'll probably have mcimport set chunk_size = 1

**Comment by LazyJ** [comment]
Adding a bit to the conversation, the door conversion LBMs still stops after converting a few doors and leaves unknown nodes in my tests with Minetest engine 297546a when run on a backup copy of LinuxGaming. Changing the door conversion code to use AMBs gets the job done. I haven't checked how well the xpanes LBM conversion has worked yet.

**Comment by Fixer-007** [comment]
I have just test save, with mg_name = singlenode and chunksize=1. Conversion still stops after some time.

**Comment by MarkuBu** [comment]
I still think, LBM's should have a mode  where they run at every first load. 

Use case: I want to be able to spawn mobs only once, e.g. gobblins in a dungeon. They should only spawn once and live until they get killed

**Comment by est31** [comment]
@MarkuBu that's in fact the default: http://rubenwardy.com/minetest_modding_book/lua_api.html#lbm-loadingblockmodifier-definition-register_lbm

**Comment by MarkuBu** [comment]
@est31 sofar tells me something different 

https://github.com/minetest/minetest/issues/5214

**Comment by est31** [comment]
@MarkuBu ah it seems you want to run it after mapgen. That indeed won't work with LBMs. Better use register_on_generated as @sofar said in the thread.

**Comment by MarkuBu** [comment]
So I really should loop over 512000 nodes in Lua just to find same nodes? I know that Lua is fast, but to much of it could slow down everything

**Comment by est31** [comment]
@MarkuBu there are functions that do it in C++ and give you the results, but its better to ask for this in the forum or on IRC, this is an issue tracker.

**Comment by MarkuBu** [comment]
#5275

**Comment by Fixer-007** [comment]
This is a big bug for me, do not leave it alone.

**Comment by BluebirdGreycoat** [comment]
I can confirm that LBMs are fundamentally unreliable, and this bug will affect *every* code that uses LBMs; doors and xpanes not being the only victims.

A little more than a month ago, I got the idea to convert all the lava in my nether ocean to a new lava type, different from default lava (I wanted a different texture and different properties for it). First, I edited the Lua mapgen to place the new lava type when generating the ocean -- and that worked properly. All newly generate mapchunks used the new lava for the ocean layer. But of course, this still left all the chunks that had already been generated before this change, so I decided to try an LBM that would find all lava that was part of the nether ocean, and change it to the new lava type.

The short story is that this did *not* work. At first when flying around and reloading old chunks, the LBM would run and convert old lava to new lava, but after a while it would stop working, and old chunks would load, but the LBM would never run for them.

The even shorter story is that I had to set `run_at_every_load = true` and then search for *every* place players had gone in the nether (by grep'ing debug logs). Then I would have to fly around and regenerate the old chunks manually. Hours of work!

The takeaway is that modders can't rely on LBMs to properly convert their old nodes, because LBMs are, currently, broken. Not simply buggy, but (effectively) completely broken, since it is not doing what the whole purpose of its design is to do.

I'd like to add that I have not and do not use mcimport. My world is a standard setup, meaning I'm using the same `map_meta.txt` the server created (with the exception of changing the water level). It created the file with `chunksize = 5`.

**Comment by est31** [comment]
> I have not and do not use mcimport. My world is a standard setup, meaning I'm using the same map_meta.txt the server created (with the exception of changing the water level). It created the file with chunksize = 5.

@BluebirdGreycoat Interesting, this is something different from this bug then. No idea though what the cause could be.

**Comment by Fixer-007** [comment]
@est31 I think I've also observed this earlier on other world I had with proper meta file. Someone needs to look at this issues, I'm not comfy with it open.

**Comment by Fixer-007** [comment]
This bug still occurs as of 0.4.16-dev, bumping it up.
