### ISSUE TITLE
Chat improvements

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4143]
At first I was enthusiastic about new chat menu (via T key) that was reworked by Shadowninja. But after I played some large time with it, I can conclude it is not the best choice (at least for me), it hides player coordinates and it drop downs on the same text just for the sake of "drop down". F10 menu is nice though. And I see that other people share my view and dislike current T-chat dropdown thing.

In my opinion chat menu via T key should not drop down from above, it must be nonitrusive and small for typing text and to have some transperency (aka like in ---------).

**Comment by DonBatman** [comment]
I am not fond of the new chat. I like that T and F10 work together now. Some of the improvements are great. The only issue I have is  the layout.

Ideally I would like to see a few things changed. Make it so subgames can change layouts. 
This is what I would like to see;

1. The regular view of chat. Make it a hud element that has a height and width setting. Also a position setting so it can be put any where on the screen.

2. The T chat window. Same as with the regular view of chat.

3. The F10 window. The only change to this would be make the height configurable.

**Comment by nerzhul** [comment]
I think this console should be moved at a better place, in the left bottom corner like many RPG for example, or, at least, the chat

**Comment by DonBatman** [comment]
@nerhul I agree for some subgames but not others. That is why I would like to see it configurable.

**Comment by sofar** [comment]
If the chat window becomes a builtin HUD element, this would be solved entirely.

**Comment by nerzhul** [comment]
@DonBatman it's the final goal i think :)

**Comment by wilkgr76** [comment]
Workaround (for some servers): /area_pos1 gives the co-ordinates where pos1 is placed. 

Agreed, extremely annoying!

**Comment by Fixer-007** [comment]
also this https://github.com/minetest/minetest/issues/4650

**Comment by Fixer-007** [comment]
It is also kinda odd that it scroll downs over text, thats text over text... why? Just make it like in GTA SAMP, just below chat text output, example: https://i.imgur.com/w2aUy.jpg Simple and easy. Why overcomplicate so much? Leave F10 one as usual, but T needs rework.

**Comment by Fixer-007** [comment]
Here is a big reason why I hate it -> coordinates, that I need to read 1) when working with /deleteblocks /emergeblocks or worldedit (and here it is _very_ annoying) 2) when somebody asks me, I need to type it

**Comment by paramat** [comment]
At least move it to below debug info.

**Comment by DS-Minetest** [comment]
Can the debug info be moved below the chat dropdown?

**Comment by TumeniNodes** [comment]
I realize this is bumping a 2 year old issue, can this be added to milestones?
It does seem to be enough of an issue to address it, at least by 0.5.0

**Comment by paramat** [comment]
I agree it should be below F5 information if that is present.

I think the transparency is fine as it is, it needs to be almost opaque to make the text readable.

It can't be to the left of the hotbar because with a small game window there isn't enough width. If just above the hotbar and only on the left side it will be no less intrusive than at screen top and with less room for typing. I feel that lower-left is likely to be used for other purposes. Screen top is already used for F5 info and reading chat readout so that seems the suitable place for typing chat.

**Comment by tacotexmex** [comment]
It's understandable why one would want the chat to not cover the F5 information but simply offsetting it more towards the middle of the screen is a horrible solution since a by players commonly used feature (chat) has to make room for a developer's feature (F5 information) and not the other way around.

**Comment by paramat** [comment]
Keep in mind that players very often use F5 information.

**Comment by Zughy** [comment]
Closing in favour of #10372
