### ISSUE TITLE
Hotbar item selector continuous scroll

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest#4221]
It's as if the mouse wheel were being scrolled indefinitely and the wielditem is continuously changing.  Reverting 2060fd9cbe587d7e8ffe0cecdd67925f13a56c05 fixed it for me.

@est31 

Edit: I'm using Debian Sid.

**Comment by est31** [comment]
@everamzah most likely one of your laptop's devices registers as jostick... If you disable the `enable_joysticks` option, does the bug still occur?

**Comment by everamzah** [comment]
Thanks, that fixed it!  Much easier to switch a setting off than to revert a commit!  (That option is not in minetest.conf.example, however.)

**Comment by est31** [comment]
It'll be there the next time that file gets regenerated.

**Comment by est31** [comment]
Either way, you aren't the first user reporting this, and this bug should be fixed so that nobody is suprised by this regression. Think of people with your hardware first trying minetest, they'll think its horribly bugged.

So two ways to fix this:

1. somehow detect if the device is built in
2. change the default value of the setting to false

**Comment by everamzah** [comment]
I hadn't thought to plug my gamepad in to try to stop the scrolling.  In mednafen (multi-system emulator), the joystick is off by default, and you must manually assign each button before using it.
