### ISSUE TITLE
Force loading without activation

### ISSUE THREAD

**Issue by Hawk777** [minetest/minetest#4233]
Right now, we have the forceload_block API which makes the block in question active—stays in memory, simulates stuff, etc.. We also have the VoxelManipulator, which can load blocks but AFAICT does nothing to prevent them from unloading again later (from a brief inspection of the source code, it seems that VM does not refGrab the MapBlock, nor does it affect its usage timer).

Sometimes it would be nice to have an anchor-like block which would keep a MapBlock in memory but not active, to reduce CPU usage. Specifically, this would be helpful when building geographically distributed Digilines networks. Mapblocks containing only cabling and no interesting hardware need to be loaded into memory in order for such networks to work (so that minetest.get_node returns something other than ignored), but having kilometres worth of blocks active is completely unnecessary.

As far as I can tell there is currently no Lua-accessible API that accomplishes this goal.

**Comment by Aftermoth** [comment]
I have found that calling get_meta on an unloaded "ignore" node makes its real name, data and functions accessible without activating its timer. This is temporary, as player movement will re-unload it. You may find this behaviour well-suited to your needs provided "no interesting hardware" means some external function is handling the logic. Although, you can also call the node's functions explicitly if needed.

**Comment by Hawk777** [comment]
Understood, but I wanted to build something that would keep the mapblocks loaded, not just load them once. Obviously Digilines could easily be hacked to load unloaded mapblocks while tracing out networks, but my objective was to provide a separate mod with some sort of “half-anchor”, which would solve the problem for all mods that would otherwise see Ignore blocks, rather than hacking each mod individually.

**Comment by Aftermoth** [comment]
If I understand correctly, you want any mod, with no knowledge that your code exists, to always find a useable node when it looks.

The approach I would try is to write your own modified versions of minetest.get_node etc.
They would have the original names and use the builtin function, but also wake up any nodes that need it.

Actually keeping the mapblocks loaded doesn't seem to be functionally essential, more a side interest in efficiency. I think that would ultimately be addressed by refinements to the game's automatic cache management, rather than explicit control by mod developers. Perhaps some additional node properties would be added if deemed helpful, but that would probably be the extent of its Lua-side API.

**Comment by Hawk777** [comment]
You understand correctly but with the caveat that I mean “always find a usable node when it looks _if that node contains an anchor_”. Not just keep every block in the universe available.

Is overwriting those functions something that a mod could and/or should do?

**Comment by Aftermoth** [comment]
I assume you meant: if that _mapblock_ contains an anchor.
And, the anchor is a separate node you would provide (because the other nodes don't know how to be anchors themselves)
In that case, you will have to keep your own table of anchored mapblocks, and save it to a file, because you are using anchors that are not loaded and can't declare themselves when the game loads. The sethome mod is a good example.
Your get_node would check the table to decide how to behave. (BTW, remember to keep an anchor count per mapblock)

As to the question of overwriting existing functions, these are my thoughts:
Provided you don't edit the original lua files, you can't mess up the default installation.
Making your own versions of built in functions is not fundamentally different from writing private functions, except for the wider awareness needed in considering how other mods and functions may be affected. You can't really touch anything critical, any more than any other mod. You can't make worse errors than usual.
The main issues are:
Ensuring the changes don't break mods that don't know about them.
The possibility that more than one mod will redefine the same function, in which case only one can win, which is simply unfortunate; not all mods are compatible.
Whether you can actually reach the functionality you want from lua.

I still try to work within the provided behaviours just on principle, but it's no big deal to make them more cooperative when the need arises. And the more interesting ideas usually have to widen the options a bit to work at all.

**Comment by Hawk777** [comment]
OK, it sounds like this is something that is adequately implementable with existing code. I think we can forget the added API then. Thanks for the discussion!
