### ISSUE TITLE
Public-key encrypt, at-least the chat and login info.

### ISSUE THREAD

**Issue by o-jasper** [minetest/minetest#4242]
Might also do public-key-only/password-only/both logins.

Mot a chat program though, private chat can be shielded from other players, but at least defaultly admin should be able to see, and be able to give others permissions to listen in. Prefer also not really advertising it, just have it there to keep some more aspects of peoples lives from getting recorded.. This is not really tinfoil hat stuff in 2016. ("all cameras will be watched" is neither, unfortunately)

**Comment by Calinou** [comment]
A while ago, someone implemented GPG encryption for Minetest, but it was never merged in (Windows support is not great, for example). What about Android, too?

**Comment by est31** [comment]
Yeah, encryption is a nice idea, both encrypting the network connection to the server, and using public keys for login, but I think that encrypting the chats is not the right place for minetest.

In fact, with SRP we already use a form of public key login. Right now, a simple sha hash of the original hashing method is sent for compatibility reasons, you can disable that by flipping the `send_pre_v25_init` packet.

**Comment by rubenwardy** [comment]
You really shouldn't share any personal information on a server anyway, and minetest isn't designed as a private messenging program. I don't see this as worth the effort. Additionally, this could make the game illegal in countries with bad privacy laws (ie: banning encryption)

**Comment by cyisfor** [comment]
When adding GPG support, it ended up being protocol breaking since minetest doesn't ignore new unknown messages. But the real hard part was how coupled logins were to plaintext passwords. I had to rework logins entirely if I recall, since there was no pre-login state you could be in, where you can do limited things like send the server a public key for instance.

It couldn't make the game illegal, since for countries banning encryption, you could just compile with GPG disabled, but might be a problem for pre-built binaries. But I agree it isn't really worth the effort. It would have been worth the effort, if I could figure out how to use GPG for more than just a more secure way to login (like, economies, factions, shared builds, locked doors, etc) but that was even more complicated, since minetest deletes any way to send players files (like public keys, signatures, etc) right before starting the game.

**Comment by o-jasper** [comment]
To be honest not doing encryption feels like it is bowing to bullies here. Especially since i am essentially suggesting giving the admin the ability to allow listening in. Perhaps it can be made to look like https to make it stand out less. I read into this stuff before, but strangely the a library + API parts needed often is not very co-operative.

Ftr, can already be done "manually" with `ssh -L port:host:hostport`, and presumably `ssh` set up so it doesn't have a full shell, just the game to talk to. However, wouldn't really consider that a solution.

From what @cyisfor is saying it involves annoying couplings, that'd require more looking i guess. So the connection to clients isn't quite a clean replacable thing at the moment, i guess.

**Comment by cyisfor** [comment]
Trouble with HTTPS is not the encryption, but the ordered delivery. So if you hit a monster, but the previous packet got lost, the monster will murder you without getting hit while the server is waiting for the previous packet to timeout and retrying sending it. That's why games don't work well with TCP, because of the mandatory waiting and renegotiation to enforce the ordered delivery.

That's incidentally a problem with SSH too, which wouldn't work for minetest. But there are VPNs out there that work. "cjdns":/hyperboria/cjdns in particular works fine to encrypt minetest traffic pretty transparently.

**Comment by est31** [comment]
Its pretty easy to do network encryption for UDP: just do AES-GCM. It is tolerant to reorders, packet drops and stuff. Just somebody needs to actually implement it. If there is anybody interested, I might give some assistance for the general layout.

**Comment by rubenwardy** [comment]
not what Minetest is for
