### ISSUE TITLE
Ability to see mapchunk borders ingame

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4262]
... for debug and building big structures away from chunk borders, like long railways. Turnable in config.

**Comment by lisacvuk** [comment]
+1

**Comment by MarkuBu** [comment]
I made a mod that places nodes at chunk borders. But they will stay in the map.

This feature really would be nice

+1

**Comment by tobyplowy** [comment]
+1

**Comment by Rogier-5** [comment]
You could have a mod create entities with the required size and appearance (i.e. a cube of 16x16x16 or 80x80x80). Just set visual_scale to 16 or to 80. If you position them carefully, their borders match mapblocks or chunks. Set the send distance for entities to 5 blocks and you'd be able to see them from sufficiently far away.

**Comment by est31** [comment]
:-1: This is doable by a mod, e.g. like @Rogier-5 describes. There is no need for this to be in the engine.

**Comment by paramat** [comment]
I agree with est31.

**Comment by Rogier-5** [comment]
One argument against having this as a mod, but instead implementing it as a client-side display feature, would be that the mod and entities consume unnecessary resources on the server. Why should the server care, or even need to know how the client displays the world to the player ? Mapblock borders or chunk borders are a just a display grid, conceptually not much different from fog. Fog is not a server-side feature either.

**Comment by est31** [comment]
In fact a client side solution would require changing the network protocol. The server doesn't send the chunk size to the clients atm, at least afaik.

**Comment by Rogier-5** [comment]
> In fact a client side solution would require changing the network protocol.

The player could set the grid size in the client himself, and use `/set` to obtain the chunk size if he desires. This requires a small extension to allow querying settings from map_env.txt as well. E.g. `/set map.chunksize`. The default grid size would be 16x16x16, so no need to query the server for that.

Of course, the client could also issue `/set map.chunksize` at startup to obtain the chunk size if _really_ necessary...

@Fixer-007 BTW: as far as I can tell, the chunk size is completely irrelevant to the client. The way I understand it, once generated, all mapblocks are identical. I assume you meant mapblock borders (16x16x16) instead of chunk borders (5x5x5 mapblocks by default, i.e. 80x80x80)?

**Comment by MarkuBu** [comment]
the code for a wireframe or solid box is already there. Just need to be scaled

**Comment by Fixer-007** [comment]
>I assume you meant mapblock borders (16x16x16) instead of chunk borders

If i understand it correctly I wanted smallest unit of map data that gets loaded.

**Comment by Rogier-5** [comment]
> If i understand it correctly I wanted smallest unit of map data that gets loaded.

The naming is confusing, but the unit of loading is a mapblock: 16x16x16 nodes. A (map)node is the unit of digging, and most people call that a block instead. Except in the minetest source code, where it's called a mapnode...

The chunk is the unit of map _generation_, which is 5x5x5 mapblocks by default.

**Comment by paramat** [comment]
^ correct.
Closing for reasons given.
