### ISSUE TITLE
Items should be picked up If You Walk into them (not by hitting them)

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4272]
Now you have to sort of Hit the item to pick it up this is okay but if you have a lot of items scattered around this can be extremely annoying I speak from experience UHhhhhhh. also it's faster en more efficient to just walk into it and just pick it up (NOTE) there would be a timer on it so you don't instantly pick it up again maybe like Five Seconds?

**Comment by DonBatman** [comment]
If this is added I think it should be both ways and added to the api. I can see different types of games wanting different behavior.

**Comment by everamzah** [comment]
I believe this is a duplicate.  However, quickly, I want to note that item_drop mod is not a suitable solution here because it also handles node drops, and pulls items in from afar.  Simply automatically picking up items that lay at your feet is the only desired behavior I'd like to see implemented in core, and as an option with a default of false.

**Comment by Rogier-5** [comment]
For reference: this issue was previously submitted for minetest_game, and closed because it is an engine issue. See minetest/minetest_game#1051

**Comment by Wuzzy2** [comment]
There are also mods which implement this.
But implementing this in the engine would be better as this could be more efficient.

A common problem I saw in the mod that throwing away items is not easy. If you are unlucky, you will quickly collect the same item again, acctidentally. So there must be a way to prevent this.

There should be a minetest.conf setting to choose the behaviour. It should be a server-side setting since this affects gameplay.
In the settings it could also be configurable how far the “item magnet” attracts items, and maybe also how fast.

**Comment by paramat** [comment]
There may be a duplicate issue somewhere here.

**Comment by tenplus1** [comment]
It's more realistic punching an item to pick it up, but if you have a setting you could enable/disable then this would be an interesting addition.

**Comment by Rogier-5** [comment]
> There should be a minetest.conf setting to choose the behaviour. It should be a server-side setting since this affects gameplay.

Does it ?

If it is a client-side setting, the player can enable/disable it at will. And no(*) logic will be needed in the server. If there is also a shortcut key, then the effect on gameplay is minimal.

(*) some server help in determining whether an entity is a `__builtin:item` which can/should be picked up, or something else would be helpful.

Obviously, a client-side implementation will not allow entities flying towards the player. Instead, the effect will be identical to punching the entity.

**Comment by tobyplowy** [comment]
@tenplus1 yes hitting them seems more realistic, but it's a hassle like if tnt goes off you can spend like 5 minutes picking up the items it isn't fun it's more like a punishment to me, but yeah it should be a setting so everyone can choose what they want

**Comment by DonBatman** [comment]
I would rather it be server side. Subgames should decide which method is used. That way you can have different game play depending on the type of game it is.

**Comment by MarkuBu** [comment]
Server side would be better. If the admin decides that drop and pick is important for the gameplay the player shouldn't be able to change that

**Comment by t4im** [comment]
@kwolekr asked about this only a few days before this issue
http://irc.minetest.ru/minetest-dev/2016-07-01#i_4641314

**Comment by Rogier-5** [comment]
PR #4427 adds client-side auto-pickup

**Comment by tobyplowy** [comment]
@Rogier-5 thank you :D

**Comment by rubenwardy** [comment]
This is a thing that games should decide

**Comment by paramat** [comment]
^ I'm not keen on this feature, but it could be engine code controlled from a game.
