### ISSUE TITLE
Node Drop Behavior Does Not Match Documentation

### ISSUE THREAD

**Issue by duane-r** [minetest/minetest#4283]
In the text below, from lua_api.txt, "choose one item randomly from this list" does not occur. Instead, all items from the table are dropped when any are. I'd propose a fix, but I'm not sure whether the documentation or the code is correct.

```
drop = "",  -- Name of dropped node when dug. Default is the node itself.
-- Alternatively:
drop = {
	max_items = 1,  -- Maximum number of items to drop.
		items = { -- Choose max_items randomly from this list.
			{
				items = {"foo:bar", "baz:frob"},  -- Choose one item randomly from this list.
					rarity = 1,  -- Probability of getting is 1 / rarity.
			},
		},
},
```

**Comment by duane-r** [comment]
Disregard. User error.

**Comment by duane-r** [comment]
No, I was right the first time. It's not behaving as the documentation states.

**Comment by Rogier-5** [comment]
There may be other documentation settling the issue, but I'd say: fix the documentation. It is senseless to select randomly from the inner `items` list as well. That can also be achieved in the parent `items` list. What can't be achieved in the parent list, is to drop two items together, so that's what the inner list should be for.

**Comment by paramat** [comment]
I agree that docs should change, mods may be depending on current code behaviour.

**Comment by duane-r** [comment]
How about this?

https://github.com/minetest/minetest/pull/4309

**Comment by paramat** [comment]
#4309 is merged.
