### ISSUE TITLE
change init.lua to something different

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#4322]
Working at different mods can be annoying if you have different files from different mods open in your editor, if all files in the editor tab are called init.lua

It would be helpful if the initial file could be named different, like [foldername].lua or [modname].lua. 

To be compatible init.lua could still be supported. Search for inil.lua first, than for the other name

**Comment by est31** [comment]
:-1: That's rather an issue with your editor than with minetest. My editor has a treeview of all open files and init.lua files from different mods are under a different directory, so its easily observable.

Also, lots of other projects use predefined file names too (cmake, make, the rust cargo package manager, lots of webservers show index.html instead of a directory listing if there is index.html), so you'll run into the same issue for them as well.

**Comment by MarkuBu** [comment]
You are right, it is not a minetest issue. And my editor has a tree view too. But it is in a sidebar that I always hide. And I disagree to index.html, because in a project is normally only one file with that name
