### ISSUE TITLE
Custom player skins

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#4327]
![feature idea for minetest version 0 5 - custom player skins](https://cloud.githubusercontent.com/assets/13905392/16900176/e3ee7b62-4c25-11e6-9ca1-ec1180042891.png)

**Comment by C1ffisme** [comment]
> The title says:
> for Minetest version 0.5

You don't really need to add this. Features get added in there own time, not really on any specific schedule.

So, the way I see it, there are two solutions:

1. **Make a server for skins like Minecraft does.** Not a server for playing Minetest, the term server refers to a computer hosting data (The skins) for other computers to view. However, Minecraft's skin database is already pretty overloaded, with so many Minecraft players.

2. **Send the skin to the Minetest server you are joining, which is then sent to the clients.** This seems like a cleaner way to do it, since the data is not sitting on an overloaded server which only uses the piece of data that is your skin whenever you play Minetest. (Maybe only once or twice a week for some people, maybe a player is on hiatus from Minetest. Who knows?) It also means that we don't have people volunteering to host skin servers, which leads us to having to send our skin to a server 3 or 4 times.

But, the truth is, it seems like an awful lot of work either way for something that is only decorative. If you want to look different than other people, 3D armor is pretty helpful, and of course, we have 2 or 3 skins mods.

You mentioned skins with higher resolutions, although this isn't a good idea for someone who has a 1024x512 pixel skin. If a server is struggling to host just the 16x16 pixel textures it uses to play the game, then I don't think we want people to hog the bandwidth just because they want to look cooler. (Or because they want to troll.) Of course, maybe a setting when hosting a server to enable skins or not would be good for situations where loading textures is a struggle.

**Comment by DonBatman** [comment]
imho skins should be handled by a mod. If minetest handles skins then there needs to be a way to disable it. 

Example of why is I am working on a game that will have custom skins. Player can not change the skin because it will be set and will evolve as the player advances.

**Comment by C1ffisme** [comment]
Another thing, too, the subgame might not always be using the same player model as MTG. And what if I want different skins for different subgames? I might prefer a prehistoric-looking player in a prehistoric subgame, and I might prefer an alien-looking player or Sam in a Spacesuit if I'm using a futuristic subgame.

**Comment by benrob0329** [comment]
So then we really need client side Lua for this, so that mods can define a skin interface.

**Comment by nerzhul** [comment]
Player skins should be definitively server side as i can select nude skin on servers and show my **** to everybody...

**Comment by WSDguy2014** [comment]
@nerzhul If you join server with your nude skin loaded, it will be BANNED for using nude skin!

**Comment by nerzhul** [comment]
Maybe but i re-create another account and reconnect and let's go.

**Comment by WSDguy2014** [comment]
@nerzhul But, use different skin. Its a new rule to use: Don't use nude skin or you will be banned!

**Comment by rubenwardy** [comment]
Skins should be server side, but the ability to add new skins without restart would be good. You could then make a website to allow uploading of skins, and then a moderator could approve them

**Comment by C1ffisme** [comment]
@WSDguy2014 The point nerzhul is trying to drive is that people will try to use nude skins, and simply making the rule 'no nude skins' isn't going to do much about people who deliberately break the rules. Fortunately, in the small space that I can draw my skin in, it's hard to draw offensive or obscene things. (Unless high resolution skins are allowed. Also, it's hard, but not impossible.) This could be why Minecraft doesn't allow people to have high-definition skins. (At least, as far as I can know.)

@rubenwardy Who would be this _moderator_? If several thousand people wanted to update their skins, the moderator would have a lot of work to do.

**Comment by rubenwardy** [comment]
The moderator will be the server owner, just like currently. And it's unlikely that several thousand people would want to do tha

**Comment by C1ffisme** [comment]
@rubenwardy Ah, I was thinking of having one website to hold all skins. (Which has the advantage of showing your skin to you in singleplayer.) But I suppose this fixes the problem with having different skins for different subgames.

**Comment by 0-afflatus** [comment]
Apart from the ability to load new skins on the fly I don't see much that the engine needs to do here. I specifically want to be able to limit the choice of skins on my server to enhance the medieval / dark ages theme and it's already possible to have custom skins using player_textures. Even if there was a central skin server I probably wouldn't use it.

**Comment by Ferk** [comment]
Wasn't this already implemented?
I mean, the ability to load custom skins. Not the "reload on the fly" which is not really part of the original request.

**Comment by rubenwardy** [comment]
I'm leaning towards won't add on this, skins should be specified on a website. There could be a centralized but optional gravitar style interface for this

**Comment by benrob0329** [comment]
Perhaps skins could be placed on a media server, then people only need reconnect (or download the new file) to get the new skin.

**Comment by nerzhul** [comment]
Guys here is what i propose :Lua API to register new skins present in the mod , send the list to client and csm API to select one in the list sent from server.

**Comment by rubenwardy** [comment]
First two I agree with, I don't see the point of the last one

**Comment by nerzhul** [comment]
the last one permits server owner to present a list of skin a player can choose, CSM handle it directly with local formspecs, and we start to really use CSM instead of SSM for a such change :)

**Comment by octacian** [comment]
Maybe, but skins are one thing for which I am a firm believer in client-provided skins. Although I'd be happy for an official API for server-provided skins, the feature simply would not be complete without the ability for clients to provide their own skins. One could simply have a configuration option to disable client sending skins on the server-side.

And seriously, if you're worried about inappropriate skins, throughout the 2 years I played MC, I never *ever* saw someone using an inappropriate skin, unless you consider a skin that's all skin-colour with no detail inappropriate. For that matter, you can't create a particularly inappropriate skin with such a small canvas. The few inappropriate skins that did pop up, could easily be dealt with by simply banning the player, or providing an API to force a specific server-provided skin for a specific player.

I really hope this is considered, although I'll be happy with better skins, either way, no support for client-provided skins just wouldn't be right.

**Comment by rubenwardy** [comment]
> the last one permits server owner to present a list of skin a player can choose, CSM handle it directly with local formspecs, and we start to really use CSM instead of SSM for a such change :)

This seems like an abuse to me, just use SSM to select a skin. CSM should only be used for things that SSM can't do well.

**Comment by nerzhul** [comment]
formspec like this should just be client side, as it's not a pure server side feature, it's like the death formspec, minetest should really pass the step to be a pure overloaded server

**Comment by Ferk** [comment]
> * Server Lua API attribute to set player skin (permit to restore skin when player changed it and reconnects) or change it, may be useful in some cases.

Shouldn't this be doable already without any new Lua API? just using the player attributes API.

> * Server Lua API to register new skins present in the mod , send the list to client
> * Client Lua API to select one in the list sent from server, which sent the skin selected to server.

Why don't make this more generic to support sending a lua table in general? I can see this being useful for other things as well.

**Comment by nerzhul** [comment]
sending lua table in general ? i'm not for generic for a specific feature, sending lua table mean synchronize a lua table with client and it's not the CSM purpose as CSM is the MT javascript

**Comment by Ferk** [comment]
It doesn't need to be synchronous. Where you planning to implement the skin list synchronously? why is CSM ok to use in that case?

**Comment by nerzhul** [comment]
it's not synchronous and cannot be synchronous as it's client/server model. CSM can consult local table as a single consumer to list model and so something with them

**Comment by Ferk** [comment]
Maybe I misunderstood when you said "synchronize". Though I fail to see how it's any different when it's a list of skins and not a generic list. You are "synchronizing" the list of skins as well.

**Comment by nerzhul** [comment]
"synchronizing" a lua table permits server owners to alter inconditionnaly CSM states, it's not the purpose of CSM and SSM, mods channels will be there for a such case later (as a websocket like support)

**Comment by rubenwardy** [comment]
It's so much simpler just to keep things where they belong. If you do skin selection server side, all you'd need to do is add the ability to add new textures at run time (`minetest.update_texture_from_path()`). With the CSM API, as well as this you also have to add packets for sending lists and making selections.

**Comment by nerzhul** [comment]
you will never add texture at runtime for just one reason: the media cache is loaded on player loading. It cannot be altered later, there is no runtime addition for those textures.
Only one packet is sufficient to manage the skins list client see, see the player list packet it's a similar packet. I'm in favour having correct communication between server and client instead of bullshit generic interfaces uncontrolled.
Skin selection should be an engine flavour, maybe with a setting sent to client to permit seing the CSM formspec

**Comment by rubenwardy** [comment]
So if there's no runtime addition of textures, what even is the point of moving things client side? It doesn't solve any issues here at all

**Comment by Ferk** [comment]
> bullshit generic interfaces uncontrolled.

I'm glad the designer of HTTP and javascript's "XMLHttpRequest" did not think that way.
Otherwise HTTP would have been an overly complex protocol bloated with little verbs for very particular and use-case specific methods, very hard to maintain.

**Comment by nerzhul** [comment]
we are in a game we know our network packets. XMLHttpRequest is a browser generic interface because browser doesn't know apps

**Comment by Ferk** [comment]
> browser doesn't know apps

What do you mean? you can even run emulators on a browser (see retroarch web port), you can do a lot of stuff.

Obviously javascript  runs in a sandbox, as CSM should, imho. CSM should not be allowed to do cross-site scripting or any sort of manipulation in the client filesystem except maybe inside a protected directory, if at all. Otherwise no matter if you have generic methods or not, there will be ways to exploit it or bugs in any of the multiple use-case specific implementations you are gonna have to keep safe and check for exploits every time there's a change on any of them.

**Comment by nerzhul** [comment]
CSM will not do cross server request, i never said that, CSM in the future can publish over mod channels some messages (like a websocket event communication), but it's out of the current issue subject. for the current subject CSM can be useful to have a local formspec which look at client known skins an propose a default interface to select them, which can be overrided by mods (like inventory)

**Comment by Ferk** [comment]
I know CSM is not currently allowed to do cross-server, I was just saying that it should never be allowed to do it.
The point I was trying to make is that CSM should be more like javascript, which can indeed do generic communication with the server, and that's still safe as long as it's sandboxed, and very powerful.

**Comment by Ferk** [comment]
> we are in a game we know our network packets

Is MT engine really a game? I though the idea was to be a game engine. MTG is the game.

**Comment by nerzhul** [comment]
the idea to be a game engine only doesn't mean minetest should be an empty box.

**Comment by rubenwardy** [comment]
This would be an abuse, and wouldn't accomplish anything more than having a server side mod whilst making things a lot more complex. What exactly are the benefits as you see them of having skin selection client side?

**Comment by nerzhul** [comment]
no latency when selecting each skin (hello unified inventory button which take seconds when servers are a little bit loaded...), render model directly client side with a preview model, user experience in fact, it seems there is not many devs who understand smooth user experience.
having this client side permit to reduce lag due to formspec handling to zero (except order to really change the skin). Some users and devs should really understand about CSM and the possibility to increase user experience easily

**Comment by nerzhul** [comment]
@rubenwardy for the CSM formspec they already exists, for the preview (i don't have skills for doing it) we should have a new formspec element which loads the character model and permits to apply skins on it.
The improved user experience is not just prediction, but remove server interaction when not needed in formspec. For example, a skin preview rendered should not ask server what to do on button click

**Comment by paramat** [comment]
> no latency when selecting each skin

Server lag is usually very short, and is acceptable when selecting a skin.

> render model directly client side with a preview model

It would be more useful if the preview was a set of front / side / back images, otherwise you would need a rotatable 3D model as the preview, which is complex.

Seems best to keep it simple, right now we need simplicity with few active devs.

**Comment by nerzhul** [comment]
Dev activity is not valuable as i proposed to realize thé good and lightweight implémentation for client Server lag is not short especially for Real multiplayer servers you have generally 100 lag when not many activity and many more with active spread players

**Comment by rubenwardy** [comment]
:-1:

should be done using #3528 instead
