### ISSUE TITLE
Disable shaders by default

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4335]
**Update:** shader performance was improved a lot after merging of "superflous shaders" PR4800, I have about 10% fps penalty when enabled on my PC currently, on my old laptop with Intel HD - game is unplayable with shaders enabled.

**Old edited part**: RBA opposed this, but in my opinion shaders "on" by default is bad idea, default shader setting (basic shader on) puts too much price on fps. In paramat words, basic shader "adjusts day/night/artificial colours and brightness" (for example: adds smooth day and night transition).
Big fps penalty is a major pain and source of complaints about minetest horrible performance. Typical example, with default settings you can get 30 fps, but with shaders disabled 50-60 fps can be achieved easily.
In static scenes I measured (2 scenes in 0.4.13-dev long ago, and in 0.4.14-dev today) disabling shaders adds a lot of fps, in +40-90% range:
scene1 +53% , 34 -> 52 (fps)
scene2 +42% , 24 -> 34
scene3 +66% , 38 -> 63
scene4 +93% , 14 -> 27

My older topic about this: https://forum.minetest.net/viewtopic.php?f=6&t=13763
Pics with rendering comparisons (there are slight differences in rendering, like fog and brightness):
scene 3:
https://i.imgur.com/bEuAVVx.png (shaders off)
https://i.imgur.com/lw7FAzA.png (default settings, basic shader on)
scene 4:
https://i.imgur.com/09YIbb7.png  (shaders off)
https://i.imgur.com/pJgmKZV.png  (default settings, basic shader on)

Hardware: Core i3-2120, AMD/ATI Radeon HD6870, OpenGL 4.5, Windows 7 sp1, ATI Driver Crimson Ed 15.12 beta, resolution ~1280*978, 100 nodes fixed view
Please provide your benchmarks too. If you know critical bugs in "no shaders" mode please say so.

**Comment by paramat** [comment]
:+1:

**Comment by Bremaweb** [comment]
I always turn shaders off because I can hardly tell the difference in the way it works but I can tell a difference in performance.

**Comment by paramat** [comment]
@Fixer-007 would you be happy for this issue to be expanded to also be a request for tangent space to only be used when necessary? As that is the proper and eventual fix that is needed. If so please could you update the issue title?

**Comment by Fixer-007** [comment]
Yes, but is not RBA made them to be enabled when Normal maps and Bumpmapping are used? They are not enabled for basic shader, right? I can remember he talked about this somewhere.

**Comment by paramat** [comment]
I too thought tangent space was enabled only for bumpmaps, but in fact it is enabled whenever the basic 'shader' setting is true https://github.com/minetest/minetest/commit/bf884e37a06e0a8dd6c31789a69921f07ec5a9a9#diff-c2f90db5de8c33a259c27113939c63c5R1243

**Comment by benrob0329** [comment]
So, I think its not as black and white as it seems.

Shaders could very well improve performance on "modern" machines because it puts more load on the GPU (I think, Minetest tends to be weird).

**Comment by paramat** [comment]
Added milestone, either disabling or the proper fix should i feel be done for next release.

**Comment by paramat** [comment]
See #4336 for further discussion, that was closed because i deleted the PR due to conflicts, the first post has been copied here.
I feel that shaders should be disabled by default, or, the proper fix is made, before next release.

/////////////////////

Related: #3530 #3654
Discussion http://irc.minetest.ru/minetest-dev/2016-07-18#i_4653391

20:25 hmmmmmm it's really hard to decouple now
20:26 hmmmmmm the old code used to calculate tangents from a big set of if statements
20:26 hmmmmmm now i think it actually calculates it using the mathy calculating way
20:27 hmmmmmm you need to basically revert part of his normal mapping commit
20:28 paramat mtgame no longer uses normalmaps but custom texture packs and subgames do
20:28 hmmmmmm i'm sure we can fix it, it just takes some effort
20:28 hmmmmmm everybody's busy though :/

Ideally tangent space should only be used when a shader effect that requires it is enabled, such as normalmaps. However currently tangent space is used even with the basic node shader which doesn't require it.
The result is a huge unnecessary reduction in FPS in the default setup of basic nodes shader enabled. In some cases, for example in built-up areas of servers, FPS has halved, no wonder players complain of low FPS.
The basic nodes shader only makes very subtle changes to colouring and contrast (see screenshots in issue) and may affect the smoothness of day/night transition.
Eventually, once we only enable tangent space when it's needed, we can re-enable the basic nodes shader.

**Comment by Fixer-007** [comment]
Did testing on Pentium M 2.13GHz + Intel Integrated (Arrandale) with OpenGL 2.1, when basic shader enabled there is ~50-60% fps loss, like on my main machine. Results: https://i.imgur.com/g44trWl.png

**Comment by paramat** [comment]
MT is most likely to be used on a low power device, and low FPS makes a bad first impression, the lack of basic shader effects will not be missed because newbies won't be aware of them, so it's obvious basic shaders should be disabled by default.

**Comment by Fixer-007** [comment]
Since PR4530 is :coffin: I propose devs to decide on disabling shaders by default before release.

**Comment by Zeno-** [comment]
@paramat since there is no alternative ready (or even close to ready) this should be reconsidered. Did you make a PR?

**Comment by Calinou** [comment]
I've conducted some tests on my (powerful) hardware, here's the results.

## Hardware

**CPU:** Intel Core i7-6700K @ 4 GHz
**RAM:** 32 GB DDR4-2133 C15
**GPU:** NVIDIA GeForce GTX 1080 (8 GB)

## Software

**OS:** Xubuntu 16.10 (compositing enabled)
**Graphics driver:** NVIDIA 367.57
**Screen resolution:** 1920×1080 (borderless window)

## Results

View range is set to 200, mip-mapping and anisotropic filtering are enabled and 4× anti-aliasing is used.

**Shaders disabled:** 130 FPS looking ahead (view range 200), 500 FPS looking at sky
**Shaders enabled (no special features enabled):** 110 FPS looking ahead (view range 200), 450 FPS looking at sky
**Shaders enabled (everything enabled):** 80 FPS looking ahead, 400 FPS looking at sky

Disabling compositing gives more FPS when looking at the sky, but does not really change the FPS when looking ahead.

## Conclusion

There really is a substantial performance loss when using shaders, even more so when enabling special shader features. The lack of shaders doesn't really impact Minetest in its current state, so I think they can be disabled by default.

**Comment by sofar** [comment]
I have no issues with 1080p on a normal 2-year old desktop with integrated graphics, shaders enabled. 60fps with 250 viewing range. CPU is 2014 class Intel core with HD.

This isn't even an ati or nvidia card.

Just because there's a "performance loss" when using shaders, nobody has posted unplayable fps rates for hardware that can be considered "reasonable" as far as I can see.

(24fps is more than playable. Most console games are 24/30fps and while everyone bitches that PCs are better, customers continue to buy consoles by the millions and only a few vocal gamers on the internet complain loudly. Everyone is just playing mariokart at 30fps).

Low level android devices already have shaders disabled by default in most android builds.

So, let's put some definitions into this discussion:

GOAL(proposed): a REASONABLE computer should run minetest at a REASONABLE frame rate on a REASONABLE monitor. (with reasonable viewing range!)

DEFINITIONS (proposed):
a) a REASONABLE computer is defined as a less-than 5-yr old intel core i3 system with internal graphics, or anything newer. (This describes -probably- 90% of all PC's sold in the last 5 years)
(steam survey: ~90% of PCs have 2-or-more cores, 93% has 2gb or-more ram, 94% has 2.0GHz cpu speed or-more, fits closely with ivb or even snb-based i3 systems)
b) a REASONABLE frame rate is one that people would pay money for to play games on. Since people buy consoles to play games almost exclusively (ignoring streaming video for a second) and many console games are capped at 30fps(and this is widely known, so people must reasonably be OK with 30fps as the base frame rate), therefore, 30fps is by definition REASONABLE. last year, 40million consoles were sold worldwide. (source: https://www.statista.com/statistics/276768/global-unit-sales-of-video-game-consoles/)
c) a REASONABLE monitor is 1080p. while there are still many 720p monitors around and many laptops have 900p, for the purpose of todays standards 1080 is the bulk (source: steam hardware survey, 65% of monitors are 1080p or below. Also, all consoles support 1080p-or-less)
d) a REASONABLE viewing range is the default - 150 nodes.

@fixer's arrandale is 6+ years old (2010 class CPU) - so it's not reasonable (although it almost makes the 30fps). The machine listed at the top is close to what I consider the bottom line as it's a 5yr old core i3, and it "reasonably" makes the 30fps (it dips below only in certain complex scenes) goal.

Conclusion: none

It all depends if we can agree on the same definitions and standards.

If you look at your own machine and complain that minetest only makes 80fps on a geforce 1080 (sorry @calinou) then you are not helping at all. Moreover, @calinou's system runs at the reasonable frame rate as defined above with shaders enabled and with shaders disabled. So changing the default setting for shaders doesn't change the performance on his system all of a sudden from non-reasonable to reasonable.

I'm in favor of leaving the settings by default enabled. I want users to see the potential of minetest and it's engine, and know that we're interested in making it look better, cooler, prettier as well as do anything we can to not neuter the experience for them, even if that means sacrificing a 60-fps-flat performance number.

I'm not in favor of removing a whole bunch of settings by default just because a few vocal users are missing 20fps.

I'm also betting that 95% of PC's and Laptops sold this year easily make the reasonable performance number above. Even the crappy Best Buy ones.

remember: ANY performance discussion without DATA or GOALS is nonsense. There is some data in this discussion, but there is no accepted goal.

End rant. Please close this issue.

**Comment by paramat** [comment]
Zeno yes i'll make a PR. It would only be temporary until vertex tangents are only enabled when needed.
Calinou's results are less extreme than Fixer's, but we have to consider the effect on low power devices. My own results are a 20% drop in FPS (Intel core i5, integrated graphics).
My comment above explains why this is necessary and obvious.

**Comment by sofar** [comment]
There was another thread recently where "performance" was discussed without an agreed upon goal or meaningful data.

That is a seriously bad trend.

Please, when discussing performance, try to at least state a *goal* and make a data-driven decision.

**Comment by paramat** [comment]
The visual difference basic shaders make is extremely subtle, only the smoothness of day/night transition is significant, so this is not going to give a bad impression.
I expect new players will very quickly (probably on first play) find the settings page and will enable shaders, then if their FPS drops a lot at least they will be aware it is because of their settings.

**Comment by Fixer-007** [comment]
Arrandale has low performance, but Core i3 + ATI HD 6870 is not a low performance, but medium one that yes, gives me 60fps with v_range 240 in singleplayer in plain terrain, but if you enter any MP with some builds it gets to 30fps fast.

**Comment by Fixer-007** [comment]
And tests i did on notebook got v_range 35... because on default 100... it was 6-8 fps in singleplayer :coffin: Nobody in their minds will play minetest with that.

**Comment by paramat** [comment]
Hm, i've already done a PR for this and closed it due to overwhelming neutrality.
So i can't be bothered at the moment, someone else can make a PR, if so i will +1 it.

**Comment by Fixer-007** [comment]
30 fps was reasonable in 1999, not anymore. Lets not dumb down PC to consoles, 60fps is considered reasonable by today's gamers, don't insult them with this "30fps is fine because of console people" insanity, consoles can't provide better performance than that, they offer worse textures and have many limitations, PC gamers already fed up with -itty ports from consoles with ugly graphics and 30fps cap.

**Comment by Fixer-007** [comment]
I decided to delete my config, set fps_max 0 and went with default onto some multiplayer spawns, before measuring I've walked a bit in the northern part of spawn to load everything that can fit into v_range 100 and went back to spawn facing North, spawn results:
ESM (sky spawn): 146 fps / 1 player
ESM (old spawn): 22 fps / 2 players
Just Test 2: 30 fps / 32 players
Liberty Land (spawn): 42 fps / 12 players
Liberty Land (old): 50 fps / 12 players
Xanadu: 45 fps / 11 players
Cash World: 46 fps / 18 players
LinuxGaming.us: 19 fps / 1 player
Vanessa Basic-plus: 40 fps / 1 player
Craig server: 33 fps / 2 players
Amhi: 27 fps / 15 players
Van Dreambulder creative: 60 fps / 1 player
YGGDrasil : 50 fps / 1 player
Survival Server No 521 (sky spawn): 104 fps / 6 players
IhrFussel server: 33 fps / 3 players
Fun caves: 91 fps / 1 player
If I disable shaders, most of those results will double.

**Comment by paramat** [comment]
Are you comparing with 'basic shaders on, all specific shader options off'?

**Comment by Fixer-007** [comment]
@paramat I'm comparing on default config with fps unlocked. That means yes - it is basic shader only.

**Comment by paramat** [comment]
#4800 is merged, so less need to disable by default.
Tangent space still needs to be enabled only when needed.

**Comment by Fixer-007** [comment]
Yeah

**Comment by Fixer-007** [comment]
I believe "make tangent space to only be used when necessary" part was actually fixed by @RealBadAngel back then https://github.com/minetest/minetest/commit/7ea40e45b1bf893aa693c179cbe8612ede86faee

**Comment by numberZero** [comment]
Is that still a problem? Default shaders seem to have no impact on performance for me; while they seem to not change the look at all, things like waving water do change it, still not affecting the performance.

IMO the most important shader is tone mapping, but it is slow (I use #5057; that’s better than no tone mapping); by the way, it should probably be applied during post-processing.

P.S. My GPU is, according to `lspci`:
`VGA compatible controller: NVIDIA Corporation G98 [GeForce 8400 GS Rev. 2] (rev a1)`

**Comment by Fixer-007** [comment]
I still have 10% penalty on AMD/ATI and huge penalty on Intel HD 3000 (iirc).

**Comment by rubenwardy** [comment]
I get 60 FPS either way

```
Intel i5-5200U
Intel HD Graphics 5500
8GB RAM
```

**Comment by numberZero** [comment]
@rubenwardy Sure you have V-Sync enabled, it limits the FPS to the display refresh rate.
@Fixer-007 Oh well, just another powerless Intel GPU...
Seriously, there is no single parameter set appropriate for any computer. See #5024, that seems to be a better idea.

**Comment by Fixer-007** [comment]
Another way is @VanessaE, @MarkuBu idea to bring back auto-view-range code, that adjusts view range depending on your fps and was removed by https://github.com/minetest/minetest/pull/3749. However it had downsides and there was some opposition from some devs to bring it back.

**Comment by numberZero** [comment]
@Fixer-007 https://github.com/minetest/minetest/issues/5024#issuecomment-272443797

**Comment by paramat** [comment]
Auto view range is irrelevant, we still have manual view range control.

**Comment by Fixer-007** [comment]
Did one more test on Minetest 5.0.0-f41df431, automated straight fly over same terrain seed/position for 3 minutes.

Intel Core i5-3450 / Intel HD 2500 / 8GB DDR3 1600MHz / OpenGL 4 / Win 7

2018-08-09 - minetest - no shaders
Frames: 10260 - Time: 180000ms - Avg: 57.000 - Min: 37 - Max: 143

2018-08-09 - minetest - basic shader (first option ticked)
Frames: 8055 - Time: 180000ms - Avg: 44.750 - Min: 28 - Max: 129 (-22% worse avg)

2018-08-09 - minetest - all shaders
Frames: 3460 - Time: 180000ms - Avg: 19.222 - Min: 11 - Max: 59 (-66% worse avg)

Post your results too!

**Comment by rubenwardy** [comment]
:-1:  better to fix the problem than hide it

**Comment by paramat** [comment]
Well that is invalid logic :) if the problem was extreme and caused a bad impression to new players it would obviously be better to hide it temporarily while we try to fix it.
But of course now there is less performance penalty with basic shaders enabled so there's less reason to do this now, even i'm unsure.

**Comment by Fixer-007** [comment]
I would rather keep it a bit more open, so people post more benchmarks, to see how badly it affects various gpus/systems.

**Comment by paramat** [comment]
Yes good idea.

A result from me:
Looking over solid rainforest in mgflat, generate / send / optimise / view distances set to 256 nodes.
Smooth lighting on, opaque leaves, mipmap/filters off.
Shaders completely disabled 42 FPS.
Basic shaders on 38 FPS.
So 10% loss.

**Comment by numberZero** [comment]
Intel Core 2 Quad, nVidia GeForce 8400 GS, minetest 6cf48391c4125825e361868d28a8e736c6e23e0b (ade7a1cbcf7156ebddb12bd2ec2ea60818d72b19), MTG, view range of 100 nodes
![no_shaders](https://user-images.githubusercontent.com/7352626/43926236-4ff760b8-9c32-11e8-9448-53798977a20d.png)

* 39 FPS, 25 ms — no shaders
* 6 FPS, 146 ms — all shaders
* 30 FPS, 33 ms — basic shaders
* 30 FPS, 32 ms — basic shaders with unused sections removed (this means the optimizer does its job well)
* 32 FPS, 31 ms — basic shaders without color computation (−2 ms per frame)
* 35 FPS, 28 ms — basic shaders with per-vertex clarity computation (oops... −5 ms per frame)
* 37 FPS, 26 ms — per-vertex fog only, no color computation
* 42 FPS, 23 ms — minimal — only rendering, no fog, no fx (yet another 3 ms per frame)

As you can see, trivial shaders *improve* performance, on my system at least. But per-pixel fog kills it.

**Comment by paramat** [comment]
? I can't see shaders improving your performance over 'no shaders' anywhere here, only 'minimal' does.

**Comment by rubenwardy** [comment]
Basic shaders includes per-pixel fog

**Comment by sofar** [comment]
if you're actually serious about checking the performance, record your MT session and replay it with gltrace/frameretrace, and look at the FPS data from gltrace and not from MT. This way you can elminate the overhead of the MT engine and see how well the GPU performs, and you can even share the trace file with others so they can replay it as well. At least then we're talking about actual data, and not anecdotal evidence that is at best circumstantial.

**Comment by numberZero** [comment]
That’s why I posted frame draw time and not only FPS. On a flat map, I had about of 60 FPS but draw time of 6 ms only (that would be **160** FPS =).
@paramat “minimal” meant “minimal shaders” that I wrote specially to test performance. Note that there is no visual difference from fixed-function rendering with no fog (except of day/night transition not working):
![trivial_shaders](https://user-images.githubusercontent.com/7352626/43957212-bf909a20-9caf-11e8-854a-5264a14fca6e.png)

**Comment by Fixer-007** [comment]
https://github.com/minetest/minetest/pull/7633 Does not improve for me

**Comment by numberZero** [comment]
That means that’s not the bottleneck on your system. But note that you measure FPS only, which depends on many things other than rendering. `drawtime` is more reliable.

You can also try [my trivial shaders](https://gist.github.com/numberZero/8f27ec3a1071462551a62aee2b309eca).

**Comment by paramat** [comment]
I'm going to support this again, no longer neutral. The basic shaders make very little change to MT but lower FPS significantly.
:+1:

**Comment by paramat** [comment]
Any more core dev decisions on this? This is currently +1 -2.

**Comment by ClobberXD** [comment]
I agree with disabling default shaders, and also optimizing shaders on the long run. Sometimes (e.g. when in forests), I can barely touch 30 FPS even at `view_range == 50` with basic shaders enabled, on my potato PC (Intel Pentium G2030 w/ iGPU). Keep in mind that a huge portion of the MT userbase probably use similarly specced devices, so playing MT on devices like mine isn't an edge-case scenario - it's the norm.

**Comment by sofar** [comment]
3 years have passed. In the mean time, GPU's have consistently gone faster and faster. This PR is now 2^3 times less important than it was when it was opened.

Please spend more time looking at changes that benefit from GPU acceleration than to take the master switch to them away.

**Comment by paramat** [comment]
I am still unable to use basic shaders due to the performance hit, on a fairly nice computer: Intel Core i5 quadcore desktop. It's not as insignificant as some may think. Many people use whatever computer is available to them, often these do not have graphics cards.

Since default is basic shaders on, shader options off, there is no noticeable visual difference until the next day/night transition. But basic shaders disabled by default makes a significant FPS improvement, so disabled probably makes a better first impression.
