### ISSUE TITLE
Give servers the ability to ban android users using minetest.conf

### ISSUE THREAD

**Issue by nolsen42** [minetest/minetest#4367]
I think servers should have the ability to prohibit android users (since all they do is ping timeout) without the need of special mods. This will be great for servers with a lot of mods, since android users can't play those kind of servers. It will save the resources and keep the servers open for PC users with stable connections.

**Comment by paramat** [comment]
:+1:

**Comment by est31** [comment]
@paramat Low quality players is hardly an argument, if you want only cool players then dont announce on the serverlist, but manage it on an invite only basis. I mean its the equivalent of someone opening a public restaurant and then saying no gay couples and no blacks allowed here, which is NOT okay in my eyes.

**Comment by est31** [comment]
Also since when are we hostile against unofficial minetest clients? Most of minetest's users come from unofficial clients.

**Comment by paramat** [comment]
Seems reasonable to want to publicly announce but block android, for servers not suitable for low power devices.
You can't make an analogy with sexual and racial prejudice. I could make an analogy of not letting bicycles onto motorways. It's also for practical reasons. I think it's fine for a server owner to be prejudiced against smartphone clients, they are on average less mature and more problematic. It's not me who complains about them it's what i see expressed.
Nothing necessarily wrong with unofficial clients but they are likely to be lower quality clients or violating licenses.

**Comment by everamzah** [comment]
That's the setting I've always looked for and never found.  I have tried other methods, like strict_protocol_version_checking, but to no avail.

Why a server owner would want to restrict access based on platform isn't really the issue at hand.  What's important, I think, is that so many of us want to do it.

Personally, for what it's worth, I have come to expect and appreciate all connections.  I have some reservations about the server deciding what Minetest it will accept.  I might prefer the current `all or nothing' approach.

**Comment by est31** [comment]
I agree to technical argument though, most android devices are lower powered.

Maybe let the server send a minimum RAM info to the masterlist, and then the client filters out the servers with more required RAM than is available?

**Comment by twoelk** [comment]
build a clever designed entry lobby at spawn and let them perform stuff difficult to do with tiny touchscreens. Add vital hints in way too long texts. If they fail several times they will go elsewhere, if they practice untill they succeed they are probably the kind that you want

**Comment by everamzah** [comment]
>Also since when are we hostile against unofficial minetest multiplayer clients? Most of minetest's users come from unofficial clients.

**Comment by nolsen42** [comment]
I like @est31's idea on letting the server send a minimum RAM info to the masterlist, that should be tried.

**Comment by est31** [comment]
Yeah good idea, although that might be harder to find out clientside.

**Comment by Rogier-5** [comment]
I recall this being discussed earlier. Arbitrarily excluding users / clients will merely cause them to start pretending being another client.

> Maybe let the server send a minimum RAM info to the masterlist, and then the client filters out the servers with more required RAM than is available?

Good idea. There will also be less motivation for developers of unofficial clients to ignore this. Actually, they'd probably be motivated *not* to work around this. Provided that servers don't start lying about it or exaggerating it - on the contrary: they should be rather conservative... Else this issue will just remain an arms race, and the [first person to give up loses, at great cost to all parties involved](https://en.wikipedia.org/wiki/War_of_attrition_%28game%29).

I also think @twoelk's suggestion is great: using the forces of nature to work _for_ you, instead of trying to fight them.

**Comment by SmallJoker** [comment]
> Maybe let the server send a minimum RAM info to the masterlist, and then the client filters out the servers with more required RAM than is available?

@twoelk 's idea with creating difficult tasks is much more efficient here. There are phones with 4 GiB RAM, same as most of the computers out there. It's also possible to reduce the RAM usage by overwriting the server's high-resolution texture pack with a local 16px one.

**Comment by Rogier-5** [comment]
> Maybe let the server send a minimum RAM info to the masterlist, and then the client filters out the servers with more required RAM than is available?

There'd also have to be an incentive for unofficial client writers to implement this filtering...

> difficult tasks

This could easily be achieved using a mod: use `on_newplayer()` to teleport a new player to the location of the task, and if they complete the task, they are teleported back to spawn. Completing the task could also result in privs being granted, like `interact` for example.

**Comment by Wayward1** [comment]
I think the RAM request is the better alternative as well. Besides the users of higher-end tablets, what about the users of both Phoenix OS and Remix OS, as well as Android-x86 itself (which both are based on)? Using any of those, I can (and often do) effectively turn my touchscreen laptop into a 15.6-inch quad-core @2.7GHz Android tablet with 8GB RAM, on which the Minetest apk runs quite well.

**Comment by Ferk** [comment]
The idea of sorting by performance is good also when you want to avoid laggy servers, even when running on PC.

But I'm against it if it's gonna be misused by servers that want to reject android builds by artificially setting a high requirement. If the servers are gonna set the performance minimum arbitrarily I think it would stop being a good indicative. Also laggy servers might set up a lower requirement if they think they lose users because of that, cheating the system.

Considering how fast technology advances (and improvements in the engine?). I'm not sure it's worth it anyway. Maybe in 5-10 years everyone will have vulkan-powered mobile devices and very few people would be concerned about the performance speed of Minetest.

**Comment by nolsen42** [comment]
The problem with @twoelk's idea is they are still on, and they might not even do anything, but timeout, thus taking up CPU, RAM, bandwidth resources, and taking a user slot up.

**Comment by Rogier-5** [comment]
An option might be to detect the symptoms of underpowered clients on the side of the server, and deny access. For example: sending some kind of puzzle that requires a lot of memory to solve. If the client software can't solve it, or not fast enough, then don't allow login.

Question is: what category of puzzles would be suitable...

**Comment by est31** [comment]
@Rogier-5 essentially you want a form of bitcoin. It really just boils down to: send the client a 128 bit string, and let the client fuzz around the other 128 bit until the hash value is below some threshold.

But imo thats already a bit overkill. I mean the client can still fake stuff: the riddle can be solved on a separate computer (even by a cloud service the client developer supplies), then upload the result :)

**Comment by Ferk** [comment]
@nolsen42 from a mod you can automatically kick or ban a user, you can decide a time limit for the quest (long enough for the player to also read and check what he is doing, please), warn the player about it and then kick it if he didn't finish it fast enough.

I've seen some servers having this sort of tasks in the spawnpoint and if done well it's actually entertaining to go through them, so imho it's a good idea.

**Comment by Wuzzy2** [comment]
Stop the Android discrimination!
Android Lives Matter!
Against technical segregation!
:smile: 
---



But for real: Locking out players because they have the “wrong” operating system? Please, no. This is screaming for abuse. Server owners should not have a say force a particular client or OS on anybody. This is none of their business. This is like saying, a TV network gets to say with which kind of television I have to watch their programme.

The real problem is that the Android client is somewhat lacking behind feature-wise, but this is not solved by banning people, but by fixing the Android client. Also, I think it can be very frustrating to Android users if many servers are off-limits to them because the server operator says so. Especially since they are not just told “ERROR” but instead “You have been banned.” but they don't really know why. This is asking for trouble.

But hey, if it is OK to lock out Android users, then what is stopping us to also allow server operators to lock out Windows, Mac OS or GNU/Linux users? What could possibly go wrong? ;-)

> Maybe let the server send a minimum RAM info to the masterlist, and then the client filters out the servers with more required RAM than is available?

I think this is the right approach. Let the client decide.

**Comment by Fixer-007** [comment]
He does not necessary mean those players are bad, it is just they constantly time out, mindless in and out...

**Comment by paramat** [comment]
Also many Android users are users of nasty or illegal clones.
I actually support this ability, it may seem unpleasant but i see a lot of server admin who are fed up with smartphone users. There will always be plenty of servers not excluding Android.

**Comment by Wuzzy2** [comment]
> Also many Android users are users of nasty or illegal clones.

Then what's stopping you from also allowing to ban Windows, Mac OS and GNU/Linux users? Everyone could fork Minetest and create a “nasty or illegal” clone. I don't understand the bias against Android. This is not neccessarily a problem limited to Android.
Also, locking out *all* Android users because *some* of them might use “evil” clients is punishing a lot of “honest” Android users who use the official client and don't intend to cheat or something.

I doubt that banning any OS is helping to lock out “nasty” clients in the long run. This is just a lazy ad-hoc solution. Then they are just going to other OSes or just pretend to be another OS, which would probably be very easy to fake.

I am all-in when it comes to cheat prevention but this is the totally wrong approach. A cheat prevention which relies on the client to be honest does not work. Also, stop assumming that Android users = cheaters.

I don't really understand what is wrong with smartphone users.

> it may seem unpleasant but i see a lot of server admin who are fed up with smartphone users. There will always be plenty of servers not excluding Android.

You just contradicted yourself. If *many* server admins are fed up, then why would only few of them decide to exclude Android users?
My fear is that too many server operators decide to show Android users the door. If this happens, it effectively destroys the Android Minetest for multiplayer mode because the choice of “allowed” server is severely restricted. Which in turn might players to rage-quit Minetest.

This leaves me to wonder why there even is an Android build in the first place, if it is apparently so many people are against it, and apparently even some of the developers don't like it. o_O

Out of curiosity: What are the problems with Android users? Do they behave significantly different than other users? What are the problems with the Android build? Can you give me a list? I think the concrete issues with Android need to be known so that they can be fixed. Are there other serious differences from the desktop Minetest which impact quality?

**Comment by paramat** [comment]
Well, i'm not so sure now.

**Comment by NathanSalapat** [comment]
Wuzzy, I think the big problem isn't the Android users themselves so much, but the rogue, and dare I say, illegal Minetest apps, that are floating around on the various app stores.
It gets annoying with people are complaining about the ads they are seeing, or can't use fly, because the app they use has locked that to an in-app purchase.
Of course banning any Android users would be foolish, as we do have an official client.
I think server operators that are having problems with such players should just put a sign up in their spawn, or put a message on a formspec that they see when joining, that lets them know they are on a Minetest server, and can download the offical clients from minetest.net.

**Comment by Wuzzy2** [comment]
Yeah, plastering Minetest with ads all over the place is not good.
But frankly, such forks could even be totally legal. There's nothing in the license which would prevent anyone from forking Minetest only to plaster it with ads, as long as they abide to the rest of the license. Even in-app purchases would also not be illegal as such. And obeying the license would not at all be really difficult. I doubt that many of these apps actually obey the license. But even if they do, there would be nothing we could prevent anyone from including ads or in-app purchases in Minetest.
Although I very much hate such practices.

And I fully agree, more users need to be aware that o that they know they do not actually *have to* pay or do not actually *have to* live with the ads. As soon as the users learn about the “real” Minetest, I guess most of them will switch immediately.

**Comment by Zeno-** [comment]
:-1:

**Comment by paramat** [comment]
:-1:

**Comment by rubenwardy** [comment]
>  As soon as the users learn about the “real” Minetest, I guess most of them will switch immediately.

Except that the official app's UI/UX isn't great

**Comment by rubenwardy** [comment]
> Locking out players because they have the “wrong” operating system?

I'd like to point out the distinction between platform (mobile) and OS (windows/OS X/android) - they're not aiming to discriminate against an OS but rather mobile clients - Android of which being the main one

> What are the problems with Android users? Do they behave significantly different than other users? 

The perception is that Android clients make low quality players - walking around aimlessly, punching random things - and tend to be young children trying to date each other. I feel like this is an over generalisation but does hold _some_ truth, I personally think this is because of the ease of access of the Minetest ports, the marketing ability of the play store, and the popularity of mobile devices with younger people

-------

I think allowing admins to block devices is rather crude, and also technically difficult. It also doesn't solve the problem - you can still get immature players on PC clients. A better solution would be whitelisting - although you'd get less users

:-1: from me

**Comment by nolsen42** [comment]
How did we go from "hiding servers if the device isn't strong enough to support" to "stopping illegal clones"?

**Comment by paramat** [comment]
4 disapprovals for just banning due to Android.
