### ISSUE TITLE
Minimal password length

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4394]
Having setting to specify minimal password length for player account will be nice (with default as 8 symbols?). Anyone interested in this feature?

**Comment by NathanSalapat** [comment]
I think this would be a nice feature, keeps players from using just a single character which isn't very safe.

**Comment by lisacvuk** [comment]
As long as the server admins can turn it off, it's a plus.

**Comment by est31** [comment]
:-1:  you can't protect people from their own stupidity. A number limit won't help against `1234567` or similar totally insecure passwords. So the next step would be to implement a more sophisticated check, which compares the password with a list of known common passwords, but still the tiniest variation could make a change.

You can't really convince people to chose a strong password by enforcing it.

And the worst that could happen is that the people then chose to use their "secure" passwords they also use for online banking etc. Because then if the minetest password is known, attackers could compromise their really important accounts.

Of course, finding out the password is hard, and was made even harder with the srp upgrade, but note that the client still sends the old hash to the servers to maintain backwards compatibility. There are still servers that only support non srp protocols, so I don't want to disable pre srp init just yet (see this [survey](https://gist.github.com/est31/66602d589b225b27afd5)).

**Comment by est31** [comment]
Also we do nothing to make the hash computation harder. Its made much easier to brute force minetest passwords due to this.

**Comment by bendeutsch** [comment]
While it may be nice to strengthen the password security of users who want it, the issue here is forcing a minimal security level for everyone.

Every once in a while, the password database of a major online service is leaked. Inevitably, the most used password is "password" or similar, and cries go up left and right about the need to educate users to use strong passwords.

But the problem is not the stupidity of the users. The problem is that they are required to generate an account that they simply do not care about (say for registering hardware or similar). Hence they use a throwaway password for what is (for them) a throwaway account.

Please consider what it means for **you the server admin** if an account is hacked because the user chose a password of "12345" (like on their briefcase). Is the rest of your system at risk? Do you have to deal with too many account rescue requests? Are irate users constantly blaming you for allowing trivial passwords? If so (and I admit that I am not a server admin), then it makes sense to act. If not, I'd rather not make it harder than necessary for people to try out minetest.

(My suggestion if we want to do something like this: keep it generic. The user sends a password, and if it is not acceptable, the server sends a descriptive error message back, like "must contain at least 8 characters", "must contain a number and an upper-case letter", or "may not look like a phone number". Extra credit for adding a password strength indicator to the registration screen.)

**Comment by t4im** [comment]
> "must contain a number and an upper-case letter"

Minimal password length is one thing, but never enforce charset characteristics.
It just annoys people and actually helps the attackers by decreasing entropy.

> Password must be at least 2 and and at most 2 characters long.
> It must start with a lowercase letter and end on a number.
> It must contain at least a 'b' and a '4'."

If something enforces anything but minimal length, walk away!
(If something [enforces max length](https://cdn.arstechnica.net/wp-content/uploads/2012/09/hotmail-password.png),  run,
because they are saving your password in plain text.)

**Comment by beyondlimits** [comment]
Possible solution would be to provide an API method:

```
minetest.register_on_login(function(username, password)
	if username == '' then
		return false, 'You must provide an user name.'
	end
	
	-- TODO: check here whether user provided a gibberish name
	
	if string.len(password) < 6 then
		return false, 'Your password is too short (should be at least 6 characters).'
	end
	
	return true
end)
```

After that, standard authentication (registration of new user or password check) is performed.

**Comment by rubenwardy** [comment]
The plaintext password is not sent to the server during connection, and should not be

**Comment by beyondlimits** [comment]
@rubenwardy: yeah, good point. The hash is sent to the server, so it has no knowledge about the length of password nor any characteristics of it.

**Comment by est31** [comment]
If people are stupid, noone can help them. And if their account gets compromised, nothing much is lost, compared to online banking accounts or similar.

Just require your admins to have long passwords, and you trust them already as they are your admins, so if they say they have long passwords you can believe them.

**Comment by sofar** [comment]
It might just be a smart idea to do some education here. Minetest users are likely to be kids who are asked for the first time ever to make a password for something online, and so it's a good opportunity to teach them about password safety:

- don't share your password with others
- don't choose an easy to guess password
- don't use a password you've already used for another service
- do use numbers, upper case letters, symbols
- do use 8 or more characters

**Comment by Fixer-007** [comment]
Decided to close this for now, if someone wants to rise this topic again, feel free to reopen
