### ISSUE TITLE
Reduce list of default singleplayer privileges

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4413]
This issue came out of
https://forum.minetest.net/viewtopic.php?f=3&t=15301&p=228291

I suggest to reduce the list of default singleplayer privileges since currently those privileges are also irrevokable at the same time and MANY of the existing privileges can be used for cheating. In other words, in singleplayer, cheating is enabled by default.

I suggest to only grant the following privileges (nothing else) to singleplayer by default:
- `interact`
- `shout`
- `privs`

`interact` and `shout` should be obvious. `privs` because `/grant singleplayer all` is a common idiom which would get many players and modders angry if it would stop working by default. :D

The change itself is trivial, it just involves editing `builtin/privileges.lua` and adding `give_to_singleplayer=false`. The question is whether you agree with my list.

Implementing the change will not directly solve the problem I have with irrevokable privileges directly (see thread), but as it turned out many of the default singleplayer privileges we could do without anyway. So this would be a good first step IMO.

EDIT: I changed my proposal to grant 3 privileges and not granting everything else.

**Comment by Rogier-5** [comment]
A general remark regarding cheating: whether using a priv should be considered cheating, depends on how people play. Creative players would consider `give`, `teleport`, `server` etc. essential...

However, do I agree that less privileges could be granted to singleplayer by default, or to the admin user for that matter (especially as the name of the admin user for local  games automagically changes when you log in to a server, and then exit minetest). IMO the only irrevokable privilege should be `grant`.

Force-granted admin privileges can be especially annoying, as some mods have _intrusive_ behavior changes depending on a priv. I know of unified inventory which has the 'creative' priv, which modifies the behavior of the inventory so that recipies can no longer be looked up, but stacks of items are given instead. Combined with the fact that the admin user name for local games can change unexpectedly, this is a real nuisance.

So I'd suggest just ignoring `give_to_singleplayer` altogether, and also no longer granting any additional privs to the admin user either. Except for the `grant` priv. Optionally, a minetest.conf setting could be created that lists a number of additional privileges to be granted to singleplayer or to the admin user _on first login only_. So that such privileges can be revoked later.

**Comment by Wuzzy2** [comment]
Rogier-5: Well, singleplayer needs at least to have `interact` granted. ;-) Don't forget this.

Also note that **force-granted** privileges are a different issue, at least in princible.
It's a bummer that a default-granted privilege currently automatically is also a force-granted one. But that's a different issue.

**Comment by t4im** [comment]
No reason to not grant `server`. `/set` is already about as convenient as leaving the game and changing it in the advanced settings dialog.

But :+1: on not granting game related privs like `give`  or `teleport` by default.

**Comment by Rogier-5** [comment]
> Well, singleplayer needs at least to have `interact` granted

Granted on first login: yes (and that is normally achieved using `default_privs`), but force-granted: no.

You're right that those are separate things, however, singleplayer and admin have all those superfluous (?) privs *only* because they are force-granted. If you check auth.txt, singleplayer only has shout and interact (i.e. `default_privs` from minetest.conf...). And while singleplayer does not have some privs, including fly, fast and noclip force-granted, admin *does* - admin gets *all* privs force-granted...

There is no way that special privs can be granted (or denied) to singleplayer, except by modifying the code. Same for admin. So the way I interpret it, this issue is about privs that are force-granted to a particular role (admin or singleplayer), and that shouldn't be...

**Comment by Rogier-5** [comment]
@t4im: IMO, there's no reason to treat the `server` priv differently from any other priv. If the `grant` priv is force-granted, then any player can easily grant themselves the `server` priv. If they don't know how to do that, then they also wouldn't know how to use `/set` to their advantage to begin with...

Actually, I think the code should not treat *any* priv specially. Not even `grant`. Special treatment would have to be configured in minetest.conf. Currently there is `default_privs`. If `default_admin_privs` and `force_admin_privs` (for instance) are added, preferably with the capability to specify `all` *and* the capability to specify privs to be denied (e.g.: `default_admin_privs = all -rollback -someotherspecialpriv`), then anything is possible without the need to hard-code special handling of any priv.

If it is *really* desired, an exception could be made just for `grant`, which could always be force-granted to admin or singleplayer.

**Comment by Wuzzy2** [comment]
Hmm. We should agree on a list of privileges which should be granted by default. Otherwise, it's pointless to open a PR now.

So far you seem to agree mostly on my proposed list, you just don't seem to be sure about `server`. I still think it should be disabled because of `/set`.

**Comment by everamzah** [comment]
While I'm no fan of singleplayer mode, I nominate the `zoom' priv as a default priv for that named player.

**Comment by Fixer-007** [comment]
also I'm against time and zoom as default privs in singleplayer

**Comment by Wuzzy2** [comment]
Hmm. Maybe it is easier if we just say which privileges should be granted by default, with all other privileges off.

I propose to only enable `interact` and `shout` by default, with everything else disabled.

**Comment by Fixer-007** [comment]
yes, as on most multiplayer servers

**Comment by Wuzzy2** [comment]
Hmmm, maybe I'd add `grant` to the list as well, because `/grant singleplayer all` is a common and important idiom for modders (and cheaters :D).

**Comment by Wuzzy2** [comment]
Since there was no more feedback, I just went ahead and just posted a PR with the 3 privs I previously mentioned.
I also added `basic_privs` to the list because `basic_privs` is a logical subset of `privs`.

**Comment by paramat** [comment]
#4738 merged.
