### ISSUE TITLE
More control of chat in the API

### ISSUE THREAD

**Issue by Darknuju** [minetest/minetest#4438]
Hello, I apologize if this is either duplicate or violating some rule or guideline I did my best to read through everything before posting this to make sure no one had already mentioned it or anything.

I would like the API to give mods more control over chat as I would like to add prefixes to players and other such things, and I believe many other developers could use tools like this as well. Maybe you could be given the option to cancel a message when you intercept it and then could resend the message through the API with an added prefix or whatever the mod does to chat. I think this would be useful to myself and many other developers because as of now it seems I can only read messages when I intercept them and have no control over how the message is presented or even if it is presented at all.

Obviously this is not very important and for all I know it could not even be possible, but I thought I would make the request to see if it could be done.

Thanks

**Comment by lisacvuk** [comment]
Would be nice in order to allow players to color their chat messages.

**Comment by rubenwardy** [comment]
Already possible using minetest.register_on_chatmessage. just return true to cancel. See how ctf appends the team name to the chat

**Comment by lisacvuk** [comment]
Oh, thanks! /me is off to make a colored chat mod.

**Comment by Darknuju** [comment]
Oh thanks I didn't know that.

**Comment by Darknuju** [comment]
Does this work if you want to cancel other registered events?

**Comment by rubenwardy** [comment]
If by other registered events, you mean mods sending chat messages, then no - you'll need to override minetest.chat_send_all and minetest.chat_send_player

**Comment by Darknuju** [comment]
I mean other events such as hpchange can those also be canceled?

**Comment by rubenwardy** [comment]
You can return 0 in hpchange to cancel the HP change. See docs/lua_api.txt

**Comment by Darknuju** [comment]
Ah thanks so much!

**Comment by paramat** [comment]
@Darknuju Can we close this?

**Comment by HybridDog** [comment]
paramat, as far as l know, currently the chat is buggy, if you write something, it appears for you immediately, then it is sent to the server, after that the server sends it to every client except you, so
if you write something into chat you don't know if and when it arrived and
the order of the chat messages you can see can differ from the real order of the server,
e.g. a writes "hello", then approximately at the same time b writes "hi", due to this crude prediction, at the end to a it looks like this:
```
<a> hello
<b> hi
```
and b and other players which didn't chat see the real order:
```
<b> hi
<a> hello
```

This could be easily fixed by disabling this prediction and telling the player in another way that he/she pressed enter with a message.
Additionally without the prediction coloured chat can be added.

**Comment by paramat** [comment]
^ Surely this is unrelated to this issue?

**Comment by Darknuju** [comment]
I have everything I need if noone else needs to add anything.

(I also apologize for the late reply)
