### ISSUE TITLE
Do not generate unnecessary chunks

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#4440]
I watched the minp coordinates while map generation and I noticed that lots of unnecessary chunks are generated.

I would suggest to increase the default chunk size to 6. The minp.y is -48, which is deep enough for any structure that is visible from the surface. But generate chunks at -144 only if the player is below e.g. -16. If the player is below -16 stop generating chunks at +48

To sum up: two layers of mapchunks should be enough. Do not generate invisible chunks

The generation time per chunk may take longer, but much less chunks need to be generated 

To test my assumption I used my own cave mod. The default settings with chunksize 5 and no y limit generates 20 chunks and takes 11 seconds. 

Then I set chunk size to 6 and hard coded a limit of -64 to my cavegen. Only 12 chunks are generated and generation time is about 1-2 seconds faster

This even works with a chunk size of 5, but then I would suggest a limit of <0 instead of <-16 where lower chunks are generated

**Comment by paramat** [comment]
>  lots of unnecessary chunks are generated.

All chunks within the set generation range are generated, this keeps impassable "ignore" nodes more distant so there's less chance of colliding with them. For many mods and features it's very useful to have a fairly large space around the player generated so that mods can act on that, it is also essential to have a satisfying amount of world visible around the player.

> I would suggest to increase the default chunk size to 6

We cant do this. Although some mods can cope with alternate chunk sizes many cannot.
Chunksize has been 5 for so long we are accustomed to it and the positions of chunk borders.
Larger chunks are a problem for lua mapgen mods which will then cause significantly longer lua lag when generating a chunk. Perlin noise per chunk will become much heavier and slower, especially 3D noise.
The person who made chunksize configurable actually regrets doing so because it causes so many problems when changing it.

> Do not generate invisible chunks

It's impossible to know if a chunk will be air-only until it's generated.

> This even works with a chunk size of 5, but then I would suggest a limit of <0 instead of <-16 where lower chunks are generated

Underground needs to be generated, for example imagine a mod creates large excavations in the ground, you look down and can only see 32 nodes rendered, it will look really bad.

:-1:

**Comment by MarkuBu** [comment]
@paramat you missunderstand me. Chunks at the height of the player should always been generated. Also the underground of the current chunk.

But if the player walks on the surface he will never see the chunk that is below his current chunk. This one should be generated if the player goes below 0 or -16

**Comment by SmallJoker** [comment]
You can't simply check for the Y axis. The realm mods aren't around the Y = 0 level. I don't know how the chunks are sent when you press full range but I assume the code for this "chunks in sight" check would be far too complex. Get more space if the map grows too fast.

**Comment by paramat** [comment]
> But if the player walks on the surface he will never see the chunk that is below his current chunk. This one should be generated if the player goes below 0 or -16

I think i understand, with chunksize 5, you suggest not generating anything below y = -32 if the player is above y = 0?
As i wrote, if a mapgen or mod creates a giant abyss a player at y = 1 will only see down to y = -32, which is not far enough to create an acceptable view, many use a view range of 100-200 nodes.
Also a deep seabed will not appear if it dips below y = -32 (which it does often).
In a floatland realm there is visible structure reaching downwards.

In every direction chunks need to be generated out to a satisfying view distance, the default is 6 * 16 = 96 nodes which is reasonable, roughly 1.5 chunks. If a player is roughly in the middle of a chunk then all surrounding chunks are generated, 26 of them.

You can use 'max_block_generate_distance' to choose how far to generate chunks.

**Comment by MarkuBu** [comment]
> I think i understand, with chunksize 5, you suggest not generating anything below y = -32 if the player is above y = 0?

correct

> As i wrote, if a mapgen or mod creates a giant abyss a player at y = 1 will only see down to y = -32, which is not far enough to create an acceptable view, many use a view range of 100-200 nodes.

If so, than the mod should be able to activate chunk generation. 

> Also a deep seabed will not appear if it dips below y = -32 (which it does often).

I agree. That's why I suggest to set the chunk size to 6 because I never saw something generated below -48 at default mapgens

> This would often create an upward view limited to 64 nodes, too short.
What does a player see if he is that deep? If he digs down the chunk is already generated. I never had a situation where a player can walk below -16 to a new chunk and look up

But anyway, I closed this issue.
