### ISSUE TITLE
Encoding issues with some window managers

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#4447]
![bildschirmfoto von 2016-08-16 20-49-31](https://cloud.githubusercontent.com/assets/1377943/17711677/08c28822-63f3-11e6-8f8e-f11ba8886c43.png)

Should be Hauptmenü not HauptmenÃ¼.

**Comment by Wuzzy2** [comment]
Sorry, I can't repeoduce this on my GNU/Linux machine. Neither in dev nor 0.4.14.

**Comment by kahrl** [comment]
Can't reproduce this either on my Gentoo Linux box (using XFCE and the de_DE.utf8 locale).

Ã¼ comes from taking ü (U+00FC LATIN SMALL LETTER U WITH DIAERESIS), encoding it as utf-8 and decoding the result as if it were iso-8859-1 (latin1). This can be checked with
```
$ python -c "print(u'\u00fc'.encode('utf8').decode('iso-8859-1'))"
Ã¼
```
Minetest uses either utf8 or wide strings for most things internally, so @lightonflux it seems that your system is expecting window titles to be passed in iso-8859-1 but Minetest passes it as utf-8. Perhaps you have an iso-8859-1/latin1 locale set? (You can see the current locale by typing the command `locale`.)

**Comment by est31** [comment]
Minetest passes them as wstring:

1. Minetest calls Irrlicht in [src/client/clientlauncher.cpp](https://github.com/minetest/minetest/blob/986d70ccecb09fcbd247758643a4d623c9c4e1b8/src/client/clientlauncher.cpp#L192) with a wstring as window caption.
2. [Irrlicht then](https://sourceforge.net/p/irrlicht/code/HEAD/tree/trunk/source/Irrlicht/CIrrDeviceLinux.cpp#l1100) calls [XwcTextListToTextProperty](http://linux.die.net/man/3/xwctextlisttotextproperty) and [XSetWMName](https://www.x.org/archive/X11R7.5/doc/man/man3/XGetWMName.3.html) to set the caption on the window.

Its a bit confusing, as the most likely candidate would be `wgettext` which for example could instead of reading the .po file (which is apparently utf-8 encoded) with utf-8, reads it with the iso format. But that doesn't seem to be the cause as wgettext is used all over the place and below the special chars seem to work again.

**Comment by lightonflux** [comment]
My locale is `LANG=de_DE.utf8` and the window manager is mutter 3.20.3.

**Comment by lightonflux** [comment]
My locale is `LANG=de_DE.utf8` and the window manager is mutter 3.20.3. Also tested with i3 4.12 and same problem there (with the questionmark in a rhombus symbol). So it is not a problem with the window manager but something else. 

> Is the window title the only place where umlauts fail for you?

Yes as far as i can tell.

Other applications with umlauts are not effected.

**Comment by rubenwardy** [comment]
Please bump if you can reproduce
