### ISSUE TITLE
Limit the message size one can send in chat (while excluding commands)

### ISSUE THREAD

**Issue by nolsen42** [minetest/minetest#4515]
I just noticed that there is no message limit on one can send, which means one could copy (or type) a message long enough to cover the other players' screen.

Here is a good example: https://nolsen.xyz/paste/?6b1ea014e0906340#HRSZ/XAiuZmxlZDHv0cJCEJlLSt7LCQbShAdgIwLJHw=

**Comment by NathanSalapat** [comment]
I'm sure there is a mod that can limit the length, but it would be nice to have a setting exist in Minetest_game that gives a limit of how long a message can be before it gets truncated or the player gets a message about it being too long.

**Comment by SmallJoker** [comment]
Lua spam prevention script written a month ago: http://pastebin.com/i3VX5Qjq

**Comment by est31** [comment]
Yeah there should be a setting imo that controls the length, with 0 meaning that its turned off.

**Comment by est31** [comment]
Or well, its doable in a mod, so probably not that much important.

**Comment by SmallJoker** [comment]
A character limit would be only helpful to prevent from high draw times in the client, not to reduce spam.
Maybe let's limit it to 500 characters by default, that's already fine for all cases.

**Comment by nolsen42** [comment]
But would 500 characters fill small screens like android?
(I never used minetest on android, so I don't know how their chat system works)

**Comment by raymoo** [comment]
You could be roleplaying or something, with a large minimum word count. I don't know if people would actually use Minetest for that, but I don't think it should be ruled out.

**Comment by t4im** [comment]
In-game explanations of game mechanics can sometimes span 1-2 paragraphs, too.
But IRC also only allows 510+CRLF (including command), so @SmallJoker's suggestion seems like a reasonable size, that people are used to

Also if it is being truncated, the sender still needs to **know** about it, which might need a client change to truncate the displayed text on the senderside as well, or the sender will not know that information was lost.

**Comment by est31** [comment]
Note that a possible implementation should probably limit the /msg command too, otherwise you can just msg someone with spam, and people who hack their clients can use that to bypass the spam barrier.

**Comment by Wuzzy2** [comment]
I support this idea. It is way for everyone too easy to destroy the chat like this, just annoying the hell out of everyone. It is very frustrating when this happens.

> Or well, its doable in a mod, so probably not that much important.

I disagree. IMO this is important, because one rogue player can destroy the entire chat for everyone quite easily. There is no good reason for allowing absurdly long chat message (e.g. > 500 characters) as those are almost always just there to disrupt the chat.

If we do it the “mod” way, this means that by default, chat can still be easily destroyed by rogue players. This is a feature that no sane person would *not* want to have. What about putting it into `builtin` if you are against putting it into the engine?

I too want this feature, plus a sane default. Yes, it won't prevent *all* spam, but it will prevent a very specific and highly annoying type of spam, so that's still a plus.

**Comment by rubenwardy** [comment]
I feel like this is so important it should be an engine feature. The client should also stop the player from writing more at a certain point, to give feedback that long messages are not allowed. Note that it should also be enforced on the server

Rate limiting is also important

**Comment by nolsen42** [comment]
Don't forget about relaying messages to IRC, if your message is long enough, you can actually make the bot disconnect from Max SendQ/RecQ, or Excess Flood.

**Comment by raymoo** [comment]
> Don't forget about relaying messages to IRC, if your message is long enough, you can actually make the bot disconnect from Max SendQ/RecQ, or Excess Flood.

I think this particular consideration is a concern for the IRC mod, since IRC is not part of Minetest and Minetest isn't particularly intended to be compatible with IRC.

**Comment by est31** [comment]
Closed by d4c76258e37337ea585cf24d8e05b50a30fa307d (#4571)
