### ISSUE TITLE
whene moving fast , the game start to make noises on screen

### ISSUE THREAD

**Issue by masrourmouad** [minetest/minetest#4563]
when moving fast , the game start to make noises on screen, but when i move normally it does not do it

![screenshot at 2016-10-02 00 26 13](https://cloud.githubusercontent.com/assets/403487/19017589/2a497556-8837-11e6-8879-5e7d42052b00.png)

**Comment by paramat** [comment]
By 'noises on screen' do you mean visual distortion? I can't see anything wrong in the image.

**Comment by rubenwardy** [comment]
Sounds like the noise integrated graphics makes when it's overworking

**Comment by masrourmouad** [comment]
yes , visual noise i play other games but they do not make visual noise, by the way you should zoom the picture to see

**Comment by paramat** [comment]
Ok it does look a little noisy, i had assumed that was due to having mip-mapping turned off.

**Comment by t4im** [comment]
How much anti-aliasing do you have set?

**Comment by masrourmouad** [comment]
i tries all anti-aliasing settings but it does not change

**Comment by paramat** [comment]
Why closed?

**Comment by Fixer-007** [comment]
I don't see any noise, you mean moir? grainy picture? Turn on "Mip mapping" to make it better.

**Comment by paramat** [comment]
Roof and leaves in top half of screen.

**Comment by masrourmouad** [comment]
i Turn on Mip mapping it make it less grainy but it became laggier , by the thanks paramat for reopening the issue

**Comment by Fixer-007** [comment]
top trees have some fog added, thats why they are more bright.

**Comment by masrourmouad** [comment]
sorry but its way laggier, with Mip-mapping its worst

**Comment by paramat** [comment]
By 'top trees' i think that refers to the trees at higher altitude, closer to the camera.
In both screenshots leaves look different in one half of the image, they look noisier in the top half.

**Comment by kahrl** [comment]
With no mipmapping, leaves (and some other textures) will be "noisy" / show moire patterns. This is not a bug, it's to be expected since one of the main purposes of mipmaps is to reduce such patterns.

With mipmapping enabled and otherwise standard settings, I can confirm that leaves do indeed get darker with increasing distance. This happens because mipmapping averages the color values of neighboring pixels, even of pixels that are fully transparent. The color values of transparent pixels tend to be weird (or just black), since PNG optimizers usually discard them.

Try setting `texture_clean_transparent = true` in minetest.conf. This applies a filter to every loaded texture that fills in transparent pixels with more useful color values. Maybe this setting should default to true? I don't know how expensive it is.

**Comment by masrourmouad** [comment]
i tried `texture_clean_transparent = true` its better but it did no  fix the problem.

**Comment by paramat** [comment]
By the way mip-mapping is known to increase performance.

**Comment by masrourmouad** [comment]
thank you Paramat for all your work , i think its time to close this issue , thank you all for you help.

**Comment by paramat** [comment]
It doesn't have to be closed, it's a valid issue and maybe someone else will confirm it.

**Comment by masrourmouad** [comment]
thank you for all Paramat.
