### ISSUE TITLE
[mapgen] ice should swim on water

### ISSUE THREAD

**Issue by DS-Minetest** [minetest/minetest#4575]
in mapgen v7 (and i think in others, too) the ice is generated below the water surface:
![screenshot](http://i.imgur.com/5uKVDt9.png)
but density of ice is lower than the one of water, so it should swim, like it does in real life

(i think the mapgen is in Minetest engine, correct me if I'm false, then this issue shouldn't be here)

**Comment by paramat** [comment]
The biome definitions are in MTGame.
You're correct about how some ice should project above for icebergs.
The problem is that ice can only be formed where water is. It could be added on top is as dust, but that has it's own problems and is not possible. It could be added as a chance 1 decoration but that's slow and i don't think it's important enough to do.
If you want you can open an issue in MTGame but i'm not sure it's worth it.

**Comment by DS-Minetest** [comment]
ok, i think, i wont make another issue about it
