### ISSUE TITLE
Optionally control connected nodebox with param2.

### ISSUE THREAD

**Issue by pithydon** [minetest/minetest#4645]
Could be used with {connects_to = "param2"} and/or {paramtype2 = "connected"}.

**Comment by sofar** [comment]
- could be possible but there's no path to backwards compatibility (existing param2 values in the world now would mean something else?)
- because of that, it would force mods to handle param2, which entirely removes the benefit of the current implementation: That is currently entirely drawn client-side without mod node updates.

**Comment by pithydon** [comment]
I agree the old way should not be broken.
I was thinking this should be optional to moders.
Should have made that clear in the first place :p

**Comment by pithydon** [comment]
Maybe this could be implemented independently of connected nodebox, using paramtype2 = "nodebox".

param2 of 0 would show box0

param2 of 1 would show box1

param2 of 2 would show box2

fixed is always shown
