### ISSUE TITLE
Torch dissapears at placement occasionally

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4762]
In recent times I've started to notice problems with torch placement in singleplayer, it lights up for quick moment and disappears. To reproduce enable creative, take torch and go fly with fast underground in a big cave putting torches occasionally on the fly without stopping (after some tries you will see it, try testing on fresh caves). I have impression that it appeared recently, but my memory can be faulty. Bug is reproducible, it happens before " Improved lighting " oct27/2016 for sure, will check older or bisect it.

Was seen on builds c793700 and 0d740c5 and 9d3d43f (0.4.14 stable) and 0.4.13 stable and probably beyond.

Example: here I've tried to place torch just below crosshair in mgvalleys huge caves, it lighted area up, disappeared, and glitched lighting some more.
![missing torch](https://cloud.githubusercontent.com/assets/16494741/20160604/ec931860-a6f0-11e6-8cc6-96ccb1568a09.png)
another torch disappeared and leave this behind (torch was placed to right of crosshair in dark zone):
![aazq2nc](https://cloud.githubusercontent.com/assets/16494741/20160681/90acde2c-a6f1-11e6-81e7-4883987f0134.png)

:tired_face: :fire: :fire: :fire:

**Comment by sfan5** [comment]
does this happen with `disable_anticheat = true`?

**Comment by Fixer-007** [comment]
Tried with " disable_anticheat = true " - bug still happens.

**Comment by sofar** [comment]
placement too far from character?

**Comment by Fixer-007** [comment]
not always, sometimes in front of me

**Comment by asl97** [comment]
I have a theory, the block was unloaded by the server when the player tries to place the torch.
I reproduce it by setting `server_unload_unused_data_timeout` to a very low value (ie:1).

there are three videos file in the attachment, a 'synced' side by side of minetest and terminal running and an unedited version of each of them.
[minetest-#4762.zip](https://github.com/minetest/minetest/files/592352/minetest-.4762.zip)
ps: Feel free to reupload the attached videos somewhere it could be view online.

**Comment by Fixer-007** [comment]
It does look very similar to me (in action).

**Comment by numberZero** [comment]
Well, I see that all the time on one laggy server. The problem is obvious there: the client and the server go out of sync in their thoughts of whether there is a torch. Perhaps the server have the block without the torch in the send queue when it receives placement command, and sends it before sending the block with the torch, interfering with client-side placement prediction.

But in the @asl97’s case torch doesn’t seem to get placed at all. The reason seems to be that unloaded blocks can’t be changed that way. @Fixer-007 can you try to reproduce that with logging at `info` level? Interesting messages sound like “to place node in unloaded position”

**Comment by Fixer-007** [comment]
Will look into that.

**Comment by paramat** [comment]
We can re-open if it becomes more easily reproducable.
