### ISSUE TITLE
Falling nodes can be used to break protected blocks.

### ISSUE THREAD

**Issue by BluebirdGreycoat** [minetest/minetest#4781]
This is because the `on_step` function of `__builtin:falling_node` does not check if the node it will replace is protected when it lands and converts itself to a real node. This allows players to "sand bomb" players' gardens on multiplayer servers by bridging over them and dropping sand or another falling node off the side.

I have fixed this on my own server by overriding the `__builtin:falling_node` definition and making it call `minetest.is_protected()`. If the node it will replace is protected (and is not air), the falling node drops itself as an entity. I'm not sure if this is legal from a code perspective, but it works. It does require me to update the definition whenever a bugfix is introduced to the definition that exists in core.

I wonder if the original behavior is official and expected, and whether modders are expected to override this entity definition if they need to, or whether my fix is likely to break due to being an undocumented hack.

I am not aware whether using `minetest.register_entity()` to override builtin entities is allowed. It would be nice if this became an official part of the API, or failing that, it would be great if `__builtin:falling_node` respected protection by default.

**Comment by tenplus1** [comment]
The problem with this change is that even if the owner of the protected area places or digs falling nodes then they ALL drop as items unless replacing air.

**Comment by est31** [comment]
I guess there is a tradeoff here between gameplay and protection. If you add such a mechanism, it might be abused by players who are annoyed by gravel falling down during mining to let it drop as entity instead.

**Comment by BluebirdGreycoat** [comment]
@tenplus1, that's correct, but in practice I doubt players will find this problematic. The benefit (players no longer have to cover their gardens with glass roofing) very much outweighs the cost, at least that's what I've seen so far. If the owner of an area really needs to place a falling node on top of a non-walkable node by dropping it, they can just dig the non-walkable node first.

@est31, it's true that is possible, but in practice the player would have to protect the area first, *and* place a non-walkable node underneath the gravel, then dig the node that holds up the gravel, for this exploit to work. Seems like quite a bit of hassel to me -- I should think that if anyone tried to do this, they would find it equal to the trouble of just letting the gravel fall normally in the first place.

I would hope that even if nothing else happens regarding this issue, the ability to override builtin entities to change their behavior would become part of the Lua API, so that modders know they can change behavior if they want to, without having to rely on undocumented behavior that could break, if, for example, mod security in the future prohibted mods from modifying the core.

Here is the verbatim code I've been using:
[init.lua.txt](https://github.com/minetest/minetest/files/596212/init.lua.txt)

**Comment by ShadowNinja** [comment]
A way that this could work would be to store the placer name with every falling node.  Nodes without a placer (mapgen, pre-change, WorldEdit) would ignore protection and nodes with a placer would use it in the is_protected call.

A potential downside is that that could be a lot of extra metadata (although it should be compressed).

**Comment by est31** [comment]
What about managing it over the person causing the falling action instead (touch or removal of supporting block)? If its the owner, let it fall, if its someone else, don't. The advantage is you don't have to store anything.

**Comment by BluebirdGreycoat** [comment]
Eh, both suggestions seem (to me) to add complexity with not much player-facing benefit. Why would a player want mapgen gravel to successfully smash their protected wheat while griefer-placed gravel does not? It seems inconsistent to me; protected farms should be protected farms regardless of who drops the sand.

Anyway, my previously posted code has a slight performance issue, calling `minetest.is_protected()` when it isn't needed. Here's the updated code: 
[init.lua.txt](https://github.com/minetest/minetest/files/614126/init.lua.txt)

**Comment by ShadowNinja** [comment]
This causes issues with sand and gravel in protected areas though.  It will always drop itself instead of just falling like it should.

**Comment by BluebirdGreycoat** [comment]
Are you sure? I have tested it just now in case I missed something, and it worked. The code is live on my server and I have gotten no complains nor have I seen any issues yet. Falling nodes only drop as items if they land on a protected, non-walkable node (like a flower).

**Comment by ShadowNinja** [comment]
@BluebirdGreycoat: Oh, O.K.  That sounds much more reasonable then.  :-)

**Comment by est31** [comment]
> Falling nodes only drop as items if they land on a protected, non-walkable node (like a flower).

That sound reasonable for me as well.

**Comment by paramat** [comment]
> The benefit (players no longer have to cover their gardens with glass roofing) very much outweighs the cost, at least that's what I've seen so far. If the owner of an area really needs to place a falling node on top of a non-walkable node by dropping it, they can just dig the non-walkable node first.

I agree.

> A way that this could work would be to store the placer name with every falling node.

I disapprove.

> What about managing it over the person causing the falling action instead (touch or removal of supporting block)? If its the owner, let it fall, if its someone else, don't. The advantage is you don't have to store anything.

The falling node touched is likely to be outside the protected area. Also, falling nodes will not fall which is wrong.

> Falling nodes only drop as items if they land on a protected, non-walkable node (like a flower).

Add to that, the node must be diggable.

**Comment by beyondlimits** [comment]
Bet if Minetest was more popular (and therefore had way more hackers around), you would discuss a little and end up with solution immediately.

**Comment by SmallJoker** [comment]
@beyondlimits PRs are welcome.

**Comment by paramat** [comment]
The suggested simple solution in the first comment seems ok to me.
We have discussed a little. MT has plenty of hackers, ask any server owner :)

**Comment by HybridDog** [comment]
You could save the player name (e.g. puncher) when calling check_for_falling.
Then if falling sand spawns, it remembers this name in its object data.
If the falling sand arrives in the place where the node should be set, the protection is tested.
If the name is not known, e.g. when a piston push made it fall, 
on the one hand, the node should be set, the mesecons construction would be broken otherwise,
on the other hand, it should not be set because a villain could use a piston to make sand fall.

**Comment by beyondlimits** [comment]
@HybridDog, same problem occurs when either owner or someone else places sand on stone, then digs the stone.

Maybe check for area ID. However this again comes with caveat - a stranger could place a stone and sand on it above someone's elses area, protect only sand, change owner of area and dig the stone.

**Comment by sorcerykid** [comment]
I ended up patching `falling.lua` on my server so that falling nodes instead drop as items . It works flawlessly. I've never had a griefing problem since altering this troublesome behavior.

https://forum.minetest.net/viewtopic.php?p=307554p307554

Interestingly, not a single player to date has even complained about the lack of falling nodes. This raises the question why such a highly specialized feature that is inconsistent with the mechanics of a voxel game and permits destruction of protected areas on servers remains as part of the core.

**Comment by paramat** [comment]
> Interestingly, not a single player to date has even complained about the lack of falling nodes.

Very odd, i certainly would.
> This raises the question why such a highly specialized feature that is inconsistent with the mechanics of a voxel game

Falling nodes are obviously not highly specialised, and are not inconsistent with the mechanics of a voxel game, who defines what mechanics a voxel game should have? MT has falling nodes so they are consistent with MT.
> and permits destruction of protected areas on servers

That is a bug, not an intentional or essential part of the falling feature.

**Comment by sorcerykid** [comment]
So because you think something is an important feature, yet other people seemingly don't care one way or another, then you think their judgment is faulty? Wow, that seems a bit arrogant :P

I'm of the opinion that a bug that remains after 3 years being reported is no longer a bug but rather a feature. 

And yes, falling nodes are highly specialized. One only has to look in falling.lua to see that the 480+ lines of code do nothing except make nodes of the "falling" group turn into entities and fall when they are dug or placed above an air node. There ara no input options, no parameters, not even a single configuration setting to alter or disable the very singular and non-extensible behavior of this game-wide feature.

To conclude, in one word: Specialized.

**Comment by paramat** [comment]
Well, what i mean is, i disagree with their opinion, so i disagree with their judgement of the subject, so naturally i think it is poor judgement. In turn, they would consider my judgement poor, which is fine and natural.
It is not arrogance to say 'i disagree with the opinion of others'.

Sorry, i seem to have a somewhat unusual interpretation and usage of word 'specialised', you mean 'dedicated to one specific task, inflexible, unconfigurable', which is true.
