### ISSUE TITLE
Android app crash after a certain amount of chat messages

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest#4792]
The bug exists since version 0.4.13 stable AFAIK and it really annoys me by now:

Every time you play on servers and send lots of messages, your app WILL crash eventually...My guess is it has to do with the way the chat messages are typed (formspec).

Maybe each time you write a message the game pauses and somehow causes an internal "lag" which accumulates over time. After 100-200 chat messages when I try to send another message the game crashes. The amount of messages it takes can vary a lot and if I send only a few the game still works after many hours.

I hope this can be fixed in 0.4.15

EDIT: I think it even happens with other formspecs too... so I'm pretty sure that the problem can be found in the formspec definition.

**Comment by MoNTE48** [comment]
It would be great to see the logcat ...

**Comment by est31** [comment]
Sorry the bounty label was a mistake, didn't mean to set it. There is no bounty :)

**Comment by rubenwardy** [comment]
Can you reproduce this consistently?

**Comment by MuhdNurHidayat** [comment]
This happens a lot of times to me, it's very annoying. I'm using the latest stable Android app because my laptop could not be repaired yet.

As a moderator/helper/giver* on different servers, I use the chatbox a lot while playing Minetest on my phone to answer other players question and to send commands to the server like WorldEdit commands, giving objects to players' commands, kick/ban/mute commands etc. and it will just crash without any error message at certain time when too much message/command has been typed. The client debug file didn't write anything strange, the app will just crash.

*Giver is just translated term used on certain non-English server to mean player that have "give" privileges, but is not a helper.

You can reproduce this issue on Android app by using many commands and send many chat messages in one server in one session. You will just suddenly crash. Just don't spam other people's server while reproducing this.

**Comment by stujones11** [comment]
@IhrFussel Are you still experiencing this with the latest release?

**Comment by IhrFussel** [comment]
I will try to reproduce it with MT Android 0.4.17.1 now.

**Comment by paramat** [comment]
@IhrFussel please retest :]
