### ISSUE TITLE
Add world-independent storage directory for mods

### ISSUE THREAD

**Issue by Sokomine** [minetest/minetest#4821]
My handle_schematics mod is in part a filebrowser. It is supposed to offer schematics (in all popular formats, that is: .mts, .we, even mc .schematic; plus .meta for metadata) saved in other worlds or provided by other mods for placement in the current world without the user having to copy it over manually.

This is not possible with mod security beeing enabled.

I need read access to other world- and modfolders and up-to-date directory listings (minetest.get_dir_list() is of great help) in order to identify files containing schematics. Currently this can only be achieved by disabling mod security alltogether - which is not a good choice as protection from os.execute(), writing files anywhere and the like is certainly desired.

Something similar to secure.http_mods - perhaps called secure.extended_read_mods - might help. Mods listed there would be allowed to read files and directorys which other mods and/or worlds would be able to read during their runtime.

If a mod is not listed in secure.extended_read_mods, the respective functions ought to return an error but not shut the game down.

This is related to #4692

**Comment by ShadowNinja** [comment]
See [my comment in #4692](https://github.com/minetest/minetest/issues/4692#issuecomment-264684250) about accessing other mod dirs.
Allowing access to other worlds would be possible is some cases, but not all.  Eg, if you use `minetest --server --world /some/random/directory` and then start Minetest with a different world, Minetest won't know that the first world dir is a world dir since it isn't in its world search path.

**Comment by est31** [comment]
IMO the best solution for this would be to not allow access to different world dirs, but to have one directory shared between all worlds of an user.

**Comment by ShadowNinja** [comment]
I agree with @est31 here.  A writable shared directory for mods would be useful.  Something like `path_user+"/mod-data/"+mod_name`.
