### ISSUE TITLE
Lua API: Expose Minetest version number in an actually useful format

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4822]
I was excited when `minetest.get_version` was added, but got quickly disappointed:

```
* `minetest.get_version()`: returns a table containing components of the
    engine version.  Components:
     * `project`: Name of the project, eg, "Minetest"
     * `string`: Simple version, eg, "1.2.3-dev"
     * `hash`: Full git version (only set if available), eg, "1.2.3-dev-01234567-dirty"
   Use this for informational purposes only. The information in the returned
   table does not represent the capabilities of the engine, nor is it
   reliable or verifyable. Compatible forks will have a different name and
   version entirely. To check for the presence of engine features, test
   whether the functions exported by the wanted features exist. For example:
   `if core.nodeupdate then ... end`.
```

In other words, this function is (sadly) useless for most practical purposes. Number 1 use is of course to check if Minetest is in a particular version in order to find out whether a feature is available. This will it make much easier to write compability checks.

The suggestion that modders should just check if a function is `nil` is not really helping. It ignores the fact that not all features can be checked that way. For example, formspec elements. Here the only reliable way would be to know the actual version number.

My suggestion is to just add another field which includes 3 numbers (`major`, `minor`, `patch`) and maybe  a 4th field `release_type` which is `"development"` or `"release"` (for “-dev” or non-“-dev” versions) . The idea is to store the values atomically so they can be easily interpreted.

E.g. Minetest 0.4.14 would be:
```
-- (…)
major=0,
minor=4,
patch=14,
release_type="release",
-- (…)
```

Can you please try to squeeze this in before the feature freeze? It will be a relief for many modders, I guess.

**Comment by rubenwardy** [comment]
the version name should not be used to check for features. Formspec elements rely on the client version, not the server version. The proper fix is using either `minetest.features` or some form of `player:get_client_features()` for this detection

**Comment by Wuzzy2** [comment]
First, I said “version number” (=numbers), not “version name” (=string). Whatever.

But when it will be possible to properly check support for formspec elements via `minetest.features`, I may be OK with this being accepted as the solution for this issue. This implies the `minetest.features` table is properly documented (https://github.com/minetest/minetest/issues/4823).

But I still feel uneasy about this. If the version number can not be used to determine availability of features, then what good is a version number? o_O

**Comment by kaeza** [comment]
The key statement in @rubenwardy's comment is "Formspec elements rely on the client version, not the server version". That means you have no way to know if the client supports your forms.

This is probably a deficiency, but it is not related to version numbers in any way. @rubenwardy is right: whenever possible you should test for feature availability by checking for function existence and/or `minetest.features`, not version numbers.

**Comment by est31** [comment]
The features API was added for informational purposes only, and in fact the PR got lots of opposition from core devs based on the reason that it might be misused as @Wuzzy2 intends to.

**Comment by Wuzzy2** [comment]
“misuse”? o_O
OK, the what is the “correct” way then to learn e.g. what formspec elements are available?

**Comment by rubenwardy** [comment]
There is no current correct way - but there should be

**Comment by Zeno-** [comment]
Won't add? This has been requested so many times. I, for one, am not particularly against it.

**Comment by sfan5** [comment]
This was extensively discussed in the past and the potential for misuse is just to big with such an API

**Comment by Wuzzy2** [comment]
Well, if you can point me to a viable (!) and working (!) alternative which also works with formspecs, I am willing to close this issue.

**Comment by sfan5** [comment]
There is no way to do formspec version detection currectly. You should open an issue that is about formspecs specially.

**Comment by C1ffisme** [comment]
I think a features list is a pretty bad idea. It just means that there is something else someone has to go and update before they make a pull request. It's also means there is a long discussion about whether or not a feature deserves to be in the list.

Checking by version number means that mods can pick and choose the features that they need to know about. So item XYZ was added in update 0.4.16? Just make an if script:

```
if minetest.get_version().patch => "16" then
    minetest.register_craft(
        output = "mod:ABC",
        recipe = {{"XYZ", "XYZ", "XYZ"}},
    )
else
    minetest.register_craft(
        output = "mod:ABC",
        recipe = {{"mod:DEF", "mod:DEF", "mod:DEF"}},
    )
end
```

Seems perfectly logical to me. Then we don't have to classify whether or not a feature gets added to a feature list, and we don't have to worry about accidentally forgetting to add it into the list.

**Comment by est31** [comment]
@C1ffisme and once 0.5.0 released which still has the feature your check is broken.

**Comment by kaeza** [comment]
@C1ffisme what is wrong with

```lua
if minetest.some_new_function then
  -- Do things the new way
else
  -- Do things the old way, or disable functionality
end
```
?

**Comment by Wuzzy2** [comment]
@est31: Gosh. Have some fantasy. :P Just replace it with:

`if (minetest.get_version().minor >= 4 and minetest.get_version().patch => 16) or minetest.get_version().minor >= 5 or minetest.get_version().major >= 1 then`

(Assuming `get_version` returns numbers)

Or add a convenience function `minetest.is_version_later` (since manual checks like this one will get annoying quickly).

@kaeza: You're missing the point. C1ffisme is concerned about the added amount of work for contributers, and possibly about potential chaos.

And I ask again: What is the point of having version numbers if we pretend they are totally meaningless? Pro tip. They aren't. :P I mean, we have a thing called “changelog”. I think C1ffisme raised a good point about the added amount of works for modders and contributers alike, and I think the fear that certain features will be “forgotten” is also justified.

**Comment by kaeza** [comment]
@Wuzzy2 For the record, I am neither against nor in favor of exposing version info, just not advocating bad solutions to problems.

Re: Features, I think a feature is only listed there if there's no other way to let code detect things.nly go

**Comment by ShadowNinja** [comment]
One of the reasons that we don't want the version used for compatibility checks is that it breaks compatability with forks (i.e., Freeminer).
As noted before, formspecs in particular aren't even a server function anyways, so a version check won't do anything meaningful.

**Comment by C1ffisme** [comment]
@kaeza Can you point me to a reliable source of information which documents each and every function's addition to Minetest? And besides that, isn't that just a bit of a hack?

@ShadowNinja Well, to be fair, the first time I tried Freeminer, it was unable to render anything, and crashed within a few seconds of entering the world. So being compatible with Freeminer is a bit of a stretch. But supposing there is a good fork that was forked from 0.4.X. (Others don't count, since they can't have mods.) Wouldn't it be sensible to either:

1. Tweak the mod to be compatible, and make a guide to help mod developers port their mods, OR
2. Fork the mod for the other side and let mod developers pick people to run them?

The thing is, we're talking about supporting community mods for a community fork. Minetest is a lot nicer about compatibility when it comes to 3rd party content compared to many corporate game companies, but... actually, I'm rambling offtopic now. I'll stop before this conversation becomes more about forks than version numbers.

And anyway, it's not very hard to slap on your mod's forum page: " THIS IS NOT COMPATIBLE WITH FREEMINER"

**Comment by est31** [comment]
> THIS IS NOT COMPATIBLE WITH FREEMINER

This is the totally wrong way to approach this. Regardless of the quality of freeminer, we still try to be friendly to them and other forks, and no mod should break compatibility for this very stupid reason.

I'm closing this issue now, as I think there is no point in discussing this any further. Exposing versions to mods has been discussed for a long time already and always been rejected. The limited API we have now is enough for display reasons, which is why it got added. Extending the API would only support use cases that we don't want.

**Comment by kaeza** [comment]
@C1ffisme I take you're in favor of feature tests instead of version checks then? There's no such list. If you need to drive a nail, you ask for a hammer, not tool box brand X serial number Y.

**Comment by C1ffisme** [comment]
@kaeza 
> I take you're in favor of feature tests instead of version checks then?

Quite the opposite, actually. I was responding to this:

```if minetest.some_new_function then
  -- Do things the new way
else
  -- Do things the old way, or disable functionality
end```

Actually, never mind. I suppose this would work, but only in the event that this function does not change over time. For example, assume directly after a functions release in an update, it turns out to constantly return wrong things. This is fixed in the next patch, but you would still need to test if the version being used was the broken one.

There are other, smaller uses, too. Suppose you wanted to use an alternate set of textures for different versions of Minetest? Or for that matter, what about any other code snippet that can't be checked in this way? (Such as the meshnode drawtype. What if you needed to know if someone was running a version before 0.4.10, and didn't have meshnodes?)

**Comment by kaeza** [comment]
>For example, assume directly after a functions release in an update, it turns out to constantly return wrong things. This is fixed in the next patch, but you would still need to test if the version being used was the broken one.

That's what `minetest.features` is for. See e.g. `minetest.features.get_all_craft_recipes_works` (`minetest.get_all_craft_recipes` was broken for one release) and `minetest.features.chat_send_player_param3` (not sure what this is for).

>There are other, smaller uses, too. Suppose you wanted to use an alternate set of textures for different versions of Minetest?

I'm not sure who exactly would want to do that. The only case I can think of is the recent `nyancat` split, and then you can just use `get_modpath` to detect this case.

>What if you needed to know if someone was running a version before 0.4.10, and didn't have meshnodes?

Again, you are confusing client and server. The pre-0.4.10 **server** won't care about unknown fields, and will probably replace the unknown drawtype with a default one (`normal` or whatever the "full node" draw type is called?). The client will probably use a placeholder as well. There's also e.g. `minetest.features.glasslike_framed` (if you want to complain about people forgetting to update `features`, that is a separate issue).

In any case, as I'm pretty tired and see I won't change your mind, just extract the components from the `string` field with [patterns](http://www.lua.org/manual/5.1/manual.html#5.4.1). It's quite trivial to do.

**Comment by Wuzzy2** [comment]
Well, I guess I can kinda accept the closing of this issue.
I will report problems with providing compability to old Lua APIs seperately in different issues instead. I think this will (hopefully) work out sooner or later.

I already posted two related issues:

https://github.com/minetest/minetest/issues/4834
https://github.com/minetest/minetest/issues/4823

More issues are to come if I find a specific use case lacking.

**Comment by C1ffisme** [comment]
@Wuzzy2 
> That's what minetest.features is for. See e.g. minetest.features.get_all_craft_recipes_works (minetest.get_all_craft_recipes was broken for one release) and minetest.features.chat_send_player_param3 (not sure what this is for).

That's what we're arguing against. Which features belong in the list? And what happens if we forget to add one?

> I'm not sure who exactly would want to do that. The only case I can think of is the recent nyancat split, and then you can just use get_modpath to detect this case.

Okay, so that was a long shot. My idea was that you would want to have an alternate set of textures to match up with the retro style of the older textures. Sadly, most mods don't care about matching up texture styles these days.

> Again, you are confusing client and server. The pre-0.4.10 server won't care about unknown fields, and will probably replace the unknown drawtype with a default one (normal or whatever the "full node" draw type is called?). The client will probably use a placeholder as well. There's also e.g. minetest.features.glasslike_framed

The idea would be that you could detect if the version of Minetest you are installing the mod onto would not support meshnodes. That way you could register a nodebox instead, otherwise the block just looks broken.

> (if you want to complain about people forgetting to update features, that is a separate issue).

The idea of exposing version numbers is to avoid having these issues appear in the first place.

> In any case, as I'm pretty tired and see I won't change your mind, just extract the components from the string field with patterns. It's quite trivial to do.

Agreed. I'm already reaching the bottom of the barrel with my counter-examples.

I just don't get why giving mods the version number of the server requires an issue to argue about it. It seems like a piece of information we should have the liberty to use.

@est31 

> This is the totally wrong way to approach this. Regardless of the quality of freeminer, we still try to be friendly to them and other forks, and no mod should break compatibility for this very stupid reason.

What happens when freeminer changes something in their API? Do we still need to support their API? I feel like it should be the modder's decision if they want to support both games.

**Comment by est31** [comment]
> What happens when freeminer changes something in their API? Do we still need to support their API? I feel like it should be the modder's decision if they want to support both games.

Yes, ultimately its the decision of the modder, but it is reasonable to assume that forks of minetest want to have a different release schedule than us.

**Comment by C1ffisme** [comment]
@est31 Hold up, what if we just left the `project` table element in the actual function? It would get tedious to support both versions with so many if/elseifs, but you could do it.
