### ISSUE TITLE
new server packet: new texture at run time (not load time)

### ISSUE THREAD

**Issue by masrourmouad** [minetest/minetest#4845]
Add a player skin option on main minetest menu. 
    Create a player skin folder to let player choose witch skin to use.
    Add support to minecraft skins by auto cropping the png.

**Comment by tobyplowy** [comment]
@masrourmouad +1

**Comment by duckbrain** [comment]
I think this is a good idea, but this means that the client is going to need to upload an image to the server. This brings to mind a few considerations.

- Can the server handle additional images at runtime? Would already connected clients receive the skins of people who join after them?
- How does this interact with the modding API? I would prefer some sort of opt-in with utilizing the uploaded skins. There is always potential for offensive images, but also having an option to use one would be confusing if it is sometimes rejected server side.
- Are there security implications with uploading untrusted images? I know there are cases of security bugs in image processing. (eg: The stagefright bug in Android) I don't think this is a reason to not do it, but something to consider. I feel like we trust servers slightly more, but they deliver images all the time.

**Comment by masrourmouad** [comment]
@duckbrain  the server will cache the image , so the skin will be uploaded only one time, but when the user changes the skin the server will compare the (md5 or sha1) if the hash is changed it will update the skin.

**Comment by masrourmouad** [comment]
@duckbrain  for security implications the skin image will have to be validated in the client before sending it to the server.

**Comment by raymoo** [comment]
This also means the server will have to send skins to clients after the client is already connected and playing.

**Comment by masrourmouad** [comment]
It means that the first connection with the server, the skin will be validated in the client and sent to the server after, only one time

**Comment by raymoo** [comment]
The server has to send new player skins to existing clients so that they can display the skin.

**Comment by masrourmouad** [comment]
A skin server:
when player choose the skin from the main menu the selected skin will be automatically uploaded the the skin server, all servers will have do download one time the skin from the skin server and caching it, so next time the player connects the server, the server will send the skin to the player as an asset, that way the skin server will be not overloaded and the player will have skins.

**Comment by raymoo** [comment]
@masrourmouad What happens if the player is already connected and there is a player with a new skin?

**Comment by masrourmouad** [comment]
A server mod that connects to the skin server via the server can automatically update the skin, and cache the new skin; when the player connects his skin will be standard , the server mod will do the job.

**Comment by sofar** [comment]
'skin servers` should absolutely not be added. If we do something like this, the skin should be send directly from the client to the server.

The last thing we want is some central service where we have to do censorship on skins because some servers don't allow some skins, and other servers do allow it. E.g. some don't allow mature skins, some do not allow religious symbols, some do not allow text, some do not allow non-RP skins, some do not allow the Canadian flag, etc. etc. YOU CANT WIN THIS GAME, EVER.

What is needed to make this work is extensive:

- new client packet: send skin texture
- caching skin textures on the server (and maintaining that cache)
- infrastructure allowing server operators to review and approve player skins (moderate/approve)
- fixing the engine to introduce new images *after* the server has initialized (currently not possible)

**Comment by sofar** [comment]
Another issue is that servers may be using a different character model, requiring a custom skin. Meaning, all of this should be optional.

**Comment by masrourmouad** [comment]
create within the skin server an interface that allow  server operators to review and approve player skins;
i dont say we should have one skin server but we can have a lot of them, so a group of servers will create their own skin server, the skin server url will not be hard coded.

**Comment by masrourmouad** [comment]
in the client setting the player will specify the skin server.

**Comment by sofar** [comment]
Skin servers are definitely out of the question.

This whole feature is out of the question anyway, because nobody is going to solve this problem:

* new server packet: new texture at run time (not load time)

**Comment by masrourmouad** [comment]
so lets start with single player, can we apply skins in single player.

**Comment by sofar** [comment]
> so lets start with single player, can we apply skins in single player.

Yup. Make a new empty texture pack folder and put in a modified `character.png`.

**Comment by masrourmouad** [comment]
we should have a proper  skin option on main minetest menu, the texture pack option is not newbie friendly, Minetest needs more users to develop, so we need at least that feature; more than that the minetest menu should be rethought.

**Comment by sofar** [comment]
for singleplayer? you're kidding right? Do you honestly ever look at your own skin while in singleplayer?

**Comment by masrourmouad** [comment]
the skin server is the only solution to problem.

**Comment by sofar** [comment]
then start coding, I gave a list of things to do already, that should be a reasonable start.

**Comment by masrourmouad** [comment]
Ok,  a server mod that connects to the skin server via the server can automatically update the skin, and cache the new skin; is the easiest solution to the problem.

**Comment by masrourmouad** [comment]
a server owner will install this mod.

**Comment by masrourmouad** [comment]
thank you @sofar  but i will ask other members about my idea .

**Comment by sofar** [comment]
mods can not update skins in real time after the server has started, so you're stuck rebooting after a player changed their skins. That is an unworkable solution.

This is why the following issue should be solved first:

> * new server packet: new texture at run time (not load time)

but hey, what do I know?

**Comment by masrourmouad** [comment]
thanks

**Comment by sofar** [comment]
You're welcome. I hope someday someone will solve this underlying problem and we can actually have this feature.

**Comment by paramat** [comment]
We cannot use a skin server. Celeron55 had an email request for something like this and he considers it a really bad idea.

**Comment by masrourmouad** [comment]
@paramat  ok, why not just allow mods to change skins, and rethink the skin server after.

**Comment by sofar** [comment]
Mods can already change skins, there are several that do this. `wardrobe`, for instance.

**Comment by masrourmouad** [comment]
im speaking on servers

**Comment by SpaghettiDeveloper** [comment]
Sofar it's right. INSERT A Features Changing skin in the game (client), when the player connects to the server, the administrator MUST confirm the skin USA before being displayed at all? through the admin chat A notification appears with colorful text with a click will bring up the Player Data tab with preview of the skin and the button to approve the HIS skin. Program too complex?

**Comment by duckbrain** [comment]
I think the feature being requested here is for mods to be able to dynamically update resources. If mods can create/update textures on the clients while, connected, then new skins could be created.

This would pave the way for the network protocol that @sofar's concept is talking about.

- [ ] new client packet: send skin texture
- [x] new server packet: new texture at run time (not load time)
- [ ] caching skin textures on the server (and maintaining that cache)
- [ ] infrastructure allowing server operators to review and approve player skins (moderate/approve)
- [x] fixing the engine to introduce new images after the server has initialized (currently not possible)

A practical use-case: You could have 10 base character designs and 30 outfits and 5 hats. Currently you would have to create all permutations of the character models (1500 textures). If textures could be dynamically updated, you could create the new textures when they are created in some wardrobe-like mod that takes advantage of this, and only uses the combinations that are actually used by a player. (Note: I'm not suggesting that such a mod be made)

This would also make it possible to create some form of @masrourmouad's concept as I understand it, implemented as a mod. There is some server that contains a bunch of skins that players can choose from and apply to their characters. A formspec could give an interface to this server on login.

Personally I think @sofar's solution is better because the user could download/create any player texture themselves and use it when they log in to any server, and more importantly, it does not use any centralized server. Additional external tools could help with downloading/creating textures in the future.

**Comment by paramat** [comment]
Sofar has the right idea here https://github.com/minetest/minetest/issues/4845#issuecomment-264952819
I support moves to make it easier for server admins to receive, approve and apply skins.

> im speaking on servers

Mods can do this on servers too.

**Comment by masrourmouad** [comment]
the server owner or a group of server owners can make their own skin server, so there is no probleme

**Comment by sofar** [comment]
> the server owner or a group of server owners can make their own skin server, so there is no probleme

Not having a central server is simpler, and therefore better.

Also, once a client selects a skin in their client, it will be sent to all servers. Nothing prevents server admins from sharing `skin caches` between servers if implemented properly.

**Comment by stujones11** [comment]
We do already have a skin-server or sorts, see http://minetest.fensta.bplaced.net though we really should update the skin format, that's another issue.

**Comment by masrourmouad** [comment]
can a mod update the players skin at server run time

**Comment by duckbrain** [comment]
A mod can change which skin a player has, but not what skins are available.

**Comment by rubenwardy** [comment]
duplicate of #3528
