### ISSUE TITLE
inventory_items_animations = Enabled

### ISSUE THREAD

**Issue by SpaghettiDeveloper** [minetest/minetest#4851]
Hello guys. I noticed That Option "inventory_items_animations" And very pretty, but few users use it to enable it because you have to go in the Advanced Options menu! And hidden option. You think it is a good idea to include this option in the main menu of the game? in this mode it can be enabled by anyone, even by inexperienced users who unlike me, do not sail in the options and game code to discover new secrets.

Thank you all, and I hope I have written in the right section of the project (of Engine is an option so I should be in the right place). I await your response.

**Comment by Wuzzy2** [comment]
There are lots of settings which seem useful to some but we can't put everything in the “precious” space of the core settings. I do agree the feature is kinda cool.

I discovered the setting you mentioned, too. But I don't really like it as blocks look very bad when they rotate. They just look like extruded 2D images instead of the real model, which is totally wrong IMO.

This feature needs more polish before I would advocate promoting it to the main settings menu.

It's a pity that the main menu utterly wastes so much of the available screen space by not occupying it. Which leads devs often to cram too many widgets in relatively small space. :-(

**Comment by SpaghettiDeveloper** [comment]
@Wuzzy2 Thank you! your explanation was very useful for me, and I fully agree with your choice. I have now learned a new thing on your workflow, and project organization. Thank you so much for availability.

**Comment by Wuzzy2** [comment]
No choice has been made, it was just my humble opinion because I think it is obvious. You have learned nothing about the workflow. Look here instead: http://dev.minetest.net/All_rules_regarding_to_development

See here for a proposed and experimental main menu change: https://github.com/minetest/minetest/issues/4851

**Comment by SpaghettiDeveloper** [comment]
@Wuzzy2 Thanks for your help.

**Comment by paramat** [comment]
I don't think it's important enough to be in the main menu.

**Comment by tobyplowy** [comment]
@SpaghettiDeveloper I also don't think it's important enough to be in The Normal settings also I really think the menu needs to be redone (I don't like the menu now)

**Comment by SpaghettiDeveloper** [comment]
@tobyplowy I am happy to find collaborators who have my own ideas. Now I understood why many options are hidden. This is useful, because it has been years since I make the same questions, but thanks to all of you, now I understand some things.

**Comment by tobyplowy** [comment]
@SpaghettiDeveloper sorry I didn't really understand the beginning are you happy to find collaborators who have the same ideas as you?

Also at the end now I understand some things, is it in a good way or a bad way?

**Comment by SpaghettiDeveloper** [comment]
Sorry for my bad English. I meant that I'm happy to find collaborators who accept and understand my ideas, in a good way, you are very careful, and work well, with passion and skill! for this reason you do not accept every request that is made, this is a good thing. It was a compliment, I'll pay more attention next time I write, I promise.

**Comment by tobyplowy** [comment]
@SpaghettiDeveloper you don't have to feel Sorry I'm really Happy that you are here More Developers means More progress for Minetest :)  also lets stay on topic and end our conversation so we can focus on minetest :)
