### ISSUE TITLE
Desynchronize_mapblock_texture_animation off by default

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4862]
Why is this even an Option In The First Place It Looks bad please set it to off by default

**Comment by paramat** [comment]
You want synchronised by default? desync looks much better, otherwise you get a huge area of torches flickering exaclty in sync, the variation in flicker phase is lovely. Having the whole sea cycling through it's variation in appearence is bad too. The mapblock squares created by desync may not look too good but the alternative is much worse. Try a huge area of lava pulsating in phase, it's nauseating.
:-1:
