### ISSUE TITLE
Minetest lighting is too weak

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4870]
This came to me suddenly, but over the years I've noticed that in minetest it is not 220V, but something like 160V-like lighting from torches and mese lamp, even in my own houses it is semi-dark...

This is odd, I thought minetest light spreading is quite similar to minecraft one, but in minecraft it is much more brighter in my plays and in lots of lets plays I watched.

Here is prime examples (MC torch vs MT MESE lamg):
https://i.imgur.com/CJNNAIn.png (mt) 
https://i.imgur.com/C1Y5lYK.png (mc)
https://i.imgur.com/z8zfmfB.png (mt)
https://i.imgur.com/UJUIn20.png (mc)

It is definitely a problem for me indoors, I need to use tons of lights and even some tricks with torches behind slabs/stairs.

**Update:** It is not about 14 or 15! it is about actual brightness it gives in this range, it is much weaker light in minetest.

**Comment by juhdanad** [comment]
In MC there are 15 light levels, in MT it ia 14. The difference is in the light level-RGB mapping.

**Comment by juhdanad** [comment]
You can find light mapping in the source code, and compare with http://minecraft.gamepedia.com/File:1.9_lighting_curves_(gamma%3D0).png

**Comment by Fixer-007** [comment]
Light mapping in minetest is bothering me, it is too low.

**Comment by C1ffisme** [comment]
@juhdanad I'm pretty sure there are 15 in both games, because you can set the amount of light a block gives off to a maximum of 15.

**Comment by yyt16384** [comment]
You can use the `display_gamma` setting, or change the code in `light.cpp`.

But IMO the default brightness is too low.

**Comment by paramat** [comment]
```
u8 light_LUT[LIGHT_MAX+1] =
{
	/* Middle-raised variation of a_n+1 = a_n * 0.786
	 * Length of LIGHT_MAX+1 means LIGHT_MAX is the last value.
	 * LIGHT_SUN is read as LIGHT_MAX from here.
	 */
	8,
	11+2,
	14+7,
	18+10,
	22+15,
	29+20,
	37+20,
	47+15,
	60+10,
	76+7,
	97+5,
	123+2,
	157,
	200,
	255,
};
```

The current light table is actually heavily brightened between 11 and 1 compared to exponential.
The light curve could remain middle-raised but have the top end raised also, and then flattening out near 255, this would mean less extreme drop off close to light source.

**Comment by yyt16384** [comment]
Is the hardcoded `light_LUT` table actually being used? It seems to be overwritten in `set_light_table`.

**Comment by sofar** [comment]
This is the current curve, plotted as a simple graph.

![light-old](https://cloud.githubusercontent.com/assets/1880041/21036633/32a3ba2a-bd7c-11e6-9322-dc1544f94912.png)

There is all sorts of stupid wrong with all the code in light.cpp:

- the code claims the default display_gamma value of 1.0 corresponds with `1.8`. Not, no such thing.
- the default should be 2.2 (only macs use 1.8 as default, everyone else uses 2.2)
- the code is retarded, to say the least: it fills `light_LUT` with the values above, then makes a reference of it in `light_decode_table`. But then `set_light_table` **overwrites** all the values in light_LUT? wtf? Oh and get this: if you print out light_LUT after `set_light_table`, it's just full of completely different values!!! 
- setting a gamma of 3.0 should make things brighter. It makes things darker because if you run math.power(x, y) with y being 0 < y < 1 it's a fraction and thus the value is lower, not higher.
- the whole `if (i > 1 && light_LUT[i] < light_LUT[i-1])` statement makes absolutely arse sense to me.

@paramat +4? I don't know how your screen looks but let's start with +16 at the lower end (but it isn't working because the math in here is all messed up the wrong way anyway).

so, fuck this code in particular.

What I'd like to see is:

- a 2.2 gamma default
- with 2.2 the curve is nice and light and makes torches usable 10 or so nodes away. Meaning, at 10 nodes away I can still read a sign or see e.g. coal in stone ore.
- don't do the exponential thing near the bottom of the light range. dark is dark, it's ok if the "fringe" darkness is only 2-3 nodes.
- setting a display_gamma of 1.1 makes the game DARK
- setting a display_gamma of 3.0 makes the game BRIGHT

also, more importantly, I want to **understand** this code and how it's actually being used :(

(If I'm being unsalted, this is one time where it's the RIGHT place to say what a fucking disgrace this code is).

**Comment by paramat** [comment]
Oh i meant +4 as the step for the raising values, so instead of
2, 7, 10, 15, 20
use this
4, 8, 12, 16, 20
So that the raising values themselves are a smooth curve added to the smooth curve of the base exponential curve. Currently the raising values lok like they started as 5, 10, 15, 20, then 2 and 7 were squezzed in, then 5 removed from one end, messy.

**Comment by sofar** [comment]
doesn't matter, as long as every display_gamma value higher than 1.1 still makes the screen *darker*, this whole code needs to be fixed, badly.

TBH, if the calculation actually does the right thing, the `adjustments[]` table can just be removed.

**Comment by paramat** [comment]
Yeah i don't understand the gamma stuff.

**Comment by paramat** [comment]
It seems the light table corresponds to light levels 0-14:
`Length of LIGHT_MAX+1 means LIGHT_MAX is the last value.`
LIGHT_MAX is 14.
But then confusingly it says :+1: `LIGHT_SUN is read as LIGHT_MAX from here.`
If 14 is 255 how is 15 made brighter?

**Comment by sofar** [comment]
Because I was fedup with it, and this makes it look better and the gamma values meaningful:

#4873

**Comment by bigfoot547** [comment]
How does `display_gamma` work? Or am I a dummy.
:smiley:

**Comment by beyondlimits** [comment]
AFAIR I've already talked about this on IRC.

**Why not to keep the light table in minetest.conf?**

**Comment by sfan5** [comment]
The light table is not something that is supposed to be tuneable by the user. For example you could then achieve a "always full bright" cheat simply by editing minetest.conf

**Comment by sofar** [comment]
#4873 is merged.
