### ISSUE TITLE
Upgrade v6 Mapgen to v7 biomes

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5080]
The only mapgen that doesn't support the new biomes is v6. With the same code base for all mapgens it would be easier to maintain and would increase the mod compatibility for all mapgens.

So I will propose to add the v7 biomes to v6 mapgen

**Comment by paramat** [comment]
We have to support old mgv6 worlds (we actually guarantee this) so this would need to be an option.

I have suggested adding a new mapgen mgv62 that is mgv6 terrain plus the shared biome system of the others, but hmmmm insisted this should be done as an option in mgv6, however, this may be difficult to do as an option. What do others think about doing this as a new mapgen?

Doing this as a new mapgen would be easy for me, as an option, difficult.

This 'new' mgv6 would not have the 'mudflow' terrain-erosion process but would be unlimited vertically, mudflow currently causes bugs if terrain passes y = 47.

We need to gather opinions about this, are there many players who love mgv6 terrain? I think it's boring.

**Comment by MarkuBu** [comment]
Ok, that's a good point. I think, new biomes as an option doesn't make sense. 

I was wondering why I never found mountains >=50

Also a new mg without any improvements wouldn't make sense.

Don't know what's best.

**Comment by paramat** [comment]
Essentially, if this is wanted i can only be bothered to add it the easy way, as a new mapgen, adding it as an option within existing mgv6 will be a nightmare.

**Comment by MarkuBu** [comment]
I would make a new mapgen. Then it would be possible to add new features and higher mountains and old v6 maps still can be used

**Comment by paramat** [comment]
Exactly, the new one would not be limited to y = 47 so could have different default parameters.

**Comment by Wuzzy2** [comment]
So, are you basically saying, you are OK with a v6 with the new biomes, but against removing the current way how v6 behaves?

But I agree with you, paramat. We should not drop the “old” v6 lightly. Not just for legacy reasons. v6 is the only mapgen which allows subgame makers to get a usable world relatively quick, since you don't have to do all the tedious and difficult biome balaning to even get started. Other mapgens only give you a stone world. With v6, you only need to define a few nodes and mapgen aliases and already have a simple but usable result.
If this would be dropped, the entry barrier for new subgame authors is much higher and many people will burn out faster.
I agree, it is not the prettiest mapgen but I think it is too early to remove it entirely.

Thumbs up for the idea of offering both current v6 and “v6 with new biomes”.

I suggest the name “v6+”.

**Comment by paramat** [comment]
Yeah, we promise to support old worlds especially with mgv6, in fact mgv6 is the only officially 'stable' mapgen.

**Comment by rubenwardy** [comment]
Should this issue be closed due to risk of breaking mapgen?

**Comment by MarkuBu** [comment]
Can be closed

**Comment by paramat** [comment]
Yes the request as stated cannot be done, but feel free to open a request for a new version of mgv6 that uses the Biome API, i could code that quickly. Personally i'm neutral about doing this.
