### ISSUE TITLE
get_node_timer():start() only uses integer

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5189]
I tried to start a node timer with a float number, but the timer only starts at full seconds. Decimal places are ignored

But lua_api.txt says

> `timeout` is in seconds, and supports fractional values (0.1 etc)

**Comment by paramat** [comment]
It's possible timers only work in integer seconds, if so this is no problem we don't reaaly need fractional values.

**Comment by dsohler** [comment]
> It's possible timers only work in integer seconds, if so this is no problem we don't really need fractional values.

And why exactly is your answer in no way related to the described issue?

**Comment by paramat** [comment]
Because we either update the docs to not state this, or we alter the code to allow timers to run to fractional values, i'm saying that i don't see much need for fractional-value timers and interger-secind timers may be more lightweight.

**Comment by dsohler** [comment]
> I'm saying that

Actually no. You said nothing like you said in your second comment. You only speculated about the possibilities on how timers work and used “we” instead of “I” once again.

**Comment by sofar** [comment]
The documentation is correct, but nodetimer_interval defaults to 1.0 seconds.

Set it to 0.1 (as many mods and sub games already do) and you'll see that it works.

**Comment by paramat** [comment]
dsohler that is slightly petty objections to use of language.
When i write "we don't really need .." it is a lazy way of me writing "in my opinion we don't really need .." which again is slightly sloppy and means "i don't see much need for .." which also means "i don't see that we have much need for .."
My first comment was related, my second clarified, and you're being silly.

**Comment by kilbith** [comment]
> It's possible timers only work in integer seconds, if so this is no problem we don't really need fractional values.

[Really ?](https://github.com/minetest-mods/xdecor/blob/master/src/mechanisms.lua#L3)

**Comment by sofar** [comment]
I've argued before that the default nodetimer_interval is bad, which is why I personally submitted that the setting should be at least tunable:

https://github.com/minetest/minetest/commit/c5c727d62735e334ec64f07c557a2896d6d66d9f

Of course, a default value of 1.0 is suboptimal, because it causes a LOT of nodetimers all to coalesce, which means a large workload once a second for the server, and thus lua tasks are prone to lag spikes.

So, feel free to discuss a change to the default here:

https://github.com/minetest/minetest/pull/5193

**Comment by Ekdohibs** [comment]
I have precisely optimized nodetimers so that the setting could be decreased without too much performance impact. If this still isn't enough (although I believe it is, since it is now in O(mapblocks_loaded + number_of_timers_run * log(active_timers))), I can make yet another PR to bring the performance to O(number_of_timers_run * log(active_timers)). Optimizing nodetimer performance was done to make them efficient with a low interval since they are now more used than ABMs in well-coded mods.

**Comment by sorcerykid** [comment]
I'm in agreement with sofar on the necessity of scattering timers to prevent lag spikes, in which fractional timeout values are optimal. For example, I'm doing something similar using globalstep.

```
if timer % 5 == 0 then
...some code to execute every 0.5 seconds...
elseif ( timer + 2 ) % 5 == 0 then
... some other code to execute every 0.5 seconds, offset by 2 ticks
end
```
For the same reason, I would argue that node_timers should support non-integer values for timeouts.

**Comment by Ekdohibs** [comment]
Closing because #5193 was merged.
