### ISSUE TITLE
"ERROR[Server]: Pathfinder: failed to update cost map" floods console

### ISSUE THREAD

**Issue by MT-Modder** [minetest/minetest#5218]
This was discussed before: http://irc.minetest.net/minetest/2016-05-06#i_4602859

Maybe you should let mods decide whether to print these type of errors?

**Comment by Wuzzy2** [comment]
This not just spams the console. No.
**This error also floods the *chat* with red error messages.**

Yes, this error message is very frustrating. I frequently get it when using mobs from Mobs Redo.

Bu Gee put some reasearch into this, this is what he found out:

* This error comes from Minetest, namely: https://github.com/minetest/minetest/blob/master/src/pathfinder.cpp#L758
* It appears that mods can't get rid of this message
* This error may appear when you call in Lua the function `minetest.find_path`, that is, you use the pathfinder

Bu-Gee says:

> Looking cursorily at the code, it looks like the message is generated whenever a path can't be found regardless of the reason. I don't know why the message is compulsory because they appear to suppress other messages in that section of code.
> 
> AFAICT, it is in there to be modder abuse. That is a message that shouldn't pop up unless you're running a debugging version of minetest. I don't know if this is something you should send upstream to be fixed, but if it were up to me, that message would be suppressed unless debugging.

I agree. It seems pointless to write out this error message because a path search failed once. IMO `minetest.find_path` should just return `false` or something. I think a single failed path search with perfectly valid parameters should be considered normal operation. It makes sense that the pathfinder can't always find a path because the target can, in fact, not be reached.
`minetest.find_path` should just return `false` in that case.

Or is there any particular reason why this error message gets screamed out into the chat? Is this maybe a bug in the pathfinder?

---
@Bu-Gee

**Comment by kaeza** [comment]
#5377

**Comment by Wuzzy2** [comment]
#5377 is merged, can this issue be closed now?
