### ISSUE TITLE
Android: Missing/wrong cart texture

### ISSUE THREAD

**Issue by hkzorman** [minetest/minetest#5296]
Opening as requested by @paramat in [https://github.com/minetest/minetest_game/issues/1575](https://github.com/minetest/minetest_game/issues/1575)

Using the latest Android client, the cart texture is missing (for me, on a tablet/chromebook) or is upside-down (on phone). Although I couldn't find recent examples, I have seen the upside-down behavior before on old Minetest-based Android apps.

It seems to me that the culprit in this case is `minetest.inventorycube()` as the cart inventory item is the only one using it in vanilla minetest_game.

__Screenshots:__
On tablet:
![screenshot 2017-02-18 at 10 11 33 am](https://cloud.githubusercontent.com/assets/24514440/23286058/25d99fda-fa03-11e6-8e12-0b8273cf5eb9.png)

On phone:
![screenshot_20170218-100735](https://cloud.githubusercontent.com/assets/24514440/23286069/2bff2a6a-fa03-11e6-8684-da5cfe1a466a.png)

**Comment by paramat** [comment]
Hmm seems high priority, buig still happening?

**Comment by srifqi** [comment]
Yes, the bug still happens on master (plus stujones11/minetest@543700e64dc1356965236fe550337ce47d44c2e0).

**Comment by paramat** [comment]
@numberZero any ideas?

**Comment by numberZero** [comment]
@paramat My idea is that the Android-specific `// use no render to texture hack` in `generateTextureFromMesh` is broken. For example, author might forget that `glReadPixels` returns data in bottom-top order, while many other functions assume top-bottom order.

Really, there should be software implementation instead of that dirty hack—at least as long as #3551 is not implemented.

**Comment by numberZero** [comment]
Reproduced with upside down image on OpenGL 3 with `inventory_image_hack` forced (available for Android only in `master`, see `src/client/tile.cpp:784`)
