### ISSUE TITLE
Larger mapgen vertical overgenration for more consistent biome depths

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5318]
I remember an issue with a similar problem, but I can't find it. With my grass patch I have the problem, that I can't generate full grass blocks at a height of 48 and I have a horizontal line of half grass blocks

That's because the mapgen doesn't fill the map with the node_filler node. There is a small plain of stone below the dirt. I set depth_filler = 3.

depth_top = 2 doesn't fix the issue too

![screenshot_20170227_230740](https://cloud.githubusercontent.com/assets/16163058/23382225/ab3a15b0-fd41-11e6-9345-185742d75bf9.jpg)

**Comment by paramat** [comment]
Yes y = 47 is a nightmare for mapgen devs.
Is your 'grass patch' a mod or rewritten engine code? Are your full grass nodes are failing because there is not enough depth of filler below the surface?
The mapgen code already overgenerates from maxp.Y + 1 to minp.Y - 1 to partially solve this, there would need to be a larger amount of overgeneration to keep filler depth consistent over a chunk border. So this is expected so only partially a bug, a solution may be difficult but i might think on it.

**Comment by MarkuBu** [comment]
It's not a mod. I patched MTG to generate full grass blocks with a half grass block below. But if there is not enough dirt I just generate a half grass block. That causes the issue

https://forum.minetest.net/viewtopic.php?f=9&t=16786

**Comment by paramat** [comment]
Looks good, i like grassy sides too.

**Comment by paramat** [comment]
This is a balance, currently we overgenerate +1 -1 in mapgen for continuity at mapgen borders, this is the minimum needed for continuity but is not perfect, it means biome surface material has a limited depth at borders. Increasing the overgeneration will slow mapgen and mean 3D noises are calculated for 2*6400 more nodes. I don't think it is worth doing as so much depends on the current overgeneration. So closing.
