### ISSUE TITLE
Allow to disable higher jumping with sneak+jump

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5325]
Minetest has a small uniqueness in that you jump slightly higher when you hold down the sneak key when you press the jump key.

Please understand: **This is ***not*** the sneak glitch!** It is a completely separate mechanic which few people even know it exists.

I reqeust that this behaviour should be either disabable or tweakable (meaning you can change the “jump boost”. Ideally, it should be on a per-player basis, settable by the player flags you use to disable sneaking, the sneak glitch, the jump height, etc.

This behaviour may seem very subtle for most but it can be actually game-breaking behaviour for some use cases.

For example, I am creating a subgame (MineClone 2) with fences with a 1.5 high collision box, a normal jump doesn't suffice to go over the box. Fences are supposed to prevent jumping over them.
But a sneak jump makes you jump high to get over the fence, even with the sneak glitch enabled. Thus, it's (kinda) game-breaking behaviour. This is why I want to be able to at least disable the higher sneak jump.

**Comment by sfan5** [comment]
The problem here is that instead of allowing you to sneak on the top ledge of a node, the game allows you to sneak "on" the whole face. Effectively a sneak jump allows you to overcome 2 node high obstacles.

Meaning you can sneak "on" the pictured stone node despite being way lower:
![screenshot_20170301_141908](https://cloud.githubusercontent.com/assets/1042418/23461525/8d8def9c-fe8a-11e6-92b9-b55a6d3c6762.png)

**Comment by Wuzzy2** [comment]
Hmm, I'm not sure if you understand.

Sneak+jump  ANYWHERE makes you jump higher, this has nothing to do with the sneaking itself. If you don't believe me, test it: Stand in front of HUGE flat wall of stone blocks, but far away from anything to trigger the sneaking behaviour. Look at the stone tiles and jump, then sneak-jump. Compare the jump heights (the stone block textures make it easy to see). It is only this behaviour what I'm talking about and which I want to be able to disable, not sneaking itself or the sneak glitch.

I hope I didn't insult you for pointing this out, but your post confused me. :D

**Comment by Fixer-007** [comment]
**I'm tired of this, maybe it is time to disable sneak glitch forever (at least by default). There's already a list of critical gameplay bugs due to this sneaking thing. PLEASE DISABLE IT ONCE AND FOR ALL, this will solve a lot of problems and will create at least some challenge to player, in concert with this - fix falling damage on ignore. After this fixes you will think twice before hiking on a big mountains. It is not a matrix, when I fall from big height - I die - no matter what I pressed**

**Comment by sfan5** [comment]
@Wuzzy2 
What I mentioned in my post is not *the* sneak glitch either.
However it seems you are correct, jumping with sneak causes you to go 0.4 nodes higher independent of surroundings.

**Comment by tenplus1** [comment]
Sneak is a handy feature when scaling walls and wanting to hang onto ledges and the like, but it brings many of it's own problems that do need addressed...  Dunno if it's related though but the disable_jump group for nodes doesnt work on liquids.

**Comment by Wuzzy2** [comment]
tenplus1: What do you mean? You can't stand on liquids and jump from them, so `disable_jump=1` doesn't really make sense. This sounds off-topic anyway.

**Comment by paramat** [comment]
> I reqeust that this behaviour should be either disabable or tweakable (meaning you can change the “jump boost”. Ideally, it should be on a per-player basis

This is overcomplex and unnecessary, it should just be fixed with no setting and no parameters :-1: 
It is clear that the player in MT is not meant to be able to jump up 1.5 nodes, if that is wanted it can be done per-player with physics override.

**Comment by Wuzzy2** [comment]
I'm also fine with getting completely rid of increased jump height when sneaking.

**Comment by red-001** [comment]
yeah it seems completely unnecessary, like paramat said you can override physics if you want to change the jump height.

**Comment by paramat** [comment]
@sfan5 perhaps your PR to fix sneak bugs will somehow fix this too? If not maybe this fix can be added to that PR?

**Comment by Wuzzy2** [comment]
@paramat: Yes, the increase jump height is already removed in sfan5's sneak PR.
I support this.

**Comment by paramat** [comment]
#5327 merged.
