### ISSUE TITLE
subgame setting changes are made in global minetest.conf

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5346]
I add some settingtypes to my subgame, but any change in the subgame is made in the global minetest.conf and not, as I would expect, in the subgame minetest.conf

So if I change for example "give initial item" in my subgame it effects all subgames

**Comment by WSDguy2014** [comment]
I got a same thing, i installed regnum version 2.3.0, started to play world in regnum subgame, then playing on minetest_game subgame and going to die (if it's enabled damage and disabled creative mode) with default privileges set (interact, basic_privs, shout, privs), it keeps items in my inventory. Because i was started to play world in regnum subgame, will add a code on global minetest.conf file `bones_mode = keep` (Unfortunately, i cannot report problems anymore on regnum subgame to 1248).

**Comment by MarkuBu** [comment]
I think this is a critical bug and should be fixed before 0.4.16 release

**Comment by Fixer-007** [comment]
Can confirm since long time I go, I don't want to pollute my config with subgame settings.

**Comment by WSDguy2014** [comment]
@Fixer-007, try copy your minetest.conf file, to reproduce glitch.

**Comment by rubenwardy** [comment]
This is not a bug. The game settings should be read only, and then any changes made to the standard config.
