### ISSUE TITLE
Mapgen: No shadow cast by overhanging terrain (recalculate lighting to propagate shadows)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5357]
Hi!
In Minetest 0.4.15 and Minetest Game 0.4.15 using the map generator “v5” at default settings, I found a part of the terrain directly below overhanging terrain which was at full brightness (no shadow):

![](https://i.imgur.com/OvKZUSM.png)

The trees, flowers and dirt with grass should all be in shadow and very dark but they look as bright as sunlight. I also tried to dig some blocks all around this area but nothing changed.

Coordinates and seed in screenshot.

**Comment by juhdanad** [comment]
There is a chunk border between the ground and the cliff. The ground was generated first, and there was nothing above it that time. When the cliff was generated, the shadow only spread to the chunk border.

Direct sunlight correction could solve that, but first sunlight-emitting nodes should be introduced, else floatlands would cause huge black shadows.

**Comment by paramat** [comment]
^ Yes that. This happens in all mapgens, It may be excessively intensive to recalculate lighting for all mapchunks below when the top one is generated, unless such updates can somehow be spread out in time.

**Comment by paramat** [comment]
:-1: Difficult and seems not worth the effort.

**Comment by paramat** [comment]
I was thinking about how this could possibly be done.

When a mapchunk is generated it would of course not be possible to instantly recalculate lighting for all mapblocks below it, because that could potentially be a 32000 node high pillar of mapblocks. The new shadows would need to be propagated gradually down from the mapchunk.

So i guess the lowest mapblocks in the generated mapchunk would be marked with a 'new shadows to propagate' bool.
Each time a mapblock is loaded the mapblock above is checked for this bool, if true, lighting is recalculated in the lower mapblock, the bool set to false in the mapblock above and set to true in the lower mapblock.

As mapchunks get generated, and players move around and load mapblocks, the scattered updated shadows would very slowly trickle down through the world over very long periods of time. There would be a lot of lighting recalculations done, possibly quite intensive.

I don't see it as particularly important because it is not necessarily desirable to propagate a shadow endlessly downwards, as MT shadows are very dark, completely black 16 nodes from a column of sunlight, and stay that way over any distance with no accounting for ambient light.

So when i see lower terrain where the shadow has failed, although the shadow cutoff is a little ugly, it could be considered that ambient (multidirectional) light has lit the lower terrain. For example your screenshot, a little shadow might be good on the lower terrain but it could be considered lit by ambient light.

Overall it seems potentially intensive and not particularly necessary.
