### ISSUE TITLE
Ideas for mg v8

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5360]
These are just some ideas I have for a next mapgen. I propose to add more 2d noises to the current mg v7 to generate more variant terrains like real plains

![screenshot_20170309_161347](https://cloud.githubusercontent.com/assets/16163058/23756272/6fef4ecc-04e3-11e7-8c21-7f6c48b2b542.jpg)

a more rough but still flat terrain (high lacunarity)

![screenshot_20170309_151048](https://cloud.githubusercontent.com/assets/16163058/23753661/9cb15dc8-04da-11e7-8440-fca86b2bfeec.jpg)

Smooth hills

![screenshot_20170309_151305](https://cloud.githubusercontent.com/assets/16163058/23753760/efe8c684-04da-11e7-9430-98bf81649245.jpg)

And rough mountains

![screenshot_20170309_154839](https://cloud.githubusercontent.com/assets/16163058/23755222/edc7a636-04df-11e7-89ba-469ebf5df3b6.jpg)

or a plateau

![screenshot_20170309_161639](https://cloud.githubusercontent.com/assets/16163058/23756405/d2a74a6a-04e3-11e7-9bf8-98ebc4414f02.jpg)

Oceans should have their own noise

I also propose to add a terrain or terrain biome map that can be combined with normal biomes. A swamp or prairie should not appear in a high mountain and a glacier looks better on a mountain

Ridges should only appear in plains (optionally) because I don't really like the destroyed mountains. But they should appear at noise level and not at water level and look more like small rivers (more rough and less clean and polished). If ridges flow through mountains they should only carve a tunnle and shouldn't destroy half of the mountain

https://cdn.pixabay.com/photo/2016/08/08/10/46/minecraft-1578073_960_720.jpg
http://i1100.photobucket.com/albums/g415/TheGTRacer97/Alpha%20112%20texture%20pack%20screenies/javaw2011-09-3022-11-36-58.jpg

I really would party if v6 caves will be added and v6 and v7 caves could be activated independently (v6 only, v7 only or both at the same time).

These are just some thoughts about a new mapgen

**Comment by C1ffisme** [comment]
Maybe I'm just an MC fanboy, but I'd like to see a mapgen that can emulate Minecraft's, if only as a proof of concept or a programming project.

**Comment by MarkuBu** [comment]
I think, my suggestion is not far away from Minecraft

**Comment by Fixer-007** [comment]
There was a suggestion to port this: https://github.com/Team-RTG/Realistic-Terrain-Generation

**Comment by MarkuBu** [comment]
Well, if someone can port RTG to minetest... I would party again

**Comment by C1ffisme** [comment]
RTG would be great, but I'm talking about attempting to generate a world that is almost exactly or very close to Minecraft's mapgen. You'd have to include code in default to make sure that biomes work with the mapgen correctly, of course, because biomes such as swampland affect the generation, rather than the generation choosing to place swamps and flat biomes where the land is already flat.

**Comment by raymoo** [comment]
What about something that allows for larger-scale structure?

**Comment by MarkuBu** [comment]
You mean a flat area for villages?

**Comment by raymoo** [comment]
I mean like that one recursive mapgen thing that was requested in another issue, so you can have rivers that flow from high elevation to low elevation and things like that.

**Comment by MarkuBu** [comment]
That would be great, but this means a new mapgen from scratch. I don't think that we have enough dev power to do this. That's why I proposed additions to mg v7

**Comment by red-001** [comment]
It wouldn't be possible to port RTG to minetest due to it being created in Java and the fact that it uses GPL and not LPGL but it might be possible to create a similar mapgen.

**Comment by C1ffisme** [comment]
@red-001 
> It wouldn't be possible to port RTG to minetest due to it being created in Java

I don't think that would make it impossible. Difficult, but definitely not impossible.

**Comment by paramat** [comment]
> That would be great, but this means a new mapgen from scratch. I don't think that we have enough dev power to do this

We do, i'm already experimenting with new core mapgens, i do this even if no-one requests it out of my own interest. In many ways it's less painful than adding to mgv7.

**Comment by MarkuBu** [comment]
Ok, than this can be closed?

**Comment by MarkuBu** [comment]
What about my suggestions in general? These are features I really like to see in Minetest

**Comment by paramat** [comment]
This can be kept open as ideas for a new core mapgen.
I'll comment on your suggestions later.

**Comment by XtremeHacker** [comment]
I'd like to add one thing:
Needs trees, flowers, and other general vegetation IMHO, looks great. :)

**Comment by C1ffisme** [comment]
@XtremeHacker That's normally done by lua code, and doesn't usually have anything to do with the map generation code.

**Comment by paramat** [comment]
I agree with the 5 terrain types in the screenshots.
What do you mean by ocean noise?
> I also propose to add a terrain or terrain biome map that can be combined with normal biomes. A swamp or prairie should not appear in a high mountain and a glacier looks better on a mountain

This may be difficult for me to code, it would need a new biome system (we have the ability to support multiple biome systems). Hmmmm had many ideas about terrain influencing biomes.
To an extent the y-limits of biomes can help with this.

I certainly agree with rivers being sloped as in mgvalleys. There's no way to optionally limit them to plains because you can't control noise. River tunnels are nice but more realistically a river would erode a canyon into high terrain. My own river method simply keeps mountains away from rivers, mgv7 has it's own method where straight-side cliffs often form cutting through mountains.

I don't see the appeal of mgv6 tunnels, they are always cylindrical and very short, however my approach to tunnels is to have more intersections and more complex networks.

My approach includes using larger scale structures in mapgen, my rivergen branch has scales up to 8192 used.

RTG is not going to be ported, it would be better and easier to make our own version.

**Comment by MarkuBu** [comment]
The reason for v6 tunnels is, that they are more horizontal, v7 is often vertical. It might be more realistic, but it doesn't make fun. You always have to climb, you can't fight against mobs...

I want to have gameplay over realism. And I think, the Minecraft tunnels offers a good gameplay.

I think, terrain biomes are important. A y limit alone doesn't help because you still don't know if this node at y = 56 is on a hill, a mountain or a plateau.

**Comment by paramat** [comment]
Did you know you can 'squash' mgv7 tunnels to be more horizontal?
Try increasing the x znd z spreads for the 3D noise:
```
# mgv7_np_cave1 = 0, 12, (122, 61, 122), 52534, 3, 0.5, 2.0
# mgv7_np_cave2 = 0, 12, (134, 67, 134), 10325, 3, 0.5, 2.0
```

**Comment by MarkuBu** [comment]
> Did you know you can 'squash' or 'stretch' mgv7 tunnel noises to be more horizontal?

Yes, I tried that. But there is a limit and they became to small. Than mgv7_cave_width doesn't help

**Comment by MarkuBu** [comment]
Can't compile your rivergen. Get error messages

```
/home/markus/dev/minetest-rivergen/src/mapgen_watershed.cpp: In member function ‘virtual void MapgenWatershed::makeChunk(BlockMakeData*)’:
/home/markus/dev/minetest-rivergen/src/mapgen_watershed.cpp:332:7: error: ‘struct DungeonParams’ has no member named ‘roomsize’
    dp.roomsize      = v3s16(2, 1, 2);
       ^
/home/markus/dev/minetest-rivergen/src/mapgen_watershed.cpp:361:7: error: ‘struct DungeonParams’ has no member named ‘roomsize’
    dp.roomsize      = v3s16(8, 8, 8);
       ^

```

**Comment by paramat** [comment]
I forgot, i need to update to new dungeonparams, so that's expected.

**Comment by paramat** [comment]
Updated my branch, should work now.

**Comment by MarkuBu** [comment]
They are similar to the valleys rivers. I don't really like them. They look unrealistic and unnatural.

**Comment by paramat** [comment]
Yes smooth, you would probably like a small-scale 2D or 3D noise added to vary the riverbed.

**Comment by MarkuBu** [comment]
I mean more something like this. Water doesn't flow in circles hills up and down

![screenshot_20170313_212919](https://cloud.githubusercontent.com/assets/16163058/23874396/cd4f7c2c-0835-11e7-8b12-e8d3f670b9bd.jpg)

**Comment by MarkuBu** [comment]
Did you see my little lake experiment? 

https://www.youtube.com/watch?v=DoHbO0RN8AU

It's far from perfect, but I would try something similar with rivers

**Comment by paramat** [comment]
> Water doesn't flow in circles hills up and down

This is old news, when you create a river course using 2D noise loops happen, they are unavoidable, it happens in mgv7 a lot too.
Also common is a river changing direction: downhiill, uphill, downhill, because you cannot control noise to ensure the river always flows downhill.
If you try to create river mapgens you will realise a realistic river system is difficult to code.
A radically different and much more complex method of mapgen is needed for realistic rivers (see the recursive mapgen prototype PR).

**Comment by Wuzzy2** [comment]
I wonder if the next core mapgen should be really called “v8”. I think the mapgen “version numbers” really don't make any sense anymore since all mapgens are (de facto) more or less developed independently from each other. And v5 is in no way “less valid” than v6 or v7 or even a legacy mapgen.

Or is there any compelling reason why we should continue naming mapgens like version numbers?

**Comment by paramat** [comment]
The first new core mapgen worked on, hmmmm suggested i called it 'watershed' instead of 'mgv8', i agreed as it is more specialised. 'Mgv..' is more for what is considered a universal or 'default' mapgen as opposed to a specialised one like 'flat' and 'fractal'.
But yes, as advantage to not using 'mgv..' is that there is no suggestion that one is 'better' than another, or that an earlier one should not be used. However 'mgv..' acts as a guide to the most recently developed 'default' mapgen.
So, i'm unsure what to do. However, i am now working on a 'mgv8' but can rename it easily enough if preferred.

**Comment by paramat** [comment]
Author has left MT and points have been considered, agreed to or answered.
