### ISSUE TITLE
Underwater plantlike drawtype

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#5381]
![screenshot_20170117_164752](https://cloud.githubusercontent.com/assets/3686677/22030319/2d8c0c40-dcd5-11e6-80dc-04a7ac7d17a1.png)

^ An earlier experiment

This would address #4869 
I would like to start work on this but thought i'd gauge support / objections first.
Doing this is of course difficult in Minetest but i have thought of a workaround method.

The best implementation is for the plantlike node itself to be located not where the water is, so that normal water nodes can exist, flow, be added and removed, where the plant is. The plantlike textures would be displaced to appear where the water is.
I have demonstrated this already as shown in the screenshot, but here the actual node is above the water and the textures extend down into the water  node below.

My new idea is to have the actual node as the cubic seabed node below the plant, and use a new drawtype that creates a normal cube but has 2 plantlike textures extending upwards from it, the 'visual_scale' parameter would be used to enlarge these 2 textures to any desired height, allowing long kelp nodes to be created if wanted.
The drawtype would accept 2 texture tiles: the seabed node and the plant. This limits the plant to only be placable on 1 specific node (usually seabed sand) but this is not a problem as most plants define 1 node they are growable on.

The plant would be dug by digging the seabed node below it, or, since water is not pointable, the seabed node selectionbox could possibly be extended upwards to contain the whole plant, meaning the plant itself can be pointed at and dug.
When dug the sea bed node is replaced by a normal sand node.
When placing, a normal sand node is replaced by this special node.

Seabed plants are likely to be more decorative than other plants, so the slightly unusual behaviour is not so much of a problem.

Should this be an addition to plantlike meshoptions instead of a completely new drawtype? This would not use the more special meshoption options such as random displacement or visual size.

**Comment by MarkuBu** [comment]
Really waiting for under water flora

**Comment by paramat** [comment]
![screenshot_20170312_184500](https://cloud.githubusercontent.com/assets/3686677/23834827/a6521c2e-0754-11e7-9270-e9abbcf03aed.png)

Some progress but have z-fighting problems with the sand tiles.
Here the selectionbox has been extended up meaning you can dig the plant by pointing at the plant, even though it's 'not there'.
No PR yet but branch is here https://github.com/paramat/minetest/tree/waterplant

**Comment by paramat** [comment]
![screenshot_20170312_193039](https://cloud.githubusercontent.com/assets/3686677/23835188/e9df3c28-075a-11e7-9c07-bac710dd0664.png)

Yes it was 'solidness':
```
+	case NDT_PLANTLIKE_WATER:
+		solidness = 0;
+		visual_solidness = 1;
```

**Comment by paramat** [comment]
Fixed continuity but can't see yet how to apply face shading.

**Comment by sofar** [comment]
Sigh.

I'd honestly prefer an entity-based approach over this, but that isn't that much better either. I don't think with this method that nodes can stack (due to collision/selection box issues when the node becomes over 2 high), and that seems like a requirement - I mean, kelp that only ever covers 1 node above the bottom is going to be rather underwhelming.

**Comment by paramat** [comment]
A large number of entities would not be good indeed, much worse.
Yes these cannot be stacked of course, height is acheived by using visual_scale, these plants would be like junglegrass, obtaining their height by using visual_scale.
Consider papyrus and cactus, these already 'dig up' when you dig the lowest node, so they act like a single large node, this is little different.
Because these are for more decorative nodes the slightly unusual behaviour is not so much of a problem.

**Comment by paramat** [comment]
![screenshot_20170313_122827](https://cloud.githubusercontent.com/assets/3686677/23854349/f5f11836-07e8-11e7-84da-89aa153f5395.png)

![screenshot_20170313_123046](https://cloud.githubusercontent.com/assets/3686677/23854358/fb0a3866-07e8-11e7-8993-48740c442afa.png)

'visual_scale' only stretches the texture upwards, so here a 16x64px texture is used with 'visual_scale = 4'.

**Comment by paramat** [comment]
![screenshot_20170313_124940](https://cloud.githubusercontent.com/assets/3686677/23855298/0ceaf698-07ed-11e7-88fd-13df4295997d.png)

Face shading and smooth lighting on base cube.

**Comment by MarkuBu** [comment]
So each length needs its own texture? This will be a lot of textures if you want to make something like a kelp garden

**Comment by paramat** [comment]
Indeed that is a limitation. This drawtype would therefore be best for decorations of fixed height or a small number of heights. There are still many uses even if not used for kelp.
There seems to be no other reasonable way to create variable height kelp, certainly not hundreds of entities.

**Comment by mbblp** [comment]
please make a pull!
its a verry cool thing!

**Comment by paramat** [comment]
I will, now that the mapblock refactor is merged.

**Comment by numberZero** [comment]
Won’t it be better not to stretch but to tile the texture?
And what’s the advantage of this in comparison to mesh nodes?

**Comment by paramat** [comment]
The texture you use with this idea is not stretched, you make a texture to fit the dimensions set with 'visual_scale', for the 4 node long example above the texture is 16x64 px.
Since you worked on this sort of stuff maybe you can suggest how this can be tiled, would param2 define how many tiles are stacked? Could we maintain the ability to use 'visual_scale' to make an elongated plant without tiling?

Mesh nodes seem more complex and possibly more intensive to process and render, here i'm using a very basic approach like the 'plantlike' drawtype to make everything as simple as possible. There could be many underwater plants so render performance is important.
(In addition i don't know how to model a meshnode in blender)

**Comment by numberZero** [comment]
It may decide to tile or to stretch even on a per-node basis, that’s not a problem for a separate drawtype.

> just 1 long texture instead of multiple textures.

Tiling doesn’t mean applying several textures. GPU tiles the single texture you pass automatically. That couldn’t even be disabled until recent. Actually that is used for solid nodes to reduce face count thus increasing performance. (BTW, non-square [as well as non-power-of-2] textures may affect performance by themselves). You can use wireframe view to see that (toggled by F5 at some step IIRC, but only if you have the priv)

> Mesh nodes seem more complex

Have you ever seen the plantlike drawing code?

> In addition i don't know how to model a meshnode in blender

Me too, but such simple mesh may be written in Vim =) (I really use it sometimes to fix models) And such meshes could be supplied with MT so that mod writers wouldn’t have to make them themselves.

So, I see two advantages of a separate drawtype. The first is that its base may be drawn as a solid node, i.e. with hidden faces eliminated. *That* may speed up the rendering. And the second is that its height may be chosen with e.g. `param2`. That’s non-straightforward but possible to achieve with mesh nodes too. (Actually I think some mesh options should be applicable to them and not only to plantlike nodes as currently.)

This way, I would prefer a more universal *mesh-on-solid* drawtype that could be used for many sorts of decorations. Note that if implemented properly (which sadly doesn’t seem to be the case), mesh node may be faster in mesh generation than plantlike node; in rendering, there is no difference at all.

**Comment by paramat** [comment]
> GPU tiles the single texture you pass automatically. That couldn’t even be disabled until recent.

Thanks, interesting. Perhaps then i would prefer a new drawtype but let param2 determine the height of the 2 plantlike planes, the height being in multiples of 1 node. Then let the auto-tiling do it's thing.
I still prefer a new drawtype to a meshnode.

**Comment by Ferk** [comment]
> Mesh nodes seem more complex and possibly more intensive to process and render

Correct me if I'm wrong, but isn't plantlike just a particular case of a mesh?
It's just a standard mesh created programmatically out of 2 crossed faces. The triangle count is probably very low, but I guess it wouldn't be different in processing/rendering if it used a mesh drawtype with the same shape.

That said, #5748 on the other hand does have advantages over the mesh drawtype, mainly that the root node is rendered like a normal node.

**Comment by paramat** [comment]
#5748 merged.
