### ISSUE TITLE
Minetest appears to ignore second secure mod

### ISSUE THREAD

**Issue by tchncs** [minetest/minetest#5414]
Hi there, i just ran into issues since technic is now requiers to be added to secure trusted mods.
So this would be the setting i expect working: `secure.trusted_mods = irc, 3d_armor`
But no, i still get the security error from 3d_armor.

I had the same error in the past with sokomine's handle_schematics.

**Comment by bigfoot547** [comment]
Try setting `secure.trusted_mods` to `irc,3d_armor` (Just remove the space.).

**Comment by tchncs** [comment]
This did not help, sadly, but thanks. :)
Btw, i am close to latest commit.

**Comment by stujones11** [comment]
AFAIK current 3d_armor should not need security exemptions, though I am not sure if that is relevant to this issue.

**Comment by cheapie** [comment]
What happens if you do "3d_armor,irc" (that is, reverse the order)? Does irc give an error?

**Comment by ShadowNinja** [comment]
Er, you're saying `technic` requires an exemption, but you're giving the exemption to `3d_armor` instead?
It doesn't look like recent versions of either `technic` or `3d_armor` require an exemption, although it looks like `3d_armor` had an incompatibility with security that was resolved without requiring an exemption -- you just have to update.

Closing as apparently due to outdated mods.
