### ISSUE TITLE
CSM: preview mod causes minimap problems

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5423]
Tested on 3c4ac70 with clean config and csm enabled.
* Each game run I have different minimap shape or mod that can end up with this OpenGL texture error: https://i.imgur.com/0ZjRO37.png
* If logging into network server - empty minimap layout is shown.

**Comment by paramat** [comment]
![0zjro37](https://cloud.githubusercontent.com/assets/3686677/24082091/dcdc033c-0cb7-11e7-8e93-b8c4ac14809b.png)

**Comment by nerzhul** [comment]
@Fixer-007 for the minimap shape, preview mod call toggleshape on minimap at each game start, it's "normal" it's in the preview mod.
The empty minimap layout is a bug to fix

**Comment by nerzhul** [comment]
@Fixer-007 is minimap enabled in your config or not ? if not, please re-test current master

**Comment by NathanSalapat** [comment]
I'm experiencing a similar issue. The minimap displays correctly, but doesn't remember whether I had it set to the square or circular one, and when joining a game automatically displays the square minimap in radar mode. remove the 'enable_client_modding=true' in the configuration file it works perfect.

Just built a fresh copy before reporting this as I thought it may have been fixed in the past few days since my last build.

**Comment by nerzhul** [comment]
we will disable the preview mod just before release, but we need the PR to enable/disable mods on client before that

**Comment by nerzhul** [comment]
preview mod is a preview and is now disabled by default like all mods and should be enabled manually, it's for devs
