### ISSUE TITLE
Water is the same height as other nodes

### ISSUE THREAD

**Issue by Nyarg** [minetest/minetest#5427]
Now mapgen have one water block for water surface and under water surface and it seems absolutelly flat and stole base autentic recognizing (in that case beach border) at a glance and for boat docking.
![snag-1328](https://cloud.githubusercontent.com/assets/26514871/24083436/c801f766-0ce7-11e7-8120-a45027d64bb4.jpg)

But more smooth expirience give downing water surface ~10%. That give us feelings to see conture in 3D.
![3db6258ee32f8925d168bbe9ed23fd8a_](https://cloud.githubusercontent.com/assets/26514871/24083391/1d8d6d10-0ce7-11e7-807a-8ad6478f9f81.PNG)

**Comment by Fixer-007** [comment]
Search for "new style water" in config, should be still there.

**Comment by MarkuBu** [comment]
I complained that earlier too. Not sure if the new style water is still in the code

**Comment by rubenwardy** [comment]
Here is the commit: https://github.com/minetest/minetest/commit/8eb7ddb0a2f03ae514a96191f6edba9333ba2423

**Comment by paramat** [comment]
This might be possible with the waving water shader, maybe with custom parameters, not sure.

**Comment by paramat** [comment]
![screenshot_20170321_155957](https://cloud.githubusercontent.com/assets/3686677/24156797/7d5ba0ea-0e4f-11e7-9a24-7f99f6a331af.png)

In minetest.conf or advanced settings set:
water_wave_height = 0.0
And use the waving water shader.
New style water was removed because the shader can do this.
There could perhaps be documentation for the setting saying this is possible.

**Comment by paramat** [comment]
Duplicate of #4439

**Comment by MarkuBu** [comment]
The only problem with this solution are flickering borders with floating water
