### ISSUE TITLE
Minetest 0.4.16 roadmap

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#5530]
It's the issue to discuss about PR we want to add before feature freeze.

Feature freeze is expected on 21st May.

I added some CSM PR + Player to Database backend

**Comment by Fixer-007** [comment]
Just want to throw something that may interest devs, devs decide anyway...
"Fix multiple death messages" https://github.com/minetest/minetest/pull/5305
"Fix retrieving blocks in 3rd front camera view" https://github.com/minetest/minetest/pull/4959
"Sneaking related PRs"
"Undersampling" https://github.com/minetest/minetest/pull/5057
"Soft node overlay" https://github.com/minetest/minetest/pull/5186
"Add the possibility to skip light update and fix light later" https://github.com/minetest/minetest/pull/5373
"[CSM] Add local particles and particlespawners" https://github.com/minetest/minetest/pull/5492
"Windows: Skip cmd for release builds" https://github.com/minetest/minetest/pull/5416
"Send only changed node metadata to clients instead of whole mapblock" https://github.com/minetest/minetest/pull/5268

**Comment by bigfoot547** [comment]
Needs Addressing: #5521

**Comment by paramat** [comment]
The milestone label is used to list issues/PRs that need addressing/merging before release, so no need to list here if you are a dev who can add a milestone label.

**Comment by nerzhul** [comment]
I close this issue as we are near feature freeze.
