### ISSUE TITLE
Add negative value for node light_source.

### ISSUE THREAD

**Issue by Nyarg** [minetest/minetest#5586]
Useful for shadow making.
It's known as darkLight. Was used for example in UnrealEd.

**Comment by juhdanad** [comment]
With the current lighting implementation, it would be hard to achieve this effect.
The current implementation relies on the fact that nodes can only make light brighter, since the light level of a node is the maximum of the incoming light.

There is an implementation I can think of: add one more light bank which stores negative light. Then the current algorithm could handle these shadows too. This bank would be subtracted from the rendered light.
This implementation would require more disk space, and I don't think it's worth implementing.

**Comment by rubenwardy** [comment]
I don't really see the usecase, sorry. Maybe you could explain what this could be used for?

**Comment by C1ffisme** [comment]
More useful would be to increase the number of bits that light can have, so that you can have ultra-bright light sources that cover larger areas.

@juhdanad 
> This implementation would require more disk space, and I don't think it's worth implementing.

Just out of curiosity, (Sorry, I know this is just a bit offtopic) how much disk space does a normal Minetest world (singleplayer and multiplayer) take up? (It might be nice to have something to quote if I ever have to argue for a feature that takes up more disk space per world.)

**Comment by Nyarg** [comment]
At now with emulate shadows I see next bad situation.
Common simple shadow implemented in MT is not shadow at glance
So I find path to emulate it and really wonder at end.

with dynamic nodes................................not implemented
...with dynamic node texture change......not implemented
.......with entity........................................impossible due ones crash performance
.........with particles.................................impossible due particle plate have only vertical arrange
............with negative light......................not implemented

Resuming: No one path find at 5! possibilites.
It seems like a game model have a system structure problem.

**Comment by juhdanad** [comment]
@C1ffisme 
Each node occupies 4 bytes in the RAM:

1. 2 bytes for content information
2. 1 byte for light (4 bit day + 4 bit night)
3. 1 byte for param2

When you save your world, the same information is written to the disk, but it is compressed and I don't know the exact size.

**Comment by paramat** [comment]
Seems like a nightmare to implement, and not much needed :-1:

**Comment by C1ffisme** [comment]
I think it's possible that what he wants is a second light bank that darkens, rather than lightens, to be used for more realistic shadows (Ones that move with the sun). However, this seems like it would cause a HUGE number of lighting updates just from time going by in the game.

Of course, maybe I still have no idea what he's saying.

**Comment by paramat** [comment]
This is one of the least likely things to happen in MT, very difficult, huge amounts of work and for little benefit.
