### ISSUE TITLE
Trees being cut off at mapblock boundries

### ISSUE THREAD

**Issue by bigfoot547** [minetest/minetest#5618]
![screenshot_20170419_151122](https://cloud.githubusercontent.com/assets/21959175/25209799/da32b0b0-2542-11e7-983f-02232c4e68c8.png)
Look at the Y coordinate.

**Comment by sfan5** [comment]
related/dup: #5318

**Comment by MarkuBu** [comment]
I don't think it is a duplicate. It is related, but a different issue.

**Comment by paramat** [comment]
Yes different issue.
y = 47 is a mapchunk border, i guess this is what you mean?
How often does this happen for you? It happens to me too but rarely, there is no obvious explanation.
Which mapgen? and are there any caves nearby?

**Comment by bigfoot547** [comment]
Mapgen: v7
Caves: No, no caves.

It happens with me fairly often. Also when I do a deleteblocks, the trees don't appear until I do it again. That is probably a separate issue though.

**Comment by paramat** [comment]
I assumr default trees, if these were custom trees > 16 nodes high they would be cut off at y = 63 instead.

**Comment by WSDguy2014** [comment]
Hmm, seems old glitch/bug is back, from 2010 or 2011.

**Comment by Fixer-007** [comment]
This thing is ultra rare for me, don't even remember when I last seen it.

**Comment by bigfoot547** [comment]
@Fixer-007 That doesn't mean it needs to not be addressed

**Comment by paramat** [comment]
The rarity of this bug is variable for me, sometimes i see it 2-3 times in a session, sometimes don't see it for many days.

**Comment by paramat** [comment]
@bigfoot547 are these custom trees (schematics or l-system?) and are they sometimes higher than 16 nodes?

**Comment by Wuzzy2** [comment]
I recognize those textures. These are pine trees, maybe from v6.

**Comment by paramat** [comment]
Oh just seen 'pointing at pine needles' so yes.

**Comment by paramat** [comment]
I haven't seen this happen for a while now. maybe fixed somehow. Anyone else?

**Comment by Fixer-007** [comment]
@paramat 
Remember when I posted that screenshot with v7 river that had lots of trees near water been cut off from above? It was quite recently, somewhere in chat log with image...

**Comment by paramat** [comment]
![screenshot_20190831_020239](https://user-images.githubusercontent.com/3686677/64057542-2f438d80-cb96-11e9-8a19-ff5363ff2d08.png)

I recently did some testing of some other issue and set `num_emerge_threads = 2` (default is 1). Then soon came across a large area of chopped trees at y = 47, the first time i had seen that for 1-2 years. I suspect a link, and it makes sense as these trees are passing beyond a mapchunk border, so are in an overlap volume.
The bug probably stopped happening for me when we set the default for `num_emerge_threads` to 1 a while back.

So it seems the cause is having > 1 emerge thread.

**Comment by paramat** [comment]
I realised this bug is probably be the same bug as the one documented in past versions of minetest.conf:
```
#    Number of emerge threads to use.
#    Make this field blank or 0, or increase this number to use multiple threads.
#    On multiprocessor systems, this will improve mapgen speed greatly at the cost
#    of slightly buggy caves.
#    type: int
# num_emerge_threads = 0
```
I seem to remember 'slightly buggy caves' meant the randomwalk caves being cutoff at mapchunk borders, creating flat walls. Just like trees, the randomwalk caves are structures that 'overgenerate': extend beyond a mapchunk border (dungeons do too).

So i suspect this warning in documentation was actually referring to all overgenerating structures occasionally being cutoff at mapchunk borders. If so, it includes this cutoff tree issue.

It might be a good idea to re-add a warning to current num_emerge_threads documentation about overgenerating structures (decorations, mid-sized caves, dungeons) occasionally getting cutoff at mapchunk borders when using multiple emerge threads.
I think the current documentation understates the multiple minor bugs caused by using multiple emerge threads.

Thinking about multiple emerge threads, it seems to make sense that problems might be caused with overgenerating structures.

In non-V6 mapgens, terrain overgenerates vertically by 1 node, so i suspect that issue #9357 is closely related to this.
