### ISSUE TITLE
Renaming Minetest

### ISSUE THREAD

**Issue by azekillDIABLO** [minetest/minetest#5670]
As a long date user, i've reflected much before posting this issue. I know that devs are always trying to improve the game and its coponents but I think this should really be discussed to hope changing the name of minetest someday. First, Minetest name looks like a bad rip-off MC. Or maybe a buggy testing-only clone. If we really want to get a good popularity in gaming world, we should think to changing this names which no longer fits minetest. I'd like to know your point of view.
[Minetest Forum Topic](https://forum.minetest.net/viewtopic.php?f=5&t=17133)

**Comment by ABJ-MV** [comment]
Did you HAVE to prove the obvious?

**Comment by C1ffisme** [comment]
I can kinda agree with this, although I feel like this issue is going to go the same route as changing the name of Minetest Game: It isn't going to change that much. (minetest_game to Minetest Game.)

If I were to change the name for the engine, though, I would go for LibVoxel, similar to most open source software libraries. Then people will talk in terms of the subgame that uses LibVoxel, and not in terms of the engine itself. (Or split Minetest into two or three parts, the rendering engine being LibVoxel, the game mechanics of building and mining into LibVoxelSandbox, and the launcher into LibVoxelLauncher. That way other projects could use LibVoxel for games that need a tile-based 3d rendering system. It's also just a bit more organized.)

**Comment by azekillDIABLO** [comment]
Maybe yes, maybe no. We must find an attrative name IMHO

**Comment by paramat** [comment]
Not sure this is helpful, it's sort of obvious it's a silly name and might just be lengthy debate with nothing done. Perhaps best kept to the forum..
I feel this should be closed.

**Comment by nerzhul** [comment]
No.

**Comment by rubenwardy** [comment]
Whilst I 100% agree that "Minetest" is a shit name, this isn't really development related and should be left to be discussed on the forums. Core devs can't really decide this anyway, it's up to @celeron55 really

**Comment by azekillDIABLO** [comment]
you can't close this with a simple no. I agrre that minetest's name is pitiful but core devs should only watch this a little more or at least talk of it to @celeron55.

**Comment by nerzhul** [comment]
The discussion about a new name should wait at least 0.4.16. feature freeze is in 1 month and there are many pr to include/finish. Look at the pr list

**Comment by C1ffisme** [comment]
@nerzhul 
> The discussion about a new name should wait at least 0.4.16. feature freeze is in 1 month and there are many pr to include/finish. Look at the pr list

Erm... We still distribute Minetest with other open issues, why not keep this one open? I mean it's not like we close all of the currently open feature requests during a feature freeze.

Although, if I had to pick a time to change our name, I think we should do it around a major release (y'know, like, the first in 5 years or something?), like 0.5.0.

**Comment by rubenwardy** [comment]
Any further discussion should be on the [forum thread](https://forum.minetest.net/viewtopic.php?f=5&t=17133)

**Comment by paramat** [comment]
azekillDIABLO
> you can't close this with a simple no. I agree that minetest's name is pitiful but core devs should only watch this a little more or at least talk of it to @celeron55.

It was not closed with a no, the close was agreed between several devs on IRC.
Devs are already considering this and discussing this on IRC quite a bit and did so with celeron55 yesterday, read http://irc.minetest.net/minetest-dev/2017-04-27#i_4900524
