### ISSUE TITLE
Incomplete or mangled structures when spawning too many schematics at once

### ISSUE THREAD

**Issue by MirceaKitsune** [minetest/minetest#5685]
This has been an issue with schematics ever since they were implemented. For years it's broken buildings in my Structures mod, which uses mts files to generate randomized streets and villages. I realized I never opened an issue about it and decided to fix this now.

What happens is that, when too many minetest.place_schematic calls are placed (possibly also minetest.add_node) some of them will never complete. This results in either buildings not being spawned entirely and having large chunks missing, or node types not being replaced which for example causes walls to be made of dirt rather than wood.

I remember that in the past, I tried to work around this by adding delays in between schematic placements, going as far as 10 seconds! Yet even so, the server would be overwhelmed and lag heavily, then once the chunk finished loading it was revealed that many buildings were mangled.

While I don't expect the lag to be fixed, I do expect the process to finish correctly each time, without a single node being forgotten by the engine! I assume the flood of commands going through the server is causing it to forget some nodes or their types, whereas this might also relate to slow access to the world database, as well as the mapgen potentially acting upon a chunk after nodes from the schematic were placed and spawning the terrain on top of them.

![screenshot_20170501_005312](https://cloud.githubusercontent.com/assets/825418/25568316/b2c52b9c-2e08-11e7-9889-b7966e0ecc8f.png)
![screenshot_20170501_005407](https://cloud.githubusercontent.com/assets/825418/25568317/b2f05b50-2e08-11e7-8011-b96778b7fb1a.png)
![screenshot_20170501_005420](https://cloud.githubusercontent.com/assets/825418/25568318/b2f20c02-2e08-11e7-943a-16373066c660.png)

**Comment by paramat** [comment]
Might possibly be an issue with your mod, could you link me to the code so i can check?

**Comment by MirceaKitsune** [comment]
https://forum.minetest.net/viewtopic.php?f=11&t=5524
https://github.com/MirceaKitsune/minetest_mods_structures

I doubt it's an issue exclusive to my mod, since it's gone through heavy transformation ever since its creation: I initially made it before schematics were even implemented, and used text files to store node lists which I placed one by one using the minetest.add_node function. After I switched to schematics, I kept seeing the issue with the mapgen settings of the time, which still spawned every building at once. I then added a delay between spawns, but it was still happening. In the later stages of the mod, I made it so that structures only spawn after a chunk they touch has been generated which should also reduce the number of placement calls, yet the problem still happens in this form too.

The only arguable thing I remember my mod doing is that it first clears out the entire area around a structure, then places the actual schematic there... still this shouldn't cause the order of commands to get mixed up, if this is the case to begin with. Also I remember someone once saying that it might be the cavegen running after schematics are spawned at times, and digging holes into them while digging out the terrain... if this is the case I think it should be assured that cave generation runs at an earlier stage.

**Comment by paramat** [comment]
Cavegen always runs well before 'on generated' but they overgenerate from later-generatiing neighbouring chunks by up to 16 nodes, so all nodes you use in your schematics must have 'is_ground_content = false'. if you want to have 'default:stone' in a structure, use a mod node that drops 'default:stone'.

Note that mgv6 has dirt, grass and tree placement that overgenerates by 16 nodes, so any 'default:dirt' or 'default:stone' nodes in your schematics may have grass and trees placed on them, this is something i experienced myself in my early mods.

However these issue do not cause all the bugs here.

'place schematic' has a light update for every placement, so is meant to be used non-rapidly after mapgen. Instead you are best to use the lua voxel manipulator and use 'place schematic on vmanip', it's much faster because there's only 1 big light update on the whole LVM at the end.

So the rapid use of 'place schematic' in 'on generated' may be the cause of the problems.

**Comment by paramat** [comment]
> The only arguable thing I remember my mod doing is that it first clears out the entire area around a structure, then places the actual schematic there

Possibly unnecessary because you can use 'force place = true' for the schematic or even per-node force-place in the schematic.

**Comment by paramat** [comment]
Mod issue, use 'place schematic on vmanip' instead.
