### ISSUE TITLE
node_riverbed = "default:dirt" not working when mapgen:water_source = mapgen:river_water_source

### ISSUE THREAD

**Issue by CasimirKaPazi** [minetest/minetest#5708]
This bug forces subgames to have to types of water.

If one defines

     minetest.register_alias("mapgen_water_source", "default:water_source")
     minetest.register_alias("mapgen_river_water_source", "default:water_source")

then ```node_riverbed = "default:dirt"``` results in being default:dirt_with_grass on top, plus trees and other decoration placed in rivers.

**Comment by paramat** [comment]
WIll investigate.
Note that using normal water in mgvalleys rivers creates a huge mess on steep river slopes, a water node with small 'range' and 'renewable = false' is essential.
'River water' is the 4th fundamental 'basic terrain node' along with air, stone and water_source, so really should be included in all subgames.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/blob/master/src/mapgen.cpp#L720
The only way that 'generateBiomes()' knows when to place riverbed nodes is when river water is detected above, otherwise it will place the normal dry land surface nodes like dirt with grass, so it's not a bug.
Seeing as a special river water node is essential anyway (as explained above) and river water is one of the 4 fundamental base terrain nodes, this is not much of an issue. Subgames should have a river water node if they want to use mgvalleys.

**Comment by CasimirKaPazi** [comment]
> Note that using normal water in mgvalleys rivers creates a huge mess on steep river slopes, a water node with small 'range' and 'renewable = false' is essential.

This is based on the behavior in MTG. And to say "All subgames should behave like MTG" kind of contradicts the reason for subgames. In the case that no liquid is renewable, normal water behaves the same as river water. You end up with a duplicate nodes exactly the same except for a different name.

But in this case I just won't use valleys.

**Comment by paramat** [comment]
> This is based on the behavior in MTG

Yes subgames may have normal water that has a very small range and is not renewable, but that is unlikely for normal water because those are undesirable behaviours for normal sea-level water.

> And to say "All subgames should behave like MTG" kind of contradicts the reason for subgames

I didn't say that. Any subgame using a mapgen with sloping rivers will very likely need 2 types of water, with the river water having a very small range and being non-renewable.

>  In the case that no liquid is renewable, normal water behaves the same as river water

Liquid range is important too, rivers will get steep in new mapgens at high alttiude, maybe as steep as 1 in 2 or 1 in 3, so range 2 or 3 is essential.

Does your subgame have a normal water node that is non-renewable and has a range of 3 or less? I can understand non-renewable but a small range too?

**Comment by CasimirKaPazi** [comment]
I just have a dummy node now that gets replaced after mapgen, and it works kind of well. Should have thought of it earlier. Also I realized my arguments where about MTG, if the mapgen needs it, that's okay.

> I can understand non-renewable but a small range too?

Atm, water has a range of four. Partly to limit flood griefing but also for the blocky aesthetics.
