### ISSUE TITLE
Allow changing default stack_max when not specified

### ISSUE THREAD

**Issue by MisterXtreme** [minetest/minetest#5730]
I opened this issue on MTG: https://github.com/minetest/minetest_game/issues/1724
I've realised from the feedback, that instead of having a new default stack size, the ability to change the max stack size on any item/node would be more useful, as some items do not repsect max stack size (i.e. dyes).

**Comment by dsohler** [comment]
> the ability to change the max stack size on any item/node would be more useful,

This is possible already. The problem is, that the value gets ignored in some places.

**Comment by dsohler** [comment]
@rubenwardy I'd change the title to "Respect `stack_max` in all places when set" because the stack size is already setable and changeable (or "Allow to set a default `stack_max` value in extended configuration instead having a hardcoded value set").

**Comment by XtremeHacker** [comment]
Done @dsohler

**Comment by MarkuBu** [comment]
Is there any progress on this topic? I would like to be able to set the stack size ingame. With the hack from dsohler you need to restart the game.

I want to add some RPG elements to my subgame and one element is that the stack size depends on some attributes like strength. The stronger the character, the more he can carry.

But for this I need to be able to set and change the maximum stack size ingame

**Comment by paramat** [comment]
I think this issue should be about addressing this:

> This is possible already. The problem is, that the value gets ignored in some places.

Not about adding a new method for changing `stack_max` in-game.

**Comment by dsohler** [comment]
> Not about adding a new method for changing stack_max in-game.

Not in-game, but maybe via an extended configuration option and having this option be respected everywhere.

**Comment by MarkuBu** [comment]
> I think this issue should be about addressing this:

Well, we can extend this issue or I can open a new one, that will be closed by someone who thinks it is a duplicate

**Comment by paramat** [comment]
It's so closely related it can be the same issue.
But what i mean is, with that solved, you can then already change it in-game with 'override'.

**Comment by MarkuBu** [comment]
Ok, then I misunderstand you, sorry.

But I realized another problem right now. I need to be able to set a stack_max value by player if my Idea should work on multiplayer and it also shouldn't effect chests and other item stacks. 

So I need some custom solution anyway.

**Comment by paramat** [comment]
Related to #36 
Related PR #1118 replaced by #5919 not sure if that can alter `stack_max` @Thomas--S ?

**Comment by rubenwardy** [comment]
This does not need #36. See my old PR

**Comment by Thomas--S** [comment]
paramat, #5919 isn't going to be developed further before mid-2018 for sure, but even then I'm not sure, if I will continue to work on this. Meta-set nodedef is a big problem to implement because very large parts of the code will have to be updated and performance issues are very likely to occur.

<details><summary>My idea (offtopic)</summary>
In my opinion, it would be a better idea to make this more dynamic over time only for a single attribute at once. For this, I think it would be useful to add an optional field to the nodedef, e.g. `get_climbable(pos)`. This function is then used everytime `climbable` needs to be accessed. By default, this function returns the `climbable` field, but there would be also the possibility of changing this attribute dynamically based on the node's position.

However, this is only an idea; I did not start to code this; and I'm not sure, if this can be implemented without big problems.
</details>

**Comment by paramat** [comment]
#5919 is abandoned.
Labelling this with 'bug' also due to:
> This is possible already. The problem is, that the value gets ignored in some places.

**Comment by paramat** [comment]
It seems rubenwardy supports https://github.com/minetest/minetest_game/issues/1724#issuecomment-299632421

**Comment by paramat** [comment]
Here's 'ghost's proof of concept', it's fairly simple:
```
-- Set this value to the stack size you want. If lowering the value already
-- existing larger stacks won’t be affected – you just can’t fill them to their
-- original size.
--
-- Set to 100 to achive what’s discussed here:
-- https://forum.minetest.net/viewtopic.php?f=3&t=16817
--
-- Please note: The value of 99 for stacks (instead of using stack_max) is
-- hardcoded at various places in Minetest and can’t be altered by a mod. Using
-- this mod makes stacks the size you want in your everyday gameplay.
local desired_stack_size = 100


-- The mods you want to support. (opt-)depend this mod on them and add the
-- mod’s prefixes to this table in order to alter them.
local supported_mods = {
    'default',
    'moreblocks',
    'moreores'
}


function alter(object_name)
    for v,value in pairs(supported_mods) do
        if value == object_name:gsub(':.*','') then return true end
    end
    return false
end

local all_objects = {}
for w,what in pairs({'items', 'nodes', 'craftitems', 'tools'}) do
    for k,v in pairs(minetest['registered_'..what]) do all_objects[k] = v end
end

for name,def in pairs(all_objects) do
    if def.stack_max == 99 and alter(name) then
        minetest.override_item(name, {
            stack_max = desired_stack_size
        })
    end
end
```

**Comment by Wuzzy2** [comment]
I 100% disagree.

Ultimately, deciding on a sane stack size is the job of the game maker, not of the engine maker. If the game maker decides that 99 is a sane stack size, so be it. If not, they can change it easily.

I admit, the number 99 is a bit stupid, but I'm afraid this number is basically locked forever, and just cannot be changed. Games have been built on the assumption the default stack size is 99. If you change the default, you will screw the game makers for no reason. The stack size is NOT an UI feature, it's a gameplay feature. The solution to this is, well, just fix it in your own games.

I think changing the default stack size is almost as insane as changing the default hand range. It's insane because it breaks assumptions that game makers made, and it will have major gameplay implications.

I thought engine devs are normally very conservative when it comes to breaking things. This will totally break things. Where are the conservatives when we need them? :D

**Comment by Wuzzy2** [comment]
Ummmmmmmm … Is this actually just suggesting to change the default from the game's perspective?? Hehe, in that case, I approve. I thought this suggested an user setting … Ooops!


In any case, I thought it's already possible to change the default (from the game's perspective) …
Something something `minetest.nodedef_default`. Am I right?

**Comment by AKryukov92** [comment]
I assume that real problem here is that game depends on some user mod, which is out of control for author of the game.
I think that best solution is to remove such dependency. If someone needs cobble from default, then required parts of default should be copied and pasted to the game. This way, author of the game will be able to set any stack size for cobble.

**Comment by rubenwardy** [comment]
We have
