### ISSUE TITLE
Add group bouncy_top for making blocks bouncy on top only

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5737]
Nodes can have the group `bouncy` to make them bouncy. Currently, this makes them bouncy on *all* sides.

I suggest to add another group `bouncy_top` which works like `bouncy`, but the node is bouncy on top only.

Obvious use case: Trampoline (they shouldn't bounce when running into them from the side).

**Comment by paramat** [comment]
I'm not keen on another special collision behaviour, i've recently seen how 'bouncy' adds complexity to collision code. Instead i think better to request that bouncy nodes are only bouncy on the top? Or otherwise leave things unchanged.
For a trampoline you would just surround the bouncy nodes with non-bouncy nodes (trampoline framework) so this deosn't seem much of a problem.
:-1:
