### ISSUE TITLE
Floating decorations in v6 at default settings (caused by mudflow?)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5796]
Minetest generates floating plants/decorations in mapgen v6 at default settings:

![](https://i.imgur.com/WYrjPSf.jpg)

Above screenshot is made with almost default v6 settings (I disabled trees for this screenshot, but I tested if with trees with no impact on the bug). Note it is **not** part of the bug report that the grass spawns all over the place, this is intentional! I edited the decorations in Minetest Game to make the bug very easy to spot.

I am pretty sure this bug is caused by the `mudflow` flag of v6 mapgen settings. Here is the same spot *without* mudflow:
![](https://i.imgur.com/MjqXKi0.jpg)

How to reproduce:
* Use any simple subgame with v6 support (Minetest Game or Minimal development test work just fine)
* Define a simple decoration with a very high offset so it is generated everywhere
* Make sure to use default v6 mapgen settings, but disable trees
* Create a v6 world with seed 555
* Teleport to: X=-189, Y=15, Z=106

Note: This is *not* the same bug as this one: https://github.com/minetest/minetest/issues/1274

This bug occours for me in:
* ec490abf5889e06c88887e17f1746043de3b10fe
* 0.4.15
* Probably many versions before 0.4.15 if my memory is not failing me

**Comment by paramat** [comment]
Some decorations like grass and fowers are placed at the height of the 'heightmap', and the heightmap is generated before mudflow, so i can fix this and will do very soon.

**Comment by paramat** [comment]
But there's something else going on here too. You can see that there is not a long grass decoration floating over every 'dirt with grass' node.
Decorations have a 'place on' check which means long grass is only ever placed on dirt or 'dirt with grass', so the floating long grass you see was placed on dirt with grass' and afterwards the mud flowed away from underneath it.
However in mgv6 mapgen decorations are placed after mudflow? ...

The x co-ordinate is near a mapchunk border at x = -192, mudflow is applied out to 15 nodes beyond mapchunk borders. So chunk A generated and placed it's grass on 'dirt with grass', chunk B generated and flowed the mud in chunk A out from under the long grass. There isn't really any simple way to avoid this.

Just seen that the heightmap is indeed updated after mudflow https://github.com/minetest/minetest/blob/master/src/mapgen_v6.cpp#L560 so what you see is due to the overgeneration of mudflow on mapchunk borders.
So adding suitable labels.

**Comment by paramat** [comment]
Fixing PR #5798

**Comment by paramat** [comment]
Bug confirmed.

**Comment by paramat** [comment]
![screenshot_20170522_121924](https://cloud.githubusercontent.com/assets/3686677/26305943/45d0ec0a-3ee9-11e7-833c-dfbef6031403.png)

![screenshot_20170522_121944](https://cloud.githubusercontent.com/assets/3686677/26305947/4add0f58-3ee9-11e7-9990-343783767100.png)

^ Confirmation this is a mapchunk border issue, area affected stretches from z = 113 to z = 127 (14 nodes), the border is at z = 127.

**Comment by Wuzzy2** [comment]
> If we stopped mudflow being applied under a decoration then mudflow would not happen under decorations, meaning a pillar of dirt under each decoration. Even if this is acceptable we then break our commitment to preserve mgv6 terrain.
Maybe any 'dirt with grass' flowed can remove anything on top. I'll consider.

Yeah, I think this makes sense to remove plants under mudflow (let's say plants don't like to grow if the dirt under them crumbles away). It also keeps a nice little touch to the mapgen by keeping small areas devoid of any decorations. :-)

**Comment by paramat** [comment]
#5798 merged.
