### ISSUE TITLE
Show singlenode option in mapgen selection

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#5867]
Before now i have been unsure about this and hmmmm has stongly disapproved, but now i feel this should be present, many people have asked for it and it will actually help certain situations when a mod is detecting mapgen.
I will do this, could do this now but it is not a bugfix.

**Comment by nerzhul** [comment]
i posted #5868 for this, it's very trivial i think we can merge it

**Comment by Wuzzy2** [comment]
Yes, yes, yeeees!
I never liked the fact that singlenode was removed from mapgen selection. It has been done for the completely wrong reasons. It was done in the name of usability, but instead it did the opposite.

It is WAY too much of a hassle to create an empty world. Using advanced settings doesn't work because the main menu just instantly overwrites. So the only way to get an empty world is by editing the world file, which is just annoying.

Those few users who may get confused by this will quickly learn to avoid it. I also don't know of evidence suggesting that any users had a problem with singlenode *before* it has been removed.
