### ISSUE TITLE
Undersampling doesn't work on OpenGL 1.X or Android 4.X

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest#5929]
The new undersampling setting will just display a black screen instead of textures when you enable it on old PCs or Android 4.X devices.

Since Android 4.4 is still commercially distributed with many phones, I suggest to AT LEAST add a warning text to the setting that explains to the user that OpenGL X.X+ or OpenGL ES X.X+ are required to use this setting.

Right now when someone with that Android version adjusts many game settings at once and suddenly sees a black screen they will NOT know what exactly caused it, which is a huge flaw IMO.

**Comment by red-001** [comment]
@numberZero

**Comment by kilbith** [comment]
I don't think OpenGL 1.x should be supported at all in Minetest. This is 20 years old, people should upgrade.

**Comment by numberZero** [comment]
Wondering what could Android 4 miss... It should have render-to-texture capability, and that’s the only thing undersampling needs. So I suspect there is a bug somewhere else. But as I have no Android devices, I can’t even test it myself, not to say of fixing it.

**Comment by AntumDeluge** [comment]
I'm using Android 7.x and I have this same problem.

**Comment by numberZero** [comment]
Oh well, that’s another problem. Android should support GLES 3 since the 4.3 version. If MT can’t use that, that seems to be IrrLicht fault. And of course undersampling can’t work with such old library as GLES 1: it is designed for *moderately* old hardware, with proper software support.

Meanwhile, I found out that doesn’t work on my laptop as well, need to investigate that further. But the reason seems to be different.

**Comment by MuhdNurHidayat** [comment]
@kilbith is opengl 1.x even the same with opengl es 1.x?

> On that note, ogles1 is not even available in the drop-down list under advanced settings, even though that is what the default is for Android. Restore default sets it to opengl. In order to get it back to ogles1 the minetest.conf file must be edited, wich can be problematic on Android.
Confirmed and agreed.

I've tried setting manually to ogles3 since my Android supports OpenGL ES 3 [1] but Minetest would just crash, only ogles1 is usable (and ogles2 with weird bug, see #5600). Restore Default would set it to opengl and crash the app.

I play on Android 5.1 but I've tested on the not-for-playing phone running Android 6.0, still the same.

So this issue not just apply to Android 4.x but also Android 5.x, Android 6.x and Android 7.x (written by AntumDeluge earlier).

[1] It says so on this [page](https://www.notebookcheck.net/Qualcomm-Adreno-330.110714.0.html) on the GPU of my Android -- Qualcomm Adreno 330.
> It supports OpenGL ES 3.0 and is mostly used in Android based smartphones and tablets.

**Comment by Wayward1** [comment]
Interestingly enough, with 0.4.16 stable undersampling renders the scene just fine for me, albeit upside down. However with 0.5.0, the screen is black with random colors and the chat gets flooded with an error. I'm running Fire OS 5.1.1 (Android 5.1). On Fire OS 5.3.1 (still Android 5.1), the screen is black with 0.4.16, and white with random colors with 0.5.0.

0.4.16 stable:
![screenshot_2018-01-18-21-20-00](https://user-images.githubusercontent.com/8821916/35133010-fdc8c6fa-fc9b-11e7-9153-1f3f7c81a113.png)

0.5.0 dev:
![screenshot_2018-01-17-15-58-17](https://user-images.githubusercontent.com/8821916/35133033-2004f11c-fc9c-11e7-8e10-ee1ddd6c62cb.png)

0.4.16 on Fire OS 5.3.1: black screen

0.5.0 dev on Fire OS 5.3.1:
![screenshot_2018-01-18-22-04-28](https://user-images.githubusercontent.com/8821916/35133094-57048f56-fc9c-11e7-8282-b40e0842e367.png)

**Comment by numberZero** [comment]
Sadly IrrLicht didn’t bothered with describing which exactly operation failed.
@Wayward1 Which driver you use? ogles1 is not intended to support that at all (that should probably be mentioned). Are ogles2/3 still unusable?

**Comment by Wayward1** [comment]
By default both devices (Amazon Fire 7 2015) use ogles1, so all previous images were taken using that. Upon further testing, ogles2 still shows the same issues with transparency, but renders the scene correctly.

0.4.16 stable, ogles2:
![screenshot_2018-01-19-09-56-54](https://user-images.githubusercontent.com/8821916/35156753-c80d5080-fcff-11e7-9097-101dedc71c4d.png)

The above result is consistent on both devices and Minetest versions.

**Comment by sfan5** [comment]
FYI Irrlicht does not support OpenGL ES 3.0, there is no point in trying to use `video_driver = ogles3`

**Comment by rubenwardy** [comment]
Confirmed

**Comment by wwar-XeStro** [comment]
Android 4.4.4

Minetest 5.5.0

Undersampling = 2:
![undersampling_sucks](https://user-images.githubusercontent.com/72745616/152799182-2c3b164b-8d5e-49f0-856e-fd658c60092e.png)


Also could worth noting you can not set it back to 0 by simply typing 0 after editing it to a higher value, you can with "Restore default" though.

![undersampling_sucks2](https://user-images.githubusercontent.com/72745616/152799603-e6282709-67a9-4650-b81c-656054e0e358.png)

**Comment by erlehmann** [comment]
The original bug report might be inaccurate. I have been using undersampling successfully with Minetest 5.4.1 on OpenGL 1.4.

**Comment by Wuzzy2** [comment]
Also: 

> If you activate the undersampling setting, set it to 8 and look at the night sky, the stars flicker on and off as they move. This does not happen if this is disabled.
