### ISSUE TITLE
[visual] Allow textures span several nodes

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#5993]
It would be very nice if a texture could span several nodes (of the same type, normally). This way, walls won’t look that repetitive. Also, that will solve #5222 if implemented properly.

That’s very simple to do for solid, non-rotated nodes; rotation poses some problems, as well as nodeboxes; other nodes don’t need that, except of maybe flowing liquids (source liquid is drawn as a solid node), but that *may* be too difficult.

Note that texture need not to be just repeated as-is, it may be shifted, mirrored, etc. (if configured in the tile spec, of course), that may look better. But that may add some problems as well.

**Comment by paramat** [comment]
This may be useful for some purposes, but it's not worth worrying about textures repeating per-node, that is what a voxel game is about, repeating blocks.
This would also require huge textures or complex tile transformations.
As a way to implement #5222 this seems overcomplex.
Are there any other uses though?

**Comment by paramat** [comment]
There is another, simpler way to reduce tile repetition, which is a frame-strip where a random frame is chosen per tile.

**Comment by tobyplowy** [comment]
> but it's not worth worrying about textures repeating per-node, that is what a voxel game is about, repeating blocks.

I beg you to be more open minded on this you don't think this is important but texture pack makers do also some texture packs Need some variation in de textures (especially "realistic" ones)

Please consider this for the texturepack makers and moders!

**Comment by paramat** [comment]
Here's a better way to remove repetition #2746 i'm not opposed to that, it seems simpler and uses an existing format used for animated textures.
The feature would mean a lot more work for texture pack makers, so i doubt a large number of them want this, just a few.
We really should avoid moving MT towards requiring very large or complex textures for many nodes, creating a texture pack is already a huge effort as i know.

My comment is a more general point about feature requests for things that make a voxel game not a voxel game, such things are not a priority and the issues not much of a problem. Think about it, having a problem with repetition in a voxel game is like having a problem with cubes in a voxel game, it's a little ridiculous, just play a different game.

For #5222 having the texture of a rotated nodebox formed by an extension of a texture from somewhere else is a messy idea, better that the node itself uses it's own non-rotated texture.

**Comment by tobyplowy** [comment]
@paramat yes #2746 seems like a better fix

> Non-repetition would mean a lot more work for texture pack makers, so i doubt a large number of them want this, just a few.

I know but a lot of us really want this (me and d00med and TumeniNodes and lipki and Kenny and firefox)
In a nutshell that means most of the best texture pack Creators and other

> things that make a voxel game not a voxel game

I don't quite understand How you Set The visual rules for this kind of game there's no set rules (unless you fallow the guidelines for Minecrafts visuals) look at all the variation (terasology and portal knights and terraria and StarMade and skysaga) there's so much variation in visuals and gameplay that there's not menny rules alert from building and crafting but after that your free to do Whatever you want and that's why we all love these games they are All The Same but all Different :)

Hopefully I showed you the amount of possibilities and the freedom you have with that the only thing Holding You Back is yourself (first thing you learn in art school and its true!)

**Comment by numberZero** [comment]
@paramat 
1. Don’t oppose each and every thing people offer.
2. Learn GFX basics (I remember how were you surprised by tiling), some things you consider complex may be simple, and vice versa.
3. I know one professional game programmer. He don’t consider MT a voxel game. Really. Not due to mesh nodes, but because cubes are so huge.

**Comment by numberZero** [comment]
> extension of a texture from somewhere else

???
I just meant that texture coordinates should be set in such a way so that if two adjacent nodes use the same texture, it appears that that texture spans both. Virtually anything else would slow mesh generation down, which is a critical part already.

By the way, do you know that several nodes may be drawn with a single quad (2 faces) now? You may see that in the wireframe view that shows face boundaries only:
![screenshot_20170520_234248](https://cloud.githubusercontent.com/assets/7352626/26279224/da524058-3dbe-11e7-8a64-aed021725dc4.png)
so one texture really covers several nodes, but it’s tiled and not scaled here; that actually needs slightly more calculation. Also that conflicts with #2746 as one face can’t have different textures on different parts (unless you write a slow overcomplicated shader to achieve that; still, there is a hardware-defined limit).

**Comment by paramat** [comment]
>  do you know that several nodes may be drawn with a single quad (2 faces) now?

Yes. Strips up to 16 nodes long are possible, but long thin strips ending at mapblock borders will not create the non-repetition you describe. How would you change this to create large irregular planar areas sharing a single texture?

> I just meant that texture coordinates should be set in such a way so that if two adjacent nodes use the same texture, it appears that that texture spans both.

Ok.
A rotated brick node may have no identical neighbours, or may not share a plane with identical neighbours, so another solution will still be needed for those cases.

> Don’t oppose each and every thing people offer.

That's a ridiculous exaggeration. Unfortunately we do have to say 'no' a lot, this is inevitable with an open source project with large numbers of contributors. Many requests or PRs are unsuitable.

> Learn GFX basics

Most devs have gaps in their knowledge and you can't complain about this, sometmes you need to explain basic things to them.
  
> He don’t consider MT a voxel game

It doesn't matter if in a precise technical sense MT is not a voxel game. It is considered a 'voxel game' as in a 'MC like cube game' and my point is still valid, repetition is not a problem.

To be clear, i am not opposing this, i wrote:

> This may be useful for some purposes

I was only stating that avoiding repetition does not seem enough justification, and at the time i did not see the use for #5222. There may be other uses i have not thought of.

**Comment by numberZero** [comment]
> To be clear, i am not opposing this

Oh, sorry, I misunderstood you.

So, implementation is my concern, don’t worry of possible problems; I know what to do with virtually everything you noticed.

By the way, while repetition is not a problem with the default MTG textures, with Vanessa’s ones it is.

> requiring very large or complex textures

This feature should be entirely optional. I think it should be configured in the texture pack itself somehow.

**Comment by paramat** [comment]
What i mean is, i would like to see more uses for this to justify doing it, i don't think texture repetition alone is enough justification. So i'm not opposed but neutral and waiting for more justification.

I can see that #2746 as an implementation would break the long quads so might be worse for performance.

If, for example, a big texture is made that is 4x4 or 8x8 nodes in size, if that is then tiled on a large plane like a river canyom wall, there might still be noticeable repetition but just at a larger scale.

I'm a little concerned about the effort needed to make these textures, even 4x4 nodes is 16 times more work and the long edges need per-pixel-editing to 'tile'.

I would not worry too much about hires HDX textures, they are overkill and not much used, and i guess the repetiton problems are due to not being per-pixel-edited to 'tile' like a low-res texture can.

**Comment by tobyplowy** [comment]
> If, for example, a big texture is made that is 4x4 or 8x8 nodes in size, if that is then tiled on a large plane like a river canyom wall, there might still be noticeable repetition but just at a larger scale.

It allows you to do [These 2 by 2 Tiles](http://media-minecraftforum.cursecdn.com/attachments/120/428/635700631699738127.png) on the floor of this screenshot

Also [the way this stone bends](https://previews.123rf.com/images/pancaketom/pancaketom0809/pancaketom080900251/3612563-rock-climber-in-red-climbing-a-red-sandstone-cliff-at-Red-Rocks-Nevada-Stock-Photo.jpg) is impossible to make with normal textures (It is possible but it would look really weard and repetitive with normal textures)

Also Don't worry about time poeple are not forced to use this if they want to use it they know the time it can cost to use 

bdw it It's probably Not Gonna take that Long to make a texture (it costs way more time to make a normal Texture Because you Have To Make sure It tiles properly for me that is)

**Comment by tobyplowy** [comment]
@paramat I can give you more examples if you want 
Just ask me

**Comment by numberZero** [comment]
Is it possible for a texture pack to pass some data like tile attributes?

**Comment by paramat** [comment]
I doubt it, it's just a file of images, itle attributes come from the server nodedefs.

I like the implementation of #6075 though.

**Comment by numberZero** [comment]
**Unfinished, textures are misaligned yet**
but still...
![screenshot_20170707_012110](https://user-images.githubusercontent.com/7352626/27936253-821f3750-62b8-11e7-83ca-9fec079f11dc.png)
![screenshot_20170707_012054](https://user-images.githubusercontent.com/7352626/27936254-82206526-62b8-11e7-83f6-3871c7b0ae03.png)

**Comment by tobyplowy** [comment]
@numberZero that looks really good (but I have a question there seems to be some tiling problems in some spots in the image is that your fault or the codes fault?)

**Comment by numberZero** [comment]
I do know there are some problems on the screenshot. It was easy to make
nodeboxes tile properly, but solid nodes appear to be more problematic
as they may be joined together in mesh generation, and the whole code
is more complicated (probably due to optimization) so needs more work.
However, I think I coped with the problems, so you will see a PR soon)
