### ISSUE TITLE
Cloud API documentation needs clarifying

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6163]
Contains #5857 
```
* `set_clouds(parameters)`: set cloud parameters
	* `parameters` is a table with the following optional fields:
		* `density`: from `0` (no clouds) to `1` (full clouds) (default `0.4`)
		* `color`: basic cloud color, with alpha channel (default `#fff0f0e5`)
		* `ambient`: cloud color lower bound, use for a "glow at night" effect (default `#000000`)
		* `height`: cloud height, i.e. y of cloud base (default per conf, usually `120`)
		* `thickness`: cloud thickness in nodes (default `16`)
		* `speed`: 2D cloud speed + direction in nodes per second (default `{x=0, y=-2}`)
```
Is 'color' ARGB or RGBA?
'ambient' should be specified as RGB.
Speed is in x and y but corresponds to X and Z directions, maybe some clarification?
@bendeutsch

**Comment by Wuzzy2** [comment]
Regarding colors: Use defined terms like `ColorString` or `ColorSpec`, if they apply.

**Comment by bendeutsch** [comment]
As to X+Y vs X+Z: yes, that's just because the existing cloud code used X and Y for all 2D movement.

It should be no problem to change the *API* to accept Z instead of Y, or even in addition to Y. Or even "north" and "east"? Personally, I'm guessing users of  the API will be familiar with minetest's coordinate system. We should change to X+Z, I'll write something. And I'll look into the color definitions.

**Comment by paramat** [comment]
Yes x and z is best, familiar from world co-ordinates.

**Comment by bendeutsch** [comment]
Made a PR, please check.

**Comment by paramat** [comment]
#6164 merged.
