### ISSUE TITLE
Feature Request:  simple color facedir

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#6194]
This has been brought up once or twice before but I figured I ought to formalize it here:

I'd like to see a mode added (preferably before 0.4.17 goes out, though I'm sure that's unlikely), that adds a "simple" color-facedir, where one can select one the four cardinal N/S/W/E directions, similar to wallmounted mode, but without the up- and down-facing orientations.

This would require only two bits for the rotation, while the upper six bits would then be used to specify a palette index, in the same manner as the other color modes (but of course, 64 colors in this case).  I imagine this would be adequate for the majority of items that need both rotation and color.

**Comment by VanessaE** [comment]
@juhdanad   any chance you can code this?  This sorta thing seems to be your specialty :)

**Comment by DS-Minetest** [comment]
Example usecase: colored beds with many colors (https://github.com/minetest/minetest_game/pull/1794)

**Comment by VanessaE** [comment]
Indeed so.  I was thinking of the several items in Home Decor that would also benefit (e.g. sofas, desk lamps, and of course its beds).

**Comment by paramat** [comment]
Rotations 0-3 would be identical to current facedir to allow updating a node to a new paramtype2.

**Comment by VanessaE** [comment]
Sounds good to me!

**Comment by C1ffisme** [comment]
Ooh... I want to see where this goes.

**Comment by Sokomine** [comment]
The new color feature is great. However, 8 colors tend to be a bit limited regarding diversity, and the 24 colorwallmounted is limited regarding facedir. What paramat suggested - rotatinons 0-3 identical to current facedir - sounds very good. That way, stairs and similar nodes could be offered in more colors. Instead of having the same shape with diffrent palettes we could then have normal, upside-down and sidewise stair again, each with the full set of colors. It would be more logical than 8 nodes with the same shape and just a diffrent palette.

**Comment by paramat** [comment]
This is a good idea.
