### ISSUE TITLE
Network protocol documentation

### ISSUE THREAD

**Issue by zaoqi** [minetest/minetest#6236]
To support other clients and servers

**Comment by SmallJoker** [comment]
The title has no connection to the support of clients. However, https://github.com/minetest/minetest/blob/master/doc/protocol.txt either needs to be updated or removed for being deprecated.

**Comment by paramat** [comment]
:-1: for reasons given in #6235

**Comment by rubenwardy** [comment]
Adding protocol documentation is fair enough, as it can help contributors.

**Comment by zaoqi** [comment]
@nerzhul ?

**Comment by SmallJoker** [comment]
Valid request. No duplicate found yet, so re-opening.

**Comment by rubenwardy** [comment]
The networkprotocol.h is sufficient for protocol imo

**Comment by numberZero** [comment]
The documentation in `networkprotocol.h` is highly inaccurate, describing wrong field order, still using F1000, etc. It also specifies string length as a separate field, *but only in some places...* So here is some hopefully machine-parsable documentation based more on the actual code in `*packethandler.cpp` (from minetest@2424dfe00, no protocol changes since then) than on the header: https://github.com/numberZero/minetest-proto

**Comment by sfan5** [comment]
The [wireshark dissector](https://github.com/minetest/minetest/blob/master/util/wireshark/minetest.lua) also provides partial coverage of the protocol. The dissections for the packets it supports should be up-to-date.
