### ISSUE TITLE
[Mods] Add min_version, max_version support

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#6330]
Currently mods has dependencies but no core version checking, at least at mod loading.

Adding min_version and max_version support permits modder to manage their code easily in terms of compatibility with various version.

one good example is the setting API, define 0.4.15 as a max_version on old API and set min_version to 0.4.15 and max to 0.4.16 for the new setting API

I think the following rules should be added:

* min_version: optional, *default*: 0.5.0 (aka. the minimum MT version to support this feature)
* max_version: optional, *default*: null

**Comment by dsohler** [comment]
Mod versions are a must-have in my opinion.

**Comment by Wuzzy2** [comment]
A naked `max_version` check is dangerous because it tends to “break” mods only because Minetest got updated, even if all APIs are still technically compatible. If this will force modders to regularily “update” mods **only** to bump `max_version`, I am opposed.



If Minetest would adopt SemVer (http://semver.org/), we could also precisely predict when a mod is going to break, namely whenever a major (read: breaking) release is made.

**Comment by dsohler** [comment]
> If this will force modders to regularily “update” mods

Yes, please. Nothing is worse than outdated mods.

> only to bump max_version,

... and to verify it it still works.

But yes, a `min_version` check would be better then. So modders can say it needs `mod >= 1.0` and `Minetest > = 0.5`. So if mod 2.0 and Minetest 0.6 will be released it would still work (if compatible).

**Comment by nerzhul** [comment]
@Wuzzy2 maybe i would be more precise, min_version is, for me, mandatory, but max_version optional, it should permits modders to have a EOL on a specific version before starting new developments

**Comment by rubenwardy** [comment]
This can now be managed with the content database - and it's better to do it that way as you can retroactively add a max version to releases
