### ISSUE TITLE
Allow merging PRs with one approval in case there is no dissent

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#6365]
PRs with one approval should be merge-able after a week or two if no core dev has officially dissented to the PR. This incentivizes core devs to review PRs that are close to being merged and prevents the PRs from stagnating with one approval needed for merge.

**Comment by paramat** [comment]
:-1:  Non-trivial PRs always need 2 approvals regardless of situation. A core dev may be busy and somehow miss seeing a PR for weeks, this can't be assumed to mean they do not disapprove.

**Comment by paramat** [comment]
> This incentivizes core devs to review PRs that are close to being merged

This is irrelevant and will make no difference, a dev may very much want to work on PR review but simply has no time. It's not as if we are lazy and have lots of free time and need some incentive to review.

> and prevents the PRs from stagnating with one approval needed for merge.

One approval is not enough for a merge, irrelevant of how long it has been open.

**Comment by raymoo** [comment]
@paramat I meant one review more.

**Comment by paramat** [comment]
?
Sorry if i misunderstood.

**Comment by raymoo** [comment]
I thought you were saying that I was wrong when I said "one approval needed for merge". I was trying to clear up the perceived misunderstanding by explaining that I meant the situation where one more approval is needed, since there is already an existing approval.

**Comment by paramat** [comment]
Ahh ok i see, sorry, yes i understand that, but still disapprove of the idea for the same reasons,

**Comment by paramat** [comment]
PRs need 2 core dev approvals to be merged, this is the absolute minimum because any less would mean non-trivial PRs being added according to the will of a single person, which is unnacceptable and potentially dangerous.
There is no way to know if the absence of a core dev commenting is 'no dissent' or is them being too busy to review it or simply missing seeing it (which are very commonly the case).
This suggestion is asking us to change our rules only due to the passage of time, which makes no sense. It also means lowering our standards and quality when those are more important than dev speed.
2 disapprovals and this is obviously something we simply cannot do.
