### ISSUE TITLE
[Discussion] Widening the PR review / approval bottleneck

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#6366]
It is apparent from the collection of (previously) unreviewed ready-to-be-reviewed PRs that the PR review process is the main bottleneck in Minetest development. The core developers don't have the time or aren't willing to review PRs at the rate that Minetest receives them. All work on Minetest is voluntary of course, and nobody is obligated to contribute their time. However, given the current activity level of the core developers, it is worth considering changes to the review process that might increase the rate at which good PRs get approved. This is thread is for discussing ideas for doing this.

Related issues:
 - #6362: New "Ready for review" PR label
 - #6364: Separate code reviews and feature reviews
 - #6365: Allow merging PRs with one approval in case there is no dissent

**Comment by raymoo** [comment]
Another idea is for one of the core devs to start a Patreon dedicated exclusively to reviewing PRs. I feel like not many people would end up donating, but maybe it would be worth trying?

**Comment by rubenwardy** [comment]
I've been reviewing lots of PRs in the last week. I managed to close about 50 issues and 15 PRs (not sure on latter number) and made comments on the latter.

I agree with the first two. The latter one needs limitation.

**Comment by HybridDog** [comment]
You could add testers. They are (trustworthy) people who test the PRs and write the results (including what and how they have tested) in a comment and then add a "partially tested", "successfully tested", "two times successfully tested" or "testing failed" label (and remove out of date labels). Two successful tests count as second approval.

**Comment by nerzhul** [comment]
ready_for_review label is only useful when you have a bot connected and you can comment to flag your PR, look at https://github/ansible/ansible to see a huge bot in action

**Comment by dsohler** [comment]
> Another idea is for one of the core devs to start a Patreon dedicated exclusively to reviewing PRs.

So you need to buy in your PRs then? :rofl:

**Comment by rubenwardy** [comment]
> So you need to buy in your PRs then? :rofl:

Yeah, as of now I'm going to require £15 per PR review. You can buy 10 reviews in advance for £100 pounds (33% off!). I accept debit card, [Patreon](https://www.youtube.com/watch?v=dQw4w9WgXcQ), or [paypal](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by SmallJoker** [comment]
Damnit @rubenwardy, I thought [my offers](https://goo.gl/2FL9hP) would be the best on the market! ;)

PR stalling is a known problem, as sometimes it's not clear whether changes should be done, what's missing or if it's ready but forgotten. Adding more labels doesn't really help, however, I'm open for a system where well known contributors can review code and/or the functionality.

**Comment by dsohler** [comment]
33% off … Tempting offer … would buy.

**Comment by nerzhul** [comment]
one review is already active for trivial PR, it's important to have two review on external PR, generally it tend to be interesting to have two core devs point of view.
To win some time i see two interesting things: 
* generalize clang-format or the maximum possible to stop review code style
* finish the #6295 PR to have an automated review of the C++ code quality with warns and errors

**Comment by tobyplowy** [comment]
@rubenwardy why did I even klik That link :/

**Comment by paramat** [comment]
> The core developers don't have the time or aren't willing to review PRs at the rate that Minetest receives them

I expect this will always be the case due to the nature of open source dev.

> given the current activity level of the core developers,

Nerzhul, krock, rubenwardy and i are all very active. No matter how active devs are it will always be seen as not enough, due to the nature of free open source software which is:
1.There's no or little money in it so dev number and dev time is limited.
2.There's a very large number of contributors who all (rightly) feel thier contributions should be considered.

I can't see how PR review can be faster without review and therefore code quality falling, and code quality is more important than dev speed. Review requires devs with fairly good game knowledge. Anyone good with code but not very knowledgable about the game can review and point out coding errors, but the final approval has to come from core cevs.
So, given the human resources we have i can't see how PR review can be made quicker, we are inevitable restricted by the human resources.

**Comment by raymoo** [comment]
To say that PR review can't be faster without review quality failing is to say that our system is already perfect (as in, it is impossible to do any better given our constraints), or close to it. As a general principle it's highly doubtful that anything is being done close to perfectly, so it is worth coming up with and trying new things and seeing how they go.

**Comment by raymoo** [comment]
Alternatively we can come up with a differentiable formulation of PR approvals and optimize by gradient descent

**Comment by HybridDog** [comment]
> I can't see how PR review can be faster without review and code quality falling

If there was proper documentation, i.e. doxygen comments (it is on minetest's TODO), aggravating code quality would be very unlikely because then fairly anyone who reads the code changes could see mistakes.
Code style mistakes can easily be reported by travis.

**Comment by paramat** [comment]
I think it's fine to discuss possible improvements, which can happen here. I'm not trying to stop discussion or say everything is perfect, just responding to some points.

**Comment by TekhnaeRaav** [comment]
In the case of PR, issues and such I had a question. When minetest devs close a issue/PR like [this one ](https://github.com/minetest/minetest/pull/3739) does this mean the idea is gone, or are they basically very low priority? Because some of these things are good ideas for minetest, or maybe they could be up for community contributions.

**Comment by rubenwardy** [comment]
@TekhnaeRaav you're welcome to take over and make a PR for that feature again. That PR had issues and the author wasn't willing to work on it, hence it was closed

**Comment by TekhnaeRaav** [comment]
Oh, no not me I can't code. I understand, but, would it be useful to have a larger list of the PRs that can be continued or are in a state of "Adoption needed". Minetest development may go faster.

**Comment by HybridDog** [comment]
I think so, too. github offers labels, so you can give such (closed) PRs labels and when you want to view them, you can get a list, e.g. here're the closed "Invalid" pull requests: https://github.com/minetest/minetest/pulls?q=is%3Apr+is%3Aclosed+label%3AInvalid

**Comment by paramat** [comment]
#3739 was closed because we disapproved of it being added and probably still will, the thread comments usually make it clear.

Other PRs are closed because they are neglected by the author for 1 month (it's a dev rule), in which case we add the 'neglect closure' label, the PR will be reopened if progress is made.

There's also the 'adoption needed' label for features we want but need taking over.

No need for a 'list', just search using these labels. Labels are used fairly consistently.

**Comment by rubenwardy** [comment]
We're now down to 90 PRs, and have many more which will be merged soon. I think that the review process is certainly better now, but there's still room for improvement as 90 PRs is still a lot of code to be sitting around

**Comment by nerzhul** [comment]
#6295 is now ready for a merge and will help to catch common C++ errors. This just need some configuration
