### ISSUE TITLE
get_hit_params and get_dig_params aren't in lua_api.txt.

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6372]
get_hit_params and get_dig_params aren't in lua_api.txt.

**Comment by thetaepsilon-gamedev** [comment]
I would like to tack onto this by saying that while get_dig_params() is not yet documented, I intend to make use of this in the pipeworks mod.
Documentation in lua_api.txt would be useful to serve as a marker to consider it public API that is used by a mod, if only in case (admittedly unlikely) it is removed because it is considered "unused".

**Comment by HybridDog** [comment]
Before documenting it, the time_from_last_punch parameter should vanish: https://github.com/minetest/minetest/pull/5558/commits/a9d1f5bbaba15468f66edb9e3b0dd937ea627791#diff-b2e9183274c47c49c500e499eacd627eL134
It looks like something once used for anticheat calculations, now unused.

**Comment by paramat** [comment]
#6906 merged, partially fixes this.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/commit/187519407be5ca51db007d638857917ba53f1b6d
