### ISSUE TITLE
Generate snow as floor cover in mapgen v6

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6387]
Mapgen v6 generates too little snow. It generates snow blocks (`default:snowblock`), dirt with snow (`default:dirt_with_snow`) and snow (`default:snow` = `mapgen_snow`). But snow is only generated on top of pines but never on the ground level. We only have dirt with snow which makes the snow floor rather flat.

In all other mapgens in Minetest Game, the snowy biomes use snow quite liberally and whole biomes are covered by it. So for consistency's sake, I suggest that v6 also starts using snow as floor cover.

**Comment by paramat** [comment]
Yes when i added the snow biomes to mgv6 i deliberately tried to avoid default:snow as nodeboxes reduce FPS significantly, especially now that all have smooth lighting.
I did the same for the biome system of other mapgens for the same reason, i was forced to add snow slabs because that is the 'dust' that adds snow to trees, whereas in mgv6 snow slabs are hardcoded into the pine tree structure.

Mgv6 is a lightweight mapgen often used for lower power devices so even more reason to avoid nodeboxes if possible.
It looks ok to me so i'm currently unconvinced, but will consider.

**Comment by Wuzzy2** [comment]
If nodeboxes are problematic, why not fixing nodeboxes?

Are you sure you meant snow *slabs*? Those are 0.5 nodes high, unless `default:snow`, which is only 0.25 nodes high.

But if MGv6 follows the KISS philosophy, I can understand that.

**Comment by paramat** [comment]
By snow slabs i mean the quarter-height nodeboxes, i forgot we have snow halfslabs now.

Fixing nodebox smooth lighting may not be possible because any non-cubic node has to do calculations to create the smooth lighting @numberZero ?

**Comment by numberZero** [comment]
@paramat Calculation results may be cached (that was my initial plan, actually), reducing the meshgen time, but the drawtime can’t be reduced significantly unless the mesh is optimized thoroughly, but heh, that means much longer generation time.

**Comment by paramat** [comment]
So, a welcome suggestion but i think i prefer to leave it as it is.
I might be adding a modernised 'mgv61' which will have the biome system of all other mapgens.
