### ISSUE TITLE
Mods without init.lua

### ISSUE THREAD

**Issue by zaoqi** [minetest/minetest#6402]
test_scheme:
init.scm:
```scheme
(after 3 (lambda () (display_chat_message "hi")))
```
depends.txt:
`mtscheme`

mtscheme: https://github.com/zaoqi/minetest.scm

test_scheme doesn't need init.lua.

**Comment by juhdanad** [comment]
Do you want Minetest to have a built-in Scheme interpreter?

**Comment by juhdanad** [comment]
Oh, I see! You have an interpreter mod for an other, not Lua mod, so that mod does not have `init.lua`. I think the correct solution is to place these mods under `mtscheme`'s folder as sub-mods. But then you can not switch these on/off in the world configuration. Maybe `init.lua` should not be enforced for such "resource mods".

Then the simplest solution is to create an `init.lua` as:

```lua
-- This mod is a resource for 'mtscheme'.
-- For functionality, see init.scm
```

**Comment by raymoo** [comment]
@juhdanad If the mod is from a different author then it doesn't make sense to me to put it inside of somebody else's mod.

**Comment by dsohler** [comment]
(Hooray! (We (totally (need (more (braces (in (Minetest!))))))))

**Comment by paramat** [comment]
> Then the simplest solution is to create an init.lua as:
-- This mod is a resource for 'mtscheme'.
-- For functionality, see init.scm

If this works then this is good enough, seems too low priority to work on.

**Comment by raymoo** [comment]
I think @paramat's suggestion is fine for these kinds of mods. It's probably better for error-handling reasons too to be explicit about not needing init.lua.

**Comment by rubenwardy** [comment]
:-1:

This is unnecessary. Just require an empty init.lua
