### ISSUE TITLE
Per-biome grass and foliage colors, using hardware coloring

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6441]
I suggest to make it somehow possible to generate maps in which the grass and foliage (e.g. leaves) color is determined by the biome. The nodes themselves are supposed to use hardware coloring (which already works). So the important missing thing here is that the map generator does currently not colorize any of the generated nodes. The Biome API only allows you to place grass and dirt with grass, but it does not allow you to colorize them even if the nodes support hardware coloring.

The idea is that there is only one “dirt with grass” rather than a ton of variants which only differ in color. Many biomes use this dirt with grass and colorize this node accordingly. In savannas the color must be very different than in grasslands or jungles.

I'm not entirely sure how to implement this, but I hope you get the idea.

The main use case for this would be MineClone 2, which requires many biomes with a grass cover (dirt with grass = grass block) in which the grass only differs in color. Another requirement in MineClone 2 is that water in swampland biomes has a darker color. This would greatly enhance the visuals of biomes, especially savannas.
I don't care whether Minetest Game would make use of this feature, but the dirt with dry grass node could be removed, if it would be desired.

A theoretial workaround to this suggestion would be to register a node for each single grass color, but this would defeat the whole purpose of hardware coloring and just adds a ton of redundant nodes which I want to avoid. There does not seem to be any workaround for colored swampland water.

**Comment by paramat** [comment]
Similar to #4467 but this request is more clearly explained so i'm not intent on closing it.

I'm not interested so it would have to be coded and maintained by someone else, and i would insist the code is separated so that it does not affect or complicate the code i maintain. Hmmmm has left us with the ability to have multiple biome implementations so it could perhaps be a new one (currently there is only one the 'Biome API' of mgv7 etc.)

The justified use of hardware colouring would be MC-like smooth changes of colour even within biomes, or as you describe when you have very many biomes all with identical grass properties and only differing in colour.

For any biome which differs significantly in character, such as savanna, it is better to use a different node, otherwise all node parameters are identical, which does not allow different crafting, flammability, footstep sound etc. (so MTGame would certainly not remove dirt_with_dry_grass).
Likewise the surface node in a deciduous forest needs to have a different texture (not just a different colour) to that of a rainforest or coniferous forest or grassland.

> Another requirement in MineClone 2 is that water in swampland biomes has a darker color.
There does not seem to be any workaround for colored swampland water.

The current Biome API allows you to place a different liquid in different biomes, if you ask in the forum thread i'll explain how (should be obvious from the biome registration though).
Swampwater is significantly different from normal water so you would want it to have different node parameters and so be a different node. It differs in appearence significantly so only changing colour would be a missed opportunity and quite boring, it needs a different texture.

So i'm saying this is good usage if you want very many colour variations for a single node, but is not good usage if applied to nodes that significantly differ in characteristics.

**Comment by juhdanad** [comment]
The map generator could assign `heat×16+humidity `to `param2` of grass (or other nodes), if requested (the max value of `heat` and `humidity` is 15). For generated trees, maybe manual coloring is required. But you can not colorize flowing water this way because its `param2` is in use. Also all new water nodes woukd require manual coloring.

Since @paramat has recently started creating heat and humidity getter functions, hardware colorization will be able to depend on these values instead of `param2`. I think that would be the correct solution (but requires sending biome information to the client, which is possible due to the comparibility break).

**Comment by tobyplowy** [comment]
> The main use case for this would be MineClone 2,

And farlands I cud definitely use that instead of registering 6 (will be more in the future) difrent blocks for grass

**Comment by paramat** [comment]
There's very little advantage to hardware colouring until you get to large numbers, maybe 64+, it just reduces the number of node definitions that need transferring to the client. There's no need for this requested feature if you are using one colour per biome, you can already colour nodes per biome by using separate nodes, which themselves can use static (non param2) hardware colouring.

The 'per biome' part of the request title is not ideal. I'm treating this to be a request for smooth colour changes within biomes as MC does. The request is for 'per-node encoding of heat and humidity into param2'.

Trees use schematics, you would have to alter param2 of leaf nodes per-tree, which means altering schematic code. I don't feel that is justified, especially since there's little need for smooth colour change of trees, each tree is a species and has it's own colour.
So i'm :-1: for applying this to trees.

This request is mainly about 'copying MC' which itself is not a valid reason, however there is interest for smooth colour changes for better reasons that have nothing to do with MC.

Having smooth surface node colour change when everything else about biomes and decorations is abrupt and separated into areas doesn't make sense, and is partly why i dislike the way MC does this.
It would make more sense if biome decorations also changed smoothly and there was no division into separate defined biomes.

Adding this requested feature onto the current Biome API would therefore not make much sense, however adding another Biomegen implementation just for this feature would mean an almost duplicate with smooth param2 setting added, which is not justifiable, a new Biomegen has to be a complete well designed system.

So if we add param2 encoding for surface nodes it has to be added to the existing Biome API, but i don't consider 'copying MC' enough justification.
I'll think on it and maybe we can come up with more good reasons to add per-node param2 encoding which would then encourage me to work on it and add it.
The main problem is that it doesn't fit well with our abrupt and separate biomes.

**Comment by tobyplowy** [comment]
@paramat I'm only registering 6 types of grass (excluding the default ones) because I don't want to register a ton of nodes if I could just change the colour of every biome without having to register a new grass and leave block per biome that would be amazing (I would go nuts with the colors)

also the fact that this is in Minecraft doesn't matter I don't want this feature Because It's a Minecraft feature I want it because it Looks Good and becouse it's more efficient (an improvement and engine feature)

And I think wuzzy agrees with the above +he needs this for mineclone2 (I think Mineclone is an amazing Project It shows the power of minetest)

But at the end it seems like you paramat makes the choice so what will it be?

**Comment by paramat** [comment]
If you want to register for example 100 grass nodes for 100 biomes, you can register them in a loop that alters the static hardware colouring value for each, so there's no need to copy-paste 100 node registrations.
Likewse you could register the biomes in a loop.
For per-biome usage and your usage this feature is not needed at all.

This requested feature does not increase in-game efficiency for your usage or for any usage, it just reduces the number of nodes sent to the client. With per-biome colours and with a maximum biome number of 256 it would be very rare for someone to need >128 colours, and 128 nodes is not much to send to a client. If you use static hardware colouring then each node does not need a texture, which reduces the amount of media to send.

**Comment by paramat** [comment]
> Since paramat has recently started creating heat and humidity getter functions, hardware colorization will be able to depend on these values instead of param2

No those would not be used, the bulk data heat and humidity maps already present would be used.

**Comment by tobyplowy** [comment]
@paramat ok True but How do you get a Smooth color gradient?

> you can register them in a loop that alters the static hardware colouring value for each

But that will register a ton of unneeded blocks I whant all those 100 colors to be 1 block
And depending on the biome (the grass block or leave or whatever will change color)

**Comment by Wuzzy2** [comment]
Yeah, smooth color transitions is what would be great.

My suggested implementation is not ideal, but the general idea of having different grass colors still stands.

Paramat, if you insist on me registering more nodes, I can live with that; luckily I would not end up with too many nodes.

**Comment by paramat** [comment]
> ok True but How do you get a Smooth color gradient?

You write equations that define the R G B values depending on the loop iterator.
Then carefully place the biome points to create the colour change.

> But that will register a ton of unneeded blocks

I know but i have explained that 100 or so nodes is not much to send to a client so is not really a problem, for your per-biome usage you don't need this feature.

**Comment by Wuzzy2** [comment]
Remember, I only requested a *per-biome* coloring. Please forget about all the “smooth” transition stuff for now. I think you just got way ahead of yourselves. ;-)

Per-biome coloring alone would already greatly simplify the necessary code. Even Minetest Game has 2 grass colors.

Smooth color transitions within biomes (e.g. with heat or humidity) are a completely different topic and out of scope. I think for something like this there is a completely different implementation required, probably client-side.

The problem I have with registering 100s of nodes is not that it might be inefficient, but that it's a pain in the ass to maintain code-wise, because of all of the edge cases you have to catch.
I said earlier that I can live with registering lots of nodes but yesterday I tried exactly that in MCL2 with only adding 1 grass color. It took me almost the entire day because I not only needed grass blocks, but also many grass plants which are required to match in color.

Also, it kinda defeats the whole point of having a hardware coloring system if the most obvious use case—setting the grass color—is not possible. You end up registering one node per grass color anyway, thereby leading to the exact situation which hardware coloring wanted to solve.

**Comment by MarkuBu** [comment]
Just a hint: you can't use param2 for leaves because it has to be 0 for leave decay.

I don't know how hardware colouring works, but maybe one bit in param2 is not used, but this would probably break existing worlds

**Comment by MarkuBu** [comment]
Another hint: I would prefer if plants, mostly grass, would be able to use meshoptions at map generation, especially the horizontal displacement.

Grass can only have one paramtype2: hardware colouring or meshnode

**Comment by paramat** [comment]
> I only requested a per-biome coloring

Ok, but we can do this already and it is much better to use a separate node to do this as that allows useful changes in node parameters.

If you use hardware colouring you are essentially making all these nodes the exact same node, grass and leaves of different colours are very likely to not be the same node because they are different types of grass and leaves, for example MTG green grass and dry grass are very different, with differing properties. The way MC considers all grass identical whatever the colour is boring and limited.

So this suggestion brings little or no advantage, and it is based on wanting to copy the bad ideas of MC, which is no good reason.

> Also, it kinda defeats the whole point of having a hardware coloring system if the most obvious use case—setting the grass color—is not possible

No. Varying grass colour is not the most obvious use, people only think about that due to the bad idea MC has of using it for grasses. People need to think about MC less.

Leaves can't use param2, but in a subgame you could recode leafdecay to not depend on param2, then you are free to use hardware coloured leaf nodes and set the param2 in the schematic decoration.
Likewise all simple decorations give you the option of setting their param2.
The only thing missing is param2 of the surface node, but i'm not going to add that for reasons above.

**Comment by tobyplowy** [comment]
@paramat i think you should reopen this @Wuzzy2 is not the only one hoe needs this 

> all grass identical whatever the colour is boring and limited.

Yeh becouse grass is so exciting and interesting in real life :/
It's just grass I don't want it to do anything special!
The only Special thing I Want it to do Is it to be colored depending on the biome it's in!

I know why you don't want this to be added its because you think it's copying Minecraft and you don't want people to think minetest is a Minecraft clone but guess what it is going to happen anyways If you have blocks in your game or you can place and break stuff then you're pretty much considderd a Minecraft clone
Stop trying so hard to not be

You are only hurting the project with that attitude

**Comment by MarkuBu** [comment]
calm down @tobyplowy 

To be honest, I like the color blending in Minecraft, even it is sometimes strange to see a tree in multiple colors, and I would love to see this in Minetest. 

But I can see the difficulty to implement this in Minetest. param2 is highly overused and I would love to see param3, but as far as I know this is nearly impossible because node id, param1 and param2 are stored in a 32bit integer. So no room for more storage. Adding a new byte would break existing world databases.

**Comment by paramat** [comment]
No-one needs it because it can be done already without much more effort (and with advantages).

> The only Special thing I Want it to do Is it to be colored depending on the biome it's in!

As i wrote you can do that already easily.

> I know why you don't want this to be added its because you think it's copying Minecraft

No, i disapprove for good reasons stated, 'not copying MC' is not a reason to disapprove a request, just like 'copying MC' is not a reason to add a feature.

> you don't want people to think minetest is a Minecraft clone but guess what it is going to happen anyways

I don't care if people think MT is a MC clone, many will, that's still no reason to copy MC.

> Stop trying so hard to not be

Not just me, MT is not a MC clone and no core dev wants it to be.

**Comment by tobyplowy** [comment]
> Not just me, MT is not a MC clone and no core dev wants it to be, it never will be.

I'm not saying that you should copy Minecraft but you (with you I mean the core team) shouldn't go out of your way to not do so because it's decreasing your (teams) creativity

NOTE paramat that I really want to help and I whant minetest to have a bright future
You may think otherwise but if that was the case I would have left a long time ago!
