### ISSUE TITLE
Server menu: Show ping ms in tooltip

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#6493]
In 0.4.16, i tried to hover a cursor to a ping icon it will just say "Ping" on the tool tip, doesn't have an information how ms (milliseconds) gonna take.
![image](https://user-images.githubusercontent.com/13905392/31182308-31bab018-a92c-11e7-8826-090e552e9216.png)

**Comment by paramat** [comment]
See #6504 we're agreed that 'ping' is meaningless, we are discussing what value to replace it with, are you then requesting this new value to be shown as a tooltip? Maybe this can be done in that PR too.

**Comment by WSDguy2014** [comment]
@paramat
> are you then requesting this new value to be shown as a tooltip?

Yes

> we're agreed that 'ping' is meaningless

Wait the minute, is that weird way to use the connection speed type to "lag" instead of "ping"?

**Comment by paramat** [comment]
Well, read the 3 points in the first post of #6504 that's what i mean.

**Comment by FullTimeLinux** [comment]
I'm going to bump this and hopefully take it since it has almost been a year since this issue was opened.

**Comment by Voaz** [comment]
I spent some time in attempt to investigate in this and stuck. What I've found:
tab_online:
`image_column(fgettext("Ping")",padding=0.25;" ..`
In the `image_column` function tooltip sets and it gets first argument of the function `fgettext("Ping")` which is just a text. 
Next I tried to add a `ping` right there by calling it like:
```
local serverlist1 = menudata.search_result or menudata.favorites
...
image_column(fgettext("Ping") .. (serverlist1[1].ping or ": test")) .. ",padding=0.25;" ..
```
but it will set the same value for all servers in the list. 
How I expect it should work:
- The main point is instead of predefining data we should pass it as parameters.
- instead of calling image_column here we will just put the mock 'image,tooltip=text...' and set both values in `render_serverlist_row()` 

The question is how to set a value `text` for the `tooltip`?

**Comment by sfan5** [comment]
A quick look at the [documentation](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2441) suggests that is not possible, since you can only set cell values and a tooltip per column.

**Comment by Voaz** [comment]
@sfan5, thanks for reply! Now I see... Well, I tried))

**Comment by Zughy** [comment]
The PR Paramat mentioned was closed because current ping is useless and because there was no agreement about what alternative could be implemented instead. #6763 also asks for a complete "lagometer" removal, which SmallJoker and Paramat agreed on (it also has a "Supported by core dev" tag). This should be closed, as it's evidently not supported (anymore)
