### ISSUE TITLE
0.4.17 release

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#6542]
Some months ago we said we should release in early november.
As it's in 2 weeks only, i propose to define a date to release 0.4.17. End of november sounds reasonable to let 1 months of backports + 2 weeks of tests.

I propose 26 november or 3 december as a release date

use
* 👍 for 26 november
* 😄 for 10 december
* 👎 for other

**Comment by tobyplowy** [comment]
@nerzhul why not around end december you know Around Christmas 
So it looks like a gift (it will have more impact like this)

**Comment by nerzhul** [comment]
@tobyplowy around christmas it's holidays for us too, we can be busy in our families, in holidays, it's not optimal, it's better to release before that date :)

**Comment by dsohler** [comment]
Don’t rush it. Set a feature freeze and have a reasonably long bug fixing period and try to fix as many bugs as possible before release.

**Comment by stujones11** [comment]
I would simply make a 0.4.17 point release right now and concentrate on getting 0.5.x released instead, the current split is a maintenance nightmare for modders and server operators alike.

**Comment by Wuzzy2** [comment]
Do whatever is best for the quality of the project.

**Comment by stujones11** [comment]
> Do whatever is best for the quality of the project.

Ultimately, I think we all agree on that point, only we have different ideas of what that actually is. IMO it seems senseless wasting 6 weeks developer time on something that will soon be obsoleted. A 0.4.17 release could be made by simply reverting/undoing the breaking commits, that's only player model offset AFAIK.

**Comment by Wuzzy2** [comment]
I thought the sunken player models bug is already fixed in Minetest. IIRC it's the subgames which need updating. Has this been fixed in Minetest Game yet?
Because what's the point of releases if they are broken anyway?

**Comment by stujones11** [comment]
>  Has this been fixed in Minetest Game yet?

It's fixed if you have the right MTG + MT client/server version combination ;)

**Comment by paramat** [comment]
Hmm stujones has a point. The idea of 0.4.17 was to provide a final 0.4 version for those who want to stay with 0.4 for a while.

However i do not want to encourage people to stay on 0.4 as there are good reasons to encourage people to move to 0.5.0 as soon as possible. For example enforcing CSM restrictions (flavours) is only possible in 0.5.0. Also, some nasty forked Android apps may not update to 0.5.0 so we have a rare chance now to encourage mobile players to switch to the official app (which hopefully will be worked on and improved soon), there will be more encouragement if servers move to 0.5.0 earlier than later.

For 0.4.17 let's not put too much work into it, just 0.4.16 stable plus a few major bufixes, no features.

**Comment by Wuzzy2** [comment]
I agree. Better go on with 0.5.0 instead of wasting time with 0.4.17. I don't even understand why you want to have a 0.4.17 in the first place. Have people been requesting this?

**Comment by paramat** [comment]
> a 0.4.17 release could be made by simply reverting/undoing the breaking commits, that's mostly just the player model offset AFAIK.

That would not be simple actually, there are huge amounts of interlinked breakages, that started immediately after 0.4.16 was released, those would be a nightmare to remove.

**Comment by paramat** [comment]
> Have people been requesting this?

Some have yes, but it seems sometimes for the wrong reasons: "because of the 0.5.0 breakages happening, to avoid upgrading to 0.5.0 for as long as possible".

Delay in servers and players upgrading to 0.5.0 is what will cause the most disruption, because there will be more of a split community, modders having to provide 2 versions of their mods etc. Not making a 0.4.17 release will encourage people to upgrade as well as removing a large amount of dev work and release testing.

**Comment by tenplus1** [comment]
Personally I would rather skip 0.4.17 altogether and have players migrate straight to 0.5.0 so that mods can be fixed already for the new player model which will have minetest sitting on a new base that is easier to add to and allows us modders to use newer functions.

**Comment by sfan5** [comment]
Reminder that a list of commits planned for backporting is already [here](https://github.com/minetest/minetest/projects).

**Comment by stujones11** [comment]
> I'm beginning to feel we should not bother with 0.4.17.

I think there probably should be a 0.4.17 version at some point that will eventually mark the end of the 0.4.x series, however, I don't think it needs to be anything special.

Another possible option would be make some sort of interim release that has the player offset and CSM flavours, that would at least mitigate some of the current problems.

**Comment by TekhnaeRaav** [comment]
As a user/modder I do think that a 0.4.17 release would be really good. But also, I think it would be best to just release it right now, nothing special, just to kind of get the current features and updates out there. This way you can maybe push the 0.5.0 release date up a bit for a better, bigger release.

**Comment by paramat** [comment]
Well as i wrote we can't simply tag or point release because the version would then contain large amounts of 0.5.0 breakage and essentially would be 0.5.0. The 0.4 series ended a few days after 0.4.16 was released.

**Comment by dsohler** [comment]
Properly tag the releases and you can always point to a specific version but still be able to develop new stuff. Or use branches you merge later.

**Comment by stujones11** [comment]
> Well as i wrote we can't simply tag or point release because the version would then contain large
> amounts of 0.5.0 breakage

I am not sure just how much breakage there is currently, I initially thought it might be easier to just revert the breakage than backport all the fixes, however, if this has gone beyond only the player offset then maybe not. In that case just backport that which can be easily backported then be done with it, whatever you want to call it is unimportant, really.

**Comment by nerzhul** [comment]
@stujones11 no it's impossible to revert as all developments are based on the first breakage, C++11 compiler support. It's easier to backport as there are few bugfix commits, these are the only commits to backport for 0.4.17

**Comment by paramat** [comment]
I feel we should not release a version 0.4.17, anything that discourages or delays upgrade to 0.5.0 is bad in several ways.

**Comment by jastevenson303** [comment]
Backporting is nice, though.

**Comment by BluebirdGreycoat** [comment]
I agree that it is better to move to 0.5.0 sooner rather than later.

My main concern is that the breaking changes will not stop after 0.5.0. Previously minetest had a history, as far as I know, of being relatively stable in terms of network breakages. A server owner could upgrade their server without worrying about preventing half their players from joining.

If the breaking changes in the network protocol do not stop, then the Minetest community will be hopelessly split between versions. This is not a good place to be.

**Comment by dsohler** [comment]
> This is not a good place to be.

Update early, update often.

**Comment by BluebirdGreycoat** [comment]
> Update early, update often.

Most players (99% probably) don't have the ability to update their client at will. Thus, if the latest version on Github changes the network layer then a server cannot upgrade to it immediately without cutting players off, and instead must wait for players to update first, which can take a long time.

For a real example, take my own server. There are a lot of server-side performance enhancements and other good stuff in the dev versions beyond the last stable release, but I cannot upgraded my server to use them because of network incompatibility. All my players are still on 0.4.16 or 0.4.17. So I have to wait.

I understand the network breakage is necessary for 0.5.0 and I'm not really troubled by it *yet*. What I want to see happen is for the network protocol to become stable again during further development after the official release, so that servers (including mine) can use the latest dev versions as much as possible. This was the state (with a few exceptions I believe) before 0.5.0 was being worked on.

So to come back to this,

> Update early, update often.

That's what I used to do, server-side, until the breaking changes started comming in. I'd like to see the project return to a state allowing sever owners to do that.

**Comment by rubenwardy** [comment]
> Edit: and before someone tells me that 0.4.17 doesn't exist yet, I should point out that I have a client right in front of me that reports 0.4.17 as its version. So somehow it got out already.

blame nerzhul. That's 0.4.16 with a different name

**Comment by sfan5** [comment]
> Most players (99% probably) don't have the ability to update their client at will.

If you look at the last [server list statistics](https://kitsunemimi.pw/tmp/serverlist_stats_2017-03-17.txt) (which are skewed slighty towards mobile due to various factors) you can see that ~11% of players are on Desktop.
Which means they <b>do</b> have a way to just upgrade to a new version if they want to.

> What I want to see happen is for the network protocol to become stable again during further development after the official release

The 0.4 -> 0.5 transition poses an <b>exception</b> to the rule of providing backwards compatibility between versions.
You can expect all of the future 0.5.x releases to be compatible with eachother, just like it was for 0.4.x.

> I should point out that I have a client right in front of me that reports 0.4.17 as its version. So somehow it got out already.

Yes that was a mistake.

**Comment by BluebirdGreycoat** [comment]
> You can expect all of the future 0.5.x releases to be compatible with eachother, just like it was for 0.4.x.

Ah, that clarifies.

**Comment by paramat** [comment]
> Most players [...] don't have the ability to update their client at will. Thus, if the latest version on Github changes the network layer then a server cannot upgrade to it immediately without cutting players off, and instead must wait for players to update first, which can take a long time.

> All my players are still on 0.4.16 or 0.4.17. So I have to wait.

That's the wrong way around, waiting for players to update first means you wait forever, and some Android forks will never be compatible with 0.5.0, such as MultiCraft (with > 1 million downloads).
Delay in updating servers means less encouragement for players to update, which means less encouragement for servers to update ... which then creates a split in the MT community.

Players will be expecting servers to update as the signal for them to update, if you wait for them they will tend to not update. Why would they update to 0.5.0 if the server they play on does not? They would not be able to use the server. Obviously the server has to update first.

Updating the server to 0.5.0 quickly encourages app users to switch to the official Android app, which by that time will (we hope) be improved (at least the controls). This will then help everyone's servers by reducing the numbers of players using irritating and nasty Android forks.
The remaining desktop players will be able to upgrade to 0.5.0 straight away.

So it seems best to update servers to 0.5.0 quickly, even though this will force some players to change their choice of Android app. They may not like this disruption at first but as long as the official app is improved by then it will be better for them as they will no longer be using apps with adverts, pay-for-privilege etc.

**Comment by TekhnaeRaav** [comment]
Forget my earlier comment. Now looking at it 0.5.0 release I think is for the better.

**Comment by numberZero** [comment]
Please don’t. 0.4.17 would take too much precious developers’ time which is needed for 0.5.0.

**Comment by paramat** [comment]
We also have very little dev time at the moment, dev is very quiet, nerzhul and some other core devs are busy with RL currently. MTG is mostly just me at the moment and i have lots of engine work too.

**Comment by paramat** [comment]
Server owners don't like to update too often, releasing 0.4.17 3 months before 0.5.0 will greatly reduce the appetite for moving to 0.5.0. It's like eating a fast food meal 1 hour before the highest quality feast in 5 years.

**Comment by paramat** [comment]
Features that should not be in 0.4.17:

Emit liquid sound if the player walks in liquid
Make direct item selection keys freely bindable
Minimap: Leaner minimap arrow makes it easier to see the direction 
New lighting curve (because it's not optimum yet and subtle shadows have disappeared)
Safe digging and placing
Item drop: Tune to land exactly 2 nodes away with level view
Add mute setting (toggled by the mute key and in the volume menu)
Retrieve a small cone of blocks in the direction of the players velocity. 
Reduce server FOV with forward speed
Item entities: Enable item collision detection for sudden movement
Sounds: Add falling node sounds
Allow zoom to actually show more data (as more control is needed, PR coming)
Load files from subfolders in texturepacks

**Comment by tobyplowy** [comment]
Please don't make a 0.4.17 release
Go for the 0.5.0 release insted and take your time to make this update something special after all we are halfway through the development of V1 :)

Also i agree with the above reasons explained by paramat :)

**Comment by paramat** [comment]
I'm neutral about releasing 0.4.17 now, it's obvious that MT 0.4 should be left in a good state so bugfixes will need to be backported at some point.

However i feel we should release 0.4.17 ASAP to not be close to 0.5.0, otherwise this will reduce the number of people updating soon to 0.5.0, which is essential as explained above.
Unfortunately some have the idea ofreleasing 0.4.17 at the same time as 0.5.0, this will do the most damage to MT as 0.4.17 will be seen as an alternative to 0.5.0 and will minimise the number of people updating soon to 0.5.0.
There is the argument that new bugfixes will be found and should be backported to 0.4.17, however bugfixes will always be made so we have to draw a line somewhere, best draw it now, future bugfixes can be backported to a 0.4.18 release.

So please can we release 0.4.17 now?

**Comment by paramat** [comment]
Continuing discussion from https://github.com/minetest/minetest/pull/6718#issuecomment-348736344
/////////////

I've noticed some people (not you Ezhh) have a misunderstanding of 0.5.0, because we call it a 'breaking release' some seem to think lots of things will be broken, only compatibility is broken, mods and worlds are not, apart from player model vertical offset (quickly fixed in blender as i'm sure the mod authors will do quickly before 0.5.0), and the position of attachment of players to vehicles.

So unfortunately there seems to be an unnecessary amount of hesitation to updating to 0.5.0.
Backporting CSM flavours will reduce what 0.5.0 has going for it, adding to this problem.
I know that my approach will be unpopular with some, however i believe it is in the best interest of MT as a whole, and i'm prepared to be a little unpopular to do the right thing.

However it's clear that, as long as the official Android app is improved before 0.5.0 (i think we should delay 0.5.0 until it is good) then moving players to the official app will bring a huge benefit to servers.

You have said you are concerned about losing players, assuming the official app is improved in time, how will you lose players when they can use that?

Assuming CSM flavours cannot be backported, which seems likely, 0.5.0 will also bring flavours and my upcoming 'master disable', so it seems updating to 0.5.0 is an advantage.

Server owners continuously state how the more unpleasant unofficial apps are a huge problem, along with hacked clients. We now have a 'once in 6 years' chance to move a huge amount of players onto the official app. Because the official app is not hacked this will also reduce cheating clients.
The forked apps will soon catch up with 0.5.0 so every week of delay before updating will reduce this chance.

//////////////

Here's a big issue, i know that Multicraft will not be updating to 0.5.0, and it has > 1 million downloads, which seems to be 10 times total official MT downloads. As servers update to 0.5.0 these players will be forced to move to a new app. Mulitcraft is one of the better behaved apps, if we don't provide a good official app they are likely to move to worse ones. If servers update to 0.5.0 quickly there's more chance these players will move to the official app, before the unofficial ones catch up.

**Comment by nerzhul** [comment]
i don't know who merged jsoncpp update to backport-0.4 but it's wrong. If i'm correct this release is only compatible with C++11 compliant compilers

**Comment by nerzhul** [comment]
@paramat it's very sudden, i move the date from 3 december to 10 december

**Comment by sfan5** [comment]
A few points:
1) Releasing an eventual 0.4.18 later next year would give server owners the feeling that they can stay on 0.4.x just fine and would remove reasons for them to move to 0.5.
I suggest releasing 0.4.17 <i>just before</i> 0.5.0, while making it clear that it is a bugfix-only release and the last in the 0.4 series.
2) Backporting flavors to 0.4.17 <b>will not work</b>.
If you keep compatibility, people can just use older clients, making flavors pointless.
If you break compatibility, server owners can't just upgrade to 0.4.17 without worry and also completely goes against what the backports branch is supposed to do.
3) I added the jsoncpp update to backports, will remove when I have the time.

**Comment by nerzhul** [comment]
@sfan5 okay, valid point, no problem it was just a question, flavour are 0.5 only, motivating server owners to move to it

**Comment by stujones11** [comment]
Would it not be easier to just temporarily disable CSM for the backport release? I realize this will not stop dedicated cheaters from using older clients but it will raise the bar a little. If there could also be an option for servers to reject older clients then all the better, though I am not sure if this is possible.

**Comment by paramat** [comment]
> Releasing an eventual 0.4.18 later next year would give server owners the feeling that they can stay on 0.4.x just fine and would remove reasons for them to move to 0.5.

Good point.

> Backporting flavors to 0.4.17 will not work.
If you keep compatibility, people can just use older clients, making flavors pointless.

Yeah.

> Would it not be easier to just temporarily disable CSM for the backport release?

Good idea. Does any server owner intending to use 0.4.17 want client-provided CSM? I doubt it.

**Comment by dsohler** [comment]
> Does any server owner intending to use 0.4.17 want client-provided CSM?

Dos any server owner EVER wants client-provided CSM? :smile:

**Comment by Wuzzy2** [comment]
I'm now indifferent about 0.4.17 vs 0.5.0.

**Comment by sfan5** [comment]
> > Would it not be easier to just temporarily disable CSM for the backport release?

> Good idea. Does any server owner intending to use 0.4.17 want client-provided CSM? I doubt it.

Note that this is similarily ineffective at combating the problems CSM brings.
(People can just use older clients that have csm support enabled.)

**Comment by paramat** [comment]
Ah of course.

**Comment by stujones11** [comment]
> People can just use older clients that have csm support enabled.

It won't stop determined cheaters, nothing will. If the windows builders update their binaries and the CSM section of the forum is closed then I think it would at least stop most of the opportunists.

It could be some time until 0.5.0 is ready and I doubt that server owners will appreciate the 'motivation' to upgrade once it is. I think we can all agree that CSM should not have been in 0.4.16 and it would be trivial to disable it for the backport, however ineffective it may be.

**Comment by CloudyProton** [comment]
Weren't we looking at a 10 December release?

**Comment by paramat** [comment]
No, just before 0.5.0.

**Comment by dsohler** [comment]
30 people voted for December 10.

**Comment by paramat** [comment]
Hmm actually 'just before 0.5.0' was a suggestion by one dev, not sure what we are doing.

**Comment by paramat** [comment]
Because 'backports 0.4' is a bugfix version you can safely update to that, it is 0.4.16 stable plus bugfixes and will continue to have non-breaking bugfixes added to it.
Then when 0.5 is released the final version of 'backports 0.4' will be released as 0.4.17 stable.
0.5 may still be months away.

**Comment by JurajVajda** [comment]
When 0.4.17 is just 0.4.16 with bugfixes why we cannot update it easily with ppa instead of learning on how to build minetest from scratch?

**Comment by paramat** [comment]
^ @sfan5

**Comment by sfan5** [comment]
Because it's not released yet? What kind of question is this.

**Comment by VanessaE** [comment]
I imagine he's talking about a PPA equivalent to the daily-builds one, but drawing from the backport-0.4 branch.

**Comment by JurajVajda** [comment]
Yes @VanessaE got my question right. There is no point of waiting for release which are just bugfixes and will be released at the same time as a breaking new version...server owners would like to have these bugfixes asap since there are some important security and functional fixes what are broken in stable release atm and are misused now by i.e. android users (far digging punching) and more.. so my point is to make ppa 0.4.17 daily builds available until 0.5.0 is out...

**Comment by sfan5** [comment]
I don't manage the PPAs, so you'll need to talk to someone else about that.

**Comment by paramat** [comment]
Sorry for wrongly tagging you sfan5.

**Comment by Lourens-Rich** [comment]
Please, release 0.4.17 as soon as you can. You can stabilize 0.5 more and players will be playing on stable branch longer.

**Comment by nerzhul** [comment]
i agree @Lourens-Rich it's important to release the massive bugfix in stable branch

**Comment by paramat** [comment]
I agree with releasing 0.4.17 soon, as 0.5.0 may be several months away. We can always release a 0.4.18 later.

**Comment by paramat** [comment]
We shouldn't leave too much time between releases, it's been almost 10 months. Then i think we could release a 0.4.18 after 0.5.0 to do the final cleanup for the MT0.4 series.

**Comment by nerzhul** [comment]
then just decide to define a date, maybe 1st april ?

**Comment by paramat** [comment]
I'm wondering how much testing will be needed.
We will need to find and merge some remaining bugfixes, there is a TODO in the backports PR thread.
I need to do the same for MTG.
Maybe we can try to discuss this on Saturday or sometime weekend on IRC?

**Comment by SmallJoker** [comment]
~Fixed in~ Solved by 0.4.17
