### ISSUE TITLE
Riverbeds are not generated if using same node for river water and water

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6593]
If you use the same node for both “normal” water and river water, the riverbeds fail to be generated correctly. Instead of using `node_riverbed`, `node_top` is used for the riverbed.

How to reproduce: In a minimalistic subgame, do:

- Define a water node: `minetest.register_node("example:water", water_definition`)
- Use it for default water: `minetest.register_alias("mapgen_water", "example:water")`
- Use it for river water, too: `minetest.register_alias("mapgen_river_water", "example:water")`
- Register a test biome with `minetest.register_biome`
    - `node_top="example:dirt_with_grass"`
    - `node_riverbed="example:sand"`
    - `depth_riverbed=2`
    - (add the other usual boilerplate)
- Generate a map in valleys mapgen and search for rivers

Expected result: The rivers have `example:sand` as riverbed.
Actual result: The rivers have `example:dirt_with_grass` as riverbed. Even worse: All decorations which would spawn on this node will now also generate inside rivers, causing things like flooded trees, bushes, etc.

Version: 0.4.16

See also: https://github.com/Wuzzy2/MineClone2-Bugs/issues/398

**Comment by paramat** [comment]
This happens because the only way mapgen code knows when to place riverbed nodes is when river water is detected above.
You can add a second identical node with a different name and use this for the mapgen alias.
Maybe we can add a feature to buckets that returns the ocean water node when the riverwater node is dug, so that you would get the same node from both sources?

Using 1 node for both ocean and river water is risky because the horizontal spreading behaviour of ocean water 'liquid_renewable = true' makes the water sources of sloping rivers spread out horizontally with the danger of them overflowing their banks. This is not so noticeable in mgvalleys as it's rivers do not become steep.

**Comment by paramat** [comment]
I've had an idea, will investigate.

**Comment by Wuzzy2** [comment]
Well, would it be at least possible to disable river water in `valleys` for a given subgame?
