### ISSUE TITLE
Riverbeds are too small

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6594]
If you look closely at riverbeds, you will notice the riverbed is only generated directly below the river water source nodes. There is no riverbed below flowing river water.
This can create ugly situations like river water above dirt-with-grass:
https://i.imgur.com/k5VCYeO.png

Here, the sand is the riverbed, and the dirt-with-grass is the `node_top`. The dirt just came from an ABM (ignore it). As you can see, the sand is only below the source nodes, not the flowing ones.
I think this should not happen.
This is more obvious in areas in which the river water is shallow.

Also, there is no riverbed a few nodes above the water. For more realistic riverbeds I would expect that *sometimes*, the riverbed is a bit higher than the river itself.

IMO current riverbet generation is too simple and the resulting riverbeds are too small.

**Comment by paramat** [comment]
At mapgen time only water sources are generated, flowing water comes later when the sources flood out. So flowing water cannot be detected to enable placement of riverbed nodes below.

As explained in the other thread, riverbed nodes can only be placed by detecting river water above, so riverbed nodes extending wider is not possible. The only information about the location of rivers comes from basic (stone, water and air) terrain generation so the only information usable is the presence of river water nodes (because river water is one of the 4 'base terrain' nodes).
