### ISSUE TITLE
Allow adding fallback textures for items

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6616]
[numberZero suggested](
https://github.com/minetest/minetest_game/pull/1569#issuecomment-343699437) adding fallback textures for items, if the texture is missing, the fallback texture is used instead (if also missing use the unknown_item texture).
This could be used for e.g. dyes, if the texture is missing, a colorized white dye texture is used instead.
It eases taking care of texture pack compatibility, thus wool, dyes and other colour mods can use the colorize texture modifier.

**Comment by paramat** [comment]
That's not what numberzero suggested, he suggested manual textures falling back to colourised ones.

I disapprove of adding fallbacks for a mistake, just add the missing texture. Why would someone go to the effort of creating a different fallback texture instead of just adding the one missing? Makes no sense.
:-1:

**Comment by HybridDog** [comment]
paramat, somebody could register lots of nodes using a for loop and set a different texture with modifier for each node

fallback textures would make it difficult for mods to find out which textures an item has, e.g. the stairs mod can't simply test if the texture is a string or table.

**Comment by paramat** [comment]
Ok so it's a bad idea?
