### ISSUE TITLE
Ability to change dig params on dig, and proceed with the digging

### ISSUE THREAD

**Issue by lisacvuk** [minetest/minetest#6652]
Right now, if we change on_use of a tool, it no longer digs.

**Comment by paramat** [comment]
Do you mean being able to change tool capability halfway through digging a node? Or change it in an 'on dig' function?

**Comment by lisacvuk** [comment]
I want to be able to change duration of the digging, and other dig params.

**Comment by paramat** [comment]
That is no clearer.

**Comment by lisacvuk** [comment]
Let's say a pickaxe takes 2s to dig a node; I want to be able to change that to 1.5s if the player has 26 HP, and send him a chat message, 'Hello'.

**Comment by paramat** [comment]
Ok, i guess once an 'on_use' function has been called digging is already underway, so you would be trying to change the tool's capabilites halfway through a dig, very non-trivial and seems not justified. Sending the chat message will work though.

**Comment by raymoo** [comment]
I don't necessarily want to be able to modify dig params, but I do want to be able to decide whether having `on_use` disables digging or punching, since if `on_use` conflicts with only one of those, you might still want the other functionality to be present. E.g. a fire mace that can either smelt nodes or burn people.

**Comment by paramat** [comment]
Any core dev support? (i'm opposed).
