### ISSUE TITLE
Wield Items are Shaded Incorrectly

### ISSUE THREAD

**Issue by Jordach** [minetest/minetest#6697]
This is from git commit 20a85d7 (or last known sfan5 windows build)

When compared against the same texture generated for an entity, (64x64 texture in the Minecraft 1.8 format) it is generally darker than the entity, and the player entity in third person.

Code relevant to this issue (generates both colour for both wield item and player entities);

https://github.com/Jordach/Solar_Plains/blob/master/mods/wardrobe/init.lua#L899

and 

https://github.com/Jordach/Solar_Plains/blob/master/mods/wardrobe/hands.lua#L36

A visual demonstration of this issue can be seen here:

https://jordach.net/images/duggcklzgpllfucve.png

(Both models use the same base skin texture and clothing parts.)

Where, given the hex value #FFFFFF, the wield item turns into a medium grey, or #9f9f9f and #c6c6c6 hex values, respectively. This also occurs on regular, extruded tools, such as a pickaxe or shovel.

This shading is almost consistent with world mesh - but is inconsistent with entity meshes, which use the same set of origin textures.

This can lead to wield items looking wrong despite the original texture looking fine in the first place.

Edit:

Potential solutions - give wield meshes a brightness level (and side shading) that is closer to entities rather than world mesh.

Alternatively, for the challenge, unify the shading algorithms between the world, wield and entity mesh systems.

**Comment by numberZero** [comment]
![screenshot_20171229_023916](https://user-images.githubusercontent.com/7352626/34425944-7c6088b4-ec42-11e7-8f8c-451a2ab85725.png)

Shaders enabled, tone mapping disabled.
The difference is negligible. 0.4.16 looks the same. So the problem is not in the wield mesh, but either in the mod or in texture combining.

**Comment by paramat** [comment]
@Jordach 
> A visual demonstration of this issue can be seen here:

That image cannot be viewed, do you still have it? Please drag images into comments to host them at GitHub.

**Comment by paramat** [comment]
When the player view is level, the wield is unaligned to the world, tilted forward, and you view the sides of the object not the top. Since face shading depends continuously on face angle it is expected that wield faces have slightly different shading to world nodes. However numberZero's screenshot shows it is fairly well matched.
Entity meshes have no face shading at all so will inevitably be brighter, so those are irrelevant.
So i can't see any issue here.

**Comment by numberZero** [comment]
@paramat Shading is computed *before* the wieldmesh is rotated, so should be exactly the same as in world. The difference in color on my screenshot is probably due to blue emphasis or something similar applied to nodes but not to the wieldmesh.

**Comment by paramat** [comment]
Thanks, seems correct then.
The actual issue here is therefore object shading, players and mobs have no shading, dropped extruded items have (i think) the extrusion side shaded only.
For players and mobs the issue is #6630
