### ISSUE TITLE
Improve Android app before 0.5.0 release, to help move players to the official app

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6731]
~~It looks likely that MultiCraft, which has >1 million downloads, will not be updating to 0.5.0 code and will be incompatible with it.~~ This may be the case with other unnofficial forks of the app, or, they may take time to update.

It looks likely that a ~~very large~~ number of players will be moving to a new app, so we will now have a rare chance to move them to the official app. I know that server owners have been encouraging players to move to the official app, and some players want to, but it's in too bad a state for them.

The Android build system is being worked on, ~~and i have been in touch with forum user 'lordfingle' of Eidy https://forum.minetest.net/viewtopic.php?f=14&t=15495 who hopefully in the new year be able to do some work on Android, however this is not certain and his time is limited, so any more help is very much needed and appreciated.~~

This is worth delaying 0.5.0 for, so i imagine 0.5.0 release will be a few months into 2018.

~~High priority is the controls, it is suggested that a 'virtual joystick' direction control is a good idea, as used by MultiCraft.~~

**Comment by lhofhansl** [comment]
FWIW, I second the sentiment. The controls in the Adroid up need to be fixed. It also should be possible to play more then one local world.

**Comment by stujones11** [comment]
FWIW I have updated my WIP here https://github.com/stujones11/minetest/tree/android-c++11 This successfully builds and runs, on the few devices I am able to test on. Credit goes to @basicer for most of the minetest build fixes.

However, I am not confident enough with these changes to submit a PR just yet. For one thing it turned out to be a happy accident initially, by accidentally omitting the `NDK_TOOLCHAIN_VERSION` from the main `Application.mk`, the later NDKs are defaulting to clang so we end up using clang to compile `libminetest.so` but gcc for everything else. I'm not sure if that is bad or not but it certainly was not my intention. I've since tried using clang for everything but openssl is currently causing problems there.

Another annoying issue is the following message when you launch the app: libnativeloader.so: unauthorized access to /system/lib/libssl.so which is strange because AFAIK we are statically linking `libssl.a`?

Also of note is that fact that I cannot seem to use a statically linked STL like the existing build system, so far everything I've tried results in the app crashing on start-up.

I am posting this in the hope that someone more experienced can pick it up from here, I'd really like to work on improving the app and will have some extra time over the holidays.

**Comment by basicer** [comment]
https://github.com/buildwithpiper/minetest/commit/d9bb638895657e9cda6649310f3820d3485b1afc#diff-63448d1f904a44470e4229b78424978cL86

Is the fix for the annoying message you are talking about.

**Comment by stujones11** [comment]
@basicer thanks, I can't believe I missed that one, I was only just looking at that file a few hour ago =)

With that fixed, I feel a WIP PR might be okay for the remaining issues. I'd prefer if you did that since you can explain the engines patches better than I can, particularly the guiEditBox one had me beat.

**Comment by paramat** [comment]
Your work on improving Android build system is very much appreciated, please do keep the improvements coming.

**Comment by stujones11** [comment]
I've finally managed to get the whole thing to compile with clang and made a few more improvements to the makefiles https://github.com/stujones11/minetest/tree/android-clang

It seems to play well enough although the install is ~ 3Mb bigger, not a massive deal and gcc is deprecated since ndk-r15.

I will rebase and submit a PR at the weekend if nobody beats be to it, I still need to figure out how to update the default game (sunken player)

PS: The x86 version appears to build okay but crashes in the emulator (seems to be when it attempts to dl stuff). I would be interested to hear from anyone able to test on a real device.

**Comment by Wayward1** [comment]
I'd be willing to try the x86 version on my device

**Comment by stujones11** [comment]
@Wayward1 I presume you are not currently able to compile yourself so I have posted my most recent debug apk here: https://www.dropbox.com/s/gs3ubfag8vw6hsk/Minetest-debug.apk?dl=0

Note to others, this a x86 build do not try to run this on arm devices!

**Comment by Wayward1** [comment]
@stujones11, correct. I'm still working on it though. As for the build, it too crashes for me while downloading stuff.

**Comment by MarkuBu** [comment]
An improvement of the mobile app is important. I still don't know how to use it. I wasn't able to do simple things like placing nodes in the crafting grid for a recipe.

**Comment by hoodedice** [comment]
@stujones11 's `android-clang` branch compiles on my end. Took a couple tries, libgmp was refusing to compile, but now I've tried it a couple times after cleaning the directory each time and it works.

**Comment by stujones11** [comment]
@hoodedice Thanks for testing, the build-scripts can be a bit temperamental, esp when building with multiple cores, I find.

Note, be careful when updating the default game, it seems the game and builtin dirs are not removed when you uninstall the app resulting in weird glitches like the sunken player model. It is important that you delete your existing `minetest` dir when including an updated game. This had me stumped for quite a while.

**Comment by Wayward1** [comment]
@MarkuBu, here’s a quick video I made of how to split stacks and single nodes to craft: https://youtu.be/yGQnTx1kJYQ

I’ll probably add this or a better one to my Android builds forum topic too

**Comment by MarkuBu** [comment]
That's fiddly. But thanks

**Comment by stujones11** [comment]
I have noticed that there are no build instructions anywhere for android port (unless I missed them). I think it might help get others involved in improving the app if more people were able to build and test it.

I'd have a go at it but really suck at writing, I'm sure @rubenwardy could do a much better job ;^)

**Comment by hoodedice** [comment]
I am working on that. Should have a draft out in 25 hours.

**Comment by Wayward1** [comment]
There’s this: http://dev.minetest.net/Android

**Comment by stujones11** [comment]
@Wayward1 Thanks, I hadn't seen that, though it is a little out of date. I think you'll need a minimum of ndk-r15x for working c++11 support, though I could be wrong about that, if we do use llvm libc++ it was only just declared stable in the current ndk-r16. I personally can't get it work with anything else, ymmv.

**Comment by Wuzzy2** [comment]
If this is high prority, please also make https://github.com/minetest/minetest/issues/2873 high priority.
It's not good that Android users can't sprint. ;-)

**Comment by paramat** [comment]
No, because then all Android issue become high priority, which is meaningless.

**Comment by Wuzzy2** [comment]
OK, but please don't forget #2873 *in particular* as I do think it is quite important for Android users. I don't think other Android issues qualify as important.

Note I'm not an Android user myself.

**Comment by paramat** [comment]
Here are the Android blockers for 5.0.0:
https://github.com/minetest/minetest/issues?q=is%3Aopen+is%3Aissue+label%3AAndroid+label%3ABlocker
Work on these will be much appreciated as we are now preparing for 5.0.0 release.

**Comment by paramat** [comment]
Closing as not much need for this issue anymore, see individual issues and #1750

**Comment by paramat** [comment]
Closing as other issues are dealing with the remaining bugs.
