### ISSUE TITLE
More functions for lua table schematics

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6742]
Based on the discussion to make chests and other functional nodes usable I may have some suggestions.

I think it would be possible to add more functionality to lua schematics. For example callbacks like 'on_construct'

It would also be possible to add a flag for each node if 'on_construct' of this node is called when placed.

It would be also possible to add metadata like a chest inventory to specific nodes.

This is currently not possible because of performance reasons, but i am sure that it will be less performant and efficient if it has to be done with current methods like 'find_nodes_in_area()' 

And to clarify: this wouldn't effect the functionality and performance of binary schematics

**Comment by paramat** [comment]
:-1: Schematics are very heavily used, whether they are binary or lua table, and the vast majority of usage does not need callbacks or metadata actions, so the complexity of adding these features is not justified. These add extra fields to schematics only used a tiny fraction of the time.
Bulk node processing, whether voxelmanip or schematics, does not do callbacks or add metadata, this is our policy. 

For initialising chests etc. a much better idea (your idea) is to initialise them on first player usage, this also spreads out initialisation work instead of doing it all at placement. See #1926 for that discussion.
