### ISSUE TITLE
Mobs can push a player into solid nodes

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6749]
It happens multiple times now that a mob pushed my player into solid nodes.

If I stand in frond of a solid node like a wall or tree and a mob runs against me, the mob glitches into the player, as long as I don't touch any key to move.

If I try to move forward the mob pushes me into the solid node. 

I don't think that "my code" causes this. This shouldn't happen at all. And I also reported similar glitches before

**Comment by MarkuBu** [comment]
Made a short video that demonstrates the issue

https://youtu.be/4wD3fp3i7aI

And the only code that moves the mob is this

```
local yvel = self.object:get_velocity().y
self.object:set_velocity({x = self.velocity.x, y = yvel, z = self.velocity.z})
self.object:set_yaw(self.velocity:yaw())
```

**Comment by paramat** [comment]
Hehe amazing. Weird how collision is overriden.

**Comment by Megaf** [comment]
It's lag related I think. When the server notices it it's already too late. It's how mobs are handled.

**Comment by paramat** [comment]
We have changed collision code now, is this still happening in 5.2.0 or after?
Perhaps close this in 1 month if no reports.

**Comment by TheTermos** [comment]
Theoretically it's still possible, however it should happen way less frequently, if at all.

The reason is the mechanics I call clipping recovery that was necessary in the old code as well as it is in the new because of the fundamental flaw in MT client server model (#9806) which makes it impossible to synchronize players with entities and other players.
