### ISSUE TITLE
Nodeboxes turning black or invisible in hotbar

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6769]
![screenshot_20171209_011912](https://user-images.githubusercontent.com/3686677/33791187-1becc73a-dc80-11e7-9964-2607a1bfbdae.png)

See https://github.com/minetest/minetest_game/issues/1959 for details.
Caused by https://github.com/minetest/minetest/commit/ee6bb5a315cc13aa51cda509d02780c21333af44 "Fix item and wield meshes" by @numberZero

**Comment by numberZero** [comment]
Obscure.
May happen with cursor as well. After first appearance, happens reliably with some but not all items that use the same material... for some time. (e.g. until you flip creative inventory page).
![screenshot_20171213_000530](https://user-images.githubusercontent.com/7352626/33908494-a5818f5a-df99-11e7-8beb-8213d14a9065.png)
![screenshot_20171213_000533](https://user-images.githubusercontent.com/7352626/33908495-a5e836b0-df99-11e7-9469-12363829a2c4.png)
(shaders, filters, mipmaps disabled)

**Comment by numberZero** [comment]
@Fixer-007
1. How often does it happen?
2. Can you test the same with other nodes? It should happen with any but solid or liquid node.

**Comment by Fixer-007** [comment]
1) It happens pretty often, it seems
2) I will look deeper into that, but my goto is sandstone
3) Here is another example
![heh](https://user-images.githubusercontent.com/16494741/33941247-9ad3f42c-e01a-11e7-8ef5-70085ff5fcf9.gif)

**Comment by numberZero** [comment]
Item on hudbar is black if it uses the same material as the previous one. Item on cursor is black (on my PC) if it uses the same material as last item in the current page of the creative inventory.

Thus, assuming that the creative inventory is drawn after primary one, I can state that in some cases, it can’t draw 2 meshes one after another properly, if they use the same material. My suspicion is that the code checks whether it should change material, and the check erroneously returns false sometimes causing (empty) overlay tiles (remained active after previous draw) to be used instead of normal ones.

**Comment by numberZero** [comment]
IrrLicht bug. It can’t handle materials with multiple textures well.
