### ISSUE TITLE
Function to test if something is a player userdata

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6791]
A function to test if a variable points to a player object (userdata) could be used by mods and builtin, currently it's tested in messy and inconsistent ways, as indirectly mentioned in the comment in line 10 in builtin/game/misc.lua:
https://github.com/minetest/minetest/blob/master/builtin/game/misc.lua#L9

**Comment by Wuzzy2** [comment]
I don't know what you mean.
Just use `var:is_player()`.

**Comment by HybridDog** [comment]
Wuzzy2, this would crash if var is not a table and not a userdata or the is_player field is not a function.
You'd need to use `type(var) == "userdata" and type(var.is_player) == "function" and var:is_player()`

**Comment by Wuzzy2** [comment]
Looks like a simple helper function in `builtin` then.
I am now in favor of your suggestion.

**Comment by raymoo** [comment]
I'm not sure when this would come up. I don't think functions are usually written to take multiple kinds of userdata objects, so if it's a userdata you would know it's an ObjectRef.

**Comment by HybridDog** [comment]
raymoo, functions are written to cause an error with a reason message when a mod passes something strange, if the function wouldn't explicitly check if the passed thing is a player, the crash message confuses the modder because the reason of the crash is not clear, see the code I've linked to.

**Comment by raymoo** [comment]
@HybridDog Ok, that makes sense. It's not clear to me how common this error is, but I agree that there should be some way to check. I just adopted a defeatist attitude since Lua makes it such a pain to do type checking of arguments on the Lua side.

Maybe each type of userdata exposed to Lua should have some tag that can be checked. In the case of players, you would be able to tell if something is an ObjectRef and then use is_player to determine that it is a player.

I think it is hacky to rely on the presence of the "is_player" function to determine that something is an ObjectRef. There should be a real facility to determine the type of an ObjectRef.

**Comment by rubenwardy** [comment]
`getmetatable(player) == ObjectRef and player:is_player()` *may* work

**Comment by raymoo** [comment]
I didn't know the metatables were available like that, but that looks like it would work if they are.

**Comment by HybridDog** [comment]
Me neither, the dump function can be improved: Currently dump(player) gives "<userdata>", but dump(getmetatable(player)) dumps a table with all available callbacks.

**Comment by raymoo** [comment]
I guess they aren't available then.

**Comment by beyondlimits** [comment]
Can be closed?
