### ISSUE TITLE
MG v6 with new biome system

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6827]
The current v6 mapgen should stay unchanged for backward compatibility. But it would be nice to have this mapgen with v7 biomes, because it is the only one that doesn't support the new biomes. 

I suggest to add a new mapgen with land and cave generation from v6, but with v7 compatible biomes

**Comment by paramat** [comment]
It will be interesting to see how much demand there is, i could code this fairly quickly, i'm neutral, if much wanted i'm happy to add it.

**Comment by Megaf** [comment]
One solution could be creating v6.1 or v6ng, though that is totally against what I was talking about on IRC just minutes ago.

**Comment by 4w** [comment]
> creating v6.1 or v6ng,

Or mazbe we should start using descriptive names instead of `v` followed by random numbers.

**Comment by benrob0329** [comment]
IMO I would rather have a customizable mapgen that is well rounded, than several customizable-ish mapgens than you end up compromising on what you want.

**Comment by Megaf** [comment]
> 16:33 Megaf> we just need ONE mapgen ...
16:33 Megaf> why have many broken things instead of ONE working thing?
16:33 Megaf> v5 was broken, they made v6, it was broken, no mountains, they made v7

...

> 16:36 Megaf> IMHO v6 would be the perfect mapgen if it had mountains

**Comment by paramat** [comment]
As i wrote elsewhere, this would be a new mapgen, making Biome API compatibility optional within mgv6 is too difficult to bother with.

I completely disagree with the quotes from IRC.
None of our mapgens are 'broken'. Mgv6 was created using 2D noise because the 3D noise of mgv5 used to be very slow before hmmmm optimised it. Mgv7 was hmmmm's own mapgen which i helped to tune and finish, it wasn't meant to be a replacement for mgv6 or compensate for it.

Mgv6 cannot have mountains unless you disable the mudflow feature, that's why it doesn't extend above y = 47, it's not designed to cope with mapchunk borders.
Mgv6 code is a nightmare to work on (the hmmmm-style code of the other mapgens is much simpler and cleaner) so i have zero interest in working on mgv6, i only touch it to fix bugs. It's only kept to support old worlds, it should be left alone as we work on the better mapgens.
Mgv7 has the same basic generation as mgv6 plus mountains and rivers, just different noise parameters, so try customising mgv7.

All our mapgens are extremely customisable, more than you realise, but you need to understand how to alter the noise parameters, i made a post in the mapgen questions thread about how to customise mgv7 and have made a post explaining how noise parameters work.
Mgv7 can do almost anything through parameters.

**Comment by 4w** [comment]
> Mgv7 can do almost anything through parameters.

It’s a pity that none of them are properly documented.

**Comment by Ezhh** [comment]
Personally I'd rather more varied mapgens added, instead of new versions of existing ones, but this might be because I don't find v6 interesting enough to have two versions of, and we obviously need to keep supporting the existing one.

**Comment by paramat** [comment]
Yes we lack clear documentation of what each parameter does, especially for the noises. This is obviously my job. A new doc file for mapgen tips.

**Comment by LemonFox3008** [comment]
If clear documentation could be made things would be so much easier.
When will you get started paramat?

**Comment by paramat** [comment]
There hasn't been much interest in doing this and i'm not interested. It would create an mgv6 with less character because it has no mudflow erosion alternating with cavegen. Terrain could be higher but doing so doesn't suit mgv6 terrain. I would rather add interesting new mapgens than the extra files needed for this.
:-1:
