### ISSUE TITLE
Chat prompt: Autocomplete chat commands, node names, etc..

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6837]
I suggest to add some kind of callback if the tab key is pressed in the chat. This can be used for several things like auto complete and other functions.

It should be possible to register multiple functions, but if one call returns "false" the execution should be stopped.

This can be used to autocomplete chat commands, player names, node names and so on.

**Comment by SmallJoker** [comment]
I tagged this as Client Script API because the client won't/can't wait for the server in order to know what it should autocomplete. Player name autocompletion is already implemented, same would be possible for the node names, which are sent to the client on join.
The chat command handler does not send anything to joining players. They would have to load the commands from the server over the chat or a mod channel. Another problem there is that the commands usually take arguments, which could be autocompleted, but there's no registration process and all mods handle them on a different way.

**Comment by paramat** [comment]
See #5532

**Comment by MarkuBu** [comment]
But only works for player names and chat commands, right?

**Comment by paramat** [comment]
Looks like a general API to me, see the docs in the PR.

**Comment by MarkuBu** [comment]
You are right. Than this can be closed, thx
