### ISSUE TITLE
Passwords storage using SRP vulnerable to offline attack

### ISSUE THREAD

**Issue by Nhoya** [minetest/minetest#6858]
As I can see [here](https://github.com/minetest/minetest/blob/88b436e6a9c98af7215bd115e1b7a3f1a1db99d3/src/util/auth.cpp#L29-L48) the player's password is stored in the database as sha1 of plainPassword+name

This end up to be a predictable entry (the player name) + password and a weak algorithm (SHA1)

You should consider migrating to something like [Argon2](https://github.com/P-H-C/phc-winner-argon2)

**Comment by sfan5** [comment]
That's legacy compatibility code.
We switched to [SRP](https://en.wikipedia.org/wiki/Secure_Remote_Password_protocol) authentication over 2 years ago: 82e35edff52d88dcd64a9bfc9d2c4c93f1341b78

**Comment by Nhoya** [comment]
SRP is good against  eavesdropping attacks the problem is that is not so good against offline attacks (to explain simpler: when you dump the database and can directly bruteforce the hash

**Comment by sfan5** [comment]
> the problem is that is not so good against offline attacks

could you expand on that?

**Comment by Nhoya** [comment]
Sure, SRP aim to block what are called Man In the Middle attacks, the problems is that if you have the database you can try a dictionary attack against the hashes https://crypto.stackexchange.com/questions/29771/weakness-of-srp-after-server-compromise

**Comment by nerzhul** [comment]
Yes we know old passwords are stored without salt. But it's in the compat code and will be removed in some years, we cannot upgrade it efficiently

**Comment by Nhoya** [comment]
@nerzhul The problem is not only for old password but for current passwords too, as i said to @sfan5 my suggestion is to change the actual SHA2+SRC to Argon2|bcrypt+SRC

**Comment by est31** [comment]
As the person who designed and implemented the SRP based authentication, who is to blame for this, let me say a few things:

I refute the claim that SHA2 is broken. It is a legitimate cryptographic hash function. If you have a truly random 18 character password of random characters, with each character representing 6 bits of entropy, you'd have 108 bits of entropy, which is far beyond any bruteforce capabilities even for SHA2. Bitcoin has a hash rate of about 2*10^19 double hashes per second, so you'd need to have the entire bitcoin network run 2 ^ (108 - 65 - 1) seconds on the task to crack such a password (`-65` because log2(2*10^19) = about 64 and you need to add 1 bit as bitcoin calculates double hashes, and `-1` because on average, you'll have found the password after computing half of the hashes), which is 139 thousand years. You *can* use the current SHA2 based scheme in a secure way, so it is not broken.

Maybe with "SHA2 [...] has already been broken" you are reffering to SHA1 having a collision? Collisions are irrelevant for use as password functions. The only relevant attack is the second preimage attack, and even MD5 stands strong here. SHA1 and SHA2 standing even stronger.

As @nerzhul pointed out, we are using salts (they are large, 128 random bits), so we are safe from the really evil stuff like rainbow attacks or being able to check the popularity of passwords.

The general "SHA2 is insecure for passwords" mantra is popular inside the security world, but you shouldn't just blindly repeat it, or exaggerate it. Every hash function proposed is vulnerable to offline attacks, including Argon2, PBKDF2, and scrypt. *None* of them is magically secure. The relevant difference between SHA2 and Argon2 is how many hashes one can compute per second when doing a brute force attack. E.g. with same resources, an attacker can compute 1 million SHA2 hashes in the same time that the attacker can compute one Argon2 hash. Maybe that time is one millisecond, maybe it is one microsecond, maybe a nanosecond, maybe even less. It all depends on the resources that the attacker has access to, but there is nobody preventing the attacker from mounting an attack onto Argon2.

What does that slowdown factor mean in practice? Let's assume that one character for passwords is 6 bits of entropy and that the attacker doesn't mount a dictionary attack. The very same argument applies for dictionary attacks as well, but it is more complex to be put into words so I let's assume a normal bruteforce attack, for the sake of the argument.

If the attacker can try one million as many passwords, it would mean that the password only needs to be 4 characters longer to have the same security level (4 * 6 = 24 bits -> 2^20 is about one million). With a slowdown factor of one billion, it is 5 characters (5 * 6 bits = 30 bits -> 2^30 is about one billion).

I'd argue that in practical settings, Argon2 wouldn't be able to get a slowdown factor over the current sha256 algorithm of more than a few ten million. Single cores of CPUs without any acceleration like intel sha extensions can compute [less than 20 million sha256](https://en.bitcoin.it/wiki/Non-specialized_hardware_comparison#CPUs.2FAPUs) hashes per second, so if Argon2 runs singlecore and is 2 million times as slow, you'd spend more than a tenth second to compute the Argon2 hash. If it runs on 10 cores, and takes the same time, the slowdown factor would be 20 million. A tenth second is a perceivable amount of time and probably you'd want less than that.

Also, the parameter choice for Argon2 is [highly hardware dependent](https://crypto.stackexchange.com/a/37140). Minetest is precisely the opposite. It is supposed to run on a large set of hardware, including computers and mobile devices. Players should be able to set up their account on their high powered computer, and log in on their smartphone without having to wait 10 seconds. So you'd have to set the parameter defaults to some minimum. Ideally, the parameters would be configurable with a clientside setting, and stored alongside the salt by the server.

Back in the day, I haven't added Argon2 or scrypt or anything else because I wasn't convinced of their advantages. I've since then come to a more moderate view on them, thinking that they do bring advantages but that applying them is in many cases not worth the hassle. In the usual "password being sent to server" use case, HSM's or SGX or similar are better solutions to the offline bruteforce use case, as these make bruteforce attacks completely impossible while not wasting CPU cycles on computing Argon2.

I have left Minetest and usually don't participate in discussions any more. I just wanted to give you an explanation/history lesson why I didn't do it myself back when I've implemented SRP. If you want to add Argon2, be my guest, but this is not like a big security leak or something.

**Comment by Nhoya** [comment]
First of all @est31 thank you so much for the great and really extensive explanation of the implementation reasons, i can agree with you on lots of points and but in the real world the "true random" doesn't exists, and usually in  the case of people using random generated passwords (and i think we all know that is a really low percentage) the real entropy is much much lower. 
My point against SHA2 is that is just a general purpose hashing algorithm, is not designed for passwords. I know that using this kind of algorithms will be a "great things" for slower computers because are really fast and don't waste much CPU but this is not a good point in case of offline attacks.
Again, thank you for explaining me your arguments

**Comment by raymoo** [comment]
@Nhoya 
>My point against SHA2 is that is just a general purpose hashing algorithm, is not designed for passwords.

This is false, SHA2 is designed as a cryptographic hash function.

**Comment by raymoo** [comment]
@Nhoya 
If you want to show that Argon / bcrypt would be more secure, then you need to demonstrate that the running time for a SHA2 dictionary attack would be at feasible levels. Without that, there is really nothing else to go off of.

**Comment by Nhoya** [comment]
@raymoo 
> This is false, SHA2 is designed as a cryptographic hash function. It is designed for passwords, just not them specifically.

Cryptographic hash function != designed for passwords

>If you want to show that Argon / bcrypt would be more secure, then you need to demonstrate that the running time for a SHA2 dictionary attack would be at feasible levels. Without that, there is really nothing else to go off of.

https://medium.com/@davidtstrauss/stop-using-sha-256-6adbb55c608
https://security.stackexchange.com/questions/90064/how-secure-are-sha256-salt-hashes-for-password-storage
https://security.stackexchange.com/questions/211/how-to-securely-hash-passwords (Note: this answer is from 2010)

**Comment by red-001** [comment]
I think using a better hash function could still be a good idea, yes the passwords are salted which is a good thing, but whatever the salt is 64-bits or 128-bits or 1024-bit just does not matter much as long as the salt is unique. If anything the salt length used is overkill, could have used a shorter salt with almost no security downsides.

100 ms or so is hardly a big problem on login, that's what 6-7 frames worth? And no-one cracking passwords you should be worried about would be using a CPU cluster, a low skilled attacker with some minimal resources will most likely be using a high-tier consumer or prosumer GPU to do this, most likely just one or two.

Just increasing the memory requirement will slow down any attacker, but have a fairly limited impact on legitimate users.

Consider an RTX 4060 with the AD107 GPU chipset and 8 gigabytes of memory with a 128 KB L1 cache and 24 MB L2 cache and 24 SM units. Each SM unit can at any given time be executing a 32-thread-ish warp with up to 1024 threads allocated to a given SM unit.

Using SHA-256 we have around 32-bytes of state to keep track off, plus whatever data we want to hash. Internal state needs to be in the L1 cache otherwise the GPU will grind to a halt and be about as fast as calculating the result with a mechanical calculator. Data doesn't need to fit, it can be fetched into the cache as needed but that means that multiple warps would need to be scheduled for each SM unit to avoid stalls. With the small internal state used by SHA-256 and considering the cache line is 128 bytes could maybe get a peak of 800 threads per SM each working on checking a different password, and hence a maximum throughput of 19,200 passwords being checked at once by the GPU.

If a hash function was used that actually requires 4 kB of L1 (like iirc bcrypt does) was used that slows you down to just 128 passwords you can check at once per SM unit at peak throughput or 3,072 simultaneous passwords the GPU can check.

If you use argon2id configured to use 32 megabytes of memory then that drops the number of hashes that GPU can check at once to 256-ish just considering the size of the main memory.

These are just really rough estimates but wanted to point out you should be worried about someone who you can check more passwords *at once* not just has more time to do it, and why using a more memory hard hash is probably still worth it. A legitimate user will only check one password at once, and attacker will want to check as many at once as possible. Ideally a hash is used that makes that as financially expensive as possible.

I'm not sure what the minimum memory requirements for Minetest on Android are, would 32 MiB be something that could be afforded during login? The memory would be released right back as soon as login is done so it shouldn't have an impact on gameplay.

**Comment by rubenwardy** [comment]
it's a bad idea to comment on a close issue like this, it'll get lost

**Comment by red-001** [comment]
My bad, I didn't want to open a new issue, since this problem was already brought up. Should I do that instead?
