### ISSUE TITLE
Support running server as homeless user

### ISSUE THREAD

**Issue by dpflug** [minetest/minetest#6869]
I'm attempting to set up a server and ran into a snag. Minetest assumes the user it's running as will have a home folder. The FreeBSD port sets up a user that doesn't, by default.

path_user and path_cache seemingly can't be overridden at runtime.  They're defined in porting.cpp.

Not having a home directory helps with security, so I suggest adding a couple --flags to define path_user and path_cache. `--data` and `--cache`, perhaps. Thoughts?

**Comment by 4w** [comment]
That is not BSD specific. Homeless users are quite common on Linux-based operating systems, too.

**Comment by Wuzzy2** [comment]
Note that “homeless user” here refers to an user without the `home` directory, not an user who is literally homeless. xD

**Comment by sofar** [comment]
nothing wrong with making e.g. `/var/lib/minetest` the homedir of the user.

**Comment by sofar** [comment]
Note that in most unixes, having a `home` folder is required. It may not have to exist, but every account needs to have one defined.

**Comment by dpflug** [comment]
Those are both very good points and are good enough for me. I hadn't thought about making `/var/lib/minetest` the homedir. Unless someone has a compelling reason not to, we should probably just close this.

**Comment by M1dgard** [comment]
On Linux, if `HOME` is not set, the server will crash with
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
```
due to https://github.com/minetest/minetest/blob/c830347a57c63698f14803233dfc43adeb3fd51f/src/porting.cpp#L469-L470

---

If `HOME` is set to a location not writeable by the minetest user, the server will fail with
```
Cannot create user data directory
```

---

I hope this info might help people to find this issue.

Background info: on Linux I'm using [`runit`](http://smarden.org/runit/) as system service supervisor, and I use its [`chpst`](http://smarden.org/runit/chpst.8.html) command to change the process's permissions, such as the user. It doesn't alter environment variables like HOME.

**Comment by nerzhul** [comment]
now we properly trigger a useful end user error, thanks @M1dgard

**Comment by dch** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235355 with a fix for this issue upstream.
