### ISSUE TITLE
API: Move items between inventories

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6877]
Moving items between inventories in nodes is surprisingly difficult.

Moving an item from a chest to a neighbor chest is trivial. There are no checks or fancy restrictions, you just need to check destination space, then remove from src and add to dst.

But as soon you deal with nodes which are slightly more complicated than chests, this naive implementation breaks. Let's say you want to extract items *generically* from node inventories. This is very hard. It requires not only a lot of boilerplate, but also serious collaboration between modders.
Another example is moving an item from a hopper to a furnace fuel slot. Here it gets interesting.

Challenges:
* You need to know which inventory lists a node uses as well as their meaning
* You usually want to obey any inventory restrictions (e.g. no cobblestone in furnace fuel slot)

It's trivial to query the inventory lists, but not their meaning. The only way I see is to hardcode it for every node. This is bad.
The naive take item/put item approach completely bypasses all inventory restrictions. You would end up happily filling up a furnace fuel slot with illegal items.
One idea would be to just call the inventory move functions of the furnace, but this doesn't work. Sadly, these functions expect a player. If you supply nil for a player, the game might crash. So you are forced to supply a player, even if there isn't one. This is a very bad restriction.
So your only choice here is to basically re-implement all inventory restrictions and introduce redundant code.

---

Suggestions:

1. Rework the inventory movement restrictions to work without player argument
2. Add `minetest.move_item_between_inventories(src_inv, src_list, src_slot, dst_inv, dst_list [, dst_slot])` (or similar). This function moves an item stack from inventory `src_inv` to inventory `dst_inv` and fails if there's not enough space or any movement restrictions are violated

---

Further reading: https://forum.minetest.net/viewtopic.php?f=5&t=19202&p=306977

**Comment by MarkuBu** [comment]
As I mentioned in the forum I suggest a more generic approach.

Each node can have two callbacks. A push and a pull callback. The push callback wants to insert something, the pull callback wants to take something. This must not necessarily items. Also possible are liquids, energy and so on.

The node itself needs to deal with the callbacks and decides where to put an item or returns false if the inventory is full.

**Comment by 4w** [comment]
> Each node can have two callbacks. A push and a pull callback.

Where to pull from a furnace? Do you want to take the result, the fuel, or the raw material? So for furnaces you need at least 6 callbacks (push and pull for energy, result, and raw material).

Or lets think about mods. The fuel-fired alloy furnace from `technic`  has 4 places to take and put stuff. The two material slots, the fuel slot, and the output slots. Or take a charcoal mod that allows to burn trees into charcoal. So logs can be used as fuel and as source material. Where to put? Where to pull?

As much as I like the idea of “self-contained” logic for node inventories: You have toi give them a hint what to do.

**Comment by raymoo** [comment]
@4w You could make it based on the node face. E.g. bottom is for fuel, sides is for output, top is for input, or something like that.

In some Minecraft mods, for inventories with more slots, there is a UI for configuring which sides of the node correspond to which item slots of the node. This way the user can choose a configuration that works well with their machines layout.

**Comment by raymoo** [comment]
However I think there should be an API specifically for interacting with inventories. Something like @MarkuBu suggests could be implemented on top, in nodes.

**Comment by MarkuBu** [comment]
Who want's to take the fuel out of a furnace?

But you are right, what I described is just the basic idea. To deal with multiple outputs there are several ways, for example the face where you attach the "puller" or filter.

As raymoo said, some Minecraft mods have a configuration interface for nodes, which side is an input or an output and you can assign a face to a slot.

But all of this are decisions made in the node itself. The only decisions that are made outside is a filter, that only wants to pull specific nodes or types like liquids, energy and so on or if he wants to pull single nodes or a stack

**Comment by 4w** [comment]
Maybe define what you want to do by adding meta data to the sent thing? The node metadata addressing has to be changed, though. All slots are always numbered so you can address them separately independent of mod or amount.

```JSON
{
    "type": "source",
    "slot": 1,
    "amount": 1,
    "request": "add"
}
```

Type can be `source` (raw material for furnaces, etc.), `fuel` (anything that “powers” whatever the node is for), or `inventory`.

`slot` refers to the n-th slot of the type. So 1 is the first slot, 2 is the second slot, etc. if 0 is used any of the slots of that type may be used to fulfill the request.

The amount is simply the number of things. When 0 is used it means “all things”. If the type is “fuel” the mod decides what to do with it if it is no item, for example adding 500 to source could mean providing 500 energy units.

The request is either “add”, or “take”, or “give”. “add” and “take” are send to the node, and “give” is sent by the node to other nodes. For the other node the “give” requests works like a “take” request. For example: A water pump “give”s the `amount` of 500 `fuel`. The node that is given to “take”s the amount and adds it to the defined `slot` in the `fuel` group (i.e. starts whatever it will start when the pump pumps water to the machine).

Complex example: Give some materials to the fuel-powerd alloy furnace of `technic`.

~~~~
default:sand, { "type": "source", "slot": 1, "amount": 0, "request": "add" }
technic:coal_dust, { "type": "source", "slot": 2, "amount": 0, "request": "add" }
default:coal_lump, { "type": "fuel", "slot": 1, "amount": 1, "request": "add" }
~~~~

And some sort of pipe or filter injector could request `{ "type": "inventory", "slot": 0, "amount": 0, "request": "take" }` form the furnace.

**Comment by MarkuBu** [comment]
No no no. The duct or whatever is connected never should know what's inside other nodes. Also they don't know if they currently transport items for burning or file items.

I don't have time to make a demo. Maybe next week.

**Comment by MarkuBu** [comment]
Let me make some examples. First a simple one with a chest. Let's assume we have a chest with two ducts attached. 

One duct inserts items to the chest. He call's the insert or push callback from the chest with some information. The chest needs to check if it is a valid item (and not e.g. energy), need to check if there is enough space in the inventory and returns true if the push was successful or something else if it fails. 

The other duct (or filter, hopper...) calls the pull callback (with optional item list for filter). The chest returns the first available item or, if a filter is used, the first item from the filter. If no item was found the chest returns nil or false, otherwise the item or maybe a stack, if that was requested.

Now let's assume a furnace. There are two input slots an one output. Normally each pull request means the output slot. It is uncommon to pull the fuel or the input slot. If that is desired the furnace needs to deal with that. 

Normally the input is relatively easy. Everything that is not a fuel goes into the input slot, any fuel goes to the fuel slot. If you can't cook the item the furnace is blocked. Your bad.

The input is a bit more complicated. Lets assume you want to burn coal into coke coal, than coal can be both, fuel or item that should be burned. Than you need to have two inputs and the furnace has to define which input connects to which slot.

What I want to say: the duct or whatever is connected are dumb. They can't know what another node want's to do with an item. They just move it. They just say: "Hey furnace, I have a coal lump for you. Take it or leave it. I'm on your left side." or "Hey furnace, do you have something for me? I'm on your right side." and the furnace may say: "If you are on my right side than you maybe want to clean my fuel slot. Here you have a coal lump."

But ducts or hoppers should never interact directly with inventories of other nodes

**Comment by MarkuBu** [comment]
Probably it is not even necessary to have a pull callback, because this needs to run permanent.

Instead an attached node like a hopper can be registered in e.g. a chest, so the chest knows that there is a node that can receive items. If the chest has items in it's inventory the chest can call the push callback from the hopper. 

So we would only have push events in this system. And to improve the performance it wouldn't be necessary to move the items from duct to duct or wire to wire. A transfer chain can only be "virtual". A chain is build out of nodes like ducts, wires or similar and has a start point (the pusher) and an end point (a chest, a junction...). This would be optional, because maybe it is wanted that for example liquids are pushed through pipes and each pipe contains some liquid. 

An example: let's assume you have a power source like a battery and two lamps. You build a wire chain from the battery to the first lamp. Every time you add a wire the target node from the pusher (the battery) get's an update. If the chain is complete the battery pushes the energy directly to the lamp without to step over the nodes in between. If you connect the second lamp the target of the battery get's a new target, the junction. And the junction becomes a pusher that has two targets, the two lamps. 

Currently I have 4 types, that can be transported. Items, energy, liquids and gas, probably also steam. Each type could be subdivided in multiple types like low power and high power energy. Each type has it's own type of transport node. If I want to attach a wire to a chest, nothing happens because chests don't store or consume energy. If I attach a duct to a chest the push target of the duct is the chest. If I attach a hopper to a chest the hopper becomes the push target from the chest.

Now I wrote a lot, but does it makes sense?

**Comment by raymoo** [comment]
Actually, I change my mind; something like @MarkuBu's suggestion should work for the use case described in the issue. I do have a few criticisms, though (some copied from the forums):
- Furnaces have only one output slot, but you could imagine a node that produces byproducts. For example, maybe a machine takes "fuel" as a bucket of water, and has a "spent fuel" output that is an empty bucket, in addition to some kind of normal output. You see this in Minecraft where some machines can take in a bucket instead of having liquid piped in. Though, if you are using something like pipeworks, you could just have a sorting tube. A trickier example might be if a machine has multiple output liquids.
- If you have no pull callbacks and nodes are expected to push items to anything that is ready to accept them, there is the problem that the node won't know what kinds of items or how many items its neighbors will accept, unless it somehow keeps track of this information in itself. It seems like this would be contrary to what you are aiming for, which is transport nodes that are "dumb" and don't need to know much about its neighbors.
- For liquids, calling callbacks all the time is not ideal because of performance issues, and instantaneous travel is not ideal either for the reasons you described. Like I mentioned on the forum, for liquids I would optimize by keeping a numerical value for each position in a Lua table (to avoid needing to make expensive metadata accesses), and simulate flow by adding / subtracting between adjacent positions that are know to allow liquid flow.
- If items, liquids, and electricity all end up having different transport mechanisms, then the only thing in common would be the callbacks at the endpoints, and the input data to the callback would be different for each kind of transported thing (itemstacks for items, liquid volume + liquid type for liquids, and just a volume for electricity). You would have something like this:
```
local a_callback(transport_type, data)
  if transport_type == "item" then
    // item-specific processing
  else if transport_type == "liquid" then
    // liquid processing
  else if transport_type == "energy" then
    // energy processing
  end
end
```
Essentially, this mixes three different functions together and convolutes things for no advantage compared to just having three separate callbacks for three different systems.

**Comment by MarkuBu** [comment]
I know that Minecraft has tons of different mods for transportation like Buildcraft or Extra Utilities. It is difficult to cover all possible scenarios.

For example Extra Utilities: it is possible to transport items, liquids and energy in the same pipe. With your example it would be necessary to call the callback three times. But you can have a table that contains all three types at once.

About your second point: that's why I said, the node should be registered. For example you attach a hopper with a filter to a chest, the chest needs to know the items, the push speed and so on. After that the chat can push the requested items with the requested speed

If you store the liquid level in a table, you need to store this table on disk because all liquids get lost if the server stops.

Anyway: what I described is only to generalize the way how to insert and remove items from and to inventories. It can be used to transport items from node to node, but a transportation mod can do whatever it wants between the start and endpoint.  I just point out some examples

The basic message is: don't access inventories directly. Use a common interface.

**Comment by 4w** [comment]
> The basic message is: don't access inventories directly. Use a common interface.

I think we all agree with that!

**Comment by MarkuBu** [comment]
> I think we all agree with that!

And my suggestion only covers how to get and put things from and to inventories. It does not cover the behavior between the source and the target.

But the more I think about it, the more it feels like a convention and not like a real API with code.

What should the API do? Everything that is necessary could (must) be done in the node itself. Nodes with an inventory like chest and furnace need to handle everything by itself because only they know what they need. 

I don't see anything that could be "outsourced" to an external API. Or did I miss something?

The only thing that needs to be defined is the push callback (and maybe the pull callback).

And we probably should also consider to use this to add and remove things from and to entities. Think about the automatic armor station in Minecraft. It is possible to attach a full armor that is dropped by Droppers (or Dispensers? Not sure which one it is). Or think about a chest cart, that can be filled or emptied automatically.

**Comment by raymoo** [comment]
@MarkuBu You could have a function that does the looking of up and calling of the callback for you.

**Comment by MarkuBu** [comment]
One problem is, that the callback(s) needs to be implemented in the chest and the furnace. But a lot of mods override the chest. Not sure if they copy the original and just add their own functions or if they redefine the whole node.

**Comment by raymoo** [comment]
@MarkuBu The ones I've seen only redefine the parts they want to modify.

**Comment by MarkuBu** [comment]
We're renovating. When we're done, I'll try to program it. Maybe I try to make a transport system similar to Extra Utilities. I like that and it is simpler and more efficient than pipeworks

**Comment by paramat** [comment]
1 year bump, any core dev support?
