### ISSUE TITLE
Unexpected collision when beginning a jump that pushes the player sideways or backwards

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#6886]
When landing from a jump, with horizontal speed, sometimes the player's velocity gets pushed back or sideways-back (in one of the map axes). This is most visible if you jump repeatedly while holding a movement direction on a large flat surface.

EDIT: Actually the shifting seems to happen when the jump starts, not on landing.

**Comment by MarkuBu** [comment]
Oh yes, I can confirm this. It's like you get a little kick from the side. To try this make a flat world and jump while walking with a yaw near a 90° angle, for example 188° or 6°

With a higher speed (fast mode) sometimes it feels like you get stopped for a moment. But I don't notice that with straight yaws like 90° or 0°

**Comment by jastevenson303** [comment]
I too can attest.  The player's position is occasionally being quantized,
which ruins the flow.

**Comment by SmallJoker** [comment]
I can reproduce this issue too. Going with 135° makes this bug easier to see when starting with similar X/Z coordinates (like ending with `.0`) and jumping forward. The difference of both coordinates was up to 0.4, which indeed makes the gameplay strange.

**Comment by Fixer-007** [comment]
Can confirm this issue, I've suspected it for many months.
![default](https://user-images.githubusercontent.com/16494741/35540528-fd898410-055e-11e8-8368-5a102e28f41d.png)

**Comment by raymoo** [comment]
I just noticed that it doesn't happen on landing, it happens on jumping (lift-off). It doesn't happen to me on landing if I don't hold jump, and it sometimes happens when I initially jump even if I didn't just land.

**Comment by Fixer-007** [comment]
Nah, you should change topic to better name, like "Player shifting during collision"

**Comment by raymoo** [comment]
@Fixer-007 I'll change it to something, but the one you suggest would be inaccurate since the collision itself is unexpected.

**Comment by Fixer-007** [comment]
It is weird that few people notice this bug, it is very evident in many jumps and induces lots of OCD...

**Comment by jastevenson303** [comment]
What's weird about shifting aside when hitting a wall at an angle?  I was attesting to the player's shifting aside when performing a landing jump on a flat surface.

That's a cool gif though, for sure, but I don't believe it's the same as what's being illustrated in this issue.

To quote OP:
>This is most visible if you jump repeatedly while holding a movement direction on a large flat surface.

**Comment by DS-Minetest** [comment]
(I can confirm, too.)

@jastevenson303 Look at the first two landings and at the last one.

**Comment by jastevenson303** [comment]
You're right, it's really subtle.  All I could focus on was the bumping against walls.

![giphy-downsized-large](https://user-images.githubusercontent.com/23448162/53827653-9d8df700-3f49-11e9-8d9a-d2ff48fdf5b0.gif)

Animated gifs aren't great for illustrating all of this.  The original for the above is here: https://i.giphy.com/media/fQMq7LmshmfyjolFGd/giphy.mp4

**Comment by Fixer-007** [comment]
It shifts on flat surfaces

**Comment by jastevenson303** [comment]
Right.  I see it Fixer.

Actually here's the original: https://media.giphy.com/media/fQMq7LmshmfyjolFGd/source.mp4 <-- and it shifts twice, once at the start and once at the end.

**Comment by sfan5** [comment]
Reposting my gif here because it nicely demonstrates the issue:
![gif](https://user-images.githubusercontent.com/1042418/65950427-5663d800-e43e-11e9-9b01-cf417e9c0cc7.gif)

**Comment by sofar** [comment]
```
diff --git a/src/client/localplayer.cpp b/src/client/localplayer.cpp
index c086d860..b3a58745 100644
--- a/src/client/localplayer.cpp
+++ b/src/client/localplayer.cpp
@@ -295,6 +295,7 @@ void LocalPlayer::move(f32 dtime, Environment *env, f32 pos_max_d,
        collisionMoveResult result = collisionMoveSimple(env, m_client,
                pos_max_d, m_collisionbox, player_stepheight, dtime,
                &position, &m_speed, accel_f);
+       errorstream << initial_speed.X << " / " << initial_speed.Z << " -> " << m_speed.X << " / " << m_speed.Z << std::endl;
 
        bool could_sneak = control.sneak && !free_move && !in_liquid &&
                !is_climbing && physics_override_sneak;
```

Confirms that the `CollisionMoveSimple` call at this location here (`src/localplayer.cpp` at line `295`) is the culprit, because the following is printed out to the console when this "wobble" happens:

```
2019-10-01 20:54:35: ERROR[Main]: -30.5384 / 25.8342 -> -30.5384 / 25.8342
2019-10-01 20:54:35: ERROR[Main]: -30.5384 / 25.8342 -> -30.5384 / 25.8342
2019-10-01 20:54:35: ERROR[Main]: -30.5384 / 25.8342 -> 0 / 25.8342
2019-10-01 20:54:35: ERROR[Main]: 0 / 25.8342 -> 0 / 25.8342
2019-10-01 20:54:35: ERROR[Main]: -3.4 / 25.8342 -> -3.4 / 25.8342
2019-10-01 20:54:35: ERROR[Main]: -3.4 / 25.8342 -> -3.4 / 25.8342
2019-10-01 20:54:35: ERROR[Main]: -6.6 / 25.8342 -> -6.6 / 25.8342
```

**Comment by sofar** [comment]
Printing out the collision axis (src/collision.cpp:459) shows that the collision is detected with Z or X axis:

```
2019-10-01 21:10:24: ERROR[Main]: X
2019-10-01 21:10:24: ERROR[Main]: 27.7058 / 28.8511 -> 0 / 28.8511
```

**Comment by sofar** [comment]
Bug seems to happen even when walking without jumping. printing out X/Z collisions while walking, not jumping, gives:

```
2019-10-01 21:16:18: ERROR[Main]: X
2019-10-01 21:16:18: ERROR[Main]: Z
 ```

This was just walking on a flat surface.

**Comment by TheTermos** [comment]
I might have found out what's going on. It's so called collision uncertainty radius which allows collisions to happen on negative dtime, even before the current engine step.

![backwardscollision](https://user-images.githubusercontent.com/55103816/72453125-e3992580-37be-11ea-887d-f01d411e44d6.png)

I'm not sure why this uncertainty radius is used, why it's so damn big (~0.27 BS iirc) and why negative dtime collisions are even considered, but I suspect it's a workaround for the faulty collision detection algorithm. Anyway what it effectively does is trade false negatives for false positives.

Unfortunately I can't do c++ atm, but if I could, I'd try the following:
- in collision.cpp function collisionMoveSimple() dtime value is lost as soon as it enters the loop (beginning at 427)  because it gets overwritten, I'd work with a copy (remaining_dtime) instead and preserve the original like this

instead of:
`while(dtime > BS * 1e-10f) {`
this:

`f32 remaining_dtime = dtime;`
`while(remaining_dtime > BS * 1e-10f) { ` ...etc. dtime becomes remaining_dtime from now on.


- then there's this important check at 457:
`if (collided == -1 || dtime_tmp >= nearest_dtime)`
it would look like:
`if (collided == -1 || dtime_tmp >= nearest_dtime || remaining_dtime - dtime_tmp > dtime)`

Because if remaining dtime minus negative dtime_tmp is greater than original dtime, we travelled back in time (that is, before the beginning of current engine step)

That could help probably, but fixing the original algorithm flaws would be preferable long term.
