### ISSUE TITLE
Build fails without freetype

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#6897]
@nerzhul it reports that `StaticText` is missing. It wasn’t used there before 3a772e7ed6.

**Comment by matttpt** [comment]
The `StaticText` class (extending Irrlicht) is compiled only when Freetype is enabled. Otherwise Irrlicht is used directly. There were previously two implementations of `addStaticText()`, one for each case.

3a772e7 moves the Freetype implementation of `addStaticText()` to a static member function in `StaticText`. The non-Freetype implementation is removed, so non-Freetype builds fail.

The commit I threw together earlier today (d28f3a5245ed0ac771e52ba3c1e78c0131191fb4) simply reverts the renaming. Perhaps the old name is not as "C++ friendly" in terms of style but it seemed like the simplest thing to do. (FWIW it is consistent with `setStaticText()`, which still exists.)

**Comment by numberZero** [comment]
Fixed. Thanks @matttpt. But why not a PR?

**Comment by nerzhul** [comment]
sorry for the inconvenience i missed this part. Maybe we can use it and add ifndef ifdef to static_text instead ?

**Comment by matttpt** [comment]
@nerzhul sorry, I'm not sure if I follow your comment. Use what?

Was hesitant to submit a PR since I know nerzhul was refactoring the code, and he may have a better idea to rewrite it.

**Comment by nerzhul** [comment]
Fixed by 6f2fe8a554f01b5697112c8875e02ef52b1ef69e

**Comment by nerzhul** [comment]
I also pushed the following PR #6908 to have non freetype builds on the CI
