### ISSUE TITLE
Python binding?

### ISSUE THREAD

**Issue by darvin** [minetest/minetest#69]
Is it possible as alternative for LUA?

**Comment by neko259** [comment]
No progress in this? I was struggling with LUA today which lacks even basic tools to work with lists which makes mod use horrible amount of work to check if the table contains an element. This really sucks and overloads the servers.

**Comment by ShadowNinja** [comment]
@neko259: Store your values as keys if you need to find an element fast, Python won't fix your performance problems, in fact Python is known for being slow.

**Comment by neko259** [comment]
@ShadowNinja This does not work, cause I have a table element and lua doesn't seem to think the tables with equal elements are equal.
This can be done, but I need to write the basics myself and so does every mod. Which creates code duplication.
> Python won't fix your performance problems, in fact Python is known for being slow.
Well, disregarding myths about its slowness it allows to write readable code that allows to optimize the algorithms. I wanted to optimize and existing mo and I spent entire day to understand how it works just because the major part of it is implementation of this search, something instead of __str__ etc.
Maybe some basic lua module with necessary stuff can solve this problem if added to the base minetest bundle and can be included and used in all mods.

**Comment by gravgun** [comment]
@neko259
> to check if the table contains an element

```lua
if myTable[element] ~= nil then
```
Was that so hard?
Python is a wonderful language, but likely not suited here because it's generally slower than Lua (and nothing beats LuaJIT, even PyPy is far behind it), has a heavier codebase (i.e. is not really lightweight), and although it's its power it has a pretty huge standard library, which most is of no use in Minetest.

However your "*basic lua module with necessary stuff*" would be a good solution, provided what you propose is actually useful to every mod maker.

**Comment by C1ffisme** [comment]
Even if it sounds like a stupid idea, why not add this? I mean, if we support 2 languages, there will be less of a chance of someone needing to learn a new language to code.

If not this, maybe a community member needs to build a translation mechanism for python to lua and back.

**Comment by gravgun** [comment]
> build a translation mechanism for python to lua and back

As in "translating your whole Python/Lua code"? Lua has a fairly simple parser, but Python is another story... Plus there are things that can be done in Python and not Lua (e.g. list comprehensions).

No, just make another scripting language interface if we need to.

**Comment by C1ffisme** [comment]
Yes, okay.

**Comment by neko259** [comment]
@gravgun 
> Was that so hard?

You got me wrong. I meant I have a table of tables. So my "element" would be a table and Lua doesn't use it as a key as I expect.

About the library, I'll think on that. I don't have much time though and many projects so I'd rather find someone to direct and not try to make another bunch of code myself :)

**Comment by vanillajonathan** [comment]
Considering how hugely popular Python is, and it even having been adopted by non-developers it would nice to see support for Python, it could be a boon to the mod community.

In Python you can load .dll files written in C or C++ and call functions on them.
See the chapter [Extending Python with C or C++](https://docs.python.org/3/extending/extending.html) in the Python documentation.

**Comment by sfan5** [comment]
Aside from the decision to not do this, there are some practical problems with embedding Python:
* Python is not self-contained.
  With Lua you can compile the library into your application (even statically) and that's it, Python requires you to have the standard library + various dynamic dependencies lying around somewhere.
* Python allows control over numerous things that can/will mess with engine state: Threads, Signals, File Descriptors
* It is hard to sandbox Python the way we'd want to

**Comment by Desour** [comment]
>In Python you can load .dll files written in C or C++ and call functions on them.

FYI, you can do this with luajit too, see https://luajit.org/ext_ffi.html.
