### ISSUE TITLE
More advanced in game menu for mintest

### ISSUE THREAD

**Issue by TekhnaeRaav** [minetest/minetest#6922]
Right now there are many many settings that you can change in the menu, although, these can be irritating to work with sometimes. You have to navigate the menu and reload your game every time you change them.

I don't know if this is possible, but It might be nice to have more advanced in game menu that can update things on the fly, maybe with easy sliders and such.
like the picture below

![screenshot from 2018-01-16 14-49-34](https://user-images.githubusercontent.com/30163969/35069441-d60dfd94-fb9f-11e7-9f73-5d15c77d9804.png)

Problem is, you'd have to have these settings change in game... don't know how that works.
(it may just have to do a quick reload after you finish)
If not, it could just be good to make an easier menu on the main menu.
>I'm making a lot of issues, I hope I'm not being overbearing.

**Comment by TekhnaeRaav** [comment]
Stupid me, I apologize, I suppose this is practically already being worked on.

**Comment by paramat** [comment]
Actually #6737 is not related.

The issue with your request is that the advanced settings menu is coded in a way that makes adding new settings very quick and easy, a few lines in settingtypes.txt. Any setting moved out of it would require a lot of time consuming formspec formatting and design work.
Maybe if we had a large team of paid devs we could do this, but we have a continuous severe lack of dev time, so stuff has to be simpler than commercial games, nothing comes for free, maybe you could pay me a wage? =)
Sliders are bad because often you need to set an exact number.

Many settings can't be changed in-game because for performance they are often stored as 'static' which means they can't be changed during a game session. So exiting to menu and re-entering a world is required to change some settings, this is reasonable.

Valid so re-opening.

**Comment by TekhnaeRaav** [comment]
OK, cool.
Yes, no sliders :+1: 
A wage.......sorry, no. I'd love to :money_with_wings: , but I can't.

**Comment by Calinou** [comment]
> Sliders are bad because often you need to set an exact number.

A nice alternative is to use a number field *and* a slider, so you can easily preview how large a value is, similar to Blender.

**Comment by paramat** [comment]
However we can discuss whether there are fundamental settings that need to be in the basic settings menu, some may need transferring.
Since this issue is quite general let's fold it into #6733

**Comment by rubenwardy** [comment]
This is about an **in-game** menu

**Comment by paramat** [comment]
Oops.
I get the feeling there is an issue for pause menu stuff somewhere, will look.

**Comment by paramat** [comment]
Folding into #6722
