### ISSUE TITLE
Secure builtin CSM code against modification

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6925]
See #6699 for the original issue, see #6738 for discussion of implementation.
Originally this was going to be part of #6738 but has been delayed to be a later commit.
I'm closing #6699 as that is attended to and opening this as a specific issue seems needed.

The master disable for the loading of client-provided mods #6738 has been merged but to be effective needs the final step of builtin being checked, see https://github.com/minetest/minetest/issues/6699#issuecomment-347466303 and https://github.com/minetest/minetest/pull/6738#pullrequestreview-81799517
Seems this should be done well ahead of 0.5 to be stable for that release, please can it be worked on soon?
@nerzhul

**Comment by nerzhul** [comment]
i need time to work on it, i just miss time for many projects these days. I will try to work on it this month

**Comment by 4w** [comment]
Why not working on it in an own branch and keep unfinished CSM out of the regular version and merge when done? So CSM can be developed taking all time that is needed and at the same time the released version remains "clean"?

**Comment by rubenwardy** [comment]
This should be compiled out on the 0.5.0 release. You also have to promise that you'd not oppose this, I don't want to end up in a situation where sending is merged then you oppose the disabling. There's currently no use for client-side scripting, and it's not good to have it in the release build until it's both useful and tested to be secure

**Comment by nerzhul** [comment]
then just add a compilation option to disable the startup part and disable it on release if it's not good, else let it true to default, and true in devel mode. 

also please note nobody seems interested to finish the development in or out of this team, or improve the gameplay, since months, i see no real very useful feature since 3 months, and i was too busy since months too to help finish all features, i just get time to do lazy refactoring to enhance code quality. I will look at code signing soon, and the most interesting features (client side particles & hud) are already in PR but nobody except me wants to review and then... finish that comment: no interesting feature, it's just... a loop

**Comment by paramat** [comment]
Ok thanks.
Yes dev has been very quiet recently (except me, working too hard as usual). IRL stuff is keeping people busy.
> This should be compiled out on the 0.5.0 release.

"compiled out of .."?
> There's currently no use for client-side scripting, and it's not good to have it in the release build until it's both useful and tested to be secure

I totally agree. Client-provided CSM seems boring and not very useful. It was a mistake to enable it for 0.4.16 as we know, if we hadn't made that mistake it would not be enabled now, so hard-disabling it for 0.5 is not actually controversial.

**Comment by nerzhul** [comment]
client provided CSM is boring because MT doesn't have a market for mods, it's the problem.
Look at this: it's a CSM market for wow, there is no CSM server sending but it works :) https://wow.curseforge.com/addons (it's just an example of what we need for both cases, server provided mods, and client downloading mods, if they want to have local modifications to see all as santa clauss (imagine))

**Comment by rubenwardy** [comment]
This is not WoW. I do not want to see client modding, and many others do not either. The power of Minetest is with the subgames and building your own gaming experience. I want client-side scripting to make the possibilities of subgames greater, not to fuel your WoW fantasy. Just go play WoW.

client-provided CSM is boring because there is nothing you can do. Server-mods have survived for a long time without a mod store.

**Comment by nerzhul** [comment]
@rubenwardy as you are a core dev you have abilities to make it less boring, then help as it seems you have ideas

**Comment by rubenwardy** [comment]
I don't want to make client-provided mods less boring as I see it as an abomination. I'd want to make server-provided scripting less boring

**Comment by 4w** [comment]
So instead of making it less boring maybe think about it.

I mean, c’mon … At least properly answer the questions.

https://github.com/minetest/minetest/issues/5393#issuecomment-358786307

**Comment by rubenwardy** [comment]
This is not comparible to #6114. That issue is about detecting modified clients, at which point the user has already custom compiled their Minetest. builtin hashing is about whether Lua has been modified, which is being checked by C++. It relies on builtin being easier to modify than C++.

I'd prefer builtin to just not be loaded if the server doesn't send any mods

**Comment by red-001** [comment]
it's similar in the way that it's an over-engineered solution and that once one person breaks it becomes close to useless.

**Comment by paramat** [comment]
Apparently securing builtin will have to be done whether or not #6951 is merged.
See http://irc.minetest.net/minetest-dev/2018-03-10#i_5249651

18:45 sfan5       the pr does not remove the need for hashing builtin btw
18:45 paramat     oh ok :)
18:46 sfan5       if a servers wants to disable client-provided mods, but use its own csm mods you need to load builtin
18:46 sfan5       (I assume this is planned)
18:46 paramat     rubenwardy's comment https://github.com/minetest/minetest/issues/6736#issuecomment-358479221
18:46 Krock       #5393 is about that exact issue
18:47 ShadowBot   https://github.com/minetest/minetest/issues/5393 -- Server-provided client-side scripting
18:47 sfan5       otherwise the server has two options 1) don't allow use of CSM at all or 2) make us of CSM but allow the client to inject their own code
18:47 sfan5       +e
18:50 Krock       so builtin should be secured on a way that at least minetest has to be recompiled to make builtin modification possible
18:50 Krock       that's possibly the most we can do for this, as the client's data can not be trusted

**Comment by paramat** [comment]
@nerzhul Could this be done soonish? High priority.

**Comment by paramat** [comment]
I think we need to start working towards a 0.5 freeze so this now needs attention.

**Comment by paramat** [comment]
@sfan5 @nerzhul in #6738 you were planning how to do this, are either of you able to work on this soon to allow 5.0.0 to be released?

**Comment by sfan5** [comment]
Since server-sent CSM isn't planned for 5.0, we aren't in a rush to implement this either.
Its whole purpose is to fix exploits that appear when you allow server-provided CSM but not client-provided CSM.

> Is there any way to avoid having to do this securing of builtin?

In theory the server could send its "own" builtin, but this doesn't really work in practice because different client versions require different builtin implementations.

> so maybe CSM could be completely disabled for 5.0.0 and until SSCSM is ready?

Not sure if that's a good idea, the main problem with CPCSM in 0.4.16 was that no control was given to server owners and mods could pretty much do what they wanted.
This discussion is better had in a separate issue anyway.

**Comment by paramat** [comment]
> Its whole purpose is to fix exploits that appear when you allow server-provided CSM but not client-provided CSM.

Sorry i misunderstood, i thought this was essential for security against CPCSM, removing labels and milestine ..

**Comment by paramat** [comment]
To be clear, it seems that the request of this issue will only be needed once SSCSM is implemented. As that is highly uncertain to happen, or still distant, i will close this issue for now.
