### ISSUE TITLE
Ability to specify location of user data directory

### ISSUE THREAD

**Issue by twistedlizard** [minetest/minetest#6961]
##### Issue type

 - Feature request

##### Summary
I'm working in a school and want to run minetest in an after-school club. In a school environment, the minetest folders would reside on a read-only server share, from which users can invoke minetest.exe.

Problem is, I think minetest expects users to have write permission on the minetest folders and to be able to create a 'user data directory' somewhere within them. 

I suggest some setting in minetest.conf where the path to a user data directory can be specified. Something like:
user_data_directory = "h:\minetest"

**Comment by SmallJoker** [comment]
The `minetest.conf` file also contains user data, like the username, last connected server and of course all the visual settings which include the chosen texture pack.

## Generic solution
Create symbolic links. This works with NTFS and most likely with UDF too.

## Solution for subgames and read-only worlds
### Subgames
Set the environment variable `MINETEST_SUBGAME_PATH`` to the according path where the subgame directories can be found.
### Read-only worlds
Same as with the subgames but now with the env variable `MINETEST_WORLD_PATH`.

**Comment by sfan5** [comment]
The correct solution for this would be to use `RUN_IN_PLACE=0` builds, these will automatically place all user data in the user-specific AppData folder.

**Comment by twistedlizard** [comment]
Could such builds be made available alongside the other downloads at https://www.minetest.net/downloads/ ? I'm on Windows.

**Comment by paramat** [comment]
Seems resolved.

**Comment by nycki93** [comment]
This appears to be no longer possible as symlinks don't work anymore. Is there a new way to do this?

**Comment by rollerozxa** [comment]
LUANTI_USER_PATH environment variable can change it

**Comment by nycki93** [comment]
> LUANTI_USER_PATH environment variable can change it

Thank you! Where is this documented? And, how do I set it on Android?

**Comment by sfan5** [comment]
> Where is this documented?

The manpage.

> And, how do I set it on Android?

Not possible.

**Comment by nycki93** [comment]
> The manpage.

I see! Can that be made accessible from the flatpak? Or added to the wiki?

> > And, how do I set it on Android?
> 
> Not possible.

Darn. Is there another way to sync my worlds between devices on Android?

**Comment by SmallJoker** [comment]
@nycki93 #15141 #13427 #16077
On Android 6 I do have full access to the data directory from the file manager. However, with more recent Android versions a new method is required. Please find someone who's got the interest and knowledge to implement this. Almost (if not all?) regular Luanti contributors develop for desktop, perhaps sometimes for handhelds.

EDIT: As for Flatpak: Use the `--env=LUANTI_USER_PATH=/xx/yy/zz` argument.

**Comment by nycki93** [comment]
> As for Flatpak: Use the `--env=LUANTI_USER_PATH=/xx/yy/zz` argument.

Thank you, but what I actually meant was, can the knowledge about that parameter be made accessible? I dont think I've ever needed to access the man page for a flatpak, and I suspect most users won't know how. 

My goal here is that "sync save files across local devices" should be discoverable. Right now if you try the simple thing (symlink worlds to a shared folder), it doesn't work, and the error message (mod security) doesn't tell you what broke or how to fix it (disabling mod security doesn't fix the issue either). So far it seems like the options are to set this variable (not mentioned on luanti.org i think?) or to set up a bind mount in fstab, which is overkill + footgun, I've gotten linux machines stuck at grub before because I made a bad fstab change, and its not easy to find out how to undo it.

I can open an issue for this if you like! I was worried it would be closed as a duplicate of this one, which is why I asked here.

edit: by the way, my "ideal" solution for this would be to add mods, games, worlds dirs to advanced settings, like how it works in prism launcher. this might also work in conjunction with the android permissions issue: have the user pick a folder from within the app.

**Comment by j-r** [comment]
> this might also work in conjunction with the android permissions issue: have the user pick a folder from within the app.

AFAIU that is no longer supported for apps that target recent SDK versions, and official Luanti must do that to be eligible for the app store.

For now if your devices still support it you can locally modify the android build to target SDK 28 and request external storage permissions. But this only works reasonably well, if your devices are android 10 or older, because starting with 11 accesses to external storage are filtered through a user mode fs layer and become too slow to be usable. I do something similar for my family's devices with lua code inside the main menu to synchronize data between local and external storage, but that is just a hack and not an upstreamable solution. The R/W document provider and/or support for popular backup/restore backends as requested by the issues linked above are needed. There already is a PR with Android's sample document provider code adapted for the read use case that could be a starting point for interested persons (i.e. not me:-).
