### ISSUE TITLE
World Biome Selection

### ISSUE THREAD

**Issue by TekhnaeRaav** [minetest/minetest#6967]
##### Issue type

 - Feature request

>A setting when you create a world that allows you to select which biomes that will be generated.

This would be useful if you want to build something in a specific biome, or two; and just nice in general.

_Am I right on how to use the issue template for a feature request (I'm assuming you don't need computer information and all that)._

**Comment by ThomasMonroe314** [comment]
I think that this is actually a great idea :smiley:

**Comment by paramat** [comment]
The issue template is only for bug reports.

Biomes are a game thing, the mainmenu has no access to that information, it would be a lot of work and complex to get that information, create the formspec, and apply the choice to the biome system.
I realise that it seems nice from a user perspective, but more specialist world configuration is done in MT using mods that use the existing APIs.

There is an API for removing singe biomes, that is easy enough to code into a mod. It would be much less work for a modder to write a mod using the existing APIs than to try to code this into the engine.
Due to being a FOSS project we have a severe lack of dev time so have to keep things simple, this feature is not justified and is more engine bloat when it can be done already another way, sorry :-1:

**Comment by ThomasMonroe314** [comment]
@TekhnaeRaav I gotta agree with paramat there, its probably better done as a mod than in-engine

**Comment by TekhnaeRaav** [comment]
:sob: :sob: ...No I'm just kidding, this makes sense. :+1:

**Comment by Fixer-007** [comment]
What I love in MC is how easy you can customise a custom world? In minetest - nope-nope, you end up writing mods, reading manuals to edit that mapgen world config file and that take hours (if you can program) instead of minutes in MC.

**Comment by red-001** [comment]
I don't see how is this any more non-trivial then the typical pull request, from my limited knowledge of mapgen all that would be needed for this would be creating some sort of system for subgames to tell the world creation dialog what biomes in it can be disabled and just saving the user input relating to that to either to a new settings file or finally adding per-world settings.

On the minetest game side of course it could be a bit more complicated as you would have to avoid creating areas without biomes or tweak the biome system to just use the closest biome if it can't find one for a location (not sure how that's all implemented that might be non-trivial)

**Comment by paramat** [comment]
Ok removed that label as it is possible (but not justified).
> What I love in MC is how easy you can customise a custom world. In Minetest - nope-nope, you end up writing mods, reading manuals to edit that mapgen world config file, redefine entire biomes just because you want water level changed and that takes long time even if you are a geek instead of minutes in MC GUI.

There's a reason for this as i explained above.
Nevermind MC, you can't compare a FOSS project to the world's 2nd most popular game with a dev team valued at 2 billion USD.

**Comment by MillersMan** [comment]
Still I find the idea of a system to specify mapgen/mod-details from within the main-menu intriguing. While it's clear that it won't happen overnight and even might take a lot of time it still would be a useful long-term goal. This way new stuff could be designed with keeping this in mind and making the engine ready for it step-by-step.

**Comment by paramat** [comment]
This happens already, mapgen parameters are editable in advanced settings.
A game is able to add new settings to the advanced settings menu so we can already add game parameters for biome choice, it can't currently be done on world creation though. So this may be more a game issue.

**Comment by paramat** [comment]
I think this request should be moved to MTG since it will be much simpler to implement through MTG settings.
However even then i still think this should be done by optional mods using the existing APIs. Very many world customisation possibilities are only possible in mods, and this is intentionally how MT is meant to operate.

**Comment by paramat** [comment]
Please move issue to MTG.
