### ISSUE TITLE
Unhelpful minetest.set/add_node error message

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6977]
##### Issue type

 - Feature request
 
##### Summary

https://forum.minetest.net/viewtopic.php?p=309902#p309902

I think when using minetest.add_node (or minetest.set_node) with a not registered node, it says "Not allowing to place CONTENT_IGNORE". This message is unhelpful, it should tell what actually happens: minetest.set_node with unknown node.

**Comment by nerzhul** [comment]
please respect the new issue template...

**Comment by HybridDog** [comment]
ok

**Comment by QwertyCoolMT** [comment]
If no one else is working on this, I'm going to take a crack at it.

**Comment by sofar** [comment]
This is almost worth crashing the lua state for. Any mod that causes an invalid node to be passed to `set_node` should be halted immediately, and making a warning message will just cause other issues later on.

**Comment by QwertyCoolMT** [comment]
I had two thoughts on a change around this:

One we could go the way of changing the error message to be more broad, but also potentially more helpful to someone in this situation. (ie cant place ignore nodes OR place unknown nodes)

or we can change the upper functionality in map.cpp from switching unknown blocks to ignore blocks and instead switching them to a new "unknown" block which is essentially a copy of ignore but has its own error message corresponding to what is happening more accurately.

my concern since i'm new is, will playing with that code cause problems later somewhere else? is this a much bigger change than I'm thinking? I think that if it can't be placed, it shouldn't really interact with anything else in any other way, and should be fine, but again, I don't know the code well enough.

**Comment by HybridDog** [comment]
> Any mod that causes an invalid node to be passed to set_node should be halted immediately […]

l agree.
The problem lies there: https://github.com/minetest/minetest/blob/master/src/mapnode.cpp#L47
MapNode has a constructor which gets the node id from a node name (or sets ignore).
I think this constructor should be moved to a function in lua script c++ api and cause a crash with backtrace for unknown nodes. AfaIk this constructor is currently only used for mods.

> […] instead switching them to a new "unknown" block […]

I don't think mods should be able to set weird nodes.

**Comment by paramat** [comment]
> This message is unhelpful, it should tell what actually happens: minetest.set_node with unknown node.

This is not easy, as 'ignore' is being passed to 'setNode' from elsewhere, and ignore can be passed for various reasons. I don't think it's worth adding complex code to pass the unnown nodename to setNode :-1:
