### ISSUE TITLE
Get hardware coloring more flexible and get it out of param2 and make it less annoying to use

### ISSUE THREAD

**Issue by 4w** [minetest/minetest#6979]
Currently hardware coloring is [directly bound to `param2`](https://github.com/minetest/minetest/blob/7d3295e21f96495cb0b3e2f732939344ce892e2a/doc/lua_api.txt#L580L606) which works as long as one wants to color a full “node”. As soon as one wants to color a facedired node, a wallmounted node, a nodebox, or any other type of node hardware coloring is either limited or impossible because param2 is needed for something else or has to be shared between the definition and the hardware coloring options.

It would be good if hardware coloring gets it’s own field in the node definition (backwards-compatibility: if not present, don’t colorize the node).

And when it has it’s own field setting this field to either a palette index OR an RGBA color definition color the node in that color and optionally alpha the color overlay by the value given in the RGBA definition. And getting rid of [this clusterfuck](https://github.com/minetest/minetest/blob/7d3295e21f96495cb0b3e2f732939344ce892e2a/doc/lua_api.txt#L557L567) by NOT stretching the pallette indexes would be nice, too.

Oh, and a simple colorize = 'RGBA' -- set this to the desired red/green/blue/alpha node parameter would be waaaaaay better than craming the whole color definition stuff into param2 where already a lot of other node specifications are stored.

Maybe remove this palette thing as a whole and make dyes having a custom parameter representing their color so the value can be simply accessed via getting the wielded item and then can be applied directly as RGBA value.

As of now there are conversion tables from item ID to palette index and palette index and actual pixel of the palette and all the way round the actual pixel color should match the dye color whose item ID you translate to the palette index and every single dye has to be manually added to that “translation table”. (Yes, I am aware ow “library mods” being capable of doing this semi-automatically but that is not the point here.)

All of this should be done now while hardware coloring isn’t properly/fully implemented yet.

Derived from the forums discussion [started here](https://forum.minetest.net/viewtopic.php?p=309474#p309474)

**Comment by juhdanad** [comment]
Hi! The hardware colorization was implemented by me. Let me answer your questions.

The goal of hardware colorization is to reduce the number of textures in the video card's memory, and to reduce the number of registered nodes. There are two ways to colorize nodes:

- Set a single color for the node: you can register the node for each color. So you will have many similar node definitions, with only the `color` property differing. This way you can colorize all kinds of nodes, and you can set the exact color of the node (in RGB). This is still better than using texture modifiers, because the video card will have only one version of the texture (it doesn't need to switch for different colors, speeding up rendering).
- Use `param2` coloring: to reduce the number of registered nodes.

**Why `param2`?**
I didn't want to increase the size of the world in the memory and on the hard drive. So I had three choices to store the color of a node: in `param1`, in `param2` or in node metadata. `param1` is mainly for light, and I didn't want to exclude nodes that let light trough from colorization. On the other hand, node metadata consumes a lot of space. A world consisting of many colored nodes (like colored grass) would contain a huge amount of metadata. So the only option is `param2`.

**Why did I choose to use palettes?**
There are 256 different values for colorization. This is not enough for all purposes. One might want grass colors with small differences, or various colors for a paint mod. So I wanted to make these 256 colors customizable. And the easiest way for a modder to define 256 custom colors is to create an image.

**But why do I stretch the palette?**
To avoid checking the node's type when creating a mesh for a map block. The color bits are always the most significant bits of `param2`. This means that if I scale all palettes to 256 pixels, then `param2` will tell the correct index regardless of rotation. So getting the node's color is just `color = (palette == null) ? 0xFFFFFF : palette[param2]`. It is not necessary to know `paramtype2` to tell the color.

**And what about creating palettes by Lua or getting pixel colors?**
Unfortunately, the Minetest server doesn't use image processing. The palette is sent to the client, but never read by the server. This can be solved by making Irrlicht part of the Minetest server, I think. The Lua palette creation is doable by a lot of texture modifiers currently (create an one pixel white image, and add translating and colorizing texture modifiers), but this should be easier in the future.

I'm happy that you find this feature worthy of discussion, please let me know what do you think.
Is colorization so important that `param3` should be introduced? Is there a better way than to stretch textures? Should the server be able to load and manipulate images pixel-by pixel before sending it to the client?

**Comment by 4w** [comment]
Thanks for your answer!

To ensure always 256 pixels wide palettes: why stretching? Why not simply adding black, white, or transparent pixels at the end of the user defined pixels? This would reduce the complexity of using <256 pixels palettes because index 7 will always be 7 regardless if it’s on a 2x4 palette, an 8x8 palette or a 16x16 palette.

Right now I did exactly this in my cement mod. I use [a 16x16 palette](https://github.com/4w/cement/blob/0fc348279a505813ed42a7b16b3b0ec2cf7683d6/textures/cement_palette.png) with only the first 16 pixels set to colors and the rest is black, and in the translation table I [map the dye IDs to the colors indexes](https://github.com/4w/cement/blob/master/init.lua#L9L27) and simply ignore the rest.

> please let me know what do you think.

I think hardware coloring has a LOT of potential! If it were implemented as node metadata instead of `param2` (please no `param3` and a second attribute to tell what’s `param3` is for but a simple `color` being either 0-255 for palette index or RGBA for a direct color and alpha value) and would allow an alpha value to be set it could completely replace [`[colorize:color:ratio`](https://github.com/minetest/minetest/blob/de2c40c8fc189eeeeba010a0aaa1d28aed588c68/doc/lua_api.txt#L499L508)

Currently the lack if adaption by modders is caused by the implementation. It is simply too complicated to set a color (i.e. dye type, palette, palette index, and the “translation table” have to match) and coloring is limited if `param2` is used for other things.

I imagine one dye texture and all registered dyes use this texture and set `color = RGBA` and in the on_punch function of the node that is to be colored the modeer can simply access the wielditem’s `color` ttrybute and set it as the node’s `color` attribute.

This could even be automatically possible within the engine. So ALL nodes registered by ANY mod can be automatically colored with ANY registered dye without the modder has to add one single line for coloring. (Colorize with any item in the `dye` group by using this item’s `color` and set it to the punched node’s `color` attribute. To exclude nodes from being colored add them to the group `not_colorizable` or something like that).

**Comment by paramat** [comment]
Node metadata is too slow and memory-consuming to use for hardware colouring.
Hardware colouring seems popular with modders, if the mods are few in number it seems to me it's because it is a very new feature that is still slightly incomplete in 0.4.16 stable.

**Comment by 4w** [comment]
> Node metadata is too slow and memory-consuming to use for hardware colouring.

What about implementing it like param2 was implemented which implicitly being faster? Or what about extending param2 to 32 bits?

**Comment by paramat** [comment]
Enlarging the mapnode is an extreme change that changes world format and has performance and memory-use consequences, it needs a huge amount of justification, and hardware colouring is i feel not remotely enough. There is discussion of enlarging mapnode in some other issues such as coloured light, and changing world format is discussed in the 'light bank' issue.

**Comment by juhdanad** [comment]
Color metadata is a good idea, but it is not sufficient for large number of nodes (like grass or building blocks). But for a colored LED node it is ideal, because all colors are possible without a palette. Currently the mesh generator doesn't use metadata, and it would be a major change. Also all metadata contain an inventory, which is not used there. This should be changed too.

**Comment by 4w** [comment]
> but it is not sufficient for large number of nodes (like grass or building blocks)

By default the value could be unset meaning “don’t colorize this node”.

> But for a colored LED node it is ideal, because all colors are possible without a palette

Yes, using RGBA instead of a palette would raise the possible colors from a maximum of 256 to a maximum of 4,294,967,296 colors (full RGB space times 256 alpha values: `00000000` to `ffffffff`). A lot of those colors look pretty much the same, but the point here is not amount but possibilities. And you wouldn’t even need a “translation table” for it.

Even if 256 colors sounds a lot, it isn’t. And under most circumstances you can’t even use 256 colors palettes because of the `param2` limitations.

**Comment by juhdanad** [comment]
> but it is not sufficient for large number of nodes (like grass or building blocks)
By default the value could be unset meaning “don’t colorize this node”.

I meant mods like [Luscious](https://forum.minetest.net/viewtopic.php?f=9&t=18862). Would you create metadata for all grass blocks during world generation? Sometimes `param2` coloring is better.

**Comment by 4w** [comment]
> Would you create metadata for all grass blocks during world generation? 

Of course not. Only the ones that are intentionally colored different.

**Comment by raymoo** [comment]
@4w In Luscious, every grass node is colored.

**Comment by juhdanad** [comment]
It is possible to modify the map format to allow multiple uses of `param2`. Then you could declare a `facedir` node with a full palette. However, this change would be huge. You can read the idea [on the forum](https://forum.minetest.net/viewtopic.php?f=7&t=19549).

**Comment by raymoo** [comment]
If we're considering map format changes, why not consider something bigger?:
- Params are no longer stored in the main node data, except maybe light because it's so ubiquitous that it is likely to be present in every block. Instead each 16x16x16 block of paramN values is stored in a separate entry keyed by (block key, param number), or something equivalent. Alternatively the blob format is just expanded to allow for variable number of parameters.
- There are an arbitrary number of params, the number of which are not stored explicitly but instead is implicitly represented by the highest used param number.
- Blocks where a param is 0 everywhere implicitly represent this by not having an entry for that parameter.
- Nodes define param type / param number pairings that are used to determine which parameter means what. It could simply be a list `{ "paramtype1", "paramtype2", "paramtype3", ...}` which maps each type to their position in the list.
- (Bonus) Params can be of different widths than just 8 bits. This type could be an additional dimension to the param blob key.

With this system you would still only store a couple param blobs for most blocks (light + one extra for nodes that only use one param), or even only one set of params for areas players haven't touched with weird nodes yet. If a node needs to use more than two params though, it will be able to mix and match whatever they need. Mods could also use the additional params for data they want to be able to get / store more efficiently than metadata.

Memory usage may be increased a little, or possibly lowered if enough blocks only use one param, but the main cost would probably be computational.

**Comment by paramat** [comment]
These radical ideas are fine theoretically of course. But practically for MT, the map format change and amount of rewrite needed, for something not particularly important, would make these ideas very controversial. I feel that hardware colouring is essentially ok, it's the way it is and has limitations for good reasons, and modders should work within the limits. Param2 hardware colouring is a specialist feature that is not intended to be used on every node whatever the param2 usage is.

We actually intend to add a 'simplecolorfacedir' drawtype that has a simple 4-value rotation around the Y-axis, allowing more palette colours. This will help.

**Comment by 4w** [comment]
> for something not particularly important *because how it was implemented*

FTFY 😄

**Comment by Sokomine** [comment]
Please keep in mind that even the old roundabout 16 colors we had worked only to a limited degree. Players have to obtain them (got much more difficult with mixing receipes removed), mix them, store them, apply them to the blocks. I'm not convinced that the "punch node with dye to paint it" approach will work well enough. It might even prove difficult for the player to judge if the dye he's holding in his hands is the same as the one used previously. My mods (colormachine, plasterwork) are my way of dealing with that problem and I hope they are helpful.
Technicly, hardware coloring works just fine. Get up to 256 colors for close to no price at all - that is great!

**Comment by 4w** [comment]
> Get *up to* 256 colors for close to no price at all - that is great!

This “up to” thing is one part of the issue.

**Comment by VanessaE** [comment]
I would have to side with @raymoo's [comment from Jan. 29](https://github.com/minetest/minetest/issues/6979#issuecomment-361381657), better to extend the map format and not fuck around with param2.  Seriously, one byte per node is just not that big of an increase in map size, especially when using a backend that compresses the map data.

@paramat, since the above is unlikely to ever happen, I hope simplecolorfacedir happens soon.  I guess it won't be in the 0.4.x branch, though. :smiley:

@Sokomine "Place and punch" is a thing of the past.  Now colored stuff is made by crafting, like it used to be.  See the [my latest posts](https://forum.minetest.net/viewtopic.php?f=11&t=2178&start=75#p328951) in the Unified Dyes forum thread for details.
