### ISSUE TITLE
Stop shipping devtest game in release builds?

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6987]
##### Issue type
 - Feature request
 
##### Summary
Minetest still ships the minimal development test in release builds.
Is there any reason for this?
I think it should be removed or at least hidden in official Minetest releases. Of course it can stay in the repository, visible to developers, I don't mind. But it just doesn't make sense to ship a fairly obscure subgame that is useless for normal players by default.

**Comment by ThomasMonroe314** [comment]
I don't see a problem with that

**Comment by C1ffisme** [comment]
With the new minimal in #6716, we're going to both remove any kind of legacy support for the old minimal game and we're going to be making the subgame even less useful for gamers and youtubers.

Definitely remove minimal from release builds, so that new Youtubers and Gamers that don't know better don't accidentally choose minimal rather than MTG.

**Comment by nerzhul** [comment]
i think it's better to warn minimal is a test game permitting to test various MT functions than removing it

**Comment by Wuzzy2** [comment]
Minimal already does that in a chat message when you start it. But this is besides the point. The point is that this subgame is useless for >90% of people.

Why should Average Joe Who Is Definitely Not A Programmer be bothered with a test game? The few people who need Minimal know where to look.

Here are our options:
* Rip out Minimal from the Minetest repo and give it its own repo, just like Minetest Game
* Keep shipping Minimal, but hide it from the main menu if Minetest detects itself as a release build, unless a `minetest.conf` setting says otherwise
* Remove Minimal only from the release zip archives but keep the rest intact

**Comment by nerzhul** [comment]
removing it from MT core repo is not a solution as this is used in development for integration tests. One solution can be to hide it in release mode and add a toggle flag in settings, maybe

**Comment by 4w** [comment]
> as this is used in development for integration tests

So it is a development tool. Why are development tools shipped with non-development builds?

**Comment by nerzhul** [comment]
why does some games embed (it's rare nowadays but not on every engine) a graphics test if it's a devel thing ?

**Comment by jastevenson303** [comment]
nerzhul do you have a strong opinion that Minetest should indeed ship with Minimal Development Test in all instances?

**Comment by Ferk** [comment]
Just for the record, this was also requested in the past: #1740 #4006

**Comment by Megaf** [comment]
I totally support shipping the minimal subgame. It could be renamed to dev or test or something else if people want. minimal still a very nice and slim and lightweight dev environment for mods.

**Comment by 4w** [comment]
> why does some games embed (it's rare nowadays but not on every engine) a graphics test if it's a devel thing ?

And why do the samer stupid thing and ship a whole development subgame and unit tests with the release version?

**Comment by nerzhul** [comment]
Having this permits to Ask users for a feedback using minimal test commands on some bugs, for example ?

**Comment by 4w** [comment]
Debundle and provide as separate subgame then? People who want to participate here or want to develop mods without “Minetest Game” will download and install it, all others do not care if it is not there anymore. Plus: no-one accidentally selects the even more barren “minimal” instead “Minetest Game”.

Same with unit tests (provide a compile flag to enable them but have it disabled by default).

**Comment by paramat** [comment]
Minimal will become more useful, players are often also modders, the code and the game will become a useful resource for studying code and seeing how it works. So i can see good reason to leave it in, the name is already a good warning.

**Comment by 4w** [comment]
> Minimal will become more useful when rewritten.

But no-one ever will.

**Comment by pilino1234** [comment]
> But no-one ever will.

#6716 ?

**Comment by 4w** [comment]
> #6716 ?

*All checks have passed  
This branch has no conflicts with the base branch  
Only those with write access to this repository can merge pull requests.*

Well then ...

**Comment by pilino1234** [comment]
> Well then ...

‌> [WIP]

**Comment by C1ffisme** [comment]
> Players are often also modders

Maybe, but Minetest is still in an "early development stage", so this is probably true just because of that fact. If this game reaches a more complete version with gameplay that will get people to download and try the game, then there isn't much of a reason to keep in minimal for those people.

Plus, for people that aren't modders who are interested, if they download the game and click on minimal without thinking twice, they might create a world in a crappy-looking subgame only to realize later, or worse never, that there was a much better-looking subgame available to them.

**Comment by rubenwardy** [comment]
:+1: for removing minimal from release distributions

**Comment by paramat** [comment]
> Minetest is still in an "early development stage"

Erm no.
> so this is probably true just because of that fact.

No, Minetest is about modding and always will be no matter how developed.
>  if they download the game and click on minimal without thinking twice, they might create a world in a crappy-looking subgame only to realize later, or worse never, that there was a much better-looking subgame available to them.

The game title and game screen reading 'Minimal Development Test' is warning enough, if they don't get the hints and also don't check out the other game they're stupid and we're better off without them =)

**Comment by C1ffisme** [comment]
> No, Minetest is about modding and always will be no matter how developed.

Is it?

**Comment by jastevenson303** [comment]
Paramat please don't be unpleasant to users, we do stupid things for a reason.

**Comment by pilino1234** [comment]
> they're stupid and we're better off without them =)

what the fuck?
I agree with the rest of your points, but what is this line supposed to accomplish?

(applying it in the other direction works too, btw)

**Comment by Ferk** [comment]
If minimal was changed to be more interesting, with testing tools and maybe some initial area around the spawnpoint with signs and hints that served as a sort of introduction to the game for "players who often are also modders" , that would be cool.
But then the problem is that it might plant the seed to no longer be so "minimal". I'm afraid many proposals won't make it if it's actually intended to be a "minimal" subgame.

Perhaps the purpose of minimal should be defined before making a decision.
If it is to be the minimum necessary for a subgame to exist + some stuff targeted to test the engine, then I think it shouldn't be in the releases, because that's might not be very interesting for neither players nor normal modders.
If it's intended to be developed to be friendly to devs and players interested in modding, then that sounds very good to me, I think it was in the plan to ship more games with Minetest after all, but then it should be developed further in that direction, even if it means adding more content to it.

**Comment by TumeniNodes** [comment]
hmmm, I gave a thumbs up to a comment nerzhul made but, thinking on it more, IMO it should be removed from releases and remain obtainable as a download for those who wish to use it for development or learning. Just be sure to add some notation regarding this on the main webpage.

To be honest, shipping this with a release can cause some confusion. Remember, many end users are children, and even not all adults/parents of those children are programmers/coders, and it can be as equally confusing for them.

The easiest thing for anyone, in any profession to forget is, not "everyone" out there automatically knows how to do what you do, or even understands half of what you say related to it.
The focus should always be on end users and, to do so, means you have to be able to see things from a layman's point of view.

"strip the shit, and ship the hit" (don't ask, I literally just came up with that)

**Comment by 4w** [comment]
> […] they're stupid and we're better off without them =)

This says a lot more than you probably wanted to reveal.

**Comment by Wuzzy2** [comment]
So, almost everyone is agreeing to somehow remove or hide Minimal. I think this point is settled.

But we don't seem to agree on *how* to do this exactly. Let's focus on this now.

So. Removing it from the repo directly has already been ruled out by nerzhul. I agree with the reasoning. I do not want to dictate the core devs how to do their work. That would be silly.

If Minimal is just *hidden* in release builds, unless a special setting says otherwise, would this work without making core devs angry, I suppose? ;-)

Remember, the point is not to actually take anything away from anyone, just to remove distractions to the non-coding players (i.e. >90% of players).

**Comment by paramat** [comment]
Don't worry, my =) was to hint to not take the comment too seriously.

**Comment by C1ffisme** [comment]
> i very much doubt any player would miss the hints given by the game name and title screen text

They are very obvious hints to us, the people that have been playing or developing the game for years now. As someone who knows people that often ignore important GUI text, cut-scene dialogue or stuff that the game intends for you to read and hear, it's not entirely impossible for accidents like this to happen.

**Comment by numberZero** [comment]
Just *drop it* from binary releases.
It may be nice to ship it separately, however, but as a special development tool, so that anyone who can be interested in it (i.e., any modder targeting more than MTG) should be able to find it. There should be other tools as well ofc, like formspec editor, for example (there is one somewhere IIRC...).

**Comment by paramat** [comment]
I'm neutral on this. No objection to removing it from release builds.

**Comment by paramat** [comment]
:+1: for removing from release builds.

**Comment by sfan5** [comment]
@Wuzzy2 Do you still support this even when Minimal is now Devtest?

**Comment by Wuzzy2** [comment]
Yes, it's still a DEVELOPMENT test, after all.

**Comment by pandaro** [comment]
coming from another experience in the production of open games, the issue has been solved in the launcher.
An option to select called 'development' has been added.
once selected, it shows us all those features defined as 'experimental' and provides us with all the tools that developers need.
This precisely prevents the possibility that a player finds himself having his first experience in a development environment that is certainly not suitable for him.
On the contrary, however, there has always been a debate as to whether there should be a "playable" game attached by default and if so, which one should be attached.
The issue is difficult to resolve and I have never fully agreed with the solution that was taken, which was that no game was attached, this is to protect every content creator.
On first download, once you enter the "singleplayer" page, and as long as there are no games or the "developer" option is enabled, a "download content" page should be offered.

**Comment by rollerozxa** [comment]
Development test should stay like it is in the source repository for in place builds, but when "installing" Minetest for release builds or packaging it shouldn't copy over devtest. This is already done on Android, in fact. If modders want it we can put it up on ContentDB with each stable version having its own release, as with MTG on CDB.

**Comment by rollerozxa** [comment]
#13081
