### ISSUE TITLE
Guest mode

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#7009]
##### Issue type
 - Feature request
 
##### Summary
Add guest mode to servers.

The guest mode is a special way to join a server.
Players are free to join any server as a guest.

If you chose to join a server as a guest, you never require a password, they get a guest name (e.g. “Guest” + random number), fewer privileges than normal users (set at the discretion of the server operator) and most importantly, do NOT trigger the creation of a full-blown account.
This means whenever you leave the server, all your progress is gone.
Guests might be denied to join a server when it is close to being full, in order to guarantee access to normally registered players.

Optionally, guest privs can be changed in `minetest.conf`. By default, guests have no privileges at all.

When a player joins a server as guest, the player must be clearly notified about this after joining. Maybe a permanent message at the top left could be written.

##### Why guest mode?
Server-hopping.
That is, you want to quickly browse around random servers without going through the hassle of creating a new account and thinking of a new password for every single server. The idea is, of course, to find interesting servers quickly. And of course, as a security-minded person, you are using a different password for every single server.

When you do server-hopping you often don't stay or a long time, unless a server really catches your attention (which is the point of server-hopping). So it's really a big inconvenience, for both the player and the server operator, to be forced to create an account no matter how long you actually want to play there. As a player, you probably don't know in advance whether you like a server or not. So, a lot of accounts are never used again.

Having guest accounts would also greatly cut down the number of throwaway accounts, because there's no longer a reason to create them.

Server operators, please hear me out: I know a lot of you hate so-called “guests” (there are no real guests in MT yet, however) as you believe most of them are trouble-makers.
That's where privileges come into play: By default, guests get no privileges. That way, guests can't cause damage or flood the chat. They really can just walk around and get their first impression, which is exactly the goal of allowing guests.

##### Risks
Players might miss the notification that they're currently in guest mode and not realize they will lose everything as soon they leave. But the lack of the `interact` priv makes building and collecting stuff pretty much impossible, so there's not much to lose and it should be obvious quickly.
That's why every guest must have a predictable name (“Guest” + number).
Another risk is the lack of `shout`, so confused newbies who need to ask for help in chat might get lost.

The predictable guest names could be a problem, because currently, there are REAL accounts with names of guest accounts. I don't have a solution for this yet. Ideas are welcome!

**Comment by Ezhh** [comment]
Another risk: Players won't use it because:
-  If it defaults to no privs at all they can't ask for info about the server, which can be part of the point of server hopping. 
- Many servers set up spawn areas that you'd need an actual real account to leave. You won't know this until you join the server, so the seconds it takes to enter a password are still going to be worth it.

**Comment by paramat** [comment]
@tenplus1 @VanessaE @shivajiva101 @Megaf opinions?

**Comment by VanessaE** [comment]
No thanks, I already have guest accounts forbidden on my servers by a mod.

**Comment by paramat** [comment]
I can't see any good reason for this. Encouraging more casual visitors is not good.

**Comment by ChaosWormz** [comment]
i think this could be a good idea, if the guests are spectators without actual avatars, cannot cause new map to generate, and are treated with lower priority by the server as to not influence server lag as much

**Comment by paramat** [comment]
That's even worse.

**Comment by Ezhh** [comment]
> There is really no reason to unless the server has something to hide.

Come on Wuzzy - since anyone can just make an account, how exactly is anything being hidden? Either way this is something servers do, and guest accounts wouldn't work with this.

Moving on to my own personal thoughts - I'm really not in favour. It seems like a needless complication and isn't something I'd want on my servers. It's also not something I'd feel even slightly inclined to use when visiting other servers. Making an account is already quick and easy, and without some of the features you'd deny to guest accounts, I wouldn't be able to experience enough of a server to know if I'd want to play there.

**Comment by VanessaE** [comment]
By guest account I mean that "Guest1234" username business, and similar such usenames as created by some mobile minetest client forks.

**Comment by rubenwardy** [comment]
This feature really isn't needed. I'm not even sure what problems it's supposed to solve - it won't resolve excess resources, as most clients are from apps with their own naming system, and it's not like making an account to look around is particularly difficult. A better solution would be to add the facility to prune players which haven't got interact or haven't played in the last N months, or similar.

:-1:

**Comment by jastevenson303** [comment]
In Quake one may join the server without joining the game (spectator slot
versus player slot).

**Comment by shivajiva101** [comment]
If you want guest accounts make some with blank passwords and assign the privs you want, advertise them as guest accounts. This seems to fulfil your requirements in a simple format that requires no changes...

**Comment by Wuzzy2** [comment]
@shivajiva101: That wouldn't help since you still need to know the (non-standard) name of the guest account which can be different from server to server. So it's useless for server hopping. Also, I'm not a server operator, so I can't do this.

**Comment by shivajiva101** [comment]
If a server owner wants to provide guest accounts they can do so via the method outlined and advertise it on their forum thread, you can't be suggesting it's enforced on server owners surely

**Comment by paramat** [comment]
@sofar

**Comment by sofar** [comment]
I'm not opposed to the concept of having something like a `spectator` at the engine level.

It poses, however, a significant design change to the core engine.

Either spectators (guests) are actual in-game entities, or they are not.

If spectators are "like" players, then they are essentially normal players, should log in like normal players, and having a password should really be enforced. pre-shared passwords for limited accounts is ripe for abuse and "you're going to have a bad time"(Parker/Stone).

What I think you want is something more like real spectators, where the spectator receives the data stream from the server, but is never capable of interacting with the server. You could consider implementing this by making a separate server thread that listens on a secondary port number and that allows clients to connect and spectate, without consuming resources on the actual server thread, or at least minimally impact it.

I'm not for having passwordless players based on some random client-provided flag. That is a security nightmare, and sounds like it could possibly make for a really easy way to make trouble.

I think this is also partially an AB problem. You're saying you want this "fix", but in reality you want a client to handle password management for you so this problem wouldn't even exist to begin with.

Personally, I don't think spectators should be this anonymous. I wouldn't use this feature on my server or recommend it to any server. But about the only reason to do this for me at this moment would be because "something else interesting might come out of it later".

**Comment by Fixer-007** [comment]
There is also comes the problem of cheaters, aka spectating to observe others and their holdings to use against them.

**Comment by jastevenson303** [comment]
I imagine like most things it would be managed (privs) and specific to
subgames and servers.

**Comment by Ferk** [comment]
If you want to do server-hoping without makign a new password every time, just use the same username/password and as soon as you decide to stay in the server for longer, change your account credentials to something safe.

**Comment by MuhdNurHidayat** [comment]
^ but you need to change IP when using new account in case the server you decide to stay in actually checks IP and only allow 1 account per player (those server would know if multiple players playing on same IP or it's the same player, by checking the actions being done by the accounts ingame...)

**Comment by paramat** [comment]
Unpopular with server owners and 2+ dev disapprovals.
