### ISSUE TITLE
Quick biome name retrieval

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest#7105]
##### Issue type
 - Feature request
 
##### Summary
The newly merged `minetest.get_biome_data` is great. With it came the function to retrieve biome ID from its name, `minetest.get_biome_id(biome_name)`.

As discussed in #6455, I hereby propose a new API function for doing the _opposite_ lookup: **retrieve biome name from its ID.** For the same result to be accomplished currently, one has to write a biome ID lookup of all registered biomes, then some table matching with current biome ID and so on. I find that a bit tedious.

The function could be described as something like this:
```
* `minetest.get_biome_name(biome_id)`
    * Returns the biome name for a given biome_id string.

**Comment by tenplus1** [comment]
or we could do:   local id, name = minetest.get_biome_data() to add the name to a 2nd value, or just return the actual name of the biome with the returning table.

**Comment by paramat** [comment]
As discussed it's better to keep this new API separate for performance reasons.

I support this request and will probably code it, however please still state support.

**Comment by pilino1234** [comment]
> it's better to keep this new API separate for performance reasons.

How performant and performance critical is the `get_biome_data` call? 
Is it actually necessary to force mods that want to get the biome name into using another subsequent API call to get the biome name?
Intuitively, the biome name should be a part of the returned biome data.

**Comment by paramat** [comment]
Yes initially it seems more intuitive, and i did consider it, however ...

It's more flexible to have 2 separate APIs. Most of the time a modder will know the IDs they are workng with so don't need 'get biome data' to also return name as well as ID, that's redundant information and would be bad coding practice.
'get biome data' was originally only going to return biome ID, but i realised that the heat and humidity values were laready calculated and could be returned for free, so did that. 

The rest of the biome APIs all use biome IDs instead of biome names, that's because an integer is faster and more convenient to process than strings, this is another reason why 'get biome data' returns IDs, for code consistency.
The performance difference may be small for one iteration but you never know when a mod will be using the APIs rapidly, so simplifying and optimising performance even by small amounts is still important.

**Comment by pilino1234** [comment]
Alright, fair enough.

**Comment by paramat** [comment]
PR #7117

**Comment by paramat** [comment]
#7117 merged.

**Comment by tacotexmex** [comment]
Good work. Thank you!
