### ISSUE TITLE
(sub)game CSMs

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest#7151]
##### Issue type
 - Feature request

##### Summary
I'd like to be able to distribute client-side mods with a game.
```
game
├───clientmods
    ├── modname
    |   ├── depends.txt
    |   ├── init.lua
    └── another

**Comment by rubenwardy** [comment]
#7056 #7043

**Comment by tacotexmex** [comment]
Regardless of exact structure and regardless of the status of #7056 and #7043 I'd like to be able to _distribute_ CSMs with the game. That is not the same as _sending_.

**Comment by Ferk** [comment]
@tacotexmex games are server side, even if your game is intended to be singleplayer. Even if some workaround was made to somehow use the client mods in singleplayer, if it's ever used multiplayer things might look broken.

The way Minetest is designed, singleplayer and multiplayer are tightly related. You need to have sending of client-side scripts in order to have them be part of a game cleanly.

Still, in the meantime, until #7056 and #7043 are implemented, if you only want singleplayer nothing is stopping you from distributing client mods in a zip with a game and ask people to uncompress the whole thing in the minetest folder so it'll copy both game and clientmods. You just won't have the association clientmod-game because that's only possible when the clientmod sending is done.

**Comment by tacotexmex** [comment]
Fair enough. Thank you for a the detailed response.
