### ISSUE TITLE
Define dungeon wall nodes in biome def

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7183]
Inspired by #7181 where the intention is to integrate all mapgen aspects into the Biome API, once large (pseudorandom) caves are done dungeons are left. They are currently messy and hardcoded to be certain nodes if stone, desert stone or sandstone are detected, otherwise the walls are set to the biome 'node_stone'.
There is or was a TODO in the code to make wall nodes dynamic.

I suggest we add 2 fields to biome definitions: 'dungeon wall', 'dungeon alt wall', if missing the fallback will be 'node_stone', which is the current fallback.

A task for myself.

**Comment by paramat** [comment]
This will mean some subgames and mods will have to update their biome definitions to keep their dungeon materials strictly identical, but i think a little breakage here is worth it because the 'MG_STONE' stuff is such a mess and 0.5.0 is a good chance to sort it out.

**Comment by AlexYst** [comment]
Some sort of dungeon "size" or "shape" parameter should be added as well, to allow both the type of dungeon with one-metre-wide halls and smaller rooms, like the current mossy dungeons, and the type with the two-metre-wide halls, larger rooms, and diagonal halls, like the current sandstone and desert stone dungeons.

I actually ran into this hard-coded dungeon issue when I was trying to build a subgame, though I cancelled that subgame for unrelated reasons. It's great to see fixing this is on the to-do list.

**Comment by paramat** [comment]
PR #7218 

More control over dungeons has been intended for a while, our previous mapgen dev was about to add them but then left MT. I'm unsure of the best way to have control over all dungeon parameters, and some implementations are beyond my own coding ability.
Biome definitions only apply to nodes used, not shape etc.

**Comment by AlexYst** [comment]
That's too bad about the shapes.

Having the nodes definable per-biome will be a *huge* improvement. I previously found myself having to define `mapgen_sandstone` as a non-sandstone node just to let me use a second dungeon type elsewhere in the world, and desert dungeons weren't manipulatable at all, as the place-in node and the wall node are one and the same.

This should add a lot of variance to worlds, too. Each biome can have dungeons built from materials found in the world around them instead of there being only three dungeon types, with most biomes having mossy dungeons.

**Comment by paramat** [comment]
#7218 merged.

Mapgens can be edited to be able to set dungeon parameters, for example y_min and y_max are now set in mapgens, however it seems wrong to add all dungeon parameters to mapgen-specific parameters, it feels like they should be set elsewhere.
But maybe a few more dungeon parameters will appear as mapgen parameters.
