### ISSUE TITLE
Placing/removing infinite blocks is possible if disconnected

### ISSUE THREAD

**Issue by stas730** [minetest/minetest#7207]
##### Issue type

 - Bug report
 
##### Minetest version

```
32d456bd2d4dda50f77c01c702d1b5a5ff26134b
```

##### OS / Hardware

Operating system:
CPU:
N/A

GPU model: N/A
OpenGL version: N/A

##### Summary

It’s possible to place infinity blocks if player is disconnected from server (or there is lag). It’s also possible to remove protected blocks (IIUC, there is no way to fix it using mods).
##### Steps to reproduce

0. Add one block in required player inventory
1. Disconnect from the server or set bad lag
2. Place this block more than one time

**Comment by paramat** [comment]
What do you mean by 'infinity blocks'?

**Comment by paramat** [comment]
I guess you mean you can place a node an infinite number of times despite only having 1 in inventory?

**Comment by stas730** [comment]
@paramat, yes.

**Comment by sfan5** [comment]
These changes are not permanent and client-side only.

**Comment by stas730** [comment]
Why not check it server‐side?

**Comment by sfan5** [comment]
It is checked server-side.

**Comment by stas730** [comment]
Why is this bug happening?

**Comment by GreenXenith** [comment]
> Disconnect from the server

> Place this block more than one time

Do tell how I can place a block while not connected to a server :]

**Comment by stas730** [comment]
@paramat, player can jump on these nodes for example (cheating).

**Comment by paramat** [comment]
Good point, i guess that comes under cheats possible due to lag, like lagging through protected walls etc.

**Comment by SmallJoker** [comment]
We can't fix this issue:
* Removing prediction results in jittery and delayed gameplay
* Modified clients can simply not send these node placement packets if they don't want
* Hacks and movement cheats are already known for a long time and on the todo list for our anticheat mechanism (see #6219)

**Comment by HybridDog** [comment]
@SmallJoker I think this issue is misunderstood.
The issue is not only about cheating but more generally about the possibility to add and remove nodes when the server is not receiving the changes.

> Removing prediction results in jittery and delayed gameplay

It is possible to visually tag the client-side-only placed node by adding a semi-transparent [loading icon](https://thumb1.shutterstock.com/display_pic_with_logo/169276916/557851660/stock-vector-set-loading-icons-load-load-icons-white-background-loading-vector-icon-557851660.jpg) onto its texture after a specific time, e.g. 0.1 s. Then the client can see the problem about the placement not reaching the server.

> Modified clients can simply not send these node placement packets if they don't want
> Hacks and movement cheats are already known for a long time and on the todo list for our anticheat mechanism (see #6219)

As already mentioned, this issue is not really about cheating possibilities.

**Comment by SmallJoker** [comment]
@HybridDog I interpreted this issue different. Removing and placing nodes using the prediction makes it possible for players to hop over or through walls. A feature like applying `^[brighten` (or similar) to the texture to mark them is clearly a feature request to give a feedback to players.
However, the client automatically disconnects when the server doesn't respond

It is not possibhen there's a massive server lag due to schematic loading or clearing objects. 
The player is disconnected automatically from the server after a while. Assuming that the player lost the connection to the server when the nodes aren't applied server-side yet Such a feedback can be added to the client but this issue is about predition only.

**Comment by SmallJoker** [comment]
@HybridDog I interpreted this issue different: Removing and placing nodes using the prediction makes it possible for players to hop over or through walls.
A feature like applying `^[brighten` (or similar) to the texture to mark them is clearly a feature request to give a feedback to players. Your idea does not solve the problems with node placement and dig prediction, but gives the player a feedback whether the server is still active.
