### ISSUE TITLE
New 1-texture cube drawtype to increase performance

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7268]
See #6929 and #7233 for discussion.
Related to #7222 

It seems likely that due to poor tilespec performance the number of textures a drawtype uses effects meshgen performance.
Most nodes in a world are stone, sand or dirt which are all using a 6-texture drawtype when they only need 1 texture. I suggest a new cube drawtype that only accepts 1 texture to hopefully increase meshgen performance.
It would need to be profiled to find out, even if it doesn't help it will be a useful test. I might code this to test for any improvement.

Related to this, it may be a good idea to keep the 1-texture allfaces and glasslike drawtypes even if 6-texture versions are added by #7233 especially due to the very heavy use of alface-optional in forests.
@numberZero

**Comment by numberZero** [comment]
For solid (and liquid) nodes, that doesn’t matter AFAIK, due to the way FastFaces work.
For any drawtype, that may be done as an implementation detail—runtime conversion, similar to the way `_optional` drawtypes work. That’s simple to implement, but such things make the code less readable, so:

1. testing is necessary to make sure performance difference is significant,
2. there might be better solutions that need to be considered (maybe https://github.com/minetest/minetest/issues/6929#issuecomment-383417303).

**Comment by paramat** [comment]
@numberZero i started a branch https://github.com/paramat/minetest/tree/onetex and apparently 'normal drawtype' is "Drawn by MapBlockMesh" but oddly i can't find where.
Is it better to draw it using a new function in content_mapblock.cpp instead?

**Comment by numberZero** [comment]
> Is there actually any way that a normal cube can be faster by using less textures?

No AFAIK. For other drawtypes, that may be possible, though. But I think, the core problem should be fixed instead.
