### ISSUE TITLE
Dungeon sizes depend on the chunksize setting

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#7270]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 0.5.0-dev (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=None
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"

```

##### OS / Hardware

Operating system: lubuntu
CPU: intel

##### Summary
If you increase chunksize, the dungeons are bigger.
Note that I noticed this a long time ago, but I assume the problem is still there because I didn't find an issue or PR about this problem.

##### Steps to reproduce

https://github.com/minetest/minetest/blob/12a8f8826d54362d70aae8524aa88118f2d84692/minetest.conf.example#L2789-L2791
Generate dungeons with different chunksize setting values

**Comment by paramat** [comment]
Not a bug, it's how dungeons generate. The corridors change direction if they hit the voxelmanip edge. If the volume is larger they don't need to change direction so are more spread out (but withthe same number of rooms). Many aspects of mapgen and terrain change by changing mapchunk size, it's an extreme change. Hmmmm once wrote he wished he had not made it configurable because it has such an effect.

**Comment by HybridDog** [comment]
https://github.com/minetest/minetest/blob/bb3baef30f8afcfec046050b1ef3b606a2c1248a/minetest.conf.example#L2789-L2791
