### ISSUE TITLE
Optional river depth variation for Valleys mapgen

### ISSUE THREAD

**Issue by Ezhh** [minetest/minetest#7274]
##### Issue type
 - Feature request

##### Summary
Valleys mapgen currently has rivers that "run dry" in the least humid biomes. Though it's a nice concept, I've found it can create some quite ugly results and would like an option to disable this and have consistent depth rivers in all biomes.

An example:
![mtg_broken_rivers](https://user-images.githubusercontent.com/7035183/39160051-117bea5a-4761-11e8-9470-2299bb36581b.png)
As you can see, you can end up just getting occasional single water nodes instead of a real river, and it can start to look messy.

**Comment by paramat** [comment]
This should probably have been an option from the start. The mapgen already has an option that increases humidity around a river, which tends to create oasis biomes around a river in a desert, so it makes sense to allow a full river in that situation.

I'll also try to fix those water blobs when dry rivers are enabled.

**Comment by paramat** [comment]
It gets worse, now i discover that you only get dry rivers if 'humid rivers' is enabled, makes sense =/

**Comment by paramat** [comment]
PR #7277

**Comment by paramat** [comment]
The mgvalleys settings bug is fixed so this is now possible. However the logic and interaction of shallow rivers, humid rivers and altitude chill is weird, irritating and makes little sense, i don't feel like adding to this mess by adding another option.

**Comment by paramat** [comment]
It is fairly low priority independent of how i feel about it, but borderline so i don't mind removing the label. Variable river depth can be adjusted, the code is understandable, the logic is just weird and messy (like many other aspects of this mapgen).

We made a mistake by merging this mapgen in the form it was in, i'm mostly to blame. My attitude was: "i can't get my head around it, it's messy and complex, but will leave it to duane to maintain", however duane hasn't got the skills to maintain a mapgen and has pretty much disappeared, and of course i end up having to maintain it =)
Hmmmm was right in disliking the code. Luckily i approached mgcarpathian correctly and it is very well coded. From now on we're going to be more strict about adding mapgens as they are a huge commitment.

I've cleaned mgvalleys up recently but how the mapgen generates 3D terrain is still bizarre. The way it alters the biomemap according to altitude is popular but a nightmare to maintain. I would love to remove that feature but that would be unpopular.

Concerning this request, your issue is the blobs, not an option for river depth variation, it seems i can't fix the blobs and they aren't a problem, they just visually irritate some people. I'd like to see more support for this option before i code it. I need more reason to add to this mess =)

**Comment by paramat** [comment]
Rethinking this, variable depth rivers should be an option as they are a speciality feature like 'altitude chill' and 'humid rivers'. The mapgen should be configurable to result in the usual constant river depth everywhere. Will recode this.

**Comment by paramat** [comment]
Actually, it turns out that variable river depth is already optional, it only happens when 'humid rivers' are enabled. I don't know why i didn't discuss this earlier. It may still be best to separate this out into a new option, not sure.

**Comment by paramat** [comment]
Yes i'll do this. The diff already exists and has already been approved so quite easy.

**Comment by paramat** [comment]
PR #7532

**Comment by Ezhh** [comment]
Perfect - thank you. :)
