### ISSUE TITLE
Possible (massive) ABM performance impact reduction

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#7280]
Currently, ABM code causes all active mapblocks and all nodes within them to get scanned to see if an ABM needs to be triggered for that node. This happens every interval of the ABM, without any sort of prediction.

This is the number ONE CPU utilization problem in minetest. You can't uncover this by using mod profiling, since the penalty happens in core. The Lua side of ABM's is not the problem.

in `src/serverenvironment.cpp` we can see this happen entirely. For each node in an active node, the mapnode is checked and the abm is called if it matches.

We can do predictive avoidance here:

- If no ABM's were called because the node(s) isn't (aren't) present in it, and the mapblock didn't change, there is no need to run the ABM again on the next run
- Should be done likely per ABM to have fine grained control

I lack the time and the C++ skill to do this efficiently, but I checked the code and I think it's feasible. It may mean that the loop nesting has to be changed to make it more effective (loop over abm's first, then over each block and blockpos within blocks second).

The benefit would be significant, for sure. Most ABM's avoid touching 90+% of the mapblocks entirely, if not more. All that would be recovered at the cost of a very trivial cache (std::vector or something like it).

**Comment by sorcerykid** [comment]
It just so happens that last week I began work on a new implementation of ABMs for my fork of the engine, with design goals similar to those mentioned above while incorporating some of my earlier suggestions:

https://github.com/minetest/minetest_game/issues/1561#issuecomment-279845218
https://github.com/minetest/minetest/issues/5303#issuecomment-282772354

The project actually began as proof of concept in January while attempting to optimize my snowfall mod. The performance gains (even in a purely Lua implementation), however, were phenomenal. By using pre-cached hash tables for node lookups, I was able to efficiently set tens of thousands of nodes with significantly less overhead than a purely ABM-based approach (benchmarks can be provided).

I was planning to post a synopsis of the project in the forums (probably under on the "Partly official engine development") along with a roadmap once I have time to document all of the changes I've made. It's still a WIP and there's a lot of work yet to do, hence why it hasn't been deployed on my own server. But so far I've successfully refactored the ABMHandler class, with improvements to the neighborhood search algorithm and timer mechanism. The scripting API is overhauled as well, allowing for callbacks to be issued on a per-mapblock basis (rather than per node) further reducing the bottleneck of hundreds of context switches between CPP and Lua every cycle.  The next step is to incorporate the lookup tables.

**Comment by sofar** [comment]
Love to see code, other improvement are also welcome - just make a PR, I'd say. Or, based on your description, 3 or 4 different PRs?

**Comment by sorcerykid** [comment]
I don't know anything about how to do PRs, but I will still share my code nonetheless once I have time.

**Comment by Fixer-007** [comment]
This may help you getting started https://github.com/minetest/minetest/blob/master/CONTRIBUTING.md#code (You can also edit and save code on github page itself)

**Comment by raymoo** [comment]
By the way, an ABM with a failed neighbor check could also be deactivated, as long as you reactivate it if a neighboring mapblock changes. This could potentially have good savings if there is an ABM on a common node with a neighbor check for an uncommon node.

**Comment by nerzhul** [comment]
@lhofhansl the only drawback is a higher memory usage

**Comment by lhofhansl** [comment]
@nerzhul just 400-500 bytes per block. So even with 5000 blocks cached it's < 2.5MB. Could also just cache 10 different types, or just one.

**Comment by lhofhansl** [comment]
Edit: Freeminer stores the single type if all nodes in a block are the same.
The mast majority of the block have 10 or less different node types.

**Comment by lhofhansl** [comment]
I'll post a PR for commenting, will mark as "Discussion"

**Comment by paramat** [comment]
#7555 merged.

**Comment by tacotexmex** [comment]
So was the performance increase massive or not? :)

**Comment by paramat** [comment]
The impact reduction is big when the cache is in effect, but the cache is invalidated whenever a mapblock is changed (by player, machine, code, ABM etc., so quite often), and the cache is recreated (and the ABM runs as before) whenever a mapblock is unloaded from the server. So the impact reduction can vary a lot depending on the situation.

So importantly, this is not an excuse to increase ABM usage, and it is still a very good idea to reduce usage of ABMs. Unfortunately some people have misunderstood the optimisation and are using it as an argument to not worry about ABMs.
