### ISSUE TITLE
Substrings in client-side translations

### ISSUE THREAD

**Issue by MineWitherMC** [minetest/minetest#7291]
##### Issue type
 - Feature request

##### Summary
It would be nice to be able to find a substring in `minetest.translate(domain, something)`. Use case: for example, an advanced inventory allowing search through descriptions and not only IDs.
Or at least add functions to get client-side translations as Lua tables (too many files to look for, and they're dynamically named, so probably impossible to do on pure Lua for now).

**Comment by Wuzzy2** [comment]
I don't quite understand. Is this really not possible with current functions yet?

What about `string.find`?

**Comment by MineWitherMC** [comment]
For example, a user, who is Russian, searches `слиток` in some inventory. Of course, it won't be found in string like `\x1b \x1b(@materials) Iron F Ingot F`, which is properly translated to the `Слиток железа` on client, that is the problem.

**Comment by Baigle** [comment]
It would be nice to have the string.lower functionality on the game. I would use it for wordlist matching for use in moderation and assistance CSMs, but I ran into this issue where its only registered in the android build of Irrlicht [to my knowledge](https://github.com/search?q=org%3Aminetest+string.lower&type=code).

Something that removes excessively repeated whitespaces and fixes non-keyboard-native characters would also help, in cases where servers have bridged IRC, Discord, Matrix, and Telegram channels. I think that Valve has used Steam IDs for this reason so that players can still be moderated with customized and 'alt-coded' name strings.

**Comment by rubenwardy** [comment]
Closed as this has already been implemented as server-side translations

**Comment by rubenwardy** [comment]
> It would be nice to have the string.lower functionality on the game. I would use it for wordlist matching for use in moderation and assistance CSMs, but I ran into this issue where its only registered in the android build of Irrlicht [to my knowledge](https://github.com/search?q=org%3Aminetest+string.lower&type=code).

Lua already has a string.lower() function

> Something that removes excessively repeated whitespaces and fixes non-keyboard-native characters would also help, in cases where servers have bridged IRC, Discord, Matrix, and Telegram channels. I think that Valve has used Steam IDs for this reason so that players can still be moderated with customized and 'alt-coded' name strings.

You can use gsub for this
