### ISSUE TITLE
Trains and minecarts get repositioned to a position they've already been before (anticheat related?)

### ISSUE THREAD

**Issue by Fulgen301** [minetest/minetest#7292]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 0.4.16 (Linux)
Using Irrlicht 1.8.4
Build info: VER=0.4.16 BUILD_TYPE=Release RUN_IN_PLACE=0 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="/usr/share/minetest"
```

##### OS / Hardware

Operating system: Arch Linux x86_64
CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz, codename: Skylake (Core m5)

##### Summary
Enabled anticheat feature causes minecarts (and e.g. trains from the advtrains mod) to get repositioned on a track they've already driven through, effectively repositioning them back to a position they've already been before.
Possible fix (working for me): Add `disable_anticheat = true` to `minetest.conf`

##### Steps to reproduce
- create a new map
- place minecart tracks
- place a minecart on the tracks and see how it sometimes gets repositioned

**Comment by paramat** [comment]
I assume that anticheat does not take into account the speed of a vehicle, so this seems somewhat of a feature request for that. Perhaps an API that tells anticheat code that 'this player is now using a vehicle with speed x'?

**Comment by SmallJoker** [comment]
Just to mention some facts here:

1) Anticheat is not applied to players which are attached to an entity which is logical because players can't move in this situation. The movement anticheat check is also disabled in singleplayer mode as visible in the code below. To confirm this is not the issue, set the log level to "action" or more detailed, attach to a vehicle and look out for log entries containing "resetting position".
https://github.com/minetest/minetest/blob/24b6bd0f679f3cc5ff07bb5eb5ee787c20d3a5e8/src/content_sao.cpp#L1441-L1445

2) The client prediction might also get out of sync with what actually happens server-side, thus reports a faster movement / more distant position than it actually is. After the next `set_pos` call in these mods, this will be corrected and causes some of this repositioning effect.
https://github.com/minetest/minetest/blob/24b6bd0f679f3cc5ff07bb5eb5ee787c20d3a5e8/src/content_cao.cpp#L877-L882

Whilst this is an issue I've already noticed I don't/can't believe it is related to anticheat. More likely the server gets out of sync due bad time calculations or due some kind of step duration limit.

**Comment by orwell96** [comment]
Regarding advtrains, please note that even if the wagon entity gets repositioned by some sort of anticheat, this does not affect the actual position and movement of the train (unlike carts).
This means, the train will never be actually repositioned back, only the wagon entity is. This is because thr train movement is handled completely independent from minetest's entity movement code.
At least 2 seconds after such a repositioning, the wagon entity will be at the right position again.

However, I doubt that anticheat has any effect on this. Anticheat applies only to players, not to entities, and when riding carts or trains the player is attached to the entity, which means he moves along with this entity no matter what happens around.
A common effect is indeed that client and server get out-of-sync (even on a local game, they are separated), and that the client resets the entity's position to where the server says the entity is.

**Comment by SmallJoker** [comment]
Could it be that advtrains collide with objects? If so: #7570
The laggy carts can be explained by that the server was a bit busy, the cart drove too far and teleported back because the railway pathfinder did not exist in 0.4.16 yet.

**Comment by rubenwardy** [comment]
*bump* this makes advtrains very glitchy on servers

**Comment by sfan5** [comment]
Does this still happen in 5.4.0?

**Comment by Fulgen301** [comment]
I have yet to test it in 5.4.0, but it still happens in 5.3.0.

**Comment by SmallJoker** [comment]
No reports since the last request. Please (ask to) re-open this issue if the problem persists.
