### ISSUE TITLE
Craftrecipe tool wear

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#7294]
Adding recipes that use tools is a good way to say chop melon with a sword but it doesn't change the wear of a tool while crafting...  Would it be possible to add a feature to replacements = {} that adds a wear level to the end:
```
minetest.register_craft({
	type = "shapeless",
	output = "farming:melon_slice 9",
	recipe = {"group:food_melon", "farming:knife"},
	replacements = { {"farming:knife", "farming:knife", 100} } -- take 100 from wear level
})

**Comment by Ferk** [comment]
The replacements are itemstrings, is the wear preserved at all?

Looking at the code I expect that currently any tool that is replaced in that way not only would not add wear but if it had any wear it would actually be insta-repaired to 100%, since there's no wear in the itemstring of the replacement ("farming:knife" is equivalent to writing "farming:knife 1 0", which means 1 knife with zero wear and no metadata).

https://github.com/minetest/minetest/blob/0ca121149c3f62809e8ddb56d76c87a6ddcbd708/src/craftdef.cpp#L208-L221

**Comment by NathanSalapat** [comment]
Wear is not preserved on tools when using them in recipes as replacements.
