### ISSUE TITLE
Allow multiple different nodes to occupy the same physical space

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [minetest/minetest#7301]
It would be nice to implement a multipart system. Fortunately, this has been done before in an open source fashion. Unfortunately, It was done in Java and Scala for Minecraft, but the general translated code should still work. 
https://github.com/Chicken-Bones/ForgeMultipart
It will take some work, but I think it will be worth it in the end.

Here is the mod in action: https://www.youtube.com/watch?v=u9yUr4jmU6s
I think this would work best implemented in core, as I think it should be relatively low level.

**Comment by rubenwardy** [comment]
What do you mean by a multipart system?

**Comment by Fixer-007** [comment]
Like with chisel and bits mod?

**Comment by EmergencyTemporalShift** [comment]
More like this: https://www.youtube.com/watch?v=u9yUr4jmU6s as that is the actual mod I linked to.

**Comment by EmergencyTemporalShift** [comment]
I'm going to try to get Chicken-Bones (Creator of the mod shown) to help (By giving him a monetary incentive from my wallet). He already has some open source projects in C++, so it might work.

**Comment by paramat** [comment]
I'm sure there is a duplicate issue somewhere.

**Comment by Chicken-Bones** [comment]
Nice project you have here. Unfortunately I won't be able to assist as I have no free time at the moment, and porting would require a complete code redesign. It'd probably be more work for me to understand the minetest codebase and modding context, than for a minetest dev to understand ForgeMultipart's. Additionally, some of the implementation details of ForgeMultipart are very closely tied to the state of the modding community at the time it was written (dynamic class generation). 

I'm sure you could glean a lot from the class hierarchy and roles of ForgeMultipart, and I'd be happy to discuss my design decisions and the way the mod works as a whole with an interested developer.

**Comment by Sires0** [comment]
@paramat Maybe you mean #3376
@EmergencyTemporalShift Well I have near no experience at the engine coding but from the experience I have with Minetest I can say that there would be lot's of problems:
1º Devs may disagree your idea, as you can see in 3376
2º You would have to recode most part of the engine to work in such a way, unless you use the 3376 idea, that is simply reducing the size of the nodes
3º Even if you use the 3376 idea, you'd have a **TON** of backwards-compability problems since the whole world would be shrinked by a factor of 8x or 16x
3.5º You'd have to bigger the world size 8 or 16 times, and it would consume waaaaay more storage

These are some of the problems I could think for now, but the number 2 would be the biggest one.

Making such a thing would be very hard, and I *partially* agree with paramat's comment on 3376, that would have to be another game, but in my opinion not because of the "ideaofthegame©" change, but because of the gigantic change

**Comment by paramat** [comment]
It depends on how ForgeMultipart actually works or how it would work in MT, some one needs to explain or link to an explanation. If it is indeed a big task then i am :-1: 
Will close in a month if no clarification.

**Comment by SmallJoker** [comment]
The idea is great but I imagine that the work to implement this feature is quite high. Implementation ideas and PRs to implement this feature efficiently are surely welcome.
We also had other suggestions but nobody who has the time or knowledge to implement it - so this one could probably be yet another of them.

**Comment by paramat** [comment]
I still don't think that label is worded correctly and would not be right for this. If the suggestion is too complex to be worth doing then PRs will not be accepted and it would be wrong to encourage that.
Please can it be reworded?

**Comment by Chicken-Bones** [comment]
Forgemultipart's implementation is anchored to the following parts of Minecraft
* Blocks can store arbitrary data in a corresponding TileEntity class
* Blocks can render themselves arbitrarily, suppling vertex/texture/lighting data when building the render buffers, using the corresponding TileEntity to generate geometry
* TileEntities can respond to various events as the world changes around them, or a player interacts with them, and update globally with the world

ForgeMultipart operates by storing Parts in a TileEntity, and passing all the events, render and io calls to all parts that are contained within the host block in an ordered and compatible manner

**Comment by paramat** [comment]
Thanks, in MT the arbitrary data would be 'metadata', so this would mean the mesh rendering of the multiple node would depend on reading quite complex metadata first, which is the problem behind #7278 
Due to that i am :-1:

**Comment by Chicken-Bones** [comment]
"These two PRs aimed for making everything changeable with meta data" from my scanning through that thread. Metadata everything is definitely a prerequisite.

Minecraft uses a HashMap per Chunk to access TileEntities but depending on how much RAM a user has available, an array could be used for faster access. Of course you'll still have cache misses due to TileEntities being randomly allocated throughout the heap

**Comment by EmergencyTemporalShift** [comment]
Well, I hope I at least generated a meaningful discussion.

**Comment by EmergencyTemporalShift** [comment]
Alright, the discussion seems to be over.
