### ISSUE TITLE
Add Lua API for procedural/runtime mesh generation and entity creation

### ISSUE THREAD

**Issue by jmdevy** [minetest/minetest#7314]
I was wondering how hard it would be to add support for an LUA API that can make meshes at runtime. Say for example I make a boat out of nodes, then make a mod to get positions of all those nodes and the figure out the vertices, normals, indices, (UV coordinates?) and then make it into a mesh using an LUA API function that takes the above requirements as inputs and returns/inits a mesh. This way the mesh could be created and an entity could also be made and put into the world (steer the boat?)

There could even be a function that generates the things I mentioned using whatever algorithm the Minetest engine uses (marching cubes?), to make the mesh terrain, and returns the components or the mesh itself.

I can see this being resource intensive, sure, and it would all have to be sent over the network. Although, since this is at runtime then I don't _think_ it would be necessary for something like minetest.register_entity() (is it possible to call that after a world/server has started?)  to be called however I'm not sure at all.

I'm just curious, I may even work on this myself if I ever have the time to learn how the Minetest engine works (I've worked with procedural meshes in Irrlicht already).

If this is better suited for the forums please take this down, I just wanted core dev input.

Thanks for your time!

**Comment by SmallJoker** [comment]
Either on the forums or in the depths of the issue tracker, there's also a request for node structures which are movable and stored differently in the database. However, this is now surely over three years ago and I can't seem to find any issue or forum topic - probably I'm using the wrong keywords.

This idea still sounds great but is very hard to implement because it needs
1) a faster/more efficient collision detection
2) a working attachment system - there are still situations where new joined players don't see some attachments
3) a storage for the attachments or the structure data to restore it on the next join
4) an API to link or add nodes to the structure
5) a full-time job for Minetest to implement all of this

However, you might have a simpler method in mind which works differently and faster. Feel free to implement it as soon you've understood the mechanics of Minetest - PRs are always welcome.

**Comment by rubenwardy** [comment]
@SmallJoker do you support this feature?

**Comment by rubenwardy** [comment]
This is possible with dynamic media now and a library to parse/edit meshes (like in modlib)
