### ISSUE TITLE
max_hear_distance continues to play sound way beyond the distance

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#7322]
##### Issue type

 - Bug report
##### Minetest version
```
0.4.16
```

##### OS / Hardware
Operating system: GNU/Linux

##### Summary
If you use `minetest.sound_play` to play a positional sound, you continue to hear the sound way beyond the `max_hear_distance`, although very, very quiet. It's very quiet, hard to hear, but it never goes completely away.

##### Steps to reproduce
```
minetest.sound_play("long_example_music", {
pos = pos,
max_hear_distance = 65,
gain = 1,
}) 
```
Then just move away from the sound source.
Use headphones.
You still hear the sound way beyond the distance, although very quiet.
If you teleport, thausands of node away, the sound is still not completely silenced.

**Comment by paramat** [comment]
I have worked on sound so will look into this.

**Comment by paramat** [comment]
This is expected, the confusion comes from the meaning of `max_hear_distance`. The new docs are:
"A positional sound will only be heard by players that are within
`max_hear_distance` of the sound position, at the start of the sound."
The parameter does not mean the maximum distance the sound can be heard.

After being within `max_hear_distance` at the start of the sound, a player will continue to hear that sound if they move beyond that distance according to the sound attentuation behaviour which never reaches zero gain. This is fine because the attenuation continues to act suitably.

**Comment by Wuzzy2** [comment]
Wait, what? How is this intended behavior? So if the sound is a lengthy music track played by a jukebox, it's impossible to walk far away enough to make the sound stop? :-(

**Comment by jastevenson303** [comment]
ye the whole minetest sound experience is quite messy.

**Comment by paramat** [comment]
I looked at the OpenAL docs, it doesn't support sound culling, it leaves that up to MT to do.
The Lua mod could check occasionally and stop the sound, or we could add a max distance check to the engine.
