### ISSUE TITLE
Add L-system trees as decorations

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#7346]
##### Issue type
 - Feature request

##### Summary
I suggest to make it possible to generate L-system trees as map decorations.

They start to “grow” at the coordinate chosend for the tree. The `seed` they use will be of course the map seed.

I believe this will open the door to very interesting mapgens and a lot of variety, if used correctly.

**Comment by paramat** [comment]
Yes this has actually been intended for a long time, there is even a 'l-system' deco type named in preparation. I don't currently know how to code this.
Related to #2151

**Comment by TMcSquared** [comment]
I know L-Systems pretty well....but I don't know how to translate them into voxels

**Comment by Wuzzy2** [comment]
I just realized this is actually possible now, indirectly, but it seems to work.

You can create a dummy decoration (e.g. an empty schematic which changes no nodes) and then use `gennotify` to manually spawn L-system trees at the positions you get out of the `gennotify`.

**Comment by paramat** [comment]
That's very bad, as L-system tree generation currently runs an intensive lighting update per-tree, so any dense or rapid use causes problems.
As requested in  #2151 L-system generation needs to be separated from it's lighting update so that it can be applied to a LVM.
L-system generation should never be used during mapgen (take note moretrees mod), only occasionally afterwards.
