### ISSUE TITLE
Expose broken node pos to after_use 

### ISSUE THREAD

**Issue by MineWitherMC** [minetest/minetest#7373]
##### Issue type
 - Feature request

##### Summary
I am trying to create a multi-node tool, which breaks for example 3x3 of nodes at a time. And, as in title, I need to get node pos to after_use in order to do that.

I'm not sure if there is other solution, if there is, please post it here.

on_use doesn't work as tool stops working with it, running its callback instead of breaking the node.

EDIT: Improved description.

**Comment by SmallJoker** [comment]
> (imagine almost any MC mod)

Sorry but that does not help me in any way to understand what you plan to do.
Since this part of the code is entirely implemented in Lua, it only requires to change this line
https://github.com/minetest/minetest/blob/8f827ee6800974ee451f0e82ac5eafdff63b835e/builtin/game/item.lua#L570
to
`wielded = wdef.after_use(wielded, digger, node, dp, pos) or wielded`
to add the position to the callback parameters. It's about the same change to do in the documentation.

**Comment by MineWitherMC** [comment]
That is exactly what I need.

**Comment by mtango688** [comment]
My version of hammers could use this, as I am using an ugly work-around at the moment.

https://github.com/mtango688/hammers

**Comment by 4w** [comment]
Big thumbs up for this :+1: Very useful for custom tools i.e. a tool that breaks a node and replaces that node with another node after breaking the node. Currently such a behavior needs to figuratively re-implement the whole tool mechanism in the tool’s `on_use` function ([or disgusting things like this](https://github.com/4w/cement/blob/0fc348279a505813ed42a7b16b3b0ec2cf7683d6/init.lua#L54-L76
)).

All mods adding own tools that are supposed to do something after the node was digged would benefit from having access to the just digged node’s position available in `after_use`.

**Comment by SmallJoker** [comment]
> Very useful for custom tools i.e. a tool that breaks a node and replaces that node with another node after breaking the node.

The issue with the code currently is that this won't be possible:
> How the code currently states that the node still exists when after_use is called - and will be removed afterwards regardless on the return value of after_use.

"return value" also includes any node which was placed at the same position. It would be removed afterwards. Changing this behaviour is however possible but requires testing whether the existing mods are still compatible since the "node" parameter will only be a copy of what used to be there.
The very same behaviour could also be implemented with the node callbacks `after_dig_node`, where additionally the wielded item would be given.

**Comment by mtango688** [comment]
I do eagerly await even small improvements.
