### ISSUE TITLE
core.run_callbacks is not documented.

### ISSUE THREAD

**Issue by red-001** [minetest/minetest#7520]
##### Issue type
 - Documentation Issue.
 
##### Minetest version
```
5.0.0-dev
```

##### Summary
`core.run_callbacks` doesn't appear to be documented anywhere not even as an internal function that mods should avoid interfering with.

**Comment by rubenwardy** [comment]
It's currently an internal function which is needed by the engine, hence why it's in the table. Could be documented though

**Comment by beyondlimits** [comment]
Yup, and it contains undocumented magic constants.

**Comment by SmallJoker** [comment]
> Yup, and it contains undocumented magic constants. Looks like decompiled code.

If you mean the numbers, they come from this enum:
https://github.com/minetest/minetest/blob/498078bfa09c19d42390161bc1b8b8c03b7b2956/src/script/common/c_internal.h#L75-L99

**Comment by SmallJoker** [comment]
I'd prefer to keep this function internal and undocumented. Whereas it might be helpful for modders, it is very tightly bound to the engine. Documenting it would allow modders to overwrite the function, resulting in less flexibility for structure changes or changes to this function.
After all, its logic is pretty simple. You'd be faster writing a `for` loop yourself rather than reading the documentation.
