### ISSUE TITLE
Lua_api.txt: Clarifying 'deprecated' note in entity definition table

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7590]
This documentation has always confused me: https://github.com/minetest/minetest/blob/d7d451c647f1fff7983178a9817888f4d0bab695/doc/lua_api.txt#L5283
Does it refer to 'initial properties' below? My guess is yes because the Lua entity table now directly contains all object properties.

Looking in code, this deprecation has been in place for 6 years since bdbdeab, since we are moving to 5.0.0 i think we can now remove the legacy code at:
https://github.com/minetest/minetest/blob/eef62c82a2e58700fc1216b0b8c03e421bc77995/src/script/cpp_api/s_entity.cpp#L190
Specifically:
https://github.com/minetest/minetest/blob/eef62c82a2e58700fc1216b0b8c03e421bc77995/src/script/cpp_api/s_entity.cpp#L194
It reads object poperties directly from the entity definition table, then afterwards attempts to read them from 'initial properties' if it exists.

Note that the 'deprecation' comment seems to be placed wrongly here, surely it should be referring to 'initial properties' as deprecated?

**Comment by paramat** [comment]
'Initial properties' is stil being used here:
https://github.com/minetest/minetest/blob/ade7a1cbcf7156ebddb12bd2ec2ea60818d72b19/builtin/game/item_entity.lua#L22
https://github.com/minetest/minetest/blob/ade7a1cbcf7156ebddb12bd2ec2ea60818d72b19/builtin/game/falling.lua#L10

**Comment by paramat** [comment]
My suggestion:
Remove legacy code that supports the use of 'initial properties'.
remove the deprecation comment from docs and clarify that the object properties listed above are to be added to the entity definition table.

**Comment by SmallJoker** [comment]
:-1: For three reasons:
1) There are 18 occurrences of `initial_properties` in 11 different mods inside my collection which would need updating due to that. I've got a total of ~100 mods, whereas modpacks are counted as one mod.
2) I believe the main idea was to deprecate the use of custom variables directly inside the entity definition. The term `initial_properties` also clarifies that these are applied on startup - as defaults, which means that they can still be changed afterwards.
3) Also a huge no, because we are going to break the network compatibility, but not the modding API. What you are talking about is a single code line (deprecated use of the direct definition).

https://github.com/minetest/minetest/blob/eef62c82a2e58700fc1216b0b8c03e421bc77995/src/script/cpp_api/s_entity.cpp#L189-L192
`initial_properties` is newer. dc70f50b

**Comment by pauloue** [comment]
I thought that comment meant `initial_properties` was deprecated but commit dc70f50 added both `initial_properties` and the deprecated note.

So what was actually deprecated was what came after the colon--reading object properties directly in the entity definition. That explains why the deprecated comment was added here:

https://github.com/minetest/minetest/blob/eef62c82a2e58700fc1216b0b8c03e421bc77995/src/script/cpp_api/s_entity.cpp#L190-L191

This means that either the boats mod and others should be changed to use `initial_properties` or reading object properties directly should be un-deprecated.

**Comment by paramat** [comment]
I see, ok i agree.

Lua_api.txt still needs clarifying.

**Comment by paramat** [comment]
PR #7596
