### ISSUE TITLE
Change walk controls and  darkness in Minetest 0.5.0-cca92537 for Android

### ISSUE THREAD

**Issue by DavidRotert** [minetest/minetest#7605]
# Feature request
I tried Minetest 0.5.0-cca92537 to see if a bug was fixed as I noticed some things which could be improved:
1. I would change the walk control back to arrows because it is easier to use.
2. The night should be brighter so you can see a little bit.

**Comment by MuhdNurHidayat** [comment]
The new joystick-like control in 0.5.0 (5.0.0) was one of the features wanted by the players or was made to perhaps attract more players since many complained that the arrow key control is bad. iirc. It was supposedly to improve the player experience.

See #7507 , #1750 , #7126 , #6731 for the discussions related to the new joystick based control

**Comment by DavidRotert** [comment]
Maybe you can make it available to change the joystick into arrows in the setting. This would make both parties (joystick and arrow fans) happy ; ). And the user has the chance to play the game if he can't operate joysticks very well.

**Comment by SmallJoker** [comment]
Please don't combine multiple suggestions into one issue (unless they depend on each other).

1) So users complained because the arrows were too hard to use and now there's the request to disable the new superior controls? I really don't get it. The joystick turns out to be easier to use because it combines the four buttons into one single finger control.

2) The night was always dark. The new light settings would however allow slightly more tweaking than before. If you found the perfect [setting values](https://github.com/minetest/minetest/blob/654f57333f8784cf2e45a700998cb67d8b4f118e/minetest.conf.example#L673-L697) to play Minetest, then it would be lovely if you could open a PR to change the defaults.

**Comment by DavidRotert** [comment]
Sorry, I only made this suggestion because I personally prefer arrows.

**Comment by DavidRotert** [comment]
I tested 0.5.0 again and now I can see that the night is not as dark as I thought. Sorry about wasting your time.
