### ISSUE TITLE
Animals

### ISSUE THREAD

**Issue by woshiicyrus** [minetest/minetest#7608]
##### Issue type
 - Feature request

 
##### Minetest version
-->
```
0.4.17.1
```

##### OS / Hardware

Operating system: Windows
CPU: Intel 

##### Summary
I realized there is no animals in minetest, i hope that there will be animals so that the game will feel more lively, such as herding.

**Comment by SmallJoker** [comment]
Wrong repository. See also: https://github.com/minetest/minetest_game/issues/515

**Comment by MuhdNurHidayat** [comment]
In general, animals and other mobs are added by installing mob mods.

Minetest engine is an engine, current engine issue is just about Engine API for Mobs at #2291 and I don't see any other issue. If you want to request feature for Minetest game (instead of the engine) then please do so over minetest/minetest_game, however issue of request for mobs was already made at minetest/minetest_game#1667

Even if there's no animals in default Minetest game yet, you can always add [mobs mod](https://wiki.minetest.net/Mods:Mobs "Mods:Mobs - Minetest Wiki") and any other [mods](https://wiki.minetest.net/Mods "Mods - Minetest Wiki") to enhance the gameplay. Though iirc they're adding butterflies in Minetest Game via minetest/minetest_game@0ea6065
