### ISSUE TITLE
Persistent peer_ids based on client device's configuration

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#7625]
##### Issue type

 - Feature request

##### Background
Players can get around IP bans by just using a different IP. And even if they can't, banning them would prevent their sibling from playing on the server.

##### Summary

This is a feature request for persistent peer IDs which are computed from the client device's configuration, like hardware, OS, path to MT executable, time of creation of executable, etc. These would be computed client-side and only the peer ID itself would be exposed to the server.

This would ensure that players connecting from the same device have the same peer ID, and will remain banned even if they change their IP. This would also ensure that their siblings and/or peers connecting via another device from the same IP can play unaffected. The banned players can still use another device, but that's tougher than having to just restarting their router.

This probably is a very bad idea, but I felt that it should be expressed nonetheless. Please bear with me :)

**Comment by MuhdNurHidayat** [comment]
Given the fact that almost everyone here gets dynamic IP by default no matter mobile data, DSL or fiber optic, and the fact that internet is expensive enough that it's common to share one subscription with 10 people no matter siblings or family members or friends, this might be good idea.

**Comment by SmallJoker** [comment]
Same thing as detecting hacked clients. You simply cannot expect that anything which the server receives is valid data. Additionally, I'm not even sure whether a non-reversible hash would be acceptable for privacy reasons.
Also keep in mind that dynamic IPs not necessary change by re-initializing the router.

**Comment by MuhdNurHidayat** [comment]
> Also keep in mind that dynamic IPs not necessary change by re-initializing the router.

This actually depends on the internet service provider you use, some of them do assign new dynamic IP each time the router is restarted/re-initialized.

The ADSL provider here (there's only one in my country) always assign new dynamic IP on router restart, and mobile networks assign new dynamic IP on each re-connection (either because the mobile data get restart or because the signal was temporarily loss)...

It do seems that fiber optic provider here only assign new dynamic IP on some occasion of router restart, not on every restart... while fiber optic is commonly used in some countries, it's still not widely used in the other countries... and at here, most people uses either ADSL or mobile data because fiber optic is only available in cities...

(I'm writing this on laptop using 4G mobile data WiFi tethering as I'm at hometown where the 1Mbps ADSL is too slow for me (no fiber optic coverage here)... confirmed the IP changed on each mobile data reconnect)

**Comment by rubenwardy** [comment]
This is a small security measure which stops the less technologically able from being able to ban evade. It should probably just be a hash of the mac address to make calculation

However, this is a privacy concern and potentially unethical. I don't see the community taking this favourably

**Comment by hecktest** [comment]
Fingerprinting is evil, and provides zero security. The server should not receive more info about the client than what is needed to run the game. (and so far, PC/mobile is the only meaningful difference between clients)
Instead of trying to do the impossible, focus on why you'd want to ban players in the first place, think of what the player loses by being banned, and try to limit the damage a new player can do. This is chiefly a game & mod design problem, not an engine thing.

**Comment by sfan5** [comment]
The answer is no, #6114.

**Comment by rubenwardy** [comment]
This is not a duplicate of that issue

**Comment by sfan5** [comment]
Right, I meant to reference that issue as an example for another rejected "trust the client to calculate some hash to provide security".

**Comment by rubenwardy** [comment]
Sure, not a duplicate but similar reasoning

**Comment by paramat** [comment]
What SmallJoker wrote.
