### ISSUE TITLE
Add option to filter out non-free packages

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#7640]
Optionally, also have a dialog to allow users to choose

**Comment by Wuzzy2** [comment]
Thank you. :+1:

**Comment by paramat** [comment]
Really a blocker? Doesn't seem high priority, the non-free status of a package is already obvious when viewed. If someone cares about that they will already check.

**Comment by Wuzzy2** [comment]
> the non-free status of a package is already obvious when viewed. 

Really? I do not see any indication of a package being free or not. Non-free packages look exactly the same. This is bad. Right now Minetest actively promotes proprietary packages without any warning whatsoever.

Remember, this is the *Minetest* repo, not the repo for the website.

**Comment by paramat** [comment]
Is the license not visible? Sorry no experience of CDB.

**Comment by Wuzzy2** [comment]
Yes, there is no license information / freedom whatsoever in Minetest.
To test, just compile Minetest (-dev), click on the “Content” tab and start to browse.

**Comment by paramat** [comment]
Ok sorry and thanks. Shouldn't licence be viewable in the CDB? It's quite important.

**Comment by Ezhh** [comment]
It is viewable in CDB the website, but not viewable when checking packages from the client.

**Comment by paramat** [comment]
I agree.
License is more important than filtering out non-free packages, because the license contains that info plus more, it should be visible when the package itself it viewed. Anyone concerned about non-free will need to know how it is non-free, so a simple filter is not very useful, the license itself needs to be seen.
The non-free filtering thing is i suspect, somewhat as a result of hysterical forum posts.

Or alternatively, don't filter and don't show the license, require that users go direct to the CDB site to check, this is more than reasonable, if CDB can be used from MT then the user can visit the site in a browser too.
I don't consider this being of blocker importance, but that's up to the CDB maintainer.

**Comment by Wuzzy2** [comment]
> Or alternatively, don't filter and don't show the license, require that users go direct to the CDB site to check, this is more than reasonable, if CDB can be used from MT then the user can visit the site in a browser too.

Yeah right, force users to go to the official website for *every single mod*. -_-
Believe it or not, there are *actually people in Minetest* who actually *do care about their freedom*. I know, this sounds crazy, but it is true.

**Comment by paramat** [comment]
It makes sense that mod browsing mostly takes place in a web browser, not in-game, as the in-game browser obviously cannot  be as complete or show as much information. So it's reasonable that users browse and choose mods in a web browser, the in-game access is mainly for downloading.

Otherwise the in-game browser would have to become excessively complex, it's best kept simple.

**Comment by paramat** [comment]
:-1: for the specific request.
The license is the important and much more useful information, as without that you wouldn't know how it is 'free' or 'non-free'. Filtering by 'freeness' doesn't take into account the details of the licenses, so is not very useful information.
Those concerned about 'freeness' should look at the licenses as they browse, filtering in the in-game content browser is not important enough to be justified, best left to the website if it must be done.

It's a good idea to not be too concerned with Wuzzy's hysterical rants, we've just been through this with dye groups too. This is not the big issue it's made out to be.

**Comment by rubenwardy** [comment]
This will be required in order to ship Minetest on debian

**Comment by paramat** [comment]
Oh interesting. Sorry i didn't realise.

**Comment by paramat** [comment]
That really should have been mentioned in the description :) Would have saved lots of consideration and argument.
Is there a discussion about this somewhere that can be linked to, in the forum perhaps?
What exactly does Debian require?

Oddly enough i feel that it's better to do this the simple way, just not allow non-'free' content in the CDB.
Non-'free' content must be a small minority so it's no loss. We can allow it in the forum as before but not in the CDB.
Even to me it would seem odd to provide non-'free' content in an in-game browser in a 'free' game.

So i'm still :-1:

**Comment by rubenwardy** [comment]
This is literally 3 lines of code in the engine, btw. 2 to add a setting and 1 to use it

**Comment by paramat** [comment]
Ok, removing my -1 as it's down to c55.
