### ISSUE TITLE
Expose client's current window size to Lua API

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#7658]
##### Issue type

 - Feature request

##### Summary

It'd be very useful to be able to retrieve a client's window size (**not** their screen resolution - which differs if application is not running in fullscreen) by simply calling a function `minetest.get_windowsize(player_name)`, which returns a table with two fields `x` and `y`, holding the horizontal and vertical size of the application window in pixels.

##### Use-cases
- Accurate scaling / sizing of HUD elements.
  - Useful for elements using pixel values, like `offset`
- (More to come...)

##### Implementation details
- Variables `screen_w` and `screen_h` in `RemotePlayer`.
- Client sends initial windowsize to server while establishing a connection, as a part of  `TOSERVER_INIT`.
- Client sends windowsize on every window resize event.

**Comment by paramat** [comment]
Is a mod likely to adjust aspects of HUD per-player? Seems unlikely. Also seems unlikely a mod would update HUD aspects each time the client resizes their screen. Also adds network traffic. I can't yet see justification.

**Comment by ClobberXD** [comment]
@paramat - They should be read-only properties.

@rubenwardy - the resolution should primarily be used for centering stuff, based on the client's resolution and also adjust their aspect ratio, so as to not get squished on non-standard aspect ratio screens.

**Comment by ClobberXD** [comment]
Here's an example where an aspect ratio would be useful: If I need to show an element whose dimensions need to be preserved. There's no way to achieve this, without the window size or at least the aspect ratio.

**Comment by paramat** [comment]
:-1:

**Comment by ClobberXD** [comment]
Is it a good idea to have a bool field `preserve_aspect_ratio` within the HUD element def? It would default to false to preserve current behaviour.

**Comment by paramat** [comment]
Disapproved.

**Comment by sorcerykid** [comment]
What about exposing the client's screen DPI instead? At least that would be a happy medium for situations where custom scaling of HUD or formspec elements would be valuable. The DPI of the client is persistent for the duration of a session, so the value could be passed during the initialization phase. For the API, it would just be a matter of adding a method of the player object; i.e. `player:get_display_dpi()` or something similar.

**Comment by LoneWolfHT** [comment]
If you resize small enough the layout of things like the pause menu will break anyway

**Comment by appgurueu** [comment]
HUDs are fundamentally broken. This partial easy fix is being shut down for no good reason. Heck it.

**Comment by SmallJoker** [comment]
@appgurueu Reported in #6296 and #10733. Please propose solutions there. New API functions to manually deal with scaling issues isn't a long-term solution.

**Comment by samarth-ramesh** [comment]
> IMO you should present a more concrete, well-written and convincing use case first.

Possible use cases:

1. Pick and choose formspecs based on display sizes. So as a result, the modder can show different formspecs better optimised for touchscreen and mobile devices.
2. Server owners can at their discretion filter out certain resolutions which currently don't have rich support.
3. It gives more control to the game/ server owner to decide the client type ( for example, sanely get rid of a large number of mobile users who time out too quickly and just waste resources

**Comment by oversword** [comment]
I was just looking for something like this, I agree the HUD is fine, though this is desired for formspecs.
Here's my use-case:

I have a two-page formspec format (two blocks next to each-other), but at some point the width of the screen becomes too small to display two pages, since text does not resize. At this point it would make sense to display one page and have a "next page" button, or some other means of navigation to see the other page.


As a developer, I want to test this out at every screen size and see it change dynamically - but that is just not required for the actual players.

For them, we can assume the size of the window stays the same, and should be available to the formspec generator method once at time of creation - if they need to resize it they can close & reopen it. We also don't need complete information about their screen. For my specific scenario, and I expect most scenarios people are coming across, we really only need "big" and "small". Perhaps from a more objective standard we could go with "mobile" and "desktop".

To be honest, I don't think developers would be thoughtful enough to write something that can re-arrange the form dynamically anyway, unless we intend to adopt a standard like CSS&HTML then that kind of dynamism just can't be expected. So we really just need this data to be available once per formspec

Though, framing it as "big" and "small", or having several snap-points, we would not need to send nearly as much data back and forth for effectively the same results if we wanted to make that dynamic.

**Comment by oversword** [comment]
Here's an idea:

Any formspec can now contain two new elements:
`big_screen_display[X,Y]...end_big_screen_display[]`
`small_screen_display[X,Y]...end_small_screen_display[]`

If you send both, the client will decide which to display
