### ISSUE TITLE
Apply physics modifiers on top of current values

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#7705]
##### Issue type

 - Feature request

##### Summary

Absolute multipliers result in conflicts between mods, potentially breaking the behaviour of the game. Neither can new mods be developed keeping other physics modifiers in mind, since the mod writer would have no idea about which mods will be deployed alongside their mod, and what physics modifiers those mods introduce.

**Comment by tenplus1** [comment]
We need an engine based API that handles player physics overrides using the best features of the mods available which do the same (monoids, pova, physicsh)...

**Comment by MineWitherMC** [comment]
I think there is PR: #7269. Surprising enough, it is not merged because of wrong function of `set_physics_override` (!)

**Comment by ClobberXD** [comment]
Oh nice! That's exactly what this feature request is all about :D

**Comment by paramat** [comment]
Difficult subject, see the discussion in that PR. Also the need to not break existing mods.

**Comment by ClobberXD** [comment]
Yes I've already read the discussion and as far as I can tell, the issue is mostly about the impossible coherence between overrides and modifiers. Avoiding mod breakages and retaining backwards-compat is of paramount importance, but at times, we _need_ to introduce breakages for the sake of critical new features/improvements.

In this case, physics modifiers (a.k.a multipliers) is the most logical implementation, and when merged, existing mods too should adapt and replace overrides with modifiers instead.

**Comment by paramat** [comment]
> In this case, physics modifiers (a.k.a multipliers) is the most logical implementation

I disagree, it's just as valid and essential to set an absolute value independent of what came before. We can have both as the PR now does. They may not work together but we can still have a choice of which to use.

**Comment by paramat** [comment]
:-1:

**Comment by ClobberXD** [comment]
> However i also see combining modifiers as highly variable in implementation and at gameplay-level, so should be done as mods in games or optional mods, all applying their final result using the engine's existing override system.

While this seems to be the best option at the moment, one obvious issue with this approach is that standalone mods (those not bundled with games) have to support all mods that provide support for physics modifiers, like `player_monoids`, `pova`, etc.

**Comment by LoneWolfHT** [comment]
Could this be reopened and possibly reworded?

**Comment by paramat** [comment]
You can continue discussing here, it does not need to be open to do that.
There is no core dev support so i think this should stay closed (otherwise we drown in issues).
Rewording this issue does not seem acceptable as the title should reflect the intent of the thread author. However, you can discuss similar proposals here if you want.

**Comment by LoneWolfHT** [comment]
Copying the text from that issue over to here then:

I want to be able to set player physics without worrying about breaking other mods. I could add support for the physics handler mods out there but every mod uses a different one. It would take forever to support them all, and most of them are very different from each other, so I can't really copy and paste any code either.
It was suggested that the physics managers be 'per-game'. But MTG doesn't have one, and I'm guessing about 90% of all mods are made for MTG, so that's where I would mainly be concerned about conflicting with other mods
