### ISSUE TITLE
Blue water fixes

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#7721]
##### Issue type

 - Feature request
<hr>

In RL water looks blue because of reflections from the sky. 

But if the above area is covered  (e.g. Trees, a cave roof or if it's night time)
The water won't look blue is it can't possibly reflect the sky
### DAY
![screenshot_2018-09-10-11-09-42-1](https://user-images.githubusercontent.com/33675971/45315967-96ca7e00-b4ea-11e8-8500-4efb927dcde6.png)
### NIGHT
![screenshot_2018-09-10-11-08-10-1](https://user-images.githubusercontent.com/33675971/45315990-a21da980-b4ea-11e8-8dfa-823e19630a78.png)
### CAVE
![screenshot_2018-09-10-10-41-53-1-1-1](https://user-images.githubusercontent.com/33675971/45316062-cb3e3a00-b4ea-11e8-8ad7-342f5535b33b.png)
 A simple change. 
The less natural light water gets the darker and clearer it will be

**Comment by Extex101** [comment]
Oh I probably should have done this under minetest_game

**Comment by Extex101** [comment]
Z

**Comment by Extex101** [comment]
Oops I'm new to this XD

**Comment by rubenwardy** [comment]
This is actually the correct repo

**Comment by Extex101** [comment]
What do you think of the idea?

**Comment by beyondlimits** [comment]
I was playing with uncolored water in the past. Guess, It doesn't look like it's clear. It looks like it's dark!

Probably it would look nice if it was wavy and reflective, like in Cube 2: Sauerbraten (then it can be clear - everyone knows it's water), but it's rather hard to expect considering current state of Minetest.

**Comment by paramat** [comment]
In real life water often doesn't look blue, but if it does it's not due to reflecting sky (which is often not blue) it's due to how it scatters light, so it will still look blue under artificial light.
https://www.scientificamerican.com/article/why-does-the-ocean-appear/
In MT water doesn't reflect the sky anyway.
Apart from all that this would be far too complex and perfectionist to implemeny anyway, MT is only loosely realistic in a simple way.
