### ISSUE TITLE
Allow spawning particles in a circle around the player

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#7746]
As per https://github.com/minetest/minetest/issues/4501#issuecomment-423700211, I am opening Github issues for particle spawner features.

It should be possible to have particles spawn in a circular shape around the player (either filled circle or outline). This could look nice for effects. It is not currently possible to emulate this except maybe by adding many particle spawners around the player in a circle.

**Comment by raymoo** [comment]
Why not reopen the issue specifically asking for a general mechanism for defining particle spawners then?

**Comment by paramat** [comment]
That issue was closed due to having no core dev support long term, no other reason.
Also i'm really sorry to disagree with you so much recently.

**Comment by raymoo** [comment]
OK, thanks for the clarification.

**Comment by raymoo** [comment]
Though @SmallJoker thumbsed up my post about reopening the other issue, which could be interpreted as support for it (though could just be an opinion about procedure rather than the feature itself)

**Comment by SmallJoker** [comment]
@raymoo The reaction was especially for that single statement, since these two recent issues only have the reasonable solution of implementing generic particle animation code. Such a feature would be nice, but probably requires a ton of new code for improved visual effects. Generally supporting the idea, but it depends on the implementation.
I also suggested some days ago to [close these two issues in favour of generic particle spawners](http://irc.minetest.net/minetest-dev/2018-09-25#i_5411981).
