### ISSUE TITLE
Core devs: Old unsupported feature requests need a look

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7758]
Sorry for opening an issue but this is the only way i can be sure to reach all core devs. Core devs rarely look at the organisation topics. So this issue is temporary.

All 'feature requests' and 'request/suggestions' that have been open over a year with no core dev support are now labelled with 'core dev consideration needed', please can core devs give these a quick look and, importantly, add a comment if you support it.

**Comment by SmallJoker** [comment]
Feature requests are fine; they might result in some nice ideas to improve Minetest. It's well understandable that a game like this has endless potential of features to add - dev time and complexity is what holds it back.

Although I can see that the large amount of them makes duplicates or related issues quite difficult to find. The requests are usually reasonable and implementing them would actually improve either the visuals or extend the modding possibilities. I rarely show support on those because I'm not sure whether that's the best approach on its implementation or whether it's worth the effort. It also feels unpopular with two comments per year - so closing some of them after at least a "silent year" is a good decision.
