### ISSUE TITLE
not_in_creative_inventory group is not documented (remove 'soil' from engine docs)

### ISSUE THREAD

**Issue by GreenXenith** [minetest/minetest#7783]
##### Issue type

 - Documentation issue

##### Summary

`not_in_creative_inventory` is missing from the lua_api.txt. Should probably be listed under [Special Groups](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1526-L1553). Not that it is a huge problem, but I got really confused when I was searching for it to make sure I got the name right...

**Comment by Wuzzy2** [comment]
`not_in_creative_inventory` is NOT a special group, it does not get any special treatment by Minetest.

This behaviour actually comes from games/mods. In Minetest Game, it's in the `creative` mod.

However, this group is the *de facto* standard group which all mods and games have agreed on. It is *not* enforced by the engine, however. https://dev.minetest.net/Groups/Shared_groups

It might be argued that because this group is so wide-spread, it might be mentioned in official docs anyway.

Definition:
`not_in_creative_inventory=1` means that the item must not appear in the creative inventory.

**Comment by GreenXenith** [comment]
> `not_in_creative_inventory` is NOT a special group

I said this simply because it is a group and doesn't really fit the other group categories. I dont really care where it goes - I just think it should be in there.

**Comment by rubenwardy** [comment]
This group has no meaning in the engine. It's a group used by the creative mod in MTG. I won't be against adding a section for common groups, but it shouldn't pretend to be something the engine cares about

**Comment by DS-Minetest** [comment]
Does the `soil` group have a meaning to the engine?
https://github.com/minetest/minetest/blob/b6adb7f09e4375f145c3ddb592527c1dd0b026a2/doc/lua_api.txt#L1549

**Comment by Wuzzy2** [comment]
No. `soil` does not have any meaning in the engine, it should be removed.

**Comment by pauloue** [comment]
Maybe it should be in the MTG [game_api.txt](https://github.com/minetest/minetest_game/blob/master/game_api.txt). It's also on the wiki: [shared groups](https://dev.minetest.net/Groups/Shared_groups).

**Comment by Ezhh** [comment]
It is good when games can agree to common standards, but that doesn't make it right to include documentation for them in the engine as though they are standard for everything; this could actually be misleading and confusing for some people. 

Games should document their own groups. Perhaps there could also be a section somewhere for commonly agreed standards between games, but I suspect agreeing on what should be included could spark some 'interesting' conversation.

**Comment by paramat** [comment]
I don't think these game groups need to be documented in the engine, and there's not much need for it being documented in the game either. The game code documents it's usage already.

**Comment by paramat** [comment]
Reopen until 'soil' is removed.
