### ISSUE TITLE
Allow games to contain worlds. Allow specifying which worlds can be used by a game

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#7809]
We need some way to only use a specified map for a subgame
For games such as [Tutorial](https://www.google.com/url?sa=t&source=web&rct=j&url=https://wiki.minetest.net/Games/Tutorial&ved=2ahUKEwjm1dujnpjeAhV9HDQIHf4vA0kQFjAAegQIAhAB&usg=AOvVaw1h5Ju6W3oaVBSj4kCuFCNY) where the game won't work without a specific map.

I think we should have something like this
Game
Menu.         | mods |                      map
menu files | mods | map_meta, and other mark files

**Comment by Ezhh** [comment]
In current dev version it's already possible to exclude mapgens for a specific game. Just set disallowed_mapgens in game.conf.

If you mean maps supplied by the game itself, then the game itself needs to supply those maps anyway.

**Comment by paramat** [comment]
```
World-specific games
--------------------

It is possible to include a game in a world; in this case, no mods or
games are loaded or checked from anywhere else.

This is useful for e.g. adventure worlds and happens if the `<worldname>/game/`
directory exists.

Mods should then be placed in `<worldname>/game/mods/`.
```
Seems possible already, you can provide a game contained in a world. So that game canonly be used with that world.

**Comment by Wuzzy2** [comment]
Games included in a world sound interesting, but they are not very useful for adventure maps or the Tutorial. You cannot reset them. This is a very crucial missing feature. The only way to “reset” them is by deleting the world and re-copying it from scratch, all by hand.
Also, the main menu does not seem to display those worlds properly because the main menu assumes you always have a game selected

In the current form, “world-specific games” still need work as there are too many rough edges and they are certainly not solving this issue.

This particular feature request does not make sense. Hiding random worlds by name is a crappy solution and can be easily circumvented and does not improve anything. This request should be rejected.

I think what the author REALLY wants is proper support for adventure worlds.

I define an adventure world as a world in which the world and the player start with specific conditions in a specific enviroment with some challenge to beat. Think of it as a level/stage.
What is crucial here is that you can either win or lose here. For adventure world to work, there must also be a way to reset them, so you can start over.

It should be clear by now that “support for adventure worlds” is pretty much non-existent. But this is off-topic anyway.

---

Sidenote: It is no longer true that Tutorial requires the user to install the world manually. The world is included in the game (using some hackery) and will be generated when you create a new world. This is just an emergency solution, but at least it works and also allows easy resetting (you just create a new world).

**Comment by jastevenson303** [comment]
paramat i dont understand.  he's asking to be able to distribute games with worlds that are available by default.  currently you have to ship both game and world and ask user to put world in worlds dir.

does that make sense?

**Comment by jastevenson303** [comment]
games cant ship worlds.  they must be shipped in parallel.

it would be nice if games could ship worlds.

**Comment by jastevenson303** [comment]
That's two features: 1) Allow games to ship with worlds ("contain worlds"); and 2) Able to precisely specify which maps can be used with the game.

That's kinda a misleading title change, but better than the original.  Still, it's framed as two feature requests in one IMO.
