### ISSUE TITLE
Node side facing world edge does not render (add air gap)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#7815]
##### Issue type
 - Bug report
 
##### Minetest version
```
0.4.17.1
```

##### Summary
At the world edge, the side of nodes facing the world edge is never rendered. This grants player a rare view inside the land.

##### Steps to reproduce
1. Teleport near the edge of the world (0, 0, 30912)
1. Go to the surface (use noclip if needed) and stand as close to the edge as possible
1. Switch camera to 3rd person view
1. Look towards the generated land

Result:
![Screenshot of the world edge](https://i.imgur.com/WwgCSN8.png)

The side of the solid nodes facing the edge is not rendered, allowing a look inside the land and caves below without any special privs. This is a rendering fail IMO.

Expected result: For solid nodes, the side facing the world edge is rendered, thus obstructing the view into the cave system below.

Fun fact: Glasslike nodes and leaves have all their sides rendered.

Fun fact: This works in all 6 directions.

**Comment by rubenwardy** [comment]
This is because the nodes are next to `ignore` nodes, and so treat it as a solid node. It may be better to treat ignore as air, but this could cause inefficiencies

**Comment by Wuzzy2** [comment]
Maybe only treat `ignore` as `air` (for rendering purposes) when it is outside the map bounds.

**Comment by paramat** [comment]
I don't consider it a bug, the edge of the world is likely to be weird and this makes it suitably weird. I don't think seeing through the world at world edge is a big problem since it only happens here.
So i feel this isn't worth being concerned about and the work and code to alter it not justified.

In one of my core mapgen experiments i created an air gap between the solid edge and the ignore edge to make the world a cuboid floating in space, you could fall or climb down the side of it:

![screenshot_20180401_130319](https://user-images.githubusercontent.com/3686677/47418278-b8698700-d771-11e8-914a-599051fba899.png)

**Comment by rubenwardy** [comment]
CTF uses a fake ignore node which renders the sides of the world, but doesn't allow water to flow:

```lua
minetest.register_node("ctf_map:ignore", {
	description = "Artificial Ignore", -- this may need to be given a more appropriate name
	drawtype = "airlike",
	paramtype = "light",
	sunlight_propagates = true,
	walkable     = true,
	pointable    = false,
	diggable     = false,
	buildable_to = false,
	air_equivalent = true,
	drop = "",
	groups = {not_in_creative_inventory=1}
})
```

**Comment by Extex101** [comment]
I think it's good the way it is because otherwise you can see all the ores along the edge
