### ISSUE TITLE
Load textures from the subfolders in mods' textures folders

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest#7818]
##### Issue type
 - Feature request

##### Summary
With #6412 in place I believe it would be even more coherent if mods' `textures` directory behave in the same way so that content of that directory's subdirectories are accepted when loading the mod.

**Comment by DS-Minetest** [comment]
The issue title is misleading because the texture pack folder is named "textures", too.

**Comment by thecow275** [comment]
This would be a useful feature as i hate working with textures that are in a single folder for example i have a mod that adds multiple nodes with 6 different textures 1 for every side so it would ease my mod updating and maintenance a lot if we could have subfolders in textures as i would only have to look at the particular node's folder to change the textures if needed and this would help with renaming some nodes textures 
for example now you have to rename every single texture for that node so "modname_node1_sidehere.png would need to be renamed manually to modname_node2_sidehere.png and so on instead if we had subfolders that could be used for this so textures/modname_node1/sidehere.png etch could easily be renamed to textures/modname_node2/sidehere.png so only the folder would be needed to be renamed instead of the texture names also the textures folder wouldn't be such a mess to deal with when you have multiple nodes that have different textures for all sides.

so
`tiles = {"modname_nodename_side.png"},`
would become
`tiles = {"/modname_nodename/side.png"},` or `tiles = {"modname_nodename/side.png"},` or even
`tiles = {"textures/modname_nodename/side.png"},`
when using subfolders
if not possible to implement with current way of loading textures it could be possible to do `tiles ={"modname_nodename/modaname_nodename_side.png"},`

another idea is that it could be

`tiles = {"modname_subfoldername/nodename_side.png"},`

also sorry english is not my main language and is self learnt so that is why my marking and punctuation is flawed or completely missing

**Comment by benrob0329** [comment]
This wouldn't change the naming, it would just add organization to the existing texture system.

**Comment by DeltaNedas** [comment]
This would really help with large mods.

**Comment by DS-Minetest** [comment]
Implementing this might be relatively easily. Just push the `dln.name` to `paths` here:
https://github.com/minetest/minetest/blob/05a7da627959afef2198f2036f4144e3d8abfbda/src/server.cpp#L2347-L2348

**Comment by tacotexmex** [comment]
Could you create a PR?

**Comment by DS-Minetest** [comment]
Done: #9065
