### ISSUE TITLE
Improve Copy/Paste Support

### ISSUE THREAD

**Issue by WulftheNordicRanger** [minetest/minetest#7830]
##### Issue type
 - Feature request
 
##### Minetest version
0.4.17.1

##### OS / Hardware
Operating system: Linux Mint
CPU:AMD raedon

##### Summary
I would like to see the copy/paste support in minetest improve so that people can make better use of password managers so people can make use of stronger passwords on servers. Specifically, a copy/paste dialogue when right clicking in text fields.

**Comment by paramat** [comment]
Duplicate, #1312 has become about copy/paste, as the core devs consider that more useful than the original request of clickable links.

**Comment by paramat** [comment]
#1312 was closed by author so re-opening this issue.

**Comment by edo9300** [comment]
I'm not an user of this program, but since I too am working on a project using the irrlicht engine, I know pretty well its issues, and I too struggled a lot with the clipboard handling on Linux. But recently i managed to fix this issue and i pushed those changes in a fork of mine of irrlicht1.8.4, https://github.com/edo9300/irrlicht1-8-4/, since in my project too some snippets from this project are being used, i think i'm in duty to help the development of this project :). Hopefully the commits would be self explanatory, but if you need clarifications I'll gladly help.

**Comment by SmallJoker** [comment]
@edo9300 That's great news. Thanks you for looking into this issue. Are there any chances to get those changes into the original/upstream Irrlicht repository, or is it too dead to accept contributions?

**Comment by edo9300** [comment]
Idk, i've planned to try to commit some minor fixes there as well, _but one of the things that's preventing me from doing that is understanding how sourceforge works_, while for this clipboard change, i'm not very fond of the char* to wchar_t* conversion, as i'm using a manual approach, instead of using the functions from the standard (mainly because that's an hackish way to avoid dealing with locales), so i'm not sure about how they'll look in upstream (this commit https://github.com/edo9300/irrlicht1-8-4/commit/68049587fdcbd8d025c6a4f4307a4b6fde85cc84).
> or is it too dead to accept contributions?

i checked the forum and weirdly there were some posts from this month, maybe the project isn't completely dead yet XD.

**Comment by appgurueu** [comment]
You are talking about https://github.com/edo9300/irrlicht1-8-4/commit/d1584400f918397b1c4edaefa35a69a93a49bdac and https://github.com/edo9300/irrlicht1-8-4/commit/f4a3f9a4fddf1b05eb6fc9988adbb5f24156afec I assume?

**Comment by edo9300** [comment]
> You are talking about [edo9300/irrlicht1-8-4@d158440](https://github.com/edo9300/irrlicht1-8-4/commit/d1584400f918397b1c4edaefa35a69a93a49bdac) and [edo9300/irrlicht1-8-4@f4a3f9a](https://github.com/edo9300/irrlicht1-8-4/commit/f4a3f9a4fddf1b05eb6fc9988adbb5f24156afec) I assume?

Those commits were just some "desperate" attempts to make things work (and in the end they revealed to not be really needed), you can see the major changes that were needed to fix the clipboard here [CIrrDeviceLinux.cpp](https://github.com/edo9300/irrlicht1-8-4/compare/746909a9249163cb2251dae7349da98d105c5d18...master#diff-0da010150b62ba6b4d11e5ad57707fcb), alongside the other changed files (the OSOperator and CGUIEditBox)

**Comment by kevinlul** [comment]
Basically, for the purposes of Minetest, are the core developers willing to modify and patch Irrlicht 1.8.4 for the bugs it shipped with, since the timeline for a 1.9 release is uncertain?

**Comment by sfan5** [comment]
That's kind of hard to do since we don't control the way Minetest is distributed on Linux.
Short of importing the entire Irrlicht source tree into Minetest, your only option is to copy in single source files over, which doesn't look possible in this case.

**Comment by kevinlul** [comment]
That's true. We deemed proper UTF-8 clipboard support, some coordinate fixes on macOS, and other features that we've added are critical for usability, so we static link Irrlicht on all platforms. For quite some time, I admit we did use package manager-provided Irrlicht.

**Comment by mk-pmb** [comment]
> since we don't control the way Minetest is distributed on Linux.

Does it mean this bug can be fixed by installing a patched version of Irrlicht into the build environment? That sounds like an easy way to fix it in our PPA at least, and our Makefiles could hint at this thread if they detect a broken Irrlicht.

**Comment by mk-pmb** [comment]
Meanwhile I figured out the Irrlicht version in the build system only matters if you build statically. On the other hand, if we build Minetest dynamically, it means users can use the current Minetest binaries and just upgrade specific Irrlicht functions via `LD_PRELOAD`. I'll investigate a bit.

**Comment by mk-pmb** [comment]
@edo9300 I tried to build libIrrlicht from your repo. (`make --directory=source/Irrlicht clean sharedlib`)
My plan was to make it work with entirely your version, then try and extract only the relevant functions into an LD_PRELOAD library.

* The latest commit 10959c76d compiles but makes MT 5.3.0 segfault, so I tried to find an older commit that works.
* commit 746909a92 ("Add additional editbox text controls") works but still has the problem that clipboard content resets after a very short time.
  Workaround: [xsel helper script](https://github.com/mk-pmb/minetest-util-pmb/blob/master/misc/copypaste_helper.sh), but this seems to freeze the client for a few seconds each time it seizes responsibility for maintaining the clipboard content. Thus, reliable copying becomes possible, but at a heavy price. No sulution for paste yet.
* commits 741b6b7ba ("Update linux clipboard handling") and e3265857b ("Update clipboard functions") cannot be compiled: `CIrrDeviceLinux.cpp:1893:12: error: cannot convert ‘irr::core::stringc’ {aka ‘irr::core::string<char>’} to ‘const c8*’ {aka ‘const char*’} in return`

Do you have advice for how to make it work, or what parts of your many patches I should apply?

**Comment by edo9300** [comment]
> * The latest commit 10959c76d compiles but makes MT 5.3.0 segfault, so I tried to find an older commit that works.

hmm, i don't have such issues, highly probably it is abi incompatibility (did you just try to make minetest load the different library without recompiling it first?)
> * commit 746909a92 ("Add additional editbox text controls") works but still has the problem that clipboard content resets after a very short time.
> * commits 741b6b7ba ("Update linux clipboard handling") and e3265857b ("Update clipboard functions") cannot be compiled: `CIrrDeviceLinux.cpp:1893:12: error: cannot convert ‘irr::core::stringc’ {aka ‘irr::core::string<char>’} to ‘const c8*’ {aka ‘const char*’} in return`

Starting from this commit https://github.com/edo9300/irrlicht1-8-4/commit/714022e32a1846665e09a524d3dff3df5b639b07 the clipboard should be properly working and the client compiling, the commits you took were too old to have the proper changes applied. Anyways, if you want to keep compatibility with the standard irrlicht as well, you'll have to change back this https://github.com/edo9300/irrlicht1-8-4/commit/e3265857ba3e3d7207fd309724b13d7dec763696 (and the other changes that came after changing the clipboard data type that could have been done in subsequent commits) and make the clipboard functions work with char* rather than wchar_t* again.

**Comment by mk-pmb** [comment]
Yes my plan is to make clipboard work in the original MineTest for Ubuntu as is provided in the PPA. Thus I only modified the library. To make this work, I'll have to reimplement the functions without changing their parameters or header files.
Thanks for the pointer, I'll try to undo that commit then.

**Comment by zeuner** [comment]
Great! Using https://github.com/edo9300/irrlicht1-8-4 and changing some occurrences of char to wchar_t, Minetest can now paste text from other applications using Ctrl-V on the Ubuntu machine where I tested it. However, I can't figure out how to copy text from Minetest so it can be pasted into another application.

**Comment by mk-pmb** [comment]
> Ctrl+C doesn't put anything in the clipboard.

Are you sure about that? With the original binary, mine does, albeit only for a very short timespan and/or one paste (whichever happens first). That's what my "xsel helper script" (see above) picks up.

**Comment by mk-pmb** [comment]
Also I assume with "put … in the clipboard" you meant something like ["serves CLIPBOARD selection requests"](https://www.uninformativ.de/blog/postings/2017-04-02/0/POSTING-en.html).

**Comment by zeuner** [comment]
@mk-pmb Thanks, you're right. I can see clipboard activity using your xsel helper script, at least when I copy text from formspecs. Nothing happens when I try this from the server login screen, though.

Can I somewhere find some more in-depth information on why Minetest/Irrlicht serves the clipboard data for just such a small timespan?

**Comment by r1bnc** [comment]
Still no fix?? Is there any way to copy-paste using 3rd party GNU/Linux programs?

@mk-pmb  Can you please add descriptions and how to use the scripts at `minetest-util-pmb` repo?

**Comment by rubenwardy** [comment]
I'm able to copy past into Minetest on Manjaro linux by pasting twice. I have clipman/xlip

This is a bug in Irrlicht, and will be possible to fix when we move to our own fork of it. Hopefully 5.5.0

**Comment by mk-pmb** [comment]
@r1bnc I added an explanation to the clipboard helper script.

**Comment by zeuner** [comment]
Any chance the relevant changes from https://github.com/edo9300/irrlicht1-8-4/ can be ported to https://github.com/minetest/irrlicht ?

**Comment by sfan5** [comment]
Open an issue on our irrlicht repo with a list of commits so we don't forget.

**Comment by sfan5** [comment]
fixed by minetest/irrlicht@9c4b6f25ab73c413730f9c8d35f34ef7db7e2b33

**Comment by mk-pmb** [comment]
Very nice. Thanks! Let's hope it works.

**Comment by r1bnc** [comment]
Thanks
