### ISSUE TITLE
Attachments not in effect on client if client joins after attachment is done

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#7841]
##### Issue type
 - Bug report
 
##### Minetest version
```
0.4.17.1
not in 5.0.0 (!)
```
Operating system: Ubuntu 16.04

##### Summary

I've written a mod(see "playertags").
It attaches nametag entities to people.
When opening a server, for me, the server admin, everything works perfect.
But not if I join from the same host : 
It seems that entity attachment is lost, the entity is just laying around, and not attached to the player when viewed from the client.

##### Steps to reproduce

Use playertags mod, host a game, join it from your local host, and see the problem.

**Comment by appgurueu** [comment]
![Entity data seems lost : PROLMD nametag stuck in dirt when viewed by LMD_ALTER_EGO, a client](https://user-images.githubusercontent.com/34514239/48072885-cab9db00-e1dd-11e8-9337-5b6a7e993056.png)

![Here, for PROLMD, the server admin, it's working fine](https://user-images.githubusercontent.com/34514239/48072914-dc9b7e00-e1dd-11e8-8bbe-0ee26a3e875a.png)

**Comment by appgurueu** [comment]
This is strange because 3d armor works fine.

**Comment by appgurueu** [comment]
**Tested & found out that this bug is not present in 5.0.0**

**Comment by appgurueu** [comment]
**Hacky solution**
attach playertag again on_step : 
`self.object:set_attach(minetest.get_player_by_name(self.owner), "", {[...]}, {[...]})`
Now, new bugs appeared, but they are not that bad...

**Comment by paramat** [comment]
Please can you link to your mod code?

**Comment by appgurueu** [comment]
I am renaming this issue as actually the data seems to be preserved but the attachment is lost.

**Comment by paramat** [comment]
Yes a known bug, and i searched too but couldn't find an issue.

**Comment by appgurueu** [comment]
Will this be fixed in another 0.4.1x.x bugfix release ?

**Comment by SmallJoker** [comment]
@appgurueu I already looked into this issue and can tell that it'll be fixed way after the last 0.x release. It's a rather complicated issue because entities aren't sent all at once when the players joins, thus attachments sometimes fail to find the parent (which isn't known to the client yet).
PRs are welcome, but it'll surely take a while to fix it.

Also imagine the player view distance is set to "infinite": The car/cart where the player sits in is currently not sent to other players when it's out of range, thus the player cannot be attached to it. This also means that their position and rotation won't update unless the object and the attachment is known to the other players.

**Comment by raymoo** [comment]
A more performant workaround than reattaching every server step would be reattaching on every player join

**Comment by appgurueu** [comment]
@raymoo that's already how it works

**Comment by sorcerykid** [comment]
I can confirm that #4128 fixes the problem. I patched my server with the changes in that commit, and now existing attachments (like players in carts) are correctly propagated to clients that later join the game or enter the activeobject radius. So this issue can probably be closed.
