### ISSUE TITLE
Possibility to set a position for node.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#7871]
##### Issue type

 - Feature request
 
I would like to have a possibility to move a node  _without_ removing it and adding again. Couldn`t you add a method like minetest.set_node_pos(nodename, pos) ?

**Comment by rubenwardy** [comment]
A node is directly related to a position, setting the position of a node doesn't make sense

**Comment by Andrey2470T** [comment]
Why is this issue closed ???

**Comment by DS-Minetest** [comment]
@Andrey2470T A node at a position only consists of its name, param1 and param2. The inventory isn't saved in the node. However, you can set an inventory in node meta data, but that's not the node itself.

(Oh, and use a ' instead of a \` or make a \\ in front of it.)

**Comment by paramat** [comment]
It's been explained why this has been closed, because it makes no sense.
> a possibility to move a node without removing it and adding again

See https://github.com/minetest/minetest/issues/7735#issuecomment-422914896
As already explained, nodes are by definition things with fixed positions, MT relies on this to function, it's impossible to move them around without removing and re-adding them.
See https://github.com/minetest/minetest/blob/e5a37543cc7932f6252a086b4b8619b5dde9ae5a/doc/lua_api.txt#L945
"Huge amounts of them are handled efficiently, but they are quite static."
"Static" means they don't move. "Huge amounts of them are handled efficiently" only because they have fixed positions.

If you want something movable use a Lua "object" called an "entity", this is how falling nodes work, see https://github.com/minetest/minetest/blob/master/builtin/game/falling.lua
The node is removed, replaced by an identical-looking entity that then moves, then when it stops, a node is re-added at the new location.
> Let's say i want to move a node that has inventory inside. Then i need to copy content of that inventory before removing, add it to separate table to save, then add node again and later set the content for new node of former one. And it would be easier just to call a function like that

That's not what you are requesting in the first post, also, the node would still be removed and re-added by this function.
> minetest.set_node_pos(nodename, pos)

We already have that.
