### ISSUE TITLE
Architectural improvement needed (Code structure)

### ISSUE THREAD

**Issue by Unarelith** [minetest/minetest#7899]
The goal of this issue is to open discussion on global code architecture and standard.
There's some things that really bothers me in MT codebase so I will list some of them here, and how I suggest to fix them. (I will add more stuff when I find it)

It won't break anything since the goal isn't to change the code itself. However, it will break PRs, that's why I haven't done anything yet. I'm waiting for your opinion.

I have enough time to work on this, and I'm ready to adapt all PRs if I get PR author and coredevs help. This could close a lot of PRs actually.

> Files like [content_sao.h](https://github.com/minetest/minetest/blob/master/src/content_sao.h) holds way too many classes/struct

Split the file into a new folder and one or two classes/struct per file

I made a fork and splitted `content_sao`, here is what it looks like: https://github.com/Quent42340/minetest/commit/da9e0c3dc89d857091ebbd89999f69b2429e7e13

> Some classes are defined in `.cpp` files, for example: [content_sao.cpp](https://github.com/minetest/minetest/blob/master/src/content_sao.cpp#L41)

You should create their own header file. For example, I had to do this for `TestSAO` in my fork.

> Headers and file naming are C-like, not C++-like

Header file extension for modern C++ is usually `.hpp` to let `.h` for C code.
Filenames should also use PascalCase naming instead of C camel_case one.
It's mainly because each file should define only one unit (so one main class and optionally 1 or 2 additional classes/structs which are only used by the main class)

> 80 column width limit is historical and not adapted to modern C++, I think sometimes prevents readability, for example [this code](https://github.com/minetest/minetest/blob/master/src/content_sao.h#L101-L165).

Increase the limit to 120.

> `src/` folder is a mess

Find a better subfolder structure, every file should be sorted in a folder (except main.cpp)
I moved all the files `src/*.h` and `src/*.cpp` in a new folder named `engine` (https://github.com/Quent42340/minetest/commit/c06b7bce2b4412c7d55bbeb2fbafca59e0974d35), then I added a subfolder name `client` for client-specific code (https://github.com/Quent42340/minetest/commit/3a733f26dfb0d6686ab4a7afa93112362d9ddc22).

**Comment by paramat** [comment]
> 80 column width limit is historical and not adapted to modern C++,
Increase the limit to 120.

Not a good idea, on a typical modern monitor i can only just display 2 code windows side by side, essential for working on code.
On GitHub long lines run off display edge in most code views and are therefore unreadable.
In threads, code display clips long lines (> 80 columns) making the code very difficult to read as it needs to be scrolled.
So 80 is actually absolutely essential. The hard limit we enforce is actually 90.

**Comment by Quent42340** [comment]
> Not a good idea, on a typical modern monitor i can only just display 2 code windows side by side, essential for working on code.

I'm doing exactly the same thing and I can see 100 characters in each of my window. So maybe it would be better to increase the limit to 100 and to allow 120 if the line can't be nicely splitted, because too much splitted lines are definitely not good for readability.

I personnally don't mind scrolling a bit, since you'll often remember what you can't see. But there must not be really important things beside 80, like computations or other stuff. For example, if a function call exceeds 100 characters but only forwards current scope variables to parameters with the same name, it's useless to split.

For example this would need to be splitted:
```very_very_very_very_long_func_call(a, b, c, d, e + 1)```

This wouldn't need:
```very_very_very_very_long_func_call(a, b, c, d, e)```

> On GitHub long lines run off display edge in most code views and are therefore unreadable.

You mean when code is embedded in issues/PR comments?

> The biggest problem with code maintenance PRs currently is getting reviews and coping with rebase, as the PRs tend to be big and core dev time is extremely limited. Many good code maintenance PRs are already being neglected. Since it's low-priority work it might be necessary to wait until we are better staffed. However discussion is welcome.

That's why I started my fork as an example of what I suggest.

**Comment by paramat** [comment]
100 might be ok as a hard limit. A lot of our code already goes to around 100.
> You mean when code is embedded in issues/PR comments?

Yes.

By the way, it's really good to see someone new who is able to contribute =)

**Comment by Quent42340** [comment]
> LOL sorry for the mess, MT is a bit messy. As we develop we clean up as we go, but are endlessly stumbling into code that hasn't been touched since it was written.

It's a common issue with big projects like this one.

> No code is obvious, it always needs to be visible when working with side-by-side windows.
There are a few exceptions where a line cannot be split without causing problems.

It really should be. At least obvious to an experienced developer, but still.

> With my 24" 1920 pixel width monitor 100 columns side by side is just possible, but with narrower windows the primary editing window can be kept a little more central on the screen for comfort.
Many MT users have old or cheap equipment so may well have less monitor width.

But they probably have the same resolution, and I'm using a 15'', so technically it's possible.

> I mean like this, which isn't clickable.

Then people should just use this:

https://github.com/minetest/minetest/blob/d83fe16a29c231491183c890c5378c671525fc8e/src/content_sao.h#L101-L165

**Comment by paramat** [comment]
> 80 column width limit is historical and not adapted to modern C++, I think sometimes prevents readability, for example [this code](https://github.com/minetest/minetest/blob/master/src/content_sao.h#L101-L165).

Nothing wrong with that code, a few functions have split arguments, they're still very readable.

Yes actually, some code is somewhat obvious, rarely though. I don't think that's a good enough reason to allow a long line, only if readability is severely affected, which is already covered by the below.

Our so-called 'hard limit' of 90 is not actually enforced, there are a few places where the readability is affected so much that we decide to allow a little more than 90 columns.
> Then people should just use this:

That's only possible when linking to code in the repo. Often we need to post code intended for MT which isn't in the repo.

I do somewhat agree 80 is a little too small for comfort, i'd be fine with no longer mentioning 80 and just saying 'split at 90 unless readability is very severerly affected'.

**Comment by Quent42340** [comment]
> Nothing wrong with that code, a few functions have split arguments, they're still very readable.

Everything is wrong with that code. Some functions are inconsistently defining their content on the next line, some are just splitted. And whole class definition only contains 3 blank lines. So no, this class is not readable.

> That's only possible when linking to code in the repo. Often we need to post code intended for MT which isn't in the repo.

Then make a gist or something, the issue isn't the line length but GitHub's markdown code support.

> I do somewhat agree 80 is a little too small for comfort, i'd be fine with no longer mentioning 80 and just saying 'split at 90 unless readability is very severely affected'.

Nice, the most important is to prioritize readability anyway.

**Comment by Quent42340** [comment]
I work like this:
![screenshot-20181126173111](https://user-images.githubusercontent.com/554446/49027714-176f5100-f1a1-11e8-81dd-e55028ff297c.png)

> Increasing to 140 characters would be way too much, but I wouldn't mind a smaller increase in rare occasions.

*120. 140 is way too much, I suggested 120 based on the code I read.

**Comment by paramat** [comment]
> Everything is wrong with that code.

Sorry, i agree, 'nothing wrong' was unclear. I meant, that code was used as an argument for a larger line length, but i don't think it makes that case at all. A few functions won't have to split lines, but some still will. The line splitting doesn't cause readability issues, it's general sloppiness and inconsistency which does that.

I can't work with one of my code windows right against the screen edge like in your screenshot. I work like rubenwardy with the primary code window a little more central.

For documentation text files narrow is useful, as documentation is quite likely to be opened alongside a game window or share the screen with several other windows.

**Comment by hecktest** [comment]
The code is ugly and the files are huge. I'd welcome some cleanup.
+1 for extra columns, 100 should be comfortable on 1920x1080 even with vertical split and some side panel. I still recommend extra displays to anyone serious about coding.
Github's web interface should not be an argument in this.

_Wardy, do you really need such big margins?_

**Comment by paramat** [comment]
Yes, i agree about not being concerned about GitHub display issues, i over-emphasised that, sorry.

I have a 1920x1080 display and have just set my editor to display a line at 100 columns. This pushes 2 windows to the edges of the screen, which i find very uncomfortable visually for the left (primary) window due to having little margin. I need about 2 inches of margin.
My font is small enough, making it smaller would bring me closer to the screen whihc is bad for the eyes.
90 seems about right and is already our long-stated limit, i support removing any mention of 80.
I've already set my editor to display a line at 90 columns and am now working with that instead of 80.

I'm serious about coding but like many people don't have the money or the space for 2 displays, That cannot be a requirement for coding as it would exclude so many people, especially MT users who tend to have little money anyway (it's a free game).

**Comment by nerzhul** [comment]
I Agree with 100 columns, 90 is quite short as C++ is a little bit verbose language.
If okay we should increase the clang-format rule in the repository and re-run clang-format on all files which are checked by it

**Comment by nerzhul** [comment]
Many historical parts are ugly but not easy to rewrite, generally i do some refactors but it's not easy because some part are too linked. I started more code refactoring in  5.0.0 but it's a long term goal

**Comment by JosiahWI** [comment]
The topic of this issue is of significant importance, because a bad architecture will give developers a bad experience, slow them down, and ultimately lead to difficulty adding new features at all. How many times have you looked at a project and said to yourself "bleh, adding the feature I want would require way more work than makes sense!" Line length and editor width is to architecture like wallpaper is to building design. You can get away with bland wallpaper, but if you mess up the architecture it can collapse and potentially kill all the occupants. I think Minetest's architecture is a really good point of discussion that's currently undervalued. What are the real architectural limitations right now, and which ones are highest priority to improve?

**Comment by JosiahWI** [comment]
I tried compiling voxel.cpp and its dependencies as a static library, to find out how tightly the common engine-like code is coupled to the specific client and server implementations. I quickly unearthed something strange: the node and item definitions both depend on the client tile class... and that depends (indirectly, most likely, I did not check) on the node and item headers. This seems like an odd design, and it seems like the tile should be an interface implemented by the client. This may be naive thinking, because I don't have a lot of knowledge or experience on the subject matter.
