### ISSUE TITLE
Star glitch

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#7905]
##### Issue type

 - Bug report
 
##### Minetest version

```
0.5.0-dev
```

##### Summary

Stars show up too early for how dark they are
![screenshot_20181127_135935](https://user-images.githubusercontent.com/33675971/49114474-23185180-f24d-11e8-83f8-b832fddc9492.png)

##### Steps to reproduce

- Type `/time 19:00`
- Look towards the sunset

**Comment by paramat** [comment]
With shaders on, stars appear just after time 19150, with shaders off, just after 19250. Shaders affect the sky brightness at a particular time.

The 'directional coloured fog' effect makes dark stars much more noticeable because it brightens the sky so much. Both screenshots below are at time 19150, shaders on:

![screenshot_20181128_023913](https://user-images.githubusercontent.com/3686677/49125321-99519e00-f2b7-11e8-8bd4-71927ec19735.png)

![screenshot_20181128_024031](https://user-images.githubusercontent.com/3686677/49125329-9d7dbb80-f2b7-11e8-8990-8d78e8df494a.png)

A dark star is seen in the sunset glow in both.
It's possible that stars turn on when their brightness equals that of the sky so that turning on isn't noticeable. In which case these dark stars may be unavoidable.
I'll investigate.

**Comment by paramat** [comment]
Anyway i agree stars appear a little too early, halfway through sunset, i can tune this to be later.

**Comment by paramat** [comment]
Stars reach full brightness at 20275 (shaders off).

**Comment by paramat** [comment]
PR #7921
