### ISSUE TITLE
Support for Mesh Animations in Mesh Nodes

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#7930]
##### Issue type

 - Feature
It is possible currently only for entities. But could you make it for mesh nodes to which an animation is attached in Blender?

**Comment by Andrey2470T** [comment]
Hmm... what decision for this issue? Core devs, are you going to add this support for 5.0.0?

**Comment by paramat** [comment]
Unlikely, we're nearing feature freeze for 5.0.0 release.

**Comment by ExeVirus** [comment]
Has then been reconsidered by core devs recently? 

Is it a relatively simple change of taking the entity code and transferring it to node code?

**Comment by paramat** [comment]
Seems a reasonable request so i will mark it as supported. Not high priority though.

**Comment by rubenwardy** [comment]
Note that this is currently possible using entities

**Comment by paramat** [comment]
Good point, i am removing my support then. It is a reasonable request but seems low priority.
So also, no core dev support for a year so closing.

**Comment by ExeVirus** [comment]
True, but entities have a lot more overhead, and don't exactly have crafting recipes. Windmills, Circus rides, anything that spins really, would benefit from being a node, rather than an entity. 

And I will gladly take up this project.

**Comment by Andrey2470T** [comment]
I think it should be added as it decreases efforts to make animations for nodes. You`d need to make it exactly the same as it is done for entities, _without_ a need to add additional faces in Blender, then additional range of textures to overlay each one on corresponding faces. Doesnt it?

**Comment by rubenwardy** [comment]
> but entities have a lot more overhead, 

So will animated meshes on the client-side

> and don't exactly have crafting recipes. Windmills, Circus rides, anything that spins really, would benefit from being a node, rather than an entity.

You can place an entity when placing a node. This has been done in the past for [windmills](https://content.minetest.net/packages/Sokomine/windmill/) and [various other things](https://github.com/CERN/CTW/blob/develop/mods/reseau/experiments.lua#L76)

**Comment by ExeVirus** [comment]
True, and that might end up being the route I take with this, as it keeps clutter out of the codebase. 

Is there already way to do a degenerate entity that has (essentially) no processing and is just there for animation? (in other words, can we turn off callbacks to reduce the performance hit server-side?)

**Comment by ExeVirus** [comment]
Issue #6963 had a similar request and currently has core dev (Paramat) support, and would solve this issue.

**Comment by AbbyRead** [comment]
I know this is years after the fact, but bear with me.  I came across this when looking for how to do the thing and wanted to save anyone else the trouble if they end up doing the same.
> You can place an entity when placing a node. This has been done in the past for [windmills](https://content.minetest.net/packages/Sokomine/windmill/) 

I was trying to do this in my game, so I looked at the windmill code, but it just uses an animated texture, scaled up, and drawtype=signlike.  So they worked around the lack in a different way than entity spawning here.

> and [various other things](https://github.com/CERN/CTW/blob/develop/mods/reseau/experiments.lua#L76)

This might be a good lead, but it doesn't seem to be maintained or have a whole lot of documentation.  Loading in has a lot of unsatisfied requirements and a bunch of satisfied with errors indications.  So I'm guessing it might have been some actual class curriculum that didn't get shared.  Which is a shame because this sounds really cool.

But yeah, anyway.  In case anyone else is looking for such an example, it seems like this is the source code that does the entity spawn on node creation:
https://github.com/CERN/CTW/blob/develop/mods/ctw/reseau/experiments.lua
https://github.com/CERN/CTW/blob/develop/mods/ctw/npc/api.lua

That codebase is massive compared to the windmill mod.
