### ISSUE TITLE
Inclusion of the languages "pt" and "pt_BR"

### ISSUE THREAD

**Issue by Lunovox** [minetest/minetest#7944]
Please add the translations below:

* https://hosted.weblate.org/projects/minetest/minetest/pt/
* https://hosted.weblate.org/projects/minetest/minetest/pt_BR/

If you can not download the files, I can send them by email, or otherwise.

Thank you! =)

**Comment by SmallJoker** [comment]
All language files will be updated before the next release happens.

**Comment by Lunovox** [comment]
> All language files will be updated before the next release happens.

So, do I need to do something else to add the "pt" and "pt_BR" languages on the next release?

**Comment by SmallJoker** [comment]
The language files are already included, see here: https://github.com/minetest/minetest/tree/master/po
However, many translations are yet not available because the update script wasn't yet run to provide the new material to the translators.
If you only have an English interface, check whether your client was built with gettext.
