### ISSUE TITLE
Node sound service locator

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#7972]
Currently you need to depend on default to use sounds from it. This is unnecessary, as it you don't need anything that special from default - just the sound. I'd like an API to allow decoupling of mods that only need sounds.

Not sure how this can be designed, the basic premise is to allow default to register item sounds with a number of names, and then another mod to ask for a node sound matching one of a list of names. This is similar to the `font-family` API in CSS.

Example:

```lua
minetest.register_item_sound({
	names = { "" },
	sound = {
		dug = {name = "default_dug_node", gain = 0.25},
		place = {name = "default_place_node_hard", gain = 1.0},
	},
})

minetest.register_item_sound({
	names = { "stone", "brick", "hard" },
	sound = {
		footstep = {name = "default_place_node_hard", gain = 1.0},
		dug   = {name = "default_hard_footstep", gain = 0.25},
		place = {name = "default_place_node_hard", gain = 1.0},
	},
})

-- ---- ---

sounds = minetest.find_item_sound({ "obsidian", "brick", "stone" }),
```

**Comment by jastevenson303** [comment]
Odd.

Those functions exist, from what I can tell, to easily fill node def parameter `sounds'.  If you do sounds = minetest.find_item_sound({"obsidian", "brick", "stone"}), then which is it that's supposed to be filling the value?

These are the node def sound values: footstep, dig, dug, place, and place_failed.  These are played in the engine and are not accessible from Lua.  Those five sounds values are filled with SimpleSoundSpecs, which consist of, basically, a name.  Now, they permit the gain parameter, but so do Sound Parameter Tables.  The docs say, I believe, that SimpleSoundSpecs also allow for pitch, but I believe that either is not the case, or not from the engine at least.  That's an aside, though.

So whatever's implemented, I think it makes sense to register the sounds like you've done here, and just to get a nice table out that fits in a node def with the 1-5 soundspecs.

**Comment by rubenwardy** [comment]
This is possible with tighter integration into minetest, with sounds being resolved at the end of load time

**Comment by paramat** [comment]
> Currently you need to depend on default to use sounds from it.

I am a little concerned that this proposed feature might be partly justified by the poor mod structure of MTGame. I feel that just one poorly structured game should not be used as justification for a complex engine feature, because the problem is in the game, not in the engine.
I oppose adding engine features to compensate for the poor design of MTG, this will encourage and perpetuate the focus on MTG. The best thing for the MT project is for people to consider MTG a mess to run screaming from.
MTG is feature-frozen now and will become increasingly unimportant (hopefully). New games will have better mod structure.
So, ignoring MTG, is there still significant need or usefulness for this?

However, ignoring MTG, i still do not see any justification.
I cannot currently see the problem with the current behaviour. If you want to use media, you have to depend on the mod that contains that media. This is expected and just how MT works.
I am uncomfortable with how this considers sounds as more important than any other media, or functions, they are not (but i am certainly not suggesting it is done for all media and functions, i cannot see justification for doing this for anything).
> This is unnecessary, as it you don't need anything that special from default - just the sound.

Well ... it is necessary because you do need something special from default, the sound =) The logic here seems very odd.
Why would a sound be considered something of no significance different from everything else in a mod? If you need a texture you depend on the mod that contains it, if you need a function you depend on the mod that contains it, etc. And there is no problem with this.

"Currently you need to depend on default to use sounds from it.": If the modder is writing a mod for MTG or a game derived from MTG (that probably contains default and the desired sounds) there is no problem because the mod would probably depend on default anyway, and there is no harm in depending on default.
I cannot see the usecase where you see a problem.

**Comment by rubenwardy** [comment]
This problem is independent from Minetest Game's design, it's about making multi-game support easier
