### ISSUE TITLE
Add visual & sound effect when nodes are construced or dug in multiplayer

### ISSUE THREAD

**Issue by ne-vlezay80** [minetest/minetest#7996]
Предлагаю реализовать возможность, когда соседний игрок будет слышать и видить, как разрушаются блоки(ноды). Дело в том, что другие игроки не видят, как разаушаются ноды, они вилят только то, что нода просто исчезла или появилась. Это увиличивает монёвра для грифиров и для подстав других играков.

EDIT by SmallJoker: (translated by computer) This issue is a feature request to have a visual and sound feedback when nodes destroyed by other players.

**Comment by jastevenson303** [comment]
```
minetest.register_on_dignode(function(pos)
  minetest.sound_play("dig", {pos = pos})
  minetest.spawn_particlespawner(pos, {idk particles})
end)
```

Footstep sounds are played in the engine and are heard by all players.  Dig and place sounds are also in the engine but aren't heard by other players(?).  I don't know about particles.

Whether the footstep sounds are played at all is a property of the ObjectRef.

**Comment by paramat** [comment]
The audio feedback is for the placer/digger. Audio feedback from other players placing/digging would be a little confusing and create a lot of noise, possibly rather irritating.
Visual feedback of dig progress is for the digger only, seeing the dig progress of other players is unnecessary.
Other problems:
Feedback of other player's actions is subject to network lag so may be out of sync. Local feedback is simple and instant because it is local.
The crack animation on nodes updates the mesh for a whole mapblock, which is a significant load on the client, if this happened for all players mesh updates would become far more frequent.
:-1:

**Comment by nerzhul** [comment]
@paramat we already have animation feedback, and no this will not be laggy. on any MMO you have feedback from combat actions for other players.
The animation is not to be laggy and can be done, the sound too, but should be affected by distance (short distance).

**Comment by SmallJoker** [comment]
Player textures are brightened on damage, so I think it would make sense to also add effects for nodes which are being dug. I generally like this request, although I'm also a bit worried about the mapblock mesh updates on crowded servers.

**Comment by paramat** [comment]
Ok i was unsure about lag, corrected.
My other points are the more important, and mesh updates are too intensive to do this. Mesh updates caused by the player's own digging are already an issue. There's no need to see dig progress of other players, seeing the node disappear is good enough.

If we do anything here i think sounds are a better idea, no mesh update, more lightweight.

**Comment by jastevenson303** [comment]
It will be of a lesser amplitude, as their position will be far from you.  And of course it all depends on this max_hear_distance business, with its strange volume ramping curve.

**Comment by Fixer-007** [comment]
>Mesh updates caused by the player's own crack animation are already fairly intensive. 

Why not do it via particles?

**Comment by An0n3m0us** [comment]
I'm pretty sure sound feedback for other players will have to be added from the engine;
I tried in mtg and all I could get to work is the sound when a player places or has *dug* a block; not the sound while digging. And along with that I had to prevent the 'local' sound of 'place' and 'dug' from playing; so it's kinda hacky but it works perfectly.

After that I decided to check how the footsteps sound is broadcast to all of the players; I think it's on line *994* in `content_cao.cpp` which is in `src/client`.

I found it in the engine and tried to do replicate the same format for the digging and placing sounds, but since I've no experience with C++, ended up nowhere.
I'd love to try and 'help' another user who is proficient in C++ so we can solve the sound issue.

**Comment by paramat** [comment]
The request is for other players to see/hear something on node 'dug', not during digging which i feel is overkill, and would be network-intensive considering how much digging occurs.

I suspect digging sounds would be more difficult to implement, as digging is even more a clientside thing. Whereas a 'dug' node is predicted in the client, then the node destruction is confirmed by the server and map updates sent to other players, which is where the 'dug' sound would be sent to them too.

Not included in this request but implied (and added to the title) is other players also hearing a node 'place' sound.
>  (translated by computer) This issue is a feature request to have a visual and sound feedback when nodes destroyed by other players.

Actually, taking the wording literally, the visual side of this already happens, when a node is destroyed it disappears for other players, that is the feedback =)
Adding a burst of particles on node destruction may be a problem as particles are still intensive to render
I would be ok with sounds on node 'dug' and 'place', but not visuals.

**Comment by An0n3m0us** [comment]
Well, the way my code works is simple but I don't think you would like it xD. Here's how it works:

builtin/register.lua
```diff
function core.register_node(name, nodedef)
	nodedef.type = "node"

+        if nodedef.sounds and nodedef.sounds.name then
+            nodedef.on_construct = function(pos)
+                node = node or minetest.get_node(pos)
+                minetest.sound_play(nodedef.sounds.name.place,
+			        {pos = pos, max_hear_distance = 8})
+            end
+
+            nodedef.on_destruct = function(pos)
+                node = node or minetest.get_node(pos)
+                minetest.sound_play(nodedef.sounds.name.dug,
+			        {pos = pos, max_hear_distance = 8})
+            end
+        end

	core.register_item(name, nodedef)
end
```

So register.lua first checks if the 'new' sounds format variable is defined (so that otherwise it falls back to the normal type). Then it just plays the correct sounds when on_construct and on_destruct are called.

And then:

nodes.lua
```diff
minetest.register_node("default:stone", {
	description = S("Stone"),
	tiles = {"default_stone.png"},
	groups = {cracky = 3, stone = 1},
	drop = "default:cobble",
	legacy_mineral = true,
-       sounds = default.node_sound_stone_defaults(),
+       sounds = default.node_sound_stone_defaults({
+           name = default.node_sound_stone_defaults(),
+           place = {},
+           dug = {}
+	}),
})
```

The dug and place in the sounds are set to nothing so that they don't play for the local user; instead they are played for all of the players in register.lua

**Comment by sfan5** [comment]
> I suspect digging sounds would be more difficult to implement, as digging is even more a clientside thing.

The client notifies the server about starting/stopping the digging, this is also used for anticheat.
So this is certainly possible. The question remains whether you _really_ want to send every punch to all clients nearby.

**Comment by An0n3m0us** [comment]
Yeah; I think every punch is a bit too much. 'Dug' and placing will be enough for now, then we can add digging later if needed.

**Comment by An0n3m0us** [comment]
Do you mind if it isn't done in the engine and in mtg instead? I tried for 3 days and I couldn't manage anything, but I did manage to do it in mtg with not much code.

**Comment by paramat** [comment]
This really should be done in C++ in the engine, not in builtin or in games.
