### ISSUE TITLE
Selection/collisionboxes of entities attached to entities not functional further than 200 nodes from (0,0,0)

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8037]
Tested in singleplayer, at commit a5197eaebc61ac6b555a640f36c0b427faef381d

Below, the highest entity is attached to the middle entity, which is attached to the lowest entity.
The lowest (parent) entity is placed where the player spawns.

![screenshot_20181231_052440](https://user-images.githubusercontent.com/3686677/50555000-4b1c2a00-0cbd-11e9-9a0a-5d880434639c.png)

^ Using `static_spawnpoint = 0,10,0` or  `static_spawnpoint = 199,10,0` in mgflat. All 3 selectionboxes are visible

![screenshot_20181231_053020](https://user-images.githubusercontent.com/3686677/50555007-6d15ac80-0cbd-11e9-91d0-3e7c3c37ad02.png)

^ Using `static_spawnpoint = 201,10,0` in mgflat. Only the parent entity selectionbox is visible

The 200 value suggests this is related to camera offset that is applied every 200 nodes:
https://github.com/minetest/minetest/blob/c6f784f43bca3328c6810c26c8bda2ea507c70e8/src/client/camera.cpp#L432
https://github.com/minetest/minetest/blob/c6f784f43bca3328c6810c26c8bda2ea507c70e8/src/client/camera.cpp#L39

Seems confirmed. If the player spawns at (199,10,0) there is no bug.
Then if the player crosses x = 200 the bug occurs.
Crossing back over x = 200 doesn't fix the bug because camera offset only resets to (0,0,0) once you pass back over x = 0.

Test code:
```
minetest.register_entity("lab:cube", {
	initial_properties = {
		physical = false,
		collide_with_objects = false,
		collisionbox = {-1, -1, -1, 1, 1, 1},
		selectionbox = {-1, -1, -1, 1, 1, 1},
		visual = "cube",
		textures = {
			"lab_no_texture.png",
			"lab_no_texture.png",
			"lab_no_texture.png",
			"lab_no_texture.png",
			"lab_no_texture.png",
			"lab_no_texture.png",
		},
		pointable = true,
	},
})

minetest.after(5, function()
	local pos = minetest.get_player_by_name("singleplayer"):get_pos()
	local ent1 = minetest.add_entity(pos, "lab:cube")
	local ent2 = minetest.add_entity(pos, "lab:cube")
	local ent3 = minetest.add_entity(pos, "lab:cube")
	minetest.after(1, function()
		ent1:set_attach(ent2, "", {x = 0, y = 20, z = 20}, {x = 0, y = 0, z = 0})
		ent2:set_attach(ent3, "", {x = 0, y = 20, z = 20}, {x = 0, y = 0, z = 0})
	end)
end)
```
I'm surprised this hasn't been reported already.
@GreenXenith you seem to be the person who first reported this, do you know if this is a newly-occuring bug?

**Comment by paramat** [comment]
Another weird thing discovered, possibly a separate bug.
While testing, if i fly out of range (48 nodes) so that the objects are removed from view, then return, only the parent object remains.

**Comment by GreenXenith** [comment]
This exists in 0.4.17.x (and earlier I would assume - haven't tested) so it is not really "new", no.
Also affects collisionboxes, not just selectionboxes.
>  then return, only the parent object remains.

Hm. I've always seen this as expected behavior and made my mod handle it anyway.

**Comment by paramat** [comment]
Seems related to #5013 , camera offset and distance from (0,0,0) is mentioned there.

**Comment by paramat** [comment]
Not a high priority bug as i'm not sure our code is meant to cope with entities attached to entities.

**Comment by SmallJoker** [comment]
I did some testing about this issue because an accidental misbehaviour of the camera changes fixed this issue. My conclusions so far were that Minetest and Irrlicht seem to get out of sync. The SceneNode is shown at another location than Minetest thinks where the selection/collision boxes are.
One of the relevant code parts can be found here: (Irrlicht should and does update the attachments automatically)
https://github.com/minetest/minetest/blob/c6f784f43bca3328c6810c26c8bda2ea507c70e8/src/client/content_cao.cpp#L763-L778

**Comment by v-rob** [comment]
I have encountered this bug, and I have detail to add.  Once the selection box of the entity disappears, it will not reappear until you move to `(0,0,0)` again.  For instance, if you make an entity at `(200,0,200)` and then make another at `(150,0,150)`, the latter's selection box will not appear until you move back to `(0,0,0)`

I hope this bug gets fixed because it devastates a certain mod I'm working on.
