### ISSUE TITLE
Need for mapgen_lua.cpp as a mapgen option or some other protection.

### ISSUE THREAD

**Issue by oiaohm** [minetest/minetest#8040]
##### Issue type
 - Bug report
 
##### Minetest version
0.4.17.1

##### OS / Hardware
Linux Debian
CPU:
##### Summary
I have run into a intermittent problem with skyblock mod. Where due to high IO load I can at times enter and die before the skyblock mod map gen has completed.

This is when I notice following
1)No option that I can see when creating map to say there is expected to be a lua mapgen.
2)No auto deplaying for lua mapgen.   Deplay option is no players can enter server/area until the lua mapgen says it finished in the area

Issue 1 results in you being able to enter game by mistake when you have failed to select the lua mapgen this would be better if the game server error with lua mod mapgen missing.

Issue 2 results in me at times being able to enter the server before the lua map gen is 100 percent ready and fall to death in skyblock mod while watching the skyblock island appear above me.

This could be that mapgen_lua.cpp gets added next to the likes of mapgen_v6, v7.... So that lua map gens are not second interfaces. You could even allow the lua mapgen to use multi mapgen cpp modules in different areas of the map so a map that is in fact a mix of mapgen v6/v7, valleys... with how that layout is decided by the lua.

This could be used to solve the other problem of different Lua mapgens only working with particular mapgen versions as making a  mapgen_lua.cpp puts the lua script for mapgen in charge of what other mapgens it works with.

##### Steps to reproduce
Problem 1 is straight forwards
You are going into skyblock you fail mod on the world has generated.   If you turn the skyblock mod late its not going give you skyblock so you have to delete the world and start over.   It would be simpler if there was some flag that say new world need lua mapgen and if lua mapgen cannot be found because user made mistake like not activating right mods error.. 

Problem2.   The steps to repoduce to not exactly straight forwards:

minetest + skyblock mod.   have high IO load set world as quite deep.  Watch island form in above you as you fall to death.   Because you entered server before floating island was formed. 

The lua mapgen stuff need to be properly linked to the normal mapgen.

**Comment by SmallJoker** [comment]
Mapblocks are sent to players when the generation (including the `on_generate` callback) has finished. While generating, the player will collide with the not sent mapblock - stopping its movement.
How you described the issue, it appears to me that the skyblock game uses `set_node` instead of the generation callback. Nodes will appear after the mapblock has been sent; the client will fall down until that happens.

I think you should file an issue in the skyblocks mod.

**Comment by paramat** [comment]
> Mapblocks are sent to players when the generation (including the on_generate callback) has finished.

Yes.
The skyblock mod should generate the world in a 'on generated' function of the first mapchunk generated, this means world generation will finish before any player is spawned.
Which skyblock mod? How does it generate the world? Does it load the world as a schematic?
> 2)No auto deplaying for lua mapgen. Deplay option is no players can enter server/area until the lua mapgen says it finished in the area

So this already happens for Lua mapgens, any problem is caused by the skyblock mod, contact the author. There are several ways this 'player falling before generation' problem can be solved in Lua.

> 1)No option that I can see when creating map to say there is expected to be a lua mapgen.

It's the user's responsibility to enable the Lua mapgen mod before using singlenode mapgen. It can't be forced because many users use singlenode without a Lua mapgen.
