### ISSUE TITLE
Confusing and problematic Android app versioning, should be 0.4.17.1-something, not 0.4.17.3

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8072]
Please can we rename the apk in the releases page 'assets' section to 0.4.17.1-3 or something similar, and please can we refer to the app version as that?

The use of 0.4.17.2 was a mistake that has caused a lot of confusion and problems. I know this may not be obvious to other devs but other devs haven't attended to the issues and confusion caused over the last few months because they haven't had time to, or have been absent. It's been a nightmare and a headache, so please trust me on this. I warned months ago that this would cause confusion.
MT 0.4.17.2 or 0.4.17.3 would be full releases, but they don't exist and never will.

To avoid further confusion i suggest these rules for Android versioning, based on what we are already doing that makes sense:
* Android-only point releases are versioned as a sub-version of the previous full MT release (currently 0.4.17.1), so would be 0.4.17.1-3 or similar. This is obvious, 0.4.17.3 can only be a full MT release.
* Any Android-only release assets are placed in the 'assets' section of the previous full MT release on the 'releases' page.
* On the playstore page the version will be stated matching our official versioning. However i realise that 0.4.17.22 is currently used for various reasons so it's possible 0.4.17.1-3 or similar doesn't need to be stated on the playstore at all.

**Comment by nerzhul** [comment]
This issue is to close. I cannot set 0.4.17.1-3 on the play store it's 0.4.17.3 instead (and in reality it's 0.4.17.22 in the apk, 22 is the android version code)

In next 5.x.y series we will not have a such -thing. On each stable-5.x we will have a new tag on each android release to prevent a such crazy thing. Semver will have a patch and permit to definitively fix that problem :)
If we release for android after 5.0.0 it will just be 5.0.1.

**Comment by SmallJoker** [comment]
This issue won't arise again in future releases. It's surely not an optimal version naming but the Android release happened, so it's the easiest and west way to just keep it as-is.
