### ISSUE TITLE
Add register_on_pointed_thing callback

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#8103]
##### Issue type
 - Feature request

##### Minetest version
```
5.1.0
```

Both callbacks are necessary! Please add these in 5.1.0!

**Comment by ClobberXD** [comment]
Assuming you want callbacks to be run when changing the wielditem, see #7587

**Comment by nerzhul** [comment]
the on_point_thing is a little bit tricky. What is your use case ?

**Comment by paramat** [comment]
Both requests are very vague, what do you mean?

**Comment by Andrey2470T** [comment]
paramat, i requested to add register_on_point_thing and register_on_wield_item callbacks. I don`t know what you don`t understand here: first callback will be called constantly because any player constantly "point" to anything in-world. Second one will be called when player will wield any item.

**Comment by ClobberXD** [comment]
You seriously want a server-side callback that runs every time a player points at something? o_O

**Comment by paramat** [comment]
You need to explain the exact situation and the event which triggers each callback.

A callback cannot happen constantly, it can only happen on an instantaneous event, so i guess you mean each time the player's pointing selection moves from one node to another? It would then be 'register on pointed thing change'. 'point thing' is not used in MT.
This would cause very rapid callbacks. If you explain what you need this for it's likely a better way already exists.

A callback cannot happen when wielding an item, it can only happen on an event such as changing the wielditem, there's a PR for that.

**Comment by Andrey2470T** [comment]
Yes, i mean register_on_pointed_thing will be called when player changes node`s selection. Maybe it is not needed. Second callback will be called when player changes wielded item. I don`t know what it`s needed for currently, either.

**Comment by SmallJoker** [comment]
Changed title since #1377 already includes later request.

**Comment by sorcerykid** [comment]
I believe the callback for changing wielded item (per PR #7587) would be quite easy to implement, and I really hope to see that happen. But as for this suggestion, I too have serious doubts whether it's worth the additional overhead, even though there are legitimate use-cases.

Perhaps a better implementation would be to add on_pointed_at( ) callbacks for entities and nodes that can receive notifications only when a player first points at them (this way messages aren't being sent continuously). However, this still isn't as ideal for inspection tools.

Another possible implementation would be to add an on_pointing_to( ) callback for craftitems that is called whenever the wielded item is pointing to a different entity or node (once again to avoid a continous stream of messages). This has the benefit that it should work very efficiently, since 99.9% of the time a player would not be wielding such an item. Likewise it would be very easy for the client to maintain a state table to determine whenever the pointed_thing changes, and then to send a single message to the server.

**Comment by paramat** [comment]
:-1: because i feel it's probably best to get the pointed thing when you need it, not every time the crosshair crosses a node (which will be rapid and intensive). Also there isn't any specified need for this or explanation why it can't be done another way.

**Comment by sorcerykid** [comment]
I'm going to have to respectfully disagree. Clients already send movement messages continuously as a player's yaw or position changes. Yet somehow that isn't deemed "too intensive" for servers to handle.

Also, as I pointed out in my suggestion above, the pointed_thing information would only be sent when the player is wielding an item that the server requests an updated pos, and only when that pos changes, and only within the selection range of the tool (and all of this being computed by the client ahead of time). That means that the frequency of packets would be trivial in comparison to that of movement.

As for potential use cases, what about automatic actuation of entities and nodes in world, just by looking at them with a specific tool? That would make the game far more interactive than the current situation where players are required to manually click everything (or press one of two keys, both of which are bound to multiple actions already). Or imagine a sign mod, that opens a formspec showing the full text if a player points at it for more than 1 second.  This could even be extended to mobs that turn hostile when a player is pointing at them with a weapon. The possibilities are endless.
