### ISSUE TITLE
LVM sometimes refuses to replace air in caves

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8152]
##### Issue type
 - Bug report
 
##### Minetest version
```
944e9f5acbac8971643553eb6e351abe362c4c17
```
and 0.4.17.1, too.

##### Summary
I suspect (!) a bug in the LVM. The bug (if my suspiciou is true) is that sometimes, the LVM fails to generate in certain mapblocks. Detailed description below.

##### Evidence

The following minimal mod is supposed to replace all air below Y=-52 with lava.
At mapblock boundaries, also steel block and mossy cobble is used instead of lava, but this is only used to make mapblock boundaries visible. If you want, you can revert this to lava.

Use this mod in MTG or Minimal for testing.

```
local lavalayer = {}

lavalayer.layer = -52
local c_lava = minetest.get_content_id("default:lava_source")
local c_brick = minetest.get_content_id("default:brick")
local c_steelblock = minetest.get_content_id("default:steelblock")
local c_cobble = minetest.get_content_id("default:mossycobble")
local c_mese = minetest.get_content_id("default:mese")

minetest.register_on_generated(function(minp, maxp, blockseed)
	local vm, emin, emax = minetest.get_mapgen_object("voxelmanip")
	local data = vm:get_data()
	local area = VoxelArea:new({MinEdge=emin, MaxEdge=emax})
	local min, max = minp, maxp
	if min.y <= lavalayer.layer then
		for x = min.x, max.x do
			for z = min.z, max.z do
				for y = min.y, math.min(max.y, lavalayer.layer) do
					local p_pos = area:index(x, y, z)
					if data[p_pos] == minetest.CONTENT_AIR then
						if x == min.x or z == min.z then
							data[p_pos] = c_cobble
						elseif x == max.x or z == max.z then
							data[p_pos] = c_steelblock
						else
							data[p_pos] = c_lava
						end
					elseif data[p_pos] == c_lava then -- if node was lava  already for some reason, replace it with mese. If this happens, maybe the mapgen iterated over this mapblock twice?
						data[p_pos] = c_mese
					elseif data[p_pos] == nil then
						minetest.log("error", "NIL POS!: "..minetest.pos_to_string({x=x,y=y,z=z}))
					end
				end
			end
		end

		vm:set_data(data)
		vm:calc_lighting()
		vm:update_liquids()
		vm:write_to_map()
	end
end)
```

The problem: If you use this in v7, and use fly and noclip to explore a lot of caves at around Y=-52, sometimes, the LVM seems to ignore some mapblocks completely, leaving the caves untouched, and leaving the air alone.
I expect that caves that are at Y=-52 or below are NEVER having air, it must be either lava, steel block or brick. But sometimes, there's no lava, just air.

It needs a little trial-and-error to trigger the bug, just explore for a while near Y=-52 and generate enough mapblocks. The longer you explore, the higher the chance you eventually find an "air mapblock".

For comparison, if you use the same mod in singlenode, all seems to work fine, there is lava everywhere. This should be evidence that the problem lies not in the mod (I hope).

I have not tested this in other mapgens.

##### Screenshots
How it should look like at all mapblock bounds in caves at Y=-52:

https://ptpb.pw/qwzq.png

How it sometimes looks like, when generation fails:

https://ptpb.pw/bLvj.png

I'm not sure if the coordinates are reproducible. I suggest to just fly around in a random map and hope for the best.

##### Impact

In MineClone 2, all "cave air" that is generated below Y=-52 shall be replaced with lava, as a very simple mechanism to generate a flat “lava layer”. This problem causes lava generation to screw up sometimes.

The impact might be greater than that, because such a bug in LVM might cause hilarious bugs in games that are hard to explain.

**Comment by Ekdohibs** [comment]
If I remember correctly, the cave generation can run in adjacent mapblocks and carve air again in what was already placed. The same thing might happen with dungeons as well. I would be a lot more surprised if the bug were with LVM and not some map generation changing the map again.
A while ago, we already had the bug of caves carving into generated structures. It was fixed, but I don't remember if there was something that needed to be done on the Lua side or not.

**Comment by paramat** [comment]
Yes, the 'large mgv6 type sometimes flooded caves' generate beyond the mapchunk borders by up to 1 mapblock, just like dungeons do, so your mod must process the whole 7x7x7 mapchunk volume.
Try:
`local min, max = emin, emax`
I hope that works.

**Comment by Wuzzy2** [comment]
Yes, it seems to work. But are you really sure about the solution?

Because that seems inefficient, as this will make the algorithm iterate over many nodes twice. :( This doesn't seem right.

Should I consider it an official recommendation to iterate over `emin,emax` instead of `minp,maxp` when doing anything with VoxelManip? If yes, might consider to write that down in the docs.

It seems a bit paradoxical to me that it is required to touch nodes *outside* of an `on_generated` area. Are you sure this is safe and not a possible danger to destroy parts of the map?

**Comment by paramat** [comment]
Yes sure. It's necessary to iterate over the overlaps twice, because caves are generated twice in the overlaps.

I guess you could possibly use the 'gennotify' data for 'large caves' to judge where the overgeneration occured and process outside the mapchunk only in certain places. But this might be difficult, the 'gennotify' data doesn't contain data on the size of caves, just start and end points of cave centres, so you would never be totally sure and it may take some tuning.

Personally seems too much headache to be worth it.
> Should I consider it an official recommendation to iterate over emin,emax instead of minp,maxp when doing anything with VoxelManip?

No, only when dealing with structures that 'overgenerate': The mid-sized sometimes flooded caves, and dungeons.
> touch nodes outside of an on_generated area.

Strictly speaking nothing is touched outside, the volume of the 'mapgen object voxelmanip' is from emin to emax, and is the mapchunk plus a 1 mapblock thick shell around it.
The engine's own voxelmanip used during mapgen is also this exact volume.

It may seem dangerous, that a build may be griefed, but consider that if a player is in a mapchunk, the 'max block generate distance' ensures that all neighbour mapchunks are generated too. So no player build can be griefed by overgeneration.

However, structures placed in 'on generated' can be griefed by overgeneration, which is why the mod nodes of structures placed in 'on generated' should all be 'is ground content = false' to avoid being eaten by overgenerating caves. So, 'default:stone' should not be placed, instead, a dummy stone node with 'is ground content = false' and which drops 'default:stone'.
