### ISSUE TITLE
Proposal: replace serverlist ping with geolocation hint

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#8163]
I'm going to skip over a ton of discussion here, feel free to add links or references to this topic.

Currently, the "ping debacle" hinges on the fact that nobody has come up with a client-side ping solution, and reasons for that are sensible, as this would likely mean that one has to do a UDP ping to many machines, from every client. This is not a good idea - it's a terrible idea, even. (imagine thousands of android clients mass-pinging servers).

From a cursory glance, however, it is evident that something that tells players that "a server is near me" provides value. Just as that "a server that is responsive" has value (represented by the current m_lag value, for instance, but that isn't what this is about).

It occurred to me that with the availability of geo-ip databases, the serverlist could easily perform a geoip lookup for each server and store its *country* information. This information provides not only a measure of responsiveness, it may even provide a measure of language and culture.

To implement, we'd have to:
1) modify the serverlist to lookup and cache country names through some geoip service. These appear free and plentyful, and with caching there should be zero issues using them.
2) modify the client to display (e.g.) a 2-letter country code instead of lag value.

There are variations that can be done here, including just adding the country to the list, sorting the list based on grouping by e.g. continent and other scoring things (in other words, sorting the list differently per client).

**Comment by Linuxdirk** [comment]
When getting the country from the IP using an external service it is important to make sure to do this in compliance with the GDPR otherwise Minetest would become illegal in the European Union.

Another solution would be server owners providing this information. This might cause a protocol update due to another value that has to be transferred.

**Comment by sfan5** [comment]
There is no need for an external service to geolocate IP addresses, several downloadable databases exist that provide the same functionality.

**Comment by sofar** [comment]
@linuxdirk I'll leave it to you to validate the implementation, you seem to enjoy these sorts of things. 

Note, the serverlist doesn't (and won't, I think) collect data of players (where an IP address may be personal data). It does of servers (where the IP address is arguably not personal data, since the server is registered, not a person).

Please don't write threats like "you will get minetest banned in europe". That's a hostile way of contributing to minetest. There are far more polite and constructive ways of dealing with concerns, and I'm open to them permitted you don't play into emotional feelings by using extreme language like that.

@sfan5 right, that's likely an easy way

**Comment by Linuxdirk** [comment]
> I'll leave it to you to validate the implementation, you seem to enjoy these sorts of things.

Actually yes, but only sometimes and only a little.

> Please don't write threats like "you will get minetest banned in europe".

Read carefully what I wrote. I never wrote "you will get minetest banned in europe" I just mentioned that Minetest would become illegal in the European Union if personal user data is processed and forwarded without getting consent of the user beforehand. This is nothing I made up. This is a fact based on the EU-wide directives (namely the GDPR).

> I'm open to them permitted you don't play into emotional feelings by using extreme language like that.

Emotions have nothing to do with code and software development. Plus: "Extreme language" is the most effective and straightforward thing to use when it's about code and software development. The only one always bringing emotions into this and causing drama is you.

**Comment by Ezhh** [comment]
I'd rather it not be country specific, because:

> it may even provide a measure of language and culture.

...would prove extremely misleading in some cases. My server is in France, but the official languages we support are english and german. I don't want people joining my server expecting french to get them far, because it won't, and if they try to leave me messages in french, they'll mostly be talking to themselves. 

So I think slightly broader ranges than specific country, at least within Europe, would be better. By continent could be a good approach.

**Comment by sofar** [comment]
https://github.com/minetest/master-server/pull/29

**Comment by sofar** [comment]
> So I think slightly broader ranges than specific country, at least within Europe, would be better. By continent could be a good approach.

Honestly from a `ping` perspective it is good enough, however I do feel that players will be able just fine to distinguish between servers that are hosted out of convenience in e.g. `.nl` may be any language, as the server name and description would provide these hints.

My goal isn't to exclusively promote `.fr` servers to players in `.fr`, but to group them together and provide them all nearby servers (for .fr, that would be most of west europe I guess) as servers that would be of equal scoring in the ranking on the client. In any case, more precise data would help with that. Especially for Asia, where distances can be huge: compare Azerbaijan with The philipines - both are in Asia, but the distance and ping between them is huge, and grouping by continent is really not appropriate there, but country grouping/scoring would potentially be.

**Comment by Ezhh** [comment]
Yes, Europe has a lot of closely grouped fairly small countries where knowing the precise country doesn't matter much, whereas it could easily be an appropriate scale to use elsewhere (why I added "at least within Europe"). The issue with Europe specifically is there's also a lot of different languages within all those relatively small countries (not unique to Europe, I know).

I have had issues with players who don't speak english before. I've also had no end of offers from people who want to translate rules and so on, which is helpful and kind of them, but I am not interested in running a server where people don't primarily communicate in a language I speak or can at least mostly follow. If they can manage the rules and manage to follow them, it's fine and tolerated, and they will even receive whatever help the team can give them, but it's not what the server is aimed at.

Due to such things, a lot is really going to depend on how it's presented; if my server gets displayed as a french server I'm going to get really annoyed. This is very different from displaying it as a server that is hosted in France, but even that might encourage french players to join and to some extent discourage others, which is why it would simply be better to list it as European, or whatever sub-division of European is decided on, rather than country specific.

**Comment by sofar** [comment]
> Due to such things, a lot is really going to depend on how it's presented; if my server gets displayed as a french server I'm going to get really annoyed

Please, do not panic.

I don't intend for such a thing to be implemented, as it clearly would be a misrepresentation of the server, and therefore objectionable.

My intent is that clients can choose a preferred region, and the serverlist sorts in a way that servers in the preferred region are given a scoring bonus and appear higher in the list.

A second intent is that clients can filter by region and remove servers from the list entirely that are not in that region.

Even if we'd implement sending the country code, the goal is to *sort* or *filter* the serverlist with hints about *nearby location* and not to change the description of the server or any other properties:

- A player in switzerland would see servers in france, italy and germany somewhere in the same location on the server list
- A player in ireland would generally see a servers in turkey below servers in belgium
- other sorting factors like player count and servers being full or having lots of guests would also still apply to the sorting order

Nothing in here suggests that servers in France are going to be portrayed as french, this is purely about making the serverlist sorting and display remove the need for the current "false ping" value, without having every client ping every server, which would be wasteful.

**Comment by Ezhh** [comment]
No panic here. I've just learned that not making a strong statement up front about such things can lead to a later accusation of "but no one complained", so now I don't want to take my chances.

I'm completely in favour of this so long as we skip the "it may even provide a measure of language and culture" in your first post.

**Comment by TurkeyMcMac** [comment]
I'll close this as the idea has now been implemented: https://github.com/minetest/minetest/pull/12790
