### ISSUE TITLE
[Menu] Weird bug with clouds on game background

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#8170]
##### Issue type
 - Bug report
 
##### Minetest version
```
Minetest 5.0.0-dev-0d0875fc
```

##### OS / Hardware
If needed let me know

##### Summary
![image](https://user-images.githubusercontent.com/28972859/52182081-2e887b80-27ae-11e9-8012-ac296f4eab33.png)

##### Steps to reproduce
It looks like this happens when there is transparency in a background?

**Comment by paramat** [comment]
Seems intentional, what else could be used as background in transparent areas?

**Comment by LoneWolfHT** [comment]
> Seems intentional

The clouds appear to 'burst' through the picture. They're at the wrong angle too.

> What else could be used as background in transparent areas?

I'm fine with the sky color. But the clouds look wrong.

![clouds](https://user-images.githubusercontent.com/28972859/52220191-29c9d300-2853-11e9-8401-9d4b56884b6b.gif)

**Comment by paramat** [comment]
The clouds are rendered as if the camera is pointing upwards slightly, so they can't be used with an image that uses a different camera angle, so they are not compatible with most landscape images.

The option of seeing animated clouds in transparent areas is intentional, many wouldn't like then being removed. If you want skycolor as a background then you would use that in an opaque image.

Animated clouds used as a background for a non-animated landscape scene looks weird and fake. Also, the cloud scene is usually not aligned with foreground nodes, not correctly scaled to them, and likely usually uses a different FOV to the foreground image.
So, i recommend not using animated clouds with a landscape foreground.

If the camera angle of the cloud scene is reduced then those clouds, and the lack of a visible ground, will look weird when a foreground landscape isn't used.

**Comment by LoneWolfHT** [comment]
I was thinking just disable the clouds when a game provides a custom background

**Comment by paramat** [comment]
Any game using a custom screen with transparency does so to display clouds and wants clouds.
If you disable the clouds you have a static blue sky, which can already be added to an image to create an opaque custom screen.

**Comment by LoneWolfHT** [comment]
Ok. Shall I close?

**Comment by jastevenson303** [comment]
Such a cool feature though; great idea to incorporate menu clouds into your
background image.
