### ISSUE TITLE
Item held from craftresult remains after die/respawn.

### ISSUE THREAD

**Issue by jastevenson303** [minetest/minetest#8186]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 5.0.0-dev-fc566e2e (Linux)
```

##### OS / Hardware

Operating system: Debian 9
CPU: Intel

GPU model: Intel
OpenGL version: 3.0

##### Summary

If you click on the `craftresult` item, and then die before placing it somewhere, the item is still held when you respawn.
##### Steps to reproduce

1. Place wood in your craft grid
2. Walk into some fire
3. Click the four sticks before your health is depleted
4. Respawn and open inventory, noting the four sticks still held

Video demonstration: https://www.youtube.com/watch?v=tjNO-3F-eSs

**Comment by blindley** [comment]
Some relevant observations.

When you pull a stack from most slots (like your inventory or a crafting grid), it seems to retain memory of the spot you pulled it from, and if you exit that gui, the stack goes back to that slot.

However, if you pull a stack from the crafting preview slot, then exit and re-enter the gui, the stack is still there on your cursor. I assume this is because it has no memory of where to go, since it can't go back to the crafting preview slot where it came from.

So, not having investigated the code, my guess would be that when you die holding a stack in a gui, the gui is exited as normal, so held stacks go back to your inventory if they were pulled from there, but they stay in limbo if pulled from the crafting preview. And the contents of this limbo area are not affected on death.

If I'm correct, then I would suggest instead of changing what happens when you die, change what happens to that held stack when you exit the gui. Perhaps follow Minecraft's lead and spit the stack onto the ground?

**Comment by ClobberXD** [comment]
Related: MT-CTF/capturetheflag#92 - Players were able to retain an item from craftpreview this way, and were able to place it back in their inventory after it was wiped clean at the start of a new match.

**Comment by SmallJoker** [comment]
Needs fixing in MTG: https://github.com/minetest/minetest_game/blob/master/mods/bones/init.lua#L167-L168
