### ISSUE TITLE
Breath statbar might show 10.5 bubbles for high breath values

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8210]
##### Issue type
 - Bug report
 
##### Minetest version
```
f5bdc04ab5b47bd094ba0ced5f086e8fe6b12298
```

##### Description
If you have a high breath value (>30), the breath statbar might show 10.5 bubbles.

##### How to repro

1. Obtain `luacmd`
2. Set your max. breath to 100 or another high value with /lua me:set_properties({breath_max=100})
3. Dive in water until the bubbles appear

There will be 10.5 bubbles shown.

**Comment by ClobberXD** [comment]
Here's the code that calculates the number of bubbles to be displayed:
https://github.com/minetest/minetest/blob/0ad96cc73f5498cf4ffe85afe1478066acfd377a/builtin/game/statbars.lua#L28-L35

This method is invoked every time the health/breath bar's value or max. is changed. I used some print statements, and realized that the returned value goes upto 11 only for the breath bar. This is because of a very simple reason - the constant `PLAYER_MAX_BREATH_DEFAULT` (assigned to the local `nominal`) is equal to 11 instead of 10 (!). This is probably to show all 10 bubbles while regaining breath before making the breath bar invisible. If that's the case, we could set `PLAYER_MAX_BREATH_DEFAULT` to 10, and then:

- Just leave everything else as it is - we'd only be able to see 9 bubbles before the bar vanishes.
- Make the breath bar permanently visible - we'd be able to all 10 bubbles forever. :)
- Use core.after to make the breath bar disappear after the 10th bubble has been displayed.

I'm willing to work on this, do let me know what is to be done here. :)

**Comment by jastevenson303** [comment]
personally i just hide the bubbles always and forever.  i intend also, and
this is an aside, to make player regain full or near-full breath once
exposed to air, like i did in dcbl.

nice to see hp and breath statbars being worked on, Thank You!

**Comment by Wuzzy2** [comment]
Yes, before the max. breath was changable, the value 11 had a special meaning in that it means “breath is full AND make breath bar invisible”. Also, 10 breath is already considered to be full breath, as far I know. The calculation obviously does not take that into account yet. I guess the calculation should not use `breath_max` in their calculation, but `breath_max-1`.
The docs about `breath_max` also should be more explicit about this special case as it's a potential tripwire.

Changing how the breath bar works in principle is off-topic and unrelated the bug report.

**Comment by paramat** [comment]
> If that's the case, we could set `PLAYER_MAX_BREATH_DEFAULT` to 10, and then:
Just leave everything else as it is - we'd only be able to see 9 bubbles before the bar vanishes.
Make the breath bar permanently visible - we'd be able to all 10 bubbles forever. :)
Use core.after to make the breath bar disappear after the 10th bubble has been displayed.

This seems good to me, the 11 thing is messy. Bubbles disappearing when 10 is fine with me, as is always seeing the bubbles (as they are inconsistent with hearts).
For simplicity i would prefer to avoid using 'after'.
