### ISSUE TITLE
When Autoforward is on, player:get_player_control() return only false on "aux1"

### ISSUE THREAD

**Issue by TillCoyote** [minetest/minetest#8247]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 5.0.0-dev-eea1fda-dirty (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Linux Mint 19
CPU: AMD A6

##### Summary

I have a mod, that turns player running when it holds both W and E buttons (up + aux1). With W everything is OK. I tryed to run with Autoforward key - it didn't work. The problem is in function player:get_player_control():

Input: I pressed the Autoforward key.
Expected output: player:get_player_control() returns a table, where "up" is **true**.
Actual output: player:get_player_control() returns a table, where "up" is still **false**, like I am not going forward right now.

##### Steps to reproduce

1. Register a globalstep with this:
`
minetest.log( minetest.serialize ( player:get_player_control() ) )
`

1. Start the game, and check that "up" is false in terminal.
2. Tap Autoforward key.
3. Check that "up" is still false in terminal and **nothing** has changed.

I wrote my best, sorry if not informative.

**Comment by SmallJoker** [comment]
Cannot reproduce your issue with the current HEAD.
Autoforward enabled, `E` released:
```
{
	right = false,
	aux1 = false,
	sneak = false,
	down = false,
	LMB = false,
	left = false,
	RMB = false,
	up = false,
	jump = false
}
```
Autoforward enabled, `E` pressed:
```
{
	right = false,
	aux1 = true,
	sneak = false,
	down = false,
	LMB = false,
	left = false,
	RMB = false,
	up = false,
	jump = false
}
```

Testing code:
```Lua
minetest.register_globalstep(function(dtime)
	for _, player in ipairs(minetest.get_connected_players()) do
		print(dump(player:get_player_control()))
	end
end)
```

**Comment by DS-Minetest** [comment]
Related: #7805 (This might be a worse problem for your sprint mod.)

In your steps to reproduce you did not write that the aux1 key is pressed by you. It's the expected behavior that `player:get_player_control().aux1` is `false` in this case.

Btw. pressing the up key makes you fast in autoforward mode, too.

> like I am not going forward right now.

You do know that the key up tells you whether you are moving forward, right? aux1 is the key that is E by default.

This issue might be a duplicate.

The meanings of the keys sadly aren't documented:
https://github.com/minetest/minetest/blob/00a22ec76ddd727a22088ecdb856f41aac241df5/doc/lua_api.txt#L5160

**Comment by TillCoyote** [comment]
@DS-Minetest I misunderstood that E is aux1 and W is up. I updated my post, thanks. When I press Autoforward, "up" in the table is still **false**.
