### ISSUE TITLE
Wrong wielditem scaling for different drawtypes

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#8281]
##### Issue type
 - Bug report
 
##### Minetest version
5.0.0-dev, since bb22567

##### Summary
> Noticed this when digging a tree, saplings and apples sit a few pixels below the ground, other items display fully about ground. It looks like nodes display correctly, and craft items are drawn a pixel too low.
> 
> ![screenshot_20190222_075022](https://user-images.githubusercontent.com/8930456/53246584-bc051000-3676-11e9-90e4-81321086ee07.png)
> 
> ![screenshot_20190222_075422](https://user-images.githubusercontent.com/8930456/53246741-228a2e00-3677-11e9-8edc-cb9cc3447857.png)

Sauce: https://github.com/minetest/minetest_game/issues/2320
"Issue within builtin. There seems to be a scaling mismatch when using the the `wielditem` entity draw type for different node draw types."

**Comment by pgimeno** [comment]
Bisected to bb225672

**Comment by pgimeno** [comment]
The 0.75 is a "magic" hardcoded value that applies to the ratio between extruded wieldmesh and cube wieldmesh. The 0.75 ratio comes from here:

https://github.com/minetest/minetest/blob/1942660955bc3684a60d527e2fafa0ec3e02dd54/src/client/wieldmesh.cpp#L37-L38

I don't know where the 40 comes from, but it turns out to be the size necessary for the cube to match the collision box. The number 30 there is therefore 0.75 times the 40, and that's where the 0.75 comes from. Setting `WIELD_SCALE_FACTOR` to 40 makes the cube match the collision box and rest perfectly on the ground when removing the 0.75 factor from item_entity.lua. That, of course, looks ugly, but the bottom line is that this difference between extruded items and cube items is an engine problem.

Since the intention of `coll_height` was to make the item rest on the ground, I came up with this patch:

```diff
diff --git a/builtin/game/item_entity.lua b/builtin/game/item_entity.lua
index a330e8723..fde709f35 100644
--- a/builtin/game/item_entity.lua
+++ b/builtin/game/item_entity.lua
@@ -52,16 +52,13 @@ core.register_entity(":__builtin:item", {
 		local max_count = stack:get_stack_max()
 		local count = math.min(stack:get_count(), max_count)
 		local size = 0.2 + 0.1 * (count / max_count) ^ (1 / 3)
-		local coll_height = size * 0.75
 
 		self.object:set_properties({
 			is_visible = true,
 			visual = "wielditem",
 			textures = {itemname},
 			visual_size = {x = size, y = size},
-			collisionbox = {-size, -coll_height, -size,
-				size, coll_height, size},
-			selectionbox = {-size, -size, -size, size, size, size},
+			collisionbox = {-size, -size, -size, size, size, size},
 			automatic_rotate = math.pi * 0.5 * 0.2 / size,
 			wield_item = self.itemstring,
 		})
diff --git a/src/client/wieldmesh.cpp b/src/client/wieldmesh.cpp
index 2c6807fab..8adca5869 100644
--- a/src/client/wieldmesh.cpp
+++ b/src/client/wieldmesh.cpp
@@ -36,6 +36,7 @@ with this program; if not, write to the Free Software Foundation, Inc.,
 
 #define WIELD_SCALE_FACTOR 30.0
 #define WIELD_SCALE_FACTOR_EXTRUDED 40.0
+#define WIELD_POSITION_FACTOR (40.0 - WIELD_SCALE_FACTOR) / 2.0
 
 #define MIN_EXTRUSION_MESH_RESOLUTION 16
 #define MAX_EXTRUSION_MESH_RESOLUTION 512
@@ -239,6 +240,8 @@ void WieldMeshSceneNode::setCube(const ContentFeatures &f,
 	changeToMesh(copy);
 	copy->drop();
 	m_meshnode->setScale(wield_scale * WIELD_SCALE_FACTOR);
+	// offset the cube item so it touches the ground
+	m_meshnode->setPosition(v3f(0.f, -wield_scale.Y * WIELD_POSITION_FACTOR, 0.f));
 }
 
 void WieldMeshSceneNode::setExtruded(const std::string &imagename,
```

**Comment by SmallJoker** [comment]
@pgimeno Aligning the mesh to the bottom would solve this particular issue; but the builtin item is just one use-case of this drawtype. Changing the offset might cause visual issues in other mods. We could however test other mods with a matching scaling factor for cubes and extruded meshes.

**Comment by pgimeno** [comment]
Thanks. If it's going to cause issues with mods, I think it's best to just let it float (i.e. apply only the first hunk of the patch above).

**Comment by SmallJoker** [comment]
Issue no longer relevant since #9947
