### ISSUE TITLE
A new type of drawtype that works in a similar way to raillike

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#8334]
##### Issue type

 - Feature request
### Connected textures 

Example
![temporary_1551918502989](https://user-images.githubusercontent.com/33675971/53923763-3e55e280-402e-11e9-968a-e5d794439435.png)

Example code
```lua
tiles = {{
     type = "connected",
     right_turn = "right_turn.png",
     left_turn = "left_turn.png",
     straight = "straight.png",
     center = "center.png",
     one_eighty = "one_eighty.png",
     all_round = "all_round.png",
}},
```
![screenshot_2019-03-06-16-35-28-1](https://user-images.githubusercontent.com/33675971/53924188-f89a1980-402f-11e9-8d68-685a8da97da5.png)

**Comment by Extex101** [comment]
No that's not what I meant
Because I could just use glasslike_framed like in the image above. 
But what I'm suggesting is a node that's texture changes depending on the other nodes nearby
Like maybe if I wanted a block with arrows pointing to the direction of the next node
This could be used for:
- A connecting tree node
- Fancy outlined carpets like in the image shownot
- Things like this:
![base_landscape_0-1](https://user-images.githubusercontent.com/33675971/53931446-06f52f00-404a-11e9-9f7c-e418cc859ee4.png)
- Little striped roads

**Comment by DS-Minetest** [comment]
Related: #2748

**Comment by Extex101** [comment]
Kinda but instead of the ugly triangular blending have it use preset turns, straight, and blank tiles

**Comment by paramat** [comment]
By "A new type of connecting drawtype for connected area borders" i mean what you described with your carpet example, similar to how raillike drawtype works, i don't mean like glasslike framed.

**Comment by pgimeno** [comment]
I don't get how the feature is supposed to work. Is the engine supposed to be stacking several of these textures (up to 4 by my count) in the same square, in order to create the adequate tiling? Or is the example just missing possible tiles? I count 15 different types of tiles necessary (not counting rotations):.

![Tiles-for-borders](https://user-images.githubusercontent.com/4267396/54095809-5ff5f780-43a9-11e9-9880-6b965673c2a7.png)

**Comment by paramat** [comment]
It's likely just missing tiles.
Is this meant to work in 3D also?

**Comment by Extex101** [comment]
Yeah

**Comment by pgimeno** [comment]
I can see a use case for doing it 2D like the raillike drawtype, but not for 3D. At first sight, doing it 3D would be a big complication of the algorithm to select the right tile and rotate it.

Can you give examples where a 3D tiling like this is necessary or convenient?

**Comment by Extex101** [comment]
- Connecting tree trunks
- Turning road lines
- Things like my previous example of top-down-style tiles
-Custom stone brick block that connects the bricks realistically

**Comment by paramat** [comment]
I don't see much need for this in 2D and certainly not in 3D.

**Comment by Extex101** [comment]
Well the reason I opened this was because I needed it.
And I've also needed it several times in the past (If there are any modders who agree with me please speak up)

**Comment by rubenwardy** [comment]
I can see a use for this, but there may be a better way to get this

**Comment by Extex101** [comment]
What do you mean?

**Comment by pgimeno** [comment]
I've been giving some thought to this.

Full 3D where faces in different planes can connect by the edges to each other even (e.g. between sides of a cube) isn't easy to define, and even if it's possible to define it, the algorithm would become a hell and it would probably be too slow. The main problem is defining which edges are seams.

Next best is 2D per side, which I think is what the picture in the OP shows. I've made a mockup of a slightly more complex case demonstrating the problems with this approach:

![mockup-opaque](https://user-images.githubusercontent.com/4267396/54398701-6fcc4f00-46bb-11e9-9ad9-14d33ad4e2fd.png)

It may look incorrect in some intersections, but if you look at a transparent version it becomes clear why they are like that (short answer: because they don't connect in full 3D as defined above):

![mockup-transparent](https://user-images.githubusercontent.com/4267396/54398920-655e8500-46bc-11e9-98a7-18c90fbcee1d.png)

I'm not sure how feasible this is and whether it will be fast enough to draw. It's certainly not similar to raillike, because raillike is a flat node that always lies horizontally and the connections are very simple.
