### ISSUE TITLE
macOS Mojave: Black Screen

### ISSUE THREAD

**Issue by motherboard1999** [minetest/minetest#8365]
##### Issue type
 - Bug report

##### Minetest version
```
5.0.0
```

##### OS / Hardware
Operating system: macOS Mojave 10.14
CPU: Intel Core i5 (4th Gen)

GPU model: Intel HD 4000
OpenGL version: 4.1

##### Summary
I compiled the latest version 5.0.0 (and have tried it with the brew method), but if I start the script (or the app) I get a Black screen.

Here's the terminal output:
`➜  minetest-5.0.0 ./bin/minetest
2019-03-12 11:30:42: ERROR[Main]: Subgame specified in default_game [minetest] is invalid.
Loaded texture: /Users/florian/Downloads/minetest-5.0.0/games/minimal/menu/icon.png`

![Bildschirmfoto 2019-03-12 um 11 39 04](https://user-images.githubusercontent.com/31076457/54194247-0d593000-44bc-11e9-9d7a-e446fe8bf0ed.png)

##### Steps to reproduce
Compile the lastest version on macOS with the following commands and start the script:
`cmake . -DRUN_IN_PLACE=TRUE`
`make -j 1`
`./bin/minetest`

**Comment by pauloue** [comment]
Did you install Minetest Game?

**Comment by stormchaser3000** [comment]
does 0.4.17 work correctly in the latest MacOS? I test 5.0.1 and ran into the same issue. I wonder if this could have anything to do with apple trying to deprecate their OpenGL implementation (see this page on apple's website for confirmation: [](https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/OpenGL-MacProgGuide/opengl_intro/opengl_intro.html))

**Comment by tacotexmex** [comment]
`brew install minetest --HEAD` works fine for me.

```
cmake . -DRUN_IN_PLACE=TRUE
make -j 1
./bin/minetest
```
works for me too.

macOS Mojave 10.14.5.

<img width="1092" alt="bild" src="https://user-images.githubusercontent.com/25328789/58792768-1b1edd00-85f5-11e9-9c29-d24142233341.png">

**Comment by devshgraphicsprogramming** [comment]
OpenGL compatibility profile is, so on Mac OS X you will get max OpenGL 2.1 (which is lower spec than even ES 2.0)

Only when using core-profile (which Irrlicht is not doing) do you get OpenGL 4.1 max (because Apple are @"%^! and have abandoned OpenGL support over 8 years ago)

Its really hilarious given that all Mac hardware that people have out there in the wild starts supporting OpenGL 4.3 core and compatibility as soon as Windows or Linux is installed.

**Comment by Calinou** [comment]
@devshgraphicsprogramming Minetest should still be able to run with OpenGL 1.4 if you disable shaders in the settings.

**Comment by devshgraphicsprogramming** [comment]
"Should" is a misleading statement, when was the last time you tested on actual OpenGL 1.4 capped hardware?

**Comment by tacotexmex** [comment]
> supporting OpenGL 4.3 core and compatibility as soon as Windows or Linux is installed

Seriously considering Elementary OS…

**Comment by devshgraphicsprogramming** [comment]
Without much additional work...
For Minetest you could use MoltenGL and compile the MacOS version to use OpenGL ES instead of desktop GL (then use MoltenGL to provide a GL ES implementation over Metal).
iOS could be handled the same way.

That would obviously make the Mac have the same featureset as an Android Phone, but obviously it doesn't matter since you guys are allergic to shaders, despite the fact that every implementation of OpenGL 2.1 on GPUs newer than Geforce 7800 (2006), Radeon HD 2000 (also 2006), HD Graphics Ironlake (2010) emulates the fixed function pipeline with pre-compiled shader combos that run on Unified Shader architectures (same core executes fragment and vertex shader).

I'm in favour of an "Apple Tax" as people who own Macs don't care about performance already (since if they did they would buy better performing hardware for the same dollar), so they shouldn't mind the overhead of a Vulkan/OpenGL to Metal translation layer (which I'll be using in the form of MoltenVK or gfx-portability, when a user/developer appears that actually uses a Mac for my project)... while we developers really care whether two back-ends have to be written and our workload doubling.

**Comment by Calinou** [comment]
MoltenGL isn't open source (or even available for free), so we can't link to it and distribute it in officila builds. Only MoltenVK was open sourced as part of the deal with Khronos.

**Comment by devshgraphicsprogramming** [comment]
Then you still have a choice of ANGLE, etc.

**Comment by SmallJoker** [comment]
@devshgraphicsprogramming Does this problem still persist in current `master`, using the `brew` method ([above](https://github.com/minetest/minetest/issues/8365#issuecomment-498188781)) - or did something change?

> when was the last time you tested on actual OpenGL 1.4 capped hardware?

I played a while on such a system in 2014. Textures had to be powers of 2 or they were rendered incorrectly.

**Comment by sfan5** [comment]
> Only when using core-profile (which Irrlicht is not doing) do you get OpenGL 4.1 max

Now that preparations are underway to use [our fork](https://github.com/minetest/irrlicht) of Irrlicht, this should be fixable.

**Comment by sfan5** [comment]
Please re-test if this occurs with Irrlicht 1.9.0-dev.
