### ISSUE TITLE
Expose render hooks in Lua API

### ISSUE THREAD

**Issue by xaphiriron** [minetest/minetest#8426]
##### Issue type

 - Feature request
 
##### Minetest version

```
5.0.0
```

##### Summary

Rather than nodes and items having their texture and model hardcoded and immutably set at creation time, have some Lua function (`on_render` or similar) that recieves a node's/item's state (param values plus metadata) and returns render state. 

For nodes, have the function return the relevant drawtype/tiles/etc data. For items, an image reference. (Though, given that all image data is currently managed in the form of strings, this would probably involve some slightly more advanced primitives in the fashion of `inventorycube`, for things like compositing images or animating images in a way that's more controlled than just a strip.)

This could be used to make lots of things:

* battery items that visibly drain as they lose charge
* tools that degrade as their durability goes down
* tools that are formed from composited images (like tconstruct-style procedural tools)
* colored blocks a la minecraft wool/clay/etc
* plants with multiple growth stages
* vining plants like the minecraft pumpkin/melon
* things like power cables that visibly transmit power
* leaf nodes that change color based on season
* dynamic stair combinations
* generally, many nodes or items with distinct uses that can share the same ID, for mods that want to conserve node/item ids

Some of those things are already possible in the minetest engine, but require some combinatorial-explosion number of nodes/items to manage every possible render state. Allowing nodes/items to dynamically change their render information based on their state would simplify the logic enormously and make a lot of new mods possible.

In the C++ side, this would presumably be used somewhere around `drawNode` (though probably called at some point in the past, like "when the node was last changed", to avoid whatever overhead there is from running Lua deep in the render code / calling to recalc a node often) and add some `getNodeMetadata` and `getContent`/`getParam1`/`getParam2` calls in the general vicinity to make sure the information is on hand. I'm not sure where the item/tool version of it would go.

**Comment by rubenwardy** [comment]
This is a bad idea for performance and technical reasons. See this instead: https://github.com/minetest/minetest/issues/36

**Comment by xaphiriron** [comment]
Could you give a ballpark point in the code that's actually the bottleneck? I have no real clue about the performance characteristics of the code; is it that Lua is expensive to run, or there's no good way to determine when exactly a node changes any of its param values and thus any render-state callbacks would have to be called very frequently, or would having a node's meshes vary based on param/metadata destroy mesh caches, or what?

I've been looking at the code over the past few days thinking of mods to write, and it's mostly been a process of realizing that nearly every idea I have is impossible, or at least impossible without having to do things like create and register ~256 different nodes to handle different block render states, and that seems... extremely not ideal, if the point of minetest is to provide a flexible engine where all the content is in the form of mods.

**Comment by Linuxdirk** [comment]
> ... create and register ~256 different nodes to handle different block render states, and that seems... extremely not ideal

It can be easily done programmatically. The amount of nodes is the real problem here. Let's say you need 256 different nodes to represent the different states. Now have a mod that adds 10 of this nodes. This would made 2560 nodes. Now have 3-4 of such mods. You'll reach 10k+ nodes very easily (where in reality you would actually see 30-40 of them and the other nodes are registered for effects only).

Not to mention the [maximum registered nodes limit](https://github.com/minetest/minetest/issues/6101).

So instead of having render hooks exposed a good start would be having node data being actually node meta data (or overwritable by node metadata) that can be changed after loading state.

**Comment by paramat** [comment]
Almost all the usecases listed are already possible by using multiple nodes, and this is a good way to do things. It may require many nodes but 32768 are allowed, and there are advantages. For example: Having each node state a unique node with a unique content ID enables a lua voxel manipulator to process and detect node states very simply and quickly.
In many similar ways it is best that each possible node state is defined by ID and param2, because these are the fundamental values stored in the world and are quickly and simply processed.

This sort of request is understandable but is based on making modding a little easier and using fewer nodes, without realising the big engine problems caused. There is also the problem of it being a significant change to how MT works, with all the work, bugs and maintenance required.

It may cause modding problems too. For example we have hardware colouring of nodes such that a single content ID can have multiple colours depending on param2. Seemingly useful for modders, however it's complexity has caused many issues and it is actually not so straightforward to deal with in mods. Having one node per colour actually turns out to be simpler to mod, the only benefit is the reduction of nodes.
The amount of bugs and required maintenance it has added means that i am now uncertain it was worth adding (this is from an engine core dev perspective, obviously modders will like it).

You can see in #36 the problems explained, and the PR #1118 / #5919 has very serious performance problems, and is inherently very intensive if large numbers of nodes use the feature.

Whatever the implementation i am :-1: as i think it will cause a lot of problems and maintenance for something not much needed, and when using many nodes, although at first seemingly a pain, is actually the optimum method. Modders will just have to accept working within the limits of MT and not use more than 32768 nodes, it's not a small number and it looks possible we may be able to boost that some way towards 65000.

**Comment by xaphiriron** [comment]
I mean sure, ultimately you're the devs and if you say 32768 distinct render states is enough then that's how it's gonna be, but...

Like there are plenty of different ways an even slightly-parametric node can take up 64 or 256 node IDs for different render states -- a two-texture node that covers all possibilities, like for bark/wood or giant mushrooms or giant fruit, would take 64, since it would need different render states for every combination of faces; a minecraft-style vine that can grow on all four inner faces of a cube plus maybe the top or bottom could take between 16 and 64; an 8bit genetic plant that spreads and mutates randomly would take 256 nodes; and so on. 32768 is only a lot of nodes if you don't need to use 64-to-256 each for each of your actual nodes.

If you have a node that has 64 different render states, which is not even that many, then you can only have 512 nodes of that complexity _ever_, across all mods you have installed. That's really not a lot.

Like for example, in terms of minecraft mods, with something like Thermal Expansion that provides a dozen different machine blocks with configurable input/output faces... a node that has configurable sides, with options of input/output/none on five of its faces, would have to use 125 distinct node IDs to handle all those render states. A node with options of input/secondary input/output/secondary output/none on five of its faces would require _3125_ distinct node IDs. If you have six of one and six of the other, then that's a total of _19500_ node IDs, or using ~60% of all possible node IDs, only for the one mod, only for those dozen machine block types. That's not even getting into something like Tinkers Construct, where there's 20-50 materials times 6-12 modifiers times 15 tools times 3-6 tool parts.

Like, even just making render type/texture dependent on only `param2`, without any of the other metadata tags, and exposing that on the Lua side would be a huge improvement, because then mod authors could come up with their own arbitrary encodings instead of having to duplicate nodes for anything that falls even an inch outside of being representable with any of the hardcoded `param2` uses.

"Actually just use a different node for each render state" seems wildly insufficient, especially given that minetest purports to be a general-purpose game engine where all the content is in the form of mods.

**Comment by rubenwardy** [comment]
This is a bad idea for many reasons

### Requires client side scripts

Mods are currently entirely server side, and there is no way for a server or game to dictate what should be loaded. We're working on a client side API, which will one day help with this

### It will be very slow

Luckily there is no such thing as drawNode. Instead, meshes are generated for entire map blocks (16*16*16) at a time. Even when generated like this, you would need to call the function a lot of times. You'd need to trigger a remesh, which is what will happen in #36 anyway

### Limits multithreading

Lua can only be ran from one thread for a particular environment

### Is generally inferior to the alternative

Just read #36

**Comment by Linuxdirk** [comment]
@rubenwardy 

> Just read #36. This solution will have an in-memory encoding for overrides to the rendering

Is there any work on this or just paramat's 👎 on having the ability to change a node's texture after loading state?

**Comment by rubenwardy** [comment]
There's a few open PRs and
