### ISSUE TITLE
Discussion regarding implementation of custom keypress sending

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#8437]
##### Issue type
 - Feature request / Discussion

##### Summary

This is a discussion about the feature request first suggested in #8057, which is about SSCSMs being able to register custom key-binds.

##### Firstly, the reason behind the feature request

Mods are currently restricted to using chat-commands, formspecs, or a very limited set of keypresses, for execution of client-triggered code. Basically this feature request is about detecting more keypresses and sending them to the server, because the current set of keys just aren't enough.

##### Implementation details

- Mods have to register each extra key, along with the keybind for that key. e.g.
  ```lua
    minetest.register_key("reload", "KEY_R", function(name, ...)
        minetest.chat_send_player("Reloading...")
    end)
  ```
- When there's a keypress, the client checks if it matches any of the special mod-registered keybinds, and if there's a match, executes the callback of that keypress.

##### Other things that need to be kept in mind

I'm not sure how this can be worked out for touchscreen UIs. All of the above typically applies to only devices with keyboards. I can however think of the following workaround:

- The touchscreen UI will have a special menu like the one that contains the less frequently used buttons like minimap, zoom, fly, fast, noclip, etc.
- All the special keys registered by mods will be added to that menu as buttons. As for the button icons, I can't think of how that would be handled without having to force mods to provide the textures. Maybe iconize the button name itself?

**Comment by DS-Minetest** [comment]
Also related: #2731, #7008

- I agree that there should be some sort of registration function for keys.
- Imo the keynames should be in the format `"<modname>:<whatever>"`. (This only applies to keys registered by mods, built in engine keys should not have to follow this of course.)
- Maybe there should be separate `register_key` and `register_on_keypress/release` functions.
- The keybind value should only be the default keybind. There should be an ingame menu to change the binds.
- The server should be able to change the default binds via its config file for all players. (For mods with overlapping default binds.)


Btw, is there any progress in sscsm?

**Comment by Linuxdirk** [comment]
We have four key states: _not pressed_, _pressing_, _being pressed_, _releasing_. Those cycle when players press a key. First the key is _not pressed_, when a key is pressed is is in _pressing_ state for 1 tick, after that the key is _being pressed_ for whatever duration the key is pressed. When releasing the key the state is _releasing_ for 1 tick. After that the key is in _not pressed_ state until the player decides to press the key again.

When we’ll ever have custom key handling available it should be able to define a function for all four states. I go with the `register_on_*` functions.

```Lua
register_on_keypressing('KEYSYM', 'modname:my_cool_action', function(keysym, presser)
    -- Executed the first tick the key is pressed
    -- keysym is the keysym of the pressed key
    -- presser is the player name or object pressing the key
end)

register_on_keypressed('KEYSYM', 'modname:my_cool_action', function(keysym, presser, dtime)
    -- Executed from the second tick on the key is being pressed
    -- keysym is the keysym of the pressed key
    -- presser is the player name or object pressing the key
    -- dtime is the server ticks same as for globalstep timers
end)

register_on_keyrelease('KEYSYM', 'modname:my_cool_action', function(keysym, presser, dtime_total)
    -- Executed the first tick after releasing the key
    -- keysym is the keysym of the pressed key
    -- presser is the player name or object pressing the key
    -- dtime_total is the amount of server ticks the key was pressed
end)

register_on_keyunpressed('KEYSYM', 'modname:my_cool_action', function(keysym)
    -- Executed every tick while the key is not being in one of the other states
    -- keysym is the keysym of the key
end)
```

In a second step the client needs a new ingame interface for key configuration. Instead of cramming all default keys (that change little to no times ever after fist setup) into the menu it should be an interface to mod-registered actions.

The interface shows the name/id of the action and when it is triggered and allows to change this action to another key. The function then gets triggert if the changed key is in the state the function was registered for.

**Comment by ClobberXD** [comment]
Good point about separating the callback from the key registration, and about the four possible key states. I too agree the callback should be separate from the key registration.

**Comment by DS-Minetest** [comment]
@Linuxdirk Afaik, minetest uses [irrlicht's event receiver interface](http://irrlicht.sourceforge.net/docu/classirr_1_1_i_event_receiver.html)[.](https://github.com/lisacvuk/minetest/blob/d411d555949ebd7aa711c3461262d6e15a58c1c5/src/client/inputhandler.h#L131) This probably means that there are only events when a key is pressed or released, not while it's pressed and unchanged. Are you requesting that there should be helpers using globalstep that are only executed while a key is (not) pressed?
This might actually indeed be useful (because you normally want the exact dtime between the moment when the key is pressed/released and the first globalstep call and because it would be useful if the step callback would also be called a last time (with correct dtime) when the key state changed).

**Comment by Linuxdirk** [comment]
> Are you requesting that there should be helpers using globalstep that are only executed while a key is (not) pressed?

If it is possible without impacting overall performance then yes. Otherwise: use what's there. Everything is better than not having an option to configure keys to run custom (mod-provided) functions.

**Comment by raymoo** [comment]
Realistically there won't be any real decision until someone submits a PR

**Comment by ClobberXD** [comment]
> Realistically there won't be any real decision until someone submits a PR

And that's not going to happen until the basic SSCSM functionality is in place... :)

At least the would-be implementer might get some ideas and take some hints from this discussion, or even get inspired to work on the feature after they see this. :D

**Comment by appgurueu** [comment]
I suggest being able to show non-focusing formspecs while the player is in-game. Of course only Android players would be able to use them.

**Comment by ClobberXD** [comment]
> I suggest being able to show non-focusing formspecs while the player is in-game. Of course only Android players would be able to use them.

Why are you suggesting this, if only Android users can actually use it? And how is this related to custom keypress sending? :thinking:

This does indeed seem to be along the same line as #2731. I opened this issue specifically to discussion regarding the implementation (which I now think is unnecessary, in hindsight).

**Comment by appgurueu** [comment]
> Why are you suggesting this, if only Android users can actually use it? And how is this related to custom keypress sending?

I phrased this poorly. Android needs a custom method of registering "alternatives", which need to be elements aranged on the screen. Those could be provided by non-focusing formspecs, which would only be sent to mobile clients.

**Comment by ClobberXD** [comment]
Ah, thanks for clarifying. Would these "formspecs" need to be manually built by the mod that registers keypresses or would this done automatically engine-side? If this is automatically done engine-side, why specifically formspecs, and not something like buttons?

**Comment by rubenwardy** [comment]
See #2731
