### ISSUE TITLE
Support configuring rotation axis for `automatic_rotate`

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#8456]
##### Issue type

 - Feature request

##### Summary

Note: This feature request has been modified quite a bit (as per https://github.com/minetest/minetest/issues/8456#issuecomment-480642585). Check out the previous edits to see the original feature request.

The `automatic_rotate` feature would be more useful if the axis of rotation could be specified. As paramat noted, a new field (let's say, `automatic_rotate_axis`) can be added for this.

##### Use-cases

- Aircraft propellers, fans, etc.
- Planetary rotation(?) - this is possible only if `automatic_rotate_axis` takes a unit vector instead of just `x`, `y`, or `z`.

**Comment by stujones11** [comment]
AFAIK `automatic_rotate` is based on unit vector of velocity, therefore is would only be possible to extract a meaningful `x` and `y` rotation, ie. pitch & yaw. You can not determine roll without more information, usually a local 'up' and 'right' vector (depending on the coordinate system)

**Comment by DS-Minetest** [comment]
>Still a single unit vector is not enough information. It could be used to specify the axis of rotation but you still require direction and speed.

Of course a unit vector is not enough information, but a vector with any length is.
Example:
Vector `(-2,1,2)` has the length (= rotation speed) `3` and the direction (= rotation axis) `(-2/3,1/3,2/3)`.

Interesting code for this issue:
https://github.com/minetest/minetest/blob/ffb17f1c9a203fea6de70159b461f52d104e05b9/src/client/content_cao.cpp#L992-L996

**Comment by stujones11** [comment]
Okay, he doesn't state this it should be a unit vector, however, I still fail to see how this can be used in any meaningful way in 'all three axes' as you have no control over the rotation order.

**Comment by ClobberXD** [comment]
Looks like I've caused some confusion. I'm sorry if I haven't explained the feature request well. What I meant was that entities should support `automatic_rotate` for all three axes. I thought it was pretty simple (is it not simple?). Thanks to DS-Minetest for linking to the relevant code. I thought this feature request could be implemented by simply modifying that block of code like so (and the server-side code ofc):

```cpp
if (!getParent() && std::fabs(m_prop.automatic_rotate) > 0.001) {
	m_rotation.X += dtime * m_prop.automatic_rotate.x * 180 / M_PI;
	m_rotation.Y += dtime * m_prop.automatic_rotate.y * 180 / M_PI;
	m_rotation.Z += dtime * m_prop.automatic_rotate.z * 180 / M_PI;
	rot_translator.val_current = m_rotation;
	updateNodePos();
}
```

**Comment by DS-Minetest** [comment]
>you have no control over the rotation order.

`{x=0,y=1,z=0}` is in the opposite order of `{x=0,y=-1,z=0}`.

**Comment by ClobberXD** [comment]
What's passed to `automatic_rotate` is the value of turn in radians per-step, not a unit vector, btw. :)

**Comment by stujones11** [comment]
> {x=0,y=1,z=0} is in the opposite order of {x=0,y=-1,z=0}.

You over-simplifying an extremely complex subject, the tldr; is that some rotations will not be possible without providing more information, like a quaternion or rotation matrix.

**Comment by DS-Minetest** [comment]
PR: #8457

**Comment by ClobberXD** [comment]
I think I now understand what stujones11 means. My use-cases involve the entity _pointing_ at an arbitrary direction, and spinning about _one_ axis. This requires directly setting the rotation of the entity using `set_rotation`, and _then_ setting `automatic_rotate` for a single axis. My use-cases had literally nothing to do with `automatic_rotate` supporting all axes. :)

But my feature request is still valid, because there's currently no way to set `automatic_rotate` for the `x` and `z` axes.

**Comment by paramat** [comment]
> Suggestion: Allow to specify `automatic_rotate_axis`

This is best, as it keeps the existing auto rotate property relevant.

**Comment by paramat** [comment]
I think the rotation axis should only be X or Y or Z, otherwise it will be complex code to calculate object rotations around some axis pointing in an arbitrary direction, and i don't think that's much needed. Almost all desired rotations will be around the X or Y or Z axes.

Note that in the 3D rotation issue and PR it was decided to not add 3D auto rotation due to the complexity of that.

Please can we follow the MT roadmap and keep this simple and lightweight and covering most usecases, instead of complex, intensive and covering only slightly more usecases?

**Comment by ClobberXD** [comment]
Either X, Y, or Z is fine with me. Multiple axes at the same time results in wonky movement and has no usecase whatsoever.

**Comment by paramat** [comment]
What i mean is, the defined axis of rotation being aligned to X, Y or Z axes only, not allowing arbitrary angles between.

Also, i'm bemused why planets are being used as a usecase, that's not a valid usecase, objects disappear at a few nodes distance. Even if they didn't, they need to remain at infinite disance so should be provided by a skybox, not an object.
Besides, in MT the world rotates around a Z-aligned axis, not some angle inbetween, which suggests that planets in MT would have X, Y or Z-aligned rotation.

**Comment by DS-Minetest** [comment]
I think, only rotating around 3 axis isn't that much easier. As minetest uses Euler angles (z-x-y (extrinsic rotations) configuration I think), if, for instance, the object is already rotated around the y-axis, changing the z-value will only change the rotation around the z-face, not the z-axis.

**Comment by paramat** [comment]
This alternative approach seems a better idea https://notabug.org/pgimeno/minetest/pulls/5

IRC http://irc.minetest.net/minetest-dev/2019-04-09#i_5526901 onwards:

09:51 p_gimeno   Regarding #8456, I've looked into the automatic_rotation code. We could have a new property, e.g. automatic_rel_rot, that specifies a rotation that is always relative to the object. For best effect, it should also work for attached objects, so it allows e.g. a plane with propellers. It's unclear what drawtypes it should apply to; probably only mesh.
09:51 ShadowBot  https://github.com/minetest/minetest/issues/8456 -- Support configuring rotation axis for `automatic_rotate`
09:52 p_gimeno   ^ @ANAND
09:52 p_gimeno   Best of it, it can be implemented with minimal extra processing time, by just altering the rotation of the child node.
09:56 p_gimeno   The idea is that it will rotate only on Y, so you design the model so that it should spin on a vertical axis (e.g. the blades of a propeller would be horizontal). Then you use set_rotation() to orient them as desired, e.g. 90° on X would make it rotate like a propeller blade.
09:59 p_gimeno   Or for a globe, you rotate it by the axis inclination (23.5 degrees for the real Earth) over either the X or Z axis.
10:00 p_gimeno   In fact, automatic_rotation should have been intrinsic. But it's probably too late for that.
10:05 ANAND      Interesting
10:05 ANAND      > automatic_rotation should have been intrinsic. But it's probably too late for that.
10:05 ANAND      Yea, true :P
10:06 p_gimeno   unless, well, it's regarded as a bug and fixed in 5.0.2 or 5.1
10:06 ANAND      haha
10:07 ANAND      There's no real reason for it to be there, tbh, since we have set_rotation
10:07 p_gimeno   it would not be too much off the mark... I mean, vertical automatic_rotate does not make sense for models that use set_rotation
10:08 p_gimeno   oh it has a reason, for sure
10:08 ANAND      Convenience?
10:08 p_gimeno   it's reasonable to have objects spin without the server having to send an update every frame to make it spin
10:09 ANAND      Oh, I didn't know of that, nice!
10:09 p_gimeno   however, making it spin only in the yaw direction is the problem, because when you use set_rotation, it will still spin over a vertical axis
10:10 ANAND      o_O
10:10 ANAND      Argh, rotations are confusing...
10:10 p_gimeno   yeah, and that's what is not useful and can be regarded as a bug, and I don't think is too much of a stretch
10:10 ANAND      I thought the axis of `automatic_rotate` was local to the object
10:11 p_gimeno   if it was, I would have voted no to the issue because the functionality is already there
10:11 ANAND      True
10:12 ANAND      I think we should just modify it to work with local axes, and call it a day
10:13 ANAND      Basically what you suggested, but without the extra property
10:13 p_gimeno   there's a problem though, currently automatic_rotate does not work for attached objects, meaning it's not possible to make e.g. the blades of a helicopter
10:13 ANAND      Argh, bug it is ._.
10:14 p_gimeno   unfortunately, there may be mods that rely on it not working for attached objects
10:15 p_gimeno   so I'm not sure if changing that is feasible
10:25 p_gimeno   maybe we could add a new property automatic_rotate_attached which specifies the automatic rotation while attached
10:25 p_gimeno   so, while unattached the rotation speed would be determined by automatic_rotation, and while attached, by automatic_rotation_attached
10:26 p_gimeno   s/automatic_rotation/automatic_rotate/g

**Comment by stujones11** [comment]
:+1: This is a much better idea altogether, makes perfect sense :)

I am still slightly dubious about the suggest use-cases as most would be much better done with mesh animations and I fear this will be used as a lazy way to that.

The only things I can think of are; you need everyone to see the same rotation at a given time (assuming that's actually the case) or maybe rotate a pre-existing/generated mesh. IIRC, the itemframes mod uses this to spin a `wielditem` mesh on a pedestal (somewhat annoyingly, IMO)

**Comment by DS-Minetest** [comment]
>As long as the model is constructed in such a way that it's designed to spin over its local Y axis (for example, making a propeller such that it "lies" on the XZ plane and with the rotation axis being the Y axis), it's possible to use `set_rotation` to reorient the object so that the rotation axis points in the desired direction.

Wouldn't this be easier done by "lying" such a propeller in the xy-plane and using an automatic rotation around the z-axis instead of changing the y-rotation of the child?

**Comment by stujones11** [comment]
> Wouldn't this be easier done by "lying" such a propeller in the xy-plane and using an automatic rotation around the z-axis instead of changing the y-rotation of the child?

It would be better done using a single object with an animated propeller ;)

Using attached objects like that would not only be wasteful of resources, it would not work well with the current attachment system, anyway. Objects do not automatically re-attach when re-activated, for example.

**Comment by paramat** [comment]
I support this if only rotation around X, Y or Z axis, which the thread author seems happy with.

**Comment by ClobberXD** [comment]
@paramat Instead of sticking to a specific axis, p_gimeno provided a patch to allow the `automatic_rotate` object property to work in conjunction with `ObjectRef:set_rotation`, which is a much more flexible approach (IMHO) to this feature request. See #8468.

**Comment by paramat** [comment]
Ok, the PR is being reviewed so is probably supported.
