### ISSUE TITLE
Flat mapgen corruption issue

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#8463]
http://irc.minetest.net/minetest-hub/2019-04-09#i_5526996

![image](https://user-images.githubusercontent.com/2122943/55805684-d421d900-5ad6-11e9-9012-a34233f6078c.png)

![image](https://user-images.githubusercontent.com/2122943/55805669-cd936180-5ad6-11e9-92ca-a3bb53f74be0.png)

```
mgflat_np_cave1 = {
	flags = defaults
	lacunarity = 2
	offset = 0
	scale = 12
	spread = (61,61,61)
	seed = 52534
	octaves = 3
	persistence = 0.5
}
mgflat_np_terrain = {
	flags = defaults
	lacunarity = 2
	offset = 0
	scale = 1
	spread = (600,600,600)
	seed = 7244
	octaves = 5
	persistence = 0.6
}
mgflat_np_filler_depth = {
	flags = defaults
	lacunarity = 2
	offset = 0
	scale = 1.2
	spread = (150,150,150)
	seed = 261
	octaves = 3
	persistence = 0.7
}
mgflat_hill_steepness = 64
mgflat_hill_threshold = 0.45
mgflat_lake_steepness = 48
mg_flags = caves, dungeons, light, decorations
mgflat_large_cave_depth = -33
chunksize = 5
mg_name = flat
mapgen_limit = 600
water_level = 1
seed = 10398534904106224379
mg_biome_np_heat = {
	flags = defaults
	lacunarity = 2
	offset = 50
	scale = 50
	spread = (1000,1000,1000)
	seed = 5349
	octaves = 3
	persistence = 0.5
}
mg_biome_np_heat_blend = {
	flags = defaults
	lacunarity = 2
	offset = 0
	scale = 1.5
	spread = (8,8,8)
	seed = 13
	octaves = 2
	persistence = 1
}
mg_biome_np_humidity = {
	flags = defaults
	lacunarity = 2
	offset = 50
	scale = 50
	spread = (1000,1000,1000)
	seed = 842
	octaves = 3
	persistence = 0.5
}
mgflat_spflags = nolakes, nohills
mgflat_np_cave2 = {
	flags = defaults
	lacunarity = 2
	offset = 0
	scale = 12
	spread = (67,67,67)
	seed = 10325
	octaves = 3
	persistence = 0.5
}
mg_biome_np_humidity_blend = {
	flags = defaults
	lacunarity = 2
	offset = 0
	scale = 1.5
	spread = (8,8,8)
	seed = 90003
	octaves = 2
	persistence = 1
}
mgflat_lava_depth = -256
mgflat_lake_threshold = -0.45
mgflat_ground_level = 8
mgflat_cave_width = 0.09
[end_of_params]
``

**Comment by paramat** [comment]
Note: This is in the Kidscode fork.
Will check in MT. Looks like a dungeons issue, it's all cobble.
Sad to see the report had to come with abuse.

**Comment by paramat** [comment]
The only non-default parameter is a mapgen limit of 600.
I recreated the conditions but can't reproduce it.

**Comment by paramat** [comment]
I don't even know why this issue was opened here or why i bothered to test. Kidscode is a significantly altered fork of MT so Kidscode bugs are irrelevant here. The fact that they didn't touch flat mapgen is irrelevant, there are many other ways to cause errors in mapgen.

Anyway, i now know how this can be made to happen, and can confirm it is a Kidscode error and nothing to do with MT. My screenshot:

![screenshot_20190410_005736](https://user-images.githubusercontent.com/3686677/55842672-74eeb380-5b2c-11e9-98dc-b6536393f31a.png)

Because the report came with abuse of MT core devs i'm not saying how this is triggered. No idea why someone would think we'd help them if they abuse us.
