### ISSUE TITLE
Add a "reconnect" button on timeout

### ISSUE THREAD

**Issue by Niwla23** [minetest/minetest#8520]
##### Issue type

 - Feature request

 
##### Summary
 Add a reconnect button like when the server crashs also on timeout. So you dont have to type the password again when you time out. Sorrry for the bad english.

**Comment by sfan5** [comment]
<pre>#    Whether to ask clients to reconnect after a (Lua) crash.
#    Set this to true if your server is set up to restart automatically.
#    type: bool
# ask_reconnect_on_crash = false
</pre>
does this not do what you need?

**Comment by ClobberXD** [comment]
Generally a timeout indicates that a server does not exist at that IP and port. There's no point in having a reconnect button for the rare cases when the client times out even if they connect to the right IP and port, and the server is up and running.

**Comment by Niwla23** [comment]
I often timeout while playing! so im playing and suddenly: Connection time out. And there should be a recconect button.
@sfan5 Thats only on server crash not on client timeout, right?

**Comment by ClobberXD** [comment]
A connection timeout means that the server did not send any packets to the client for the past `x` seconds (30, IIRC). In most cases, this means that the connection between the server and the client is very bad, that the client lags behind by more than 30s, and triggers a "timeout". While it's certainly possible to implement this feature request, I don't see enough need for this to justify the dev effort.

> Thats only on server crash not on client timeout, right?

Yes, that's correct.

**Comment by FullTimeLinux** [comment]
> In most cases, this means that the connection between the server and the client is very bad, that the client lags behind by more than 30s, and triggers a "timeout". While it's certainly possible to implement this feature request, I don't see enough need for this to justify the dev effort.

One great reason to add this feature is for laptop or mobile users. If the wifi gets interrupted say because someone inside the house is using the microwave or a neighbour changes their wifi channel to interfere with your own, the player would be kicked. Then the player would have to go through the hassle of retyping the password even though a simple retry button would suffice. Having this feature adds more convenience to minetest and makes it more attractive. 


In regards to sfan5 if the default server software has this setting off by default it should be turned on by default instead to save hassle.

**Comment by ClobberXD** [comment]
Valid points, thanks. I support this feature now.
