### ISSUE TITLE
Hold Interact on mobile

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#8543]
##### Issue type

 - Feature request
 
On Android build of minetest you can tap and hold to break 
But you can't double tap and hold to continously interact
An Example(Feature):
Speed place block

Another example(Bug):
 - Log on to "Subgames for all"
 - Play hide and seek
 - (Play until you are a hider) Try to use bow that requires interact/place

It's impossible on Android

**Comment by ClobberXD** [comment]
I really feel having dedicated buttons for LMB and RMB is the option that allows maximum flexibility.

**Comment by Extex101** [comment]
Also maybe labeling them better instead of
LBM, RBM, and AUX 'cause nobody knows what that means

**Comment by DS-Minetest** [comment]
Continuously rightclicking and sending RMB seems ok. But I do not think that continuously placing nodes makes sense for android because on mobile devices it's difficult to move, look around you and hold the place button at the same time. Therefor it is rather useless to be able to continuously place nodes. Players would struggle to use this and leave ugly structures behind themselves.
I might be wrong of course.

**Comment by ClobberXD** [comment]
Let's have (optional, ofc) gyroscope-based look direction apart from manual swipes. :D
