### ISSUE TITLE
Allow mods to apply pitch move per player

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#8556]
##### Issue type

 - Feature request

Allow for mods to set pitch move per player

For things like:
An Elytra/wingsuit mod
Fancier swimming

Could be used like this
```
player:apply_pitch_mode()
player:disable_pitch_move()
```
Only works of client has pitch move disabled
```
player:apply_normal_move()
```
Disables pitch fly for those who have it enabled client-side

**Comment by Linuxdirk** [comment]
We already have (non-persistent) player attributes. A system could be implemented reading a setting from there. This would avoid adding a new object member function.

**Comment by paramat** [comment]
Flying: Vehicle mods don't use fly mode as it's an admin/dev mode and a privilege.

Swimming: I can't see the usefulness of a mod being able to switch this, can you explain why it is useful for a mod to do this instead of the player? It's a player's personal preference so they will likely just toggle it if they like it and when they need it (this goes for flying too).

**Comment by Extex101** [comment]
Making a swimming mod that rotates the player based on pitch and yaw and increases speed when swimming


Besides I prefer pitch swimming to normal swimming but I find it hard to fly with pitch fly

**Comment by LoneWolfHT** [comment]
For games like water_game where all of the gameplay is underwater being able to force pitch move would be really nice

**Comment by lefty-studios** [comment]
> For games like water_game where all of the gameplay is underwater being able to force pitch move would be really nice

For reference:
https://github.com/lefty-studios/water_game

**Comment by paramat** [comment]
> For games like water_game where all of the gameplay is underwater being able to force pitch move would be really nice

Pitch move is a strong personal preference. In this context i cannot see the benefit, forcing it would irritate half the players for apparently no good reason. Can you explain the benefit for underwater games?

**Comment by LoneWolfHT** [comment]
> Pitch move is a strong personal preference. In this context i cannot see the benefit, forcing it would irritate half the players for apparently no good reason. Can you explain the benefit for underwater games?

The movement in [Subnautica](https://unknownworlds.com/subnautica/) is pitch-based except for when the player is on land (Like MT right now, but without the toggle). I've never heard of anyone complaining about that. I think it's kind of expected for underwater games actually.

I find it's a lot easier to move around underwater with pitch move on. The only reason I usually don't with MT is due to https://github.com/minetest/minetest/issues/9316 and https://github.com/minetest/minetest/issues/7946

I don't think players being mad about something like this is up to the engine either. Since all this should do is allow mods/games to force enable (and I guess also force disable) pitch move.
If a server owner uses this to force enable/disable pitch move on their server then the mad players is their problem. Not the engine's

**Comment by Warr1024** [comment]
Ideally, players should have final say in pitch-move, so a 3-way toggle like force-on / force-off / server-recommended would be nice.

I find myself not using pitch move because there are some annoyances, like the way it changes the meaning of the up/down movement axis instead of just forward/backward, so I can't use the jump key as a "panic and swim up for air" key, I have to do the more complex "aim directly up with mouse and swim forward" thing, which sometimes conflicts with things I'm trying to do at the same time.  It seems like maybe there should be a separate toggle for whether pitch-move affects the vertical axis too, so clearly if pitch-move is to be useful for all players and all games at least a little more configurability would be helpful.

**Comment by paramat** [comment]
LoneWolfHT,
Subnautica and its players are irrelevant, that is a different game.
If it is expected (games differ, so expecting is somewhat unreasonable) or desirable, then MT already offers this mode, but even better, offers a free choice of 2 modes.

MT players are used to the previous swimming behaviour so the preference is likely to be varied.
I generally do not like pitch move when swimming, but might occasionally use it if it is useful in a certian situation, at the least i would insist it was left to me to choose.
I expect most players prefer to be able to switch it themselves, as each mode has advantages and disadvantages.
Allowing forcing seems pointless as it will only irritate a lot of players.

So i cannot see where you have explained why it would be useful.
Extex101 made a valid point about how it would be useful.
> Ideally, players should have final say in pitch-move, so a 3-way toggle like force-on / force-off / server-recommended would be nice.

Why have a server recommended mode at all if the player is free to choose for themselves? What is the benefit of that?

I support #7946

**Comment by LoneWolfHT** [comment]
Looking at the OP nothing was said about forcing pitch move, and now that I think about it I'm not sure that's really what I wanted. I guess what I'd like to see is this:

* Allowing servers/mods to set the default movement mode for new players (pitch/default)
* The commands listed in the OP in addition to something like `get_movement_mode`

> Why have a server recommended mode at all if the player is free to choose for themselves? What is the benefit of that?

I'm fine with them choosing as long as I get to pick what they start with, in this case I'd like to be able to have them start with pitch move enabled.

**Comment by ClobberXD** [comment]
I'm personally against forcing players to (not) use pitch move, as that's a very personal choice. That'd be equivalent to forcing "Invert mouse" (for whatever reason), IMO. Regarding servers setting the default movement mode, I think it might not be worth the time and effort put into implementing it.

IMO, a simpler alternative to setting default movement mode (that's just as effective), is for servers/games/mods to suggest to the player (not) use pitch move via signs, chat, formspecs, or other similar means. This approach:

- doesn't require any dev effort.
- isn't as intrusive for the player.

**Comment by LoneWolfHT** [comment]
> isn't as intrusive for the player
I'd argue it's more intrusive if you're popping up a formspec asking them to switch to pitch movement

**Comment by ClobberXD** [comment]
Obviously, a displaying a formspec just for this purpose is not great; what I meant is that this suggestion could be integrated with something like a welcome formspec shown to new players, or to all players upon join. It'd be up to the server to decide upon a way to _suggest_ enabling pitch move to players.
