### ISSUE TITLE
Can't change player hand

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#8559]
##### Issue type
 - Bug report
 
##### Minetest version
```
Minetest 5.1.0-dev-d5c7d762
```

##### Summary
I don't seem to be able to change the player's hand with the mod I'm working on or with the interchangeable hands mod

##### Steps to reproduce
* Get this mod: https://github.com/octacian/hands
* Run `/sethand default:stick`
* Inspect your hand

The hand changes with 0.4.17.1 but not with 5.0

**Comment by SmallJoker** [comment]
Followed from a security issue where you could put any item into the hand slot in 0.4.x, you now have to take care of this special slot:
https://github.com/minetest/minetest/blob/b917ea4723fb0fe976486602a456c8dd41eab7ef/doc/lua_api.txt#L2293-L2294

https://github.com/octacian/hands/blob/master/init.lua#L34
```Lua
    -- if not param, return to default hand
    if not param or param == "" then
      player:get_inventory():set_size("hand", 0)
      return true, "Set to default hand"
    end
    player:get_inventory():set_size("hand", 1)
    player:get_inventory():set_stack("hand", 1, param)
return true, "Set hand to "..param
```

Also don't forget to register a player inventory callback. Right now all players with this privilege kinda got the functionality of `giveme` because they can take the itemstack out of the slot, even though the slot is not shown on any formspec.

**Comment by BruceMustache** [comment]
> because they can take the itemstack out of the slot, even though the slot is not shown on any formspec.

How the player can do that?
What should I do to prevent this on newhand mod?

**Comment by sfan5** [comment]
You are supposed to use `minetest.register_allow_player_inventory_action` to disallow the user from modifying the hand inventory.

**Comment by BruceMustache** [comment]
Thanks. I've already begin to implement it but I've noticed my allow isn't apply on lua calls
It  continues secure right? Since player can't use lua api inside a minetest world right?

**Comment by LoneWolfHT** [comment]
If the player could run lua api functions they could give themselves the item(s) without taking advantage of the hand cheat
