### ISSUE TITLE
Formspec: add min, max and pagesize parameters to scrollbar element 

### ISSUE THREAD

**Issue by DS-Minetest** [minetest/minetest#8575]
##### Issue type
 - Feature request
 
##### Minetest version
```
Minetest 5.1.0-dev-b917ea4 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=0
STATIC_SHAREDIR="."
```

##### Summary
Currently the `scrollbar` formspec element sill uses the `gui::IGUIScrollBar` class and the `min` and `max` values are set to `0` and `1000`:
https://github.com/minetest/minetest/blob/7379aa74cf98c7e4c7aa5325ef1531d412a0abac/src/gui/guiFormSpecMenu.cpp#L516-L520
https://github.com/minetest/minetest/blob/7379aa74cf98c7e4c7aa5325ef1531d412a0abac/doc/lua_api.txt#L2196-L2206

I request that the scrollbar element uses the new `guiScrollBar` class (from #8507) and that you can set the `min`, the `max` and the `pagesize`.

Note that there's #8530 which would already cover `min` and `max`, but not `pagesize`.

**Comment by v-rob** [comment]
I'm not sure what you mean by `pagesize`.  #8530 has `smallstep` for using the arrows/scrolling the mouse wheel and `largestep` for clicking the bar background.  I think that's what you mean by `pagesize`, or do you mean something else?

I agree that the new guiScrollBar class should be used from #8507.  I'll do that.

**Comment by DS-Minetest** [comment]
`pagesize` is a scrollbar parameter that was added by #8507 (see [here](https://github.com/minetest/minetest/pull/8507/files#diff-a10e3439096ba2abde3e95b9c31a7cabR42)). It is a number that defines, how long the scroller is.

**Comment by v-rob** [comment]
I see, that makes sense.  I think that `pagesize` should be set to the height of the scrollbar rect by default, since that would be the `pagesize` in normal situations.  I will also make it changeable, of course.  To reset it to use the automatic `pagesize`, I think that `-1` should work well.

BTW, since `guiScrollBar` was merged after I created `scrollbaroptions`, can I somehow update the repository?  I have no experience with Git at all (I just drag and drop with GitHub).

**Comment by DS-Minetest** [comment]
>I just drag and drop with GitHub

O_O Why?

Use your terminal and do a rebase. (Instructions are here: https://forum.minetest.net/viewtopic.php?f=3&t=14262&p=211498#p211502)
(The good thing is that there are probably not even merge conflicts.)

Or I've heard that there are programs that provide a GUI for git. But I've never used such a thing.

**Comment by v-rob** [comment]
I'm in a very peculiar setup.  I work on Windows, since it's my main OS, but I can't figure out how to compile Minetest on it, so I do that on a Linux virtual machine.  I know basically nothing about Linux, so I've been using the one-line scripts at https://forum.minetest.net/viewtopic.php?f=42&t=3837.  Thanks for the link;  I'll figure it out somehow.

**Comment by DS-Minetest** [comment]
If you really want to continue with your weird practices, you could also make something like a rebase via github by opening a PR in your fork from minetest/minetest master to your branch and merging it.
