### ISSUE TITLE
Formspec: scrollable container

### ISSUE THREAD

**Issue by Desour** [minetest/minetest#8576]
##### Issue type
 - Feature request
 
##### Minetest version
```
Minetest 5.1.0-dev-b917ea4 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=0
STATIC_SHAREDIR="."

```

##### Summary
I request a new formspec element that should work like this:

Two formspec elements are added:
```
scrollbar_container[<X>,<Y>;<W>,<H>;<name of a scrollbar>;<multiplier>]
scrollbar_container_end[]
```
All formspec elements that are defined after a `scrollbar_container` and before a `scrollbar_container_end` should be
- offset by `<X>` and `<Y>`,
- additionally offset by the current value of the scrollbar with the name `<name of a scrollbar>` ~~(or the value of the scrollbar of the element with the name `<name of a scrollbar>` (eg. `textarea`))~~ times `<multiplier>` (the direction depends on whether the scrollbar is vertical or horizontal) and
- not drawn outside of the window defined by `<X>,<Y>;<W>`.

If your mouse is in the scrollbar container, the corresponding scrollbar should be scrolled with the mouse wheel.

This would allow small and large windows with relatively much information.

##### Example
The following formspec:
```
size[6,4]
scrollbar[5,0;0.2,4;vertical;scrbar;0]
scrollbar_container[0,0;5,4;scrbar;0.025]
button[0,0;2,1;btn;Button]
field[4,4;3,1;fld;field;empty]
scrollbar_container_end[]
```
Should look approximately like this:
![example](https://user-images.githubusercontent.com/7613443/58763719-190a3f00-855f-11e9-83b8-128635a742a0.png)
![example2](https://user-images.githubusercontent.com/7613443/58763720-19a2d580-855f-11e9-848c-f159024b2135.png)

##### Usecases
I can see very many usecases for this. Here are just very few examples:
- A key change menu where you do not have to compress a limited number of buttons to small space.
- A creative inventory where you just scroll through the list.
- A formspec listing rules where you can't mark the text and where the button to accept appears when you at the bottom of the text.

**Comment by v-rob** [comment]
I have thought of this myself.  It's possible to do with a normal scrollbar and some immense hackery since scrollbars can be handled directly on change, but the formspec would have to be reshown every time and would require a settable min and max, and elements wouldn't be clipped at the bottom.

Judging by how the internal formspec code works, I don't think that this would be easy to do at all because I don't think Irrlicht has any way to move and clip `rects` in the way that this would require it to.

**Comment by DS-Minetest** [comment]
🎉
I've managed to do make the requested element myself.

See https://github.com/DS-Minetest/minetest/tree/scroll_container.

However there are still many things to do. The basic feature works. The moving works and the clipping works, too. However, I've concerns that not all elements work yet. And things like the multiplier, the scrolling if the mouse hovers above the container or scrollbars of any elements are not implemented yet.

I'll open a PR when it's more ready as general discussion can be done in this issue and too many comments in a PR cause the TL;DR effect.

**Comment by v-rob** [comment]
Very nice!  So, are the screenshots in the first post pictures of this, or are they just mockups?  (I ask because the button and field don't look quite aligned with the scrollbar).

I suspect using the scroll wheel in this will be tricky because certain elements, like `textarea`, `textlist`, and `table` have their own scrollbars.  Another problem I foresee is that dropdowns might be cut off inside the container so that not all options can be seen, which could be very problematic.

**Comment by DS-Minetest** [comment]
>So, are the screenshots in the first post pictures of this, or are they just mockups?

Hehe, no I've made them before with gimp, just for this issue.

Here's a real ingame screenshot:
![2019-06-06-011709_1920x1080_scrot](https://user-images.githubusercontent.com/7613443/58996534-f2673500-87f8-11e9-82d5-a0a04f335e62.png)

Scrolling:
I thought that I simply set the scrollbar focused if the background of the scroll_container is clicked (other elements like buttons, fields or scroll_containers with more parents have more priority of course).

I guess the cutting off of the dropdown element will be as bad as if the dropdown would go out of the window made by `size[…]`. This is no real problem I guess.

**Comment by v-rob** [comment]
If a dropdown is cut off at the bottom, that is expected and mod developers can compensate by not placing it there.  But players who can scroll the container may scroll it so that the dropdown is at the bottom of the visible part of the container, and they might wonder why they can't see all or part of it.

**Comment by DS-Minetest** [comment]
This might be something for a `style` option, not clipping the expanded dropdown.

**Comment by DS-Minetest** [comment]
I've done the multiplier now.
Sadly there are many elements that don't work which means that I have to change them.
<details><summary>Here's a list showing which elements work without problems and which don't.</summary>

```
button				t
pwdfield			t
container			t
list				f
background			f
box				f
image				f
item_image			f
bgcolor				f
label				t
vertlabel			t
textarea			t
item_image_button		f
tooltip				t
checkbox			t
scrollbar			t
table				t
tablecolumns			?
textlist			t
dropdown			f
field_close_on_enter		?
image_button			t
tabheader			f
```
</details>

**Comment by v-rob** [comment]
Most of those actually make sense because they are rendered independently of Irrlicht by Minetest since they aren't built-in for Irrlicht.  They also have stacking issues (i.e. lists are rendered above everything else, boxes are below everything, etc.)  The nice thing is that the solution for one of them will probably work for most of them.

**Comment by DS-Minetest** [comment]
The real problem with stacking is now that if I fix it, which I have to, it will likely break backward compatibility. Also, the background for example has to be drawn before everything else.

**Comment by DS-Minetest** [comment]
`box`, `tooltip`, `list`, `image` and `dropdown` work now.
(However, the items in the list are not clipped correctly as I haven't found a way to do so. Instead they are not displayed if more than 50% of the item can not be seen.)

**Comment by DS-Minetest** [comment]
Ok, all elements work now as expected.
I'll work now especially on the inputs and co. And I thought that it would be better to set the direction of the scrolling in the scroll_container definition, so I'll do this, too.

**Comment by DS-Minetest** [comment]
Ok, it works now, even with textareas as scrollbars.
However, the code is so ugly. >_<

**Comment by v-rob** [comment]
Just two questions:  Are dropdowns clipped at the bottom?  Can you scroll left-right as well as up-down, and can you do it at the same time?

And don't worry _overly_ much about the ugly code.  The formspec code is already a pretty much uncleanable mess. :-P

**Comment by DS-Minetest** [comment]
The open part of the dropdown is not clipped. And if you scroll, the dropdown is closed.
Scrolling down and to the right is possible.
Nesting scroll_containers is possible. Diagonal scrolling doesn't make much sense.

I think, I won't support binding to other elements than normal scrollbars anymore. There are no real usecases and it makes the code much more complicated, I'll KISS.
