### ISSUE TITLE
Brighter natural night light (was: Raise display_gamma limit?)

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#8577]
I'm finding a lot of players (Including me) don't like how dark `display_gamma=3` is.
(EDIT by paramat: See https://github.com/minetest/minetest/issues/8577#issuecomment-542833165 gamma does not make natural night light brighter, a change is needed elsewhere)

[Here's a recent Reddit complaint](https://www.reddit.com/r/Minetest/comments/bw3ors/completely_dark_even_with_gamma3_brigtest_value/)
(EDIT by paramat: Invalid complaint)

Places I've heard complaints:
* At least 2 players on the Undercore Server
* At least 10 on the CTF server (display_gamma=999999 was common there though...)
* At least 3 on Discord
* Possibly 1-2 on the forums

Probably a lot more than just that though

**Comment by DS-Minetest** [comment]
You are referring to the `display_gamma` setting, right?

Side note:
:thinking: In German, it says "Kleinere Werte sind heller." [()](https://github.com/minetest/minetest/blob/7379aa74cf98c7e4c7aa5325ef1531d412a0abac/po/de/minetest.po#L1961) which means that smaller values are brighter, however in English it says, that higher values are brighter:
https://github.com/minetest/minetest/blob/7379aa74cf98c7e4c7aa5325ef1531d412a0abac/builtin/settingtypes.txt#L638-L640

**Comment by LoneWolfHT** [comment]
> Side note:
> thinking In German, it says "Kleinere Werte sind heller." [()](https://github.com/minetest/minetest/blob/7379aa74cf98c7e4c7aa5325ef1531d412a0abac/po/de/minetest.po#L1961) which means that smaller values are brighter, however in English it says, that higher values are brighter:
> 
> https://github.com/minetest/minetest/blob/7379aa74cf98c7e4c7aa5325ef1531d412a0abac/builtin/settingtypes.txt#L638-L640

Higher values have always been brighter for me. Maybe the translations weren't updated

**Comment by Calinou** [comment]
It seems the lighting calculations were adjusted in 5.0.0, and there's no way to make the game decently bright anymore (I tried all the `minetest.conf` light table settings). The only way to save it without recompiling the source code would be to edit the node shaders, but that's hacky.

**Comment by SmallJoker** [comment]
@numberZero I think this algorithm needs tweaking.

Here it's also very dark; higher gamma values (brighter) would be lovely to have.

**Comment by paramat** [comment]
Heh, the reddit comment is from a user called 'russian-homophobe'.
"even gamma=3 (max allowed) gives complete darkness underground and 16 block beneath sea level."
Yes, completely dark places are completely dark, and always should be to avoid cheating (navigating in completely dark places without lighting). So we can ignore that comment.

Some darkness complaints are very silly, however, it seems some of the complaints are valid, for example when you are playing in a brightly lit environment and need to just be able to see in moonlight (which should be possible), so i support raising the limit, as long as it doesn't make it possible to see in complete darkness (underground).

**Comment by Linuxdirk** [comment]
Limiting gamma in the engine cannot be used as anti-cheat for gamma values. Every nowadays operating system allows changing system gamma to any value without the applications knowing anything about it.

`xgamma -gamma 6` and you can see everything. (I sometimes do that when running out of torches and wood when deep underground.)

**Comment by LoneWolfHT** [comment]
> Limiting gamma in the engine cannot be used as anti-cheat for gamma values. Every nowadays operating system allows changing system gamma to any value without the applications knowing anything about it.
> 
> `xgamma -gamma 6` and you can see everything. (I sometimes do that when running out of torches and wood when deep underground.)

xgamma -gamma 6 doesn't work at all for me. Turning up monitor settings works for me though (Everything outside of the game looks terrible though. And it's a pain for me to change my monitor settings every time I play MT)

**Comment by Calinou** [comment]
> xgamma -gamma 6 doesn't work at all for me.

This depends on the graphics driver (not all graphics drivers may obey hardware gamma settings; Intel is known to ignore those). Software which enables a "night mode" such as Redshift can also interfere with hardware gamma settings.

**Comment by Linuxdirk** [comment]
> xgamma -gamma 6 doesn't work at all for me.

As @Calinou already stated: It depends on graphics driver. Maybe try lower gamma values like 2 or 3. Or you're just unlucky 😃 But as you already said: one can simply raise monitor hardware settings.

Arbitrarily limiting engine's gamma settings doe snot solve anything.

**Comment by v-rob** [comment]
I think that gamma that allows one to see underground makes perfect sense.  There should be a way to limit it on servers to prevent cheating, but in local play, anyone should be able to have gamma as bright as they want.  On my particular screen, contrast is higher, so the current gamma limit is still too dark and it strains my eyes unless I place an exorbitant amount of torches.

**Comment by numberZero** [comment]
Completely dark areas are rendered as black, so no gamma adjustment can make anything recognizable there. That includes hardware gamma adjustment, unless shaders mess things up. Only semi-dark areas with non-zero light level are affected by gamma.

> In German, it says "Kleinere Werte sind heller." () which means that smaller values are brighter

That was the case a long time ago...

**Comment by paramat** [comment]
That's what i suspected, and thanks it's good to have that confirmed.

Making completely dark areas bright is what fullbright mode will be for.

**Comment by ClobberXD** [comment]
#8618 - Working upper limit increased to 10.0

**Comment by paramat** [comment]
See PR, try increasing 'alpha' too.

**Comment by LoneWolfHT** [comment]
@paramat Could you give an example of settings that increase the brightness of the world at night but keep the sky dark?

lighting_alpha increases the brightness of the sky, and lighting_beta makes it darker. But when I use beta with display_gamma even when I put them both to max I see no difference in the brightness of the world. Only the sky

There's no brightness difference with non-max gamma/beta settings either
(Not at max, I can provide a screenshot of that if wanted though)
![image](https://user-images.githubusercontent.com/28972859/66718853-58625b00-ed9d-11e9-87cb-1085a65c568a.png)
Note: I'm looking at the brightness of the nodes (In this case the grass. Here's a ground comparison:)
![image](https://user-images.githubusercontent.com/28972859/66719223-d9235600-eda1-11e9-8263-c6f96ad4edf3.png)

---

Increasing only lighting_alpha even to its max limit does nothing but increase the brightness of the sky. It also breaks lights
![image](https://user-images.githubusercontent.com/28972859/66719112-59e15280-eda0-11e9-9b48-b820aa72ec03.png)

---

Screenshot of the broken lights. Taken at midnight. lighting_alpha = 4
![image](https://user-images.githubusercontent.com/28972859/66719048-a5dfc780-ed9f-11e9-8574-796e67370ffb.png)

**Comment by LoneWolfHT** [comment]
I guess my request is to allow players to increase the brightness of their world without increasing the brightness of the sky, since it looks ugly then. Shall I create a new issue?

**Comment by paramat** [comment]
> Increasing only lighting_alpha even to its max limit does nothing but increase the brightness of the sky.

Ok sorry i was wrong then, i was going by what others reported.
> Could you give an example of settings that increase the brightness of the world at night but keep the sky dark?

I have never tried, it may not be currently possible.
Feel free to open a new issue for making that possible.

**Comment by paramat** [comment]
Reopen.
It seems uncertain whether a gamma upper limit of 10 is enough.
It also seems uncertain whether the lighting parameters are actually able to make night terrain reasonably visible to the degree of previous versions of MT, does anyone have settings that do this?

**Comment by ClobberXD** [comment]
> Increasing only lighting_alpha even to its max limit does nothing but increase the brightness of the sky.

From what I understand, lighting_alpha tunes the lower end of the light curve so that the brightness across the lower brightness levels quickly increase to a high value, and the next part of the curve continues from there (picturing a steeper curve with the start and end values unchanged, would help understanding this). i.e. `lighting_alpha` only increases or decreases the gradient of the initial part of the lighting curve, and doesn't actually make increase the brightness across the board. That's why a torch lights up an area of the same radius, but even the outer reaches of this area is quite bright, and the light fades away more abruptly past that point.

Btw, I can confirm the broken lighting, with `lighting_alpha = 4`. I suspect that the different parts of the curve don't play along well if `lighting_alpha`, `lighting_beta`, etc. are modified. It'd be nice to be able to graph out the light curve to confirm this.

**Comment by paramat** [comment]
>  i.e. lighting_alpha only increases or decreases the gradient of the initial part of the lighting curve, and doesn't actually make increase the brightness across the board.

It does actually =) See graph: https://github.com/minetest/minetest/pull/5279#issuecomment-307450248
Horizontal axis is node light levels 0-15
Vertical axis is visual brightness.

alpha is gradient at the low light end.
beta is gradient at the high light end
mid-boost adds a configurable boost of mid-values.
gamma ... erm ...

https://github.com/minetest/minetest/blob/2dd4f8d3fe666eb1d86050e0f5efa44c848b1a4a/src/light.cpp#L69-L84
This is odd, gamma doesn't seem used at all, investigating ...

**Comment by ClobberXD** [comment]
Oh nice :)

That clears things up a bit, thanks.

**Comment by paramat** [comment]
It is odd though, the new light curve parameters are powerful, and the application of gamma seems unchanged. The light curve is very well tuned and similar to MT 0.4.x.
The broken torch light with high alpha suggests a bug.
It seems that the effect of gamma has changed somehow.

Brightening the display to compensate for certain monitors or playing in bright environments is valid, but MC-style stupidly-bright-as-day nighttime is not, MT just does not do that (although it might in future).
I think of the requirement this way: Nighttime is always full moon. In real life with full moon it is possible to just see well enough to navigate, but it is still quite dark. This should be possible with all monitors and in all environment brightnesses.

Now that the gamma limit is raised, please can users report if this has solved the problem? (ignoring for the moment any excessivley bright sky).

**Comment by LoneWolfHT** [comment]
The bright sky is the only think that helps. You still can't see a thing in the forests at night.

> but MC-style stupidly-bright-as-day nighttime is not

I don't think it's up to the engine to decide that. It would be nice if the server had some control over this. IIRC @IhrFussel was talking about that on Discord too

**Comment by paramat** [comment]
> You still can't see a thing in the forests at night.

The issue is, could you in previous versions of MT? We should of course continue what was possible before.
> I don't think it's up to the engine to decide that.

To clarify, what i meant was: MT has, so far, never intended to make unlit nighttime surface terrain as bright as it is in MC, so it is not valid to assume that should be possible currently. However, we might make that possible in future, which i do not oppose, but that is a separate issue.
I just have a personal dislike for how MC makes unlit nighttime surface terrain so bright by default.

**Comment by paramat** [comment]
This issue is lacking detail.

The reddit post was invalid.
References to vague complaints about darkness in MT with no other detail are meaningless. People have always complained about MT being dark, this is mostly because they do not understand that light cannot spread further than 16 nodes, when combined with the light curve being somewhat exponential by necessity this makes light fall off quite rapidly.

So please can those noticing a problem give more detail:
When was there a change in how gamma behaved? Was it between MT 0.4.16 and 5.0.0?
What values of gamma were you using before the change and for what purpose, whaqt was the result you found useful?
What is different now?

@LoneWolfHT by "don't like how dark display_gamma=3 is." do you mean the darkness of unlit surface terrain (open to sky and moonlight) at nighttime?

////////////////////////////////

Certain monitors being darker or people using computers in bright areas is irrelevant because in those situations you would just increase monitor brightness to compensate, because you need to do that for all other use of that computer.

So what this seems to be about, and what gamma actually adjusts, is the brightness of low light levels relative to high light levels.
Gamma applies an exponential transformation to the light curve. A value > 1 increases the contrast of low light levels, raises the brightness of low and mid light levels, and because the highest light level cannot become any brighter, it compresses the visual brightnesses of the high light levels.

Because there may be a bug here i may investigate this, print to terminal the brightness values of the light curve while adjusting light curve parameters,

**Comment by ClobberXD** [comment]
> I think of the requirement this way: Nighttime is always full moon. In real life with full moon it is possible to just see well enough to navigate, but it is still quite dark. This should be possible with all monitors and in all environment brightnesses.

In my experience, with the increased upper bound for `display_gamma`, the terrain is indeed a little brighter, but the horrendously bright midday-ish sky makes the brighter-than-before terrain even harder to see.

**Comment by paramat** [comment]
Thanks ClobberXD, so indeed we need to work on the effect gamma has on night sky (there is an issue).
The light banding when using large alpha is a possible bug currently buried in this issue, so yes please a new issue will be useful as this issue is quite a mess.

LoneWolfHT, is the first post in this issue a report of a decrease in the effectiveness of gamma since a previous version on MT, or just a general request for gamma to be more powerful in its effect? Or maybe both?

**Comment by paramat** [comment]
I think gamma does need a carefully chosen upper value that makes sure that nighttime is always suitably and significantly darker than daytime, otherwise in many situations most players will end up making night as bright as day to try to gain advantage over other players, which would be a disgusting result (see the first post about how players set gamma in CTF).
So i suggest that, clientside, night can be made no brighter than Minecraft night, which is fairly bright but tastefully so.

Any more powerful brightening feature needs to be server-controlled or limited to creative mode.

**Comment by Calinou** [comment]
> otherwise in many situations most players will end up making night as bright as day to try to gain advantage over other players, which would be a disgusting result (see the first post about how players set gamma in CTF).

This can already be achieved by adjusting monitor settings (or using a GLSL color correction shader), so I wouldn't try to restrict it too much.

**Comment by paramat** [comment]
I expected that argument to come up =)

Making a monitor extremely bright is not a practical cheat, as bright areas, HUD, formspecs and general monitor glow will be painful.
Graphics driver settings or a special shader are quite an effort to set up, and beyond the understanding and ability of most players, especially the 95% on Android, so those workarounds will not be used much.

The difference is that gamma or a game setting is very straightforward to alter, so will be widely used to gain advantage, so limiting that will be very effective in minimising this kind of behaviour.

**Comment by paramat** [comment]
Some investigation has clarified the situation:

Here i am using a mod i wrote that creates an underground chamber with a pure white floor. Either placing a light source on the floor, or digging a 1-node shaft to the surface to let a column of light enter, allows investigating lighting.

Each screenshot shows all light levels 0-14 or 0-15 positioned from image left edge to 
centre.
The first of each screenshot pair is lighting defaults, gamma = 1. The second of each pair is gamma = 10 (the current maximum).
The first pair is artificial light of level 14.
The second pair is a column of daylight.
The third pair is a column of night light.

![light_default](https://user-images.githubusercontent.com/3686677/66946899-d0ed4400-f049-11e9-8afe-a963d7294232.png)

![light_gamma10](https://user-images.githubusercontent.com/3686677/66946932-de0a3300-f049-11e9-934a-72d72a787ac5.png)

![light_nat_default](https://user-images.githubusercontent.com/3686677/66946941-e498aa80-f049-11e9-9867-290610a02198.png)

![light_nat_gamma10](https://user-images.githubusercontent.com/3686677/66946948-e82c3180-f049-11e9-8f8b-1941bab4b3e0.png)

![light_nat_night_default](https://user-images.githubusercontent.com/3686677/66946956-ebbfb880-f049-11e9-9614-23599685ec11.png)

![light_nat_night_gamma10](https://user-images.githubusercontent.com/3686677/66946963-ef533f80-f049-11e9-9963-228a20fe940e.png)

The effect of gamma = 10 is as expected, it is not broken: An extreme jump from level 0 to level 1, then very slight changes from 1 to 14/15.

As you can see, with night light, all light levels 0-14/15 are present and gamma acts as expected, however, extreme gamma does not make night light bright, it only causes a subtle change to low light levels.
We have been looking in the wrong place, the brightness of night light is not determined by alpha/beta/gamma/boost but by something else that makes all light levels of night light visualy darker at night.
We could possibly add a setting to alter this, and this is what this issue is actually about.

So now it is clear that gamma is not effective for making night light significantly brighter, it only makes artificial light brighter.

**Comment by v-rob** [comment]
Here's some screenshots at midnight:

0.4.16, gamma 2.2 (default):

![screenshot_20191016_145913](https://user-images.githubusercontent.com/31123645/66962570-2b74a900-f026-11e9-9809-7e0806918ce8.png)

5.1.0, gamma 1.0 (default):
![screenshot_20191016_150110](https://user-images.githubusercontent.com/31123645/66962592-3f200f80-f026-11e9-85b3-167862ced2ed.png)

5.1.0, gamma 2.2:
![screenshot_20191016_145706](https://user-images.githubusercontent.com/31123645/66962582-34fe1100-f026-11e9-84a9-6179f5c7990d.png)

So yeah, sky is really the only big difference in blackness.  I think gamma should at least change the brightness of the terrain a tiny bit because the bright sky with pitch black terrain is ridiculous.

**Comment by paramat** [comment]
Thanks. It is good to see a comparison with 0.4.16, terrain has become slightly darker. So perhaps whatever controls the brightness of nightlight could have its default value adjusted. The brightness of 0.4.16 terrain seems suitable for a moonlit night.
I might investigate this.

> I think gamma should at least change the brightness of the terrain a tiny bit

It does. A tiny bit =)
Anyway, as explained above, gamma is the wrong thing to work on, it also makes sky bright so is the cause of the bright sky problem. The thing to work on for brighter terrain is elsewhere.

**Comment by paramat** [comment]
So in fact, raising the gamma upper limit was a mistake, because it does not help what we thought it would help. The result now will be, in competitive situations, players using gamma = 10 to make artificial light and daylight extend as far as possible to try to gain an advantage, making artifiical light and daylight spread disgustingly saturated (see my tests above). Any player with more taste who does not will then feel they have to also to not be at a disadvantage, so everyone will end up doing this.

As i somewhat suspected, gamma = 10 is a ridiculously extreme exponential transformation for the light curve.
Likewise, the limits for alpha/beat/boost may need to be less extreme.

My head is deep into this now so i have self-assigned.
I will make a PR to revert the gamma limit back to 3.
I will make a PR to make night light the same brightness it was in 0.4.15/0.4.16, which is what people actually want.
Then we could perhaps have a server-controlled 'player:set_night_brightness()' so that a server can set this for players if desired, this cannot be clientside for obvious reasons.

**Comment by paramat** [comment]
Nightlight brightness is set by the first value in the day-night ratio table:
https://github.com/minetest/minetest/blob/b7e358703fd6f828423c2e6622c0740669eb1d7a/src/daynightratio.h#L33
Here are screenshots for the default 150 and a test of 250:

![screenshot_20191017_175154](https://user-images.githubusercontent.com/3686677/67030577-9b0e9500-f107-11e9-8794-b03b064a2ab0.png)

![screenshot_20191017_175306](https://user-images.githubusercontent.com/3686677/67030587-9ea21c00-f107-11e9-9b0c-645aeb613c5f.png)

If i tune the lower values nightlight can be made slightly brighter to match 0.4.15/0.4.16.

**Comment by paramat** [comment]
I tested nightlight in 0.4.15 and 0.4.16.
There was a significant change to lighting between 0.4.15 and 0.4.16, as well as the changes between 0.4.16 and 5.0.1.
All screenshots are of a column of 'open to sky' nightlight falling on pure white nodes in an underground chamber, with shaders off.

![nightlight0415](https://user-images.githubusercontent.com/3686677/67047259-e5a10900-f129-11e9-9c74-13382bfafeac.png)

^ 0.4.15

![nightlight0416](https://user-images.githubusercontent.com/3686677/67047474-4892a000-f12a-11e9-939b-3e5958aa603d.png)

^ 0.4.16

![light_nat_night_default510](https://user-images.githubusercontent.com/3686677/67047520-606a2400-f12a-11e9-91c6-13ab75cd8788.png)

^ 5.1.0

I will make a PR to make the maximum brightness (central node, open to sky) match the brightest of 0.4.15 and 0.4.16.

**Comment by paramat** [comment]
Also, just to remind myself, i should edit the settings comments for the lighting parameters to avoid the misunderstanding about MT gamma.

The problem with using the word 'gamma' is that it implies a certain conventional behaviour. MT gamma applies in the conventionally understood way to the values of the MT light curve, but the resulting light curve is then darkened for nightlight. So MT gamma is not applied to the final resulting brightness of MT lighting. This has probably added to the misunderstanding, with users expecting MT gamma to significantly brighten natural nightlight.

**Comment by paramat** [comment]
First PR #9053

**Comment by paramat** [comment]
PR #9054
