### ISSUE TITLE
Segfault caused by chat sending scrollbar change

### ISSUE THREAD

**Issue by v-rob** [minetest/minetest#8587]
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.1
```

##### OS / Hardware
Operating system: Windows 10, Linux Mint
CPU: Intel something-or-other

##### Summary
If you have a formspec with a scrollbar, and you send the value using `minetest.chat_send_all` _without_ using `minetest.explode_scrollbar_event`, after closing the form, Minetest will give the following error and segfault: `WARNING[Server]: ScriptApiBase::objectrefGetOrCreate(): Pushing ObjectRef to removed/deactivated object, this is probably a bug.`

##### Steps to reproduce
Paste the following code in any file, enter Minetest, press space to open the form, move the scrollbar and notice the chat, and then close the form.

```lua
minetest.register_globalstep(function(dtime)
        local player = minetest.get_player_by_name("singleplayer")
        if player then
                local controls = player:get_player_control()
                if controls.jump then
                        minetest.show_formspec("singleplayer", "formspec:test", 
					"size[10,1]"..
					"scrollbar[0,0;10,1;;name;0]"..
                        "")
                end
                player:set_look_vertical(math.rad(0))
        end
end)

minetest.register_on_player_receive_fields(function(player, formname, fields)
        if not player or not formname then
                return
        end
	minetest.chat_send_all(fields.name)
end)
```

**Comment by DS-Minetest** [comment]
I was able to reproduce with this exact code.
However, if I remove the "player:set_look_vertical(math.rad(0))", there's just a lua crash because `fields.name` is `nil` (which it should be as just esc is pressed) and the warning.
A warning however, that happens on a crash is probably not so problematic.

I've replaced the chat sending line with `crash()`, if I closed the formspec with esc, the described crash happens, if I moved the scrollbar (or at least tried to), I got a gray screen.
