### ISSUE TITLE
Pre-compiled headers for MT

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#8620]
Compiling takes a **lot** of time. This is true for incremental builds as well (i.e. re-compiling only the translation units that have changed). But a lot of time can be saved by using pre-compiled headers, as the non-MT header files take up a significant chunk of MT's compile-time. Pre-compiled headers can greatly reduce compile-time by pre-compiling the headers that don't change (or change very rarely), and compiling only the contents of the changed .cpp file itself when re-compiling. We can add all the headers we use, from C++ standard library, STL, Irrlicht, and Lua to a new header file (say, `pch.h`), and set it up as a pre-compiled header.

As almost all the files are going to be touched in the process, there is a (very) slight chance of conflicts with other PRs, but they'd just be a couple of lines, if at all. So I wouldn't worry much, from that angle.

I'm more than willing to setup pre-compiled headers for MT, if there's no objections from the core devs. Thanks in advance.

**Comment by Calinou** [comment]
By the way, there are a few other ways to speed up compilation:

- Use Ninja instead of GNU Make when generating build configuration (`cmake -G Ninja`). It seems to work well with Minetest. Ninja also uses multiple CPU threads by default, and offers more concise output when there are no errors 
- On Linux or macOS, install [ccache](https://ccache.dev/) so that some files can be directly pulled from the cache.
- Overclock your CPU if you can :slightly_smiling_face:

Using [LLD](https://lld.llvm.org/) for linking may also be a possibility, but I haven't tried it yet with Minetest.

**Comment by ClobberXD** [comment]
I do plan on exploring Ninja; how does it differ from `make -j` though? I'll also check out ccache. Thanks for your suggestions. :)

**Comment by Calinou** [comment]
> I do plan on exploring Ninja; how does it differ from make -j though?

Ninja is a simpler task runner than GNU make, focusing on high performance rather than convenience (when writing build files by hand, which you don't do with CMake anyway).

Note that you should generally never use `make -j`, as it will spawn an unlimited number of jobs. Use `-j$(nproc)` (Linux) or `-j$(sysctl -n hw.logicalcpu)` (macOS) instead.

**Comment by paramat** [comment]
What are the disadvantages of pre-compiled headers?

**Comment by ClobberXD** [comment]
> https://github.com/minetest/minetest/issues/8620#issuecomment-504784713

None that I know of. I'll also try my best to implement this without adding any cmake "library" to MT.

**Comment by devshgraphicsprogramming** [comment]
@ClobberXD this CMake function works for GCC and MSVC:
https://github.com/buildaworldnet/IrrlichtBAW/blob/master/cmake/add_pch.cmake

No idea how to make it work for Clang.

Aside from that `ccache` can be enabled optionally:
https://github.com/buildaworldnet/IrrlichtBAW/blob/master/CMakeLists.txt#L23

Gold not LDD is the linker to use on GCC (it can do threaded linking and LTO).

**Comment by ClobberXD** [comment]
> @ClobberXD this CMake function works for GCC and MSVC:
> https://github.com/buildaworldnet/IrrlichtBAW/blob/master/cmake/add_pch.cmake

Wow, this simplifies things a lot! Thanks! :)

I'll also look into Gold and PCH for Clang.

**Comment by devshgraphicsprogramming** [comment]
> I'll also look into Gold and PCH for Clang.

Maybe try compile our engine with Clang?

**Comment by numberZero** [comment]
Precompiled headers suck. Really. The reason is that unlike [modules](https://clang.llvm.org/docs/Modules.html), you can only have *one* precompiled header, that you are to fill with all the libraries used. But. Not sure of MSVC, but with GCC too large PCH only slows compilation down. This way, you can’t do just what PCHs are for: precompile the heaviest headers.

What could help *incremental* builds is generating a PCH per source file. This way it won’t be too large, so might help more.

**Comment by ClobberXD** [comment]
> Precompiled headers suck. Really. The reason is that unlike modules, you can only have one precompiled header, that you are to fill with all the libraries used. But. Not sure of MSVC, but with GCC too large PCH only slows compilation down. This way, you can’t do just what PCHs are for: precompile the heaviest headers.

Haven't heard of this issue anywhere else, thanks for the info. I'll play with PCH for a bit, and I'll post the results in this issue. I really hope MT's PCH wouldn't cross that threshold. :)

**Comment by ClobberXD** [comment]
@devshgraphicsprogramming It seems like the `add_pch.cmake` script automatically enables `FORCEINCLUDE` when using GCC. This is a problem as MT has a couple of `.c` files as well, and including the C++ PCH in the `.c` files would throw a compile-time error. Is there any way to turn off `FORCEINCLUDE`, or disable it for certain files?

**Comment by ClobberXD** [comment]
I found the following CMake script-let to set up pre-compiled headers for clang:

```cmake
# add the pch custom target as a dependency
add_dependencies(corelib pch)

# add the flag
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -include-pch ${CMAKE_CURRENT_BINARY_DIR}/stdinc.hpp.pch")

# target
add_custom_target(pch COMMAND clang -x c++-header ${CMAKE_CURRENT_SOURCE_DIR}/src/stdinc.hpp -o ${CMAKE_CURRENT_BINARY_DIR}/stdinc.hpp.pch)
```

(courtesy: https://stackoverflow.com/a/54207342)

I've no idea how that works (CMake noob), but I'll give it a shot.

**Comment by paramat** [comment]
numberZero confirms there is a disadvantage, and i don't think compilation time is as much of a problem as stated.
It seems to me not worth doing :-1:

**Comment by numberZero** [comment]
@ClobberXD That effectively does that force-include, but only for C++ (thus *CXX* flags, CXX is CMake’s name for C++). For GCC you would just `-include`. Also not sure whether that is valid, GCC requires compilation options be the same for PCH and source code. It would be better to somehow make CMake compile it, maybe marking the file as C++ code...

@paramat On performance, my test could be incorrect, and compilation time is really annoying.

**Comment by paramat** [comment]
Ok, but this point seems still valid:
> Precompiled headers suck. Really. The reason is that unlike modules, you can only have one precompiled header, that you are to fill with all the libraries used.

**Comment by devshgraphicsprogramming** [comment]
> you can only have one precompiled header

Where did you read that?
Only one per compiled file, you can have different PCH per project component (per pseudo-lib).

The number one thing to make sure, is that your code produces zero or little errors, you'd be surprised how much a few thousand errors can slow down compilation just due to stdout pressure.

**Comment by numberZero** [comment]
> Only one per compiled file

That’s exactly the problem. You need to stuff everything into it.

> you'd be surprised how much a few thousand messages can slow down compilation just due to stdout pressure.

I’d not. I know TTYs are slow, even if they are just emulators. /dev/null is much faster, although generating all the output still takes some time.

Anyway, see the PR:
