### ISSUE TITLE
Add mapgen "The Void"

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#8657]
## Problem

If you want to build a map like a Skyblock map there is no easy way to start. You need a mod or whatever to have a starting point in a singlenode map

## Solutions

Add a simple mapgen that generates a square plane of cobble without any further decoration at the center of the world

**Comment by LoneWolfHT** [comment]
This is something for a mod IMO. You can remove it later when you post your map

**Comment by MarkuBu** [comment]
Of course. But where can I find such a mod? I need to ask in the forum or chat because I don't know what to look for.

Let's assume I'm new to Minetest and want to build a map. I have to register in the forum or join a chat just to ask for this mod. And to be honest: Although I've known Minetest for years, I don't know what to look for. I'd have to ask because I don't know what terms to look for.

That's why I open a feature request and this would make singlenode obsolete. If a mod recommends singlenode it should be specified in the code

**Comment by style-nine** [comment]
Sounds like a simple thing to find: https://github.com/ac-minetest/skyblock/tree/master/skyblock

**Comment by MarkuBu** [comment]
I don't search for a skyblock mod. That ws just an example

**Comment by CBugDCoder** [comment]
This is what you are looking for: https://forum.minetest.net/viewtopic.php?f=11&t=17493

**Comment by MarkuBu** [comment]
Basically yes. But no one will find this except he knows the search terms.

As mapgen it would make more sense to me

**Comment by paramat** [comment]
The singlenode mapgen is for this usage, it is for mods to add nodes to in whatever way they want, for example a starting node (or nodes) for a skyblock world, which is very easy to code in a mod.

A dedicated skyblock mapgen would therefore be duplicating singlenode and is redundant.
It is inflexible because the mapgen would dictate the number and dimensions of the starting nodes, and what nodes to use. Everyone will want something different for a starting platform, and want different spawning behaviours, which is why it should be done by a mod in singlenode.

> But where can I find such a mod? I need to ask in the forum or chat because I don't know what to look for.
Let's assume I'm new to Minetest and want to build a map. I have to register in the forum or join a chat just to ask for this mod.

Arguing that Minetest users are incapable of looking at or using the forum, or searching for mods is very silly, this is what Minetest is all about and players aren't that lazy or stupid.
It's not an unreasonable suggestion that players join the forum, most players will want to anyway. To search for mods you don't even need to join the forum.
You are therefore arguing for things to be added to the engine that don't belong in the engine. With this logic, everything will have to be in the engine because 'players aren't able to, and shouldn't be expected to, use mods'.

> Basically yes. But no one will find this except he knows the search terms.

> And to be honest: Although I've known Minetest for years, I don't know what to look for. I'd have to ask because I don't know what terms to look for.

I don't believe that at all, it's not difficult to come up with a 'skyblock' search term, you refer to 'skyblock' in your 1st post.
I just opened the MT forum and searched under 'skyblock', bottom of 1st page of results is 'Start-a-node, which links to 'The Origin' mod. Bottom of 2nd page of results is 'The Origin' mod.

The CDB makes it even easier to find mods. I found 'The Origin' by searching under 'singlenode'. Unfortunately 'skyblock' had no results but more mods and improved descriptions will address that.

> That's why I open a feature request and this would make singlenode obsolete.

It won't be obsolete, singlenode is for far more than just a skyblock platform. Most Lua mapgens use it.

:-1:
