### ISSUE TITLE
Increase world dimension

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#8660]
## Problem
World size is not big enough. Especially if you have mods adding 4 or more dimensions, it is possible that you soon reach the border of map or dimension.

## Solutions
Make the worlds **bigger**. Right now there's only *n* (I think it's 2) bytes available to store each coordinate, which leads to a max world size of about 64000^3. This probably is so that the resulting numbers still fit in 6 bytes (Java and probably also C int size). Increase this "n".
With "only" 20 bits, maps with a size of 1048576^3 (more than a million!) could be stored. This would bring Minetest closer to it's promise of offering "an infinite world".
Aaand, it would still fit into a long, with it's 60 bits total (long is 64 bits=8 bytes). Most processors today are x64 anyway, and thus have no problem dealing with longs.

## Concerns
As of now, I see the following concerns : 
- Fundamental code change required
- DBMS might have some trouble dealing with it (?)
- Might break backwards compatibility with old maps
- ???

## Alternatives
See https://github.com/minetest/minetest/issues/4428

## Implementation
I would leave the implementation details up to the core devs.
Take this issue just as an idea showing what could be possible.

**Comment by style-nine** [comment]
It's a signed 16 bit issue, is what it is. Just bump it up to 32 bits, and you mostly solve this problem.

**Comment by SmallJoker** [comment]
You guys never seem to get tired requesting this feature although it has been discussed so many times before.
https://forum.minetest.net/viewtopic.php?f=5&t=20333
https://forum.minetest.net/viewtopic.php?f=3&t=18763
https://forum.minetest.net/viewtopic.php?f=5&t=16774

Here's a few reasons so you're not so upset about this decision:
 * Imagine teleporting to any high number coordinate. It'll become insanely complicated
 * Map has to be backwards-compatible, which is barely possible with the key size we currently use
 * Have you ever used the entire space to build on? No, you didn't, and you'll never have the time to do that because it's simply too large already to use the entire space.

This madness is entirely mind-based where you're upset about these limits just because the numbers appear so small.

**Comment by style-nine** [comment]
You could already just about add "dimensions" with all the vertical space, if that's what you're after. Just put in a different dimension every 4096 blocks and bedrock between. You could easily define 14 or 15 layers for every world.

**Comment by paramat** [comment]
It's possible that we might switch to s32 co-ordinates sometime in the future, but it's such a big and disruptive task it's not worth opening an issue about. The core devs are aware of the possibility and always keep it mind, and will decide if or when to do it, independent of any requests for it.
I agree it's low priority, the current world size is reasonable, no-one has got remotely close to filling a world even just on the surface let alone in 3D.

The spaciousness of a world is affected far more by the minimum dimension than the maximum, so our worlds are actually far more spacious then MC's ridiculous 256 node height.

**Comment by MarkuBu** [comment]
Even in Minecraft you can't use the full space. If you are about 132000 blocks away from the center you can notice the first issues and after about 4.2 Million Blocks you can fall to solid ground into the void. 

https://www.youtube.com/watch?v=tyDxEOoHMgg

Even if Minecraft offers a huge map you can't use it. The usable space is limited to a fraction of the available map space. But it is still much more than Minetest offers.

But to be honest: did you ever reached the border of a map in a regular game without cheating?

**Comment by benrob0329** [comment]
>But to be honest: did you ever reached the border of a map in a regular game without cheating?

Yes, I mean I might've abused a bug in the server's sprinting system but I still would've made it without. I was on a resource gathering mission to collect a _lot_ of cactus, so I walked in one direction and grabbed any cacti I found. Eventually I happened across the great wall of CONTENT_IGNORE and had to turn around.

**Comment by LoneWolfHT** [comment]
> But to be honest: did you ever reached the border of a map in a regular game without cheating?

Yes. I even raced another player around two sides of it. And there was no sprint mod on the server, we walked/boated the whole way

**Comment by benrob0329** [comment]
For the time being, keeping the map-size as-is is fine. Its more than big enough for single player, and if servers start becoming cramp they can start building up.

**Comment by Kezii** [comment]
Sorry if I bump this issue but,

> This madness is entirely mind-based where you're upset about these limits just because the numbers appear so small.

It's not uncommon even in small minecraft vanilla servers to build bases in the tens of thousands, on minetest this is already impossible, on minecraft anarchy servers it's common to build in the millions

Also, large scale mod projects like https://www.youtube.com/watch?v=0eyyuNvKNzw are impossible

If minetest wants to be an "engine" it should support this usecase, the website boasts about "Enormous Maps" but every minecraft player knows that 30km is very very little, it's kinda ridiculous

I think this issue should be reopened and should stay open, if "You guys never seem to get tired requesting this feature" it's because it's important for a lot of (future) use cases

**Comment by paramat** [comment]
I wrote above:
> It's possible that we might switch to s32 co-ordinates in the distant future, but it's a big and disruptive task. The core devs are aware of the possibility and always keep it mind, and will decide if or when to do it, independent of any requests for it.
I agree it's low priority,

Even i would 'like' slightly larger worlds to give me more room for my large-scale mapgens, but due to the size of the task i am not officially supporting the request, yet.
Big task, low priority. Besides, no core dev support for over a year, so issue remains closed.

**Comment by pyrollo** [comment]
This change could only occur in a major major version as it implies a complete rewrite of map management, database backends and probably many other stuff (very likely to break all backwards compatibilities, including map files).

If it's only for increasing map size, the effort wont worth it.

It could worth it if other major changes comes with it:
- Increase number of possible node types;
- Add more params or change param mechanism;
- Change in metadata/timers;
- Add a fourth dimension (instead of world stacking);

But this is like restarting from scratch.

**Comment by rubenwardy** [comment]
It won't be a complete rewrite, you just need to change the hashes, position sizes, and then make sure everything has the correct space to avoid overflows

You could probably fairly easily migrate maps, but network compatibility would be more difficult - I'm not sure how many packets reference hashes and positions. It's acceptable for old clients to be unable to exceed 32km, but new clients to be able to

**Comment by Kezii** [comment]
It is rumored that Mojang is working to move the world border from 30 milion to the bilions

https://www.youtube.com/watch?v=tvq0atr24W4

**Comment by paramat** [comment]
Seemed interesting, but the video has a clickbait title and it turns out AntVenom is only speculating on very weak evidence. That is not even 'rumour'.
Makes no difference to MT if it did happen.

**Comment by tigercoding56** [comment]
> Seemed interesting, but the video has a clickbait title and it turns out AntVenom is only speculating on very weak evidence. That is not even 'rumour'. Makes no difference to MT if it did happen.

 30 million is much larger than the minetest world size  anyways

**Comment by rollerozxa** [comment]
Minecraft Bedrock Edition also has noticeable jittering occuring as early as at 16k blocks out, worsening at 32k where movement begins to break down. Do you think we should replicate this as well?

**Comment by mk-pmb** [comment]
Nope, the engine itself should tend towards reliable precision movement and no jittering. When someone wants to add jitter or redefine movement behavior, they can add it as a mod, and the engine will reliably and precisely enact the exact jitter and movement requested by the mod.

**Comment by Kezii** [comment]
> Minecraft Bedrock Edition also has noticeable jittering occuring as early as at 16k blocks out, worsening at 32k where movement begins to break down. Do you think we should replicate this as well?
This is such a stupid argument

**Comment by appgurueu** [comment]
> This is such a stupid argument

No, it's an important addition to an unfair "Minetest vs Minecraft" comparison.

**Comment by tigercoding56** [comment]
why are we even comparing minecraft and minetest in the first place ? this issue  clearly says increase world dimension which can be interpreted as add a  4th dimension or world switching in game via lua code (per player)

**Comment by mk-pmb** [comment]
>  which can be interpreted as add a 4th dimension

Please read the original opening post again.

**Comment by Kezii** [comment]
There's this thing your competitor does better than you by 3 orders of magnitude: you can either accept that there is a problem, keep the issues open and at least have a discussion, or you can put your head under the sand and delude yourself to not "compare minecraft and minetest" in a stupid excuse to do nothing

Get a grip on reality, minecraft is minetest's main competitor, it's a giant piece of software with 1000x your userbase, you can't ignore that, you can't delude yourself that the rest of the world is not comparing minecraft and minetest. 
The world size of minetest is laughably small*, y'all can't go around forever boasting this ridiculous number as it's something great, unless you are trying to get laughed at, and run minetest's popularity into the ground. From this and dozens of other issues where the minetest community seems to have this cult about doing things the shit way

 \*  in the directions that MATTER like THE HORIZONTAL SURFACE OF THE WORLD, nobody cares about going 60km up in the sky, that's not how the real word works, how humans work, how a POV game engine should work, this is an obvious desing fuckup from the original minetest developer and you should stop finding excuses

**Comment by Kezii** [comment]
Recognizing that a problem exists is not a "project goal", it doesn't take manpower and it's absolutely something a leisure project can compete with
I'm not asking to have this feature done, I don't even care about this feature, that ship has sailed. I'm asking people to stop inventing more and more absurd justifications for something that is objectively bad design

Again: this is a first person POV game, where you walk horizontally in a realistic fashion, do you **really** think, from the bottom of your heart, that digging 30km down or building 30km up is something you are going to do? And that is somehow more important and should take the place of having an XZ size that is bigger than a small county? Do you work that way in real life, on in any other first person game? 

> that's your opportunity to jump in, fork the project, and fix it.

yeah and then I'll have the opportunity to have a 6 months long discussion about getting that merged, leading to nowhere as usual

I don't care about a technical solution, I'm annoyed by the never ending justification of obvious technical debt

**Comment by mk-pmb** [comment]
> have a 6 months long discussion about getting that merged,

Nah, why merge it back? Give it a new name (FlatTest?) and merge new MineTest code into yours. All the horizontally minded people will prefer your game and not care about MineTest.

**Comment by mk-pmb** [comment]
Another point, I've spent significant time exploring possibilities to extend horizontally and/or in general, because I consider MineTest's current space limitations a shortcoming. Still, my preference doesn't make those an

> obvious technical debt

because the current coordinate system is a choice of project scope: Should this project include ways to go beyond the native limits of the 3D library we use? The devs decided that extending the ranges can be left for other projects to do.

When I explored the ways this could happen, people (not sure if devs) were very helpful in pointing out to me how I'd go about writing my own server that would be compatible with existing MineTest clients: Whenever the client is far enough away from the world origin, teleport them to 0,0,0 and internally (in the server) shift the world origin for that one client connection. My conclusion was that if I spent a few more weeks studying how the existing code works, I could probably make a server plugin that does the origin shifting. I'd then have to deal with the trouble of making the world database deal with that hugeness efficiently. However, life then decided I should do other things first.

So the two features I see needed are:
* Virtual origigin shifting in the server.
* Storage solution for huge worlds. (We can probably borrow from Minecraft here. mcaselector should have open-source code for at least reading their format.)

I do not see why those concerns should be part of the core MineTest project. They would distract from lots of the features that alreeady *are* in MineTest.

**Comment by Secret-chest** [comment]
Remember the current size is only 60 km!

**Comment by mk-pmb** [comment]
> 60^3 km to be exact

Did you mean (60 km)³ or maybe 60³ km³?

**Comment by Secret-chest** [comment]
> > Remember the current size is only 60 km!
> 
> 
> 
> 
> 60^3 km to be exact

Can you even fit 3 small IRL towns in it? No.

**Comment by mk-pmb** [comment]
> I think increasing the world size is justified.

Yeah. I think we had agreement on this even a year ago. Nobody resists. The way forward is to find volunteers that make it happen.

@appgurueu Could you edit your opening post to add a big fat hint like

> -----
>
> # Volunteers needed!<br>YOU can help increase world size NOW!
>
> Read the thread for hints about how.
>
> -----

? That might help steer future discussion in a more productive direction.

**Comment by appgurueu** [comment]
> > I think increasing the world size is justified.
> 
> Yeah. I think we had agreement on this even a year ago. Nobody resists. The way forward is to find volunteers that make it happen.
> 
> @appgurueu Could you edit your opening post to add a big fat hint like
> 
> > April 2023: Volunteers needed!YOU can help increase world size NOW!
> > Read the thread for hints about how.
> 
> ? That might help steer future discussion in a more productive direction.

I'm not sure whether core dev resources would be available to prioritize reviewing such large changes. This probably hasn't changed since the "breaking world limits" PR days. We need more core dev time, not more contributor time as the pull request counter approaching 100 again clearly shows.

Long time contributors should perhaps first strive to be made a core dev if they have reached a sufficient technical understanding of C++ and the codebase.

**Comment by mk-pmb** [comment]
> I'm not sure whether core dev resources would be available to prioritize reviewing such large changes.

I stand by my opinion above that the world size expansion stuff should stay out of scope of the original MineTest project and thus should not be merged. Thus, the core devs won't have to care except maybe for some adapter code, but I think we can postpone that aspect until adapter code actually materializes.

> Long time contributors should perhaps first strive to be made a core dev

They should do whatever they consider the best use of their time. However, I guess if one of the long time contributors would have been interested in tackling the world expantion, they would have announced their effort in this thread long ago. I thus expect that whoever will start the world expansion effort, will be a new face. Another reason why it would be good to make the expansion stuff a separate project, because then the new face can reign unencumbered, without being slowed down by obtaining consent for any experiment.

**Comment by appgurueu** [comment]
> > I'm not sure whether core dev resources would be available to prioritize reviewing such large changes.
> 
> I stand by my opinion above that the world size expansion stuff should stay out of scope of the original MineTest project and thus should not be merged. That way, the core devs won't have to care except maybe for some adapter code, but I think we can postpone that aspect until adapter code actually materializes.
> 
> > Long time contributors should perhaps first strive to be made a core dev
> 
> They should do whatever they consider the best use of their time. However, I guess if one of the long time contributors would have been interested in tackling the world expansion, they would have announced their effort in this thread long ago. I expect instead that whoever will start the world expansion effort, will be a new face. Another reason why it would be good to make the expansion stuff a separate project, because then the new face can reign unencumbered, without being slowed down by obtaining consent for any experiment.

Agreed. I've added the following section:

>  ## What should I do?
>
> Current core dev consensus seems to be that this is low-priority, non-trivial and thus won't be added as core dev time is better spent on higher priority and/or lower hanging fruit. Thus people who want to invest their time implementing this feature should, after careful consideration, do so in a separate project, without the expectation of being able to merge their changes back to upstream.

**Comment by mk-pmb** [comment]
Thanks! Let's hope it's visible enough that way.

**Comment by appgurueu** [comment]
It's (60 km)³, and somehow ~300 servers seem to run just fine under this limitation.

**Comment by AndreiSva** [comment]
a server like 2b2t just can't exist on minetest because of the small world size. People go out hundreds of thousands of blocks away from spawn.

**Comment by rollerozxa** [comment]
A server like 2b2t can't exist in modern Minecraft either, considering they're still stuck on a half a decade old version due to newer versions absolutely decimating server performance.

**Comment by AndreiSva** [comment]
2b2t is on 1.19 now

**Comment by Sposito** [comment]
I came here because I wanted to proc gen full south America on Luanti (I had funny ideas about using Fourier decompositions instead of noise maps), for what I have read here, I am scrapping this idea.
I liked the vertical dimensions idea with bedrock layers. Maybe Pacific islands or some Caribbean islands could be a thing (and teleport at map edge.

Question for someone who attempted it: how lighting works in that situation, what about the sky?
And for the folks who work on this project, thanks million! This is amazing, and looking forward to contributing back at some point.

**Comment by Haskely** [comment]
> A server like 2b2t can't exist in modern Minecraft either, considering they're still stuck on a half a decade old version due to newer versions absolutely decimating server performance.

29 March 2024 1.20 Update

6 March 2025 1.21 Update https://www.2b2t.org/

**Comment by Golbinex** [comment]
I find it unfortunate that this issue is closed with "Won't add" tag and "Nobody needs this" reason, since large-scale games/mods that would want to implement multiple worlds have limited options considering the map size and lack of MC-like dimensions.

Obviously developers can't be demanded to implement this, but this issue should be at least open to signalize to possible contributors that developers are willing to merge map expansion PR into the next major release if done properly.

**Comment by sfan5** [comment]
Such a PR in fact exists (#11843), but contributed code isn't "free" from our standpoint.
We need to review, test and maintain any such changes.

**Comment by yunfan** [comment]
640K is enough :D

**Comment by SmallJoker** [comment]
FWIW, 6 years after - here's an update on my ~~beloved~~ response from 2019:

> Imagine teleporting to any high number coordinate. It'll become insanely complicated

Relative teleportation with the `~` notation has been added. Dealing with large numbers could however still be impractical from a player or admin perspective.

> Map has to be backwards-compatible, which is barely possible with the key size we currently use

* Since #15768, newer (migrated) SQLite3 worlds now use separate `x`, `y`, `z` coordinates instead of `0xZZZYYYXXX`. The limit would be far beyond any drive capacity ([up to 8 bytes](https://www.sqlite.org/datatype3.html)).
* Since #16058, PostgreSQL worlds are limited to 2¹⁶ *mapblocks* in each direction, but the [`smallint` data type](https://www.postgresql.org/docs/current/datatype-numeric.html) could be changed. That would however (again) increase the disk usage of any smaller words.
* LevelDB still uses the compact [`0xZZZYYYXXX` format](https://github.com/luanti-org/luanti/blob/5.14.0/src/database/database-leveldb.cpp#L43-L45)

**Comment by chaojian-zhang** [comment]
Regarding "infinite server size", I want to share an comment and ask a question: is there a way to simply travel to a different server (i.e. while attempting to use the same login)? Like [this](https://github.com/luanti-org/luanti/issues/5813).
For my purpose I am fine with 64km^3 per server, but I feel it would be handy to chain servers together - kind of like Second Life/Overte.

If you know of a mod/API that can do that, please let me know!

**Comment by kneekoo** [comment]
> FWIW, 6 years after - here's an update on my ~beloved~ response from 2019:
>  ...
> Relative teleportation with the `~` notation has been added. Dealing with large numbers could however still be impractical from a player or admin perspective.
> ...
> * Since [[no sq] Split blockpos into 3 different columns in sqlite3 map database #15768](https://github.com/luanti-org/luanti/pull/15768), newer (migrated) SQLite3 worlds now use separate `x`, `y`, `z` coordinates instead of `0xZZZYYYXXX`. The limit would be far beyond any drive capacity ([up to 8 bytes](https://www.sqlite.org/datatype3.html)).
> * Since [Switch to smallint for position keys (x,y,z) in postgres backend #16058](https://github.com/luanti-org/luanti/pull/16058), PostgreSQL worlds are limited to 2¹⁶ _mapblocks_ in each direction, but the [`smallint` data type](https://www.postgresql.org/docs/current/datatype-numeric.html) could be changed. That would however (again) increase the disk usage of any smaller words.
> * LevelDB still uses the compact [`0xZZZYYYXXX` format](https://github.com/luanti-org/luanti/blob/5.14.0/src/database/database-leveldb.cpp#L43-L45)

I hope more progress is done towards having bigger worlds. What many people don't consider is how on peaceful servers people enjoy building and they need at least 200-300 square blocks to build something that's not even huge. Such servers only allow 100 players in any one direction away from spawn. Realistically, a 500 square block area is more generous to not only have enough room for future expansions, but also a buffer zone between "lands". And because the terrain and biomes also play a role, few players would choose frozen biomes, oceans, or other difficult biomes to build in, especially when they want some mob farms that require specific biomes.

So the world size cannot be seen strictly as numbers on axes. No perfect grid can be filled to evenly distribute player bases around spawn. Each seed is different, players have different ideas and plans, and the map generation indirectly dictates how players spread across the map.

Then there's the time factor. Old servers end up gaining lots of players. While some quit playing after a while, most of the time you can't tell if they ever plan to come back. Even when assuming they never do, some builds are so cool that it would be a pity to reset that terrain to allow someone else to settle in. So long time servers end up having less and less available room for players.

When it comes to singleplayer, which is unaffected by this practical limitation, having bigger worlds allows games to come up with more interesting content in far away places, to make it worth exploring - very rare biomes, structures, cool trails that require long treks, and so on. And because some players also keep their worlds for many years, upgrading the game to newer versions means they would like to experience new content in older worlds, but they'll need plenty of unexplored areas to build new bases with new content. The fact that a non-trivial amount of players don't explore much is beside the point. Not having large worlds limits games and plenty of players who would like to explore more.

**Comment by Stargate38** [comment]
Please remove the "Won't add" tag. This really needs to be implemented. It would also allow people to create their own version of the Minecraft Far Lands, and make this game even more like that one. I see no reason why it couldn't be done, as long as you find a way to keep compatibility with existing savegames/servers.

**Comment by 4Arcturus** [comment]
> This really needs to be implemented.

From [#12142](https://github.com/luanti-org/luanti/pull/12142#issuecomment-1183622517) and [the current roadmap](https://github.com/luanti-org/luanti/issues/16162#issuecomment-3179472959), this feature simply isn't the core dev's priority whatsoever. While we all want this (to varying degrees), there are bigger fish to fry.

It is possible that this may be implemented, but seeing as SSCSMs are the current next big thing, it likely won't be implemented anytime soon.
