### ISSUE TITLE
Builtin dot product

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#8667]
Please add a function for dot product calculations in Minetest

If not (or if it won't be added soon) could you give me a function for it?

**Comment by ExeVirus** [comment]
Hello Extex101, 

I found some code [here](https://gist.github.com/Xeoncross/9511295#file-mathlib-lua-L303), which should allow you to do dot product calculations on any two given vectors. See the commented code on that page from lines 313-317. That should do the dot product for any two equal sized vectors.

As for adding Dot Product to Minetest, I can't say for certain if it will get added (or if it is already added, but not exposed to lua). I'll dig deeper at some point in the future, and hopefully someone more knowledgeable will be able to help you in the meantime.

**Comment by ClobberXD** [comment]
Related: #5564. That PR adds a ton of vector-based functions, incl. dot product, but was closed due to lack of response.

**Comment by DS-Minetest** [comment]
#8515 [(here)](https://github.com/minetest/minetest/pull/8515/files#diff-8a982cc4f6c3442a6a8e049bd22f331fR73) adds a function for calculating the dot product of two vectors (because it's the matrix product of the transposed of the one vector with the other vector).

(@ExeVirus You can click on a line and add a "-L317" to the url to get [this](https://gist.github.com/Xeoncross/9511295#file-mathlib-lua-L313-L317).)

**Comment by Extex101** [comment]
The vector.dot function keeps giving me numbers like this:
1417198.2978446 which makes it kinda unusable
Am I doing something wrong?
