### ISSUE TITLE
Modernization of the Multiplayer tab

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#8669]
![Multiplayer](https://user-images.githubusercontent.com/6764600/61092259-dbde7a00-a445-11e9-8ab3-2c8ec9f47408.jpg)
![minetest](https://user-images.githubusercontent.com/6764600/61092682-8f943980-a447-11e9-941d-972badca3469.jpg)

Simple discussion. I decided to experiment a bit on the Multiplayer tab view.
Do not focus on the background, only on the elements.
1) First, my designer drew new icons instead of the horror that Minetest uses now.
2) Then I removed the annoying 99+ for servers with a three-digit number of players. Now the number does not increase 999, but the “+” looked strange.
3) Is there a scenario in which the server can use damage and creativity? If so, then it is so rare that I decided to combine the icons of a creative server and survival in one position. It saved space on small phone screens as well.
4) Field alignment. Width fields 'Name / Password' - take a look at the width. It seems strange, doesn’t it?
5) The height of the "Search" button. I understand that the formspec is still terrible, but you do not need good vision to understand that you were wrong with the coordinates!
6) Something else?..

I decided not to do PR because not all the proposals will appeal to the community. It seems that so few people in Minetest have a taste and a sense of beauty :)
(Forgive my English too. Often I have to use a translator)

**Comment by LoneWolfHT** [comment]
1: The new icons are fine IMO, although it may be possible to do better ones
2: 99+ doesn't bother me at all. And IMO once you get into the 3-digit numbers it just looks wrong
3: I think I've seen a few out there. IMO creative mode should be a game-side option though. Or the icon type should be decided by a minetest.conf setting like `server_type = <survival/creative/other>`
4: Doesn't bother me too much. But I do think it could use a redesign. Haven't given much thought to that yet though
5: I like how you changed it to use a magnifying glass button :+1:
6: I don't like how the 'remove favorite' button was changed to a trash icon. That suggests you are deleting the server from your serverlist
7: Instead of putting that 'mangled' minetest icon there for non-favorite servers why not just shift the line contents to the left until the gap is filled? Changing the color of the text to a yellow/golden color might be a nice addition too

**Comment by MoNTE48** [comment]
1) 16x16, draw better :) Also icons are drawn in MultiCraft style
2) 99+ looks terrible for my server when there are more than 100 players on it. Using empty space for "+" is very strange.
3) Is MT obliged to take into account any special game modes that are exclusive for a couple of servers? Did not quite understand your idea.
6) I think this is subjective. But it makes the connect button bigger and more visually intuitive.
7) 16x16, I repeat! Even it was very difficult to do it :)
Although do not pay attention to it. This is done because the official MultiCraft servers have a different icon in my client. I meant that the empty space does not look very nice, maybe you should add something to it.

**Comment by LoneWolfHT** [comment]
1: I'd be fine with 16x16 then, I don't think I like the Multicraft style though
2: Ah, maybe some coding could be done to remove th '99+' and set it to the real number if the player count goes over 99+
3: I'll take that back. I just realized one of my reasons were faulty

**Comment by MoNTE48** [comment]
1) I'm not saying that the MC style is Minetest. I say Minetest uses horrible textures. Not only here :)
2) I did it (see screenshot). I changed rounding from _* > 99 = 99+_ to _* > 999 = 999_

**Comment by LoneWolfHT** [comment]
>     2. I did it (see screenshot). I changed rounding from _* > 99 = 99+_ to _* > 999 = 999_

I meant if there are 18 players online then show `18/99+` and if there are 118 players online show `118/150`
In this case the server the players are on has a max of 150

**Comment by MoNTE48** [comment]
999+ : we are again taking away the usable space. It will always be empty if we want to fit the 4th character once
1300 : I'm trying to make the server work stably with 200+ players. My record is about 130. You want a lot

**Comment by paramat** [comment]
> First, my designer drew new icons instead of the horror that Minetest uses now.

> It seems that so few people in Minetest have a taste and a sense of beauty :)

Well, thanks, but actually your icons look far worse, they suffer from 'lumpy edges caused by image scaling' because they don't use the trick MT icons use to avoid this. For the refresh icon there's not much difference between the design of a single arrow circle compared to a double arrow circle, so i can't see what's so horrific about it and i can't see why it needs to be changed. -1 for your icons.
> Is there a scenario in which the server can use damage and creativity? If so, then it is so rare that I decided to combine the icons of a creative server and survival in one position. It saved space on small phone screens as well.

Combining icons has already been discussed and rejected for reasons of clarity, i'll try to find the issue. -1.
> Field alignment. Width fields 'Name / Password' - take a look at the width. It seems strange, doesn’t it?

Keep in mind that the size and alignment of formspec elements varies as screen size varies, so some small alignment problems may only be a result of this particular screen size.
'Name' and 'password' should not be identical in widths to 'address' and 'port' above, because 'name' and 'password' are similar in length, whereas 'port' is shorter than 'address'.
But yes the serverlist extends too far down and there are probably some other valid improvements.
> Then I removed the annoying 99+ for servers with a three-digit number of players. Now the number does not increase 999, but the “+” looked strange.

Good idea. +1.

I'll support a PR for the 99+ -> 999 players change, but nothing else. I think it's best someone else works on formspec alignment. Formspec alignment isn't really 'backporting from MC' so i don't think you should spend time on that.

**Comment by MoNTE48** [comment]
Another item. Perhaps Minetest could use a beautiful background, instead of a translucent rectangle?
Yes, it will partially hide the clouds. But is it the whole menu feature in the clouds?

**Comment by HybridDog** [comment]
As far as I know, the connection speed (green bars) refer to the speed measured by the serverlist server and not to the connection between the player and the server, so it can be very inaccurate. I think the player needs to be informed about this.

**Comment by MoNTE48** [comment]
I have already spoken about testing client side ping. This is something that will be added to the MC in the future and something that MT core devs are unlikely to accept.

**Comment by Mrchiantos** [comment]
Anyway, they tend to refuse anything that does not come from their own team.

**Comment by sindastra** [comment]
I like the suggested blue background with the nice border and the new font.

**Comment by Zughy** [comment]
I think this should be closed because it sounds more of a PR and because #6733 includes it. Also, the whole main menu should be completely redesigned, a thing I'll be glad to do after 5.4 rolls out. These are just a few tweaks that won't solve very much

**Comment by MoNTE48** [comment]
Of course, instead of doing something, it's easier to just close.
"As awful as it looks, it works!" <= FOSS
