### ISSUE TITLE
Add mark_as_public to metadata

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#8687]
## Problem

Currently you need to explicitly mark metadata values as private. 
If you make a mistake, the metadata is public and needs to be sent to the clients.
https://github.com/minetest/minetest/blob/9fe32461540316d9ef06b2f06c02684c36c5fa94/doc/lua_api.txt#L5226
I think that public metadata causes a lot of network traffic and often metadata is redundant for the client.

## Solutions

When setting metadata without marking it as public or private, a warning message could be shown to inform the mod developer.
Metadata which is known to be needed by the client (infotext, inventory, etc.) does not cause a warning message, and the messages are only shown when some setting is enabled.
The mark_as_public function could be added for metadata which is used by the client but has an unusual key.

This can help mod developers to find metadata which is public although the client doesn't need it.

## Alternatives

The mod developer could also use local map saving to find such metadata, but finding the right keys is probably difficult.

## Additional context

‪Mapblocks including their metadata are sent very often I think.

**Comment by LoneWolfHT** [comment]
Why not make it private by default? I didn't even know I could make meta private

**Comment by HybridDog** [comment]
> Why not make it private by default?

I think that formspec can reference to a metadata field.
https://github.com/minetest/minetest/blob/a6f784835244111c90c05b6aae47092c2c5763a7/doc/lua_api.txt#L1894

**Comment by SmallJoker** [comment]
> I think that formspec can reference to a metadata field, where the key can be an arbitrary string.

https://github.com/minetest/minetest/blob/a6f784835244111c90c05b6aae47092c2c5763a7/doc/lua_api.txt#L2092-L2093

> When setting metadata without marking it as public or private, a warning message could be shown to inform the mod developer.

That would be quite spamming in regard to all but a few mods which simply write to the meta data without caring about privacy (because it's not security-relevant). Although I can see that this is needed if you want to explicitly send instead of explicitly prevent from sending metadata.

> Mapblocks including their metadata are sent very often I think.

Yes, that's the case. But most of the data is spent for inventory lists (and item metadata) plus node IDs in the mapblock.

**Comment by paramat** [comment]
Replaced by #10127
