### ISSUE TITLE
Create admin/priveleged user on servers by default

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#8741]
## Problem

If someone joins with the username of the admin (set by `name = admin` in minetest.conf), they can gain privileges undesired by server owner. Currently the server displays warning messages until someone is logged in as this user. As things stand now, there is _almost always_ a time after initial server start in which server privileges can be hijacked.

## Solutions

The user should be created automatically using either:
1. a random password that can be changed via console, or;
2. a password set in config files, having both a `name =` and `password =` makes sense.

**Comment by DS-Minetest** [comment]
You can set `default_password` for the first time that you start your server.

**Comment by SmallJoker** [comment]
FYI: `name` defaults to empty value. As soon you host a server it will be assigned to your name as well. Your issue here seems to be that you'd like to use the same minetest.conf for the client and your dedicated server. Using different files would make more sense in this case.
https://github.com/minetest/minetest/blob/3ad9a8f3a978b41a88ebf8a88690ad658cd132c7/src/defaultsettings.cpp#L32

**Comment by jastevenson303** [comment]
In fact you are warned as such when issuing --terminal
