### ISSUE TITLE
Sunrise / sunset brightness transitions significantly out of sync between shaders enabled and shaders disabled

### ISSUE THREAD

**Issue by Jordach** [minetest/minetest#8806]
##### Minetest version
Minetest 5.1.0-dev-2f879e8b
Minetest 5.1.0-38b94f2
##### OS / Hardware

GPU model: nVidia GTX 1060 (6GB)
OpenGL version: 4.6.0

##### Summary
Sky colours are different between clients that have shaders enabled and those that have shaders disabled. This also expands to how lighting is applied, where changing the time rapidly between light and dark makes the shaderless client update chunks non smoothly, while the shader enabled client smoothly fades to the correct light level.

##### Steps to reproduce
Start a localhost server with either shaders turned off, and other client connecting to the server client with shaders enabled. Put windows side by side, and perform the following commands:

`/set time_speed 100` and `/time 4000`

You should see something like this:
https://www.youtube.com/watch?v=2zRTTXcw_1w

**Comment by paramat** [comment]
> Sky colours are different between clients that have shaders enabled and those that have shaders disabled.

In your video, the full-daytime sky colour seems identical between shaders and non-shaders.
At nighttime, it does look like a different brightness, but not necessarily a different hue, i'm not sure why brightness would differ.

Are you referring to full daytime and full nightime sky colours, or colours during dawn/dusk transitions? If the latter, that is expected due to how lighting transitions are handled differently.
However, is this issue actually about how the brightness transitions are very out-of-sync, even when taking into account the non-smooth / smooth difference?
> This also expands to how lighting is applied, where changing the time rapidly between light and dark makes the shaderless client update chunks non smoothly, while the shader enabled client smoothly fades to the correct light level.

Lighting always alters in steps with shaders disabled and smoothly with shaders enabled, that's just how it is coded, it doesn't depend on time speed.

By the way, looks like you do, but it's important to have the 'directional coloured fog' feature disabled as it alters everything so much.

**Comment by Jordach** [comment]
>By the way, looks like you do, but it's important to have the 'directional coloured fog' feature disabled as it alters everything so much.

Ohohoho, directional fog was kept enabled on purpose.

**Comment by paramat** [comment]
Well, nevermind how it was 7+ years ago, there are sudden lighting changes because it's coded that way.
Please answer my questions.

**Comment by ClobberXD** [comment]
Probably related:

https://github.com/minetest/minetest/blob/e8716ffede885b3041a5fc97557b336d6699abc5/src/environment.cpp#L45-L51

https://github.com/minetest/minetest/blob/e8716ffede885b3041a5fc97557b336d6699abc5/src/daynightratio.h#L22-L72

The function in the second snippet does some extra stuff if `enable_shaders` (aka `smooth`) is true. Those numbers need tweaking, maybe?

**Comment by paramat** [comment]
No answer to questions so i'll assume this issue is for the significant difference in visual brightness during dawn and dusk transitions, changing title.

**Comment by sfan5** [comment]
Please confirm this still happens.

**Comment by Zughy** [comment]
No answer from the author after 5 months, "possible close" label, closing
