### ISSUE TITLE
Add a river system to MGflat

### ISSUE THREAD

**Issue by TumeniNodes** [minetest/minetest#8816]
MGflat already has options to use hills and lakes, it is not a far reach to feel that rivers could be added as an option as well.

I understand some prefer MGflat to be just _flat_ , and there will be some staunch resistance but the fact remains it is very nice having the option to use the hills and lakes provided.
Even better, would be to add the option to have a river system, or even just one, sizable river which winds down the center-ish of the map.
Attempting to adjust the parameters of other mapgens to get this prime landscape can be frustrating and also leaves oddities which look horrible.

An addition of a customizable river(system) would make MGflat one of the best maps provided.
And I am sure it would become a favorite with such an added feature.

I suggest either a system such as ridges from MGv7, or something even easier to customize.

I looked at the guidelines for feature requests and pulled out the bits which suit my needs here.

>Minetest is about:
    Messing around
    Being able to do crappy but interesting stuff which nevertheless is enjoyed by other people

>Keep the common base (the Minetest Engine) as universal as possible.

What could be more "universal" than offering one more, important optional feature to a mapgen to make it even more flexible to the user base?

So I feel this matter justifies a discussion, to see how those here/involved feel about it, and then go from there, or stop here... depending on how the conversation goes.

**Comment by benrob0329** [comment]
Reposting my comment:

>As someone who uses mgflat as a base for a Lua mapgen, a new default setting would break my game. **This is fine**, so as long as it's clearly documented as doing so; this way I can update my code accordingly.

I still feel that bits like this should be defined by the game, and not the engine. But this will likely not happen with our current mapgen code.

**Comment by paramat** [comment]
benrob0329 if optional rivers are added to mgflat they will be disabled by default just like hills and lakes, because 'flat' is the primary usage. So adding the river option won't break existing worlds.
Indeed to have reasonable performance, mapgen stuff is best done in the engine, if the feature is justified.

There have been some requests for rivers in mgflat.
I have been surprised how popular the 'hills' and 'lakes' options are, after initial resistence to my idea from our previous mapgen dev 'hmmmm / kwolekr'.
Rivers do make sense to complete the set of simple optional world features. It would add 1 more 2D noise and be lightweight. So i'm ok with the idea, it just depends on support from other core devs.

Mapgen flat was never intended to only be a featureless flat surface with no other features, even the old 'flat' option in mapgen v6 wasn't like that either. It is intended to be a fully-featured mapgen with large amounts of flat terrain.

**Comment by Wuzzy2** [comment]
Let's discuss some details:

How exactly should the rivers be?

* Should they be at lake level? Or should they have their own height?
* Should they connect to lakes?
* Should water springs spawn in hills?
* Should rivers be endless or have a starting point?
* What to use? River water or normal water?
* Should rivers consider the biome river values so they behave kinda like in `valleys` mapgen, with unique river “styles” per-biome, or should rivers ignore the biome river settings and always use the same “style”?
* Are rivers allowed to form circles? Because that's going to happen if you base them on simple noise alone

**Comment by TumeniNodes** [comment]
> Let's discuss some details:
> 
> How exactly should the rivers be?
> 
>     * Should they be at lake level? Or should they have their own height?

I prefer them at the same level as lakes, personally, and to use normal water.
River water systems are a great idea but, imo, they produce too many oddities.
Of course I also feel river water should be maybe a bit lighter or darker but not an entirely diff colour (especially not the colour of Caribean sea water)

Water hills spawning in hills right now seem best as a mod, due to the numerous issues they would bring atm. It _can_ be done but it may be too costly and messy right now (perhaps later)

I would love for rivers **not** to form circles and/or figure 8s (that annoys me for some reason)

To me, just adding a simple/basic river into the map would be a huge step as it is.
Just one scalable river winding or "meandering" down the center-ish of the map, and which can cut clear through the highest avail scaling of the hills...

Great for building masterpiece bridges, both highland and low lands.
Would be great for making CTF maps
Lots of possibilities....
... but first it has to exist and get the initial bits ironed out and enjoy that for a while before adding more complexity or not.
 Perhaps new mods will be created to do some of what you mentioned... in fact I would almost guarantee they would start popping up soon after
Maybe we just start with that, and then see where it might go in the future.
> 
>     * Should they connect to lakes?
> 
>     * Should water springs spawn in hills?
> 
>     * Should rivers be endless or have a starting point?
> 
>     * What to use? River water or normal water?
> 
>     * Should rivers consider the biome river values so they behave kinda like in `valleys` mapgen, with unique river “styles” per-biome, or should rivers ignore the biome river settings and always use the same “style”?
> 
>     * Are rivers allowed to form circles? Because that's going to happen if you base them on simple noise alone

**Comment by TumeniNodes** [comment]
Sorry for the sloppy mess to follow below, but I had a really annoying morning so Im tired and trying to unwind :P

I prefer them at the same level as lakes, personally, and to use normal water.
River water systems are a great idea but, imo, they produce too many oddities.
Of course I also feel river water should be maybe a bit lighter or darker but not an entirely diff colour (especially not the colour of Caribean sea water)

Water hills spawning in hills right now seem best as a mod, due to the numerous issues they would bring atm. It _can_ be done but it may be too costly and messy right now (perhaps later)

I would love for rivers **not** to form circles and/or figure 8s (that annoys me for some reason)

To me, just adding a simple/basic river into the map would be a huge step as it is.
Just one scalable river winding or "meandering" down the center-ish of the map, and which can cut clear through the highest avail scaling of the hills...

Great for building masterpiece bridges, both highland and low lands.
Would be great for making CTF maps
Lots of possibilities....
... but first it has to exist and get the initial bits ironed out and enjoy that for a while before adding more complexity or not.
 Perhaps new mods will be created to do some of what you mentioned... in fact I would almost guarantee they would start popping up soon after
Maybe we just start with that, and then see where it might go in the future.

**Comment by paramat** [comment]
There are fewer choices than you think =)

*At lake level, as sloping rivers are far too complex, and probably impossible, to implement in mgflat. Besides, if there are no hills then rivers have to be flat like the terrain.

*The river course is defined by 2D noise as in all other mapgens (there's no other known reasonably simple and lightweight way, and rivers in mgflat will be simple because everything else is), so will be random, they will randomly intersect with lakes.

* No water springs in hills for obvious reasons.

* Endless / starting point: See above.

* Which water: Good question. Mgv7 and mgcarpathian use normal water for non-sloping rivers, probably that.

* Rivers are always affected by biomes, whichever water they use.

* River loops: See above, occasionally, unavoidable with noise.

**Comment by TumeniNodes** [comment]
I'd love to see thoughts from other core devs on this...
Perhaps we can take no thoughts as no issues with going ahead? :D j/k

**Comment by LoneWolfHT** [comment]
+1 for this. I just started using flat with hills and lakes for my game. I would love to add rivers too
