### ISSUE TITLE
Heart.png Is Scaled Improperly

### ISSUE THREAD

**Issue by benrob0329** [minetest/minetest#8886]
##### Minetest version

```
5.0.1
```

##### Summary

`heart.png` seems to be scaled to 24x24 pixels, which leaves scaling artifacts and disproportional textures for 16x16 textures.

![hearts](https://gitlab.com/benrob0329/ikea/uploads/0bd86b751363636e22b80b4734f5beb8/hearts-comparison.png)
Top: Scaling As It Is Now
Bottom: Same But With Padding Added To The Texture

See https://gitlab.com/benrob0329/ikea/issues/20

**Comment by Linuxdirk** [comment]
I measured from a screenshot and on my machine hearts are scaled 19x19 pixels.

**Comment by paramat** [comment]
I suspect this is not a bug, but is instead just low quality image scaling behaviour, which has been seen elsewhere in MT. But, might be a bug.

**Comment by Wuzzy2** [comment]
Oh, this explains why my food texture looks oddly distorted in MCL2. Thanks for finding!

**Comment by Linuxdirk** [comment]
> I suspect this is not a bug, but is instead just low quality image scaling behaviour

Is the same scaling method that is used for textures also used for GUI elements? This could explain why it is low quality.

https://github.com/minetest/minetest/issues/8020

**Comment by sfan5** [comment]
Is the issue here that the scaling is low-quality?
Or is it that the texture is being scaled at all?

**Comment by Calinou** [comment]
The texture *should* be scaled, but it should only be scaled by an integer factor. This is an issue with pixel art in general; crisp scaling can only be performed using integer factors, anything else will look blurry (at best) or pixel sizes will be all over the place (at worst).

**Comment by paramat** [comment]
No, image scaling means being able to scale to any size. Only being able to scale by integers would make scaling almost completely unusable, because there is no fine control.
Reasonable looking fine-control scaling is possible.

The first post is a little confusing, but i think it is referring to poor quality image scaling.
Hearts being scaled to 24x24 seems irrelevant and is not an issue, textures are usually 16px and the ideal on-screen size is > 16px, so scaling has to happen.

**Comment by Calinou** [comment]
@paramat In general, we can expect the HUD to always contain pixel art (inventory items, hearts, …), so it'd probably make sense to round the effective GUI scale to the nearest integer.

**Comment by paramat** [comment]
With integer image scaling the initial HUD textures would be forced to be a certain size, instead of 16px or 32px or what the texture maker prefers. It would also break all texture packs.
Forcing to the nearest integer scaling would mostly result in unusable sizes, with the heart and bubble textures and bars being too big or too small. It's not practical.

**Comment by benrob0329** [comment]
The current scaling is unacceptable for pixel art. Also no, it would not be forced to one certain size, it would be forced to it's size times an integer amount.

**Comment by Wuzzy2** [comment]
Hmm, I just noted in the example the scale went from the original image size 16×16 to 24×24. That's a factor of 1.5, i.e. not a power of two.

**Comment by paramat** [comment]
> Also no, it would not be forced to one certain size, it would be forced to it's size times an integer amount.

I'm referring to the initial texture, not the result. But correct, the initial textue would be forced to particular sizes, but this doesn't alter my point.

**Comment by Warr1024** [comment]
When you need to scale an image to a non-integer multiple of its original size, there is no scaling method that gives correct results.

However, there is a scaling method built into MT that gives the _least incorrect_ results.  Enable the `gui_scaling_filter` setting.  It does the equivalent of an integer-up-then-linear-down scale filter.  If your scale is an integer, you'll get integer scaling; if it's not, you'll get the best anti-aliased approximation.

**Comment by SmallJoker** [comment]
Workaround made in #9237.
Same issue as in #2419. The image resize code is the same, and sucks in both places.
