### ISSUE TITLE
Formspec: Style to highlight button on hover

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#8901]
A button (simple or with an image) will be highlighted (e.g with white color) when a user has pointed at it with a mouse cursor. I suggest to add a param to the form element string to enable it: "button/image_button[highlight_by_cursor=bool]"

It's considered to be added for 5.1.0 Formspec Release.

**Comment by ClobberXD** [comment]
If this is implemented, it'd probably be better to integrate this with `style[]` instead.

**Comment by Andrey2470T** [comment]
Probably yes, for instance, `style[<button_name>, button_pointed=color]`. 
Also support for button_exit, image_button, item_image_button and tabheader.

**Comment by paramat** [comment]
A very large proportion of buttons on applications do not change appearence when hovered over, so i can't see why there is any need, can you explain? I realise it can be 'visually nice' but MT is meant to be simple, so this needs significant justification.
I'm also wary of adding unnecessary stuff to formspecs when we intend to replace them.

**Comment by Andrey2470T** [comment]
But most games including minecraft has this feature, therefore why would MT not have it also? Just for attaching more animating to the elements and that creates good look.

**Comment by DS-Minetest** [comment]
>A very large proportion of buttons on applications do not change appearence when hovered over

And maybe an even larger proportion of buttons do change look when they are hovered over.

Games GUIs should be able to be hedonistic and to look and feel nice.

**Comment by Df458** [comment]
> A very large proportion of buttons on applications do not change appearence when hovered over

I would be curious to know where you got that idea. GTK+, QT, and WPF all have this behaviour out-of-the-box, covering most modern applications running on both Windows and Linux platforms. Indeed, even websites (like Github) follow this pattern regularly.

As for justification, this is a standard UX feature found everywhere. It exists because it both serves as instant feedback to a user that an action can be performed (vs disabled controls, which almost never follow this pattern), and also lets a user see at a glance what they're about to click on without having to focus on where their mouse is.

But just for good measure, here's a third reason to have this: Minetest already does it, presumably for these very reasons, with inventory slots. Ideally, the rest of the UI should follow suit. I can certainly sympathize with not wanting to pile more on a system that you intend to remove, but given that the feature is already used _somewhere_ you'll need it for the replacement anyway.

**Comment by paramat** [comment]
I'm not too bothered about this, but:

Most games and MC are commercial with paid developers who have time, unlike MT. So MT has to be simpler.
MT is meant to be simple, it's a central philosophy, for maintainability, see the roadmaps.

I'm not opposing, and i agree it looks nice and is rather desirable. But also, when a button doesn't alter appearence it's not particularly offensive.

**Comment by rubenwardy** [comment]
this would only require editing the guiButton.cpp file if you don't make it a style option

**Comment by Df458** [comment]
Indeed, after a quick look the change looks quite simple. Unless someone else wants to do it, I'll see if I can get a pull request for this up within the next week or so.
