### ISSUE TITLE
Add a mapgen flag for ore generation

### ISSUE THREAD

**Issue by mbartlett21** [minetest/minetest#8903]
## Problem

I would like a flat mapgen that is just stone without any ores

## Solutions

An option in flat mapgen settings to turn ores off

## Alternatives

Make my own subgame that does not implement ores

**Comment by jastevenson303** [comment]
I think if u remove the mapgen mod this will do what u want

**Comment by TumeniNodes** [comment]
An option to generate the map without ores would impact several areas of the code.
In this instance, it is probably best for you to make your own custom changes to remove ores, as adding this option would require much additional code, which honestly is not justified due to one request, from a single individual.

**Comment by Tomracer** [comment]
But i like the idea! Would be cool when a subgame exists for that!

**Comment by paramat** [comment]
`mg_flags = caves,dungeons,light,decorations,biomes`
Hmm we don't have a mapgen flag for ores, that could possibly be added, since it is a major component of mapgen. Quite a good idea.

Otherwise, or until then, you can clear the registered ores using this line in a mod that depends on default (and any other mods that register ores):
`minetest.clear_registered_ores()`

I'll rename this to be for a global ores setting.

**Comment by paramat** [comment]
I will work on this soon if no objections from core devs.
I often find it useful to disable ores, doing that using a mod is a little annoying.
Another primary reason is: Looking at a mapgen's 'makechunk' function, ore generation is now the only component of mapgen that isn't controlled by a setting.

**Comment by paramat** [comment]
PR #10276
