### ISSUE TITLE
Add API support for v6 biome, heat, humidity

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8926]
## Situation
The v6 mapgen has a biome, heat and humidity system. However, it is completely different from the Biome API system used in other mapgens. Decorations and ores don't recognize v6 biomes. The Biome API functions like `minetest.get_biome_data` always return Biome API-specific values, which are incorrect for the v6 mapgen.

## Solution

I request to add API support for the v6 biome, heat and humidity.

First step:

For Lua purposes only, the v6 biomes are given special identifiers: `"mgv6_normal"`, `"mgv6_jungle"`, `"mgv6_desert"`, `"mgv6_tundra"` and `"mgv6_taiga"`. These identifiers will be used in the functions and treated specially. Also, from now on, any biome identifier that begins with “`mgv6_`” is reserved for Minetest use only (so a mod is forbidden from registering a biome with name `"mgv6_candyland"`, for example).

Second step:

Modify these functions:

* `minetest.register_decoration`: When in v6, the `biome` parameter will now recognize the special v6 biome mapgen identifiers. But any other biome in this list will be ignored in v6 (just like before). And if you're in v7, the v6 biomes will be ignored. EXAMPLE: So if you write `biomes={"mgv6_normal","mgv6_jungle","Forest","Grasslands","Rainforest"}`, the decoration will, in v6, appear in v6 Normal and v6 Jungle biomes, and in other mapgens, appear in Forest, Grasslands and Rainforest biomes. (It's probably still better if you register decorations separately for v6 and non-v6.)
* `minetest.register_ore`: Same as above.
* `minetest.get_biome_data`, `minetest.get_heat`, `minetest.get_humidity`: Add an optional 2nd parameter to the function family above: If `"auto"`, will output v6 values in v6 and Biome API values in other mapgens. If `"biome_api"`, will always output Biome API values (current behaviour). If `"v6"`, will always output v6 values. We can argue about what the default value of this parameter should be.
* Add the v6 biomes to `heatmap` `biomemap` and `humiditymap`

## Other notes

There's a mod which implements this at least partially:

https://forum.minetest.net/viewtopic.php?f=9&t=23158

However, it would be cleaner if this is exposed in the core Lua API, as the mod-based solution might become outdated. The mod basically is just a workaround and a copy of the engine algorithm. The mod is unable to restrict decoration and ore generation to certain v6 biomes, however.

**Comment by paramat** [comment]
:-1: I very strongly disagree.

It's really not worth doing all this work and adding so much complexity just for a legacy mapgen that we're trying to move away from. Altering the existing biome API to deal with mgv6 will make the currently very nice code horrible, unbearable in fact, it's difficult enough work as it is.

It's a far better idea to add a new version of mgv6 that uses the existing biome API, as i have suggested, and can code quite easily, see #8745 . I'm waiting for core devs to consider that, if i get some support i'll do it.

Mgv6 is an excruciating pain in terms of mapgen code and maintenance, if at all possible i would like to remove it completely, but of course we have to support existing worlds. So the best approach is to leave it as it is, keep it a special self-contained mapgen, don't add features, bugfix and maintain only, to not make things even more of a pain.
Users of mgv6 mostly just want it to continue as it is, because they like it that way.

**Comment by Wuzzy2** [comment]
Eh, it was worth a try. :D

Yeah, MGV6 with Biome API support would be nice indeed.
