### ISSUE TITLE
Can't edit a flag of mgcarpathian_flags in All Settings

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8987]
##### Minetest version
```
26b39f1eae1f576669cbf49c6db94ef4ed8624df
```

##### Summary
The `mgcarpathian_flags` setting in the All Settings menu behaves weirdly. It shows a value that you cannot edit.

##### Steps to reproduce
1. Go to All Settings
2. Go to `mgcarpathian_flags`
3. Look at the default value
4. Click on Edit
5. Look at the available checkboxes

After step 3, I see `caverns,norivers`.
After step 5, I see only one checkbox: `caverns`. There's no checkbox for `rivers`/`norivers`.

But I expect that after step 5, I see 2 checkboxes: `caverns` and `rivers`.

##### Notifications
@paramat

**Comment by paramat** [comment]
Will attend.

**Comment by paramat** [comment]
Confirmed. Suspect #7847 @srifqi 
The entry in settingtypes.txt is correct.

**Comment by paramat** [comment]
Found the cause but not a solution yet.
Mgflat checkboxes work fine, so i was looking at settingtypes.txt to try and see a difference:
`mgcarpathian_spflags (Mapgen Carpathian specific flags) flags caverns,norivers caverns,nocaverns,rivers,norivers`
`mgflat_spflags (Mapgen Flat specific flags) flags nolakes,nohills lakes,hills,nolakes,nohills`

It turns out the difference that causes the bug is:
`caverns,nocaverns,rivers,norivers` BUG
`lakes,hills,nolakes,nohills` NO BUG

Testing:
`caverns,rivers,nocaverns,norivers` NO BUG
So probably a simple cause.

**Comment by paramat** [comment]
Relevant code

https://github.com/minetest/minetest/blob/26b39f1eae1f576669cbf49c6db94ef4ed8624df/builtin/mainmenu/dlg_settings_advanced.lua#L690-L707

It looks ok, it iterates over every 'possible setting', i can't see why it would fail.

**Comment by srifqi** [comment]
This issue is caused by the usage of `i` (for-each index variable) inside the loop.
https://github.com/minetest/minetest/blob/5fde69798c69b26b8f1cc5c3ed5b823d691599fd/builtin/mainmenu/dlg_settings_advanced.lua#L694-L695
It will only work if we arrange like what paramat has said before.
