### ISSUE TITLE
AreaStore is badly documented

### ISSUE THREAD

**Issue by niwla23** [minetest/minetest#9027]
The Documentation is very unclear what it actually does. Does it protect something? What is an "area" in this context?

**Comment by jastevenson303** [comment]
An area is some volume of nodes.  Use methods to, for example, query
whether pos intersects with area.

**Comment by ClobberXD** [comment]
I agree that AreaStore can be better documented. :+1:

**Comment by SmallJoker** [comment]
Do you use the 5.1.0-dev Lua API after https://github.com/minetest/minetest/commit/fec30e3#diff-1305560bd8befb32862f0feeefabd02e ? If so, what kind of explanation do you need?
Areas are 3D "spaces", specified by minp, maxp like in VManip. Just because it's used in the areas mod does not mean it does anything protection-related - neither does the doc state anything like that.

**Comment by paramat** [comment]
Seems well documented to me.
'Area' in MT is widely used to mean a volume (unfortunately, as 'area' implies a 2D area).
Protection is irrelevant, it is just a way to manage areas and their relation to positions.

**Comment by AKryukov92** [comment]
If documentation is clear to paramat, then it doesn't mean that documentation is clear for humans.
I see that documentation can be improved by adding definition of `area` term.
You can start with:
> Areas are 3D volumes, specified by minp, maxp like in VManip.

Does area contains information about nodes?
Does area contains **only** `data` string attribute?
Is it true, that area is only cube? Is it possible to create area with arbitrary shape?
What is "fast implementation" [here](https://github.com/minetest/minetest/blob/fec30e37ac1d160a942777b05a7717b5395c4d99/doc/lua_api.txt#L5203)? Can you list all implementations and logic of their selection?

Constructors can be written in distinct section like
```
### Constructors
* `AreaStore()`
  * Creates area with fast implementation
* `AreaStore(type_name)
  * Creates area.
```
What is `type_name`? What values can be passed to this argument?
What do you mean by `mod decides where to save and load AreaStore` [here](https://github.com/minetest/minetest/blob/fec30e37ac1d160a942777b05a7717b5395c4d99/doc/lua_api.txt#L5202)?

What if I call AreaStore constructor multiple times?

Why there is no constructor with definition of coordinates? How one is supposed to create area?

Each method lacks explanation of its arguments.
For example `include_borders` can be true/false, but it also can be table with true/false for each border.
Why *border*? If we mean 3D volume, then it should be named as `include_faces`(of cube).
What exactly should be passed to `edge1` or `edge2` arguments? Is it number or table?

What if I call `reserve` method multiple times with different argumens?
For example:
```
AreaStore.reserve(5)
AreaStore.reserve(3)
AreaStore.reserve(7)
```
How much resources it will reserve? 5? 7? 15?

**Comment by SmallJoker** [comment]
> Does area contains information about nodes?
> Does area contains only data string attribute?
> Is it true, that area is only cube? Is it possible to create area with arbitrary shape?
> What is "fast implementation" here? Can you list all implementations and logic of their selection?

Whatever you want to put in there. Can be any value.
Yes.
Yes. No, it's fixed to cubic forms.
Available `type_name` values are `"LibSpatial"` (default, if compiled with libspatial) and `nil` for the MT implementation.

> What do you mean by mod decides where to save and load AreaStore here?
> What if I call AreaStore constructor multiple times?
> How one is supposed to create area?

It means that you have to take care of saving and loading the data using a data backend you like.
What if I create multiple `ItemStack`s? Creates a new Lua reference each time.
https://github.com/minetest/minetest/blob/47d07793654c1bdd92afbcb486e1ff1429f29a8f/doc/lua_api.txt#L5227-L5232

> Each method lacks explanation of its arguments.
> Why border? If we mean 3D volume, then it should be named as include_faces(of cube).
> What if I call reserve method multiple times with different argumens?

`edge` is a `v3s16`, or simply Vector in Lua. Seems pretty clear to me.
PR welcome.
`reserve` only does something when compiled with libspatial. Like in C++ containers, tt will extend or shrink to the given length in total. This code will allocate 7 areas.

**Comment by AKryukov92** [comment]
I'm asking these questions here, but it is better to put answers to documentation.

**Comment by paramat** [comment]
Sorry, there probably is a need for some documentation improvements here.
However, what you referred to in the first post was already clear:
> Does it protect something? What is an "area" in this context?

... so i was responding to that.
Thanks for a more detailed list.

**Comment by doxygen-spammer** [comment]
I can confirm that AreaStore is badly documented. Sorry for being rude. :/

The documentation is misleading, because:
1. It doesn’t state that “Area” here means “volume”. A newcomer simply doesn’t know that.
2. It includes “store”, which sounds like it actually stores content. It doesn’t really store content, just some outlining information. (Map-territory problem)
3. Similarly to the point 3: it is described as “A fast access data structure”. This sounds like it stores complicated stuff, which in the context of Minetest would be world data, i. e. nodes or objects/entities.
4. It takes `edge1` and `edge2` parameters. These parameter names are inappropriate. I am not aware of any way to define an area (or a volume) by two edges. Actually, it expects 3-dimensional vectors, which define corners. I believe this is a translation error: `english “edge” != german “Ecke“ == english "corner”`.

Well, this negative critics is mostly about area != volume. There are also positive points in this documentation:

* It describes constructors.
* It describes where/how to store an AreaStore. (Though it is marked “Experimental”?)
* In general what applies to lua_api.txt. (Thanks to its authors! :) )

I suggest these changes:

* Change the description of “Area” from area to 3-dimensional volume.
* Change edge to corner.
* Change the introduction from “fast acces data structure” to “data structure to calculate intersections of volumes and points.”

(I’m talking about lua_api.txt from git master.)
