### ISSUE TITLE
Ability to limit placement of decoration to X per sidelen

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest#9106]
## Problem

Sometimes one needs to more tightly control the placement of decorations in making sure no decoration appears too close to each other. With very low `fill_ratio` that risk runs very low, but now there may be too far between decorations instead.

## Solutions

I've no exact suggestion for syntax but something like `max_per_sidelen` and possibly `min_per_sidelen` would do.

That means with `sidelen = 80` and `max_per_sidelen = 1`, a decoration would not be place more than once each mapchunk.

**Comment by paramat** [comment]
This is a rare and specialist requirement (i have never had a request for this before now) so does not justify adding to engine decoration code, which can only contain features that are very useful to many users. Something this rare and specialist should be done in an optional Lua mod.
:-1: sorry.

**Comment by paramat** [comment]
> making sure no decoration appears too close to each other

> That means with sidelen = 80 and max_per_sidelen = 1, a decoration would not be place more than once each mapchunk.

If a decoration is placed so that only 1 is randomly placed per sidelen ^ 2 area, it can still be very close to a decoration randomly placed somewhere in a neighbouring sidelen ^ 2 area.
There may be a decoration close to the North edge of a mapchunk, and a decoration close to the South edge of the neighbouring Northward mapchunk.

For the following i will assume the request is 'making sure no decoration appears too close to each other':

Thinking more on this, it seems 'practically impossible', meaning: 'theoretically possible, but so complex and extremely intensive (huge reduction in performance) it cannot be done'.

During mapgen, within each mapchunk, as decorations are placed their positions are recorded. So it would be possible, but fairly intensive, for each new decoration to calculate distances to all other decorations, and not be placed if below a specified distance.

However, this record of positions only exists for the mapchunk and is deleted after mapchunk generation. So when a neighbouring mapchunk is generated later (could be milliseconds to years later) it has no idea if decorations are being placed close to decorations in the initial mapchunk.

So, each placed decoration would have to perform a distance check by searching a cubic volume around each decoration of radius 'minimum_separation_distance'. This would be extremely intensive, especially for separation distances larger than a few nodes.

The mapchunk being generated would have to have all its neighbouring mapchunks loaded into the server, to check for decorations in those. This currently does not happen, a mapchunk being generated may have unloaded neighbouring mapchunks.

If i have misunderstood feel free to explain, but this is a 'can't add' so closing, sorry.
