### ISSUE TITLE
Use array style vectors

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#9146]
Warning: non-trivial! _And don't shoot the messenger, please._

The decision to use a {x=,y=,z=} form of vectors in MT was a big, big blunder. These vectors are slower to access, a pain to type, possibly consume more memory, and cannot be optimized by LuaJIT as easily as array vectors. (which LJ handles very, very nicely from what I've tested, as long as you use them correctly)

At the moment, the use of dictionary vectors is not a huge issue in MT. There aren't that many functions that take a vector, so I personally use the array form in my own functions and convert between the two when needed (and metatables soften the blow). As it is, this is not an issue for me, though it is stupid that I have to waste cycles to provide them in the dictionary form, only for the engine to convert them back to arrays when it's time to feed them to Irrlicht.

However, the talk of SSCSM has raised a red flag to me about this. Client side functions will use vectors _a lot_ more, and they will use them for much heavier tasks, potentially including collision and rendering. Client side scripts also carry an expectation of better performance than doing things on a server. So not only will the performance issues of hashmap vectors have a much greater impact, but also the amount of API functions that use them will rise exponentially, making it much harder to deprecate the old form once they are in place. Additionally, advanced client side features may require more math primitives like matrices and quaternions. Inconsistent syntax between vectors and other primitives is less than ideal, and crippling the future primitives with dictionary semantics to keep things consistent would be just plain horrible.

Therefore, I'm raising the issue now, before SSCSM is operational, because if this isn't fixed now, it'll stink even worse later. The change can be gradual at some point; old functions can still look for the x/y/z/w keys if [1]-[4] are missing. (Why did I add a fourth dimension there? Because LJ can use packed instructions to move vector components two at a time, and a W is needed for certain operations.)

**Comment by SmallJoker** [comment]
What's easier to use?
```Lua
local pos = vector.new(1, 6, -10)
pos.y = -30
pos.x = pos.x - 4
```
or
```Lua
local pos = vector.new(1, 6, -10)
pos[2] = -30
pos[1] = pos[1] - 4
```

I vote for former. Better readability, even though if it costs some more time to execute.

**Comment by rubenwardy** [comment]
This smells of premature optimisation. Also, metatables are much slower than keyed accesses

**Comment by paramat** [comment]
Since this is scripting, readability is a very important issue, axis letters to numbers will be a headache.
> At the moment, the use of dictionary vectors is not a huge issue in MT.
[...]
However, the talk of SSCSM has raised a red flag to me about this. Client side functions will use vectors a lot more, and they will use them for much heavier tasks,

On average, i do not think SSCSM will use vectors more or for heavier tasks than server Lua.
>  Client side scripts also carry an expectation of better performance than doing things on a server.

I disagree, the requirement for server Lua performance is also huge due to it causing lag for everything else.
> Additionally, advanced client side features may require more math primitives like matrices and quaternions.

On average, i think server Lua will probably use these just as much.
So i do not think SSCSM is an argument, best argue based on current usage (SSCSM has gone nowhere in 2.5 years and we now have even less core dev time for it. 1 core dev opposes it and another is concerned about security).
The readability issue and the effort/complexity/disruption/deprecation issues concern me. Interesting idea though.

**Comment by rubenwardy** [comment]
This is a lot of work for something that is very likely to have a negligible effect to performance, and a detrimental effect to API usability. To improve performance, you should start with low hanging fruit - small amounts of work which provide a large benefit to performance

**Comment by hecktest** [comment]
Let me interject for a moment; you're not supposed to edit vectors! Watch this:
![immutable](https://user-images.githubusercontent.com/42101236/69589993-4efc1d80-0fee-11ea-9f4b-d30ff9d58719.png)
Now let's take the immutability away... oops.
![uh oh](https://user-images.githubusercontent.com/42101236/69589996-51f70e00-0fee-11ea-80ce-043b688cb3b1.png)
When you do things right, doing the math on LJ's side is actually faster than relying on C functions, and almost no different from what a C compiler would spit out.

In the end, this is not my problem, I'll just weasel my way around it like always. You don't have to do this now, but I strongly advise you to consider fixing this before adding more APIs that use vectors. I shudder to think of things like a custom mesh API that expects vertices in a {{x=,y=,z=},{x=,y=,z=},{x=,y=,z=},{x=,y=,z=},...} format. Vector math is one of the most used things in a 3D game, doing it right is _not_ premature!

Other things, off the top of my head:
- In serialized form, there are 6 bytes of dead weight for every vector. Floats in text form can actually be very efficient (4.8 bytes mean for all the numbers in a mesh I tried, compared to 8 bytes for a raw double), but not if you do things like this!
- Accessing vec.x is okay but typing {x=,y=,z=} instead of {1,0,0} is noisy
- You can't unpack() a dictionary vector
- ...or construct it with { unpack() }, { 1, unpack() }
- I had a look at vector.new, and... really? Type check and two asserts?
- As long as vectors are broken, every PR utilizing them will be forced to conform to the broken form. In addition, contributors may be discouraged from implementing interesting features by this. It's a vicious cycle.
- This **will** infect quats and matrices (or block them from ever being implemented), you just watch.
- You grilled me once for using a matrix, insisting on wrapping it in a branch, and _that_ wasn't premature?

**Comment by v-rob** [comment]
Alright, let's break every single mod that uses vectors (which is a _lot_) or add the new arrays to the current vectors together (which makes it even slower and consume more memory) or make it different for CSM and SSM (a headache for modders, code duplication, and hard to transfer) or make a full new set of functions to accept the new vectors (a bigger headache for modders and will result is weird function names to keep compatibility).

How do you propose to do it?

**Comment by hecktest** [comment]
Slowly, with a big fat warning about deprecation for one or two major versions before pulling the trigger.

**Comment by jastevenson303** [comment]
This one seems smart, grab yer pitchforks!

**Comment by paramat** [comment]
Anyway, i want to say thanks for this seemingly significant and useful information, despite the problems of readability and implementing this. After all, you did state it is 'non trivial' =)

**Comment by v-rob** [comment]
> Slowly, with a big fat warning about deprecation for one or two major versions before pulling the trigger.

That fails to answer the question.  I asked about implementation.  Here are the possibilities:

1. Add the new vectors to the old vectors, creating something like `{1, 2, 3, x=1, y=2, z=3}`, which uses much more memory, is confusing, and highly prone to error.
2. Make a new API for the new vectors, like `new_vector.new` and `ObjRef:set_attach_new` versus their current equivalents of `vector.new` and `ObjRef:set_attach` which will be ugly for new code and a headache for modders and will create compatibility problems between mods using different APIs.
3. Make a new API for `vector.new` and similar functions, but making things that accept vectors like `ObjRef:set_attach` check for which type of vector in inputted, which is slower and has the same problems as option 2.
4. Have different APIs for CSM and SSM, so CSM `vector.new` returns `{1, 2, 3}` and SSM `vector.new` returns `{x=1, y=2, z=3}` which would make SSCSM totally incompatible.
5. Break compatibility right now and make it so that `vector.new` returns `{1, 2, 3}` and break every single mod that uses vectors.

These are the only options.  Now I'll ask again, what do you propose to do?

**Comment by rubenwardy** [comment]
>  When you do things right, doing the math on LJ's side is actually faster than relying on C functions, and almost no different from what a C compiler would spit out.

Vector math on the Lua-side is implemented in Lua, not by calling C functions. 

> As long as vectors are broken

Vectors are not broken

> You grilled me once for using a matrix, insisting on wrapping it in a branch, and that wasn't premature?

I did not

----------

In order to persuade us that this needs to happen, you will need to show that the *absolute* performance improvement from doing this is worth breaking almost all mods.

**Comment by hecktest** [comment]
This has gone well past shooting the messenger, it's a firing squad.
I never implied that MT is calling the binary to do vector math, I meant to highlight that an immutable array is the best possible approach, eliminating any potential need to call the binary in the future, even if some heavy lifting is required.
The issue was not that this needs doing _now_, as currently this change would not be worth much. But dictionaries stink and they're eventually going to infect some piece of code where it can be felt. I'm not ruling out the possibility that it might be already too late to eat this frog. So I wanted to discuss this, but all I got was "well how are YOU going to implement it, huh? huh?". So I give up, you win.

**Comment by sfan5** [comment]
I don't see anyone shooting the messenger in this thread.
Asking for concrete implementation details is exactly the discussion we should be having and not the same.

> But dictionaries stink and they're eventually going to infect some piece of code where it can be felt. 

There are ways to avoid performance problems of dict vectors and we already use them in places where it matters.

Take a look at VoxelManips: The data you get is a table of numbers. And aside from using convenience functions (`VoxelArea:index()`), no vectors are needed at all.
A code fragment that works like this can be seen [here](https://github.com/Uberi/Minetest-WorldEdit/blob/8feaf8a21d71c9587722d5e1004a1eea5e1c78a7/worldedit/manipulations.lua#L184-L199), there is even some optimization potential by turning `{dst,src}_{stride,offset}` into array vectors.

**Comment by gpcf** [comment]
This has come up in conversation about optimizing advtrains, since I read this in the lua manual. If I sometime have time  for it, then I might change parts of advtrains to use arrays as position vectors and will report on the results. I believe the performance boost will not be neglegible at the volume of vectors handled by lua.

**Comment by DS-Minetest** [comment]
Handling vectors is very annoying with the current api. Things like having to do stuff like `matrix3.multiply(my_matrix, vector.add(vector.multiply(my_vector, -1), 1))` instead of `my_matrix * (-my_vector + 1)` is much much more problematic than having to do `my_vector[1]` instead of `my_vector.x`.
Therefor vectors should finally use metatables for easier modding (related #7196). This would allow allowing both forms of addressing, even more forms (eg. `v.zx` for `v.z, v.x` (this has a name, swizzling I think) or `v.1`) and many more useful features while keeping the vectors' scalars in an array table.
If done right, this won't totally break backwards compatibility everywhere. Eg. api functions could still use the `.x` notation or first create a new vector from the given one.
Having immutability would also be nice, of course. Eg. it happens very often that you get a vector as function parameter and want to save this vector somewhere, if you don't copy that floppy vector, the caller might modify the vector. This is error prone.

**Comment by v-rob** [comment]
Metatables seem like a good idea at first, like this example here:
```lua
local vec = {1, 2, 3}
setmetatable(vec, {
    __index = function(t, k)
        if k == "x" then
            return t[1]
        elseif k == "y" then
            return t[2]
        elseif k == "z" then
            return t[3]
        end
    end
})

print(vec.z)
print(vec[3])
```
Output:
```lua
3
3
```
But they don't work always.  Some mods don't use `vector.new`, so if an old mod does this:
```lua
local vec = {x=1, y=2, z=3}
print(vec.z)
print(vec[3])
```
Output:
```lua
3
nil
```
This won't be a problem for the old mods within themselves, but internal functions will have to either handle both types of vectors or possibly use the metamethod version, making them slower.  But mods communicating with each other where the newer mod uses the number syntax will fail completely.

Metatables would also be nice to add things like operator overloading, for checking equality, arithmetic, length, etc., but we can't use them unless we can force everyone to use `vector.new`.

**Comment by paramat** [comment]
Disapproved by several core devs.
