### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by zaoqi** [minetest/minetest#9154]
## Problem

minetest doesn't support iOS

## Solutions

Migrating changes from https://github.com/MultiCraft/MultiCraft

**Comment by Enrikoo** [comment]
Good idea, but someone told me there are license conflicts, so it can't be in the AppStore if it hasn't been solved.

**Comment by paramat** [comment]
Does #9066 do this?

**Comment by zaoqi** [comment]
@paramat #9066 is about Android

**Comment by SmallJoker** [comment]
The AppStore's terms are incompatible with (L)GPL code. In order to install Minetest from the website you need to Jailbreak your i-Device.
There is yet no official iOS build because it's not worth the efforts for those few people who would finally play the game.

See also:
https://forum.minetest.net/viewtopic.php?f=5&t=14987 (2016)
https://forum.minetest.net/viewtopic.php?p=215506#p215506 (2016)
https://forum.minetest.net/viewtopic.php?p=217059#p217059 (2016)

If the licensing situation is still the same, there will never be an official iOS app. Additionally all Minetest-based apps on the AppStore are illegal.

**Comment by zaoqi** [comment]
There are some unofficial app stores with no jailbreak required

**Comment by NPlatinum** [comment]
Aw man does that mean I have to convince my Mom to buy me an android now...😢
