### ISSUE TITLE
Everything's wrong with styling *image_button[]

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#9195]
Different tests on [craftguide](https://github.com/minetest-mods/craftguide) with https://github.com/minetest/minetest/commit/9284313d17ba906de449c6d39ef3ddacb6c73791 results in observations of bugs.

#### Case 1
```Lua
style_type[image_button;border=false]
style[xxx;bgimg_hovered=bar.png]
image_button[0,0;1,1;foo.png;xxx;]
```
Result: border is _still_ drawn, hovered image remains the same than the standard one.

#### Case 2
```Lua
style_type[image_button;border=false]
style[xxx;border=false;bgimg_hovered=bar.png]
image_button[0,0;1,1;foo.png;xxx;]
```
Result: border is _finally_ not drawn, hovered image _remains_ the same than the standard one.

#### Case 3
```Lua
style[xxx;border=false;bgimg=foo.png;bgimg_hovered=bar.png]
image_button[0,0;1,1;;xxx;]
```
Result: the images are overlayed with a weird background, the original colors from the textures are not rendered exactly (they are like washed out).

![Capture d’écran de 2019-12-13 17-33-35](https://user-images.githubusercontent.com/7883281/70815961-cbed0c80-1dce-11ea-89c6-a6597c12f61a.png)![Capture d’écran de 2019-12-13 17-33-14](https://user-images.githubusercontent.com/7883281/70815965-cf809380-1dce-11ea-8466-e9d2ad2bcae4.png)

#### Case 4
```Lua
style[xxx;border=false;fgimg=foo.png;fgimg_hovered=bar.png]
image_button[0,0;1,1;;xxx;]
```
Result: before hovering, no image is shown at all (except this weird background). After hovering, the specified hovered image (aka. `bar.png`) is shown, and it sticks like that! (even after moving the cursor off).

#### Case 5
```Lua
style[xxx;border=false;fgimg=foo.png;bgimg_hovered=bar.png]
image_button[0,0;1,1;;xxx;]
```
Result: before hovering, no image is shown at all (except this weird background). After hovering, the specified _standard_ image (aka. `foo.png`) is shown, and it sticks like that! (even after moving the cursor off).

Probably more weird scenarios that can happen...

@Df458 @SmallJoker @rubenwardy

**Comment by Df458** [comment]
I haven't had a chance to test your findings thoroughly (I'm in the process of changing pcs at the moment) but here are some initial thoughts:
- I think the border bug is likely an existing issue with style properties, from a quick test it seems that the `StyleSpec` passed to the button in case 1 has no value set on `StyleSpec::BORDER` at all. Maybe the two styles are combining incorrectly?
- You probably want `fgimg_*`, not `bgimg_*`. `image_button` supports both, but the values passed to the element itself are the foreground. Right now, you're sticking new textures underneath the button's content instead of replacing it.
- You do need to specify `fgimg` in order to access `fgimg_hovered` and `fgimg_pressed`... I'll admit that it's a little silly in this case, but my goal in doing this was to keep the behavior more or less identical between `fgimg` and `bgimg`. If people think it's better to lose this consistency to make the styles less redundant, I'm totally willing to reconsider that decision.

**Comment by kilbith** [comment]
> You probably want `fgimg_*`, not `bgimg_*`.

Read **Case 4**.

**Comment by SmallJoker** [comment]
For the broken button text color style (which isn't mentioned in this issue) see #9187.

**Comment by Df458** [comment]
Some more testing has revealed a second bug: If you make an image button with no texture specified, it starts behaving quite weirdly (probably because it's receiving an invalid texture). I'll admit that I didn't think to test this originally, but this should be a pretty easy fix... in this case we can simply let the `fgimg` style property take precedence as it should. It's worth noting that **Case 4** works *perfectly* (as far as I can tell from a quick test, anyhow) if you don't remove the texture from the `image_button` element.

**Comment by Df458** [comment]
Anyhow, I'll prepare a PR this weekend to address these two issues and any more I find from playing around with these cases

**Comment by kilbith** [comment]
> It's worth noting that Case 4 works perfectly (as far as I can tell from a quick test, anyhow) if you don't remove the texture from the image_button element.

Yes, I can confirm. But it shouldn't have to be specified in the `image_button` element to work.

**Comment by kilbith** [comment]
Another case on craftguide:
```Lua
style_type[item_image_button;border=false;bgimg_hovered=craftguide_selected.png]
```

The background image does not apply.
