### ISSUE TITLE
Typing on android 10 not working

### ISSUE THREAD

**Issue by shrek15001** [minetest/minetest#9257]
##### Minetest version

```
5.0.0.23
```

Operating system:Android 10
CPU:Qualcomm Snapdragon 855
GPU model: Dont know
OpenGL version:dont know

##### Summary
Every time I go to type something in it doesn't register. Can't change the name of my game or anything like that.
##### Steps to reproduce
Try typng something in on android 10 you well see what I mean.

**Comment by i10neorg** [comment]
I can confirmed the same behavior (can enter text characters, but cannot "enter") on:

Android 10 (build number QQ1A.191205.011)

with Minetests from:

F-droid:
Version 5.1.0.25 (25) - Added on 2019-12-26
Version 5.0.1.24 (24) - Added on 2019-05-01

Google Play:
Version 5.0.0.23 - Updated March 15, 2019

**Comment by SmallJoker** [comment]
Is there any Minetest version where typing works, like 0.4.16 or 0.4.17.1?

**Comment by Warr1024** [comment]
I can confirm that typing _usually_ doesn't work on Android 10, but rarely it actually does, so the bug is not 100% deterministic.  If I go really slowly and wait several seconds between each action, it seems like it gives the system a chance to "settle" behind the scenes and I can usually get my password entered after about 5 to 10 tries.

The non-deterministic behavior suggest it could be due to one of a few different classes of bugs, such as a race condition between me trying to type and the serverlist loading in background and replacing the main menu formspec that had just accepted my password.  Unfortunately, disabling the server list and then waiting until I'm sure the UI has had a chance to settle doesn't seem to completely fix the issue either.

**Comment by MoNTE48** [comment]
This PR https://github.com/minetest/minetest/pull/9066 solves all possible (including this one) problems.

**Comment by SmallJoker** [comment]
Who's got a new 5.3.0-dev build and Android 10? Does this issue still persist?

**Comment by himanshi274** [comment]
So i downloaded 5.3.0-dev build from the following link (https://minetest.rubenwardy.com/android/) and the app crashes.

**Comment by MoNTE48** [comment]
@himanshi274 Just don't do it. Here is the correct link. 
http://multicraft.world/Minetest/Minetest-5.3.0-dev-armeabi-v7a.apk
Ruben should more actively monitor PR activity with correction and accept it if he decided to create an issue.

**Comment by MoNTE48** [comment]
@SmallJoker issue fixed 2 months ago, issue can be closed.

**Comment by SmallJoker** [comment]
I'd like to know whether the issue is really fixed for the affected users. Would be great if someone could report whether it's working properly.

**Comment by MoNTE48** [comment]
@SmallJoker https://forum.minetest.net/viewtopic.php?f=6&t=24607

**Comment by i10neorg** [comment]
Android 10 on Pixel 3A

   1. I installed:
   http://multicraft.world/Minetest/Minetest-5.3.0-dev-armeabi-v7a.apk
   2. Launched
   3. Granted Media access permission
   4. Saw the sky blue of Minetest
   5. Then it crashed, with a small temporary bubble at the bottom saying:
   /storage/emulated/0/Minetest/LICENSE.txt: open failed: EISDIR (Is a
   directory)

Thanks!

**Comment by MoNTE48** [comment]
Wait merge this PR: https://github.com/minetest/minetest/pull/9900

**Comment by nonom** [comment]
Back to topic: The problem still happening, I couldn't write in an Android 10 since the 5.2

**Comment by Warr1024** [comment]
Problem seems to be mitigated for me.  I still get some failures (e.g. if the server list refreshes while I have the JNI editor open) but I can get it to work after only a retry or two.  This is much better than the ~95% failure rate I was seeing before.

Minetest Build: https://github.com/rubenwardy/minetest/releases/tag/ruben-20200604 (app-arm64-v8a-release.apk)

Device: Google Pixel 2 v1.0
Android Version: 10 (QQ1A.200205.002)

**Comment by amm-dt** [comment]
Aquarius U Plus not working

**Comment by MoNTE48** [comment]
@amm-dt the coolest bug report I've seen. Link to the APK (there is still no official APK with all the corrections at the same time!), Version of Android, video with error playback. I have VERY many test devices, now on Android 10. And everything works for me.

**Comment by nonom** [comment]
Because I'm not a reporter. I did fine I suppose since you answered me like
a troll

**Comment by SmallJoker** [comment]
This particular issue has been fixed in a recent development version of Minetest. There is yet no official build, but you can install [this unofficial apk](https://github.com/rubenwardy/minetest/releases/tag/ruben-20200604) manually to get Minetest working on Android 10.

If you are using that build or a newer one (please check twice) but still experience major usability issues, please look for similar issues or open a new one if nothing matches.
Thank you for all the feedbacks.
