### ISSUE TITLE
Make torchlike nodes more visible

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9304]
## Problem

Nodes of drawtype `torchlike` are sometimes hard to see when placed on the ground or floor.

When on ground or floor, a single sprite is rendered in an 45° angle.

As there's only a single sprite, they become practically invisible if you view them exactly from the 45° angle. That's not very useful for games and can be quite annoying.

## Solution

Draw torchlike in an X shape like `plantlike` when on the floor or ceiling.

Downside: We don't know if anyone actually wants the single-sprite solution.

## Alternatives

* Use `meshoptions` to add the X shape variant for `torchlike`. Downside: `param2` is already used for `wallmounted` direction
* Add a new drawtype `xtorchlike`

**Comment by Wuzzy2** [comment]
Screenshot of current situation:

https://satoshiupload.com/images/tMOSLb8md4.png

On each tree trunk there's a torchlike node. Node that in center you'll just see some pixel dust.

**Comment by Extex101** [comment]
So you want it thickened like dropped items?

**Comment by paramat** [comment]
Torchlike is probably being used with textures that do not work as an X.
> Draw torchlike in an X shape like plantlike when on the floor or ceiling.

This would also be an inconsistent appearence between floor/ceiling and wall. Best that they are all flat single textures.

As for visibility, because players move around these nodes are only very briefly invisible at 2 precise locations around the node, so it is a very minor issue.
Overall i think it is best to leave it as it is :-1:

**Comment by Wuzzy2** [comment]
Feel free to close, it's an old drawtype and most games use nodeboxes or meshes instead.
