### ISSUE TITLE
Formspec elements can be pressed without clicking on them.

### ISSUE THREAD

**Issue by v-rob** [minetest/minetest#9330]
##### Minetest version
```
Minetest 5.2.0-0877587-0877587-dirty
```

##### OS / Hardware
Operating system:  Windows 10
CPU: Intel Core i5 x64

##### Summary
In any formspec element that has focus, clicking outside the formspec form will activate the thing with focus, and releasing the mouse button will let go of the element without activating it (as though you pressed on a button and then released outside of it)

##### Steps to reproduce
Open Minetest, make an element have focus (like a button by clicking and releasing outside the button) and then click the mouse again outside of the gray form border not on another element.  The button will be pressed when the mouse if pressed

I knew that so many formspec PRs would introduce some weird bugs.

**Comment by Df458** [comment]
I can confirm that this happens on my end in 5.2.0 and not in 5.1.1... there's a decent chance that it comes from one of my PRs, so I'll see if I can track the issue down in the next day or two.

**Comment by Df458** [comment]
Actually, after further testing this issue *is* reproducible in 5.1.1... just not with `image_button` / `item_image_button`. I suspect this is because those are the default irrlicht buttons in 5.1.x and below.

I've also noticed something interesting: The button element seems to still get mouse events when the mouse clicks outside of the formspec. Since the handler for `EMIE_LMOUSE_PRESSED_DOWN` doesn't check if the cursor is within the button's clipping rect and the `EMIE_LMOUSE_LEFT_UP` handler only checks if the pressed state was set, the button can be clicked without the mouse hovering it. I'll submit a PR to add a clipping check tomorrow morning.

**Comment by Df458** [comment]
It looks like this also affects dropdowns, which is interesting because I think they're the built-in Irrlicht version. To fix those, we'll either need to work out a way to inhibit mouse events that don't clip with the target element (I suspect this is buried in Irrlicht, so this may not be possible) or re-implement the element as a new class on our end.

**Comment by Df458** [comment]
Ok, after some more testing: Minetest 5.0.0/0.4.17.1 **do not** have this issue for buttons, probably because they're from before the local GUIButton implementation was introduced. However, they still have the issue for dropdowns.

I suspect this is a long-standing issue that no one noticed or bothered reporting previously.
