### ISSUE TITLE
A* pathfinder sometimes walks very long, convoluted ways

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9331]
##### Minetest version
```
5.1.0
```

##### Summary
The pathfinder (`A*` and `A*_noprefetch` algorithm) sometimes takes a hilariously complicated and long path to a close destination. This does not affect `Dijkstra`.

![YVmC855PVA](https://user-images.githubusercontent.com/3686677/73028578-b76c4d00-3e2d-11ea-86d9-17cdd2eb453f.png)

It starts at “START” and ends at the red X. As you can see, the pathfinder decides to first go into the mine and all around the mountain first …

The optimal path would be about 6-9 nodes, but pathfinder traverses over 400 nodes. Inside the cave (not visible in screenshot), the pathfinder also decides to take several zigzag routes.

That's not how the A* algorithm is supposed to work. ;-)

##### Steps to reproduce
Play around with the Pathfinder Tester from the `devtoys` modpack (soonish to be added into my `devtest` game as well):
https://forum.minetest.net/viewtopic.php?f=9&t=23802

Rightclick the target node, punch to find path, shift+punch to change algorithm.

You preferably want to try out areas with obstacles, caves or holes. Then select 2 points close to each other like in the screenshot.

There's a similar problem with the optimal path which is much easier to reproduce:
Play on a perfectly flat map and mark any positon. Then walk a bunch of nodes diagonally and start the search. The path will take 2 straight lines instead of being diagonal.

**Comment by LoneWolfHT** [comment]
I think the fact that it does straight lines only is intentional. A node-sized entity would wrongly think it could get through this wall otherwise:
```
XOD
OXO
EOX
```
(X = Wall, O = Air, E = Entity, D = Destination)

#
I can confirm the weird pathfinding.
The red line is the path, and the destination is inside the grass cube, the entrance to which is marked with a green X
![image](https://user-images.githubusercontent.com/28972859/72768326-deb3e780-3bab-11ea-983c-67bdae08bcb9.png)
(A little rougher to follow than Wuzzy's screenshot, I think you get the point though)

**Comment by sorcerykid** [comment]
I wrote a highly-optimized Lua-based pathfinder based on A* last February. It handles 3D terrain mapping, converting all walkable surfaces into 2D "hint" maps, then compresses and caches those results into per-mapblock node-graphs for lightning fast lookups. The pathfinder supports numerous search options too; e.g. jumping, dropping, falling, ducking, cutting corners, opening doors, climbing ladders. 

https://forum.minetest.net/viewtopic.php?f=3&t=156&start=8300

You can see in this example, the pathfinder produced a route from point A at elevation Y=2 through a room, down a step to elevation Y=1, then through another room and courtyard, and then back up a step to elevation Y=2 to reach B.

Processing time: 0.001 seconds

Here's a quick demonstration video of pathfinding with randomly selected waypoints.

https://vimeo.com/324076654

The mod is effectively ready for release as is, but I want to get the hint-map analyzer working first.

**Comment by Wuzzy2** [comment]
Do you consider your code to be good enough as a template for the C++ pathfinder?

Note that for the C++ pathfinder, it needs to be generalized. There must be no special treatment for Minetest Game or any other game, so hardcoding any game-specific nodes would be a no-go.

**Comment by sorcerykid** [comment]
The pathfinder algorithm is game agnostic. However, it does account for several common node types: wall, door, floor, ceiling, jump, drop, and cliff in order to deduce which path is walkable. The `find_path()` function itself, includes an `options` parameter that permits ignoring one or more node types. For example setting `can_open = true`, would allow for paths through `door` nodes.

Hooks can also be set for specific node types, so if the pathfinder encounters a certain node in its search, it will call a Lua function that can return true if it is walkable, or false otherwise. This is very useful in the case of nodes that can frequently change state, like doors, in which a cached hint map cannot be relied upon. The return value of the hook is then saved in the node graph for the remainder of the search (to avoid the cost of redundant callbacks for that same node).

Ultimately it's the hint map analyzer that is responsible for the gruntwork of translating the map nodes into a suitable node graph for the pathfinder algorithm will use.  Currently it refers to the node definitions to make the determinations of corresponding node types, looking at standard properties like `walkable `and `node_box`. 

The screenshot in my comment above actually depicts what the hint map analyzer generates as a serialized cache (each symbol is a specific node type, with `#` being wall and `/` being door) for two distinct layers of the map. That cache is compressed and stored within the corresponding mapblock. When the mapblock is reloaded, the cache is automatically deserialized and converted from a hint map back into a node graph for later use by the pathfinder. In many respects the hint map concept is not much different than how minetest pre-computes lighting for efficiency in rendering.

In an ideal world, of course, this could be accomplished more efficiently if there was a param3 field where node types could be stored directly for each node in the map rather than as separate serialized cache. But right now we'll have to work within the confines of the existing map database format.

For these reasons, I'm inclined to think that the hint map analyzer would benefit the most from being ported to C++ (given the overhead of scanning entire mapblocks, as well as storage and retrieval), whereas the pathfinder itself is efficient and flexible enough that retaining it in Lua might actually be an advantage.
