### ISSUE TITLE
Reminder: Consider reverting collision tweak before 5.2.0

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#9375]
See #9351 
We are currently testing this collision tweak (either #9327 or new value #9365 ), but before releasing 5.2.0 we need to decide whether to revert this due to the risk of making a fundamental change to collision soon before a release.

**Comment by TheTermos** [comment]
One last time I'm putting up for consideration testing #9343 before 5.2.0.

I know there's the argument that it could be risky at this point in time, but on the other hand, collision detection isn't exactly not broken now, so that makes the risk kind of virtual.
That PR is a fix as opposed to tweak, but now with changes to localplayer reverted it's confined to one place and as easily reversible as the tweak. I've tested it quite a lot and am nearly certain it works way better than the old one. Last thing left to do is for it to be tested by other people.

Might be easy to overlook being busy with all that other stuff, but problems with collision detection are potentially very apparent to new users, all they need to do is install the most popular mob mod or mcl2, those mobs test collision detection in and out, and that doesn't make a great initial impression about quality, so what's the better time for it.

**Comment by paramat** [comment]
Merging #9343 before 5.2.0 seems obviously very risky as it is fundamental changes to collision and likely to cause unforseen bugs to arise long afterwards. Even your previous tiny tweak caused bugs that took some time to be noticed, even the current state of that tweak is itself a little risky and may even be reverted for 5.2.0.
The potential risk of #9343 is far larger than the current minor collision bugs, so the risk cannot be dismissed as you have done.

You have also rethought and rewritten #9343 several times and will probably continue to do so for a while, so i do not see it as settled, it needs more time and then a release cycle of testing.
So i disapprove merging #9343 before 5.2.0.
I agree we should test if we can, but, it is not high priority so may not get much testing until after 5.2.0 release. Also, because it is best to merge it after release the testing will probably be done then also. Our time before release is better spent elsewhere.

**Comment by SmallJoker** [comment]
Old value:
```C++
f32 position_max_increment = 0.1*BS; // clientenvironment.cpp
pos_max_d = position_max_increment; // "localplayer.cpp"
f32 d = pos_max_d * 1.1f; // collision.cpp

p = 1.1f;
```

New value:
```C++
f32 d = 0.3f; // collision.cpp
```

The new value is good - no glitches after various thin slab waking and step-up tests. The sidewards-jump-glitch is however still there, I can't tell whether it improved.

My opinions:
- Do not revert the collision PRs. The collision code is identical, and the new distance value works.
- Merge #9343 after 5.2.0 to give it more time for testing

**Comment by TheTermos** [comment]
> I agree we should test if we can, but, it is not high priority

Yes, I've been getting the impression it's seen as low priority.
It's not a good sign if glaring bugs in such a fundamental functionality as collision detection persist for many releases and are dismissed as minor.
An example, I reported that objects don't collide with players about a year ago, a couple of core devs dismissed it saying it was probably lag. It is evident some of you guys don't even realize how broken it is.

What's the purpose of these releases? Are they to make a difference, or is it just the time for a new number? I don't know, maybe there are features coming in 5.2 that everybody can't wait to try out, but otherwise I don't see what's the point of rushing another broken release.

**Comment by SmallJoker** [comment]
@TheTermos [Releasing Minetest](https://dev.minetest.net/Releasing_Minetest#Feature_Freeze) is usually a tiring process of checking whether everything works, and notifying the repository managers. Most players usually stay on fixed releases which are "known good".

Collision is the topic of some of the 321 open issues. It's a bad excuse, but collision worked like this for years, so one more release doesn't change much. No matter how well tested a feature of bugfix is - there can always be side-effects or even worse - players/modders relying on the bugs. Thus, it would be best to release 5.2.0 soon to carry on with riskier changes, like your promising collision fix PR which affects the entire gameplay.

**Comment by TheTermos** [comment]
@SmallJoker If there's so much overhead, maybe it would be better if these releases were less frequent?

Back to the tweak, I think I owe some more info. There are differences in behavior.
- When player stands on a moving object (because bug: objects don't collide with localplayer) On the original player will glitch up and down but usually stay on top of the object and rarely fall through, on the tweak player will fall through most of the time.
- object-object and object-player collisions (because client/server rarely agree on object position and sometimes set object position inside another). The original is able to correct some of these situations (potentially pushing objects into nearby terrain in the process). On the tweak boxes remain clipping more often.

There's no best d value, changing it only makes some glitches less frequent at the cost of making others more.

**Comment by paramat** [comment]
> My opinions:
Do not revert the collision PRs. The collision code is identical, and the new distance value works.
Merge #9343 after 5.2.0 to give it more time for testing

The above is fine for me.
> I've been getting the impression it's seen as low priority.

It is not low priority or minor obviously, i wrote 'it is not high priority' and the context is 'not high priority for things that need attention before release'.

**Comment by paramat** [comment]
We agreed no revert.

**Comment by TheTermos** [comment]
Managed to glitch player into a node.
The picture below, jump from one dirt onto two dirt column. If the jump fails and player hits the side of the node, they rarely glitch into the node.

This is quite difficult to reproduce and requires many attempts, may have something to do with that I'm testing at the edge of the world where floating point precision sucks the most.

If I had a say in this, I'd vote revert.

![glitch](https://user-images.githubusercontent.com/55103816/76247939-a726fa80-6240-11ea-9672-8a4c9e69880b.jpg)

**Comment by sfan5** [comment]
Did you confirm that reverting the tweak fixes the player glitching into the node?

**Comment by TheTermos** [comment]
I can only attest that so far I couldn't reproduce the glitch in the following scenarios:
- tweak on, near 0,0,0 world coordinates
- tweak reverted, anywhere

**Comment by paramat** [comment]
At 30000 30000 i can reproduce that, 4 times in about 3 mins of tries.
Cannot yet repeoduce at 0 0.

**Comment by TheTermos** [comment]
By the way, slightly related fp precision issue I posted some time ago #9346

I have a modification kicking around that increases position calculation precision to 64b, but it affects many files and also I had to incorporate two irrlicht headers, so it's waiting for some better time.

**Comment by rubenwardy** [comment]
I can consistently reproduce falling through the world by walking up against a node

**Comment by rubenwardy** [comment]
This happens with 5.1.1 too

**Comment by rubenwardy** [comment]
I'm wondering whether this is something to do with CTF's player model

**Comment by TheTermos** [comment]
> This happens with 5.1.1 too
> I'm wondering whether this is something to do with CTF's player model

This is new, does it happen everywhere or just near world edges?

The only collisionbox related issue that comes to my mind right now is when a box dimension is no greater than 0.275 - that's the magic number in 5.1. All weird stuff happens if it's that small.

**Comment by paramat** [comment]
The new bug detailed in https://github.com/minetest/minetest/issues/9375#issuecomment-596724534 "The picture below, jump from one dirt onto two dirt column" takes about 10 tries to reproduce, jumping in a particular way, aiming at the corner of the higher column.

There may be other new bugs caused by your updated collision tweak, but it seems to me that this new bug is far less of a problem than the collision bugs of 5.1.0, which i assume are now fixed (i need to test).
So i am really not sure we should revert your collision tweak.

**Comment by paramat** [comment]
Update to the above: The collision tweak does not fix all the bugs, but improves some, see https://github.com/minetest/minetest/issues/9143#issuecomment-599253229

**Comment by paramat** [comment]
#9143 shows that the tweak does not affect the most serious bug, and slightly improves some others. However it also causes a minor bug and adds risk.
Because the advantages and disadvantages are fairly balanced i think i prefer to revert the tweak for release, a revert is also preferred by the tweak author.

**Comment by TheTermos** [comment]
Turns out it can't be definitely said that the tweak makes things better overall, it improves some things while making others worse, and out of two evils people tend to choose the one they know, so reverting seems a better option.

There's the fix waiting so tweaking the old isn't so important anymore.

**Comment by paramat** [comment]
I agree.
Lets revert! =)

**Comment by sfan5** [comment]
Fine by me.

**Comment by paramat** [comment]
@SmallJoker @rubenwardy ok with that?

**Comment by SmallJoker** [comment]
Feel free to revert the distance value back to `d = 1.1f;` if you feel safer afterwards.

**Comment by appgurueu** [comment]
I have found 5.2 with the collision tweak to have fewer problems than 5.1 - using cellestial game, there was one particular nasty bug where I'd be stuck in the walls. This doesn't happen with 5.2. I think this is quite an improvement.

**Comment by paramat** [comment]
Hmm ... but there may be bad undiscovered bugs. I prefer to go with the opinion of the author of the tweak.

I was asked on IRC about the status of this. It just needs to be done, we have agreement from 3 core devs.
I could make a PR but this may be revertable by git command, however i have low confidence in using this command correctly, so i am waiting for someone else to try a revert by git command (sorry).
However, if you want a revert by PR then i can make one, let me know here.
