### ISSUE TITLE
Discussion: FormSpec expressions

### ISSUE THREAD

**Issue by v-rob** [minetest/minetest#9381]
Formspecs are getting better, but they are still limited by the coordinate (no forms stretching to the size of the screen, for instance, limiting the new main menu ideas).  So, I propose that we add formspec suffixes like `px`, `vmin`, `vmax`, `vw`, `vh`, `em`, and perhaps `ch` (Just like CSS) that can be added to any number to change it from the normal formspec coordinate to any of these other things.

To compliment this, expressions with these like CSS `calc()` could also be implemented, namely `+ - * / % ^ ( )`.  This would require a small parser, of which could be an implementation of the shunting-yard algorithm (https://en.wikipedia.org/wiki/Shunting-yard_algorithm).  If the maintenance/possibility for bugs for this would be too much, order of operations could be ditched along with parentheses to leave a very simple left-to-right parser of expressions.

This proposal was inspired by [Scarlet](https://forum.minetest.net/viewtopic.php?f=46&t=22566), and it seeks to expand the possibilities of such a thing and implement it directly in the engine.

**Comment by Df458** [comment]
> But what if we need a combination of units together, like CSS `calc()`?

Not to be that guy who shoots down ideas, but how often do we actually need this? I absolutely support the idea of having different size units, but this line I've quoted feels like a bit of a leap. This makes me a little nervous, because what you're suggesting is that we basically embed a proto-scripting language into formspec strings, and the entire argument seems to hinge on this assumption.

I'll say this: I like the idea of being able to send new values to the client, but I don't like the idea of
* Adding and maintaining something of this complexity to formspecs
* Modders having to write and maintain logic written in *strings*, with no way to validate even basic syntax without opening all of their formspecs and testing by hand.

If there was (maybe there is? I don't know) a way to pass lua functions over the network without writing them as strings in the code, this would be a lot more ideal because we could re-use existing tech and modders could test & validate with relative ease. At that point, we could even start looking into enabling patterns like MVVM and really modernize how formspecs work. But as this proposal stands, I think it goes a little too far.

**Comment by rubenwardy** [comment]
I am wary of adding these expressions to formspecs. We should reduce the amount of maths required in formspecs by moving to a container/layoutter way of doing things. This is the more modern approach which works much better than manual placement

I support enabling patterns like MVVM, it's the best way to do it. It also allows separation of data and layout, allowing modders to update the layout and data independently. Without lua, you could have a form of viewmodel which is a table on the client that communicates with the server, this would be suboptimal however

**Comment by sorcerykid** [comment]
> Then, I came up recently with the idea of suffixing numbers with a unit, 

No, I think you are very much aware that I devised such an idea last year:

https://forum.minetest.net/viewtopic.php?f=46&t=22566

> It hit me then, that we need a math parser to parse math expressions.

Scarlet can already parse arithmetic expressions. And that functionality is supported in my upcoming Ratio Workspace mod too (since it interfaces with the Scarlet expression translator).

https://forum.minetest.net/viewtopic.php?f=9&t=23886

> Now, I decided that parsing the exact same expressions tons of times for different buttons would be dumb, so I decided variables would be useful. Functions like min and max would also be helpful. \

What a coincidence. Last week, I posted screenshots of how embedded functional expressions are being added to the Bedrock Markup Language. Now you are submitting a proposal for embedding functional expressions into formspecs.

https://forum.minetest.net/viewtopic.php?p=366904#p366904

> Alternatives None, really.

How disingenuous to claim that there are no alternatives, "really",  when much of what you've described has been an ongoing focus of mine as a mod developer. You certainly are not oblivious to the personal investment I've put into Scarlet Formspec Preprocessor, Ratio Workspace, ActiveFormspecs, Polygraph, Imagen, or the Bedrock Markup Language. You've posted replies in some of those topics. And now you are taking credit for several ideas that I had implemented in one respect or another as a mod or that I have publicly announced to be incorporated into a forthcoming mod. Suggesting that there are non-existent alternatives to this proposal is patently untrue, and you know that.

Aside from these concerns, I do not favor this proposal for a number of practical reasons:

* First and foremost it adds further complexity to the engine, which is of questionable merit given the costs of long-term maintenance. Minetest isn't a Web browser. Adding a full blown lexer and interpreter to the CPP code-base just to parse formspec strings seems like overkill to me.

* Secondly, trusting that a home-grown scripting language will be stable and secure enough to integrate with the GUI back-end is very risky. Given that formspecs are used everywhere in Minetest, this has the very real potential to introduce unforeseen side-effects and vulnerabilities.

* Thirdly, the long-term goal should be to get away from Formspec strings, not to further entrench that archaic system into the regimen of mod development by adding even more obtuse lexicon. This is just proof that formspecs are being pushed beyond the limits of their intended design.

* Fourthly, people's longstanding dislike of formspecs have been discussed ad nauseum both here and on the forums. It doesn't make sense to vastly increase the learning-curve for mod developers when there are already multiple open issues on GitHub about eventually replacing formspecs.

* Lastly, this would be imposing yet another standard for GUI coordinates, right after "real_coordinates" was rolled out. To overhaul a brand new system as end-users are still becoming acclimated to the latest one, doesn't seem like a very pragmatic approach to software design.

What really needs better attention is server-sent CSM. That would obviate the need for this entire proposal. I think that formspec strings need to be generated client-side NOT server side. That way mods can have access to a rich API to to account for screen resolution. text overflow, etc.  In a broker software architecture, the server should never have to send a single formspec string to the client.

Furthermore, the concerns about complicated layouts can already be effectively addressed with no changes to the engine. Here are some very feasible alternatives:

1. A formspec string preprocessor (i.e. Scarlet)
2. A visual formspec layout tool (i.e. Ratio)
3. Use of hierarchical container[] elements

It's also worth noting that the deficiencies of UnifiedInventory have little relevance to the shortcomings of formspecs. That mod would be bloated no matter what proposal is put forth to streamline the GUI.

Anyway, I  hope that this discussion might serve as a catalyst to focus on the server-sent CSM. Of all its potential applications, I think formspecs could benefit greatly from that technology.

**Comment by v-rob** [comment]
Well, I'm glad the idea has been shot down.  This is exactly why I posted this before starting anything serious.  Therefore, I will trim down my idea to what I think really matters.

@sorcerykid: I'm sorry, I didn't mean to act like I was taking credit for the ideas that you most definitely had in the first place.  I wrote this late last night, and I should have credited you.  Yes; arithmetic was also your idea.  As for functions, I must protest that I got this around two weeks ago when investigating the Shunting-yard algorithm on Wikipedia, which implements functions (https://en.wikipedia.org/wiki/Shunting-yard_algorithm).

But as for Scarlet, while I do like its ambitions, I don't think it has some of the abilities I have here, or I wouldn't even have this idea.  I prefer Lua to C++ any day.  I think that a formspec preprocessor is more than adequate for coordinates like images, buttons, inventory slots, etc, all things that can be derived from the basic coordinate, whether in the old form or not, but I don't see how a preprocessor can _perfectly_ implement things like pixels or fractions of the viewport of the entire screen using the coordinate.  I haven't looked at the code (the download link hasn't worked until recently, as I recall) but I don't think that those are perfectly possible.  This is what I mean when I say that there are no alternatives.

This honestly was never intended to be a full-blown solution.  I admit I got carried away with my fantasies, but this was originally meant to just help formspecs.  I think the main tenants of my idea was (yes, from Scarlet) `+ - * / % ( )` and suffixes.  So, I will change the first post to this, since this is the real core of the idea.

**Comment by sorcerykid** [comment]
Sorry if i came across so defensive. I'm sure you can understand my initial reaction. And I apologize for jumping to conclusions about your idea for embedded functional expressions. Perhaps that goes to show that great minds think a like ;) Just so you know, there are no hard feelings, and I value the work you do (and have done) on improving formspecs :3

As for achieving pixel perfection, you'd be surprised. In this video I can align and move elements on a per-pixel basis: https://vimeo.com/383923001

Admittedly there can be small rounding errors, given the inconsistencies of the old coordinate system (and it also depends on the client's screen DPI setting). But overall, I think it's a pretty remarkable accomplishment how accurate and efficient Scarlet is when incorporated into a real-world application. If it can scale for a mod like Ratio, then it's probably safe to say that it should be more than capable for handling ordinary formspecs as well.

Even with my investment in Scarlet, I absolutely do think that formspec string creation needs to be offloaded to the client, and that is best achieved through SSCSM rather than rolling a formspec-specific scripting language into the engine. Don't get me wrong, I too have a habit of getting carried away with grand ideas too, so I can 100% empathize. But I think there's a time and a place. And if you have the motivation to work on something as visionary and compelling as this, then I could only hope that you might be willing to apply those skills to help make SSCSM a reality for the Minetest community!

So rest assured, I wouldn't say that this idea was at all "shot down". On the contrary, I hope it's a much needed segue into the next phase of Minetest development -- a truly distributed modding architecture, beginning with formspecs :)
