### ISSUE TITLE
Placing sounds sometimes not played locally

### ISSUE THREAD

**Issue by An0n3m0us** [minetest/minetest#9414]
##### Minetest version
```
Minetest 5.2.0-dev-ee7d357-dirty
```

##### OS / Hardware
Operating system: Linux

##### Summary
When placing (but not breaking) blocks rapidly, some sounds are not played for the local player, but other players can hear them all (as of #9342).

Local player: https://my.pcloud.com/publink/show?code=XZ6CwskZECCb6LIhXDFk7U0TNuPPa4u93Wpk

Other players (audio is muted for local player): https://my.pcloud.com/publink/show?code=XZTlwskZj75N3kKuth7HciPMxXfi9pnQGTeX

##### Steps to reproduce
Place blocks in quick succession; notice how some sounds are not played, but other players can hear them all.

**Comment by HybridDog** [comment]
Afaik, placement sound for the local player is played directly by the client whereas the sound for the other players is created by the server and then sent to those other players.
https://github.com/minetest/minetest/pull/9342/files#diff-83bb4564c6fbf230569bdeb2becc32b9R370
It is implemented like this so that the sound always plays when the node appears, which happens either because of placement prediction (you're the placer) or because the placed node is received from the server (the other player placed it).

I think the problem here is that when holding right click, the placement sounds are not played correctly locally. To test this, you can change the `repeat_rightclick_time` setting. This happens since the repeat_rightclick_time setting has been introduced.

**Comment by An0n3m0us** [comment]
I wasn't holding right-click; I was just pressing it quickly.

**Comment by HybridDog** [comment]
> So that means the sounds (for the local player) are being played elsewhere?

Yes, maybe in game.cpp http://github.com/minetest/minetest/blob/e8a8185d24897ccf964327017effae81aa1c9d40/src/client/game.cpp#L3422
