### ISSUE TITLE
Minetest cannot use all CPU and GPU

### ISSUE THREAD

**Issue by wzy2006** [minetest/minetest#9439]
##### Minetest version 5.1.0
```

```

##### OS / Hardware

Operating system: windows7
CPU: i5-2410m

GPU model: nvidia geforce gt 540m
OpenGL version: 4.5.0

##### Summary
![image](https://user-images.githubusercontent.com/29888010/75510487-1d985100-5a26-11ea-80ce-bb6646b8d561.png)
![image](https://user-images.githubusercontent.com/29888010/75510508-2be66d00-5a26-11ea-96b4-6d160880c981.png)
![image](https://user-images.githubusercontent.com/29888010/75510601-7831ad00-5a26-11ea-94eb-c4c451c8dac7.png)
As shown in the figure, the FPS of minetest is more than ten.
However, the CPU and GPU utilization rate are not up to 100%
Can ‘t minetest make good use of CPU and GPU?
##### Steps to reproduce
Loaded a lot of MODS, the renderer is fully open

**Comment by appgurueu** [comment]
Mods in Minetest run in a single thread. This might be changed in the future, but currently, this is expected behavior. Your task manager likely displays absolute stats, and on a multi-core system, Minetest only uses one core for the Mods.

**Comment by SmallJoker** [comment]
Your laptop matches my desktop computer quite closely in terms of performance:

CPU: https://www.cpubenchmark.net/compare/Intel-i5-2410M-vs-Intel-Core2-Quad-Q6700/796vs1039
GPU: https://www.videocardbenchmark.net/compare/GeForce-GT-540M-vs-Quadro-FX-4600/27vs1596

As already mentioned, Minetest can only make use of one core. Thus, Minetest heavily relies on the CPU single core performance. Also Irrlicht (render engine) doesn't make use of newer GPU features.
Please check whether a 16px texture pack improves the frame rates. Also disable the shaders just to check whether it changes anything. This is roughly the performance you should get:
![screenshot_20200228_201737](https://user-images.githubusercontent.com/1497498/75580170-94a20980-5a67-11ea-905c-c01866405304.png)

**Comment by wzy2006** [comment]
No, it's no use turning off shaders. I tried d3d9, which does not support shaders on its own, with FPS up to 35. After all the OpenGL shaders are turned off, the FPS is still around 20. But the image quality of d3d9 is very fuzzy (the same configuration file) (the same texture package)
Why is that?

**Comment by wzy2006** [comment]
What's more, is minetest's single core restriction in the source code or in the Irrlicht engine?

**Comment by Df458** [comment]
Minetest isn't completely single-threaded, iirc mapgen is handled on a secondary thread.

There are definitely some architectural issues in the code that prevent it from getting the max performance, but a major problem with multithreading is mods. If you want them to communicate with relative ease, you need them to run on the same thread. For that reason, the mods you run can have a major impact on CPU performance.

Out of curiosity, have you tried running a 'vanilla' Minetest Game world to compare performance? That might give a pretty good idea of where the bottleneck is. If you get noticeably higher FPS from that, then it's probably one (or more) mods causing the performance issues. If not, it's probably something in the engine.

**Comment by wzy2006** [comment]
Can we run these mods on multiple threads?

**Comment by rubenwardy** [comment]
> What's more, is minetest's single core restriction in the source code or in the Irrlicht engine?

Being single core isn't a restriction; being multithreaded is a feature. The important distinction is you need to actually design code to run on multiple threads, it doesn't come for free. This is a difficult subject and you can result in slower performance if you're not careful

Mods will never be able to run on multiple/distinct threads - they need to be on the same thread in order to make function calls to each other. We may in the future add support for worker threads and mapgen threads in Lua.

**Comment by paramat** [comment]
Since this is simply due to MT's architecture, and since changing that is very non-trivial, i think this should be closed (discussion can continue).

**Comment by SmallJoker** [comment]
Such performance bottlenecks and multithreading requests are well known, and indeed non-trivial.
This issue seems to be about a particular machine which should perform way better than it actually does. Possible attempts to fix it:

- Change the Energy Plan to Performance (Gaming?)
- Connect the power supply to ensure Windows really delivers maximal output
- Check whether the CPU and GPU temperatures are normal (overheating will throttle the system)

**Comment by runsy** [comment]
https://www.google.com/search?q=lua+multithread&oq=lua+multithread

Lua is already multithread I mean!

**Comment by appgurueu** [comment]
> https://www.google.com/search?q=lua+multithread&oq=lua+multithread
> 
> Lua is already multithread I mean!

No it's not. It supports gearing but without modifications/separate states no real multithreading is possible.

**Comment by FriendlyGamer** [comment]
Hi I came across being the most relevant issue I can find about multithreading... So I thought to get insights from within, please let me know if there a better "issue discussion" elsewhere for multithreading.

> Mods in Minetest run in a single thread.


> Mods will never be able to run on multiple/distinct threads


May I know the different between Minetest and Minecraft in this particular regards? Because I think since 1.12.2 Minecraft Java you CAN run mods in parallel with the mods referring to "main" whenever it needs it. So in Minecraft it would be... 

Main Thread
<Mod1's thread 
<Mod2's Thread
<Mod3's Thread
<etc (as long as there actually is enough threads on the hardware of course)

Then as Mod1, Mod2, Mod3, etc needs Main it will "talk" to main as needed. While doing as much it CAN on it's own thread. 

So this is a shipped "feature" of Java or something? 

Thanks very much in advance!

**Comment by appgurueu** [comment]
> Mods in Minetest run in a single thread.

Yes, that's how it currently is implemented.
 
> Mods will never be able to run on multiple/distinct threads
> 
> May I know the different between Minetest and Minecraft in this particular regards? Because I think since 1.12.2 Minecraft Java you CAN run mods in parallel with the mods referring to "main" whenever it needs it. So in Minecraft it would be...
> 
> Main Thread
> <Mod1's thread
> <Mod2's Thread
> <Mod3's Thread
> <etc (as long as there actually is enough threads on the hardware of course)
> 
> Then as Mod1, Mod2, Mod3, etc needs Main it will "talk" to main as needed. While doing as much it CAN on it's own thread.
> 
> So this is a shipped "feature" of Java or something?

It indeed is. Java supports proper concurrency out of the box, Lua does not - you have to implement it yourself with separate Lua states. There is a PR by sfan5 for this: https://github.com/minetest/minetest/pull/11131. Synchronization among threads is tricky; Lua implementations usually take a "data channel" approach.

Currently, there are two things you can do to multithread: 1. Tweak the C++ code, which, just like Java, is very well multithreadable; or 2. Don't multithread, start multiple processes instead (which in fact isn't all that different from many Lua multithreading: You have entirely distinct Lua states / VMs running and only communicating over a data channel - Inter-Process Communication tends to be slower however.
