### ISSUE TITLE
Change default daytime sky colors

### ISSUE THREAD

**Issue by TheTermos** [minetest/minetest#9449]
## Problem

I find the default daytime sky color quite dark, overwhelming and depressing. 
Yes, that's quite subjective, so to make it more objective I sampled different photos featuring clear skies, and the results were consistent, current sky color is too dark and has too little G compared to the real thing.

## Solutions

Here are the new colors I came up with after some experimentation.
The most important factors were for it too look natural, go easy on the eyes, blend nicely with terrain and foliage and look good on a variety of display devices

**before**
sky: 140, 186, 250
bgrnd: 155, 193, 240
![sky_before](https://user-images.githubusercontent.com/55103816/75676410-6e5bb400-5c89-11ea-8931-d97e22e64f4b.jpg)

**after**
sky: 150, 220, 250
bgrnd: 175, 235, 250
![sky_after](https://user-images.githubusercontent.com/55103816/75676504-a82cba80-5c89-11ea-9caf-e8a2d0ef40f9.jpg)

## Additional context

This would be a quick-win low-effort change involving altering just two lines in sky.cpp.

**Comment by runsy** [comment]
I love vibrant kawaii colors!!!
But again hardcoded?
What about a config setting in minetest.conf?

**Comment by runsy** [comment]
Related:
https://en.wikipedia.org/wiki/Sky_blue

**Comment by TheTermos** [comment]
> But again hardcoded?
> What about a config setting in minetest.conf?

This is probably a good idea, but the issue is about the default, 
so I'll take anything that involves changing the default color, configurable or hardcoded.

**Comment by paramat** [comment]
> I find the default daytime sky color quite dark

I find your proposal image painfully bright, it will make player's eyes adjust to the brightness, making the darker terrain harder to see. So this will cause discomfort or inconvenience to everyone.
> so to make it more objective I sampled different photos featuring clear skies, and the results were consistent, current sky color is too dark

Precise realism is not important, especially when it causes discomfort to the eyes.
Besides, it is possible to have a really deep blue sky on a clear bright sunny day, which is very pleasant.
The current sky colour is not dark, it is already fairly bright and hazy and looks like a realistic brightness.
> The most important factors were for it too [...], go easy on the eyes,

This is ironic, it is not easy on the eyes at all. Your image actually causes me slight eye pain.

The proposed change would cause me severe visual discomfort, i would have to then darken my monitor, making terrain and darker areas more difficult to see, also causing visual discomfort.
So i would have to use a specially compiled MT to keep playing, which would be an extreme inconvenience.

The current sky colour brightness has not caused complaints of brightness or darkness from users, i cannot remember any before this issue, so the current brightness is obviously a well-chosen compromise.

So i am very strongly opposed to just changing the hardcoded values :-1:

Sky colours could become user-customisable, which would then satisfy everyone without ruining MT for others. I expect there is already an issue requesting that.
Perhaps you could work on that? After Jordach's sky PR is merged.
> This is probably a good idea

=)
>but the issue is about the default,

The default brightness is already a good compromise, due to the lack of complaints either way, so i would be :-1: for altering the default brightness to what you propose even if customisable, for the reasons above, the glare makes terrain and darker areas more difficult to see.

**Comment by rubenwardy** [comment]
The suggested colors look terrible. I suggest basing the colors in reality rather than tweaking to what looks best for you

**Comment by TheTermos** [comment]
> I suggest basing the colors in reality rather than tweaking to what looks best for you

That's what I did exactly. Did you?
Current MT default sky color is not based in reality, it is shifted towards red.

However, 'terrible' doesn't leave any room for discussion, case closed.

**Comment by TheTermos** [comment]
> I find your proposal image painfully bright

Painfully is quite a strong word, considering you seem to have made the opinion based on just the image. 
Thing is, it's impossible to get that looking at it on the page against white background, and it's difficult not to get it if you then click the image and switch to black background.

Doing colors is tricky, there are visual illusions involved, that's why I took the time to test it ingame, on different display devices. Actually a bit darker would still look good on most devices, but too dark on some.  

Just wanted to test the grounds, now I know.

**Comment by sorcerykid** [comment]
Part of the problem as I see it (no pun intended) is that terrain in Minetest looks glaringly flat (no pun intended again) because of lack of shadows. So it doesn't help that there already is so little perceptible contrast to begin witth, which no doubt overemphasizes the apparent brightness of the sky. That's just a hunch.

**Comment by Wuzzy2** [comment]
This issue is completely pointless because games can already customize their sky color with `player:set_sky()`. As paramat has pointed out, the current default sky color is the best compromise.

Just leave the default untouched. Request sky color changes from the respective games instead.

**Comment by runsy** [comment]
> This issue is completely pointless because games can already customize their sky color with `player:set_sky()`. As paramat has pointed out, the current default sky color is the best compromise.
> 
> Just leave the default untouched. Request sky color changes from the respective games instead.

Only for player or game/server space?

**Comment by TheTermos** [comment]
> This issue is completely pointless because games can already customize their sky color with `player:set_sky()`. 

This issue is about the default, not about whether there are ways to customize sky. Even it set_sky worked remotely similar to default behavior (it doesn't), it would be irreleveant to the question asked. 

> As paramat has pointed out, the current default sky color is the best compromise.

Current default sky color was picked randomly, nobody ever gave it any thought.
Looks like it's too late now.

**Comment by runsy** [comment]
Well, I've checked the color in game and is way better than default. But only is my opinion and my eyes indeed hahaha.
The change is coded in 2 lines, so I will implement in my packed game. Thanks Termos to show me how to do it. I am happy now.

**Comment by sorcerykid** [comment]
Perhaps it might be worth making the "Default Sky Color" a setting on the main settings page (and in minetest.conf), with a dropdown of presets. There could be maybe three presets: Serene (current), Natural (Termos' proposal). and Alien (just for fun). It honestly doesn't really make sense to me why the default sky color is even hardcoded in CPP to begin with.

**Comment by rubenwardy** [comment]
> why the default sky color is even hardcoded in CPP to begin with.

It's not hardcoded, there's an API to change it.

I oppose adding more settings for something like this, settings cause an explosion of state and make things harder to test, and so should be avoided.

> > I suggest basing the colors in reality rather than tweaking to what looks best for you
> 
> That's what I did exactly. Did you?
> Current MT default sky color is not based in reality, it is shifted towards red.

I had red shift on which made it look worse, but it's still too turquoise. There is also no noticeable gradient.

![image](https://user-images.githubusercontent.com/2122943/75831893-ae678780-5dac-11ea-8c2e-275ac6d6007d.png)

comparison of current, Termos' proposal, and a sky gradient I found which matches reality closer:

![image](https://user-images.githubusercontent.com/2122943/75831855-909a2280-5dac-11ea-8e1f-35bea7113552.png)

**Comment by sfan5** [comment]
> there's no gradient in MT

technically, a gradient with one step inbetween is also a gradient
![grafik](https://user-images.githubusercontent.com/1042418/75911762-597d4d00-5e50-11ea-9992-0b8d6c94912d.png)


As a more serious suggestion, perhaps an option for using a sky color gradient should be implemented.

**Comment by TheTermos** [comment]
> As a more serious suggestion, perhaps an option for using a sky color gradient should be implemented.

There's already that overlay used during sunset that could probably be used to gradient-like effect during daytime, but it seems the way things are looking now, any work put into this could be just waste of time. 

There's a reason why I used that particular color, it's because I had to pick just one, and that was the proper color to appear on the sunny side. Any other would look off next to the sun, and presence of the sun is more apparent that it's absence.

**Comment by TheTermos** [comment]
Just for fun, a poor man's sky gradient, done using existing "far foggy things" except their top edges have been lifted to match the real thing more or less. 
- we're loosing the horizon line, but that doesn't seem to be a problem
- now seen at an angle, their corners become visible so they look skyboxy, but maybe it's acceptable in a blocky world, otherwise they could be made some n-gons instead of square pens.

True gradient would require some work, because when skybox isn't used, the sky is done using just background color.

![screenshot_20200306_173030](https://user-images.githubusercontent.com/55103816/76110876-962b7e80-5fdf-11ea-9d36-72f2bec200f6.png)

**Comment by paramat** [comment]
Closing as we have merged the sky gradient PR, which has new colours.
