### ISSUE TITLE
Regression of image_button appearance

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9492]
##### Minetest version
```
0cb34ce158989b66ecd42257dbed6729a338ff1e
```

##### Summary
The `image_button` formspec element appears differently in -dev than it appeared in 5.1.1. This is a regression.

@rubenwardy

##### Steps to reproduce
1. Start MineClone 2 in Creative Mode
2. Open inventory
3. Check out the creative tabs

In 5.1.1, it looks like this:

![](https://satoshiupload.com/images/suOHsudrgL.png)

But in -dev, it looks like this:

![](https://rwdy.uk/G15EV.png)

The relevant code for the tabs is in `mods/HUD/mcl_inventory/creative.lua`.

**Comment by Df458** [comment]
Going by the code, I'm fairly certain you mean `item_image_button`...

The cause of this bug is very simple: The element used to be 2 elements in the backend, and due to the old z-ordering it was possible to place elements *between* them (which is what you did). Because the element is now a single element instead, the old z-ordering method needs to either place the whole thing above or below.

As far as I'm aware, there's no simple solution that can give the previous behavior without throwing out several formspec improvements and 'un-refactoring' code. However, there is a very simple fix:

`style[<button name>;border=false]`

Conveniently, adding this line before the offending button will give the correct behavior in 5.2.x without breaking compatibility with 5.1.x. On the other hand, this requires intervention from modders. I will leave the call to the coredevs.

**Comment by rubenwardy** [comment]
Some clarifications:

In 5.1.1, the item_image_button was drawn in two parts - the actual GUI element renders below images, and then the item renders on top of _everything_ (manually, not as a GUI element).

In 5.2.0-dev, the item_image_button is now a single element which renders at the same level as a normal button. This is a bug fix that unfortunately results in MCL2 breaking. The general policy of supporting legacy formspec versions is to attempt to replicate formspec v1 behaviour using crude hacks, it's up for discussion whether this should be done here

-------

To prevent mineclone2 from showing the gray button, you can use the following style:

```
style_type[item_image_button;border=false]
```

You may also wish to consider removing the image entirely, and showing the background in the item_image_button like so:

```
style_type[item_image_button;border=false;bgimg=mcl_tab_background.png;bgimg_middle=10]
```

**Comment by rubenwardy** [comment]
In order to replicate 5.1.0, I believe you'd need to do the following:

* Move item_image_button in std::stable_sort to below images
* Render items above everything only if formspec_version (note: how to stop multiple draws?)
* Add support for "clicking through" non-interactable elements like images (currently these will block input)

**Comment by Wuzzy2** [comment]
> In 5.1.1, the item_image_button was drawn in two parts - the actual GUI element renders below images, and then the item renders on top of everything (manually, not as a GUI element).

Ah, this is very interesting. This explains why the “gray button background” didn't appear here. So basically, MCL2 relied on a bug, haha.

Thanks for the workaround for MCL2, it works like a charm. It works in both 5.1.1 and -dev. Good. :-)

I leave it up to you how you proceed. Given that MCL2 relied on a bug, I don't mind if you don't bother "fixing" this at all. Also note that MCL2 still is on formspec version 1 (it's just too much work to convert all those coordinates).

**Comment by rubenwardy** [comment]
If you're happy then I'm happy for this to be closed

**Comment by MoNTE48** [comment]
@rubenwardy well, 5.2 breaks my inventory. Applaud standing.

```
"item_image[" .. ofs_img["food"] .. ";1,1;" .. bg["food"] .. "]" ..
"image_button[" .. ofs_tab["food"] .. ";1.3,1.3;creative_tab.png;food;;;false;creative_tab_pressed.png]" ..
```

```
"item_image[" .. pos .. ";1,1;" .. item .. "]" ..
"image_button[" .. pos .. ";1,1;blank.png;" .. item .. ";;;false;default_item_pressed.png]" ..
"tooltip[" .. item .. ";" .. tooltip .. "]"
```

**Comment by rubenwardy** [comment]
Please add a reproducable example - ie: a single string with all the variables resolved. Also, I'd appreciate a description of what is wrong - item_images shouldn't have border backgrounds, so this isn't the same issue.

**Comment by MoNTE48** [comment]
@rubenwardy 
https://www.youtube.com/watch?v=MK29S9h7Xjw
Here is a sample code. And how it worked UNTIL 5.2
Can you imagine how much time was spent on perfect alignment of all elements with the old coordinate system?
```
"image_button["6.74,-0.35";1.3,1.3;creative_tab.png;tools;;;false;creative_tab_pressed.png]" ..
"item_image["6.87,-0.15";1,1;"default:pick_emerald"]" ..
```

**Comment by rubenwardy** [comment]
#9507
