### ISSUE TITLE
Ship MTEngine with no games, choose and install from the Content Database (after main menu improvements)

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#9509]
I searched and could not find an issue for this, but the idea is mentioned in a few different places, and in one place by rubenwardy.

I would really like focus to be removed from MTGame, and for MTEngine to be considered a neutral 'game engine' for which many games are available, with MTGame being just another game (although a very significant and much used one due to how much uses it as a modding base).

Whatever games are bundled with MTEngine, they are more likely to be used instead of downloading from the Content Database, and will therefore unfortunately tend to influence the perception of the MTEngine, which then makes it a case of whether the user likes the (probably small number of) games that have been bundled. Chance of disappointment is therefore high.

By being forced to download a game from the Content Database, there is a higher chance the user will find something they like.
This also gives a good impression due to the variety of games avaialble for MTEngine.

Shipping with no games will probably have to wait until after changes to main menu, to help guide users to the Content Database to download a game.
The Content Database should probably have a list of 'featured games' (games known to be high quality) which will include MTGame (but not top of the list). MTGame should have an improved description to manage expectations of it.

Shipping with no games will make releases smaller and releasing simpler, especially compared to the previous idea of bundling a variety of games with MTEngine.

**Comment by LoneWolfHT** [comment]
For now we could add an 'Install games with the ContentDB' button (Linked to the contentdb menu) below the game selector, regardless of what games are installed.

**Comment by LoneWolfHT** [comment]
Oh, and why the downvote @Extex101?

**Comment by rubenwardy** [comment]
I support this, but it very much definitely needs to wait for main menu changes

**Comment by Extex101** [comment]
I don't think that MT should be released without a game. Some ppl dont even know about the download content button.
Besides that would mean that ppl would have to download both MT and MTG separately

**Comment by Wuzzy2** [comment]
I fully support everything that paramat said. Thanks to the Content DB, the path forwards is very clear now. This further emphasizes the role of Minetest as being “neutral” and an engine, rather than a game.

I also agree that this issue depends on a main menu rework. The interface must account for a proper game selection.

@Extex101: That's why this issue depends on a main menu rework. The main menu rework must account for the case when no games are installed, and make it very straight-forward that Minetest supports multiple games.

**Comment by sfan5** [comment]
This should definitely not be done until improvements to the main menu happen.
Starting Minetest but there not being playable content and no clear way to install it is going to lead to much more disappointment than bundling just MTG.

Care has also be taken to make offline installations reasonably easy, downloading a ZIP from minetest.net only to find out later that it's useless on its own is not a good experience.

> The Content Database should probably have a list of 'featured games' which will include MTGame (but not top of the list)

I don't think it's useful to put anything but the most widely used game on the top of such a list.

> Shipping with no games will make releases smaller and releasing simpler,

Do you propose that MTG releases on its own pace exclusively via CDB (and Github)?
If this is done, it will also need to be decided how much compatibility it is going to provide, e.g. keeping close to the old model of "latest MTG release only runs with latest engine release".

　

I generally support the engine being more neutral / promoting different games, but I'm not sure if bundling no games is the best way to go about it.
Bundling more games than just MTG (+ promoting CDB) should always result in a better user experience than bundling no games and having to download one or two to even get anything to work.

**Comment by appgurueu** [comment]
I'm working on [Mainmenu Improvements](https://github.com/minetest/minetest/pull/9505).

**Comment by Warr1024** [comment]
Unbundling the games is also an excellent way to better decouple the games' release cycles from the engine's.

Players who don't install games via the content browser will be less likely to know about the content browser, and thus even more unlikely to ever update the games.  This forces bundled games to follow a very conservative development process, and avoid innovating, for risk of leaving players with a bad impression of Minetest overall, being unaware that they can update the game to get the fix instead of having to wait for an engine release.  Conservative development cycles are fine for some games that are at a "mature" stage, but it will impede the development of new games that would help better showcase the versatility of the game engine.

**Comment by v-rob** [comment]
I believe that Minetest Game should be at the top of the featured games list.  Here's why

1. MTG is the most stable game at any one point.  It is _very_ mature and bugs are rare.  If a player downloads a buggy game, they will get a very bad impression.
2. Many existing players who like MTG may wonder where it has gone, so we need to make the transition as easy as possible.
3. If MTG is the first content people try out, they will find it is similar in a way to Minecraft, and many people will probably be fine with that.  If they are not, they will know that other games exist because they had to choose one in the first place.
4. Most mods are designed with MTG in mind, so having people download MTG will dramatically increase the likelihood of mods being compatible as opposed to, for instance, MineClone 2 being the first game on the list.

**Comment by Wuzzy2** [comment]
No matter if MTG is featured or not, definitely NOT on top.

1. "MTG is stable": MTG is not alone with that. I do agree, however, that buggy games must not be featured
2. "People wonder where it has gone": Wrong. Those who have MTG, already have it. They just need to click the update button.
3. "They will find it is similar in a way to Minecraft": Absolutely not. No mobs. No enchanting. No status effects. Very little gameplay depth. No crafting guide. Almost no buildings. I could go on. It's always the same story, it happened over and over again: Newbie finds MTG, is disappointed about the lack of content, runs away screaming. Especially the lack of mobs will disappoint most people. The lack of crafting guide makes it newbie-hostile and it's also just bad usability that you always must “tab out” to your browser to open that wiki. MTG is NOT what newbies should see. MTG is for advanced players ONLY as they first need to learn how the mod stuff works. Ideally, new players are exposed to complete games first.
4. "Most mods are for MTG so its more likely they will work": Bad argument. This is actually just a limitation of the Content DB interface in Minetest which does not display the dependencies properly. It's not clear which mod works in which game. The real fix is to display which mod has which dependencies, then this argument falls apart.

The whole point of this issue is to move focus AWAY from MTG, not to further strenghen its reign. Even paramat agrees.

**Comment by paramat** [comment]
Extex101, i attended to your concern in the first post. See the issue for proposed main menu improvements, it would be made very clear and easy for a player to download a game.

> Do you propose that MTG releases on its own pace exclusively via CDB (and Github)?
If this is done, it will also need to be decided how much compatibility it is going to provide, e.g. keeping close to the old model of "latest MTG release only runs with latest engine release".

I have not thought much about this, but currently i would prefer MTG is devloped and released as before, release when engine does with compatibility synchronised.

I am not particularly opposed to putting MTGame top of a featured games list. It certainly should be near the top and visible without scrolling.
It is just that my experience and the endless complaints suggest maybe something more impressive should be top even if it is less stable.
The good points about MTGame (code quality, good maintenance) are not really things a new player is conscious of, whereas it seems that certain MT forks with lower quality games with monsters and complete Minecraft-like gameplay seem to make a better impression.
Anyway, it will help to have a longer and improved description for MTGame that manages expectations, the current one "fairly playable without mods" does not.

Heh, it is really funny now seeing people jumping to the defense of MTGame =D I am not used to this.

**Comment by paramat** [comment]
> I generally support the engine being more neutral / promoting different games, but I'm not sure if bundling no games is the best way to go about it.
Bundling more games than just MTG (+ promoting CDB) should always result in a better user experience than bundling no games and having to download one or two to even get anything to work.

I think we should either bundle multiple games or none, bundling just MTG is far worse than either of those.
Consider that we have been intending to bundle multiple games for many years already, probably 4+ years? And nothing has happened, and we now have fewer active core devs and less core dev time. So i have little hope it will happen. CDB allows us to solve this by moving to no bundled games.

I am concerned aobut the workload of bundling multiple games:
* First we have to choose, so a lot of time trying out various games.
* Deciding which and how many will be difficult.
* Bundling games means a lot of pressure to test for bugs, as any bundled game will affect the impression of MTEngine. Every release each game will have to be tested and re-assessed for suitability.

If we ship with no games, we still have the task of choosing which will be 'featured games' in CDB, but the workoad and pressure will be much less.

**Comment by TumeniNodes** [comment]
> I don't think that MT should be released without a game. Some ppl dont even know about the download content button.

To address this problem (which I am sure does exist), and even given that games can readily be found on CDB... perhaps a "games" or "install games" button/tab can be added? ( prob just "games" as the latter seems too long)

I know it seems redundant to do this but, I _can_ imagine a lack of one causing confusion.

**Comment by TumeniNodes** [comment]
I'm all for this... It's not like MTG will die off doing this, because it is "the" testing and proving ground for the engine.

 I feel as though doing this may eventually drive more people toward designing/creating new games more?
 Whereas right now the focus is mostly toward modding specifically _for_ MTG.

**Comment by rubenwardy** [comment]
I'm against bundling multiple games, because it locks the games to our release cycle and makes it unfair for games that aren't bundled. That latter point applies when just minetest game is bundled.

> To address this problem (which I am sure does exist), and even given that games can readily be found on CDB... perhaps a "games" or "install games" button/tab can be added? ( prob just "games" as the latter seems too long)
> 
> I know it seems redundant to do this but, I _can_ imagine a lack of one causing confusion.

See my main menu redesigns, they place installing games and ContentDB front and center. #6733

**Comment by paramat** [comment]
I added 'high priority' because the more i think about this the more important it seems. Removng the focus from MTG, or any game, seems to me one of the most important engine tasks we need to do.

Having no games shipped will significantly improve the impression people new to MT get:

With no games shipped, the responsibility of finding a satisfactory game is now on the user, so now they have less ability to blame others for being disappointed.
Forced to search, there is a fairly good chance they will find something they like to some degree.
Even if they do not find something they like, the variety of games they saw will give them a sense of the potential of the MTEngine, which is also a positive impression. This might also inspire them to get involved and create a game.

**Comment by Wuzzy2** [comment]
> With no games shipped, the responsibility of finding a satisfactory game is now on the user, so now they have less ability to blame others for being disappointed.

That alone is not enough. Curation will become much more important. If we just give >20 games to the player and force them to find the right one, that might be even worse. Because many games are still in alpha stage or outright suck. Nobody likes to be forced to try out 19 half-arsed broken unfinished games to finally find 1 decent one.

See #9530 and https://github.com/minetest/contentdb/issues/210.

**Comment by IFRFSX** [comment]
One thing to remind:
Even if MTG and MT are developed separately, remember to add tags corresponding to the MT engine (5.4.0/5.5.0/5.6.0/6.x...) to the release of the MTG warehouse to prevent players from playing a specific version The mt engine cannot find which mtg package to download.

**Comment by speccius** [comment]
Compatibility go _**poof**_

**Comment by rubenwardy** [comment]
This will be done with the mainmenu redesign. I don't see a need to keep this issue open

**Comment by sfan5** [comment]
I do, it serves as a reminder until the day we do actually ship a release without MTG.

**Comment by ixPost** [comment]
Yes, maybe the default game should be Mineclone5(or 2)?

**Comment by rubenwardy** [comment]
Absolutely not, those games are best off as unofficial and not endorsed by us

**Comment by ixPost** [comment]
> Absolutely not, those games are best off as unofficial and not endorsed by us. We're more than just a Minecraft clone. And we don't want any default games at all anyway

??? What do you mean by not endorsed by us?

**Comment by appgurueu** [comment]
> to endorse: declare one's public approval or support of.

**Comment by Wuzzy2** [comment]
As the founder of MineClone 2, I agree. It should not be made the default game. And I never pushed MCL2 to become that. We want to get away from the concept of a default game anyway. Also, MineClone 2 still has way too many bugs. Especially the special position of MCL2 as a MC clone makes it especially problematic to become the default game cuz this will lead to the impression MT is just another MC clone (which it is not).

My ideal world is when Minetest suggests *featured* games, a curated list of high-quality, polished and stable games the Minetest community can be proud of.

**Comment by ixPost** [comment]
@Wuzzy2

Ok, your right.
