### ISSUE TITLE
Visual node connecting issue with hardware-colored drawtype "glasslike_framed"

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest/minetest#9542]
##### Minetest version
```
5.0+
```

##### OS / Hardware
Operating system: Linux
CPU: x86_64

GPU model: Intel Corporation HD Graphics 620
OpenGL version: 4.6.0

##### Summary
Glass nodes are not visually connecting in the vertical direction ~~anymore (worked in <=0.4.17)~~ if they are hardware-colored and have `drawtype = "glasslike_framed"`.
**EDIT**: Plain nodes without altered `param2` values work as expected.
**EDIT by paramat, author's text from below:** I might have been mistaken with the "working in 0.4.17" part, sorry (edited above) i think the tinting was achieved with separate nodes back then... Non-colored glass works as expected, the issue arises only if it is colored (param2 changed).

Example:
<img src="https://user-images.githubusercontent.com/41878182/65702709-c4498180-e083-11e9-8d38-17390013d3e2.png"></img>

##### Steps to reproduce
Install the mods:
* `unified_dyes`
* `framedglass`

Place two rows above each other and color them with the airbrush pistol.

**Comment by sfan5** [comment]
> (worked in <=0.4.17)

**Comment by Desour** [comment]
`glasslike_framed` nodes seem to use two bits in param2 to decide whether to connect vertically and horizonally:
https://github.com/minetest/minetest/blob/0877587cce1d96b1c8c009221684ab382e8f1929/src/client/content_mapblock.cpp#L708-L709
There should probably be a check for `f->param_type_2` being something.
I wonder if the functionality of not connecting vertically or horizontally is even used anywhere. (Liquid-filled glass probably uses vertically not connecting, but that could also be decided based on whether the param2 value is neither 0 nor full.)

**Comment by BuckarooBanzay** [comment]
> Due to the large amount of changes since then, this unfortunately isn't very useful.
Do you happen to know if this worked in 5.0?

I might have been mistaken with the "working in 0.4.17" part, sorry (edited above). Non-colored glass works as expected, the issue arises only if it is colored (`param2` changed).

**Comment by paramat** [comment]
> glasslike_framed nodes seem to use two bits in param2 to decide whether to connect vertically and horizonally:

So it seems that glasslike_framed(_optional) nodes are incompatible with hardware colouring.
Perhaps the mod has a bug where it should be looking at paramtype2 and avoiding applying hardware colouring to `paramtype2 = "glasslikeliquidlevel"`?

Perhaps glasslike_framed(_optional) nodes that are not `paramtype2 = "glasslikeliquidlevel"` should automatically be assigned a new paramtype2 so that mods can check the param2 usage?

glasslike_framed(_optional) nodes used to lack a paramtype2 for the liquid level feature but i added that a while ago. This seems to be another case of a param2 usage that is lacking a paramtype2.
As before, i think that any usage of param2 must always be flagged by a paramtype2 value so that mods can detect it.

(The implementation of glasslike framed nodes is a mess because the liquid tank feature was squeezed in alongside everything else. Liquid tanks should have been a different drawtype.)

**Comment by An0n3m0us** [comment]
Confirmed; occurs in `5.3.0-dev-7e21b3c-dirty`:
![kép](https://user-images.githubusercontent.com/49789044/79278950-ca2e7500-7ea4-11ea-8260-6a3fb44823ce.png)

**Comment by BuckarooBanzay** [comment]
I found an interesting exhibit on my server that shows the issue with the overlapping param2 values:

![screenshot_20200918_213318](https://user-images.githubusercontent.com/39065740/93637850-9a0c7480-f9f6-11ea-9636-09b02e18d458.png)

Top-left is 0 and increases to the right / down

Thanks to `Huhhila` :smirk:

**Comment by paramat** [comment]
> glasslike_framed nodes seem to use two bits in param2 to decide whether to connect vertically and horizonally:

So, this drawtype is incompatible with hardware coloring, perhaps we can just document this?

**Comment by BuckarooBanzay** [comment]
> > glasslike_framed nodes seem to use two bits in param2 to decide whether to connect vertically and horizonally:
> 
> So, this drawtype and "glasslike_framed_optional" are simply incompatible with hardware colouring. Perhaps we should document this? Currently the documentation does not list which drawtypes work with hardware colouring.
> The only bug here is perhaps the lack of checks to prevent hardware colouring being applied to these drawtypes.

Err, i _do_ think that drawtype should work with hardware-coloring, the issue here is that the vertical/horizontal connection info is actually expected to be in the `param2` value when it just should check the neighboring nodes...

**Comment by paramat** [comment]
Making 'glasslike framed' work with hardware colouring is currently not possible, as 2 bits are used for HV merging and the remaining 6 bits are used for the 'liquid tank' feature. So param2 is entirely used, no bits remain for hardware colouring.
>  the issue here is that the vertical/horizontal connection info is actually expected to be in the param2 value when it just should check the neighboring nodes...

That is a request for a new implementation. "it just should check the neighboring nodes" may not be possible or as easy as you suggest, and has not been discussed yet.
Besides, even with those 2 merge bits freed, the other 6 bits are still in use for the liquid tank feature, so this is not a solution.

The fact that hardware colouring partially functions on this drawtype at all is the bug here, it should be disallowed for this drawtype as it is understandably and unavoidably broken.
Once we fix that, then we can consider a new implementation in a separate issue, but that will be difficult to do.

**Comment by paramat** [comment]
What you are experiencing here is a mod error, partly caused by poor documentation.

'glass framed' has never worked properly with hardware colouring.
My guess is the modder applied hardware colouring to a 'glasslike framed optional' node, saw it worked in 'glasslike' mode, but did not properly test it worked in 'glasslike framed' mode.
The mod or game author should be contacted and asked to change the drawtype of the node from 'glasslike framed optional' to 'glasslike', then hardware colouring will always work.

This issue is therefore for:
* Documenting that hardware colouring cannot be used for 'glasslike framed' or 'glasslike framed optional' drawtypes.
* Disallowing hardware colouring from functioning at all for the 'glasslike framed' drawtype.

**Comment by sfan5** [comment]
It's not unavoidable at all, the liquid level is not inherent to glasslike_framed. `paramtype2 = "glasslikeliquidlevel"` enables the liquid behaviour and there is no reason `paramtype2 = "color"` could not enable another behaviour.

Why does glasslike framed use two bits to determine merging behaviour anyway? This isn't documented anywhere.

> That is a request for a new implementation. "it just should check the neighboring nodes" may not be possible or as easy as you suggest, and has not been discussed yet.

No it's not, the code is literally already there:
https://github.com/minetest/minetest/blob/0877587cce1d96b1c8c009221684ab382e8f1929/src/client/content_mapblock.cpp#L752-L761

**Comment by paramat** [comment]
Sorry, i was thinking about this after i last posted and realised i had misunderstood, and realised what others were writing about and that they were correct. What i realised is what sfan5 has just posted.
I agree with changing the issue title back to the previous version.

**Comment by paramat** [comment]
I have done some investigation of the commit and code history.

The H/V merging according to 2 param2 bits is a separate feature to the liquid tank feature, but was never documented. The liquid tank feature was originally not documented either (a characteristically sloppy RBA contribution, the PR description only had 7 words, also a sloppy review) and i added the documentation later but missed the H/V merging feature.
So the H/V merge feature is probably not used, and because it was never documented can be removed.
Without those 2 merge bits used this drawtype will then work with hardware colouring, fixing this bug.

However, those 2 merge bits are harmless when this drawtype is being used with paramtype2 = "glasslikeliquidlevel".
So i propose this as a simple initial fix:
* Keep the H/V merge feature, for now at least, it could possibly be removed later.
* When paramtype2 = "glasslikeliquidlevel", set H/V merging by reading those 2 bits, as before.
* With any other paramtype2, ignore param2 and automatically set merging to be horizontal and vertical.

The H/V merge feature has some usefulness in liquid tank mode, as liquid tanks look wrong if they merge vertically, due to how the interior liquid is rendered as a fraction of each node.

I will make a PR.

**Comment by sfan5** [comment]
> Keep the H/V merge feature, for now at least, it could possibly be removed later.

Does this imply you suggest to keep it undocumented? Or add a note that it might be removed?

**Comment by paramat** [comment]
Hmm good question. Because H/V merge is harmless in liquid tank mode we could keep that feature and document it.
I am neutral on whether H/V merge should be removed later, i will go with core dev consensus on that.
For now i think i will document it as there is not really any need to remove that feature in liquid tank mode.

**Comment by paramat** [comment]
Ugh ... actually i think it should be left undocumented, as there is a high chance the H/V merge feature will be altered later, so we should not encourage its use.
Preventing vertical merge is useful for liquid tank mode, but preventing horizontal merge is useless, so the H/V merge feature probably needs rewriting and simplifying.
Actually, we should probably just automatically prevent vertical merge in liquid tank mode, as that is always necessary. Which means we never need to read those 2 bits for merging.

**Comment by paramat** [comment]
PR #10417
