### ISSUE TITLE
Sometimes certain packets don't go from server to client

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#9592]
##### Minetest version
```
5.1-5.2, maybe earlier
```

##### Summary
Sometimes when playing on servers certain packets won't be sent to my client at all. This results in:
* Being able to send messages in chat that don't show up for you but show up for everyone else in the server
* Being able to teleport around with /teleport but not receiving any indication in the chat that the command even worked
* Being able to shoot and kill mobs (with a gun that shoots but doesn't lose wear or make sounds like it should) that take knockback, follow you around, and die but once dead don't disappear and don't get their velocity reset, so they just float off into the distance

During this player movement is also usually smooth and accurate. But I have seen a few cases where the packet-deprived client isn't aware of new players joining or position changes

An example of this:
Top window is the `Lone_Wolf` client (Client 1)
Bottom window is the `Lone_Wolf2` client (Client 2)
![image](https://user-images.githubusercontent.com/28972859/78458365-91e99400-7665-11ea-9d93-e25a2a914c11.png)
In the image Client 2 is aiming at the back of Client 1 which thinks Client 2 is way over by the other red player. But that other red player's movements are smooth and on-time for both clients

I was experiencing no internet lag at the time, I was in a voice chat that had no lag at all, and the messages of both clients showed up instantly in chat

I say packets aren't being sent but I can't confirm that. It's just what it looks like.
It might actually just be delaying of packets, since a few times I have recieved the updates as if catching up on some lag

##### Steps to reproduce
Seems to be random, although it usually happens a few minutes after joining a server.
Possibly only to clients that sit in the pause menu for a while?

**Comment by sfan5** [comment]
> `5.1+, maybe earlier`

**Comment by LoneWolfHT** [comment]
5.1.1 and 5.2

**Comment by LoneWolfHT** [comment]
In that screenshot you can see the full version number in the windows

**Comment by LoneWolfHT** [comment]
@Jordach was using latest master I believe, they were the one running the remote server
Jordach, who is also the third client, was seeing movement fine from what I can tell

> Can you reproduce this in MTG?
Without mods?

**Comment by sfan5** [comment]
> Without mods?

Ideally yes. If it only reproduces with mods, try to find the minimal set that will reproduce it.

**Comment by LoneWolfHT** [comment]
It looks like this happens on two servers with skyboxes/lots of hud changes

**Comment by sfan5** [comment]
"lots" is an understatement. When I tested this with Jordach, his game sent on average 230 `HUDCHANGE` packets every second (even if nothing has changed).
The problem then happens when a packet is lost: since the HUD packets are only delivered in order, everything else stalled until that one packet could be resent.
The new PR only helps with this because it moves `HUDCHANGE` to the correct channel, the same problem can still occur and stall everything HUD related this time.

In the end you are still throwing way too many packets at a single client and a single network hiccup can break everything at any time.

**Comment by rubenwardy** [comment]
Possibily related topic: https://forum.minetest.net/viewtopic.php?p=375061

I only skim read

**Comment by LoneWolfHT** [comment]
Yeah, that sounds like it

**Comment by Warr1024** [comment]
I have seen what might be related issues involving HUDs.  It seems like HUD add/remove packets are sometimes lost, which causes HUDs to become stale.  NodeCore uses waypoint HUDs for player nametags, and sometimes I would notice that one gets stuck in one place when it should have been deleted.  Since NodeCore caches HUD information server-side and assumes that HUD delivery is reliable, it never sends updates after that and so the HUD remains there until the client quits and rejoins.

This happened rarely with 5.2 client/server.  When I updated the client to 5.3, it seemed to happen more often, and some mods that I had that were using waypoint huds _extensively_ stopped working.  I ended up ripping out the HUD feature, but now I wonder if it was caused by the same thing reported here...

**Comment by LoneWolfHT** [comment]
I also get this when playing with a steady but extremely slow connection
