### ISSUE TITLE
Using "/teleport player" moves them forwards

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#9704]
I can't even begin to explain this so here https://youtu.be/6QlBtqeJrTg

**Comment by ClobberXD** [comment]
Wow, the command checks for collision, and even moves the player backwards if something's in the way. ;)

****

I can reproduce this too. The direction of movement seems to be aligned with the +X axis, irrespective of where the player is looking at. I can also reproduce the weird collision-detection/avoidance mechanics (lol) of the chat-command.

**Comment by ClobberXD** [comment]
@oilboi This seems to be intentional. There are two ways to invoke the chat-command:

- `/teleport x y z`
- `/teleport target_name`

Entering `/teleport target_name` will teleport you to the pos of the target. If the target is you yourself, you'll be "teleported" to the same pos. The moving forward part is because of the following:

https://github.com/minetest/minetest/blob/23c6d0c31f2e0a4a6032b0afb02fab1d5f9c517b/builtin/game/chat.lua#L392-L412

https://github.com/minetest/minetest/blob/23c6d0c31f2e0a4a6032b0afb02fab1d5f9c517b/builtin/game/chat.lua#L432-L448

When invoked using the second syntax, the code checks for a valid location nearby, by adding the above offsets to the target pos. Since the first offset is +X, you're teleported 1 node along the +X axis. If the next node is not suitable for teleporting, the second offset is applied, which is -X.

OTOH, I think that the ability to specify one's own name as target_name when invoking the chat-command can be considered as a bug. No one's so lazy to walk one node, and instead teleport themselves one node at a time. :)

**Comment by Wuzzy2** [comment]
Possible solution: Make the command a no-op when entering "/teleport <your_name>".

**Comment by paramat** [comment]
> Make the command a no-op when entering "/teleport <your_name>".

+1.
