### ISSUE TITLE
Player noticeably twitches when jumping up a node 

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#9725]
##### Minetest version

```
5.3.0-dev-6cf15cf8
```

##### Summary

The player seems to twitch every time I jump up a one node height. This happens consistently, every single time, and it's pretty easy to reproduce. *Occasionally*, the player twitches twice when climbing an 1-node high L-shaped corner.

I suspect this might be introduced by the recent collision fixes.

@TheTermos 

##### Steps to reproduce

- Approach a one-node jump.
- Make sure you're touching the side of the node you're going to jump on.
- Press jump and forward at the same time.
- Observe a twitch mid-jump.

**Comment by sfan5** [comment]
I observed this too when testing #9343 (though didn't mention it), I think it might be caused by the `stepheight` being applied when the player is almost up the node.

**Comment by TheTermos** [comment]
> I think it might be caused by the `stepheight` being applied when the player is almost up the node.

That's correct.
This behavior was intended by whomever coded that part in localplayer.cpp, stepheight is supposed to be 0.2BS when player is in air, except before it didn't always work as intended because of `touching_ground` being broken.

The twitch can be easily reproduced in 5.1 by stepping up stairs or walking over a 1 node gap, so nothing new here. Probably it has to do with 3rd person camera adjusting to abrupt position change.

**Comment by paramat** [comment]
> The twitch can be easily reproduced in 5.1 by stepping up stairs or walking over a 1 node gap, so nothing new here

This visual jolt is a recently occurring problem, or is far more noticeable than before, so it has not always done this. I noticed it start/worsen a few weeks ago.

I think the correct approach to fixing this is not to remove the in-air stepping up, as a submitted PR does, but to investigate why the camera has such a sharp movement.

When a player steps up by 0.5 nodes onto a half-node slab, camera smoothing smoothes the upward motion and it is visually acceptable, but the in-air step up of only 0.2 nodes causes this visually unacceptable sharp movement.
So my guess is camera smoothing is not working for the in-air step-up.

I think in-air stepping-up must be preserved, other aspects of movement probably rely on this.

**Comment by paramat** [comment]
Here is an experiment to investigate camera smoothing.

Use of third-person camera shows the effect of camera smoothing, because the player model will move upwards instantly while the smoothed camera lags behind. So the player model appears to bob upwards away from screen centre when stepping-up.

![screenshot_20200607_000802](https://user-images.githubusercontent.com/3686677/83956243-ab6caf00-a853-11ea-8041-1eb286ce51a4.png)

In third-person camera mode:

Try jumping onto the full node to reproduce the bug.
Try climbing the stairs.
Try stepping up onto the snow slab (0.125 nodes high collisionbox).

In my test, the player 'bobs' away from screen centre only for stairs and snow slab, not when jumping onto the full node.
This suggests camera smoothing is not functioning when the 'in-air step up' happens when jumping onto a node, causing the bug.

**Comment by paramat** [comment]
I found a disapproved and closed issue that proposed the removal of air stepheight together with a compensating increase in jump speed.
#3397

This has more detail on why the 'in-air stepheight' of 0.2 is useful. Removing it breaks many things, for example walking over 'dotted bridges', single node holes, or (closely related) walking horizontally across a diagonal slope.
It also suggests it would break the current ability to rapidly climb 45 degree slopes made with full nodes.

Adding this in case someone suggests removal of air stepheight completely, which i think has been mentioned, it would be very bad.
Looking back through history, air stepheight has been in MT for 8 years, it was added so long ago there are not even any IRC logs from that time.

Quotes from the issue:

> When the player gets near the edge, he gets teleported up a small distance and can instantly jump again

Response:
> As far as i know this is fine-tuned to enable the climbing of a 45 degree slope of full nodes fast in a rapid series of re-jumps, an almost continuous upwards motion. Your changes would seem to make this a slower climb where each jump is a jump-and-fall, [...]
A year or two ago player motion was changed which broke the fast climb feature, the changes were reverted a while after. As far as i know jump speed has been tuned so that the player will just hit the edge of the node to trigger stepheight to, in turn, enable an instant re-jump at the node edge.

This suggests that the 'in-air stepheight' has a primary purpose of enabling a rapid sequence of jumps, one per stair, when climbing a 45 degree slope made with full nodes.
This suggests that PR #9983 in its current form might break this, as it disallows air stepheight when the player is moving upwards.
