### ISSUE TITLE
Reconfigure Clang Format

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#9731]
New issue, see previous discussion in #9074 

Clang Format is highly configurable, but is currently very poorly configured for MT code, resulting in large amounts of nonsense suggestions and large amounts of whitelisted files, as well as misleading and confusing contributors and irritating core devs.

As part of this, i request that CF is configured to no longer report on indentation and alignment for readability, as this is the largest source of CF nonsense i see.

**Comment by nerzhul** [comment]
i think first we should ensure we have most of the code parts covered by the linter, we have too many ignored filed because we didn't rewrote the code style properly,
then after that we can generate a list of the wrong things we must fix in the configuration. 
I saw we have again some code style time loosing review to do on some client parts, especially, because today effort is done there

**Comment by rubenwardy** [comment]
clang format is no longer used
