### ISSUE TITLE
Interest into MSVC GitHub Actions build

### ISSUE THREAD

**Issue by adrido** [minetest/minetest#9732]
It seems the build bot has moved to GitHub actions. As GitHub also provides a windows platform, I want to ask if there is interest into a automated MSVC build inclusive Windows installer artifact?

If there is interest, I would write the action and create a PR.

**Comment by nerzhul** [comment]
hello @adrido if you can make it work, okay for me, it's a target to avoid breaking MSVC build because we don't test it. the only conditions:
* build step should not exceed 20 mins time (currently it's 7 min mean)
* we should not pay a license fee for it

**Comment by adrido** [comment]
see #9740 

- Currently the Build time including dependencies is about 20 minutes, but the dependencies are then cached, and further builds take about 7 minutes.

- Visual Studio and the Windows runner is part of GitHub Action which is free.

**Comment by appgurueu** [comment]
What would be the advantages if using MSVC? A "Windows installer artifact" I assume?

**Comment by adrido** [comment]
> What would be the advantages if using MSVC? A "Windows installer artifact" I assume?

What are the advantages of GCC/Clang/BorlandC/...?
Well, its just another compiler.
It is the native compiler for Windows, and yes, it is able to generate Windows Installers for Minetest.

The "Artifact" is just a feature of Github Action, that allows to download the package or any other "artifact" that is uploaded during the build.

**Comment by Caellian** [comment]
I already wrote an action for building CMake project on Windows. You are free to copy it over from 'java-decompiler' if you want.
It's currently failing due to some issues I'm having with includes provided by Conan, but you won't have to start from scratch if you decide to implement it.
I personally don't care much about Windows, but it would be nice to have a shiny badge on the Readme for each system so that people know that everything is supported.

**Comment by sfan5** [comment]
(Already done)
