### ISSUE TITLE
Objects inside blocks turning black sometimes

### ISSUE THREAD

**Issue by Echoes91** [minetest/minetest#9752]
##### Minetest version
```
Minetest 5.2.0 (Linux) using Irrlicht 1.8.4
```

##### OS / Hardware

Operating system: Arch Linux x86_64
CPU: Intel Pentium Gold G5400

GPU model: Nvidia GeForce GTX 1050
OpenGL version: 4.6.0

##### Summary
Object entities that find themself partially inside a block sometimes turn black. There belows are my [spears](https://forum.minetest.net/viewtopic.php?f=11&t=13367), they are flying entities that stick into nodes:
![Schermata da 2020-04-23 23-41-26](https://user-images.githubusercontent.com/11097013/80286878-4e4aed00-872e-11ea-9a72-8b6b9b9efbbd.png)
The chances seems related to orientation but not consistently.
A similar issue could be the player turning black in #9625 

##### Steps to reproduce
Throw some [spears](https://forum.minetest.net/viewtopic.php?f=11&t=13367) into nodes (or any other mod object that can go partially inside a node) until it happens.

**Comment by Desour** [comment]
How bright an object appears depends on the light value of the node that it's currently in, for stone that is always darkness (paramtype != "light"). This is normal behaviour.

**Comment by paramat** [comment]
Yes. Object brightness is determined by the light level at object centre. If the object centre is inside a solid node it will be dark. So this is expected. It would be far too complicated and intensive to partially light objects according to what parts are outside nodes.

**Comment by sfan5** [comment]
This behaviour is easily explained but it's good good either, partially stuck items should obviously not be entirely black.
(In fact if you consider this a limitation of the engine it should be "Bug + Won't fix" rather than "Not a bug".)

> It would be far too complicated and intensive to partially light objects according to what parts are outside nodes.

It is not necessary to do that though. For example taking the maximum light at four collisionbox points would be a noticeable improvement in many cases where an entity would otherwise be incorrectly shaded.

**Comment by paramat** [comment]
Duplicate.
See #2467 and PR #7626
