### ISSUE TITLE
FormSpec: Complex buttons

### ISSUE THREAD

**Issue by v-rob** [minetest/minetest#9754]
## Problem

Formspec buttons are really cool now, but they're kind of limited in one respect: You can only have text in one spot on the button, and images are forced to be stretched across the entire button.  This is fine in most circumstances, but some more complex buttons are necessary, or at least desired, in some circumstances.  For instance (from #8758):

![Complex buttons](https://user-images.githubusercontent.com/2122943/73688251-8c9eb600-46c3-11ea-90d1-1a41a2739d8a.png)

These buttons are created using plain textless buttons with labels and images on top of them that can be clicked through.  Overlaying buttons with other elements is the most versatile way of making complex buttons because you can have multiple images, tons of different aligned text, animated images, boxes, etc.

The problem comes when trying to style the button.  It is impossible to style these other elements associated with the button.  You can hack around with `style_type` after the button, but prepends can't insert `style_type` wherever they want.  Plus, what if you want to make the text green if the button is pressed?  It's impossible to combine with state selection.

## Solutions

I think that the easiest way to do this would be to make a button/container hybrid.  Something along the lines of this:

```
button_container[x,y;w,y;name]
    other_elements[bla]
button_container_end[]
```

Obviously, this is a really rough estimate how it could be done, and of course this is much lower priority than many formspec things.

## Alternatives

What we have currently is fine for a large majority of things because I don't expect people to care about state selection combined with things like textcolor too much.  But I do think that it is something that we should consider going forward.

**Comment by Extex101** [comment]
And button_container9[]

**Comment by Df458** [comment]
I support this (I've brought up the possibility once or twice in other PRs), and it should be pretty straightforward--all current `button` elements are coded as containers that display child elements for their content already, so we really just need one that holds user-provided elements.

`button_container9` makes no sense though. All button elements support 9-slice backgrounds already as of 5.2.0, and if this proposed button bases itself on the same base class it will implicitly support this as well.

**Comment by v-rob** [comment]
Some things that should be thought about:

* How should we handle styling the inner elements?  We could style them globally, so setting `textcolor` to `green` on the button container thingy would make all of the labels green, or we could handle the child elements somehow, perhaps similar to the `:nth-child()` selector in CSS.
* Should we support `image_button` and `item_image_button` as well in this?  Since we can add images and item images manually, it might not be necessary.
* Should we let interactable elements be children of button containers?  It doesn't make much sense to do so.
* Would `content_offset` and `padding` apply to the child elements?  It might make sense to apply `content_offset` to some things, like text, but not others, like background images.  And how could `padding` work when we're using normal coordinates?  Perhaps, if interactable elements can't be children, then `content_offset` could apply to the children selectively.

**Comment by Df458** [comment]
Here are my thoughts:

> How should we handle styling the inner elements?

- This is a tough question, because formspecs aren't very hierarchical right now we're breaking some new ground... I think certain properties (such as textcolor) should naturally apply to child elements unless a more specific value is provided. As for selecting child elements, it's on my to-do list (I believe it will be necessary for effectively styling more complex elements, such as scrollbars). Rather than `:nth-child()` I was thinking more along the lines of an `element1>child1` type of selection for the time being .

> Should we support image_button and item_image_button as well in this?

- I don't think that would make sense. The goal for this proposed button is custom content, so making variants with predefined content would be a little weird. The only benefit I see would be support for something like `image_button`'s `fgimg` changing in different states, but there are more flexible solutions (changing templates by state in WPF fashion, or mixing state and child selection)

> Should we let interactable elements be children of button containers?

- It doesn't make sense, but I think we should still allow it. Making this restriction complicates the API and restricts features (albeit in a way that's unlikely to cause issues for users). While adding interactable children doesn't make much sense from a UI design perspective, I don't think blocking this is worthwhile.

> Would content_offset and padding apply to the child elements?

- Yes, always. We want consistent and predictable behavior, and background images should be added via style properties rather than child elements. In the future, as we improve containers and support more advanced layouts, consistency will be a very valuable thing. We don't want a repeat of the `real_coordinates` transition if we can help it.

**Comment by v-rob** [comment]
> I was thinking more along the lines of an element1>child1 type of selection for the time being.

This kind of brings up another thing I have a problem with.  How, then, could we select a specific label, seeing as they have no name?  HTML has `id` as a global attribute, but that's hard to apply to formspecs.  The best we could probably do is add some ridiculous esoteric syntax like `label[x,y;text]name]` taking advantage of formspec's bad syntax checking, but that's obviously a bad solution.

Of course, for now, `style_type` will have to do.  But ways to select individual nameless elements is something we should think about going forward.
