### ISSUE TITLE
New GUI design guidelines

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#9802]
Minetest GUIs are inconsistent and unpleasant to look at. I suggest formalising a new design that is nicer to look at, and will apply to the engine.

I don't have the experience to work on this by myself, the limit of my skills are  flat rectangles, border-radius, and drop shadows

## Contents

This design guideline should cover padding/spacing, theming, and colors.

## Questions

* Pixel art or vector?
* Flat or otherwise?

**Comment by tacotexmex** [comment]
Great idea! Any inspiration from other projects/products? 

How about building a design system providing both guidelines _and_ actual mockup components?

**Comment by nerzhul** [comment]
we use the standard irrlicht one, and also our menu organization is quite unfriendly. Minecraft one (which is pretty common in any modern game) is far more friendly that our tab big console.
Also theming the interface to a game one can be nice. But remember one thing, if we pass this idea, it means minetest is a game not just an engine and we should continue on that way.

**Comment by TumeniNodes** [comment]
I'd love to see vectors used for scalability

**Comment by Zughy** [comment]
> Also theming the interface to a game one can be nice

Please don't. The main menu should be neutral, without any reference to whatever game. Minetest is an engine and it should have its own main menu. I'll try to represent what I'm talking about whenever I'm free

**Comment by Wuzzy2** [comment]
Don't make the mistake in thinking that having a “neutral” main menu means it needs to need bland and boring.

I think the idea of 100% neutrality might even be misguided, as this would just lead to the most generic design ever, which is a major artistic constraint and will probably just make the main menu very bland and boring.
As Minetest is a voxel game engine, a theme/style based on voxels might make sense. I think the idea of “neutrality” could be seen that it simply does not allude too strong to any particular game, but that should be really only a rather loose constraint. I think the main menu should still be allowed to have its own distinct style, let's call it “the Minetest style”, something that just looks nice and will be recognized by players immediately as Minetest.

The ugly gray style really needs to go away. It has no life and soul in it. It really looks like a cheap early alpha throwaway prototype than something “game-y”.

However, I do agree that Minetest should not copy the style/theming of a particular game, especially not Minetest Game. The threat of reintroducing the MTG bias is too big.

---

And now I am going to post my ideas for this issue. It's only about the main menu and I have written the text a while ago, I just didn't send it. This issue now promted me to actually send this. Here we go.

---

## Problem
The default style of the main menu (and by extension, the default style of Minetest) is really ugly. It looks more like a very early tech demo and just uninviting.

First, it's sad graytones everywhere. Second, *everything* is flat, and there's little usage of borders. When borders are used, they are used in an inconsistent manner. Third, the background just looks boring.

I know, style is something highly subjective, but I think many players agree that the main menu looks bad.

Finally, the style hasn't been really changed for a very long time. The only major change was when the background turned from a dirt background to sky. After that … nothing happened, style-wise.

I think a reason why the style hasn't been touched is probably due to a perception that Minetest must remain “neutral” and “pure” in some sense. That argument might be valid as defense against going a little over the top with styling, but it should not be an excuse to not even try to make Minetest look nice.

NOTE: This text is only about the visual styling, it's NOT about usability or layouting (we have other issues for that).

## Overall Solution

Do a COMPLETE overhaul of the style. I don't think that a few little tweaks will cut it.
That is, rethink the main menu background, experiment with various styles for the buttons, try out different color schemes, add decorations. Everything that can be styled, should be styled.

I'll set Windows 3.1 as a benchmark. Minetest should not look worse than Windows 3.1. :D It's a very low bar, but it's a bar nonetheless. :)

The next section is for my concrete ideas I have for the main menu:

### Idea 1: Context-sensitive backgrounds

For menus that are not game-specific, use a special background that is more interesting than just the boring sky. The background could be used as indicator in which menu you are.

Contexts:
- Main menu
- Settings
- ContentDB
- Credits
- Loading
- etc.

Each background should have a fitting theme to it. I think a different background can make a HUGE difference already.
Experiment with different art styles, more than just boring clouds, or get rid of the clouds altogether.

Some possible ideas:

- Cube: A large rotating 3D object (usually cube) in the empty screen area
	- main menu: Minetest logo, but in 3D
	- join server: planet Earth cube
	- settings: spanner
	- keyboard settings: key
	- ContentDB: cardboard box
	- texture packs: picture frame
	- credits: smiley face?
- Retro: tiled, possibly moving pixelated 2D background image. Very simple.
- Cube rain: Let rotating colorful cubes fall from top to bottom
- Isometric Disco: Render some floating single-color cubes at random positions in the background with isometric perspective, some of them flash up from time to time. The color changes depending on context
- Landscape: Render cubes that resemble a "landscape" (but with a single-color cubes only), then yaw the camera slowly, so it (kinda) looks like as if you are in the game. A "landscape" can be just like something you would encounter in a real game. Two rules: 1) The cubes must all fit in the raster like in the real game. 2) Each cube is a flat single color. It could be a traditional grassland or something a player would build, or maybe something random. Landscapes could be implemented as hardcoded meshes to keep polygon count low. This mode could use one of multiple possible "landscapes", either at random or depending on context. There could be many such landscapes, just something fun to look at

### Idea 2: Details!

* Eliminate the flat-looking stuff.
* Experiment more with opacity. Consider eliminating semi-transparent menus altogether
* Experiment with color
* Use 9-slice as much as possible
* Make buttons look 3-dimensional and not flat.

Thicker outlines. 1 px is too thin.

Different button style. Higher contrast, should look more like pressing them.

### About default style

NOTE: This rough list of design ideas should apply to main menu only. The *default* style should not be touched IMO, in order to not break games that rely on it. It's just that the *main menu* will no longer use the default style. Thus, the default style is just something for games that didn't spefiy their own style. One might say “fallback style”.

### Possible idea X
Maybe you have better ideas, please post! :)

**Comment by paramat** [comment]
> if we pass this idea, it means minetest is a game not just an engine and we should continue on that way.

Well we obviously cannot do that =)

Engine formspecs need to be fairly neutral and universal as they apply to all games, whereas MTG can be more styled.
We should not consider MTG in this issue, MTG formspec styling is an independent consideration and should be dealt with elsewhere.
> Backwards compatibility. Does changing the Minetest Game theme drastically break mods? If so, the design should be kept dark theme

This is irrelevant and should not be considered here.

**Comment by mercorii** [comment]
Creating formal style guide(lines) is a pretty good idea. It would give minetest more professional vibes design wise. It could also attract more ux/ui/graphics designers to take part in the development of minetest.

> Great idea! Any inspiration from other projects/products? For open source design the Elementary Human Interface Guidelines are pretty stellar as a starting point, but there should be more good resources out there.

Elementary Human Interface Guidelines is definitely something worth having a look at. They describe the intentions of the design alongside the actual designs. The "why" is as important as the "how", because it tells when it is okay to break the rules, and when it is extremely important to stick to them.

> Don't make the mistake in thinking that having a “neutral” main menu means it needs to need bland and boring.

The main menu is a great opportunity for building the minetest brand. It is probably one of the best ones in-game, if the engine itself is not counted, given that individual games can modify things to their own liking.

> I think the main menu should still be allowed to have its own distinct style, let's call it “the Minetest style”, something that just looks nice and will be recognized by players immediately as Minetest.

It's important that the menus radiate minetest brand:

1. People spend long times in menus. (Personally, many times, I spend more time in netflix's menu, than I actually end up watching their content)
2. With strong brand visible already in menu, any socially shared content where menu is visible, is immediately recognizable as minetest, and works as an advertising for the project. This could be screenshots, or twitch streams, where people wonder what they are going to do, and what server or game they are going to play, while the menu is visible.

> For menus that are not game-specific, use a special background that is more interesting than just the boring sky. The background could be used as indicator in which menu you are.
> ...
> Each background should have a fitting theme to it. I think a different background can make a HUGE difference already.

This is a very good idea. In addition to making the navigation of menus a minigame of itself, theme's break repetition, and like said also give secondary visual aids for people to see (in a snap) what screen they are looking at.

Also worth considering is that you could tell a unified story with your main menu, (with a different menu telling a different part of it). 

Take for example, Hearthstone as a good example of a game that creates a larger background story with its menus. The menus are all depicting a tavern setting, where a card game is played in a wooden box. (I think they are even selling a physical copy of that wooden box at their store). The important part being the tavern setting. I think they are using it to underline the social and warm setting of the game. In the game itself, the story is about swords and wizardry, but the menus create a meta story behind that one. One where the players can immerse themselves as tavern patrons playing with the characters. (The last part is pretty interesting, it encourages players to roleplay a fantasy character playing with fantasy characters, and shows them a playful way to approach playing the game itself. I think minetest could do something similar, and provide an optional meta level narrative for playing minetest.)

Hearthstone goes pretty deep with the meta theme. The initial loading screen of the game is even depicting the tavern's doors, before the player enters the tavern and the game starts. Even the playgrounds where the cards are played, are depicting a miniature setting inside the box (which is on a table inside the tavern).

I think a suitable story / theme for minetest could be something along the lines of "exploration". It kind of fits well with the engine's infinite worlds, and plays excellently with the fact that the game is FOSS, and provides limitless possibilities.

How could the theme then be depicted? Backgrounds for different menus could be picked with the theme in mind. Perhaps there could be other exploratory iconography or symbols as parts of the menu. Portals perhaps (just non-minecraft portals), or something that could come from a Victorian explorer society's collections (The Lost City of Z, or Indiana Jones movies could give inspiration).

The theme could also take place outside the game on minetest's site and in any promotional material, as well as in any style guide(line)s.

**Comment by nerzhul** [comment]
There is no minetest brand and minetest is not a game, you will never have that radius :(

**Comment by tacotexmex** [comment]
Some good points, mercorii. I think the Hearthstone comparison is interesting but then the "story" would need to be a meta story about the engine more than a game itself. Game themes, modes, loops all vary among the range of Minetest based games.

> There is no minetest brand

This is factually wrong, the Minetest name certainly comes with certain connotations whether you want it to or not. As soon as it's out in the wild it starts to make impressions on people. When those impressions gains group recognition, _a de facto brand is shaped_. The question is whether we want to take control of the branding, to counter impressions of "very early tech demo" for example, when in reality the engine is both stable and feature-rich.

**Comment by mercorii** [comment]
> There is no minetest brand and minetest is not a game, you will never have that radius :(

Just a quick jump to off-topic: I think there's a false dichotomy lurking in the background when people argue whether minetest should be an engine or a game. It's obviously neither: unity is an engine and minecraft is a game. Minetest is something else. Perhaps a browser?

> Minetest name certainly comes with certain connotations whether you want it to or not. As soon as it's out in the wild it starts to make impressions on people. When those impressions gains group recognition, a de facto brand is shaped. The question is whether we want to take control of the branding, to counter impressions of "very early tech demo" for example, when in reality the engine is both stable and feature-rich.

I very much agree with this, especially with the part about taking control. The fact that minetest resembles so much minecraft in both looks and name (a curse and a blessing), means that minecraft has a huge impact on minetest's narrative, whether people like it or not.

By creating a clear brand of its own, minetest could control the expectations of people, without being immediately compared to minecraft. For a FOSS product, "exploration" or "possibilities" could be a great building block for the brand.

>  the "story" would need to be a meta story about the engine more than a game itself

The "story" can be thought in a sense that the "story" of coca-cola is "enjoy" and for nike it's "just do it" - not as a story in something like Campbell's Hero's journey or a story in a game. Coke and nike have managed to push their whole story into a word or two, but those words, and ideas they create, are very deeply tied into their whole brand language. Coke is all about enjoying life, family, friends, christmas, you name it. Nike is all about doing things, and getting past one's own limits. Their stories offer a way to approach their products.

For minetest this could be perhaps "explore", or something similar. It could be included in the design language of all things minetest. It doesn't have to be the same interpretation of "explore" everywhere: it could be a wink at the player, asking "What cool stuff are you going to find today?" at one place, and in other place it could appear as a random (featured) mod recommendation. It could be all over the design, but in different incarnations.

The important thing with this kind of story is that it acts as a design guideline in itself. If a design in making can be seen from the perspective of exploration, it already fills the "explore" design guideline, and the design in making then resembles a bit more the rest of the brand's design.

It's one more tool for keeping the brand's identity unified.

**Comment by v-rob** [comment]
Oh c'mon, Minetest is perfect.  We have the perfect example of a UI in Firefox's PDF viewer:

![image](https://user-images.githubusercontent.com/31123645/81978284-25f13880-95e0-11ea-81e4-fc722ab80bb0.png)

Gray, bland, etc.  Perfect!  Of course, Windows 3.1 _is_ a strong contender.

---

On a more serious note, no one seems to have any idea of what the main theme should be.  We all agree that it _shouldn't_ be translucent gray boxes and gray gradients and black with [gasp] green textlists, but we don't know what it _should_ be like.

I don't have any ideas, but that seems like the logical first step to me.

**Comment by hecktest** [comment]
Since the currently selected subgame can change the main menu's background, why couldn't it also skin the entire GUI?

**Comment by rubenwardy** [comment]
that's the eventual plan - we need a good default for the engine, though

**Comment by Wuzzy2** [comment]
I think the only sensible path forward is to have NO default game. And the main menu needs to be designed around that assumption.

**Comment by hecktest** [comment]
Well, the only default is what's default in a fresh minetest.conf, other than that the engine loads what was loaded last. And that can load a skin for everything, including the settings and the server browser.
Is a pretty engine-wide fallback really needed? The current GUI is sufficient as a minimal fallback.

**Comment by Df458** [comment]
I think y'all are forgetting that the minetest client has some game-agnostic GUI--including the content browser and serverlist, which get quite a bit of use. We want games to skin their GUI for sure, but we also need a good default for the places that they can't reach.

**Comment by BruceMoustache** [comment]
What if make the possibility to community free customize minetest menu
As in minetest we have games, textures, mods I suggest to make a new thing maybe called "menus" which, like inventory managers completely changes the inventory GUI, they completely changes the minetest menu. And then, like the official game "minetest game", we can have the official menu "minetest menu".

> if we pass this idea, it means minetest is a game not just an engine and we should continue on that way.
 
So maybe we can fix this problem?
And plus gives the power to community makes awesome menus 😁

**Comment by Zughy** [comment]
so I guess I'm up to the challenge now. Also, beware that designing a GUI also means redesigning the whole main menu. I wanted to do it myself in Lua but yes, it'd be far better within the engine.
> Who are you?

The guy who made [this](https://lospec.com/palette-list/zughy-32), [this](https://content.minetest.net/packages/Zughy/soothing32/) and a lot of pixel art, even for a living. I'd love to work together with a few other semi/professional artists, if there are some and they'd like to join. Also, if some core dev has any idea, this is the best time to share it. As a pixel artist, I'd stick with my cup of tea.

Anyhow, I'll do my homework with a few sketches and then I'll come back here with some mock-up (coding it is not up to me :D). LET'S DO THIS PEOPLE

**Comment by BruceMustache** [comment]
> it's done using mods
do you know some?

**Comment by IFRFSX** [comment]
```We already have theming, it's done using mods. Not all elements are supported yet, as it's still in development```

i suggest put this to minetest program.

**Comment by Pevernow** [comment]
Look at this web page.
(This is a question that some Chinese are talking about minetest)
(The title is "Why can't minetest replace minecraft?")
The words in the red box mean 

“The main reason is that the details of "minetest" are not polished in place, revealing a serious sense of cheapness. A comparison shows that "minetest" is not as good as "minecraft" in terms of material, animation, UI and operation feel.”

![image](https://user-images.githubusercontent.com/29888010/95870623-498ef980-0d9f-11eb-85c2-f270da52f242.png)

A better GUI and good textures can make minetest more popular all over the world.

**Comment by v-rob** [comment]
Question: So, I know that this GUI design definitely focuses on the main menu, but what about all other GUIs?  Are we planning anything to apply to _all_ GUIs (not the main menu), or are we going to leave them as gray gradients by default?

**Comment by rubenwardy** [comment]
The in-game menus are mostly customisable using formspec prepends already iirc. The other modals in the main menu should all be themed according to the design guidelines

**Comment by cosoc** [comment]
ui的确丑陋,如果需要经费，我可以提供资金援助和设计技术支持！

**Comment by numberZero** [comment]
> Currently i find it an unpleasant 'design shock' when theming changes when switching between main menu tabs, and this is unnecessary, it certainly should never have happened when editing a setting.

There are exactly 2 solutions: either style the whole main menu with the currently selected game, or style it with a builtin theme. For me it’s highly unpleasant when clicking on some button changes *both* theme and content (world list).

> 'All content is provided by the game' is how MT operates.

It does, in singleplayer. But in multiplayer the content is provided by the server (which takes it from the game and mods but that doesn’t matter here). Until one chooses a server, there is no way to choose a “correct” theme. Moreover, there may be no game themes installed at all as games aren’t necessary to play on servers!

> unity is an engine and minecraft is a game. Minetest is something else. Perhaps a browser?

A good point. Finally. MT is **not** an engine. And browser doesn’t change the theme when one opens a page, yet allows *arbitrary* theme on the page itself.

So either MT becomes an engine, in the sense that one wouldn’t be able to launch NodeCore and connect to a Multicraft server, or it remains a browser. In the latter case it shouldn’t adapt it look to any particular game. Even moreso, the concept of “selected game” may be removed at all, becoming an icon in the world list instead.

> What if make the possibility to community freely customize minetest menu

Sounds very Minetestish. Many apps have several themes (usually differing in colors only), some have customizable colors, but only a few allow real customization.

**Comment by snowyu** [comment]
I think MT should be an engine first, then extends to a "browser". You can build your "browser" (like Chrome and Chromium).
And This would turn MT into the cornerstone of the realization of the [metaverse](https://en.wikipedia.org/wiki/Metaverse).

MT engine will mainly focus on the following aspects:

* Data
  * Environment
    * Air(component, poisonous), Air pressure, Temperature, Humidity, Gravity...
    * Land: Plane, Spherical
    * Liquid: (maybe only need the material melting point table)
  * Thing
    * Material(Non-living)
    * Object
      * Plant
      * Animal: Player: Human&Computer(NPC)
* Data Security
  * Passwordless signup/login Schema and Data Encryption via OpenPGP
  * Transport to another server seamlessly
* Render
  * Terrain, 3D Model, Particle Effect
  * Switch-able between Pixel style(Old graphics card or old machine) and Realistic style
* Pluggable GUI Engine
* Pluggable Script Engine
* Pluggable Network(Comunication) Engine

**Comment by TuringZauber** [comment]
I would propose taking the layout and style from minecraft.net. It's a voxel game similar to Minetest and the UI proved to be usable for the target audience. I feel strongly that we should take what's best and make it better.

We should hire a professional ux designer to improve the <del>stolen</del> inspired assets.
https://blog.codinghorror.com/this-is-what-happens-when-you-let-developers-create-ui/
This project is dear to me. You can ping me for funding in regards to hiring a ux designer.

**Comment by TuringZauber** [comment]
Inspiration

https://www.reddit.com/r/Minecraft/comments/le2tnp/a_concept_i_made_for_a_modern_cooler_minecraft/

![image](https://user-images.githubusercontent.com/6533815/141674673-5a2532dd-026b-454e-ac7c-50bbe025233d.png)

![image](https://user-images.githubusercontent.com/6533815/141674639-26e5838a-ebde-474f-9c13-bee8d226c354.png)

**Comment by TuringZauber** [comment]
I completely agree with @Wuzzy2.

So who's responsible?
Please elect **some Person** to be responsible for solving this issue.

If nobody is willing to, assign this issue to me

**Comment by Rick-W-Storm** [comment]
Is it done thought? What's the decision?

**Comment by rubenwardy** [comment]
Some people are putting together a mainmenu/engine proposal, there's likely to be a RfC on that soon

And for this issue, I don't think that it's really needed. Different games can have their own user interfaces as it makes sense
