### ISSUE TITLE
Can't teleport attached player

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9823]
##### Minetest version
```
5.2.0
```

##### Summary
You can't teleport players that are attached to an object (like a boat or minecart).

##### Steps to reproduce
1. Attach yourself to any object (like a boat in Minetest Game)
2. `/teleport 1 2 3`

EXPECTED: You teleport to (1 2 3).
ACTUAL: Nothing happens.

This is also the case when you try to teleport not yourselves, but another player.

**Comment by rubenwardy** [comment]
This sounds like a feature, I guess

Perhaps teleport should attempt to detach, but it would need to allow entities to veto this - perhaps in on_detach

**Comment by Wuzzy2** [comment]
This is an usability desater then.

* You type `/teleport 1 2 3`
* Nothing happens
* You rage-quit because you think Minetest is broken

If this is intended behavior, how about adding a warning in chat then?

**Comment by KaylebJay** [comment]
I definitely don't think this is a feature. I have gotten stuck in things and the only way was to force deattach from them in some cases, or hotfix the code to deattach me :D A command to deattach (like teleport) would be much better.
This also causes some problems. For example, sometimes players will get teleported while on a horse or train and will stay on the horse or train (like it should be). Otherwise they would lose their horse. The Towercrane also has this 'feature', which is incredibly useful.
So IMO, it would be better to have a deattach command rather than teleport doing it. It would be incredibly useful for servers where some players don't know how to interact properly with attachable objects.

**Comment by Wuzzy2** [comment]
PR that adds an error message when teleportation failed: #9824.
Not a true fix, but a start.

Adding a `/detach` command sounds quite useful, but it should be reserved to privileged players only (to cleanup buggy situations basically) because a game's integrity might depend on players being attached to something at all times, and letting everyone detach at will might break gameplay. But this is off-topic.

**Comment by LoneWolfHT** [comment]
:+1: for a `-f` and `--force` option with `/teleport`

**Comment by rubenwardy** [comment]
Attaching a player to an object is a common way to prevent a player from moving, so any option to detach must be vetoable by the entity

**Comment by SmallJoker** [comment]
By attaching the full movement control is passed to  the parent entity. It would be wrong to allow plain `set_pos()` calls for attached players.

What I'd prefer: `/teleport` adjustments to detach players when forced
What's also okay: `ObjectRef:set_pos(pos[, force])`

**Comment by paramat** [comment]
> Attaching a player to an object is a common way to prevent a player from moving,

^ Critical point.
So i disagree that teleporting should detach a player and then teleport, unless that can be restricted.
Likewise a 'detach' command must be restrictable.
But i cannot see much need for either of the above.
Not teleporting when attached seems reasonable.
I cannot see problems with detaching from entities, if players get stuck attached to something that is either bad mod code or bad mod documentation, which should just be fixed.

For this issue i think #9824 is the correct approach and is good enough for now.

**Comment by LoneWolfHT** [comment]
Shouldn't mods that attach a player to prevent them from moving use on_detach_child() to reattach them?

**Comment by paramat** [comment]
#9824 is merged.
Closing this as attached players should not be able to teleport to escape attachment, and the issue author has not made any other request. We could possibly reopen this if the author has another request.

**Comment by FeXoR-o-Illuria** [comment]
@paramat said: "[...] attached players should not be able to teleport to escape attachment."
He could just pick up the boat (as long as we are talking about the Mintest game and it's mods - or what other things a player can get attached to in the scope of this repository?)

@paramat said: "if players get stuck attached to something that is either bad mod code or uninformed players, which should just be fixed."
This sounds like building a very simple trap from just 4 random blocks, a water source and, say, a diamond block that can traps "uninformed" players that don't happen to have a diamond pick with them (or the means to craft it) indefinitely is OK.
(Trap setup, on plain ground:
1) Place 4 blocks (say dirt) on the ground surrounding a 1 block space where the water source is fo go, place the water source in the middle.
2) Place 2 more blocks on top of one of the already placed blocks (they can be removed later) and put a Diamond block at the top block above the water source.
3) Place a boat on the water source
(4) Optionally place a luring sign at the diamond saying: "Whoever manages to mount this boat here will get the diamond block!")
(For new players even an obsidian glass or cactus block will do.)
Or "bad mod" ... which would imply this is to be fixed here since it's part of this mod ;)

As I understood it the boat is meant to be a (faster) way of transportation especially over water.
But I may be wrong :D

**Comment by paramat** [comment]
> He could just pick up the boat

The point is, some servers attach a player to a special entity to confine them or control their movement, this is used to prevent clientside cheating, so is essential.
Even if an attachment trap is possible, the above takes priority.
