### ISSUE TITLE
Lua: Bit Manipulation

### ISSUE THREAD

**Issue by Lejo1** [minetest/minetest#9843]
## Problem

For especially cryptographic functions you either need a library(Also for CSM) which are hard to add and more like a insecure dirty workaround(I just try to prevent them) or you need a pure Lua Library but they normally use the bit operators of 5.3 or a library
[PS: Found one Library which works but only AES](https://github.com/TylerRHoyer/Lua_AES)

## Solutions

Either adding the 5.3 operators which is some kind of impossible with LuaJit.
Or adding a bit library like the one of luaJit.

Other solutions welcome!

**Comment by SmallJoker** [comment]
See also: #3028  and LuaJIT bitops.

**Comment by Lejo1** [comment]
What about allowing this bit library without minetest.request_insecure_environment()?
So something just adding a bit.xor, ...?

**Comment by sfan5** [comment]
There is no reason it would need to be in the insecure environment.
Minetest could add a bit library to the normal environment (for both Lua and LuaJIT) just fine.

**Comment by Lejo1** [comment]
Yeah, just a easy possibility to access the library.

**Comment by sorcerykid** [comment]
My Bitwise Operations mod is very efficient works out of the box. I use it in several of my other mods for cryptography, checksums, etc.

https://github.com/sorcerykid/bitwise

**Comment by Lejo1** [comment]
@sorcerykid 
Thanks! Will have a look at it!

**Comment by sorcerykid** [comment]
Np. If you have any questions feel free to ask in the forum thread or here. For guidance, you can see some examples of working implementation in my Simple Cipher mod.

**Comment by Lejo1** [comment]
The cipher encryption is symmetric, isn't it?
You wrote cipher.generate_key generates a public/private key pair.

I'm searching for a safe asymmetric algorithm. But didn't found any without some kind of library needed.

**Comment by sorcerykid** [comment]
Yes Simple Cipher is a symmetric encryption library, since it's not intended for secure data exchange but rather secure data storage. The cipher.generate_key function shouldn't be confused with public key cryptography.  The key in this case is generated from hashes of the player name (public key) and pass phrase known only by the administrator (private key). For asymmetric encryption, you'll definitely need a library, as rolling your own is not advisable. You can probably find some pure-Lua implementations that could be adapted to use my bitwise mod just by aliasing the appropriate bit functions at the top of the script.

**Comment by Lejo1** [comment]
I tried it #9847

**Comment by rubenwardy** [comment]
Implemented
