### ISSUE TITLE
Investigate minetest.get_translated_string() behavior

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#9845]
##### Summary
This serves as a reminder to check the following:
1. Does it return the English string if no translation for the given lang_code?
2. Should it strip the translation escapes in some situations (such as the above)?
3. What does it return if `lang_code == ""`?

relevant IRC discussion: http://irc.minetest.net/minetest/2020-05-10#i_5683609

**Comment by Wuzzy2** [comment]
> Does it return the English string if no translation for the given lang_code?

Yes. :-)

> Should it strip the translation escapes in some situations (such as the above)?

Good question! :-/

I don't even know if the returned string contains translation escapes. (Off topic: It is kind of tricky to debug/analyze those escape code. What's the easiest way to print the raw string, for debugging purposes of course?)

> What does it return if lang_code == ""?

The source string (English). :-)

---

How I tested the first question:

- Played in German with `luacmd` in MTG -dev
- `/lua print(minetest.get_translated_string("de", minetest.translate("default", "Savanna Dirt")))`
→ Returned “Savanna Dirt” :-)

How I tested the third question:

- Played in German with `luacmd` in MTG -dev
- `/lua print(minetest.get_translated_string("", minetest.translate("default", "Savanna Dirt")))`
→ Returned “Savanna Dirt” :-)

(The string “Savanna Dirt” has been chosen because it is currently not translated in German)

**Comment by Wuzzy2** [comment]
> Should it strip the translation escapes in some situations (such as the above)?

Hmmmm. I think yes. Thinking about this, I would say that the returned string should never have translation escapes. The reason is that the output must ONLY be used on the server-side, which also the `lua_api.txt` tells me. On the other hand, translation escapes are meant only for clients. So the translation escapes are completely pointless for the server.
Also, the `lua_api.txt` explicitly cites sorting as an use case. Still having translation escapes in the output would be quite annoying for sorting.

**Comment by rubenwardy** [comment]
To summarise my views:

The behaviour should be exactly the same as on the client. The `lang_code` from get_player_information() really should return `en` when the language is en.

> Does it return the English string if no translation for the given lang_code?

It should return English

> Should it strip the translation escapes in some situations (such as the above)?

Yes, because this is required to return English

> What does it return if lang_code == ""?

Like any other invalid language code - return English

**Comment by Wuzzy2** [comment]
> The behaviour should be exactly the same as on the client.

But this implies returning translation escapes in some circumstances. This makes sorting annoying. Maybe the best solution is to add a separate function to strip translation escapes.

> The lang_code from get_player_information() really should return en when the language is en, for consistency. The value "" in the language settings means take the system language, it does not mean en.

Nice catch! I agree.

**Comment by rubenwardy** [comment]
> But this implies returning translation escapes in some circumstances. This makes sorting annoying. Maybe the best solution is to add a separate function to strip translation escapes

When does the client ever do this? I've never seen it happen. If the locale isn't found, English is shown

**Comment by pyrollo** [comment]
I think :
* lang_code = "" is irrelevant as `get_translated_string` is suppose to get translation for a player (and player always has a specified language).
* It should work with English as any other language.

**Comment by Wuzzy2** [comment]
> > But this implies returning translation escapes in some circumstances. This makes sorting annoying
>
> When does the client ever do this? I've never seen it happen. If the locale isn't found, English is shown

I thought the client receives this translation escapes in order to do this translation work … I thought these escapes are still there when the string is being translated. I might be wrong or not. I don't really know.

Anyway, this doesn't really matter. `minetest.get_translated_string` should not return translation escapes, no matter how the current client translation system works.

Also, everyone: Please note that this is only 1/3 discussion issue (question 2). The other 2/3 are about hard, cold facts (basically about if `minetest.get_translated_string()` works or not).
And currently, the answer to questions 1 and 3 match my expectations.

**Comment by rubenwardy** [comment]
> I thought the client receives this translation escapes in order to do this translation work … I thought these escapes are still there when the string is being translated. I might be wrong or not. I don't really know.

The client receives the escapes, but it resolves them. By "the same as the client", I meant the same way that the client resolves translations when showing in chat

**Comment by Wuzzy2** [comment]
Still waiting to see what @sfan5 thinks about this.

**Comment by sfan5** [comment]
`get_translated_string` should never return a string with translation escapes inside, regardless whether a translation was found or not.

**Comment by rubenwardy** [comment]
The current behaviour of get_translated_string already matches my expectations. I suspect that FreeLikeGNU had a mod issue somewhere.

Test code:

```lua
local S = minetest.get_translator("trans")

minetest.after(2, function()
    local str = S("Hello @1", "World")
    minetest.log("error", minetest.get_translated_string("", str))
    minetest.log("error", minetest.get_translated_string("en", str))
    minetest.log("error", minetest.get_translated_string("fr", str))
    minetest.log("error", minetest.get_translated_string("unknown", str))
end)
```

Output:

```
Hello World
Hello World
Bonjour World
Hello World
```

**Comment by Wuzzy2** [comment]
Looks good to me, too.

**Comment by sirrobzeroone** [comment]
Just wanted to thank you all for going to the extra work of adding and testing this functionality. Being able to replicate this server side saved me some significant headaches.
