### ISSUE TITLE
Replace SAO with ECS

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#9848]
## Problem

OOP is not the best paradigm for game development. Because of it's nature it may cause performance issues, especially cache misses in the CPU.

Here is an article about this topic
http://gamesfromwithin.com/data-oriented-design

## Solutions

I suggest to use an ECS design (entity component system). Because rewriting the current code is nearly impossible I suggest to implement a secondary entity system that replaces the current one if it is finished.

I'm pretty sure this will help to boost the performance of Minetest, especially on multiplayer servers. An example for an ECS for C++ is https://github.com/skypjack/entt

**Comment by sfan5** [comment]
A better explanation of ECS: https://en.wikipedia.org/wiki/Entity_component_system#Characteristics

> OOP is not the best paradigm for game development. Because of it's nature it may cause performance issues, especially cache misses in the CPU.

The problem you are stating is pretty vague. I don't think it's easy measure how the entity system design influences performance and I think the bottleneck is somewhere else.

Minetest only has two SAO types: [`PlayerSAO`](https://github.com/minetest/minetest/blob/master/src/server/player_sao.cpp) and [`LuaEntitySAO`](https://github.com/minetest/minetest/blob/master/src/server/luaentity_sao.cpp). When `step()` is called these mostly always do the same, there are is no "accessing other objects further down in the tree" or "cascading, totally different operations at each object" as the article mentions.

As for the advantages the article mentions, parallelization for example is not easy possible even if Minetest used ECS.
Suppose you have a collision detection component, it needs access to the environment (map + objects), which can only be locked once since it lacks a reader-writer locking mechanism. So that's not something you can do in parallel.
I guess you could parallelize rotation calculation but does that really matter?

If you look at what an entity does you also end up at possibly the slowest part, calling `on_step()` in Lua. Aside from not being parallelize-able (at all), it also can't be changed to fit the ECS design better.

> Because rewriting the current code is nearly impossible I suggest [...]

I wouldn't be so sure of that. Rearchitecting perhaps 2000 LOC isn't impossible at all.

**Comment by nerzhul** [comment]
Mangos unofficial WoW servers use OOP massively, and runs thousands of NPCs & players at the same time without problem. Our problem is really not the less than 1 hundred SAO at the same time on a MT server

**Comment by MarkuBu** [comment]
Well, yeah, this is broken by design and can't be fixed I think
