### ISSUE TITLE
Distinct priorities of emerge requests

### ISSUE THREAD

**Issue by Hume2** [minetest/minetest#9849]
## Problem
When there are too many emerge requests, the "first come - first serve" mechanism is no longer sustainable. These things happen:
- There are many requests to emerge mapblocks which are far from a player but then another player wants to emerge mapblocks right in front of him. However, these far mapblocks have to be emerged first because they were enqueued first.
- There are mapblocks which were requested a long time ago but the player who requested them already got too far so he no longer needs them.
- When a player goes offline, his requests still stay there.

## Solutions

1. Before an emerge request is processed, it should be checked if they are still relevant for the player.
2. Emerging mapblocks which are close to the player should have a higher priority than the farther ones.

## Alternatives

Another sollution might be dropping the queue once over a time or changing the load map radius dynamically.

## Additional context

It might solve performance issues on many servers. https://forum.minetest.net/viewtopic.php?f=6&t=24485

**Comment by sfan5** [comment]
Have you debugged to determine if the emerge queue really is too full or is this a guess?

Also by checking the code I can confirm that `get_voxel_manip` bypasses the emerge queue so map loading instantly when using it is not a surprise.

**Comment by Hume2** [comment]
It is my guess. I tried implementing that feature at Tunnelers' Abyss to compare the results. So far, it looks like it really improves the performance.

**Comment by lhofhansl** [comment]
@Hume2 Do you have a patch or PR to look at?

**Comment by sfan5** [comment]
> There are many requests to emerge mapblocks which are far from a player but then another player wants to emerge mapblocks right in front of him. However, these far mapblocks have to be emerged first because they were enqueued first.

This is correct but shouldn't be a big problem in practice since the emerges *should* complete within less than 5s. Whether this works out remains to be seen.

> There are mapblocks which were requested a long time ago but the player who requested them already got too far so he no longer needs them.

Also true, see above.

> When a player goes offline, his requests still stay there.

This could be somewhat easily since the code already tracks the player that requested a block.

Generally, the problems you mentioned only occur if you have a very very slow mapgen (or a bug) because if the queue clears out within 1-10s none of the problems are apparent to users.

<hr />

Either way I've created a branch with code that tracks pending emerges in the queue: https://github.com/sfan5/minetest/tree/emerge_debug
It will print the contents of the queue to stdout(!) every 30 seconds (unless the queue is empty for a longer time). It also logs when enqueues are rejected because of limits, which is normal and happens during normal use.

@gpcf if you still have these issues I would appreciate if you could test this too

**Comment by Hume2** [comment]
@lhofhansl You can see these two commits:
[](https://gitlab.com/h2mm/minetest/-/commit/ce864a9e4cf5aecb736470b3c7560c672aa5635f)
[](https://gitlab.com/h2mm/minetest/-/commit/0f00e6ca6e641e683039b7cdcca5a40a9e288333)

@sfan5 My experiments show that the slow loading happens even when the people are loading only the map which was generated before. For some reason, I sometimes have to wait for tens of seconds or minutes to get all the wanted mapblocks, even though they are all generated.

**Comment by sfan5** [comment]
> My experiments show that the slow loading happens even when the people are loading only the map which was generated before

That's good to know but please test the situation with my branch and watch the log output.

**Comment by busybody42** [comment]
This is kinda offtopic, and aimed at hume, but...
We need you back on the Supertux team, hume!
You're making great work, no matter what game it is,
but we need some assistance so we can ALSO make great work!

**Comment by Hume2** [comment]
I think, I figured out the issue. The requests come faster than they are completed so the queue grows until it reaches its maximum. After that, no more requests are being accepted until a request is completed. And then there are multiple candidates so only the first few pass and the rest of them are rejected. It is a game of chance whether another request is accepted or not.

Maybe the queue should be passed once over a time and the least important requests should be trashed when the queue is nearly full.

**Comment by sfan5** [comment]
The queue should never be full for an extended period of time, clearing it would just hide the problem.
Do you have log output from reproducing the issue with the branch I linked?

**Comment by Hume2** [comment]
Yes, I have. It says just that the request was rejected because the queue is full a lot of times in a row.

**Comment by sfan5** [comment]
As I've said:
> It also logs when enqueues are rejected because of limits, which is normal and happens during normal use.

The full output of the _contents_ of the emerge queue would be much more useful to determine the cause.

**Comment by Hume2** [comment]
[](https://www.dropbox.com/s/ffr9swtgdrkossa/stdout.7z?dl=0)

**Comment by sfan5** [comment]
Thanks.
Your description [here](https://github.com/minetest/minetest/issues/9849#issuecomment-631402436) is accurate but I don't think clearing the queue or prioritising will properly solve this issue.
When blocks are sometimes stuck in the queue for more than 30 seconds then you should rather look at what is making block loading be so slow, e.g.:
* LBMs that take a lot of time
* slow disk
* slowness caused by the database
* in case the mapgen is involved: slow `on_generated` callbacks
