### ISSUE TITLE
On collide for entities without collide_with_objects 

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#9873]
collide_with_objects is great, but can we still have access to the collision detection if the object enters another object's collisionbox? would be useful for things like arrows and such

**Comment by LoneWolfHT** [comment]
Pretty sure we already have this https://github.com/minetest/minetest/pull/9668

**Comment by tenplus1** [comment]
This feature already exists: https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L6637

**Comment by TheTermos** [comment]
Not sure if I understand correctly, but entities with collide_with_objects=false are entirely unaware of other objects.
This suggestion would require different processing, such as collision detection with objects is performed for them, but its effects not applied.

The problem is that would negatively impact entities that don't need it, particles probably the worst, so, a new entity parameter would be required, something like collide_with_objects_but_not_really.

If I was trying to implement arrows and such, I'd probably just try making them collide with objects normally and attach them to the other object upon impact, or set_pos & set_velocity if it's meant to pass through.

**Comment by sorcerykid** [comment]
This doesn't make sense. If an object is not supposed to collide with objects, then there is no collision detection and hence no reporting of a collision.

**Comment by oilboi** [comment]
Then how about "soft" collision detection like I have implemented into the mobs in Crafter? Like two positive magnets repelling

**Comment by sorcerykid** [comment]
I'm not sure if you are talking about collisions or physics. Elasticity is not collision detection. There is already an issue discussion about resistive forces in #9520.

**Comment by SmallJoker** [comment]
Callbacks are triggered by server "events", such as collision or new players. Intersecting has no special effect.
I think `Raycast` is more helpful to you in this case.

**Comment by paramat** [comment]
Seems a lot of work for something unimportant, it also makes no sense for objects that do not collide, see above comments. Does not seem worth it to me :-1: No support from core devs either.
