### ISSUE TITLE
Weird falling node collision behavior

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#9883]
##### Minetest version
5.3.0-dev c1ce4be756e2554051a27f244303377c0a7d69a6

##### Summary
When large stacks of falling nodes fall, the entities at the top rest for seconds and only slowly transform into nodes. 
<b>VIDEO: https://0x0.st/iLhY.mp4</b>

Falling nodes instantly turn solid on collision, so this must be an issue with collision detection.
Reverting 6ef7ad09bbed9176d0d15f53b5cb14ef6e18a3b2 fixes this issue. (@TheTermos)

**Comment by TheTermos** [comment]
I'll have to look at the falling code.

> Falling nodes instantly turn solid on collision, so this must be an issue with collision detection.

If I remember, these entities don't collide with objects, yet they don't seem to fall through each other.
If there's no velocity, there are no collisions, my first guess is whatever keeps them from falling/moving, keeps them from colliding as well.

**Comment by sfan5** [comment]
> these entities don't collide with objects,

they do

**Comment by TheTermos** [comment]
Floating point precision again. these entities are exactly 1.0 n tall, and due to precision error the taller the column the more the error adds up and the more misaligned with nodes they get, so collisions takes a while to propagate as entities turn nodes.

It would be the best solution if the following was possible in falling.lua at 47
		_collisionbox = {-0.5, **-0.49**, -0.5, 0.5, 0.5, 0.5},_

I'm going to try making a PR increasing precision to 64 after new collision settles in.

By the way, can we somehow combat falling nodes briefly turning black?

**Comment by sfan5** [comment]
> collisionbox = {-0.5, **-0.49**, -0.5, 0.5, 0.5, 0.5},

This would work for the builtin falling entity, but this is not a solution you can just expect other mods to implement.

> I'm going to try making a PR increasing precision to 64 after new collision settles in.

Would this fix the issue?
This is what confused me in general, the changes in #9764 were supposed to prevent errors due to floating point precision, yet they <i>caused</i> this issue.

> By the way, can we somehow combat falling nodes briefly turning black?

In this case the entities spawn before the nodes are removed (for the client), can probably be fixed.

**Comment by TheTermos** [comment]
> This would work for the builtin falling entity, but this is not a solution you can just expect other mods to implement.

Are mods likely to implement multiple entities of exactly 1.0 size collide in a row and turn into nodes one by one?

I'm going to investigate it further, but with this low precision we're mostly in the trade off area.

> Would this fix the issue?
> This is what confused me in general, the changes in #9764 were supposed to prevent errors due to floating point precision, yet they caused this issue.

It would, with some further modifications to collision detection.
#9764 is meant to improve collision success rate, with 32 bits it's impossible to perfect, because there are just too little trustworthy digits to work with. See the example in the description of #9346.

**Comment by TheTermos** [comment]
Hold on, done some additional debug, the results suggest this issue might have nothing to do with collision detection.

**Comment by TheTermos** [comment]
**The test:**

In falling.lua:
debug 'collision object' after 278 `if info.type == "object" then`
debug 'collision node' after 282 `elseif info.axis == "y" then`
debug 'remove' after 345 `self.object:remove()`

In game:
Create a stack of 3 falling nodes and dig the bottom one.

**Example result:**
```
collision object
collision node
remove
collision object
collision object
collision object
collision object
collision node
remove
```
There are only two objects, so following the first remove there should be only one last object left with no other objects to collide with, yet it still keeps colliding with an object for a few steps.
Looks like maybe objects aren't being removed immediately the very next step after remove() and linger on for a few steps.

The recent collision detection modification might have exposed this problem, but probably isn't the immediate cause.

**Comment by sfan5** [comment]
Yep, there's a missing check for `obj->isGone()` here:
https://github.com/minetest/minetest/blob/11723cffe011e99c1092388958fb1a047ab1c09c/src/collision.cpp#L400
