### ISSUE TITLE
Move "Discussion" issues in the forum

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#9908]
## Problem

There is a forum for discussing: scattering discussions in different places doesn't help who doesn't want to lag behind. Also, that's what forums are made for

## Solutions

Create/use a forum section for them and close the current issues with the "Discussion" label. 966 issues is a very high number, even 20 issues less would help

**Comment by KaylebJay** [comment]
Another issue :)) 
_someone had to say this, sorry_ :D

**Comment by paramat** [comment]
Most issues opened here whose labels include the 'discussion' label actually belong here, as they contain content, or other content, that belongs here. So we cannot remove every issue whose labels include the 'discussion' label, that is obviously an ignorant way to consider removal that ignores the actual issue content.
:-1: 

We might be able to move some, but which ones does not depend on the presence of the 'discussion' label.
We should obviously judge each issue independently. If it is a discussion that should be elsewhere then we can ask for it to be moved to the forum. In fact, we probably already do this, although it is ok to remind us to do this.

To make this issue useful, please list the issues that should be considered for removal.

**Comment by rubenwardy** [comment]
Discussion basically just means "request for comments" here

**Comment by mercorii** [comment]
There's a new [discussions](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions) system coming to github in the near(ish) future. It is currently in limited beta, but according to the link, it should be coming to public beta soon for public repositories.

One of the repositories that is part of the limited beta is [zeit/next.js](https://github.com/zeit/next.js/discussions), in case someone wants to take a look at it now.

It might be a good place to hold some of the discussion that doesn't fit exactly under issues.

**Comment by paramat** [comment]
> To make this issue useful, please list the issues that should be considered for removal.

Ignore that, it is best to comment in the issue itself if anyone feels the issue should be elsewhere.

I looked through all issues that contain the 'discussion' label. All of them are valid and belong here, as i suspected, usually because they have other labels that mean they belong here.
If an issue appears that should be elsewhere we already state this and close it.
Keep in mind that core devs can very easily miss a forum thread, any important development discussion should be here.
Development involves 'discussion', it makes no sense to claim that 'discussion' does not belong here.
The suggestion in the first post is crazy, super-crude and obviously unacceptable.
