### ISSUE TITLE
Segfault in GenericCAO::setNodeLight for upright_sprite entities

### ISSUE THREAD

**Issue by EmeraldMT** [minetest/minetest#9916]
##### Minetest version

```
5.2.0 from Ubuntu PPA
```

##### OS / Hardware

Operating system: Xubuntu 18.04
CPU: Intel i5-2400

GPU model:
OpenGL version:

##### Summary

Client segfaults happen most frequently during gameplay on new NodeCore server.
GDB backtrace: https://pastebin.com/zYdRtVEM

##### Steps to reproduce

Server is nodecore.mine.nu:33333
Other players report crashing as well. Warr suggests that doing the following is the most likely way to cause the crash:
(1) have some items and some empty slots in your inventory
(2) be in a darkish cave
(3) scroll your items rapidly while walking around

**Comment by ClobberXD** [comment]
I can reproduce this, but only with shaders enabled (enabling basic shaders suffices). Backtrace points to `GenericCAO::setNodeLight` for me too.

I suspect the issue is within the `if (m_enable_shaders)` block here:

https://github.com/minetest/minetest/blob/e79bc40c0a5312baf4e8c3e33048d50b41b4a2ff/src/client/content_cao.cpp#L824-L862

**Comment by Kimapr** [comment]
catchsegv (memory map not included):
https://paste.debian.net/1148394/

**Comment by Kimapr** [comment]
another one
https://paste.debian.net/1148395/

**Comment by Warr1024** [comment]
Since I can't leave NodeCore in an unplayable state, I've added a workaround to the game.

To reproduce this issue, use NodeCore commit https://gitlab.com/sztest/nodecore/-/commit/c2fab4b12d42363f78219a7724498f3d28157f07
