### ISSUE TITLE
Change registration type checking to show a warning rather than throw an error

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#9950]
https://forum.minetest.net/viewtopic.php?f=6&t=24817

**Comment by Wuzzy2** [comment]
But why? If I understand correctly, `inventory_image` can only be a string, because it only accepts a single texture. Why allowing a table?

IMO anything but a string or `nil` in `inventory_image` is an error, and the modder is to blame. Minetest shouldn't try to guess what the modder could have possibly meant.

I'm afraid you're about to create a BugFactory.

**Comment by ClobberXD** [comment]
I understand why this is being requested, but I'd personally really prefer to have the current behaviour - mods should really be following the correct types, and throwing errors ensures that these mistakes are caught more easily. I hope this can at least be re-added in the next major version.

**Comment by rubenwardy** [comment]
Worth noting that there are some false positives. In 5.2.0, you're able to use a number as the text of a HUD text element. In 5.3.0-dev, it throws an error. It's perfectly valid for a number to be used, Lua even implicitly converts [it in getstring](https://www.lua.org/manual/2.4/node15.html)
