### ISSUE TITLE
Black patches on models, bad shading

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#9985]
_5.2.0 release_

The newly added vertex lighting completely breaks when a model doesn't have normals. Models are covered in random black patches, as if some junk data was being used instead.
![patches](https://user-images.githubusercontent.com/42101236/83547189-22c3db00-a502-11ea-8a2e-7a455f3150a1.png)
![checkers](https://user-images.githubusercontent.com/42101236/83547193-248d9e80-a502-11ea-90c1-7068460ae411.png)

I made all my art with the previous lack of shading in mind, stripping the normals to save space, and utilizing an optimal topology that doesn't shade well. Cheap vertex lighting is going to make it look like 90s garbage. Where's the object property that toggles it?

**Comment by SmallJoker** [comment]
Does #9969 fix this?

**Comment by sfan5** [comment]
Preceding discussion in the PR that introduced object shading: https://github.com/minetest/minetest/pull/9374#issuecomment-587086837

**Comment by hecktest** [comment]
> 
> 
> Does #9969 fix this?

It does not.
The shading should probably be off by default. minetest_game can enable it for players. That way it won't be a breaking change.

**Comment by paramat** [comment]
This is a rather nasty breakage, i would like to see this resolved before 5.3.0.
Not using normals was and is a valid choice, sometimes for good reason, not a case of 'broken models' as claimed in the PR.
The PR has plenty of complaints about this.

**Comment by sfan5** [comment]
> > Does #9969 fix this?
> 
> It does not.

It should though. Do you have a testcase so I can reproduce this myself?

**Comment by appgurueu** [comment]
> > > Does #9969 fix this?
> > 
> > 
> > It does not.
> 
> It should though. Do you have a testcase so I can reproduce this myself?

Yeah, it should. By glancing at the code I can see that it **explicitly** checks for the normals being 0 and disables shading for such normals.

**Comment by Moth-Tolias** [comment]
off topic but i love the aesthetic of that second picture.

**Comment by hecktest** [comment]
Try using this mesh, it should have the black patches. Also, restart the client a few times; the patches are completely random, and every now and then the mesh will not have them.
[icocage.zip](https://github.com/minetest/minetest/files/4725334/icocage.zip)

**Comment by dcbrwn** [comment]
Disabling this per-object sounds like good idea. Any hints how to implement this?

**Comment by dcbrwn** [comment]
@appgurueu thing is that it does that in shader per-vertex. so maybe that's the issue.

I can look into this on weekend.

**Comment by hecktest** [comment]
ObjectRef property, something like "shaded". Ideally off by default, because a lot of existing textures already have shading painted into them.

And how does this shading feature interact with objectref's "glow"? I don't see a reference to that in the shader. Glow should be flat regardless of shading, since it simulates emission.

**Comment by dcbrwn** [comment]
I meant hints on how to add properties to lua object. I bet it's a bit of a hassle. And then there will be a pleasure of passing it to the shader.

**Comment by hecktest** [comment]
Last time I checked, all you had to do was add the relevant property to object_properties.cpp/h, then do the lua part in script/common/c_content.cpp

**Comment by sfan5** [comment]
> Try using this mesh, it should have the black patches. Also, restart the client a few times; the patches are completely random, and every now and then the mesh will not have them.

I can confirm even with 9969 applied. The random nature of this issue could mean that the normals are just junk data since they aren't defined.

**Comment by appgurueu** [comment]
Junk normals confirmed:

![Screenshot](https://user-images.githubusercontent.com/34514239/83908208-fd83d680-a766-11ea-8701-4d05da19dd36.png)

(model displayed in-game using my second rendering stage)

**Comment by dcbrwn** [comment]
More weirdness: I've added node with "mesh" drawtype, and for normals are calculated!

![изображение](https://user-images.githubusercontent.com/12214069/83943048-92d3a900-a801-11ea-83ed-b18f326b1103.png)

**Comment by sfan5** [comment]
Although it is not possible to turn off shading, I believe this issue has been sufficiently fixed at least for the 5.3 release.
Objections?

**Comment by hecktest** [comment]
I hate the forced lambert shading in either case. It's horrible. Give me custom shaders or an option to turn it off and I'll shut up about it.

**Comment by paramat** [comment]
So, #10000 forces shading when there are broken normals? Surely it should have fallen back to old shading when there are no normals? Because that was the actual previous appearence. This is obvious.

Key point:
> A lack of normals is not "faulty mods", it can be a choice. All art until now was made with the lack of shading in mind.

The shading feature, because it is forced, has altered, and therefore in many cases broken, the appearence of meshes.
This is why there should either be a choice, as a new object property, or broken normals should make the appearence fall back to old flat shading.
So that, if meshes have broken normals, they will appear as before for unchanged and unbroken appearance, and if the modder wishes to have the new shading they can then fix the normals.

I disagree with dcbrown's attitude in #9374 , which i guess is why #10000 turned out the way it did. It did not address the complaint at all. Sorry i did not realise earlier and complained.
Quote https://github.com/minetest/minetest/pull/9374#issuecomment-639015113
> And btw, if you don't like the shading you have several options to disable it:
set normals in your models to 0

(the other 'options' to disable it were not valid)

A modder should not have to reset broken normals to zero to avoid the breakage of an intended appearance. It should be those who want a change to shaded meshes that have to fix their normals.

So i am re-adding this to milestone and i think it is possibly a blocker too.

**Comment by paramat** [comment]
Seems falling back to old shading was the original request and original intention:
Question:
https://github.com/minetest/minetest/pull/9374#issuecomment-587086837
> Is it possible to detect the absence of normals and do the old flat shading in that case?

Answer:
https://github.com/minetest/minetest/pull/9374#issuecomment-587112256
> Best we can do is to check if normals have length. In that case it's easy to fallback to old shading.

**Comment by paramat** [comment]
Is it the case that the 'old shading' is an implementation that has been removed, such that the only choice now is either new mesh shading or absolutely flat shading (which is also different to the old shading)?
If so, i am not sure what is best to fallback to.

**Comment by sfan5** [comment]
> So, #10000 forces shading when there are broken normals? 

Yes, the PR recalculates normals if it detects them to be broken, so that shading can work correctly.

> Surely it should have fallen back to old shading when there are broken normals? Because that was the actual previous appearance. This is obvious.

The aim was to fix the black patches on models with broken normals, hence why #10000 is just a partial fix. An option to get old shading back could be added later (or already exists, see below).
Automatically fixing normals also has the advantage that mods do not need to be updated to make use of the new shading (which is a net improvement).

> A modder should not have to reset broken normals to zero to avoid the breakage of an intended appearance.

Why not?
Assuming "broken normals -> old shading" won't happen, setting an object property vs. setting model normals to zero are both valid ways to get back the old behaviour.
In fact as the comment you quoted says, the latter way already works _right now_.

> Is it the case that the 'old shading' is an implementation that has been removed (and would be complex and code bloat to keep alongside) [...]?

The "old" code still exists for people with `enable_shaders = false`, so I don't expect that to be a problem.

**Comment by dcbrwn** [comment]
I think that for minetest to stop look miserable, flat shading should be enabled by default and the object property that disables it should be set intentionally. This way modders will be forced to update their assets. Otherwise we are stuck with poorly made meshes and this really messes up impression about the game. For the cases @hecktest mentioned shading is actually still pretty much required, it's just different kind, "toon" shading. So probably custom shaders is a better option. But it opens up opportunity for modders not just kill the appearance and aesthetics (like with high-poly models, which should be discouraged IMO), but also potentially hurt performance a lot.

**Comment by dcbrwn** [comment]
@paramat 

> (the other 'options' to disable it were not reasonable)

Disabling shaders at all actually brings rendering back to the point where shading wasn't a thing. Before #9374 meshes used some kind of basic shader that wasn't even tone-mapped, it didn't support parallax effects, etc. So enabling shaders then, resulted in even more bizzare ugly-looking image than one can get now by disabling shaders.

**Comment by paramat** [comment]
sfan5, good points.
> This way modders will be forced to update their assets. Otherwise we are stuck with poorly made meshes

Good point.
> For the cases @hecktest mentioned shading is actually still pretty much required, it's just different kind, "toon" shading

Not sure about that, they were specifically requesting no shading at all, because the shading is already present in the model skin.

Anyway, a complex subject, best i stay neutral for now while i do ot completely understand it all =)

**Comment by dcbrwn** [comment]
>  they were specifically requesting no shading at all

And that's a shame! :D Here's how toon shaded model can look like. Notice that some kind of shading is already backed into texture.

![toon_example](https://user-images.githubusercontent.com/12214069/84459105-48be4d80-ac6f-11ea-8fdc-481a52d2d326.png)

With all that being said, the option to disable or tune shading model is still desirable.

**Comment by hecktest** [comment]
If you paid closer attention, you'd notice that I've already written a shader like that to make this situation more bearable.
![shader](https://user-images.githubusercontent.com/42101236/84478864-49b4a680-ac92-11ea-9646-4979cd593a39.png)
But I can't use it until server sent shaders are a thing. So until then, shading off.

And in case you don't realize just how bad the current diffuse shader looks:
![lambert](https://user-images.githubusercontent.com/42101236/84479444-40780980-ac93-11ea-924d-64b318ab26d7.png)
_yuck_

**Comment by dcbrwn** [comment]
> But I can't use it until server sent shaders are a thing.

So make it a thing. Open up a PR, deliver it to the stable version, fix new bugs and revealed old ones. I'm sure it will be useful, and most of the modern hardware can handle basic shading easily.

There is also a problem with minetest's rendering pipeline that it doesn't have post-processing stage. Well it does have it for 3D VR things, but it still can be improved, so that entity/node shading can be simplified and sped up.

Or maybe setting up rendering pipeline, able to generate shadowmaps. Doing this in a reasonable sized PR would be also a great deal, since this opens up a world of dynamic shadows. Only requirement IMO is that this must be done surgically as non-invasive as possible, or it will take ages for PR to be adequately tested and merged.

So there is a plenty of room for small manageable improvements. Take a responsibility and make it happen.

**Comment by hecktest** [comment]
You might want to take a look at #9907 and #9895, this is already being made. But it won't be here for a while yet.

I would not recommend pursuing shadowmaps right now, not until the rendering is optimized to handle almost twice the load that shadows would generate.

Taking responsibility means fixing bugs before making features.

**Comment by paramat** [comment]
So personally i am now neutral about this issue being removed from the 5.3.0 milestone. hecktest, do you feel strongly that something still needs to be done before 5.3.0 release? Feature freeze is in 1 day, bugfixes are allowed over the next 1-2 weeks before release.
Is setting your normals to 0 or disabling shaders a practical solution for you, for 5.3.0?

I find hecktest's player model looks better with no shading, even though the world is shaded. Maybe this is an anime fan taste (i love anime).

**Comment by dcbrwn** [comment]
@paramat take a look at #10033. It's quite small and probably can get into stable before the release.

**Comment by hecktest** [comment]
Yes, entities currently look like garbage. Adding a way to turn off this disaster should count as a bug fix. I can't go live with a server in this state, and who knows when 5.4.0 will be. I cannot work around this because the normals will just be forcibly generated now, and it never worked for .x models anyway. Disabling shaders is not an option because the client has to do it. I can already imagine: "We're sorry if the game looks like crap, please turn off your shaders and restart, h-haha..." Besides, the textures are tuned for tonemapping (another client option I can't control) and without shaders they will look wrong.

The reason the unshaded version looks better to you is because it is better. I'd say even Minetest Sam looks better unshaded, for the same reasons; diffuse shading multiplied with a single texture is mathematically equivalent to painted cardboard, and looks like it.
Without shading, what you draw is what you get, so you can make up for the lack of hardware effects by painting everything on. Shading without programmable shaders puts you into this uncanny valley of suck where you can no longer fake an effect by painting it, and you can't do it properly with math either.

**Comment by sfan5** [comment]
> I cannot zero out normals to work around this because the normals will just be forcibly generated now

I was going to say that this is incorrect, but it's not. A side effect of #10000 is that setting normals to zero is no longer possible.
@dcbrwn is this intentional?

**Comment by dcbrwn** [comment]
@sfan5 yes. I proposed setting normals to 0 before we made a PR where we recalculate normals and consider ones with near 0 length as invalid.

**Comment by dcbrwn** [comment]
"disaster"

![изображение](https://user-images.githubusercontent.com/12214069/84568272-da6cae80-ad86-11ea-8eca-ae708486bc57.png)

**Comment by hecktest** [comment]
So the existence of beginner art justifies breaking the rest?
It still looks worse shaded. The "lights" are no longer as bright as they should. They now look painted on. The vibrant yellow paint now looks like puke. There are gradients in places where they shouldn't be. There are no shadows, so places that shouldn't be brighter than their surroundings now are. Even your strawman example is shaky. It's also the very definition of a solution looking for a problem.

I've already explained in every way why the shading is bad, and provided examples. Even in the 90s, when this was the only kind of shading available, smart developers avoided it altogether, instead baking light into vertex color or the texture. It only sort-of works for really gritty and dirty kind of art like in Quake. Even then, light sources were usually more sophisticated than a global directional light, which is something that nobody does.

You're trying to argue with someone who has made game art in every possible style from unlit to PBR, animated it all, and also wrote shaders for it. I also paint in spare time. Stop before you embarrass yourself further. You also piss me off, treating me like some clueless complainer who needs your help to "see the light", acting like I don't even know what a toon shader is, never mind that I can't use one right now. Not like one written by you would look any good either.

#9907 is the correct solution if you're really bothered by the old shader, not an opinionated change like this. I call it a disaster because it was a very thoughtless change.

**Comment by Df458** [comment]
> So the existence of beginner art justifies breaking the rest?

I don't see anyone making this argument, especially given the existence of a PR to reinstate the old behavior that you want.

I am fellow artist who's been watching this argument for the past week or two from afar, and frankly you look like you're having a pretty dramatic overreaction. Most of your critiques of the above image are fairly weak at best, and can be improved upon with future PRs.

Baking shading is a valid option, one that I also choose to use, but given your experience you yourself should be aware of how very limited it is. Furthermore, the vast majority of existing content for Minetest does not take this approach, and from my experience modders are generally unwilling or unable to sit down and improve their graphics. Your suggestion of custom shaders also puts the onus on the modder, basically ensuring that it will almost never actually be used. Seriously, I can't personally convince modders to fix basic shit like broken randomly overlapping uvs, *and you want to make them write custom light shaders?*

I understand the frustration of having your art direction thrown in the toilet by a graphical change you weren't wanting or expecting. However, the fact that you're still railing against this change even after #10033's introduction is a bit much. Just because **you** don't want something and think it's ugly doesn't mean most people think the same way, and right now it feels like you're trying to remove a genuine step in the right direction because it doesn't suit the goals of your personal unreleased project.

**Comment by dcbrwn** [comment]
@hecktest I didn't mind to place myself above you or anyone and didn't at all assumed any level of skills of knowledge you do or do not have. All I tried to say multiple times is that if you see a problem and have an ability to fix it - do it. Instead of writing walls of text, you would be better of making #10033 or helping with testing of other related PRs.

**Comment by hecktest** [comment]
This isn't a step in the right direction, anyone could've written this crap shader by following a beginner GLSL tutorial.
#9907 is the right direction, so that someone's terrible taste can be confined to his own server only, instead of infecting the whole engine. People could share shaders, so saying that a custom shader feature would never be used, is akin to stating that @dcbrwn's rubbish is the best that the Minetest community can come up with.
The only thing I'm railing against is @dcbrwn being a smug prick even after he cleaned up after himself, making posts like the one with the train. He's salty because I don't like his pet "feature". The amount of white knighting here is off the charts.

**Comment by dcbrwn** [comment]
The shader is not mine, the feature is not mine. Only thing I did and will continue doing is to support it and fix bugs related to it.

**Comment by dcbrwn** [comment]
@hecktest if all this is just personal, then I apologize for all and especially my first comment in this conversation. I don't consider this shader/feature as a pinnacle of engineering, and I'm not exactly the author. I just extracted it from previous PRs, support it and fix bugs in the process. It's in fact just a copy of a shader applied to nodes/blocks rendered in the map. It's basic and it's okay, since this is how minetest looks like. And applying same math for entities is done just to make overall look consistent.

**Comment by sfan5** [comment]
@hecktest I think you should give a few thoughts towards your style of discussion. Personal insults and claims of "white knighting" or "shooting the messenger" when contrary opinions appear are not productive, do not lead to any conclusions and result in an immediate defensive stance of the other party even if they are willing to discuss.

**Comment by paramat** [comment]
#10033 merged. hecktest are you happy to close this now?

**Comment by hecktest** [comment]
yes
