### ISSUE TITLE
Modularize minetest development in order to reduce complexity

### ISSUE THREAD

**Issue by mercorii** [minetest/minetest#9989]
# Short version

Split minetest into smaller more modular pieces in order to reduce complexity. This could be done for both code and discussion. Or just one of them.

_(When I talk about splitting the code, I only mean internal splitting of code into different libraries and repositories. The final deliverable would still stay the same. The modularization is only proposed for reducing complexity.)_

**Two ways to split:**

1. discussions - create text-only repositories for different discussion topics (brand, community, design, moonshot feature requests). Make these RFC repositories, so that explicit desicions could be made in them. Minetest/minetest would no longer be spammed with discussion that should reside in these repositories.
2. modularize engine into multiple modules placed in their own repositories - related issues and PRs would naturally follow to those repositories.

The complexity of all the repositories would reduce because of the modularization.

The first step of the code modularization process would be to convert the repository into a monorepo. This process could happen as slowly as needed - bit by bit. With time, small parts of the code could be modularized and moved under the monorepo parts of the repository. When larger separated modules would be managed to separate from the rest of the code, they could be split into new repositories.

**This would have two effects:**

1. New repositories would split discussion (issues) and code contributions (PRs) into internally less complex smaller repositories
2. It would become easier for specialists and new contributors to contribute, as the required information would reduce.

**RFC process for reducing non-mergeable PRs**

Additionally, I propose taking RFC process into use for the engine repository. In this scenario RFCs would limit non-mergeable PRs in minetest/minetest. The RFCs would reside in a different repository. The benefit of the second repository would follow the above logic - the discussion in central engine repository would be reduced to implementation details only.

All these proposed changes combined would reduce the discussion happening inside this repository, and make the repository less complex.

---

This became a longer text. You can stop reading here, or read the proposal in more detail below.

That being said, this is an important topic and would benefit from thorough evaluation. The complexity is not going anywhere by itself.

---

# Long version

## Problem

Minetest is a popular project.

Due to the popularity, minetest's repository is flooded with issues and PRs. There is a lot of good quality content in the issues and PRs, but not enough time or hands to fully embrace it all.

All the issues are mixed together in one big bowl. This is a large project that due to lack of proper channels must also handle a lot of non-code related development discussion.

Additionally, due to the complexity of the project, the bar on contributing is high. In order to fully participate in the development, you need to know a lot about different parts of the project. You need to be a jack-of-all-trades. All the aces of design, storytelling, media sector, game design, to name a few, are having a hard time to contribute, because they lack knowledge on other fields.

All in all this repository is complex, in both code and discussion.

## Current solution

I've understood the current solution to mitigate the number of issues and PRs has been just to try and cope with the number of open issues and PRs, and to close them when possible. While this might work at the moment, it is largely only mitigation of the damage, and does not tackle the actual problem.

There's been discussion about this in earlier issues, but on the ones I've read through, there hasn't been many proper solutions widely discussed. Most of the solutions that I'm proposing here have been discussed earlier briefly, or at least by term in different issues.

What I try to write here in length is argumentation why these solutions should be considered.

## Alternative solution

It would be important to tackle the problem itself - the complexity of the minetest project - instead of just trying to cope with it. 

This could be done by splitting the project into smaller submodules, for both code and discussion.

The main benefit would be that old and new issues and PRs that currently reside in minetest/minetest would be moved into different, newly created, specialized repositories. 

It would be easier to keep the numbers of issues and PRs smaller, as the internal complexity of these new repositories would be lower.

Additionally, it would make it easier for new contributors to join development on areas where they are already familiar with, without having to know everything about the whole project.

**It would be possible to do the modularization in two parts:**

1. **Create new text-only repositories for issues that are not strictly related to the core engine development.** This would mean feature requests, design talk, branding, community management, etc. A special case would be engine design.
2. **Modularize minetest code base into multiple different separate modules.** Create new repositories for each one, so that relevant issues and PRs can be moved into those repositories.

**Benefits in short:**

- Text-only repositories could be used to move non-engine related issues from minetest/minetest into different avenues for different topics. This would also move parts of the contributor base into those repositories. With tighter topics, specialized discussion would have better opportunities than they currently have. Additionally, non-engine related issues would no longer drown engine related tickets in minetest/minetest.

- A text-only repository for engine design could be created, that would be based on using RFCs (Request For Comments) to validate ideas before implementation. They way RFCs could be used, would go as follows: until an RFC is accepted, a PR would not be able to be merged. Meaning, it would be pointless to create PRs unless there was an RFC already very close to validation. If PR would be created before an RFC would be accepted, that PR could be temporarily closed, as it would be referenced in the related RFC PR. This could immediately lead to reduction in the number of new PRs.

- Modularizing the minetest code base into new repositories could be used to reduce the number of issues and PRs in minetest/minetest, as those issues and PRs could be collected in the new repositories next to the relevant modularized parts of the code.

### Why modularize things?

When large chunks are split into smaller modules, dependencies inside the modules become easier to understand, and the amount of knowledge needed for working with the modules becomes smaller.

Modular content means abstraction.

In code, a module doesn't know about the things that are using it, and likewise, the code using the module doesn't know what happens inside that module. Modularization is also about access control. Modules can't poke the internal parts of other modules (or at least they shouldn't, even if a language would allow it). Information hiding only happens on code level - the developers still know what happens on both sides of the module border.

By modularizing discussion, it is also possible to do similar things. Different topics can be discussed in a relative isolation. When other topics need to be discussed, it is still possible, but the topic barriers, known by participants, make it easier to keep the discussion inside the topic.

With modularization, participation in the development of a module no longer requires the full knowledge of the whole system. People can still participate in the development of multiple modules, if they so want, but the barrier becomes lower for new contributors.

Lowering the barrier in this case doesn't mean lowering the quality of contributions. Opposite is true, as it becomes easier to gain better understanding of the smaller, less complex modules.

### Splitting issues into new repos

Given the name of this engine repository (minetest/minetest), for newcomers and alike, it appears to be the central repository of the project. Because of this, it attracts various different types of issues that might not belong here. Given that they don't have a better place, this repository is where they end up.

To remedy this, new non-code repositories could be introduced under the minetest organization.

The topics discussed in this section could also be moved outside github, but that is not recommended. The current external forum is not fully a development focused environment, and splitting development related discussion into multiple places would only add to the confusion.

Text-only repositories under minetest organization would keep the discussion near the development, but still outside the development repositories.

There are multiple ways for moving the discussion away from minetest/minetest into new repositories. There could be only a single new text-only repository, to start with. It could then on a later date be branched into multiple new repositories.

Alternatively, there could be multiple text-only repositories made available from the beginning. The benefit of this would be that it would allow a better place for various very different topics that might not share much common ground.

Possible different discussion divisions (and repositories to create):

- **documentation** - general location for general development documentation that currently has been spread among minetest/minetest, forums, wiki and other possible places. Repository specific documentation should reside in each repository, but any documentation with wider scope, should be brought into a single place. It is possible to generate html pages from this using static site generators ([hugo](https://gohugo.io/), [jekyll](https://jekyllrb.com/), [gatsby](https://www.gatsbyjs.org/), [docusaurus](https://docusaurus.io/))
- **brand** - discussion and handling of any brand related things: logos, marketing, media, PR, etc
- **ux / ui / graphics design** - discussion about different design
- **community** - discussion on how to engage with community - what forums to keep, how to recruit contributors, how to engage with different stakeholders
- **features / moonshots** - place where moonshot ideas could be talked - features that might not be able to be immediately added to engine. These are still important for discussion about the engines future, even if they are not implementable immediately - ones that can be later promoted to be added to the engine.
- something else?

The new text-only repositories could be built around RFCs (Request For Comments), and would contain discussion on relevant sides of minetest. The file structure of such a repository would consist of RFC files. Issues would be used for wider discussion and preparation of RFCs. PRs could be used for fine tuning and creation of RFCs.

RFCs would be beneficial, as they would act as an official archive on decisions made about different actions related to minetest. Issues can also be seen as archives of past decisions, but all the decisisions made in them are usually implicitely declared. As RFCs are only created via merging of PRs, their creation would be explicit decision making.

Later, the upcoming github's "discussions" feature could be used to move discussion away from issues, in these new repositories, and into the new discussion systems of the same repositories. This way issues would work as preparation for RFCs, and discussion would be separate from them, yet they would still happen in the same repository.

Additionally, if a better tool would be found on a later date - let's say, for design discussion, as designers might not feel themselves so comfortable in github - it would be possible to do so.

The guiding philosophy behind this part is that information should be kept as close to where it is used, and where it is expected to be found. Github (or another forge) is largely that place for development discussion.

#### RFC model in (a bit) more detail

RFC is a document declaring a feature or a process, or other design.

While there are multiple processes for creating RFCs, in this proposal RFCs are made via a PR in a dedicated repository. The PR is only merged when the RFC has been accepted. Until then, it will be fine tuned inside that PR. If no agreement can be found, the RFC may be discarded.

Before the PR is made, there can be a lengthy discussion in issues in preparation of creating the RFC.

RFC is a design tool, used for defining a design for a feature, and validating and finally accepting that design. It can be used to gate keep any implementations. If there is no RFC and thus valid design, there should be nothing to implement.

Use of RFCs should help reduce the number of non-merge-ready PRs.

### Splitting engine development (code and discussion) into new repos

There are two different use cases for splitting engine development into multiple repositories:

1. RFC repository for engine development - this is different from other text-only repositories as it would be directly be related to current minetest/minetest repository development - as a design tool for validating PR features
2. Splitting different parts of the minetest engine and application into new repositories

The former would reduce the amount of new PRs, while the latter would reduce issues and PRs in the main engine repository (this repository), and move them into better suited, less complex repositories.

#### Using RFCs in engine development

A new process could be introduced for approving PRs into minetest/minetest, in the form of RFCs.

Any larger PR to minetest/minetest would need to have an RFC created for it, before it could be merged to minetest/minetest. This would immediately reduce the number of new PRs. Any existing PRs could be grandfathered in, and be considered mergeable even without RFC, if they would be deemed to be properly thought out and to be considered important to require this special status. Other existing PRs that would not have full dev team support, could be required to create an RFC just like any new PRs. They could be closed while the RFC is in the making, and reopened when the RFC would be accepted.

Additionally, it would stop development of unneccessary PRs, prior to accepting the need for the new features (in the form of the RFC).

This would be a win-win situation for all parties involved. Contributors wouldn't need to write code until they would know that they have a good chance of getting their code to be merged, and the core team wouldn't need to review implementations prior to accepting that the feature is needed and is properly designed.

#### Splitting engine code into new repositories

*I don't have much knowledge about the current state of the code base, and thus possibilites of actually breaking this engine code base into modular parts, due to my currently lacking c++ and lua skills, but bear with me a bit further. If you don't like this part, remember that there are proposed changes also above that could be implemented independently of this part.*

As far as I've understood, there are multiple conceptually separate parts inside the minetest engine, in theory. In implementation, the separation might not be as clear. Building this separation should be a core priority, as it would help reduce the complexity.

Some of the parts could be modularized, and moved into separate repositories. With the modularized code, also the relevant issues, discussion and PRs could be moved from minetest/minetest into the new repository. This is the primary reason why I recommend splitting the project into multiple separate repositories. If the number of PRs and issues weren't so large, I would just recommend slowly changing the repository into a monorepo, and keeping everything together.

By abstracting different parts into modules, that reside in separate repositories, it will make it clearer for the people participating in the discussion about those modules, where the module's boundaries are, and what discussion belongs where.

**How then could the engine split be done?**

1. Convert the repository into a modularized monorepo
2. Start moving large modularized subprojects outside the repository

**Monorepo it**

The first step would be to make this repository into a monorepo.

This repository is very complex. There are a lot of large files. The folder structure is very flat, implying that different parts of the code might not be properly separated from each other.

These files would first need to be broken into smaller files, and then grouped inside the monorepo into separate modular subprojects.

Any new features should be implemented in new modularized subprojects.

**Splitting of the repository**

After this modularization process would be started, larger parts could be moved to separate repositories, as they would be unentangled from the rest of the code.

What parts then could be moved into new repositories?

There has been earlier discussion about introducing a middle layer between the irrlicht engine and the minetest engine. Additionally, another opportunity might be found separating the engine from the actual application that launches the games.

Regardless of the modularization, the different parts could, and should, still be developed to be delivered together, similarly to how it is now done. The aim is not to mindlessly chop minetest into parts, but to make it easier to develop. Easier to get new contributors at a level they can contribute to various parts of the code.

Possible (naive) splitting points (possibilities for new repos):

1. **middle layer between irrlicht and minetest engine** - there's been talks about this before
2. **application split from minetest engine** - the user interface that player interacts with, before they join a server or start a game. There might be an opportunity for splitting mobile app and server app as well. Also something that has been discussed before.
3. **client vs server vs core**
4. **gui** - so that is easy to swap away from the old implementation at later date - or put it in maintenance mode
5. **chat**
6. something else?

Alternatively, to get the process going, the splits wouldn't need to be immediate code base separations. Instead new repos could be created early on, and as a first step all relevant new discussion could be moved to these new repositories.

Any new features that would be added to one of the areas that would be decided to be split off, would be made to happen through the newly created middlewares. Slowly, the old functionality could be moved to happen also through the middleware, and finally when all the parts of the module would be fully separated from other code, the module's code could be moved to the new repository.

**Benefits of splitting different parts**

1. Creating a middleware between minetest engine and irrlicht would allow switching to new graphics engine on a later date, if that would be needed. Additionally it would make it easier to switch to a different irrlicht fork.
2. Benefits of splitting engine from the application would mean that the application could have releases independently of the engine. Menus could be updated, app protocols added, player visible menu content changed, all without needing to wait that the engine is ready to be updated.

## Conclusion

Modularization would make it possible to share the burden of the project management with larger specialized contributor groups. This could hopefully lead to more time being left available for actual development and other more fun things.

I think this project is awesome, and there are some very skilled devs, contributors and community members involved.

This is a complex project, and it appears that it has been that way for a while already.

The project will only become more complicated by every new PR that gets merged. Similarly, the increasing popularity of the project will only increase the amount of discussion happening in this repository. Modularization could remedy the negative sides in both cases.

**Comment by Zughy** [comment]
I don't know if this is possible, but as someone who started developing on Minetest just recently, it'd be awesome to have things more compartmentalised: trying understanding the code is pure suffering at the moment

**Comment by Df458** [comment]
Modularizing code is a worthy goal, I think, and we should definitely do it.

I'm a little worried about 'policy' type decisions and discussions getting squirreled away in separate repos though, I feel like that might wind up hiding important decisions from users and new devs.

**Comment by mercorii** [comment]
> I'm a little worried about 'policy' type decisions and discussions getting squirreled away in separate repos though, I feel like that might wind up hiding important decisions from users and new devs.

That is a good point. This kind of information is only useful, if it is accessible, and easy to find.

On the other hand, github is very linkable. You can link to files, rows, issues, prs, comments and review notes. So it is very easy to reference things in github. Github even prettifies automatically internal links.

**Comment by mercorii** [comment]
> I'm a little worried about 'policy' type decisions and discussions getting squirreled away in separate repos though, I feel like that might wind up hiding important decisions from users and new devs.

Additionally, in a scenario where RFCs would be used for decision making, it would be possible to use CI, to run a static site generator when an PR modifying an RFC would be merged. If RFCs would be in a format like markdown, it would be easy to create web pages from them.

This way it would be possible to make the RFCs accessible also for people who are not familiar with github or git. Such stakeholders could be designers, translators, etc.

**Comment by SmallJoker** [comment]
Thanks for providing a short version.

There is currently not enough core dev activity to maintain anything beyond this repository. Like issues here, RFCs might end up in the same long discussions, without much benefit.

Do you have an exemplary project where RFCs are proposed and discussed? Would be interesting to see their workflow.
After months (or years?), getting more core devs - and with them activity - into the boat is still an open task. Your suggestions are reasonable but the team is currently quite small to justify splitting the code base even remotely.

**Comment by mercorii** [comment]
> Thanks for providing a short version.

Yeah, it got bigger than I intended. It would have been hard to read it, without there being a shorter version spreading out the main ideas.

This unfortunately got a bit long as well :grimacing: I had to cut the second part with the actual RFC links into a second comment.

> There is currently not enough core dev activity to maintain anything beyond this repository. Like issues here, RFCs might end up in the same long discussions, without much benefit.

The RFC process is quite a powerful tool. It's kind of a gate keeper. But it is also very transparent, because RFCs are readable by everyone. 

Then there's the whole thing that RFCs are a relatively clearly defined process. There are certain expectations on the outcomes, that normal issues might not have. Because of the clear outcome, it pushes for actually designing the implementation from multiple perspectives, and requires putting those perspectives down in the writing for everyone to see. Issues are usually more informal, and the expectations are not as well shared between participants, which can lead to pushing the ball back and forth, without actual progress happening.

### RFCs are important for technical process

The RFC process would be most important for the technical RFCs. Specifically the main RFC repository would be important for this repository. 

The secondary technical RFC repository for moonshot features and ideas would be less important for actual development. It could possibly have more freedom, as it would not be as important for the daily development of the engine. The moonshot repository could possibly act as an ventilation / exhaustion system for ideas that are not as properly thought out as they possibly would need to be for immediate implementation in engine. It would give people possibility to go wilder with ideas, without it affecting engine development as much as if those ideas would be voiced among the more important discussion.

### For less technical discussion RFCs can act as control mechanism

For the less technical discussion, the RFCs would have a different use case. More important would be to move those discussions outside this repository. 

This would have two benefits:

* It would make the non-technical discussion (such as on community, brand and design) more important, as it would have it's own space
* The non-technical discussion would not be taking space from technical discussion, as they would no longer share the same space.

The benefit of RFC in non-technical repositories would be that any other discussion in those repositories would be informal, and that only accepted RFCs would be valid. 

Those repositories then would possibly not need as strict overseeing than the technical discussion in technical repositories. Although, regular moderation would be needed still, but that doesn't mean that there would be less need for moderation if the same discussion would happen in this repository.

**Comment by mercorii** [comment]
> Do you have an exemplary project where RFCs are proposed and discussed? Would be interesting to see their workflow.
After months (or years?), getting more core devs - and with them activity - into the boat is still an open task. Your suggestions are reasonable but the team is currently quite small to justify splitting the code base even remotely.

I'll be glad to share links.

## A good place to start

### Rust language

Rust language has a prolific RFC repository, that is central to the language development.

Rust has a good, short documentation about their own RFC system in their static site generated from the repository. It's a good place to learn how they do it, and to take inspiration on what you can do with an RFC system.

There are a lots of RFCs that have gone through their process.

**Links:**

- https://github.com/rust-lang/rfcs - repository
- https://rust-lang.github.io/rfcs/ - same repository, but as a static site, generated from the readme and RFCs

## Interesting use case

### OBS Project

OBS project has a relatively lately adopted the system.

OBS is a tool for editing streams. It's mostly used by streamers to modify their stream sources and adding overlays and the like.

The reason I'm referencing them here, is that their RFC process came to rescue at a time when they got a large amount of extra publicity at the beginning of pandemic. People realized that there are improvements crucially needed for remote meetings, in this case modifying the camera feed that was passed to skype and the like, and also saw that OBS could be a possible solution. Then someone threw in a bounty for creating a virtual camera output for OBS, allowing OBS to modify camera feed in teleconferencing. If there wouldn't have been the RFC process, there would have been many competing, possibly not so great implementations of the virtual camera output hitting their PR system at the same time. Thanks to the RFC process, they managed to keep the quality high, and control the situation.

- https://github.com/obsproject/rfcs - Their RFC repository

So far they have only pushed one RFC through, but it was the one that got all that attention in the developer world due to the pandemic and the bounty. Even though they only have a single accepted RFC, they have many more under work. 

Had they not had the RFC process, I think the situation would have turned into a way bigger mess than what actually happened. They were also quite strict on the RFC process, which allowed them to keep the control.

The issue+PR related to that RFC is actually a pretty good read on the benefits of RFC process, and on how they managed to keep the thing in control. It starts with a bounty issue, follows in an RFC PR, with a final deliverable being the RFC. The actual implementation is still partly under work, as they target multiple APIs in different OSs.

- https://github.com/obsproject/obs-studio/issues/2568 - bounty issue that draw the interest of wider audiences. It got attention both because of bounty but also, because virtual camera output for OBS was something that became useful when everyone suddenly started using teleconferencing en masse.
- https://github.com/obsproject/rfcs/pull/15 - the related PR
- https://github.com/obsproject/rfcs/blob/master/accepted/0015-virtual-camera-support.md - the final RFC - not that special in itself if there wouldn't been the attention. Still, it's a good RFC that takes multiple different perspectives on the implementation.

## Other RFC processes and projects using RFC

### Reactjs RFCs

A javascript frontend library/framework.

Has a good documentation in the readme.

- https://github.com/reactjs/rfcs

### NPM RFCs

Package manager for javascript, recently bought buy github.

Alo has a good documentation in the readme.

- https://github.com/npm/rfcs

### IETF RFCs

Then there's the grand old lady - IETF and its RFCs.

It's sometimes a bit more formal system, but [not always](https://tools.ietf.org/html/rfc7168). I'm mentioning it mostly for historic reasons and the more formal system.

- https://ietf.org/standards/rfcs/

**Comment by rubenwardy** [comment]
Also see: [There are too many PRs](https://forum.minetest.net/viewtopic.php?f=3&t=24629)

I think the number of issues and PRs in the repo indicates an issue with processes and number of reviewers, and won't be solved by _artificially_ dividing the code into multiple repositories. GitHub's issue tracker sucks a bit for prioritising and managing issues, every so often I go through and find loads of duplicates. Something like BugZilla might be better, it allows categorising by subsystem and component

I think the PR and issue reviews are slow because time is wasted on things like code style review rather than code review and testing, see: #9731. This combined with a lack of active reviewers

Relatively few of our issues are RFC-like, perhaps this is a bad thing. The main ones we have on this issue tracker relate to larger changes like #6733 #6527 or refactor/process suggestions like this issue and #9358. Some thought of the overall design would be good, but I worry that this will take up even more of our time. The projects you mention are much larger than Minetest, and so have a greater need for formal processes like RFC. What benefit is there to doing RFCs outside of an issue? Focus on a solution?

**Comment by paramat** [comment]
This seems a lot of work and disruption, and a bad idea, i think you are wrong about the benefits and misunderstand the actual problems of development.

Issues are already divided and managed by labels, labels allow division and filtering in many combinations of ways, instead of only one fixed division that would occur by modularising.

Modularizing MT code adds the complexity needed to make the modules work together.
It is wrong to focus on each module and claim that complexity will fall, because the complexity of MT as a whole will actually rise, which is what matters.
In fact, each subsection of MT will not become less complex, how can it? It still has to do the same things.
Modularisation will inevitably reduce the effectiveness of the code because it has to now cope with the complexity and limitations of modularisation.
Modularisation will add more chances for bugs and problems to occur, and increase workload.
It is always better to work on code in a wholistic way.

I disagree modularisation will help contributors. Contributors can already work on one part of MT without needing to be good at all parts. I think you are wrong that contributors have to be somewhat good at all parts to contribute.

:-1:

**Comment by mercorii** [comment]
> ...won't be solved by artificially dividing the code into multiple repositories.

I think there's an actual need for dividing the project into smaller pieces. The only thing artificial would be to split the project into multiple repositories, and on even that I'm not sure how artificial the need is. 

There's an actual need for creating repositories, or other professional level working environments, for discussing non-technical things related to minetest (design, community engagement, brand, to name a few). Currently they appear to take place in this repository, in contentdb repository, in site repository, at forums, and other places. That kind of discussion should be brought into a single place. Forums is not a professional place in that sense, as hopping to different parts of forums is very easy, and there are many existing use cases for the forums currently. A repository on the other hand is a discreet unit, and very transparent.

Back on the concept of code repositories, in a general case, I personally prefer just doing modularization with monorepos, where you have many small projects in separate packages, inside a single repository. It makes everything so much easier to maintain, when you don't have to touch the parts that are working, and you get to put your time on fixing the actual problems and adding features on those modules that require work. 

Minetest could do with more modularity, whether it is in the form of monorepo or multiple repositories,

In a large non-modular project, it is hard to keep track what parts of the code are connected. With separate modules, its way harder to add unwanted tangles between two different modules, without the connections becoming explicit.

>  What benefit is there to doing RFCs outside of an issue? Focus on a solution?

I tried to write this in the previous comments, but like you said, basically RFC has a specific outcome that you try to achieve. It is basically a design document, one that can be written collaboratively.

Issue is more like a discussion. Issue is for searching problems (and solutions), and gathering information, where as RFC is for designing a solution, and writing down how to do things.

There is usually only implicit decision making happening in issues, whereas with RFC you get an explicit decision as an outcome. Because the outcome is explicit, everyone has a better idea on what steps to follow. 

Also, with RFCs you get a small summary of all the wisdom that was gathered in the preceding issues and PRs. To keep up, it's enough to read only the RFCs.

**Comment by rubenwardy** [comment]
At my work, we do Architecture Decision Records where we document why a particular architecture decision was made. There's also Downselection Documents for library/technology choices. I guess RFCs perform a similar purpose once selected

**Comment by KaylebJay** [comment]
Quite strongly against anything like this. I like all the discussion in one place. Spreading everything out is not going to do what you say:

> Modularization would make it possible to share the burden of the project management with larger specialized contributor groups. This could hopefully lead to more time being left available for actual development and other more fun things.

Modularization makes it more confusing for everyone involved and does not automagically give developers more time. This is a false narrative. 

> discussions - create text-only repositories for different discussion topics (brand, community, design, moonshot feature requests). Make these RFC repositories, so that explicit desicions could be made in them. Minetest/minetest would no longer be spammed with discussion that should reside in these repositories.

We have the forums. We discuss most things there. Minetest/minetest is not spammed with discussion at all - if this is true, this discussion should be closed right now because it is much too spammed with discussion ;)

> Due to the popularity, minetest's repository is flooded with issues and PRs. There is a lot of good quality content in the issues and PRs, but not enough time or hands to fully embrace it all.

Ummm, splitting them up means there are the *exact* same number of issues and PRs and the *exact* same number of developers with the *exact* same amount of time on their hands. I'm not sure where you see these Bitcoins flying from :D

> Modularize minetest code base into multiple different separate modules. Create new repositories for each one, so that relevant issues and PRs can be moved into those repositories.

Work, work, work, complexity, complexity, complexity. Most professional repositories have just ONE issue-tracker, not 7 different issue-trackers dedicated to random forms of issues. 

> Split minetest into smaller more modular pieces in order to reduce complexity. This could be done for both code and discussion. Or just one of them.

... This does not reduce complexity in any way. Great, all our code is separated now so we have to pull a bunch of different repositories before rebuilding our client. 

Everything you say here points to 'lets break up the community so they have to go to a bunch of different repositories to do different things'. I think the forums for chatter and the issue-tracker for consensus is quite enough, thank you. This is like cutting the Hope Diamond into 6 pieces. :thumbsdown:

**Comment by Wuzzy2** [comment]
FYI: Developer consensus is usually written into dev.minetest.net.

**Comment by mercorii** [comment]
Oh, and good points and counter points in this discussion :+1:

**Comment by hecktest** [comment]
Sounds like a good way to introduce more bureaucracy and slow things down ever harder.

**Comment by RomanHargrave** [comment]
I disagree that a project like minetest would benefit from RFC process - a system which is typically reserved for massive-scale projects (IETF, C++, C, FreeDesktop) where interface stability and stakeholder consensus is of critical (e.g. break-the-internet) importance. As for breaking out the game in to modules, there is likely very little merit in this. Typically, a software engineer makes the choice to isolate functionality when they intend make available separately certain functionality. Minetest is not intended to provide a set of libraries for building games - that's what projects like Irrlicht are for. Minetest is intended as a runtime environment and game engine for building first-person voxel games. There would be very little point in trying to disentangle code within minetest from other code _within minetest_ because it is effectively all part of the same codebase and has a single intention and purpose.

The reason that RFC systems reduce workload (insofar as handling incoming RFCs) is that they raise the bar for participation. They are also very attractive to working groups that originate in corporate structure and culture, as the bureaucratic 

In the case of what is a very promising opensource platform for building this type of game, doing something like this would kill the project.

**Comment by RomanHargrave** [comment]
I disagree that a project like minetest would benefit from RFC process - a system which is typically reserved for massive-scale projects (IETF, C++, C, FreeDesktop) where interface stability and stakeholder consensus is of critical (e.g. break-the-internet) importance. As for breaking out the game in to modules, there is likely very little merit in this. Typically, a software engineer makes the choice to isolate functionality when they intend make available separately certain functionality. Minetest is not intended to provide a set of libraries for building games - that's what projects like Irrlicht are for. Minetest is intended as a runtime environment and game engine for building first-person voxel games. There would be very little point in trying to disentangle code within minetest from other code _within minetest_ because it is effectively all part of the same functional system.

The reason that RFC systems reduce workload (insofar as handling incoming RFCs) is that they raise the bar for participation. They are also very attractive to working groups that originate in corporate structure and culture, as their bureaucratic nature is compatible with business design and goals. I cannot say that I have encountered overarching RFC systems in the vast majority of community projects I have used or been involved with. I would even go so far as to say that an RFC process is antithetical to the otherwise highly democratic nature of community open-source projects. At the end of the day, (and you said something to this effect when you were talking about OBS' RFC system), RFCs exist to _exert control_ rather than to _share control_.

And RFCs are not some magic recipe for project management success - development of the Linux kernel has been driven exclusively by people submitting patches and arguing on the LKML for more than twenty years at this point. And while there are "RFC" emails, they're still roughly equivalent to a pull request on github rather than a formal document.

When you have a project like React or NPM, both massive corporate-driven efforts with their own ecosystems, people don't necessarily have the option of just forking your code and taking the community with them when they get fed up. On a smaller scale, I can guarantee you that this will absolutely happen. Look at Subsonic - when Subsonic decided to discontinue open-source development, the fork that picked up the most contributors was Libresonic. After a few months, it came to pass that the person running the Libresonic fork did not see eye to eye with the vast majority of participants. This is how we got Airsonic, which - to the best of my knowledge - is the current majorly active Subsonic fork.

P.S. - I would shy away from using NPM as an example of project management. This tool seems to have generated the vast majority of "open-source drama" over the past several years. Be it due to complete lack of oversight and standards for what gets published (and who published it), what gets _un_-published, or (more recently) whether you're allowed to print hundred-line-long post install messages nagging people for attention or money (a feature that I have never seen in any other dependency management tool).

Apologies for any apparently disjointed rambling, I was in the middle of something else when I saw this and just had to comment.

**Comment by TheTermos** [comment]
I've been involved in a modularized project, and it's been a mess, any apparent reduction of complexity in modules is offset by increase overall. It is sometimes a necessity when you're dealing with huge projests involving hundreds of people, but imo it's inadequate for tiny projects like this one.

What's needed to reduce complexity I'd call code modularity, a recent example:
There's sometimes a need to determine the nodes a box is in, it's been done in several places throughout the code, usually in the dumbest and most bug prone way possible - by choosing one or more points within the box and checking what node it is. That's funny because Lua API implements find_nodes_in_area and does it more or less right, so why isn't there a similar function for use by the engine?

MT code is OO on the surface, but lacks structure internally, individual methods tend to end up as huge shapeless sacks of mostly sequential code. There are no utilities to speak of, so contributors tend to reinvent the wheel and add to the mess with every contribution.

I think reviewers should keep code structure in mind and ask themselves questions like, is it the simplest solution possible, isn't there already a function for that, should some part of it be abstracted into a separate unit of code, is it the right place to do it etc. The next reviewer to step in only to request removing a trailing whitespace should be publicly tarred and feathered as an example.

**Comment by Zughy** [comment]
Two core devs not agreeing and the majority of other participants neither, essentially reporting bad experiences with it. I think it could be closed without problems (as it's tagged with 'Possible close') @paramat

**Comment by paramat** [comment]
Seems disapproved, closing as rejected but feel free to continue discussion here.
